### PR TITLE
Fix the isolated pmix component. Cleanup the ess/singleton component …

### PR DESCRIPTION
**Pull request by rhc54**
…- we shouldn't be automatically discovering the local topology as that is now done on-demand.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit 543c16b28dc0f51eb504cc0cc377c455e30142b6)

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
Fixes https://github.com/open-mpi/ompi/issues/3939

**Comment by hppritcha** [comment]
@rhc54 we could use an alternate view since Jeff won't be back till next week.

**Comment by rhc54** [comment]
Anyone can check it, but FWIW the original reporting user tested it and signed off that it fixes the problem.

**Pull request merged**
