### PR TITLE
io/ompio: next step in code-reorganization

### PR DESCRIPTION
**Pull request by edgargabriel**
- move the sort_iovec operations to fcoll/base
 - move set_view_internal to common/ompio
 - move set_file_default to common/ompio
 - remove io_ompio_sort, not used anymore.

### CODE REVIEW

**Comment by edgargabriel** [comment]
bot:mellanox:retest

**Comment by edgargabriel** [comment]
hm, not sure whether the mellanox failure is related to this commit

--- MCA component coll:hcoll (m4 configuration macro)
00:02:38 checking for MCA component coll:hcoll compile mode... dso
00:02:38 checking hcoll/api/hcoll_api.h usability... yes
00:02:38 checking hcoll/api/hcoll_api.h presence... yes
00:02:38 checking for hcoll/api/hcoll_api.h... yes
00:02:38 looking for library in lib
00:02:38 checking for library containing hcoll_get_version... no
00:02:38 looking for library in lib64
00:02:38 checking for library containing hcoll_get_version... no
00:02:38 configure: error: HCOLL support requested but not found.  Aborting

**Comment by jsquyres** [comment]
@Di0gen @artpol84 @jladd-mlnx Can someone please investigate the Mellanox failure?

**Comment by artpol84** [comment]
@jsquyres ok, we'll take care of this.

**Comment by jsquyres** [comment]
@artpol84 Thanks.

**Comment by edgargabriel** [comment]
I think I'll give it one more shot

bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Pull request merged**
