### PR TITLE
btl: ofi remove FI_MR_PROV_KEY

### PR DESCRIPTION
**Pull request by naughtont3**

### CODE REVIEW

**Comment by wenduwan** [comment]
Running AWS CI

**Comment by hppritcha** [comment]
@janjust could someone from nvidia check out what's going on with nvidia ci?

**Comment by hppritcha** [comment]
@wenduwan someone should check if this change is going to work with EFA provider

**Comment by wenduwan** [comment]
This change broke AWS CI. I need to understand the root cause.

**Comment by hppritcha** [comment]
i think this PR is incorrect for several providers.

**Comment by hppritcha** [comment]
@BrendanCunningham could you check if this works with OPX provider?

**Comment by BrendanCunningham** [comment]
> @BrendanCunningham could you check if this works with OPX provider?

@tmh97 Can you take a look at this?

**Comment by wenduwan** [comment]
I figured the problem with EFA provider is that it requries `FI_MR_PROV_KEY` in mr_mode. Therefore this change effectively disabled EFA in btl/ofi.

That said, it's not clear to me how to get what you want. I need to ask the libfabric community.

**Comment by wenduwan** [comment]
@amirshehataornl @naughtont3 Can you attest to https://github.com/ofiwg/libfabric/issues/9777 ? Is that what you want?

**Comment by j-xiong** [comment]
What is the intention of this change? Does the ofi btl now always wants to supply the mr keys instead of letting the provider choose the key?  If it can work either way the mode bit should remain. Providers that don't require the mode will clear the flag and MPI should check the flag returned from fi_getinfo() to determine how the keys should be supplied.

**Comment by hppritcha** [comment]
i see no evidence this is needed by the CXI provider and since it breaks support for EFA not sure we could consider merging this, certainly not as is.

**Comment by wenduwan** [comment]
Closing PR due to inactivity. Please reopen if you still need it.

**Pull request closed without merging**
