### PR TITLE
Refresh of the datatype engine from Topic/backport 6695

### PR DESCRIPTION
**Pull request by bosilca**
A backport of the datatype improvements on the 4.0.

Few things to mention:
- I had to pull few other commits to solve some of the conflicts, but the changes are minor and mostly necessary anyway. The 2 commits I imported in addition to the original PR are 42119254 and d141bf7912.
- I had to manually alter one of the patches to work around the atomic types added in 000f9eed4 and that have not been yet backported to the stable branch.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by gpaulsen** [comment]
Thanks @bosilca!

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest

**Comment by gpaulsen** [comment]
Fixes: https://github.com/open-mpi/ompi/issues/5540
Master PR: https://github.com/open-mpi/ompi/pull/6695

**Comment by gpaulsen** [comment]
@derbeyn @ggouaillardet Can either of you please review this v4.0.x backport of PR #6695 Please?

**Comment by gpaulsen** [comment]
Hmm.  It won't let me request a review from @derbeyn even though she reviewed the master PR.

**Comment by gpaulsen** [comment]
@ggouaillardet Are you able to review this PR?  Once this goes in, we may be able to create a v4.0.2 rc1.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by gpaulsen** [comment]
@ggouaillardet Can you please review this?  This is the only PR blocking a v4.0.2 rc1 build.
Thanks!

**Comment by derbeyn** [comment]
Sorry for not answering on time, I was on vacation….

Regards


---------------
Nadia Derbey
Extreme Computing - MPI
Phone: +33 (0)4 76 29 77 62
nadia.derbey@atos.net<mailto:nadia.derbey@atos.net>
1, rue de Provence – BP 208
38130 ECHIROLLES Cedex

**Pull request merged**
