### PR TITLE
pmix/pmix112: Update to version 1.2.0

### PR DESCRIPTION
**Pull request by jjhursey**
- Updating the internal version of PMIx to the PMIx 1.2.0 release

### CODE REVIEW

**Comment by jjhursey** [comment]
Note that there is nothing to cherry-pick from OMPI `master` since OMPI `master` embeds the PMI `master` branch.

**Comment by artpol84** [comment]
@karasevb, please verify that this is working well.

**Comment by rhc54** [comment]
FWIW: I have MTT running it now on my cluster - so far, so good. Will post results when done

**Comment by jjhursey** [comment]
Using the internal version things are looking good. I'm looking into some include issue with the `external` component at the moment.

**Comment by rhc54** [comment]
No problems found with the internal version:

```
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                          |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| MPI Install | my installation | 2.0.2a1     | 00:01    | 1    |      |          |      | MPI_Install-my_installation-my_installation-2.0.2a1-my_installation.html |
| Test Build  | trivial         | 2.0.2a1     | 00:01    | 1    |      |          |      | Test_Build-trivial-my_installation-2.0.2a1-my_installation.html          |
| Test Build  | ibm             | 2.0.2a1     | 00:39    | 1    |      |          |      | Test_Build-ibm-my_installation-2.0.2a1-my_installation.html              |
| Test Build  | intel           | 2.0.2a1     | 01:16    | 1    |      |          |      | Test_Build-intel-my_installation-2.0.2a1-my_installation.html            |
| Test Build  | java            | 2.0.2a1     | 00:03    | 1    |      |          |      | Test_Build-java-my_installation-2.0.2a1-my_installation.html             |
| Test Build  | orte            | 2.0.2a1     | 00:00    | 1    |      |          |      | Test_Build-orte-my_installation-2.0.2a1-my_installation.html             |
| Test Build  | oshmem          | 2.0.2a1     | 00:24    | 1    |      |          |      | Test_Build-oshmem-my_installation-2.0.2a1-my_installation.html           |
| Test Run    | trivial         | 2.0.2a1     | 00:05    | 8    |      |          |      | Test_Run-trivial-my_installation-2.0.2a1-my_installation.html            |
| Test Run    | ibm             | 2.0.2a1     | 06:57    | 480  | 3    |          | 3    | Test_Run-ibm-my_installation-2.0.2a1-my_installation.html                |
| Test Run    | spawn           | 2.0.2a1     | 00:07    | 7    |      |          |      | Test_Run-spawn-my_installation-2.0.2a1-my_installation.html              |
| Test Run    | loopspawn       | 2.0.2a1     | 02:35    |      | 1    |          |      | Test_Run-loopspawn-my_installation-2.0.2a1-my_installation.html          |
| Test Run    | intel           | 2.0.2a1     | 14:36    | 474  |      |          | 4    | Test_Run-intel-my_installation-2.0.2a1-my_installation.html              |
| Test Run    | intel_skip      | 2.0.2a1     | 10:18    | 431  |      |          | 47   | Test_Run-intel_skip-my_installation-2.0.2a1-my_installation.html         |
| Test Run    | java            | 2.0.2a1     | 00:01    | 1    |      |          |      | Test_Run-java-my_installation-2.0.2a1-my_installation.html               |
| Test Run    | orte            | 2.0.2a1     | 00:38    | 19   |      |          |      | Test_Run-orte-my_installation-2.0.2a1-my_installation.html               |
| Test Run    | oshmem          | 2.0.2a1     | 17:20    | 255  | 43   | 8        |      | Test_Run-oshmem-my_installation-2.0.2a1-my_installation.html             |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+

```

**Comment by karasevb** [comment]
It works well. And checked with external.
:+1:

**Comment by jjhursey** [comment]
PMIx 1.2.0rc1 is here (in case folks want to try it with the `external` component):
 * https://github.com/pmix/master/releases/tag/v1.2.0rc1

**Comment by jjhursey** [comment]
@jsquyres The commits have been updated.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
I just updated this branch with the v1.2.0rc2:
 * https://github.com/pmix/master/releases/tag/v1.2.0rc2

**Comment by jjhursey** [comment]
I just pushed an updated version that matches the PMIx v1.2.0 release.

**Comment by jjhursey** [comment]
@rhc54 If you have a chance can you review this branch?

**Comment by jjhursey** [comment]
Per discussion on the OMPI teleconf: We might want to wait on pulling this in until we get the PMIx v1.2.1 point release. Alternatively, we could merge this in and I can create another PR for the PMIx v1.2.1 update. Whichever the RMs decide would be better.

**Comment by jsquyres** [comment]
@jjhursey I think it doesn't matter because the end date is going to be the same in both cases, right?  If that's correct, do whichever one is less work.  😄

**Comment by jjhursey** [comment]
It's probably less work to just update this PR with an additional commit once PMIx v1.2.1 is released. I guess the only reason to merge it in sooner would be to get more MTT testing on it.

**Comment by jjhursey** [comment]
Discussion on the OMPI Teleconf. Let's merge this in to get some MTT exposure. I'll open another PR once PMIx v1.2.1 is ready. PMIx v1.2.1 will be a bug fix release.

**Pull request merged**
