### PR TITLE
Pr/oshmem spec1.3

### PR DESCRIPTION
**Pull request by igor-ivanov**
This PR adapt oshmem API to specification v1.3 (http://www.openshmem.org/site/sites/default/site_files/OpenSHMEM-1.3.pdf)

@jladd-mlnx @hppritcha please review and accept

### CODE REVIEW

**Comment by hppritcha** [comment]
Should the ```SHMEM_MINOR_VERSION``` be set to 3 now?  I think @yosefe pointed this out for the PR open-mpi/ompi-release#1073

**Comment by igor-ivanov** [comment]
yes, I will update minor version

**Comment by hppritcha** [comment]
remember to update the minor version number in ompi-release for v2.1

**Comment by jladd-mlnx** [comment]
Per the conversation I had with @hppritcha this morning, will merge into master to let MTT have a look once these smoke tests complete.

**Comment by igor-ivanov** [comment]
@jladd-mlnx @hppritcha @yosefe notice from @yosefe was formed as separate commit https://github.com/open-mpi/ompi/pull/1542/commits/75050b44a2197fbdfa0b0d2e82791025c295f026.
Minor version was not updated because other changes should be done later.

**Comment by jladd-mlnx** [comment]
Roger that, @igor-ivanov. Thanks for all your efforts here.

**Pull request merged**
