### PR TITLE
opal_random_* helpers

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres @thananon 
can you please review this ?

on big endian machines, ```long int``` vs ```int``` might be a big issue if sizes do differ.
ideally, this should land into v2.0.1 ...

**Comment by bwbarrett** [comment]
@ggouaillardet, this is the oldest active PR, and it looks like you have next steps.  Do you still want to do something?

**Comment by thananon** [comment]
I think this PR is outdated.  These changes have been merged with another commit. We can safely close this.

**Comment by rhc54** [comment]
good enough - thanks!

**Pull request closed without merging**
