### PR TITLE
Remove few warnings in libnbc identified by clang-1000.11.45.2

### PR DESCRIPTION
**Pull request by bosilca**
Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/08ad3d3e3294beb73e903b2e288be33a

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b70f3cf221d58db969eb814bb50beb49

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/62e7309a2961457ea600094cf2c722a4

**Comment by jjhursey** [comment]
bot:ibm:retest (CI script broke, should be fixed now)

**Pull request merged**
