### PR TITLE
oob/usock: Protect against possible NULL peer

### PR DESCRIPTION
**Pull request by jjhursey**
* Similar to PR #2833

### CODE REVIEW

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by jjhursey** [comment]
bot:lanl:retest
bot:mellanox:retest

**Comment by jjhursey** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Pull request merged**
