### PR TITLE
3rd-party/prrte: update submodule

### PR DESCRIPTION
**Pull request by wenduwan**

### CODE REVIEW

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
do these fixes need to be brought back to the pmix/prrte release branches for v5.0.x?

(pmix v4.2/prrte v3.0)

**Comment by wenduwan** [comment]
> do these fixes need to be brought back to the pmix/prrte release branches for v5.0.x?

Good question. I don't have an answer.

@rhc54 could you help here?

**Comment by rhc54** [comment]
Already in the release branches. Note that PMIx v4.2.4 has been released, so you might want to include an update to that tag. PRRTE v3.0.1 should go out next week.

**Comment by wenduwan** [comment]
Thanks Ralph - opening PR to bump openpmix pointer.

**Comment by wenduwan** [comment]
https://github.com/open-mpi/ompi/pull/11777

**Comment by wenduwan** [comment]
I will backport both bumps to v5.0.x and run a couple tests.

**Pull request merged**
