### PR TITLE
ompi/contrib: remove libompitrace

### PR DESCRIPTION
**Pull request by jsquyres**
This small library was added for a specific purpose several years ago.
There is no longer a maintainer for this library, and it hasn't been
documented for years (and therefore there are likely very few -- if
any -- users).  We're therefore removing libompitrace from future
versions of Open MPI; it can be obtained from prior version of Open
MPI if it is desired.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Refs #10036

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/789e8dc1e1c3e661ad27501b989e1edd

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cfe0915a61a8fc37e1f986587273c6e1

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8b4b76b1fce934fbff43955625f5be75

**Comment by jsquyres** [comment]
bot:aws:retest

**Review by bwbarrett — APPROVED** [review]

**Pull request merged**
