### PR TITLE
Fix memory leak in configure, which prevents leak sanitizer usage

### PR DESCRIPTION
**Pull request by cniethammer**
Signed-off-by: Christoph Niethammer <niethammer@hlrs.de>

### CODE REVIEW

**Comment by jsquyres** [comment]
@cniethammer I'm not entirely understanding what problem it is that you're fixing here.  Yes, the `free()` was missing from the configure program, but why does it matter?

**Comment by cniethammer** [comment]
This matters if I build Open MPI with sanitizers, e.g. `configure CC=clang CFLAGS=-fsanitize=address ...`.
In this case configure test programs area also build with the sanitizers and will report errors resulting in configure to fail.

**Comment by jsquyres** [comment]
Got it.  Can you put that in the commit message and/or in a comment in the code?

**Comment by cniethammer** [comment]
@jsquyres Updated the commit message

**Comment by devreal** [comment]
Should this be backported to the release branches?

**Comment by cniethammer** [comment]
Yes, would be good to have this in at least 4.1.x for testing

**Comment by jsquyres** [comment]
Might as well do v4.0.x, too.

**Pull request merged**
