### PR TITLE
coll/hcoll: ialltoallv interface

### PR DESCRIPTION
**Pull request by vspetrov**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jjhursey** [comment]
bot:ibm:retest
(Testing a new Jenkins target)

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/c33b44ddf0768d16cc21b045015889d0

**Comment by jjhursey** [comment]
The PGI failure is not related to this PR. Disregard.

**Comment by jladd-mlnx** [comment]
@jsquyres @hppritcha Please merge so that we can cover under our MTT.

**Comment by jsquyres** [comment]
I'll merge when it clears CI.

**Pull request merged**
