### PR TITLE
Detect that we have a mix of BE/LE in the system, provide a warning that OMPI doesn't currently support this environment, and error out

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit 2753f53e6d75f6aab863eaa319cea9f9d434d5ef)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 you need to cherry-pick open-mpi/ompi@823382f5d7b7477d7c9471e4d4e25db8c77ff8bb

we do support mixing BE/LE, but only when configure'd with ```--enable-heterogeneous```

**Comment by rhc54** [comment]
@ggouaillardet Are you sure that is true?? I looked but that PR you had created a long time ago was never committed, and so far as I can tell, we still don't work correctly in that mode.

**Comment by ggouaillardet** [comment]
i will resume working on that PR.
as far as i am concerned, mixed BE/LE works pretty well in my environment (which might have a few not yet commited patches).
i am fine if ```v3.0.x``` does not support mixed BE/LE, but i will appreciate if ```master``` does.

**Comment by rhc54** [comment]
I'll leave this PR as-is until we see your PR completed. I'm a little disturbed about changing master without clear evidence that hetero is working again, but let's leave that in for now with the proviso that you get that PR completed and committed soon.

**Comment by hppritcha** [comment]
hmm... well I now see something I'd like addressed if we're disabling BE/LE mixed support.  Namely, we should at least for a while, remove the --enable-heterogeneous configure option if we know it doesn't work.

**Comment by rhc54** [comment]
Okay - easy enough to add. Will leave master alone, though, pending the PR from @ggouaillardet

**Comment by ggouaillardet** [comment]
the PR is #2940

**Comment by rhc54** [comment]
@hppritcha I pushed the requested change

**Comment by bwbarrett** [comment]
I'm not sure I like this patch...  Let's push to master and then to v3.0.x.  Yes, Giles is working on fixing heterogenous in master, but he can add a revert with the rest of his patch series.  We need to get in the habit of not special casing all the branches.

**Comment by rhc54** [comment]
no problem - will do

**Comment by rhc54** [comment]
Okay, I replaced the custom commit with the one to master: 8e25733760bccdad434450831f248069191104a5

**Pull request merged**
