### PR TITLE
Shift the signal forwarding code to ess/base...

### PR DESCRIPTION
**Pull request by rhc54**
...so it can be available to more than just the hnp component. Extend the slurm component to use it so that any signals given directly to the daemons by their slurmstepd get forwarded to their local clients

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@hjelmn Please test this in your environment to verify that the slurm-based daemons forward signals to their children as desired

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/81652e9e66d6244e445b7725a7dd38b9

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/dd7eac0d2e3ff0a0750493ebe7df4854

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/21c3feb4be8b25db85b665b444be78d1

**Pull request merged**
