### PR TITLE
travis: add config file for travis-ci.org

### PR DESCRIPTION
**Pull request by jsquyres**

### CODE REVIEW

**Comment by hppritcha** [comment]
Why not add Oscar?

**Comment by hppritcha** [comment]
Sorry OS X

**Comment by jsquyres** [comment]
I will -- I'm continually updating this file while I'm trying to get the script right.  When I'm done, I'll add OS X and clang.

**Comment by ggouaillardet** [comment]
@jsquyres an other option is to tell travis to use trusty
just add this in ```.travis.yml```
```
sudo: required
dist: trusty
```
and there is no more need for ```--low-ok``` since trusty provides autoconf 2.69
this is now being tested in #1206

**Comment by jsquyres** [comment]
@ggouaillardet I think I finally have a good one for Linux and OS X, with both gcc and clang.  See https://travis-ci.org/open-mpi/ompi/builds/96289570.

**Comment by bosilca** [comment]
How do you force it only for PRs (and not for every single commit) ?

**Comment by ggouaillardet** [comment]
that can be achieved by adding this to .travis.yml
```
# blacklist
branches:
  except:
    - master
    - v2.x
    - v1.10
```

**Comment by jsquyres** [comment]
Why not for every commit?  It's free :)

That being said, when I get back online I plan to make two changes:

1. Only distcheck on Linux gcc 
1. Add the proper -j to the distcheck build

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@hppritcha @bosilca @ggouaillardet I think this travis config file is looking good now -- check out the latest travis test results.

**Comment by ggouaillardet** [comment]
:+1: 
any reason why you ```make distcheck``` on Linux/gcc only and other combinations just ```make check``` ?

**Comment by jsquyres** [comment]
@ggouaillardet A few reasons:

1. Mainly: just to use less time / resources.
1. But also:
    1. We only do `make distcheck` (officially) when we configure with gcc; no need to test with clang
    1. The OS X travis builds take 40+ minutes when you do a `distcheck`.  When only invoking `make all check`, the last OS X travis builds only took ~15 mins

**Pull request merged**
