### PR TITLE
Threadshift events to avoid threadlock

### PR DESCRIPTION
**Pull request by jjhursey**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit 117af028b1fdab33db905027edc1ab5e391b0de3)

### CODE REVIEW

**Comment by jjhursey** [comment]
Note that this made it into the v3.1.x branch, but not the v3.0.x branch.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/71d877b4c70d3d9cf50aaa5ca27df1a2

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/42d55387a9e2bf126857e40b3265e7b9

**Comment by jjhursey** [comment]
I'm looking into the merge conflict

**Comment by jjhursey** [comment]
Sorry, 1 last push to update the `ext2x` component. The other release branches keep the internal and external in sync. But v3.0.x has duplicate code still, so make sure to update both the internal and external components.

This _should_ be good now. But I'll wait for CI to run before taking the WIP tag off.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b7a006f62cb695edb2292978b27a37cf

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/18b831deb503d9d3a4b533d8f90f9218

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/bbccf07b6107f966b554910c08226993

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by jjhursey** [comment]
I'm struggling to get cycles to get back to this and fix it up. So I added a help wanted tag in case someone else wants to take a pass at it before I get back to it.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ec371ef1284b134af1bc14b125423b4e

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/66afeb6f270aca153295e37a7507d9d7

**Comment by jsquyres** [comment]
@jjhursey Is this PR going anywhere?

**Comment by jjhursey** [comment]
I need to abandon it as I'm not going to have cycles any time soon to get back to it. It's a good thing to port back if someone wants to do so.

**Pull request closed without merging**
