### PR TITLE
v4.1.x: configury reproducibility fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
ready for primetime when/if #8239 is merged as-is.

**Comment by jsquyres** [comment]
Convert to Draft PR until #8239 is merged.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/50172810ae143463efef706b25c03454

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/83d7b5ffaae35edf77df325cc5309a7a

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:retest

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
