### PR TITLE
error correction to the MPI_file operations thread safety lock

### PR DESCRIPTION
**Pull request by jijo733**
Signed-off-by: Jijo Varghese <jijo733@gmail.com>

This can become a potential threat to the thread safety.

### CODE REVIEW

**Comment by jsquyres** [comment]
@jijo733 Thank you!  Github pro tip: if you need to edit a commit (e.g., add the signed-off-by line), you can just edit that commit locally and then force push to your github.com branch.  The PR will automatically update with the new contents of your branch.

@edgargabriel Can you have a look?  Seems like a no-brainer.

**Comment by jijo733** [comment]
@jsquyres Thank you for the tip !

**Comment by hppritcha** [comment]
@edgargabriel please review and PR to v2x if needed

**Comment by edgargabriel** [comment]
The thread safety stuff is not in the 2.x branches, so there is no need for a pr to 2.x

**Comment by hppritcha** [comment]
okay.  I'll merge it in.

**Pull request merged**
