### PR TITLE
Update hwloc submodule to fix "make distcheck"

### LINKED ISSUE #7363: "autogen.pl --force" fails in master tarball due to missing hwloc dirs
If you run `./autogen.pl --force` in a distribution tarball, it fails because there are hwloc directories not present:

```
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:23: error: required directory opal/mca/hwloc/hwloc2/hwloc/netloc does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:25: error: required directory opal/mca/hwloc/hwloc2/hwloc/utils does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:25: error: required directory opal/mca/hwloc/hwloc2/hwloc/tests does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:25: error: required directory opal/mca/hwloc/hwloc2/hwloc/contrib/systemd does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:25: error: required directory opal/mca/hwloc/hwloc2/hwloc/contrib/hwloc-ps.www does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:25: error: required directory opal/mca/hwloc/hwloc2/hwloc/doc does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:35: error: required directory opal/mca/hwloc/hwloc2/hwloc/contrib/windows does not exist
opal/mca/hwloc/hwloc2/hwloc/Makefile.am:37: error: required directory opal/mca/hwloc/hwloc2/hwloc/netloc does not exist
autoreconf: automake failed with exit status: 1
Command failed: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config
```

We used to include these directories -- along with dummy `Makefile.am` files -- before we made hwloc be a git submodule.

`make distcheck` works on a master git checkout, but something is not translating correctly to the generated tarball such that if you run autogen in it, 💥.

### PR DESCRIPTION
**Pull request by jsquyres**
Hwloc upstream has fixed a problem with embedded "make distcheck" that
was breaking that surfaced when you ran autogen in an Open MPI
tarball.

This submodule update takes in the upstream hwloc fixes for this
issue.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Fixes #7363

### CODE REVIEW

**Comment by jsquyres** [comment]
@bgoglin just pointed out to me that this is not upstream in the hwloc repo yet.  So -- do not merge yet!

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
@jjhursey The problem is that the git hash isn't upstream in the hwloc repo yet (which I didn't realize when I made the PR).  It'll fail until @bgoglin pushes the commit upstream.

**Comment by bgoglin** [comment]
Pushed in upstream hwloc v2.1 branch as commit 67b2c0368cdd5e0b66476fd4222adaf8f8bac7e0
Sorry Jeff, you need to update the submodule again.

**Pull request merged**
