### PR TITLE
v4.0.x: oob/tcp: add cross version compatibility support

### PR DESCRIPTION
**Pull request by hppritcha**
Since we intend to provide cross version compatibility
between versions with the same major and minor, use
MAJOR.MINOR.0 instead of orte_version_string
(e.g. MAJOR.MINOR.RELEASEGREEK).

Open MPI 4.0.0 has already been released, so in order to make
it compatible with future 4.0.x releases, we have to use 4.0.0
as the version string, that is why we use MAJOR.MINOR.0 instead
of MAJOR.MINOR

Relates to #6157 
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by hppritcha** [comment]
Do we want to make this more general and just check Major, so 4.1 and 4.0 can hopefully talk to each other @ggouaillardet 's "half way" approach for using containers with Open MPI?

**Comment by rhc54** [comment]
IIRC, the conclusion of the telecon was to indeed only check the major number, and we will separate that from the ORTE_MAJOR_VERSION - i.e., change the code so we only pass/check "4". We will update that number if/when there is a change that impacts the oob wire protocol.

**Comment by jsquyres** [comment]
This PR -- and the master PR #6157 -- does not reflect that decision.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request merged**
