### PR TITLE
Update the RML OFI by copying the updated files from @anandhis branch

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/83d588c88a4bba7875c9ada8aa99fef9

**Comment by jjhursey** [comment]
PGI CI failure is an internal problem - should be fixed soon.

**Comment by rhc54** [comment]
@jjhursey @gpaulsen Hilarious error:
```
*** Startup tests
checking build system type... powerpc64le-unknown-linux-gnu
checking host system type... powerpc64le-unknown-linux-gnu
checking target system type... powerpc64le-unknown-linux-gnu
checking for gcc... pgcc
checking whether the C compiler works... no
configure: error: in `/home/mpiczar/jenkins/workspace/ompi_public_pr_master_pgi/ompi-src':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by jjhursey** [comment]
Yeah I upgraded our PGI compiler version and Jenkins needs to be rebooted before it can figure out where to pick it up... I'm waiting on some CI to finish then we should be in good shape.

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by rhc54** [comment]
Hmmm...same problem with the cray tester in PR checker

**Comment by gpaulsen** [comment]
That's not a feature?
---Geoffrey PaulsenSoftware Engineer, IBM Spectrum MPIPhone: 720-349-2832Email: gpaulsen@us.ibm.comwww.ibm.com
 
 
----- Original message -----From: Ralph Castain <notifications@github.com>To: open-mpi/ompi <ompi@noreply.github.com>Cc: Geoff Paulsen <gpaulsen@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [open-mpi/ompi] Update the RML OFI by copying the updated files from @anandhis branch (#3505)Date: Wed, May 10, 2017 11:28 AM 
@jjhursey @gpaulsen Hilarious error:
*** Startup testschecking build system type... powerpc64le-unknown-linux-gnuchecking host system type... powerpc64le-unknown-linux-gnuchecking target system type... powerpc64le-unknown-linux-gnuchecking for gcc... pgccchecking whether the C compiler works... noconfigure: error: in `/home/mpiczar/jenkins/workspace/ompi_public_pr_master_pgi/ompi-src':configure: error: C compiler cannot create executablesSee `config.log' for more details

**Comment by rhc54** [comment]
I'm going to assume that something is borked with the cray tester, and go ahead on the basis that everything else checks out okay.

**Pull request merged**
