### PR TITLE
master: opal: add support for s390 and s390x architectures

### PR DESCRIPTION
**Pull request by nmorey**
Signed-off-by: Nicolas Morey-Chaisemartin <NMoreyChaisemartin@suse.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@hjelmn @bosilca This is the master version of #3449.

**Comment by bosilca** [comment]
From what I see in the code there is no practical difference between s390 and s390x from OMPI perspective. I wonder why are we creating 2 defines?

**Comment by nmorey** [comment]
It is not completely necessary now but as they are 31 and 64 bit arch, I anticipated some differences that may appear later

**Comment by jsquyres** [comment]
Thanks @nmorey!

**Pull request merged**
