### PR TITLE
pmix/external: revamp external pmix package detection

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by jsquyres** [comment]
@ggouaillardet Please remove all the commented-out lines (vs. commenting them out).  Thanks.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
@Di0gen I see a bunch of these errors in the Mellanox Jenkins output -- can you fix?

```
./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh: line 217: [: missing `]'
```

**Comment by ggouaillardet** [comment]
oops, will do

**Comment by jsquyres** [comment]
@ggouaillardet In https://github.com/open-mpi/ompi-release/pull/1118#issuecomment-216196766, you mentioned that PMIx uses more than one include directory.  Can you set `CPPFLAGS` before calling `OPAL_CHECK_PACKAGE`?

**Comment by ggouaillardet** [comment]
@jsquyres This is no more needed !

**Comment by jsquyres** [comment]
Ok.

**Comment by rhc54** [comment]
👎 

This isn't correct - please read the comment about why we cannot use check_package

**Comment by rhc54** [comment]
👍

**Comment by rhc54** [comment]
Please bring over to 2.0 - blocker over there

**Comment by rhc54** [comment]
Unrelated issues again.

**Comment by jjhursey** [comment]
FWIW I did something similar in this #1583 - checkout the additional logic to opal_check_pmi.m4. It worked with external hwloc and libevent in non-standard locations.

Of course, there I was also extracting the version - which we don't need for this commit.

**Comment by jladd-mlnx** [comment]
@jsquyres @rhc54  Hmm...I'm concerned about this. Looks like the first time the Mellanox Jenkins breaks in mindist mapper is with this PR. All subsequent PRs on master are failing. I'll try to investigate more today.

**Comment by jsquyres** [comment]
@jladd-mlnx Is the Mellanox Jenkins using an external pmix installation?

**Comment by jsquyres** [comment]
@jladd-mlnx I just turned this mindist problem into its own issue: https://github.com/open-mpi/ompi/issues/1623.  Let's followup there.

**Pull request merged**
