### PR TITLE
Fix typos in the oshmem/ subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by luzpaz** [comment]
Forgot to `--signoff`, apologies. Amended and forced pushed

**Comment by awlauria** [comment]
bot:ibm:retest

**Review by awlauria — APPROVED** [review]

**Review by jsquyres — APPROVED** [review]
Thank you!

**Pull request merged**
