### PR TITLE
iof: optimize handling of stdin and stderr

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 i pushed an additional commit not to create pipes when `stderr` is redirected into `stdin`
can you please review this ?

**Comment by rhc54** [comment]
Same thing here - some of the changes are missing.

**Comment by bwbarrett** [comment]
@ggouaillardet do you want this merged now?  If so, please remove the WIP tag...

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by ggouaillardet** [comment]
@bwbarrett done, this PR is ready for primetime

**Pull request merged**
