### PR TITLE
configury: enhance external PMIx detection - add the --with-pmix-libd…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…ir=DIR option look for libpmix.* libs in DIR, DIR/lib64 and DIR - if --with-pmix=DIR is given, look for libpmix.so in DIR/lib64 and DIR/lib

Fixes open-mpi/ompi#4347

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@karasevb can you please give this a try ?
this should work even without using the new ```--with-pmix-libdir=DIR``` option.

**Comment by karasevb** [comment]
:+1:

**Comment by ggouaillardet** [comment]
@hppritcha @bwbarrett i will issue a PR for the release branches.
strictly speaking, ```--with-pmix-libdir``` is a new option, but we can consider this as a bug fix,
otherwise, Open MPI cannot be built with an external 32 bits PMIx on a 64 bits system.
so i'd rather not trim this from the PR to come.

any thoughts ?

**Comment by rhc54** [comment]
@ggouaillardet I would suggest bringing it back to the 2.1 and 3.x - not sure it needs to go any further back as the older branches are closing.

**Pull request merged**
