### PR TITLE
v4.1.x: orte/timeout: Upon timeout terminate orted's instead of abandoning them

### PR DESCRIPTION
**Pull request by awlauria**
* When `orterun` is terminating due to a timeout, it should first
   order the daemons to cleanup and exit before terminating itself. This
   prevents the opporunity for the child processes to become orphaned.

 * Add a timer to make sure we can exit in abnormal shutdown.

(cherry picked from commit 05efe6c)

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

Co-authored-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Review by gpaulsen — APPROVED** [review]

**Review by jsquyres — CHANGES_REQUESTED** [review]
https://github.com/open-mpi/ompi/pull/9272#pullrequestreview-732378984

**Comment by awlauria** [comment]
Waiting on a re-review from #9272

**Comment by rhc54** [comment]
This just needs to get updated with the timeout additions from v4.0 patch

**Comment by awlauria** [comment]
Fixed the cherry-pick from v4.0.x. ready to go.

**Pull request closed without merging**
