### PR TITLE
test: check opal_atomic_lock_t and recursivity

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hjelmn could you please have a look at this ?

i found that ```opal_atomic_[try]lock``` is recursive (e.g. a process can take the lock several times).
is this a bug or a feature ?

if this is a feature, then ```opal_atomic_lock_t``` might not be a good candidate for ```coll/libnbc``` since it leads to a request being removed more than once from the ```active_requests``` list, and ultimately causing some crashes

**Comment by ggouaillardet** [comment]
@hjelmn my test is not good, I will review this tomorrow.
so far, I only ran into an issue on Fujitsu sparc with Fujitsu compilers.

**Comment by hjelmn** [comment]
@ggouaillardet It shouldn't be recursive. The lock is defined in ```opal/include/opal/sys/opal_impl.h```.

**Comment by ggouaillardet** [comment]
@hjelmn 
i pushed a new version of my test
on my x86_64/GNU box
```
opal_atomic_trylock on an UNLOCKED atomic
opal_atomic_trylock on a LOCKED atomic
opal_atomic_trylock on a LOCKED atomic
SUPPORT: OMPI Test Passed: opal_atomic_lock_t: (3 tests)
```

but on a sparcv9/Fujitsu node
```
opal_atomic_trylock on an UNLOCKED atomic
opal_atomic_trylock on a LOCKED atomic
 Failure : trylock could lock an atomic previously locked with trylock

opal_atomic_trylock on a LOCKED atomic
 Failure : trylock could lock an atomic previously locked with lock

SUPPORT: OMPI Test failed: opal_atomic_lock_t (2 of 3 failed)
```

i will investigate this from now

**Comment by ggouaillardet** [comment]
bottom line, this is a compiler issue (!)
```__sync_bool_compare_and_swap``` is broken with FJ compiler
here is a trivial test case

```c
#include <stdbool.h>
#include <stdio.h>

#define ASI_P "0x80"

static inline int opal_atomic_cmpset_32( volatile int *addr,
                                         int oldval, int newval)
{
   /* casa [reg(rs1)] %asi, reg(rs2), reg(rd)
    *
    * if (*(reg(rs1)) == reg(rs2) )
    *    swap reg(rd), *(reg(rs1))
    * else
    *    reg(rd) = *(reg(rs1))
    */

   int ret = newval;

   __asm__ __volatile__("casa [%1] " ASI_P ", %2, %0"
                      : "+r" (ret)
                      : "r" (addr), "r" (oldval));
   return (ret == oldval);
}

int main (int argc, char *argv[]) {
   int lock;
   int zero = 0;
   int one = 1;
   bool ret;
   int x;

   lock = 0;

   ret = __sync_bool_compare_and_swap(&lock, zero, one) ;
   x=ret?1:0;
   printf ("%d %d %d\n", lock, ret, x);

   ret = __sync_bool_compare_and_swap(&lock, zero, one) ;
   x=ret?1:0;
   printf ("%d %d %d\n", lock, ret, x);

   printf (ret?"BAD":"GOOD");
   printf ("\n");

   lock = 0;

   x = opal_atomic_cmpset_32(&lock, zero, one);
   printf ("%d %d\n", lock, x);

   x = opal_atomic_cmpset_32(&lock, zero, one);
   printf ("%d %d\n", lock, x);

   printf (x?"BAD":"GOOD");
   printf ("\n");

   return 0;
}
```

with gnu compiler
```
$ gcc --version
gcc (GCC) 4.2.4
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc -O0 -o test.gnu test.c 
$ ./test.gnu 
1 1 1
1 0 0
GOOD
1 1
1 0
GOOD
```

but with FJ compiler
```
$ fcc -v
fcc: Fujitsu C/C++ Compiler Driver Version 1.2.1 P-id: T01761-01 (Sep 30 2015 15:41:31)
usage: fcc [options] files.
$ fcc -g -O0 -o test.fj -Xg test.c
$ ./test.fj 
1 1 1
1 1 1
BAD
1 1
1 0
GOOD
```

for some reasons i did not investigate, Open MPI uses ```sync_builtin``` and not ```sparcv9``` for atomics.

i made some more investigations, and here is the code generated for ```__sync_atomic_compare_and_swap``` with ```-O0 -g```

```as
/*     36 */    lduw    [%fp+2007],%g5
/*     36 */    lduw    [%fp+2011],%o0
/*     36 */    membar  #LoadLoad|#StoreLoad|#LoadStore|#StoreStore
/*     36 */    cas     [%g4],%g5,%o0
/*    ??? */    stw     %o0,[%fp+1979]
/*     36 */    xor     %g5,%o0,%g4
/*     36 */    cmp     %g4,%g0
/*     36 */    subc    %g0,-1,%g4
/*     36 */    cmp     %g4,1
/*     36 */    subc    %g0,-1,%g4
/*     36 */    sra     %g4,%g0,%g4
/*     36 */    and     %g4,255,%g4
/*     36 */    stb     %g4,[%fp+2002]
```

if i mimick the code generated for ```opal_atomic_cmpset_32``` and replace
```as
cmp %g4,%g0
```
with
```
cmp %g0,%g4
```
then it works just fine.
if i use ```-Kfast``` instead of ```-g -O0```, then the same replacement solves the same issue.


@kawashima-fj @yukiM-fj could you please comment on that ?q

**Comment by kawashima-fj** [comment]
@ggouaillardet Thanks for reporting. I talked with a compiler guy and he is investigating.
But unfortunately the summer vacation will start in our office tomorrow.

**Comment by ggouaillardet** [comment]
thanks, for now I will configure with --disable-builtin-atomics

**Comment by kawashima-fj** [comment]
@ggouaillardet It is (officially) identified as a bug of the Fujitsu compiler by our compiler developers. It will be fixed in the next version. Sorry for your inconvenience.

**Comment by bwbarrett** [comment]
@ggouaillardet, can we close this one?

**Comment by ggouaillardet** [comment]
yep, this is no more relevant, so let's close this PR

**Pull request closed without merging**
