### PR TITLE
Update the PMIx and PRRTE pointers

### PR DESCRIPTION
**Pull request by rhc54**
- Deal with deprecated cmd line options and rndz files
- Protect against DVM collisions
- Update atomics

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by artemry-mlnx** [comment]
@jjhursey 
The test failures are similar but not the same. CI for this PR fails with the error ([log file](https://dev.azure.com/mlnx-swx/9a715c71-515f-4a6f-a324-ca65880a05ca/_apis/build/builds/481/logs/8)):
```
2020-02-25T21:49:51.8253795Z + echo 'test mca_base_env_list option in /__w/2/ompi/ompi_install1'
2020-02-25T21:49:51.8254571Z + export XXX_C=3 XXX_D=4 XXX_E=5
2020-02-25T21:49:51.8255205Z + XXX_C=3
2020-02-25T21:49:51.8255644Z + XXX_D=4
2020-02-25T21:49:51.8256073Z + XXX_E=5
2020-02-25T21:49:51.8256803Z test mca_base_env_list option in /__w/2/ompi/ompi_install1
2020-02-25T21:49:51.8268515Z ++ /__w/2/ompi/ompi_install1/bin/mpirun --mca pml ob1 --mca btl self,vader --np 2 --mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
2020-02-25T21:49:51.8271353Z ++ grep '^XXX_'
2020-02-25T21:49:51.8273175Z ++ wc -l
2020-02-25T21:49:53.0196737Z + val=6
2020-02-25T21:49:53.0198677Z + '[' 6 -ne 10 ']'
```
There are several similar CI failures for Open MPI v4.0.x (need to merge https://github.com/open-mpi/ompi/pull/7468 to eliminate such failures):
```
2020-02-26T19:32:58.2008557Z + echo '--mca mca_base_env_list "XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E"'
2020-02-26T19:32:58.2009964Z + echo 'mca_base_env_list=XXX_A=7;XXX_B=8'
2020-02-26T19:32:58.2019541Z ++ /__w/1/ompi/ompi_install1/bin/mpirun --mca pml ob1 --mca btl self,vader --np 2 --tune /__w/1/ompi/test_tune.conf --am /__w/1/ompi/test_amca.conf /__w/1/jenkins_scripts/jenkins/ompi/env_mpi
2020-02-26T19:32:58.2021200Z ++ sed -n -e 's/^XXX_.*=//p'
2020-02-26T19:32:58.2022458Z ++ sed -e ':a;N;$!ba;s/\n/+/g'
2020-02-26T19:32:58.2022866Z ++ bc
2020-02-26T19:32:58.4656290Z + val=30
2020-02-26T19:32:58.4658134Z + '[' 30 -ne 54 ']'
```

@rhc54 
Are there any behavioral changes in this PR?

**Comment by rhc54** [comment]
Things are working fine for me:
```shell
$ export XXX_C=3 XXX_D=4 XXX_E=5
$ prun --np 2 --mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' --personality ompi env | grep ^XXX
XXX_A=1
XXX_B=2
XXX_C=3
XXX_D=4
XXX_E=5
XXX_A=1
XXX_B=2
XXX_C=3
XXX_D=4
XXX_E=5
```
which totals 10 lines. I'm not sure why your test is only counting 6 of them.

**Comment by rhc54** [comment]
I'll be pushing another update of the pointers soon - let's see what happens with it. FWIW: I haven't touched the cmd line parsing code since we started passing the tests.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0386ecdbbb5b77130c7edc0d89f49ea0

**Comment by rhc54** [comment]
@artemry-mlnx I still have no idea how your test is getting 6 instead of 10 - I cannot reproduce it. Is there any way you can get more info out of it? Like maybe just show the env itself?

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2f59b763220a9c403f40e4778138e322

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/db93044ccb448770578bb23af1e1b1fb

**Comment by rhc54** [comment]
> The IBM CI (XL) build failed! Please review the log, linked below.
> 
> Gist: https://gist.github.com/db93044ccb448770578bb23af1e1b1fb

@jjhursey I am confused - the gist says that everything passed. The status is checked off as good. Why did it post a comment saying it failed?

**Comment by rhc54** [comment]
> The IBM CI (XL) build failed! Please review the log, linked below.

@jjhursey I am confused - the gist says that everything passed. The status is checked off as good. Why did it post a comment saying it failed?

**Comment by rhc54** [comment]
@artemry-mlnx I found it! Fix is coming

**Comment by jjhursey** [comment]
The IBM CI got caught in the GitHub outage this morning. They started when things were fine, and got mixed up with the API failures as they were completing. They did indeed pass. The comments were posted because the GH API failed at an odd time :(

**Comment by jjhursey** [comment]
IBM CI is seeing this error message when running `hello_c` (and other examples)
```
shell$ /workspace/exports/ompi/bin/mpirun --hostfile /workspace/hostfile.txt --map-by ppr:4:node  --mca btl_tcp_if_include eth0 --mca oob_tcp_if_include eth0 --mca pml ob1 --mca osc ^ucx --mca btl tcp,vader,self hello_c'
[dda63c67cad5:00017] PRRTE ERROR: Bad parameter in file rml_oob_send.c at line 202
[dda63c67cad5:00017] PRRTE ERROR: Bad parameter in file rml_oob_send.c at line 202
[4f5c63029ce9:00022] PRRTE ERROR: Bad parameter in file rml_oob_send.c at line 202
[4f5c63029ce9:00022] PRRTE ERROR: Bad parameter in file rml_oob_send.c at line 202
```
The tests are all failing this way. CI is just going through a timeout sequence right now.

I'll try to reproduce to get more information.

**Comment by rhc54** [comment]
@artemry-mlnx Wow - much faster!! Thanks!!

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/356cdd8d90d0d032d94bf5fc36b776a9

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4d0bc3bf0629b7ab594f541bd480e403

**Comment by jjhursey** [comment]
I can reproduce with an MPI app, but not with `hostname` or a simple PMIx app. I'm looking into it.

**Comment by jjhursey** [comment]
It has something to do with vader. `--mca btl tcp,vader,self ` fails, but `--mca btl tcp,self ` passes

**Comment by rhc54** [comment]
`vader` does a local modex while the others do a global one, so perhaps there is an issue with dmodex? i.e., perhaps we are trying to lookup the node that hosts the other proc and not finding it?

**Comment by rhc54** [comment]
should clarify: perhaps we are trying to do a dmodex when we shouldn't be? i'm guessing here - sounds like prrte isn't finding a host for the proc, but it's just a guess

**Comment by rhc54** [comment]
FWIW: I just tested `$ mpirun -n 2 --omca btl vader,self ./hello_c` on my Mac and it worked fine. Just one node, though - will try it on my swarm.

**Comment by rhc54** [comment]
Hmmm...well, on a two node system:
```shell
$ mpirun -n 2 --map-by node --omca btl tcp,vader,self ./hello_c
Hello, world, I am 0 of 2, (Open MPI v4.1.0a1, package: Open MPI mpiuser@rhc-node01 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7505-g0054de0, Unreleased developer copy, 146)
Hello, world, I am 1 of 2, (Open MPI v4.1.0a1, package: Open MPI mpiuser@rhc-node01 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7505-g0054de0, Unreleased developer copy, 146)
$
```
So I tried it with the generic MCA options:
```shell
$ mpirun -n 2 --map-by node --mca btl tcp,vader,self ./hello_c
Hello, world, I am 0 of 2, (Open MPI v4.1.0a1, package: Open MPI mpiuser@rhc-node01 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7505-g0054de0, Unreleased developer copy, 146)
Hello, world, I am 1 of 2, (Open MPI v4.1.0a1, package: Open MPI mpiuser@rhc-node01 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7505-g0054de0, Unreleased developer copy, 146)
$
```
So I cannot reproduce even on my multi-node system

**Comment by rhc54** [comment]
Aha! The key is to have a mix of local and remote procs, so you need more than 1 ppn.

**Comment by rhc54** [comment]
FWIW: the error indicates it was asked to send to an INVALID peer, so it looks like there is some message regarding a proc whose location is unknown. I'll try to dig into this a bit myself and provide some more inline checks to catch the case where we don't know a location.

**Comment by jjhursey** [comment]
(I know this will fail, but I'm checking a fix in the CI logic)
bot:ibm:gnu:retest

**Comment by rhc54** [comment]
I've tracked it down. It's a combination of two problems:

* the vader modex recv is surfacing to the PRRTE daemon as a direct modex - it should be strictly locally resolved in the PMIx server

* the daemon is somehow getting an "invalid" name for the sender who requested the dmodex - it is the response message that is generating the output error log

I'm working on the solutions

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b30cb9b50a96adbd86d0ce80181efe8f

**Comment by rhc54** [comment]
@bwbarrett @wckzhang You have a problem in the AWS jenkins scripts. From the output, it looks like you are executing `mpirun -hostfile` - note the single-dash option. This is resulting in you actually executing `mpirun -h` and generating the help output on every test execution.

So the tests aren't really testing anything other than build. I'll be updating the cmd line parser to generate an error for such mistakes, but you need to fix the scripts.

**Comment by rhc54** [comment]
bot:ibm:retest

**Pull request merged**
