### PR TITLE
Fix treematch topology assert

### PR DESCRIPTION
**Pull request by bosilca**
Fixes the root cause of #4303.
Force all output to use OMPI infrastructure.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by bosilca** [comment]
argh, there were 2 commits and I squashed them ... Let me split them again then.

**Comment by bosilca** [comment]
The fixes were isolated into a single commit. The redirection of the debug output to the OMPI infrastructure is now on its own commit.

**Comment by bwbarrett** [comment]
haha; thanks!

**Comment by bwbarrett** [comment]
@bosilca, want to merge these?

**Pull request merged**
