### PR TITLE
v2.x: fix and revamp MPI_Pack and friends

### PR DESCRIPTION
**Pull request by ggouaillardet**
Fixes open-mpi/ompi#3065

### CODE REVIEW

**Comment by ggouaillardet** [comment]
This is an alternative to #3060

**Comment by jsquyres** [comment]
@ggouaillardet #3060 was merged.  Does that create a logical conflict with this one?

**Comment by ggouaillardet** [comment]
i will rebase tomorrow and fix the conflict if any

**Comment by jsquyres** [comment]
@hppritcha Need to examine this one a little more carefully because #3060 was merged before this one (this one might be ok -- and @ggouaillardet might just rebase it / make it ok depending on the timing if we want to get this in before tonight's MTT).

**Comment by ggouaillardet** [comment]
@jsquyres i rebased and fixed that (we made the same change twice)
@bosilca i got rid of ```ompi_datatype_dfd``` by cherry-picking open-mpi/ompi@6aac0d9c2255038b6cc69228c6e5587a0e763c4c

**Comment by jsquyres** [comment]
@ggouaillardet Thank you!

**Comment by jsquyres** [comment]
@hppritcha Good to go when CI finishes.  Would be good to get in the next ~80 minutes so that it's part of tonight's nightly snapshot build / tonight's MTT.

**Comment by jsquyres** [comment]
Travis is having an outage tonight and builds are currently paused.  I'm merging so that this fix gets in for tonight's MTT runs.

**Pull request merged**
