### PR TITLE
autogen.pl: patch libtool.m4 for OSX Big Sur

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks FX Coudert for reporting this issue and pointing
to a solution.

Refs. open-mpi/ompi#8218

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by rhc54** [comment]
The older gcc environments are failing:
```text
--> running ./autogen.pl 
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/darwin\*\) # darwin 5.x on\n      # if running on 10.5 or later, the deployment target defaults\n      # to the OS version, if on x86, and 10.4, the deployment\n      # target defaults to 10.4. Don\'t you love it\?\n      case \${ <-- HERE MACOSX_DEPLOYMENT_TARGET-10.0},\$host in\n\t10.0,\*86\*-darwin8\*\|10.0,\*-darwin\[91\]\*\)\n\t  _lt_dar_allow_undefined=\'\${wl}-undefined \${wl}dynamic_lookup\' \;\;\n\t10.\[012\]\*\)\n\t  _lt_dar_allow_undefined=\'\${wl}-flat_namespace \${wl}-undefined \${wl}suppress\' \;\;\n\t10.\*\)/ at ./autogen.pl line 1089.
```

**Comment by ggouaillardet** [comment]
yep, I am on it

**Review by rhc54 — APPROVED** [review]

**Review by jsquyres — COMMENTED** [review]
Can you explain why there's 2 substitutions instead of one?

Is the 2nd one to transmorgiphy `\$\{wl\}` to `\$wl`?  Because if so, there's still a handful of `\$\{wl\}`'s left in the 2nd statement.

Could we format this change like some of the other cases in `autogen.pl`, where we have multi-line strings for `$search_string` and `$replace_string`?  That makes it a bit easier to read/maintain.

**Comment by ggouaillardet** [comment]
I should obviously have left a comment here ...
recent `libtool.m4` always use `${wl}` (that is handled by the first substitution)
but some older `libtool.m4` use a mix of `${wl}` and `$wl` (this is handled by the second substitution).
Note both substitutions are independent.

I initially used `$search_string` and `$replace_string`. It was somehow easier to read but at the expense of a *lot* of backslashed. for example, `\$` has to be translated to `\\\$` is we move to multi string substitution.
I have no strong opinion on that, so if you prefer multi line substitutions I will update the PR.

I will be off tomorrow, so no update from me for the next days (feel free to take over this PR in the mean time).

**Comment by jsquyres** [comment]
@ggouaillardet Awesome; thanks for the explanation.

Let me frob this PR a little bit and see if I can make the regexp a little more manageable (e.g., Perl's `'` quoting might reduce the amount of escaping needed).

Thanks!

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by ggouaillardet** [comment]
@jsquyres I preprended all braces with a backslash to make some perl happy (for example, perl that comes with RHEL8).

I am fine with your changes, so if you are happy with my latest commit, feel free to squash and merge! Then I will issue PR to backport this into the release branches.

**Comment by rhc54** [comment]
Is this really going to work as-is? I would have thought you'd also need to update the autogen.pl's in the embedded PMIx and PRRTE (and perhaps HWLOC) since they are executed independently.

**Comment by rhc54** [comment]
This seems to work fine on my Mac 10.15 box, except for the following:
```text
Makefile:1514: warning: overriding commands for target `check-recursive'
Makefile:1235: warning: ignoring old commands for target `check-recursive'
```
I get three copies of that pair of warnings.

**Comment by hjelmn** [comment]
Will be testing this on:

```
Darwin Mac-mini.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
```

later today.

**Comment by ggouaillardet** [comment]
`autogen.pl` will patch all the `configure` it can find, regardless who generated them, so as far as Open MPI is concerned, I think this is good enough.

That being said, 3rd party projects such as PMIx should also apply the same patch so they can be built independently on Big Sur.

**Comment by hjelmn** [comment]
For arm64-apple-darwin we have a bit of an issue. pandoc required ghc which takes some work to get built on this system. I am working on a procedure for homebrew to limp along until official support. So, the build environment I have will have to get --disable-man-pages until I can work this procedure out. Otherwise I will check this.

**Comment by hjelmn** [comment]
Hmm, this PR is not required for arm64-apple-darwin. I was able to ```./autogen.pl ; ./configure ; make``` without any issues.

**Comment by jsquyres** [comment]
I upgraded my home iMac to Big Sur and was able to compile master and v4.1.x -- without this PR -- just fine.  Weird.

We _know_ that Libtool is not doing the fully-correct thing (i.e., it's missing at least some Darwin-related code paths because of the version number change), but at least in some cases, it appears not to matter.  I didn't track down what the cases are the matter / don't matter.

I tested @ggouaillardet's latest commit, and it looks good to me.  I'll squash and re-push up here.

**Comment by jsquyres** [comment]
@ggouaillardet I think that this is now good to go, but I'll let you merge it in case you're aware of any other changes that are needed (since you worked on #8239 as well, and both of these ended up being relevant to #8218).

**Comment by ggouaillardet** [comment]
@jsquyres did you build from an official tarball without `autogen.pl --force` ?

My understanding is that `brew` already patched `autoconf`, so the issue is "hidden" if you run `autogen.pl` on your mac.

**Comment by jsquyres** [comment]
Ah, I did not do that.  And I don't remember offhand if the tarball I made for testing was created on a Linux machine or my Mac.

**Pull request merged**
