### PR TITLE
v2.0.2: usnic queue fixes

### PR DESCRIPTION
**Pull request by jsquyres**
This is the v2.0.x version of master PR #2692.

It does not include all off the commits from #2692 -- some of those are just extra error checking, and one is a change in the output format of statistics.

This is a blocker because it fixes some usnic bugs when running at scale.

### CODE REVIEW

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by gpaulsen** [comment]
We'll wait a few hours to see if this gets reviewed and pulled.  If not we'll pull from PR.

**Comment by jsquyres** [comment]
@bturrubiates Updated to include fixes from review of #2692.

**Comment by hppritcha** [comment]
lanl-disable-dlopen failure is spurious.  Its catching the cpuid error.

**Comment by jsquyres** [comment]
@hppritcha This is good to go.  I'm going to merge so that it's in the nightly tarball.

**Pull request merged**
