### PR TITLE
Update PMIx and PRRTe submodule pointers.

### PR DESCRIPTION
**Pull request by awlauria**
PMIX: v4.2.6 release tag
PRRTE: v3.0.1 relsease tag

bot:notacherrypick

### CODE REVIEW

**Review by lrbison — APPROVED** [review]
double-checked tagged versions.  Looks good to me.

**Comment by lrbison** [comment]
that same ROCm CI failures here, seems unrelated but perhaps @edgargabriel could take a look?

**Comment by jsquyres** [comment]
This ROCm error *seems* to be an error in the github infrastructure.  @edgargabriel is poking around to see if there's something that we're doing that consistently bumps up against some Github Actions limit, but we don't have a resolution yet.  For the moment, the working for these infra-related failures is just "re-run the job, and it'll probably succeed this time".

**Comment by bwbarrett** [comment]
Ralph, in the case of old PMIx and internal PRRTE, PRRTE will through a configure time error anyway, will it not?  Who cares if OMPI or PRRTE throws the error?

**Comment by rhc54** [comment]
> Ralph, in the case of old PMIx and internal PRRTE, PRRTE will through a configure time error anyway, will it not? Who cares if OMPI or PRRTE throws the error?

Yes it will - and I agree we shouldn't care who throws the error.

My point really was more the documentation - if OMPI claims a min version is required for PMIx, and I give you that version, then it seems reasonable for me to expect OMPI to build. Getting an error out from the PRRTE section would seem to invalidate the information in the doc.

**Comment by bwbarrett** [comment]
> > Ralph, in the case of old PMIx and internal PRRTE, PRRTE will through a configure time error anyway, will it not? Who cares if OMPI or PRRTE throws the error?
> 
> Yes it will - and I agree we shouldn't care who throws the error.
> 
> My point really was more the documentation - if OMPI claims a min version is required for PMIx, and I give you that version, then it seems reasonable for me to expect OMPI to build. Getting an error out from the PRRTE section would seem to invalidate the information in the doc.

Yeah, fair.  We should probably have a note explicitly calling that out in our docs, but I don't think we try to handle it in our VERSION file (or try to track the PMIx version required for the internal PRRTE in our docs).  I think this is one of those places we should document by reference.

**Pull request merged**
