### PR TITLE
v2.x: group: Fix `ompi_group_have_remote_peers`

### PR DESCRIPTION
**Pull request by kawashima-fj**
@hjelmn Could you review?

Corresponding master PR: #3489.

(cherry picked from commit e453e4227997ebf96fe67a9ccfc3ed8e64629ca4)

### CODE REVIEW

**Comment by hjelmn** [comment]
Ok, much better :+1:

**Comment by hjelmn** [comment]
will let it go on master for a day or so before approving branch PRs

**Comment by kawashima-fj** [comment]
Yes, master PR #3489 was merged into master 5 days ago and have no problems in MTT.
(Original PR #3410 had a problem though)

**Comment by hjelmn** [comment]
ok, see that now. will approve these now then

**Comment by jsquyres** [comment]
@bwbarrett @hppritcha Merging this PR means that you also need to merge the v3.0.x equivalent (#3530).

But otherwise: @hppritcha good to go

**Pull request merged**
