### PR TITLE
glob.h check fixed, otherwise it always fails

### PR DESCRIPTION
**Pull request by awlauria**
Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
Hmm..

```
*** WARNING: The following people had the same email address:
***   Edgar, Edgar Gabriel

*******************************************************************************
*** YOU SHOULD EDIT THE .mailmap FILE TO RESOLVE THESE WARNINGS!
*******************************************************************************
New AUTHORS file written.
make[2]: *** [Makefile:1941: AUTHORS] Error 1
make[2]: Leaving directory '/home/ubuntu/workspace/open-mpi.build.distcheck/src'
make[1]: *** [Makefile:1592: distdir] Error 2
make[1]: Leaving directory '/home/ubuntu/workspace/open-mpi.build.distcheck/src'
make: *** [Makefile:1696: dist] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
@edgargabriel ?

**Comment by edgargabriel** [comment]
I have no idea what this is or where the issue stems from? I mean, it is probably me in both cases but I can't recall that I ever edited this file manually?

**Review by bwbarrett — APPROVED** [review]

**Comment by awlauria** [comment]
Yeah...I don't really understand why this commit is complaining. It would make sense if you are the author :man_shrugging:

**Comment by bwbarrett** [comment]
Someone broke "make dist" on master; all PRs are going to fail until the .mailmap has been updated.  I'm not sure why it didn't trigger on the commit of the ROCm patches (which looks like the breaking commit), but here we are.

**Comment by awlauria** [comment]
Yup, seeing other PR's fail now.

I think you can add your new user/email to the mailmap here: https://github.com/open-mpi/ompi/blob/main/.mailmap @edgargabriel

**Comment by edgargabriel** [comment]
I can do that, but I am not sure I understand. I made probably a dozen commits from my outlook email address that is not listed in that file as well. Could the issue be that the two email addresses listed in that file are not associated with my github account anymore? ( I closed them and removed them when I left UH)

**Comment by edgargabriel** [comment]
Never mind, I see how I broke things :-(  PR https://github.com/open-mpi/ompi/pull/10372 seems to be fixing it. It looks like on one of the machines that I made commits from for the rocm patch the git setup was not entirely correct, and I missed that. Sorry!

**Comment by awlauria** [comment]
Thanks!

bot:aws:retest

**Pull request merged**
