### PR TITLE
Import the ADAPT collective into the 4.1 

### PR DESCRIPTION
**Pull request by bosilca**
Bring https://github.com/open-mpi/ompi/pull/7716 to 4.1

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca Are you going to merge the equivalent PR into master?  We like to have things in master before release branches...

**Comment by jsquyres** [comment]
Converted this back to draft just so that we don't accidentally merge it until the corresponding master PRs are merged and the updates are brought back here to this PR.

**Comment by jsquyres** [comment]
The master version of this PR was merged (#7716), but some bugs were discovered after the merge.  Hence, we're holding off on merging here in v4.1.x until we can get some ADAPT fixes on master.

@bosilca is working on it.

**Review by jsquyres — APPROVED** [review]
Tests ok to me.

Do you want to squash these down and update the cherry-picked lines in the commit messages?

I note that we're missing the ialltoallv fix that went in on master (unrelated to ADAPT, but discovered during ADAPT testing).

**Comment by bosilca** [comment]
I can squash those down into a single commit, and point to the cherrypicked one. I'll do it later tonight.

You are right I did not import anything outside the ADAPT directory. Feel free to import as an independent PR.

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
