### PR TITLE
v4.1.x: Fix handling of large data in MPI_Sendrecv_replace

### PR DESCRIPTION
**Pull request by ggouaillardet**
bot:notacherrypick

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by ggouaillardet** [comment]
@jsquyres could you please verify the bot?

this PR is made of two commits:
 - the first one is a backport
 - the second one is a straight cherry-pick

The first one contains the following messages
```
   (back-ported from commit 6a11873ef52191962b42ba8f56e3630e266222c7)
    bot:notacherrypick
```
the bot complained of a missing cherry pick message and did not notice the `bot:notacherrypick` directive (it even suggested me to add one !)

I would suggest to add the new `bot:backport` directive so we can make the distinction between backports (e.g. cherry-pick requiring manual action) and one-off commits for the release branches (because `master` do it differently).
A valid commit in `master` could even be checked when the `bot:backport` directive is used.

**Comment by bwbarrett** [comment]
The bot:notacherrypick goes in the PR body, not in the git commit message.  We are opinionated that bit commands don’t belong in git history.

I don’t get your back port comment. The bot doesn’t check that it was a clean cherry pick or that you changed things. Only that it is either a PR marked as not a cherry commit or there’s a cherry-commit line with a reference to a valid hash.

**Comment by ggouaillardet** [comment]
Thanks @bwbarrett for the insight, I will update the PR accordingly.

Don't the `bot:notacherrypick` directive ends up in the merge commit (and hence git history)? (I have no intention to argue with this though)

My point is that, regardless the bot, I like to make the distinction between clean cherry pick  and backports.
In the former case, the git message contains a `cherry picked from commit ...` line.
With the latter, after I resolve a conflict, I used to manually replace `cherry picked` with `back-ported`.

In the second case, I understand we have several options:
 - leave the `cherry picked from commit` message: bot is happy, I am not (because I like to make it clear this is a backport and not a straightforward cherry pick)
 - make a `back-ported from commit` message **and** a `bot:notacherrypick` message in the PR. This is stil suboptimal to me since
   - the bot does not check the back-port is from a valid commit from `master`
   - in the case of a PR containing multiple commits, the bot does not check the clean/straightforward commits were cherry-picked from a valid commit.
FWIW, if this is a one off commit, I used to manually add a `this is a one-off commit for the release branch`
   - leave the `cherry picked from commit` message to keep the bot happy, and manually add a `backport was required` like message: in my highly subjective opinion, this does not look pretty.

**Review by bwbarrett — APPROVED** [review]

**Review by bosilca — APPROVED** [review]

**Pull request merged**
