### PR TITLE
Document ORTE -> PRRTE MCA parameter changes

### PR DESCRIPTION
**Pull request by qkoziol**
Document MCA parameter changes from move from ORTE to PRRTE.

Addresses Github issue #7668

### CODE REVIEW

**Review by lrbison — APPROVED** [review]
Reviewed for typos and wording.  Also confirmed none of the deprecated options would apply to 5.0.0 version series.  I cannot say if this is an exhaustive listing.

**Comment by jsquyres** [comment]
I rebased this PR on current main/HEAD, and added a 2nd suggested commit.  This commit can be squashed or deleted.

**Review by janjust — APPROVED** [review]
I would squash the commit, but otherwise looking good to me.

**Comment by rhc54** [comment]
> When replacing `hwloc_base_use_hwthreads_as_cpus` What does this mean?
> 
> > Value: `[<Value>]:hwtcpus`
> 
> I expected it to be perhaps just
> 
> > `rmaps_default_mapping_policy:hwtcpus`

The cmd line option looks like `--map-by :hwtcpus` if you aren't specifying any mapping policy. However, note that this does NOT affect the default PRRTE behavior - it is a per-job directive. For `mpirun`, it doesn't matter as you are running a one-shot - unless your app does a comm_spawn, in which case it might (depends on whether or not you have set `inherit`).

If you want to affect the defaults, then you have to use the MCA parameter: `PRTE_MCA_hwloc_base_use_hwthreads_as_cpus`

**Comment by lrbison** [comment]
@rhc54 ah, thank you for explaining.

Jeff shared a rendered version of the table with me: https://ompi--11890.org.readthedocs.build/en/11890/mca.html#label-mca-backward-compat

And while most of these make sense to me to read, the rmaps_default_mapping_policy entries was hard for me to grok, as I expect it would be for users.  I wonder if it would be worth an example explaining the concept of these parameters which get captured as extra colon-separated tags on top of other parameters.

> However, note that this does NOT affect the default PRRTE behavior - it is a per-job directive

Hmm, am I hearing you correctly then: This table isn't correctly informing users how to take the previous MCA parameter `hwloc_base_use_hwthreads_as_cpus` and get the same effect using `rmaps_default_mapping_policy` because updating the default won't change the one-shot launch behavior.  What is the correct parameter to direct the user towards?

**Comment by rhc54** [comment]
> Hmm, am I hearing you correctly then: This table isn't correctly informing users how to take the previous MCA parameter `hwloc_base_use_hwthreads_as_cpus` and get the same effect using `rmaps_default_mapping_policy` because updating the default won't change the one-shot launch behavior.

Sorry - no, it is the other way around. Updating the default via MCA param will change the one-shot behavior. My point was that the cmd line options (e.g., `--map-by foo`) do not change the default behavior - they only impact the one-shot job request. So if you pass `--map-by :hwt` you will treat hwt's as cpus for that specific job. However, if that job does a comm_spawn, you may not treat hwt's as cpus for the child job (it would depend on whether or not `inherit` was set).

If you _always_ want to treat hwt's as cpus, then you would set the MCA param so the default is set (probably in your default MCA param file, which is what I do).

**Comment by jsquyres** [comment]
@rhc54  Thanks for all the clarifications.

@qkoziol @lrbison Can you guys fix up the content?  Feel free to squash it all down to a single commit.

**Comment by qkoziol** [comment]
Working on adding some examples

**Comment by qkoziol** [comment]
Updated with examples

**Review by jsquyres — CHANGES_REQUESTED** [review]
@qkoziol These are great examples!

One point, however -- all your examples show extra spaces around the `=` in the assignment of shell variables.  That actually causes a syntax error; the extra spaces need to be removed:

```sh
# This is an error
$ export FOO = bar
zsh: bad assignment
$ FOO = bar
zsh: command not found: FOO

# It's also an error in bash
$ export FOO = bar
bash: export: `=': not a valid identifier
$ FOO = bar
bash: FOO: command not found

# Either of these are correct
$ export FOO=bar
$ FOO=bar
```

**Review by jsquyres — APPROVED** [review]

**Comment by janjust** [comment]
@qkoziol please open up v5.0 PR

**Comment by qkoziol** [comment]
> @qkoziol please open up v5.0 PR

FYI:  v5.0 PR:  https://github.com/open-mpi/ompi/pull/11926

**Pull request merged**
