### PR TITLE
Silence a bunch of warnings

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Here were the warnings:
```shell
shmem_posix_common_utils.c: In function 'shmem_posix_shm_open':
shmem_posix_common_utils.c:94:29: warning: variable 'hn' set but not used [-Wunused-but-set-variable]
   94 |                 const char *hn;
      |                             ^~
osc_rdma_dynamic.c: In function 'find_insertion_point':
osc_rdma_dynamic.c:103:69: warning: comparison of integer expressions of different signedness: 'osc_rdma_size_t' {aka 'long long int'} and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
  103 |     if (region->base > base || (region->base == base && region->len > region_size)) {
      |                                                                     ^
osc_rdma_dynamic.c: In function 'ompi_osc_rdma_find_conflicting_attachment':
osc_rdma_dynamic.c:116:38: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
  116 |         if (base >= attachment->base && base < region_bound ||
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../opal/include/opal/types.h:43,
                 from ../../../../opal/runtime/opal.h:31,
                 from ../../../../opal/runtime/opal_progress.h:37,
                 from ../../../../opal/threads/condition.h:33,
                 from ../../../../opal/class/opal_free_list.h:30,
                 from osc_rdma.h:28,
                 from osc_rdma_dynamic.h:12,
                 from osc_rdma_comm.h:17,
                 from osc_rdma_dynamic.c:13:
osc_rdma_dynamic.c: In function 'ompi_osc_rdma_detach':
osc_rdma_dynamic.c:315:49: warning: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'osc_rdma_size_t' {aka 'long long int'} [-Wformat=]
  315 |         OSC_RDMA_VERBOSE(MCA_BASE_VERBOSE_INFO, "checking attachments at index %d {.base=%p, len=%lu} for attachment %p"
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  316 |                          ", region handle=%p", region_index, (void *) region->base, region->len, base, rdma_region_handle);
      |                                                                                     ~~~~~~~~~~~
      |                                                                                           |
      |                                                                                           osc_rdma_size_t {aka long long int}
../../../../opal/util/output.h:410:36: note: in definition of macro 'opal_output_verbose'
  410 |             opal_output(output_id, __VA_ARGS__);                     \
      |                                    ^~~~~~~~~~~
osc_rdma_types.h:233:34: note: in expansion of macro 'OPAL_OUTPUT_VERBOSE'
  233 | #define OSC_RDMA_VERBOSE(x, ...) OPAL_OUTPUT_VERBOSE((x, ompi_osc_base_framework.framework_output, __VA_ARGS__))
      |                                  ^~~~~~~~~~~~~~~~~~~
osc_rdma_dynamic.c:315:9: note: in expansion of macro 'OSC_RDMA_VERBOSE'
  315 |         OSC_RDMA_VERBOSE(MCA_BASE_VERBOSE_INFO, "checking attachments at index %d {.base=%p, len=%lu} for attachment %p"
      |         ^~~~~~~~~~~~~~~~
osc_rdma_dynamic.c:315:100: note: format string is defined here
  315 |         OSC_RDMA_VERBOSE(MCA_BASE_VERBOSE_INFO, "checking attachments at index %d {.base=%p, len=%lu} for attachment %p"
      |                                                                                                  ~~^
      |                                                                                                    |
      |                                                                                                    long unsigned int
      |                                                                                                  %llu
In file included from ../../../../opal/include/opal/types.h:43,
                 from ../../../../opal/runtime/opal.h:31,
                 from ../../../../opal/runtime/opal_progress.h:37,
                 from ../../../../opal/threads/condition.h:33,
                 from ../../../../opal/class/opal_free_list.h:30,
                 from osc_rdma.h:28,
                 from osc_rdma_dynamic.h:12,
                 from osc_rdma_comm.h:17,
                 from osc_rdma_dynamic.c:13:
osc_rdma_dynamic.c:315:49: warning: format '%p' expects argument of type 'void *', but argument 7 has type 'ompi_osc_rdma_handle_t *' {aka 'struct ompi_osc_rdma_handle_t *'} [-Wformat=]
  315 |         OSC_RDMA_VERBOSE(MCA_BASE_VERBOSE_INFO, "checking attachments at index %d {.base=%p, len=%lu} for attachment %p"
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  316 |                          ", region handle=%p", region_index, (void *) region->base, region->len, base, rdma_region_handle);
      |                                                                                                        ~~~~~~~~~~~~~~~~~~
      |                                                                                                        |
      |                                                                                                        ompi_osc_rdma_handle_t * {aka struct ompi_osc_rdma_handle_t *}
../../../../opal/util/output.h:410:36: note: in definition of macro 'opal_output_verbose'
  410 |             opal_output(output_id, __VA_ARGS__);                     \
      |                                    ^~~~~~~~~~~
osc_rdma_types.h:233:34: note: in expansion of macro 'OPAL_OUTPUT_VERBOSE'
  233 | #define OSC_RDMA_VERBOSE(x, ...) OPAL_OUTPUT_VERBOSE((x, ompi_osc_base_framework.framework_output, __VA_ARGS__))
      |                                  ^~~~~~~~~~~~~~~~~~~
osc_rdma_dynamic.c:315:9: note: in expansion of macro 'OSC_RDMA_VERBOSE'
  315 |         OSC_RDMA_VERBOSE(MCA_BASE_VERBOSE_INFO, "checking attachments at index %d {.base=%p, len=%lu} for attachment %p"
      |         ^~~~~~~~~~~~~~~~
osc_rdma_dynamic.c:316:44: note: format string is defined here
  316 |                          ", region handle=%p", region_index, (void *) region->base, region->len, base, rdma_region_handle);
      |                                           ~^
      |                                            |
      |                                            void *
osc_rdma_dynamic.c:318:26: warning: comparison of integer expressions of different signedness: 'osc_rdma_base_t' {aka 'long long int'} and 'long unsigned int' [-Wsign-compare]
  318 |         if (region->base > (uintptr_t) base || (region->base + region->len) < (uintptr_t) base) {
      |                          ^
osc_rdma_dynamic.c:318:77: warning: comparison of integer expressions of different signedness: 'long long int' and 'long unsigned int' [-Wsign-compare]
  318 |         if (region->base > (uintptr_t) base || (region->base + region->len) < (uintptr_t) base) {
      |                                                                             ^
osc_rdma_dynamic.c:299:9: warning: unused variable 'start_index' [-Wunused-variable]
  299 |     int start_index = INT_MAX, region_index;
      |         ^~~~~~~~~~~
osc_rdma_dynamic.c:298:11: warning: unused variable 'bound' [-Wunused-variable]
  298 |     void *bound;
      |           ^~~~~
```

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
@jjhursey Looks like IBM CI is having a problem - both failures report problems with the infrastructure (probably network down again)

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by gpaulsen** [comment]
Josh and IT are looking at these nodes now.

**Pull request merged**
