### PR TITLE
v5.0.x: Update PMIx/PRRTE submodule pointers

### PR DESCRIPTION
**Pull request by rhc54**
Correct the PMIx version to the HEAD of the v4.2
release branch (it was sitting on the v5.0 branch
for some reason). Update PRRTE to HEAD of the
v3.0 branch.

bot:notacherrypick

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres Okay, I have no idea how to fix the "continuous-integration" CI problem - all it reports is:
```
/usr/bin/env: python3: No such file or directory
```
Any suggestions?z

**Comment by jsquyres** [comment]
> Any suggestions?

This should do it: https://github.com/openpmix/prrte/pull/1792

Sorry for the hassle -- you'll have to pull this all the way on to the PRRTE release branch. ☹️

**Comment by rhc54** [comment]
No worries - thx for the fix! This has been updated to include that patch.

**Comment by rhc54** [comment]
Sigh - truly annoying, but the way this CI works _requires_ that I bring every change around the entire master-to-release-to OMPI cycle just so I can try to see if it will fix the CI's problem. So this is going to take awhile.

@dalcinl Fixing your test suite will probably not happen until later next week.

**Comment by dalcinl** [comment]
> @dalcinl Fixing your test suite will probably not happen until later next week.

Not a big deal from my side, really. Just let's hope no new regressions slip in while we wait for a full resolution.

**Comment by rhc54** [comment]
I give up - there is clearly something wrong in the docs build logic so far as these obscure CI configurations are concerned. With no way of knowing the configuration and little info as to the reason for the failures, there is nothing more I can do...except waste more time.

**Comment by jsquyres** [comment]
> I give up - there is clearly something wrong in the docs build logic so far as these obscure CI configurations are concerned. With no way of knowing the configuration and little info as to the reason for the failures, there is nothing more I can do...except waste more time.

I'll have a look.

**Comment by rhc54** [comment]
@jsquyres was kind enough to resolve the docs build issue. He also restored at least a build level CI for PMIx and PRRTE so hopefully we will catch these things earlier.

Thanks Jeff!

**Pull request merged**
