### PR TITLE
OMPI/OSC/UCX: fix issue in impl of MPI_Win_create_dynamic (v3.1.x)

### PR DESCRIPTION
**Pull request by xinzhao3**
cherry-picked from #5094

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
fixes #5083

**Comment by hjelmn** [comment]
I don't think we agreed on this coming to v3.1.0. If it affect the release date of Friday this week then I would say no.

**Comment by hjelmn** [comment]
Note there should be quick turnaround on v3.1.1

**Comment by jladd-mlnx** [comment]
Shouldn't affect the release date and the priority is set to zero.

**Pull request merged**
