### PR TITLE
v4.1.x: Add Cornelis Networks to the LICENSE file.

### PR DESCRIPTION
**Pull request by mwheinz**
Add Cornelis Networks to the LICENSE file.

bot:notacherrypick

Signed-off-by: Michael Heinz <mheinz@cornelisnetworks.com>

### CODE REVIEW

**Comment by mwheinz** [comment]
bot:notacherrypick

**Comment by mwheinz** [comment]
bot:retest

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
@mwheinz Is there a reason this isn't a cherry pick?  It's committed on master, right?  (ca0f6bfee41ee9ea02826bd059fdd1dc54728410)

**Comment by mwheinz** [comment]
Please note that I cannot merge this PR myself - I don't have the incredible cosmic power required.

**Comment by jsquyres** [comment]
I don't think it matters for this trivial PR, but please do not game the system here: 1) include the proper cherry pick message in your commit message, and b) do not say `bot:notacherrypick` in the PR description.  In doing so, you are specifically working around a CI check that was specifically designed to ensure that our process is followed.

**Pull request merged**
