### PR TITLE
oshmem: add some useless but inoffensive communications and see how o…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…shmem+ucx handles that

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@yosefe there might be.
#4674 fails to pass the CI with UCX, and from my point of view, i do not think the PR itself is to be blamed. at a very early stage, `irecv()` receives truncated message (that is not properly handled, but this is an other issue). the goal of this PR is to get a better picture of what is going wrong.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e9c85b22d9b273bc0d4b9759fb6418fb

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6b75fe520b36c958476b22b25dd29344

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2f9d6eecef186c3bc0f3d0b7c317e1a0

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f236fa19ddd296534d4dd068413b4840

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6daefd4ce9d5b60a396f1175169af8b9

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cd479eee9d454e729dda217c396210cf

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7fcbddbc11d3bbc3422e12ad7b29d0fc

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1f3cd58761d8210f3d9079db09aec046

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ac8ee133e6dd2ca621ea5062cabf31cd

**Comment by ggouaillardet** [comment]
@yosefe there is no problem with UCX nor SHMEM :-)
i did screw up (e.g. `isend(MPI_INT)` but `irecv(MPI_BYTE)`)
iirc, UCX did crash but for some reasons, MXM did not ...

**Pull request closed without merging**
