### PR TITLE
btl/ofi: fix an uninitialized variable

### PR DESCRIPTION
**Pull request by hppritcha**
related to #10986

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>

### CODE REVIEW

**Comment by hppritcha** [comment]
@wckzhang could you review when you get a chance. we need to get this into 5.0.0.
@gpaulsen

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
@hppritcha this is find - but how does it fix the referenced issue? Shouldn't `opal_common_ofi_fi_getname()` on line 599 return an error if this variable isn't initialized?

**Comment by hppritcha** [comment]
no, that function is returning the endpoint name.  but owing to the fact that an error case is being encountered, opal_comm_ofi_fi_getname was never called so ep_name could be pointing to garbage that causes free to blow up in the error handling case.

**Comment by wckzhang** [comment]
I think we saw this exact same thing in the ofi mtl and we fixed it there. The situation was the same (ie. error case is encountered and it blows up because of garbage value and not null. The original code worked but there was a change at one point that caused it to fail and it wasn't picked up because it was the error path.

**Comment by wckzhang** [comment]
Fix in the mtl: c36452f1b1f9919159a185d915ba432c0bf3ac20
The original cause was that ep_name length was changed in this commit - 1a00a89c52e3d535deb818a318b19e48a4905d47

It used to be set as a static size of ep_name[FI_NAME_MAX] and then when we changed it to malloc missed this case. Should have caught the BTL error with the MTL fix but it slipped under our radar.

**Pull request merged**
