### PR TITLE
Update PRRTE and PMIx

### PR DESCRIPTION
**Pull request by rhc54**
- re-enable the timeout, state, and stacktrace testing options

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@artemry-mlnx I checked other PRs and the Mellanox CI is failing everywhere due to the PML/UCX problem with multi-threaded apps. Can you please address it?

**Comment by artemry-mlnx** [comment]
@rhc54 
Disabled thread tests within Mellanox Open MPI CI (https://github.com/mellanox-hpc/jenkins_scripts/pull/95).
Indeed the thread test scenarios should be revisit and reworked.
Thanks for the catch - it seems previously they're passed despite of the error (potentially wrong exit code).

**Comment by rhc54** [comment]
Ah @#$@# - this PR never got reviewed and sat here for nothing.

**Pull request closed without merging**
