### PR TITLE
Fix nidmap computation to deal with hetero nodes

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres Don't run this branch on MTT or it will generate a lot of output. However, it would be good to rerun those cmds and nodes we were using with this so we can track down the source of the error.

**Comment by rhc54** [comment]
Refs #3498

**Comment by rhc54** [comment]
Fixes #3498

**Comment by rhc54** [comment]
<snicker> here is the reported reason for this PR to fail the PR checker:
```
Aborted build: 5 minutes without output.
```

**Comment by bwbarrett** [comment]
Interesting place for that to hang.  I can't see how this patch would cause an infinite loop on autotools running :/.  @hppritcha, can you make sure the Cray isn't totally wonky?

**Comment by rhc54** [comment]
I'm going to assume that something is borked with the cray tester, and go ahead on the basis that everything else checks out okay.

**Pull request merged**
