### PR TITLE
ompi/datatype: make datatype pack thread safe

### PR DESCRIPTION
**Pull request by hjelmn**
This commit makes ompi_datatype_get_pack_description thread safe. The
call is used by osc/pt2pt to send the packed description to remote
peers. Before this commit if MPI_THREAD_MULTIPLE is enabled and the
user uses MPI_Put, MPI_Get, etc we could hit a race where multiple
threads attempt to store the packed description on the datatype. Since
the code in question is not performance-critical the threading fix
uses opal_atomic_* calls instead of bothering with OPAL_THREAD_*.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca Please take a look. This is targeted for 2.0.0.

**Comment by bosilca** [comment]
Make sense, the patch is correct but sub-optimal (the packed description will be generated by all threads and then most of them will drop it).

**Comment by hjelmn** [comment]
@bosilca Was thinking that would be ok in this case. Using atomics avoids adding a lock to the datatype structure. I will see if I can optimize the atomics version a bit more to avoid the the duplicate description generation.

**Comment by hjelmn** [comment]
@regrant This is one found by the rma threading benchmarks.

**Comment by hjelmn** [comment]
@bosilca Ok, optimized it a bit better. Now only one thread will create the datatype description.

**Comment by bosilca** [comment]
@hjelmn this looks good. Thanks for the optimization. :+1:

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
