### PR TITLE
Fix uninitialized variable. Set exit codes for failed launch so we get pretty error messages

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@bwbarrett Sorry to be a pain, but the "default" CI is failing internally - something about resources like Botany Bay and others not being available?

**Comment by hjelmn** [comment]
botanybay was down part of the weekend due to electrical work. My house has some interesting wiring.... Will likely be down for about 6-8 hours the end of this week or next when I finish some new wiring.

**Comment by bwbarrett** [comment]
botanybay being down should be fine; we now have two OS X builders (yay redundancy).  I screwed up the PR builder yesterday while trying to fix how we build dependencies.  I think I have it almost sorted out.

**Comment by bwbarrett** [comment]
bot:ompi:retest

Unfortunately, the "default" was a bad configuration in Jenkins.  There's no good way to remove it, so when the "Pull Request Build Checker" goes green, this is good to merge.

**Comment by rhc54** [comment]
roger that

**Pull request merged**
