### PR TITLE
Make usage of ompi_communicator_t, ompi_file_t and ompi_win_t mutex consistent

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by bosilca** [comment]
I am not sure I follow the logic here. We only need the protection in the multi-threaded case, which would justify the use of OPAL_THREAD_LOCK instead of opal_thread_lock.

**Comment by ggouaillardet** [comment]
@hjelmn can you please comment on that ?

i was mimicking open-mpi/ompi@6b68d1cfc879f38e1a8b2475c4aca2be47202f1b and in this commit you chose to use `opal_mutex_[un]lock()` instead of `OPAL_THREAD_[UN]LOCK()`

**Comment by ggouaillardet** [comment]
incidentally, i noted
 - `ompi_communicator_t` has a `c_lock`
- `ompi_win_t` has a `w_lock`
- `ompi_file_t` has a `f_mutex`

all are `opal_mutex_t`

also, the `OPAL_THREAD_LOCK()` macro invokes `opal_mutex_lock()`

shall i make everything consistent and use only `lock` or `mutex` ?

for example, `OPAL_THREAD_LOCK(&comm->c_lock)` could become `OPAL_MUTEX_LOCK(&comm->c_mutex)`, or `OPAL_THREAD_LOCK(&file->f_mutex)` could become `OPAL_THREAD_LOCK(&file->f_lock)`

**Comment by hjelmn** [comment]
I used the non-conditional lock because the set error handler path is not in the critical path. It could just have easily been OPAL_THREAD_LOCK().

**Comment by bosilca** [comment]
@ggouaillardet makes perfect sense to rename f_mutex into f_lock to match the rest of the components.

**Comment by ggouaillardet** [comment]
@bosilca i updated this PR is order to make everything consistent
 - the `opal_mutex_t` is always called `?_lock`
 - `OPAL_THREAD_[UN]LOCK()` is always used instead of `opal_mutex_[un]lock()`
 - `ompi_communicator_t`'s `c_lock` is now destroyed in the destructor

**Comment by bosilca** [comment]
this looks good 👍 @edgargabriel any feedback about the file changes ?

**Comment by edgargabriel** [comment]
looks good 👍

**Pull request merged**
