### PR TITLE
Fix breakage in ranking system and silence OSC/RDMA warnings

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
bot:retest

**Comment by rhc54** [comment]
@jsquyres Your commit email checker appears to be stuck

**Comment by jsquyres** [comment]
@rhc54 I wonder if github is sometimes not returning all the commits.  Hmm.  I've added some retry logic in the email checker.  We'll see if that helps.

**Comment by rhc54** [comment]
@bgoglin I'm working on the continued ranking problem now

**Pull request merged**
