### PR TITLE
usnic: show the local UDP ports

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@bturrubiates Please review.

This functionality came up the other day when helping debug some cluster-setup issues; we wanted to trace the traffic from one MPI process to another, but MPI processes didn't provide diag output indicating their source IP address *and UDP port*.  This commit adds verbose output (when running with `--mca btl_base_verbose`) that shows both the local UDP ports, and also, when "connecting" to a remote peer, show both the local and remote IP/UDP ports.  It's solely for diagnostic / verbose output purposes.

**Comment by jsquyres** [comment]
@bturrubiates actually recommends this kind of thing: https://gist.github.com/jsquyres/dd959a48b6d9d34a41261c7cf7998a5e

I don't have time to look at this at the moment, but wanted to stash it here so I don't lose it.

**Comment by jsquyres** [comment]
@bturrubiates Updated with your suggestion.  Have a look.

**Comment by jsquyres** [comment]
@bturrubiates Got your latest feedback in this update.

**Comment by bturrubiates** [comment]
Looks good 👍

**Comment by jsquyres** [comment]
I'm not sure why the Mellanox Jenkins would timeout in its test; this PR only deals with code in the usnic BTL, which the Mellanox Jenkins does not test.

**Pull request merged**
