### PR TITLE
Fix Issue 2115

### PR DESCRIPTION
**Pull request by hppritcha**
Okay this is kind of an omnibus merge.  There was a direct-inject-in-to-master commit
from @bosilca to fix some things that went in with PR #2054.  So this PR has
the commit from #2054 plus the direct inject in to master commit 93fa94f9 plus an additional
commit to suppress a compiler warning 

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
not sure why the signed-off checker failed

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
signed the commits myself. 

@bosilca we're going to start reverting direct commits to master that don't have a sign-off.  That's needed now.

**Comment by hppritcha** [comment]
LANL CI down today due to NERSC quarterly maintenance

**Comment by hppritcha** [comment]
@jsquyres did you have anything else to change here except the sign off?  That's fixed now.

**Comment by hppritcha** [comment]
@jsquyres good to go.

**Pull request merged**
