### PR TITLE
opal/pmix: Add external pmix library support

### PR DESCRIPTION
**Pull request by igor-ivanov**
Fixes https://github.com/open-mpi/ompi/issues/1064

@rhc54 @jsquyres @artpol84 could you review

### CODE REVIEW

**Comment by miked-mellanox** [comment]
@igor-ivanov , @jsquyres  - do we need to update ompi.spec to BuildRequest pmix/libevent and same for Request: sections?

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by rhc54** [comment]
@igor-ivanov At the developer telecon, we decided that we need to retain the symbol renaming, and everyone was happier with the idea that use of external pmix also require use of external libevent and hwloc. So I took your changes, removed the renaming mods, added the required build changers, and reposted it as #1226 .

**Pull request closed without merging**
