### PR TITLE
Remove a few more remnants of zlib

### PR DESCRIPTION
**Pull request by jsquyres**
The compress framework was removed in 66da0c63, but these bits escaped
removal.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7ef403040df5ced1fef99ebf2d1e3a40

**Comment by jjhursey** [comment]
The XL failure is real, but not related to this PR. I've seen mpirun/prun crash like that before. We need to track it down, but it is intermittent.
bot:ibm:xl:retest

**Comment by jjhursey** [comment]
bot:ibm:xl:retest

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest
Sorry retested the wrong thing.

**Comment by jsquyres** [comment]
@artemry-mlnx It looks like Mellanox CI died again -- https://dev.azure.com/mlnx-swx/mellanox-ompi/_build?definitionId=12 shows 4 jobs queued in the Mellanox CI, the longest from 9h ago.  Can you check?

**Comment by jsquyres** [comment]
Mellanox has been hung for 9+ hours -- not going to wait for it.

**Comment by artemry-mlnx** [comment]
@jsquyres 
Restarted the CI agents. There were some strange Azure agent crashes - under investigation.
Sorry for the inconvenience.

**Pull request merged**
