### PR TITLE
v4.0.0: text updates

### PR DESCRIPTION
**Pull request by jsquyres**
This is the v4.0.x version of #6026.

Also need to pull the contents of #6028 into this PR.

### CODE REVIEW

**Comment by jsquyres** [comment]
Meh; got confused about my

**Comment by jsquyres** [comment]
Do not merge this yet; still needs the changes from #6028.

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
After some confusion on my part, everything should be straightened out now -- this PR is good to merge after #6051 has been merged on master.

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
This v4.0.0 PR is now good to go (i.e., all the commits on this PR have now been merged to master).

**Pull request merged**
