### PR TITLE
Update PMIx and PRRTE

### PR DESCRIPTION
**Pull request by rhc54**
PMIx
- ensure cleanup of fork/exec children

PRRTE
- fix multi-app bugs
- port setup_child logic from orte
- OMPI env changes
- set app->first_rank

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ac490848d2c8e492a7b1b0f0c5bf7df3

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6bd7af2cc3f3e32e4845cbebff64439c

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/709fb4014edd64d027d3a2c21fa17e39

**Comment by rhc54** [comment]
cute - all the IBM tests failed on a "signal 15" from the test harness

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fcae6cab85ef58f0d5562ee3d6ab0575

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/eba458eac593dfaaf108ba053bda73d5

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d40f6caf2f312925d7f30d28557a2e8d

**Comment by rhc54** [comment]
same thing - looks like something is wrong with IBM tonight

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b6a1a31c2249f98d51847776d01f081f

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a71bbd2b6416e2d7be04b1c993a3353c

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/dfec663adc80321919df8d2335f73a42

**Comment by jjhursey** [comment]
It looks like autogen is taking more than 20 minutes to complete (it usually takes 3 minutes), so it is hitting a timeout. I'll take a look at what might be going on.

**Comment by jjhursey** [comment]
The main CI node was wedged in an odd state and it took a while to get it back. Let's give it another go.
bot:ibm:retest

**Comment by rhc54** [comment]
Let's hold off on committing this for a bit - there are some issues I've uncovered. If I can get it fixed today, I'll update. Otherwise, we'll commit this towards the end of the day and file a "fix it" PR over the weekend.

**Pull request closed without merging**
