### PR TITLE
pmix: fix PMIx envar name for the installation prefix.

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
Address #3980

**Comment by artpol84** [comment]
Per discussion in #3985

**Comment by artpol84** [comment]
I've verified that at runtime and master works fine in this case.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by artpol84** [comment]
@rhc54 I think this implements solution suggested in https://github.com/open-mpi/ompi/pull/3985#issuecomment-319529424

**Comment by artpol84** [comment]
I verified both at runtime for my case - they solve it

**Pull request merged**
