### PR TITLE
C99 component initialization

### PR DESCRIPTION
**Pull request by hjelmn**
This set of commits modifies every component in  Open MPI to use c99 subobject initialization.

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres, @rhc54, @miked-mellanox 
Let me know if you see anything wrong. The modifications had to be done by hand so there is a chance i screwed something up.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/456/

**Build Log**
*last 50 lines*

 ```
[...truncated 5787 lines...]
Making install in mca/if/linux_ipv6
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/if/linux_ipv6'
  CC       if_linux_ipv6.lo
  CCLD     libmca_if_linux_ipv6.la
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/if/linux_ipv6'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/if/linux_ipv6'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/if/linux_ipv6'
Making install in mca/installdirs/env
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/env'
  CC       opal_installdirs_env.lo
  CCLD     libmca_installdirs_env.la
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/env'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/env'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/env'
Making install in mca/installdirs/config
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/config'
  CC       opal_installdirs_config.lo
  CCLD     libmca_installdirs_config.la
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/config'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/config'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/installdirs/config'
Making install in mca/memchecker/valgrind
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/memchecker/valgrind'
  CC       memchecker_valgrind_component.lo
  CC       memchecker_valgrind_module.lo
memchecker_valgrind_component.c:66: error: unknown field 'mca_query_compnent' specified in initializer
make[2]: *** [memchecker_valgrind_component.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/memchecker/valgrind'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi/commit/c174d1f78c6a49f3e0da12111b54d3ed11614175
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of dc6ee0233b373d0067b337b3bdb5d4de4296c79d to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/456/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/457/

**Build Log**
*last 50 lines*

 ```
[...truncated 14 lines...]
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi/commit/224b4e853b98738f371a35a79db248483e7da21c
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: {"message":"No commit found for SHA: 224b4e853b98738f371a35a79db248483e7da21c","documentation_url":"https://developer.github.com/v3/repos/statuses/"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:496)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:127)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/open-mpi/ompi/statuses/224b4e853b98738f371a35a79db248483e7da21c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/open-mpi/ompi/statuses/224b4e853b98738f371a35a79db248483e7da21c
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of c4a61969c000d5ea75cbdd21c3a5efe78d26f32d to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/457/ and message: Merged build finished.
```

Test FAILed.

**Comment by hjelmn** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 908 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_458/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_458/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_458/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/458/
Test PASSed.

**Comment by hppritcha** [comment]
Maybe I'm missing something in the README, but shouldn't we add something about need for a c99 compliant compiler?  Maybe the contents of the Compiler Notes section might need revisiting?

**Comment by hjelmn** [comment]
@hppritcha Good point. We have been requiring a c99 compiler since 1.5 but never added it to the README.

**Comment by jsquyres** [comment]
We actually started requiring a C99 compiler in v1.7[.0], and we noted it in the NEWS back then.

**Comment by hjelmn** [comment]
Hmm, thought it was earlier than that. Guess 1.7 has been around for awhile.

**Comment by jsquyres** [comment]
@hjelmn This PR builds for me.  Huzzah!

**Comment by hjelmn** [comment]
Builds for Mellanox as well. Not sure which components that leaves untested.

**Comment by jsquyres** [comment]
At this point, I'd say we have pretty good coverage.  My $0.02: merge to master and let's see if anything breaks.

**Comment by hppritcha** [comment]
I'm good with merging to.  Perhaps PH's computer museum will hit issues, but that's okay.

**Comment by hjelmn** [comment]
Running an icc build on Cielito right now. If that completes ok I will merge this.

**Comment by hjelmn** [comment]
Good to go.

**Pull request merged**
