### PR TITLE
Allow PSM2 get its TransportKey from PMIx

### PR DESCRIPTION
**Pull request by marisaroman-cornelisnetworks**
This piece removes the need of a psm2 env var for the TransportKey and now it gets it from PMIx.

### CODE REVIEW

**Review by jsquyres — COMMENTED** [review]
Do you need a copyright for your company in there?

Also, it doesn't really matter to much, but did you intend this to be 2 commits instead of 1?

**Comment by marisaroman-cornelisnetworks** [comment]
There were two commits because the strdup part was missing from the first commit.

**Comment by jsquyres** [comment]
@marisaroman-cornelisnetworks Understood.  What I was suggesting is that it's not important to preserve these as two commits in the git history -- squashing them down to a single commit would be nice.

**Comment by marisaroman-cornelisnetworks** [comment]
Of course... I will do that next time.
Thanks!

**Review by rhc54 — APPROVED** [review]

**Comment by marisaroman-cornelisnetworks** [comment]
YAY!!!! thanks

**Pull request merged**
