### PR TITLE
common/ucx: fix variable registration

### PR DESCRIPTION
**Pull request by jjhursey**
The registration code in common/ucx was overly complex. It assumed
that re-registration is not desireable when it essentially does the
same as the find before the registration. The only thing that needs
protection is resetting the char * variables before they are
registered.

The primary purpose of this commit to fix two memory leaks caused
by the extra allocations to hold the strings. These allocations
are unnecessary.

-----
Fix the MCA registration modeling it after the common/ofi component.

bot:notacherrypick

### CODE REVIEW

**Comment by jjhursey** [comment]
* `main` version already committed https://github.com/open-mpi/ompi/pull/10105
 * `v5.0.x` version already committed https://github.com/open-mpi/ompi/pull/10229

This was found by MTT testing on ppc64le (regardless of compiler) and configured with
```
./configure --prefix=$MPI_ROOT --without-hcoll --enable-debug \
    --enable-mpirun-prefix-by-default --disable-dlopen --enable-io-romio \
    --disable-io-ompio --enable-mpi1-compatibility --with-ucx=/opt/ucx/
```
I believe that the `--disable-dlopen` is necessary. Without it the test seemed to run fine. With it I would get a segv with the stack below 100% of the time in `MPI_Init`:
```
(gdb) bt
#0  0x00007fffb635c5fc in __strcmp_power8 () from /lib64/libc.so.6
#1  0x00007fffb5c3a014 in opal_common_ucx_support_level (context=0x1002bb0b3f0) at common_ucx.c:233
#2  0x00007fffb6866e50 in mca_pml_ucx_component_init (priority=0x7fffca1e4dc0, enable_progress_threads=false, enable_mpi_threads=false)
    at pml_ucx_component.c:131
#3  0x00007fffb6858e50 in mca_pml_base_select (enable_progress_threads=false, enable_mpi_threads=false) at base/pml_base_select.c:127
#4  0x00007fffb68e5344 in ompi_mpi_init (argc=0, argv=0x0, requested=0, provided=0x7fffca1e5020, reinit_ok=false) at runtime/ompi_mpi_init.c:647
#5  0x00007fffb664ffa4 in PMPI_Init (argc=0x0, argv=0x0) at pinit.c:69
#6  0x00000000100016b0 in main (argc=1, argv=0x7fffca1e54f8) at attr-error-code.c:28
(gdb) p *opal_common_ucx.tls
$3 = 0x0
(gdb) p *opal_common_ucx.devices
$4 = 0x0
```

The problem is the same one that Nathan fixed for `main` and `v5.0.x`.

**Comment by jjhursey** [comment]
I'm able to reproduce the `ompi_info` segv. From the stack it has something to do with the `tls` registration. I'm looking into it now. Good on CI for catching that!

**Comment by jjhursey** [comment]
I pushed a new commit to this PR that addresses the `ompi_info` segv that CI caught. The issue that caused the segv is described in the previous comment. The solution was to add one level of indirection to put the string on the heap - modeled after what common/ofi does with its MCA parameters.

This PR is ready to go.

**Review by janjust — APPROVED** [review]

**Pull request merged**
