### PR TITLE
v5.0.x: Pull in the topology early and set cache line size

### PR DESCRIPTION
**Pull request by gpaulsen**
Init PMIx and get the topology immediately after setting up opal
util as neither of those operations requires any real OPAL support.
This fills in the cache line size before anything else is opened.

Signed-off-by: Ralph Castain <rhc@pmix.org>

NOTE: This PR #8761 also updates both PMIx and PRRTE submodules.
(cherry picked from commit 6b19e4ad6f60e991f1182cc80da8158dd7f97aca)

### CODE REVIEW

**Comment by gpaulsen** [comment]
@rhc54 I cherry picked this to v5.0.x.  I was a bit surprised that git complained that the submodule pointer was a conflict, but after investigating, I believe that ompi/v5.0.x's prrte/master hash just wasn't in sync with ompi/master's prte/master hash.  Wow, that's a mouthful.  Since both ompi/master and ompi/v5.0.x are still tracking prrte/master, I just set the this commit to the same prrte/master hash that you set it to in the ompi/master PR #8760.

**Comment by gpaulsen** [comment]
oh right also contrib/platform/intel/bend/mac was conflicted, so I set it to the same as the content on master.  no idea why it wasn't the same.  Please check.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e36bb1fa2f1ce0fb787a0c3ca6ff5dd1

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/04612070ed6b67ef94654204bc845c6f

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3afec3867ea8eec4c7c233345079ae1a

**Comment by rhc54** [comment]
@gpaulsen I have update the PMIx v4.0.1 pointer and switched the PRRTE submodule to the new v2.0 branch. This will resolve the prior CI failures

**Review by rhc54 — APPROVED** [review]

**Comment by gpaulsen** [comment]
Thanks.

**Review by awlauria — APPROVED** [review]

**Comment by gpaulsen** [comment]
fixes https://github.com/open-mpi/ompi/issues/7937

**Pull request merged**
