### PR TITLE
OPAL: Rewrite of registration caches

### PR DESCRIPTION
**Pull request by hjelmn**
This PR rewrites the code underlying the primary registration cache (rcache/grdma). The updated code is multi-reader, single-writer thread safe. This greatly reduces the bottlenecks when using the registration cache from multi-threaded programs.

The thread-safety is provided by a 1-dimensional interval tree (see CLRS textbook "Introduction to Algorithms") implemented using a relativistic red-black tree. More information about the red-black tree can be found in the following paper: http://onlinelibrary.wiley.com/store/10.1002/cpe.3157/asset/cpe3157.pdf?v=1&t=jddfnb4n&s=63a9b1a0be52676242f7b422e6a9224c3838f892

### CODE REVIEW

**Comment by hjelmn** [comment]
@hppritcha This is the rcache rewrite.

**Comment by hjelmn** [comment]
@regrant This fixes one of the major bottlenecks in osc/rdma identified by RMA-MT.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e2a1ddcbbd9f28ecc12c00f23d14fb0f

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/508b835edaa2cb01e0b2486ea3297376

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/78acff70611f18cc25991715e18d977c

**Comment by hjelmn** [comment]
@thananon FYI. This may also improve performance for large two-sided messaging.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hjelmn** [comment]
Found some bugs during stress tests. Think I have them all fixed and this is the final version. This is necessary to get full performance from RMA-MT with some upcoming osc/rdma and btl/ugni updates.

**Pull request merged**
