### PR TITLE
Allow MPI_ANY_SOURCE in MPI_Sendrecv_replace.

### LINKED ISSUE #3496: MPI_ANY_SOURCE in MPI_Sendrecv_replace
The following code causes seg. fault problem. The initial check shows that it seem caused by ompi_comm_peer_lookup with MPI_ANY_SOURCE, which somehow messes up the allocated  temporary buffer used in SendRecv.

any idea?

Dahai

```c
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <sys/types.h>
#include <errno.h>
#include <unistd.h>
#include <values.h>

int main(int argc, char *argv[]) {

   int          local_rank;
   int          numtask, myrank;
   int          count;

   MPI_Status   status;

   long long   *msg_sizes_vec;
   long long   *mpi_buf;
   long long    host_buf[4];

   int          send_tag;
   int          recv_tag;
   int          malloc_size;
   int          dest;

    MPI_Init(&argc,&argv);

    MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
    fprintf(stdout,"my RanK is %d\n",myrank);

    MPI_Comm_size(MPI_COMM_WORLD, &numtask);
    fprintf(stdout,"Num Task is %d\n",numtask);

    malloc_size=32;
    count = malloc_size / sizeof(long long);
    dest = (myrank+1)%2;
    fprintf(stdout,"my dest is %d\n",dest);


    host_buf[0] = 100 + myrank;
    host_buf[1] = 200 + myrank;
    host_buf[2] = 300 + myrank;
    host_buf[3] = 400 + myrank;

    fprintf(stdout,"BEFORE %lld %lld %lld %lld \n",host_buf[0],host_buf[1],ho st_buf[2],host_buf[3]);
    fflush(stdout);
    fprintf(stdout,"Doing sendrecv_replace with host buffer\n");
    fflush(stdout);

    MPI_Sendrecv_replace ( host_buf,
                             count,
                     MPI_LONG_LONG,
                              dest,
                            myrank,
                              MPI_ANY_SOURCE,
                              dest,
                    MPI_COMM_WORLD,
                           &status);

    fprintf(stdout,"Back from doing sendrecv_replace with host buffer\n");
    fprintf(stdout,"AFTER %lld %lld %lld %lld \n",host_buf[0],host_buf[1],ho st_buf[2],host_buf[3]);
    fflush(stdout);


    MPI_Finalize();
    exit(0);
}
```

### PR DESCRIPTION
**Pull request by bosilca**
Fixes #3496.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by mathbird** [comment]
Thanks, George. It works, even for more complicated tests with a ring. 

Dahai

**Comment by mathbird** [comment]
when will it be merged into the master branch?

**Comment by jsquyres** [comment]
@bwbarrett @hppritcha How far back do we want to include this fix?  v2.0.x?  v2.x?  3.0.x?

**Comment by hppritcha** [comment]
Since it's a bug I think we should apply to 3 2.0.x and 2.1.x.  Would be great to get into 2.0.x before doing the next release.

**Comment by jjhursey** [comment]
If you take PR #3500 into the release branches then you also need PR #3635

**Pull request merged**
