### PR TITLE
mtl,btl/ofi: pass job id to providers via auth_key

### PR DESCRIPTION
**Pull request by j-xiong**
The OFI psm2 provider needs a unique job key for setting up endpoints.
With commit "https://github.com/ofiwg/libfabric/commit/aafc9af6dcce"
the OFI psm2 provider can accept the job key passed via the auth_key
field of ep_attr. Such mechanism is generic and can be utilized by
other providers when necessary.

A unique job id is already available at the MPI layer. Construct a
key from the job id to fit the provider specific size requirement
and then pass to the provider.

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@j-xiong thanks for the PR.

ok to test

I have two questions about these changes:
 - are they supposed to work with `libfabric` older than the mentioned commit?
 - what about `MPI_Comm_spawn()`? my concern is that `OMPI_PROC_MY_NAME->jobid` is not the same between the parent and the child communicator. How does this impact `libfabric` connectivity?

**Comment by rhc54** [comment]
@j-xiong Could you please explain a little about the context behind this PR? I'm asking because we already pass an auth key for PSM2 to use (it is passed in the environment) and I don't understand why this PR is needed.

@mwheinz Any ideas here?

As to comm_spawn: PSM2 cannot communicate across jobs and (last I checked) doesn't support comm_spawn'd jobs.

**Comment by mwheinz** [comment]
I agree with Ralph - we already have a key exchange mechanism in place. What does do that improves on the existing method?

**Comment by j-xiong** [comment]
@ggouaillardet (1) The patch has no effect for older libfabric. (2) Processes with different jobid can't communicate with each other.

@rhc54  There is an environment variable passed for the psm2 mtl in the 4.1.x branch. It's no longer set in the master branch after moving from orte to prrte.

**Comment by mwheinz** [comment]
@j-xiong, thanks for the explanation - I wasn't aware of that change in the master branch. 

@acgoldma - were you aware of this? It might impact you as well.

**Comment by rhc54** [comment]
I appreciate the explanation - that confirms what I suspected, so let me propose an alternate solution.

About 1-2 years ago, we shifted responsibility for generation of the psm2 key from the runtime to PMIx (we left orte alone as it wasn't worth changing it there give the plan to replace orte with prrte). Rationale for doing so was to ensure that psm2 could be used regardless of the launcher being employed. Until that time, we had to ask every RM to write psm2-specific code to generate it for us, or else psm2 had to write RM-specific code to create one internally. Neither of those solutions was desirable - but as PMIx became more generally used, it was possible to just do it in that one place.

Several runtimes (including PRRTE) have taken advantage of that capability. However, with the uncertainty over psm2's future last year, we disabled it in PMIx 4.0. Thus, current OMPI master lacks that support.

I recently pinged Mike about restoring the psm2 support in PMIx, which is a somewhat broader topic than just this authentication key. However, we could do the restoration in two parts, bringing back the key generation first and then dealing with the rest of it.

@mwheinz How would you prefer to proceed? I'd rather we keep support in PMIx instead of adding it as per this PR so it remains broadly available in a consistent manner, but it is your product 😄

**Comment by mwheinz** [comment]
> @mwheinz How would you prefer to proceed? I'd rather we keep support in PMIx instead of adding it as per this PR so it remains broadly available in a consistent manner, but it is your product 😄

@rhc54 - given the recent revivification of OPA, we would very much like to support PMIX if we can. I've sent you an email to start discussing it.

**Comment by ToddRimmer** [comment]
There are additional OFI providers being developed which also need the auth_key feature in a manner similar to PSM2's past requirements.  So please keep myself and @acgoldma in the discussion.

**Comment by rhc54** [comment]
Hi Todd - I'll defer to Mike to revise the email thread participants. Meantime, I'll summarize my description of the fabric support in PMIx here. You and I have discussed pretty much all of this at one time or another in the past, so nothing particularly new here.

Each fabric has its own plugin within which the vendor can support (or not) whatever parts of the PMIx Standard they choose. Each plugin is called by the system launcher prior to initiating the launch and given a complete "picture" of what ranks will be placed on which nodes and their location on that node (i.e., where they will be bound). The plugin then has the opportunity to provide whatever information it can/wants (e.g., assigning endpt addresses and auth_keys) - this is conveyed to the backend nodes as a "blob". When the info arrives at a backend node, the "blobs" are separated out and given to the PMIx server's plugin on that node for processing.

There are also interfaces for directly obtaining access to fabric manager info. These are generally accessed by the scheduler and/or debugging tools, though there is no restriction in that regard.

Here is a brief list of the various areas covered by the Standard and implemented in PMIx:

* basic MPI communication support - e.g., create a transport auth_key. We have provided this key in the environment in the past because that is how OMPI originally did it, but I'd prefer to migrate to retrieving it directly from PMIx using the PMIx_Get interface if possible. Makes for a cleaner and more reliable hand-off.

* "instant on" support. This would allow the application to start communicating without that poorly-scaling global endpoint exchange. It means you must have a mechanism for computing the equivalent of a static TCP port for each process. Some fabrics may have an issue with doing this computation, but we believe we (Amazon and I) have found potential solutions for the most common of them. If someone is interested in this area, it might merit a discussion - there is a proposal for implementing the necessary support in OFI (https://github.com/ofiwg/libfabric/issues/5719)

* fabric topology info. This exposes the fabric topology to the scheduler so it can take that into account when making allocations - basically replaces the text file that sys admins otherwise have to create and maintain with a dynamic API. Requires that you provide some code to query the required information from your fabric manager.

* fabric traffic reports. This allows debuggers and other tools to query traffic loads - think of it as providing a mechanism by which a debugger could present a graphical display of traffic "choke points". Lots of interest here from the debugger and lab communities - we just need to create the capability.

We have an example for Slingshot already in the code base that supports all but the last of these areas (could easily be extended to meet them all, if someone wants to do so).

**Comment by rhc54** [comment]
IIRC, @hppritcha was going to add PMIx hooks to the common code in OFI, so that might be a good place to retrieve the fabric credential. I don't know where that work sits right now - Howard?

**Comment by mwheinz** [comment]
Well, there's also the issue of the PSM2 MTL...

**Comment by hppritcha** [comment]
@rhc54 i deferred add pmix hooks (which at the time I was thinking just for the GNI provider) since i found a workaround to avoid using the problematic way the GNI provider was implementing libfabr Mr. Scalable memory registration model.
Maybe its time to reconsider though.

**Comment by hppritcha** [comment]
Oh I got confused about the PMIx hooks you were referring to @rhc54 .  I was considering something for libfabric itself.
I'd

**Comment by rhc54** [comment]
Right - I was referring to adding PMIx hooks directly to libfabric. If multiple providers need access to info available via PMIx, it might be more portable and less work to do it that way. Can always use the "optional" flag to allow a fallback method if PMIx isn't there or doesn't have the required info - which should hopefully become less and less of an issue going forward.

**Comment by hppritcha** [comment]
oh okay I'll take a look at that.   slingshot approach looks interesting though (what's in pmix master).    wouldn't we need a generic libfabric pnet component that could be used within libfabric?

**Comment by rhc54** [comment]
> oh okay I'll take a look at that. slingshot approach looks interesting though (what's in pmix master). wouldn't we need a generic libfabric pnet component that could be used within libfabric?

Yes, that would be one approach. If libfabric did take advantage of PMIx directly, then we could go with a generic plugin. Without that, we've been taking the vendor-at-a-time approach, which is less efficient (IMO).

**Comment by rhc54** [comment]
Please note that I restored PSM2 support on OMPI master by bringing back the PSM2 support in PMIx (and switching the PMIx submodule back to the PMIx master branch).

@j-xiong Please confirm that OMPI master now works for you, minus this PR.

We can continue the discussion regarding the correct long-term solution. I just wanted to get the PMIx support restored so that people using non-PRRTE environments would have it back.

**Comment by j-xiong** [comment]
Yes, I confirm that the master branch now have the same environment variable as in 4.x exported for job key.

**Comment by hppritcha** [comment]
fixed via PRs
https://github.com/openpmix/openpmix/pull/2019
https://github.com/ofiwg/libfabric/pull/6498
https://github.com/open-mpi/ompi/pull/8382

**Pull request closed without merging**
