### PR TITLE
pmix: fixed immediate request

### LINKED ISSUE #3977: v3.0.x: PMIx v1.2 external doesn't work with v3.0.x
The problem reproduced with v3.0.x and PMIx v1.2 as external component and`hello_c` program.

There is a hang when the client is trying to request a key from the server:
```
(gdb) bt
#0  0x00007f8e9378ff3d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f8e937c14a4 in usleep (useconds=<optimized out>) at ../sysdeps/unix/sysv/linux/usleep.c:32
#2  0x00007f8e90748997 in PMIx_Get (proc=0x7ffd021e0a10, key=0x7f8e913b21bf "pmix.appnum", info=0x0, ninfo=0, val=0x7ffd021e0a00) at src/client/pmix_client_get.c:104
#3  0x00007f8e909a3cae in pmix1_get () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/openmpi/mca_pmix_ext1x.so
#4  0x00007f8e913b13c8 in rte_init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/openmpi/mca_ess_singleton.so
#5  0x00007f8e93437929 in orte_init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/libopen-rte.so.40
#6  0x00007f8e93cffa75 in ompi_mpi_init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/libmpi.so.40
#7  0x00007f8e93d21deb in PMPI_Init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/libmpi.so.40
#8  0x00000000004009ae in main ()
```

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #3978 

Fixed #3977

### CODE REVIEW

**Comment by bwbarrett** [comment]
Please don't file PRs against release branches until the corresponding PR has made its way through master.  Then please file a PR against the release branch with a cherry-pick note in the commit message (`git cherry-pick -x` is your friend).  You can remove the "pushed-back" label and we'll look at this PR when #3978 is in master and the commit has been updated appropriately.

**Comment by artpol84** [comment]
@bwbarrett
Sorry for the mess, I didn't communicate properly the decisions we made on the dev meeting to @karasevb.

**Comment by bwbarrett** [comment]
@artpol84, no worries at all.

@karasevb, rhc merged your patch into master, so if you update this one with the cherry pick information, we should be good to go.

We've already cut 3.0.0rc2, but we'll make sure this is in 3.0.0 (ie, we'll get to do 3.0.0rc3).

**Comment by artpol84** [comment]
@bwbarrett thank you, This will be done tonight.

**Comment by artpol84** [comment]
@bwbarrett should be ok now

**Pull request merged**
