### PR TITLE
op_avx: Fix MCA enum flags

### PR DESCRIPTION
**Pull request by jsquyres**
Remove accidental double registration (which resulted in a double
RELEASE/free).

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1385fb9e2cf54e7f6263e623e27c6c07

**Review by bosilca — APPROVED** [review]

**Review by rajachan — APPROVED** [review]
You beat me to a PR.

**Comment by jjhursey** [comment]
IBM Ci had an issue over the weekend. Retrying. bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/01585f436ec8fbfbc9c2d03a13eb18b0

**Pull request merged**
