### PR TITLE
Update ORTE/OPAL to latest commits, including PMIx v2.0.0rc1 (with thread safety)

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5085917e4590b1abbb6c40406b58341b

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/094f7b38c13567e80428b9a027a30aea

**Comment by rhc54** [comment]
@artpol84 Can you please take a look at this PR with respect to oshmem? I'm not sure why it is failing, but it only seems to be happening in oshmem.

**Comment by rhc54** [comment]
bot:ompi:retest

**Comment by artpol84** [comment]
@karasevb please investigate ASAP

**Comment by rhc54** [comment]
Just to coordinate here: I think there is still a race condition either in the client code that can cause the server peer object to be released too soon, or in the server code that can allow the host daemon to terminate too early (thus generating a "lost connection" in the client). I haven't been able to track it down.

We also know there is a rare, but repeatable, chance of hanging in finalize. This is seen in the Pull Request Build Checker tests.

I ran this branch through ```valgrind --tool=helgrind``` and got a ton of warnings about thread safety. Most of these were expected from testing the "initialized" value at the beginning of user-facing functions. Helgrind also doesn't like us modifying the "active" flag in a callback function while another thread is looping in PMIX_WAIT_FOR_COMPLETION on it. I'm working on cleaning those up by replacing them with proper lock/wait semantics. I don't believe these are the cause of the problems seen here.

@jjhursey plans to take a look at this on Fri here in the States. Let's post what we find here so we can coordinate until we find a solution.

**Comment by rhc54** [comment]
I pushed a first pass at adding the lock/wait semantics, this commit covering just the pmix_client.c code. I'll work thru the rest of the client side before doing the server, and then the infrastructure

**Comment by rhc54** [comment]
Finally got a stack trace from one of the hanging jobs:
```
Waiting for stack traces (this may take a few moments)...
STACK TRACE FOR PROC [[8676,1],1] (ip-172-31-12-55, PID 4986)
	Thread 3 (Thread 0x7faadf02e700 (LWP 4990)):
	#0  0x00007faae1ecb313 in epoll_wait () from /lib64/libc.so.6
	#1  0x00007faae18a24c3 in epoll_dispatch (base=0xbc7b90, tv=<optimized out>) at epoll.c:407
	#2  0x00007faae18a5f10 in opal_libevent2022_event_base_loop (base=0xbc7b90, flags=1) at event.c:1630
	#3  0x00007faadf8cacce in progress_engine () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/openmpi/mca_pmix_pmix2x.so
	#4  0x00007faae218c734 in start_thread () from /lib64/libpthread.so.0
	#5  0x00007faae1ecad3d in clone () from /lib64/libc.so.6
	Thread 2 (Thread 0x7faae0304700 (LWP 4988)):
	#0  0x00007faae1ec249d in poll () from /lib64/libc.so.6
	#1  0x00007faae18ae266 in poll_dispatch (base=0xb9d070, tv=0x7faae0303ee0) at poll.c:165
	#2  0x00007faae18a5f10 in opal_libevent2022_event_base_loop (base=0xb9d070, flags=1) at event.c:1630
	#3  0x00007faae18671be in progress_engine () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/libopen-pal.so.0
	#4  0x00007faae218c734 in start_thread () from /lib64/libpthread.so.0
	#5  0x00007faae1ecad3d in clone () from /lib64/libc.so.6
	Thread 1 (Thread 0x7faae28b1700 (LWP 4986)):
	#0  0x00007faadf887272 in OPAL_MCA_PMIX2X_PMIx_Finalize () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/openmpi/mca_pmix_pmix2x.so
	#1  0x00007faadf86226f in pmix2x_client_finalize () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/openmpi/mca_pmix_pmix2x.so
	#2  0x00007faae1b8bdc1 in orte_ess_base_app_finalize () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/libopen-rte.so.0
	#3  0x00007faae030689d in rte_finalize () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/openmpi/mca_ess_pmi.so
	#4  0x00007faae1b4b04a in orte_finalize () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/libopen-rte.so.0
	#5  0x00007faae23f3d55 in ompi_mpi_finalize () from /home/ec2-user/workspace/open-mpi.build.platforms/Platform/sles12sp2/install/lib/libmpi.so.0
	#6  0x00000000004009ef in main (argc=1, argv=0x7ffd4f39e848) at hello_c.c:24
```
So it appears that every so often, the client doesn't get a response to its finalize message. What remains unclear is if the server sent it and the client somehow lost it, or the server never sent it.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2c58968d6912d64ddb99a21d9b9b0461

**Comment by rhc54** [comment]
@jjhursey Can you please take a look at this and see where it is failing? It works perfectly for me, so there must be something either not pushed or maybe not initialized.

**Comment by rhc54** [comment]
MTT results do show some issues:
```
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                          |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| MPI Install | my installation | 3.0.0a1     | 00:00    | 1    |      |          |      | MPI_Install-my_installation-my_installation-3.0.0a1-my_installation.html |
| Test Build  | trivial         | 3.0.0a1     | 00:02    | 1    |      |          |      | Test_Build-trivial-my_installation-3.0.0a1-my_installation.html          |
| Test Build  | ibm             | 3.0.0a1     | 00:45    | 1    |      |          |      | Test_Build-ibm-my_installation-3.0.0a1-my_installation.html              |
| Test Build  | intel           | 3.0.0a1     | 01:17    | 1    |      |          |      | Test_Build-intel-my_installation-3.0.0a1-my_installation.html            |
| Test Build  | java            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Build-java-my_installation-3.0.0a1-my_installation.html             |
| Test Build  | orte            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Build-orte-my_installation-3.0.0a1-my_installation.html             |
| Test Run    | trivial         | 3.0.0a1     | 00:08    | 7    | 1    |          |      | Test_Run-trivial-my_installation-3.0.0a1-my_installation.html            |
| Test Run    | ibm             | 3.0.0a1     | 19:27    | 491  | 10   | 5        |      | Test_Run-ibm-my_installation-3.0.0a1-my_installation.html                |
| Test Run    | spawn           | 3.0.0a1     | 02:05    | 6    | 6    | 1        | 1    | Test_Run-spawn-my_installation-3.0.0a1-my_installation.html              |
| Test Run    | loopspawn       | 3.0.0a1     | 00:15    |      | 1    |          |      | Test_Run-loopspawn-my_installation-3.0.0a1-my_installation.html          |
| Test Run    | intel           | 3.0.0a1     | 28:42    | 454  | 13   | 7        | 4    | Test_Run-intel-my_installation-3.0.0a1-my_installation.html              |
| Test Run    | intel_skip      | 3.0.0a1     | 16:11    | 428  | 2    | 2        | 46   | Test_Run-intel_skip-my_installation-3.0.0a1-my_installation.html         |
| Test Run    | java            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Run-java-my_installation-3.0.0a1-my_installation.html               |
| Test Run    | orte            | 3.0.0a1     | 00:43    | 19   |      |          |      | Test_Run-orte-my_installation-3.0.0a1-my_installation.html               |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+


    Total Tests:    1460
    Total Failures: 48
    Total Passed:   1412
    Total Duration: 4178 secs. (01:09:38)
```

**Comment by rhc54** [comment]
Will replace this with an updated one now that we have things figured out

**Pull request closed without merging**
