### PR TITLE
v5.0.x warnings fixes

### PR DESCRIPTION
**Pull request by awlauria**
Cherry-picks from #9903

Brought #9848 over to accommodate a merge conflict.

### CODE REVIEW

**Comment by bwbarrett** [comment]
I think you want 9b8950574f8622f93c377272e71ffcf87950c366 as well, since you pulled in the patch that created the issues that patch fixes.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c077824742d0d31f7ddb448d7de0dfa8

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c077824742d0d31f7ddb448d7de0dfa8

**Review by bwbarrett — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d0b6bbbf18245007a5d18040aeeaff08

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6c2b206ee40baeb55175feca6f99d3cd

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e9b8952f367d704e4a111022ddd91240

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c795392ed8f8f0595b00a85028b658d5

**Comment by awlauria** [comment]
This must be dependent on another patch series. Looking..

**Review by gpaulsen — APPROVED** [review]
Thanks.

**Review by janjust — APPROVED** [review]

**Pull request merged**
