### PR TITLE
Support ALPS_APPINFO_VERSION 3.

### PR DESCRIPTION
**Pull request by marksantcroos**
Verified on Titan@OLCF after ALPS was upgraded to alps/5.2.4-2.0502.9774.31.12.gem.

### CODE REVIEW

**Comment by marksantcroos** [comment]
How does this process work btw? Are these kind of changes always reactive or is there some heads-up mechanism from Cray towards Open MPI?

**Comment by rhc54** [comment]
Things may have changed now that Howard is part of the OMPI community, but in the past this was always purely reactive. :-(

**Comment by hppritcha** [comment]
For the cray systems I use, the alps ras component isn't being used, so don't bother testing it.  Anyway, this ras component wont' work at all for Cray systems using slurm.

**Comment by marksantcroos** [comment]
Howard, can you enlighten me on the differences? I guess you refer to the NERSC machines, right? On all Cray's I've got access to (which are quite a number by now) on master the plain configure.sh works. But I'm not aware of different components being used on different systems.

**Comment by hppritcha** [comment]
I suspect the titan system is using a different batch scheduler.  For the NERSC and lanl internal systems I use, the tm ras component is selected as it has higher priority.

**Comment by rhc54** [comment]
The ras component that will be selected totally depends on the scheduler. If you are using Moab, then tm will be selected. On Slurm machines, the slurm component gets selected. If you are using the native ALPS scheduler, then the alps component is used.

So it all depends on the local installation as Cray's can have any of the above.

**Comment by marksantcroos** [comment]
Titan is a Torque/Moab installation. Does that mean I have the option between tm and alps?

**Comment by rhc54** [comment]
No - you will automatically select the tm ras component. However, you will use the alps launcher.

Your setup is a Moab scheduler sitting on top of the alps runtime. So - Moab to schedule and assign allocation, and alps to launch.

**Comment by marksantcroos** [comment]
Hmmm ... but we got to this discussion because I required changes to the alps ras on Titan ...

**Comment by rhc54** [comment]
Did you require them to compile, or to run? I'm betting it was a compile-time error - yes?

You'll compile both tm and alps ras components - but only the tm one will actually be used.

**Comment by marksantcroos** [comment]
> Did you require them to compile, or to run? I'm betting it was a compile-time error - yes?

No, this was fixing a runtime segfault.

**Comment by rhc54** [comment]
Odd - set -mca ras_base_verbose 10 and see what code path you're following.

**Comment by marksantcroos** [comment]
```
titan-login5:25098] mca: base: components_register: registering framework ras components
[titan-login5:25098] mca: base: components_register: found loaded component simulator
[titan-login5:25098] mca: base: components_register: component simulator register function successful
[titan-login5:25098] mca: base: components_register: found loaded component alps
[titan-login5:25098] mca: base: components_register: component alps register function successful
[titan-login5:25098] mca: base: components_register: found loaded component loadleveler
[titan-login5:25098] mca: base: components_register: component loadleveler register function successful
[titan-login5:25098] mca: base: components_register: found loaded component slurm
[titan-login5:25098] mca: base: components_register: component slurm register function successful
[titan-login5:25098] mca: base: components_open: opening ras components
[titan-login5:25098] mca: base: components_open: found loaded component simulator
[titan-login5:25098] mca: base: components_open: found loaded component alps
[titan-login5:25098] mca: base: components_open: component alps open function successful
[titan-login5:25098] mca: base: components_open: found loaded component loadleveler
[titan-login5:25098] mca: base: components_open: component loadleveler open function successful
[titan-login5:25098] mca: base: components_open: found loaded component slurm
[titan-login5:25098] mca: base: components_open: component slurm open function successful
[titan-login5:25098] mca:base:select: Auto-selecting ras components
[titan-login5:25098] mca:base:select:(  ras) Querying component [simulator]
[titan-login5:25098] mca:base:select:(  ras) Querying component [alps]
[titan-login5:25098] ras:alps: available for selection
[titan-login5:25098] mca:base:select:(  ras) Query of component [alps] set priority to 75
[titan-login5:25098] mca:base:select:(  ras) Querying component [loadleveler]
[titan-login5:25098] mca:base:select:(  ras) Querying component [slurm]
[titan-login5:25098] mca:base:select:(  ras) Selected component [alps]
[titan-login5:25098] mca: base: close: unloading component simulator
[titan-login5:25098] mca: base: close: unloading component loadleveler
[titan-login5:25098] mca: base: close: component slurm closed
[titan-login5:25098] mca: base: close: unloading component slurm
VMURI: 1560739840.0;tcp://10.128.0.13,160.91.205.243:48699
[titan-login5:25098] ras:alps:allocate: Trying ALPS configuration file: "/etc/sysconfig/alps"
[titan-login5:25098] ras:alps:allocate: parser_ini
[titan-login5:25098] ras:alps:allocate: Trying ALPS configuration file: "/etc/alps.conf"
[titan-login5:25098] ras:alps:allocate: Skipping ALPS configuration file: "/etc/alps.conf" (No such file or directory).
[titan-login5:25098] ras:alps:allocate: Trying ALPS configuration file: "/etc/opt/cray/alps/alps.conf"
[titan-login5:25098] ras:alps:allocate: parser_separated_columns
[titan-login5:25098] ras:alps:allocate: Located ALPS scheduler file: "/ufs/alps_shared/appinfo"
[titan-login5:25098] ras:alps:orte_ras_alps_get_appinfo_attempts: 10
[titan-login5:25098] ras:alps:allocate: begin processing appinfo file
[titan-login5:25098] ras:alps:allocate: file /ufs/alps_shared/appinfo read
```

**Comment by marksantcroos** [comment]
When I disable alps:
```
 orte-dvm -mca ras_base_verbose 10 -mca ras ^alps
[titan-batch3:31561] mca: base: components_register: registering framework ras components
[titan-batch3:31561] mca: base: components_register: found loaded component simulator
[titan-batch3:31561] mca: base: components_register: component simulator register function successful
[titan-batch3:31561] mca: base: components_register: found loaded component loadleveler
[titan-batch3:31561] mca: base: components_register: component loadleveler register function successful
[titan-batch3:31561] mca: base: components_register: found loaded component slurm
[titan-batch3:31561] mca: base: components_register: component slurm register function successful
[titan-batch3:31561] mca: base: components_open: opening ras components
[titan-batch3:31561] mca: base: components_open: found loaded component simulator
[titan-batch3:31561] mca: base: components_open: found loaded component loadleveler
[titan-batch3:31561] mca: base: components_open: component loadleveler open function successful
[titan-batch3:31561] mca: base: components_open: found loaded component slurm
[titan-batch3:31561] mca: base: components_open: component slurm open function successful
[titan-batch3:31561] mca:base:select: Auto-selecting ras components
[titan-batch3:31561] mca:base:select:(  ras) Querying component [simulator]
[titan-batch3:31561] mca:base:select:(  ras) Querying component [loadleveler]
[titan-batch3:31561] mca:base:select:(  ras) Querying component [slurm]
[titan-batch3:31561] mca:base:select:(  ras) No component selected!
```

**Comment by marksantcroos** [comment]
Or when I force tm:
```
> orte-dvm -mca ras_base_verbose 10 -mca ras tm
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      titan-batch3
Framework: ras
Component: tm
--------------------------------------------------------------------------
[titan-batch3:31570] [[29828,0],0] ORTE_ERROR_LOG: Not found in file ../../../../../orte/mca/ess/hnp/ess_hnp_module.c at line 492
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ras_base_open failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
```

**Comment by marksantcroos** [comment]
Regardless of whether TM should work or not. Should I have a preference for one over the other?

**Comment by marksantcroos** [comment]
```
> ompi_info |grep ras
                 MCA ras: simulator (MCA v2.1.0, API v2.0.0, Component v3.0.0)
                 MCA ras: alps (MCA v2.1.0, API v2.0.0, Component v3.0.0)
                 MCA ras: loadleveler (MCA v2.1.0, API v2.0.0, Component v3.0.0)
                 MCA ras: slurm (MCA v2.1.0, API v2.0.0, Component v3.0.0)
```

**Comment by marksantcroos** [comment]
From config.log:

```
configure:5775: --- MCA component ras:tm (m4 configuration macro)
configure:204595: checking for MCA component ras:tm compile mode
configure:204601: result: static
configure:204656: checking --with-tm value
configure:204659: result: simple ok (unspecified)
configure:204701: checking for pbs-config
configure:204711: result: not found
configure:204976: checking tm.h usability
configure:204976: gcc -std=gnu99 -c -O3 -DNDEBUG -finline-functions -fno-strict-
aliasing -mcx16 -pthread   -I/ccs/home/marksant1/openmpi/src/ompi/opal/mca/hwloc
/hwloc1111/hwloc/include -I/ccs/home/marksant1/openmpi/src/ompi/build/opal/mca/h
wloc/hwloc1111/hwloc/include -I/ccs/home/marksant1/openmpi/src/ompi/opal/mca/eve
nt/libevent2022/libevent -I/ccs/home/marksant1/openmpi/src/ompi/opal/mca/event/l
ibevent2022/libevent/include -I/ccs/home/marksant1/openmpi/src/ompi/build/opal/m
ca/event/libevent2022/libevent/include conftest.c >&5
conftest.c:775:16: fatal error: tm.h: No such file or directory
 #include <tm.h>
                ^
compilation terminated.

...

configure:204976: result: no
configure:204976: checking for tm.h
configure:204976: result: no
configure:206175: checking if MCA component ras:tm can compile
configure:206177: result: no
```

**Comment by rhc54** [comment]
Aha! There's the issue - it didn't find the Moab support. If things are working okay, then it doesn't matter - all it means is that your system has been configured to provide allocation info via the alps path instead of the usual Moab envars. You could check to see if you have PBS envars floating around, and check with the sys admin to see if they have a preference - e.g., they might want you to build --with-tm=path to tm libs instead (though I doubt it).

**Comment by marksantcroos** [comment]
> If things are working okay, then it doesn't matter - all it means is that your system has been configured to provide allocation info via the alps path instead of the usual Moab envars.

Well, "working okay" only with this PR ;-)

> if you have PBS envars floating around,

Yes, I also use them for RADICAL-Pilot for something similar that RAS is doing.
(https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L2504)

> e.g., they might want you to build --with-tm=path to tm libs instead (though I doubt it).

There doesn't seem to be headers available for the installed version of Torque, so I would say that answers that concern.

**Comment by marksantcroos** [comment]
@hppritcha Just checking that the ball is not in my court, right?

**Comment by hppritcha** [comment]
I will verify on a system here at LANL.  Then if things work I will merge this pr 

Von meinem iPhone gesendet

**Comment by hppritcha** [comment]
works for me on edison.  can use either tm or alps ras on edison, although it defaults to tm.
going ahead and merging.

**Comment by hppritcha** [comment]
@marksantcroos I'll open a PR on v2.x unless you'd like to do so yourself.

**Comment by marksantcroos** [comment]
Thanks!

**Comment by marksantcroos** [comment]
> I'll open a PR on v2.x unless you'd like to do so yourself.

I don't mind either way, whatever you consider pedagogically appropriate ;-)

**Comment by hppritcha** [comment]
Please go ahead and open pr for v2.x thanks

**Comment by hppritcha** [comment]
@marksantcroos I didn't notice till it was too late, but in the future, could you rebase your topic branches
rather than merging?  When you merge your topic branch to master, then when we eventually pull the PR in back in to master, we end up with all your merge commits (like 299fd69) showing up in the ompi/master history.  We'd like to avoid that.

**Comment by marksantcroos** [comment]
> in the future, could you rebase your topic branches rather than merging?

*nod* This is not in my regular workflow (as we work with shared topic branches) but I will incorporate it into my ompi workflow.

**Pull request merged**
