### PR TITLE
v2.0.x: Add arguments to rpmbuild script and update README.

### PR DESCRIPTION
**Pull request by martinkontsek**
We have updated buildrpm script with external arguments. Script was tested on RedHat 7.3

### CODE REVIEW

**Comment by jsquyres** [comment]
Let's let #2451 percolate through the system first (the master version of this PR).

**Comment by jsquyres** [comment]
We're looking to do v2.0.2 in the immediate future.  Pushing this to v2.0.3.

**Comment by jsquyres** [comment]
@martinkontsek Can you update this to the latest state from #2451?

**Comment by martinkontsek** [comment]
Hello, @jsquyres I have updated this branch.

**Comment by jsquyres** [comment]
Can you please pull in the fixes from https://github.com/open-mpi/ompi/commit/5ecd271934e1906d66752edc6e28f81ab3509ed3?  Thanks.

**Comment by martinkontsek** [comment]
Changes from 5ecd271 pulled.

**Pull request merged**
