### PR TITLE
RFC: opal_config_asm.m4: enable inline assembly on little-endian POWER

### PR DESCRIPTION
**Pull request by jsquyres**
Suggested by @PHHargrove: http://www.open-mpi.org/community/lists/devel/2015/04/17323.php

Running this by the assembly / IBM/POWER gatekeepers before committing to master: @bosilca @hjelmn @nysal @gpaulsen

### CODE REVIEW

**Comment by bosilca** [comment]
:+1: but the code might be suboptimal as the power8 processor support transactions.

**Comment by mellanox-github** [comment]
* Coverity found 906 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_469/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_469/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_469/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jsquyres** [comment]
IBM folks: what do you want here?

**Comment by PHHargrove** [comment]
I just updated the Title from "... POWER8" to "... little-endian POWER".

This change was to recognize the config.guess name for the little-endian mode of POWER8 (and some later POWER7) CPUs.  The "normal" case of big-endian POWER8 was *already* using the inline asm.

-Paul

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/469/
Test PASSed.

**Comment by bosilca** [comment]
If Paul had issues with the assembly I guess we do not support the XLC atomics, so we don't have a fallback. I guess we should be fine with what we have.

**Comment by nysal** [comment]
Looks good to me with a small change to add 32-bit LE mode for completeness.  Thanks!
```diff
--- a/config/opal_config_asm.m4
+++ b/config/opal_config_asm.m4
@@ -1003,6 +1003,7 @@ AC_DEFUN([OPAL_CONFIG_ASM],[
             ;;
 
         powerpc-*|powerpc64-*|rs6000-*|ppc-*)
+        powerpc-*|powerpc64-*|powerpcle-*|powerpc64le-*|rs6000-*|ppc-*)
             OPAL_CHECK_POWERPC_REG
             if test "$ac_cv_sizeof_long" = "4" ; then
                 opal_cv_asm_arch="POWERPC32
```

**Comment by jsquyres** [comment]
@nysal Good suggestion; done.

**Comment by mellanox-github** [comment]
* Coverity found 906 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_470/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_470/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_470/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/470/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 905 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_471/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_471/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_471/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/471/

**Build Log**
*last 50 lines*

 ```
[...truncated 33415 lines...]
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test mca_base_env_list option in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
test mca_base_env_list option in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ export XXX_C=3 XXX_D=4 XXX_E=5
+ XXX_C=3
+ XXX_D=4
+ XXX_E=5
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
++ grep '^XXX_'
++ wc -l
+ val=10
+ '[' 10 -ne 10 ']'
+ echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
++ grep '^XXX_'
++ wc -l
+ val=0
+ '[' 0 -ne 10 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/471/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/471/tap-master-files/cov_stat.tap].
not ok - coverity detected 905 failures in all_471 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_471/output/errors/index.html
not ok - coverity detected 5 failures in oshmem_471 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_471/output/errors/index.html
ok - coverity found no issues for yalla_471
ok - coverity found no issues for mxm_471
not ok - coverity detected 2 failures in fca_471 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_471/output/errors/index.html
ok - coverity found no issues for hcoll_471

TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_471/output/errors/index.html
coverity_for_oshmem	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_471/output/errors/index.html
coverity_for_fca	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_471/output/errors/index.html
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/814fefd44342346b8ea32ecbe8cf6ca2b2ff37d7
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of f7b8c11027b73c04f136506eecf38b071e284151 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/471/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@miked-mellanox Another Jenkins false failure?

**Comment by jsquyres** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 905 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_484/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_484/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_484/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/484/
Test PASSed.

**Comment by jsquyres** [comment]
IBM (i.e., @nysal @gpaulsen): If you guys want this on the v1.8 branch, file a PR.

**Comment by nysal** [comment]
Opened PR: https://github.com/open-mpi/ompi-release/pull/260

**Pull request merged**
