### PR TITLE
oshmem: remove `shmem_put/get` when not the C11 case in accordance with the spec v1.3

### PR DESCRIPTION
**Pull request by karasevb**
Fixes: https://github.com/open-mpi/ompi/issues/4307

Signed-off-by: Boris Karasev <karasev.b@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
@Di0gen 
```
13:25:19 [htmlpublisher] Archiving HTML reports...
13:25:19 [htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/6960/htmlreports/Coverity_Report
13:25:19 ERROR: Build step failed with exception
13:25:19 java.io.IOException: No space left on device
```

And the same issue was observed at https://github.com/open-mpi/ompi/pull/4606

**Comment by artpol84** [comment]
No space issue should be fixed

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
@jladd-mlnx @miked-mellanox can you have a look?

**Comment by artpol84** [comment]
@BryantLam, can you verify that this is what was requested.

**Comment by BryantLam** [comment]
@artpol84, Looks good to me. Thanks!

**Comment by jsquyres** [comment]
Note: This PR will affect OSHMEM ABI.

**Comment by artpol84** [comment]
Thank you.

**Pull request merged**
