### PR TITLE
Prepare osc framework for bigcount

### PR DESCRIPTION
**Pull request by jtronge**
This updates the osc framework to use size_t for counts and ptrdiff_t for displacements.

### CODE REVIEW

**Comment by wenduwan** [comment]
Running AWS CI

**Comment by hppritcha** [comment]
You mean IMB right?

**Comment by wenduwan** [comment]
Example failure
```
mpirun --wdir . -n 2  osu-micro-benchmarks/mpi/one-sided/osu_put_bw
# OSU MPI_Put Bandwidth Test v7.0-lrbison3
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_flush
# Size      Bandwidth (MB/s)
1                      11.14
2                       8.96
segfault
```
Backtrace
```
#0  0x00007f94d52edc1a in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007f94d4f159bc in opal_datatype_accelerator_memcpy (dest=0x7f94d6140100, src=0x187c050, size=4) at opal_datatype_copy.c:74
#2  0x00007f94d4f1648c in non_overlap_accelerator_copy_content_same_ddt (datatype=0x6176e0 <ompi_mpi_char>, count=4,
    destination_base=0x7f94d6140100 "\206\006A\016\070\203\aG\016@\002L\n\016\070D\016\060A\016(B\016 B\016\030B\016\020B\016\bA\v",
    source_base=0x187c050 'a' <repeats 176 times>) at opal_datatype_copy.h:151
#3  0x00007f94d4f1805b in opal_datatype_copy_content_same_ddt (datatype=0x6176e0 <ompi_mpi_char>, count=4,
    destination_base=0x7f94d6140100 "\206\006A\016\070\203\aG\016@\002L\n\016\070D\016\060A\016(B\016 B\016\030B\016\020B\016\bA\v",
    source_base=0x187c050 'a' <repeats 176 times>) at opal_datatype_copy.c:176
#4  0x00007f94d5803bc8 in ompi_datatype_sndrcv (sbuf=0x187c050, scount=4, sdtype=0x6176e0 <ompi_mpi_char>, rbuf=0x7f94d6140100, rcount=4,
    rdtype=0x6176e0 <ompi_mpi_char>) at ompi_datatype_sndrcv.c:62
#5  0x00007f94c40250fa in ompi_osc_sm_put (origin_addr=0x187c050, origin_count=4, origin_dt=0x6176e0 <ompi_mpi_char>, target=1,
    target_disp=80, target_count=4, target_dt=0x6176e0 <ompi_mpi_char>, win=0x1863050) at osc_sm_comm.c:232
#6  0x00007f94d585f97b in PMPI_Put (origin_addr=0x187c050, origin_count=4, origin_datatype=0x6176e0 <ompi_mpi_char>, target_rank=1,
    target_disp=80, target_count=4, target_datatype=0x6176e0 <ompi_mpi_char>, win=0x1863050) at put.c:82
#7  0x0000000000403150 in run_put_with_flush (rank=0, type=WIN_ALLOCATE) at osu_put_bw.c:268
#8  0x00000000004029c3 in main (argc=<optimized out>, argv=<optimized out>) at osu_put_bw.c:129
```

**Comment by hppritcha** [comment]
having problems reproducing your findings @wenduwan . what are you config options and compiler used?  and also processor type?

**Comment by wenduwan** [comment]
```
./configure --with-sge --without-verbs --with-libfabric=/opt/amazon/efa --disable-man-pages --enable-ipv6 LDFLAGS=-Wl,--as-needed --enable-prte-prefix-by-default --enable-mca-dso=all --with-libevent=external --with-hwloc=external --enable-debug
```

Note that I don't imagine libfabric to be an issue since the failure happens in sm

The segfault happens on:
- Amazon Linux 2 (GCC7) + x86
- Amazon LInux 2 (GCC7) + arm
- Ubuntu 20.04 + x86
- Ubuntu 20.04 + arm

**Comment by hppritcha** [comment]
@wenduwan could you please rerun AWS CI.  @jtronge pushed something to hopefully fix what you're seeing.

**Comment by wenduwan** [comment]
Thanks. The test passed.

**Comment by hppritcha** [comment]
@devreal could you take at this PR again to see if your questions were addressed?

**Review by devreal — CHANGES_REQUESTED** [review]
There are a few places where the format strings need to be adjusted

**Comment by jtronge** [comment]
Thanks @devreal. I think all the format strings should be fixed.

**Review by devreal — APPROVED** [review]

**Pull request merged**
