### PR TITLE
add libopen-orted-mpir when statically linking

### PR DESCRIPTION
**Pull request by ggouaillardet**
This is a one-off commit for the v4 series since
v5 and later moved to prrte.
bot:notacherrypick

Thanks Matt Thompson for reporting this issue.

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 could you please have a look at this PR?

Currently, if Open MPI is configure'd with `--enable-static --disable-shared`, linking a simple MPI program fails because some `MPIR_*` symbols are missing. This PR addresses that by adding `libopen-orted-mpir` to the list of static libs, but I am not quite sure if this is the right fix.

**Comment by rhc54** [comment]
I'm not the correct person - haven't had anything to do with MPIR in ages.

@awlauria I think you folks deal with this now?

**Comment by awlauria** [comment]
The change makes sense to me. @jsquyres / @gpaulsen / @bwbarrett ?

**Comment by hppritcha** [comment]
@ggouaillardet would you mind opening an equivalent PR for the v4.0.x series?

**Comment by jsquyres** [comment]
@bwbarrett This looks correct to me.  Can you think of any problems with it?

**Comment by bwbarrett** [comment]
I can't think of anything; it raises the question why we're leaving it in a standalone library, but let's not worry about that for now.

**Review by bwbarrett — APPROVED** [review]

**Comment by awlauria** [comment]
It was compiled into its stand-alone library to compile it with its own CFLAGS, otherwise they would be compiled with -O3 and the like:

https://github.com/open-mpi/ompi/pull/8428

**Comment by ggouaillardet** [comment]
the PR for the `v4.0.x` series is in #9618

**Comment by ggouaillardet** [comment]
@awlauria thanks for the insight.
is there any reason why this library was not slurped into `libopen-rte` (instead of being a dependency)?

**Comment by ggouaillardet** [comment]
@awlauria @bwbarrett I think I understand ... and I messed up (!)

the library used to be installed, but is now slurped (aka `noinst`) since open-mpi/ompi@952328c3827

that means this PR should be reverted (!)

do you concur?

**Comment by jsquyres** [comment]
Ah shoot.  Yes, there's the reason this PR shouldn't have been merged.  Oh well; let's revert...

**Comment by bwbarrett** [comment]
I'm not sure why CI didn't catch this.  I'll dig into that; very weird.

**Comment by ggouaillardet** [comment]
The issue only occurs if Open MPI is configured with `--disable-shared --enable-static` and a MPI wrapper is used. Not sure CI tests this.

**Pull request merged**
