### PR TITLE
cma: add support for MIPS and ARM

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@me.com>

### CODE REVIEW

**Comment by hjelmn** [comment]
@PHHargrove I think these are the correct syscall numbers. I pulled them out of the kernel source but I have no way to test. Can you try running this with a code that does some communication (NetPIPE, etc)? To make sure we use CMA run with -mca btl self,vader -mca btl_vader_single_copy_mechanism cma

**Comment by PHHargrove** [comment]
@hjelmn 
I don't really have time this week for more than the v2.x/RC testing (which is taking more than its expected share).  However, if you remind me next week I'll see what I can do.
-Paul

**Comment by hjelmn** [comment]
Yeah, lots of changes. Thanks for the testing. Should be a lot more quiet in 2.0.1.

**Comment by hjelmn** [comment]
Looks like I can build a mips-linux vm using qemu. Will run some basic testing tomorrow.

**Comment by PHHargrove** [comment]
@hjelmn 
Prebuilt QEMU images for MIPS at https://people.debian.org/~aurel32/qemu/mips/

**Comment by hjelmn** [comment]
Thanks for the link. That will speed up testing.

**Comment by PHHargrove** [comment]
@hjelmn 
Were you able to test ARM and MIPS to your satisfaction?
I have a little more time now than I did last week and could test if you still need me to.

**Comment by hjelmn** [comment]
Not yet. I was having trouble getting tuntap networking working. If you get a chance to test that would be great.

**Comment by PHHargrove** [comment]
I have not started testing, but did launch builds.
I noticed arm64 (aka aarch64 or armv8) is still not supported.
There doesn't seem to be an OPAL_ architecture value for that!

-Paul

**Comment by PHHargrove** [comment]
@hjelmn 
The undefined ref to `__sync_add_and_fetch_8` is still a problem building from your branch on MIPS with a 32-bit ABI (though ARM is fine).  So, I can current only test the `_MIPS_SIM == _MIPS_SIM_ABI64` case on MIPS.

On ARM all looks good running `mpirun -oversubscribe -host localhost -mca btl self,vader -mca btl_vader_single_copy_mechanism cma -np 2 ./NPmpi`

However, on MIPS/-mabi=64, I get the following with the same command line:
```
--------------------------------------------------------------------------
An invalid value was supplied for an enum variable.

  Variable     : btl_vader_single_copy_mechanism
  Value        : cma
  Valid values : 3:"none"
--------------------------------------------------------------------------
```
The netpipe benchmark still runs, but I am uncertain whether I have tested what you wanted me to.

**Comment by PHHargrove** [comment]
re: invalid enum
It looks like CMA was not enabled at configure time on the MIPS system.

On a (newer) MIPS64EL (little-endian) system works fine with the same command line.
So, since both are OPAL_MIPS, I will not be retesting the big-endian system.
However, I cannot yet test the other two MIPS ABIs.

Summary:
- ARM good
- ARM64 `OPAL_ASSEMBLY_ARCH == OPAL_UNSUPPORTED`
- MIPS/-mabi=64 good
- MIPS/-mabi=32 `__sync_add_and_fetch_8` problem
- MIPS/-mabi=n32 `__sync_add_and_fetch_8` problem

**Comment by PHHargrove** [comment]
@hjelmn 
I was able to test MIPS with -mabi=32 and -mabi=m32 by merging pr1659 and this pr.

The good news is that -mabi=n32 works fine.
The bad news is that -mabi=32 hangs part way through NetPipe (but at different sizes each time).

This is real h/w, not QEMU.

-Paul

Current summary:
- ARM good
- ARM64 OPAL_ASSEMBLY_ARCH == OPAL_UNSUPPORTED
- MIPS/-mabi=64 good
- MIPS/-mabi=32 hangs in NetPipe
- MIPS/-mabi=n32 good

**Comment by hjelmn** [comment]
Ok, sounds like I should take a look at the nabi32 and see about adding arm64 atomic support.

**Comment by ibm-ompi** [comment]
Test passed.

**Comment by hjelmn** [comment]
What is the cpu type of the ARM64 system? I can test ARMv7 but that looks ok.

**Comment by hjelmn** [comment]
I see why MIPS 32 is failing. The syscall numbers in 3.x vs 4.x are different :-1:. Damnit, thought syscall numbers were not supposed to change. Looks like n32 and 64 didn't change. I will have to put in a kernel version check to use the correct ones.

**Comment by hjelmn** [comment]
Or not. I now can't find where I found the alternate syscall numbers. Still digging.

**Comment by PHHargrove** [comment]
> What is the cpu type of the ARM64 system? I can test ARMv7 but that looks ok.

```
$ cat /proc/cpuinfo
Processor       : AArch64 Processor rev 1 (aarch64)
processor       : 0
processor       : 1
processor       : 2
processor       : 3
processor       : 4
processor       : 5
processor       : 6
processor       : 7
Features        : fp asimd evtstrm 
CPU implementer : 0x50
CPU architecture: AArch64
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 1

Hardware        : APM X-Gene Mustang board
```

**Comment by hjelmn** [comment]
Can you get me a gist of a config.log from the arm64?

**Comment by PHHargrove** [comment]
@hjelmn 
I can attach config.log, and optionally the full stdout from configure.

At the moment I have a build of 1.10.3rc2 available to me, but the host with the builds of v2.x and your PR is down.
Unless you say you are OK with config.log from 1.10.3rc3, I will get you config.log from this PR as soon as I am able.

-Paul

**Comment by PHHargrove** [comment]
Here is the [config.log](https://github.com/open-mpi/ompi/files/276072/config.log.txt), renamed to config.log.txt to make github happy.

**Comment by hjelmn** [comment]
Thanks! I added a commit to support ARMv8 in our asm. Please test when you have a chance.

@shamisp If you have time take a look and let me know if you can test the ARMv8 code.

**Comment by shamisp** [comment]
I actually discovered couple of other issues (not directly related to this
PR). I will be submitting patches later this week.

**Comment by hjelmn** [comment]
@shamisp Thanks! If you get a chance to test this let me know. I used the ARMv8 reference manual but I don't have any ARMv8 hardware to test with.

**Comment by hjelmn** [comment]
Remember to configure with --disable-builtin-atomics to make sure sync atomics are not used.

**Comment by shamisp** [comment]
FYI in UCX we use builtin gcc atomics.

**Comment by hjelmn** [comment]
Yeah, we use builtins by default on master but it is nice to have the ability to use inline assembly. Not sure it matters much but gcc builtins always include barrier but the opal atomics do not by default.

**Comment by PHHargrove** [comment]
@hjelmn 

Checked this PR out from git, did autogen.pl, ran "make dist" and configured the resulting tarball on an arm64 host with --disable-builtin-atomics.

Configure warned:
```
checking for pre-built assembly file... no (not in asm-data)
checking whether possible to generate assembly file... failed
configure: WARNING: Could not build atomic operations assembly file.
configure: WARNING: There will be no atomic operations for this build.
checking for atomic assembly filename... none
```
and the build failed:
```
In file included from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/asm/asm.c:21:0:
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/atomic.h:151:35: fatal error: opal/sys/arm64/atomic.h: No such file or directory
 #include "opal/sys/arm64/atomic.h"
```

I am unsure where to fix the configure-time issue.
However, the following fixes the build failure:
```
diff --git a/opal/include/opal/sys/Makefile.am b/opal/include/opal/sys/Makefile.am
index 01985a9..8b66ab4 100644
--- a/opal/include/opal/sys/Makefile.am
+++ b/opal/include/opal/sys/Makefile.am
@@ -29,6 +29,7 @@ headers += \
 
 include opal/sys/amd64/Makefile.am
 include opal/sys/arm/Makefile.am
+include opal/sys/arm64/Makefile.am
 include opal/sys/ia32/Makefile.am
 include opal/sys/ia64/Makefile.am
 include opal/sys/mips/Makefile.am
```

HOWEVER, with the file `arm64/atomic.h` now included in the tarball I reach the next failure:
```
ibtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/datatype -I../../opal/include -I../../ompi/include -I../../oshmem/include -I../../opal/mca/hwloc/hwloc1112/hwloc/include/private/autogen -I../../opal/mca/hwloc/hwloc1112/hwloc/include/hwloc/autogen -I../../ompi/mpiext/cuda/c -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone -I../.. -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/orte/include -I../../orte/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/ompi/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/oshmem/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/mca/hwloc/hwloc1112/hwloc/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/BLD/opal/mca/hwloc/hwloc1112/hwloc/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/mca/event/libevent2022/libevent -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/mca/event/libevent2022/libevent/include -I/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/BLD/opal/mca/event/libevent2022/libevent/include -g -finline-functions -fno-strict-aliasing -pthread -MT opal_datatype_destroy.lo -MD -MP -MF .deps/opal_datatype_destroy.Tpo -c /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/datatype/opal_datatype_destroy.c  -fPIC -DPIC -o .libs/opal_datatype_destroy.o
/tmp/cccvQIWZ.s: Assembler messages:
/tmp/cccvQIWZ.s:24: Error: unknown mnemonic `strex' -- `strex x0,x1,[x2]'
```

In the `OPAL_ASM_MAKE_ATOMIC` macro I believe you want to change the rejected `strex` to `stxr`.  However, when I tried that I get a different error:
```
/tmp/ccKo26ye.s: Assembler messages:
/tmp/ccKo26ye.s:24: Error: operand mismatch -- `stxr x0,x1,[x2]'
```
So, there must be more to the problem that what I am seeing.


FWIW: arm64/aarch64 emulation in QEMU is not to hard to setup and use.

**Comment by hjelmn** [comment]
Strange that is is generating x0 for int tmp. Will take a look now. Thanks for catching the other bugs. Thought I had changed all the strex instructions to the ARMv8 equivalent but I missed one.

**Comment by hjelmn** [comment]
Linux kernel uses %w1 or %w[tmp]. I pushed an update to use the later syntax. Will double-check using qemu.

**Comment by shamisp** [comment]
You right about gcc. It has barrier in the end. I'm not sure if removal of the barrier is good for correctness. I would have to check this. It is ok for certain scenarios for sure. Do we have some unit testing for this just to verify that everything operation as expected.

**Comment by hjelmn** [comment]
@shamisp Yeah. Make check does some simple checks on the atomics. I think they will compile now but I won't know until I get the qemu build running or get a 64-bit install on my raspberry pi 3.

**Comment by shamisp** [comment]
I should be able to run it on my system.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by hjelmn** [comment]
@jjhursey What is the failure? The "Details" only show 0 of 7 tests pass and nothing more. This PR shouldn't have an effect on power.

**Comment by jjhursey** [comment]
@hjelmn This was caused by a connectivity issue between our Jenkins server and the test machine. I'll try to work on the script so that it reports that error publicly instead of just internally.

Let's try this again
bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by PHHargrove** [comment]
No joy at 890aa5e:
```
In file included from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/atomic.h:151:0,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_object.h:124,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/datatype/opal_datatype.h:39,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/datatype/opal_datatype_destroy.c:23:
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/arm64/atomic.h: In function 'opal_atomic_add_32':
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/arm64/atomic.h:251:9: error: invalid 'asm': operand number out of range
         __asm__ __volatile__("1:  ldxr   %0, [%1]        \n"            \
         ^
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/arm64/atomic.h:262:1: note: in expansion of macro 'OPAL_ASM_MAKE_ATOMIC'
 OPAL_ASM_MAKE_ATOMIC(int32_t, 32, add, "    add    %0, %0, %3      \n")
 ^
make[2]: *** [opal_datatype_destroy.lo] Error 1
```

**Comment by hjelmn** [comment]
Shoot. Forgot to update the macros below. Fixing now.

**Comment by hjelmn** [comment]
Ok, fixed.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by PHHargrove** [comment]
@hjelmn 
Still having issues at 0f81417
```
In file included from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/atomic.h:617:0,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_object.h:124,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_list.h:71,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/util/proc.h:20,
                 from /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/mca/mpool/base/mpool_base_tree.c:31:
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_lifo.h: In function 'opal_lifo_pop_atomic':
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/atomic_impl.h:288:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 #define opal_atomic_ll_ptr(addr) (void *) opal_atomic_ll_64((int64_t *) addr)
                                  ^
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_lifo.h:218:37: note: in expansion of macro 'opal_atomic_ll_ptr'
         item = (opal_list_item_t *) opal_atomic_ll_ptr (&lifo->opal_lifo_head.data.item);
                                     ^
/tmp/cci0xHkI.s: Assembler messages:
/tmp/cci0xHkI.s:44: Error: operand mismatch -- `stxr x0,x4,[x2]'
/tmp/cci0xHkI.s:107: Error: operand mismatch -- `stlxr x0,x1,[x1]'
```

**Comment by hjelmn** [comment]
Hmm, its expanding an int to x instead of w I wonder if sizeof (int) is 64? I will fix the atomics to all use w1 as the temp register and throw away int tmp.

**Comment by hjelmn** [comment]
I am going to ran a qemu image and see if I can figure out what is going on.

**Comment by hjelmn** [comment]
Would help if I knew what the %w means. It just uses the word representation of the register. Think I figured this out. Update coming soon.

**Comment by hjelmn** [comment]
Sorry about that. I am still learning some of the syntax for inline assembly. Really surprised that the compiler is not picking the right register form for the int values. It is picking the %x (64-bit) register syntax over the %w (32-bit) which is invalid for the first operand of store-conditional.

**Comment by PHHargrove** [comment]
Nathan,

You are correct that the "w" between "%" the operand number requests the word (32-bit) register.
Similarly "x" requests the 64-bit register.

Will try f367b0f shortly

-Paul

**Comment by hjelmn** [comment]
I may also need to make the 32-bit atomics all used w explicitly. Will work on that next.

**Comment by hjelmn** [comment]
Done. All the 32-bit operands are now explicitly %w.

**Comment by hjelmn** [comment]
Thanks for testing Paul, I bought a Raspberry Pi 3 but I can only find a ARMv7 system image for it. Hopefully I can get an ARM64 install on it soon.

**Comment by PHHargrove** [comment]
@hjelmn 
I've started tests of c56e709
FWIW: I think a cross-compiler on an x86-64 might be faster than your rpi3, and suitable for the sort of testing I've been able to do for you so far.

**Comment by PHHargrove** [comment]
@hjelmn 
Build is still running, but I am still seeing the following warning that suggests a genuine problem:
```
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_lifo.h: In function 'opal_lifo_pop_atomic':
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/include/opal/sys/atomic_impl.h:288:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 #define opal_atomic_ll_ptr(addr) (void *) opal_atomic_ll_64((int64_t *) addr)
                                  ^
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_lifo.h:218:37: note: in expansion of macro 'opal_atomic_ll_ptr'
         item = (opal_list_item_t *) opal_atomic_ll_ptr (&lifo->opal_lifo_head.data.item);
                                     ^
```

A quick look at the code shows an `int32_t` return type that should be `int64_t`:
```
$ grep opal_atomic_ll_64 opal/include/opal/sys/arm64/atomic.h
static inline int32_t opal_atomic_ll_64 (volatile int64_t *addr)
```

**Comment by hjelmn** [comment]
Yup, typo. Fixing.

**Comment by hjelmn** [comment]
Its a good sign if that was the only message you were seeing. Uncorrected it will cause make check to fail on the opal_lifo and opal_fifo tests.

**Comment by PHHargrove** [comment]
I didn't let the build with the bad ll_64 finish.  I started again from scratch w/ the 1-line correction.

**Comment by PHHargrove** [comment]
@hjelmn 
With 386b7fc I get a complete build with only the following warnings, which I assume are entirely unrelated:
```
/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/mca/hwloc/hwloc1113/hwloc/src/topology.c:123: warning: sysctl is not implemented and will always fail

/home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/ompi/win/win.c:164:37: warning: passing argument 5 of 'ompi_info_get_value_enum' from incompatible pointer type [enabled by default]
                                     ompi_win_accumulate_order, &flag);
                                     ^
```

However, when running "make check" I get a SEGV from ompi_rb_tree and opal_lifo appears to hang.  I didn't seem to get a core from ompi_rb_tree, and ptrace_attach() is disabled on this host.
I will try to get more info, but it doesn't look promising.

So, *now* it looks like time for you to break out QEMU.

**Comment by PHHargrove** [comment]
@hjelmn 

Here is a gdb session with a core from the ompi_rb_tree SEGV:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000002000061a28 in opal_lifo_pop_st (lifo=0x7fc15dc318)
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_lifo.h:288
288         lifo->opal_lifo_head.data.item = (opal_list_item_t *) item->opal_list_next;
(gdb) print lifo
$1 = (opal_lifo_t *) 0x7fc15dc318
(gdb) print lifo->opal_lifo_head
$2 = {data = {counter = 0, item = 0x0}}
(gdb) print item
$3 = (opal_list_item_t *) 0x0
(gdb) where
#0  0x0000002000061a28 in opal_lifo_pop_st (lifo=0x7fc15dc318)
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_lifo.h:288
#1  0x0000002000061b30 in opal_free_list_get_st (flist=0x7fc15dc318)
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_free_list.h:208
#2  0x0000002000061bac in opal_free_list_get (flist=0x7fc15dc318)
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_free_list.h:225
#3  0x0000002000061fe4 in opal_rb_tree_insert (tree=0x7fc15dc2d8, key=0x414118 <keys>, 
    value=0x414138 <values>)
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/opal/class/opal_rb_tree.c:127
#4  0x0000000000402318 in test1 ()
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/test/class/ompi_rb_tree.c:150
#5  0x00000000004031b4 in main (argc=1, argv=0x7fc15dc698)
    at /home/phargrov/OMPI/openmpi-pr1634-linux-arm64/openmpi-gitclone/test/class/ompi_rb_tree.c:408
```

**Comment by PHHargrove** [comment]
@hjelmn 
I think I see the problem.
In the "sc_32" and "sc_64" inline asm I see operand "1" used twice and operand "2" unused.
Here is sc_32:
```
    __asm__ __volatile__ ("stxr    %w0, %w1, [%1]      \n"
                          : "=&r" (ret)
                          : "r" (addr), "r" (newval)
                          : "cc", "memory");
```

I'm pretty sure the args on the first line need to be `%w0,%w2,[%1]`.
Similarly, the args in the first line of the asm for sc_64 need to be `%w0, %2, [%1]`

**Comment by PHHargrove** [comment]
Hmm....  pretty sure my fix for sc_{32,64} in my previous comment are correct.
However, the ompi_rb_tree test still SEGVs.
The opal_lifo test now FAILs instead of hanging:
```
$ .libs/lt-opal_lifo 
Single thread test. Time: 0 s 28810 us 28 nsec/poppush
Atomics thread finished. Time: 0 s 25478 us 25 nsec/poppush
 Failure :  lifo push/pop single-threaded with atomics
Atomics thread finished. Time: 0 s 25003 us 25 nsec/poppush
Atomics thread finished. Time: 0 s 44852 us 44 nsec/poppush
Atomics thread finished. Time: 0 s 44449 us 44 nsec/poppush
Atomics thread finished. Time: 0 s 34913 us 34 nsec/poppush
Atomics thread finished. Time: 0 s 24982 us 24 nsec/poppush
Atomics thread finished. Time: 0 s 49535 us 49 nsec/poppush
Atomics thread finished. Time: 0 s 36676 us 36 nsec/poppush
Atomics thread finished. Time: 0 s 28934 us 28 nsec/poppush
 Failure :  lifo push/pop multi-threaded with atomics
All threads finished. Thread count: 8 Time: 0 s 52354 us 6 nsec/poppush
 Failure :  list pop all items
SUPPORT: OMPI Test failed: opal_lifo_t (3 of 7 failed)
```
The next test to run is opal_fifo, which is hanging.
So, I am not sure that this report counts as progress or not.

I see the 64-bit LL/SC use the Acquire and reLease variants of the respective instructions, but the 32-bit do not.  I don't know if that is significant.

**Comment by hjelmn** [comment]
@PHHargrove Yeah, sc was definitely wrong. Looks like cmpset was as well. opal_atomic_cmpset_64/32 have acquire semantics and I wasn't using the load-link acquire exclusive instruction. Fixed that. Will dig further later today.

**Comment by hjelmn** [comment]
Bah, I see the issue. both sc_64 and sc_32 were returning 0 on success instead of 1. Changed both to return ret == 0. Should be good now.

**Comment by PHHargrove** [comment]
@hjelmn 
With 0084ad0 I can pass `make check` and run `ring_c`, `ring_mpif` and `ring_usempi`.
NetPipe runs fine with `-mca btl self,vader -mca btl_vader_single_copy_mechanism cma`

I'd give the thumbs-up for the bot to mark this PR as Reviewed, except for one thing:  to the best of my knowledge you haven't resolved the hangs seen with the 32-bit ABI on MIPS64.  Let me know if you *did* commit corresponding changes that warrant a retest.

**Comment by hjelmn** [comment]
No, can't figure out why MIPS32 isn't working. I triple-checked the syscall #'s and they are correct. I may just disable cma for that configuration until I find more time to test.

**Comment by PHHargrove** [comment]
I'll be happy to mark-as-reviewed a version of this PR that disables the mips32 case.

Alternatively, if you want to split the MIPS(CMA) support from the ARM64(atomics/timers/CMA) support, I'll be happy to endorse the ARM64 portion.

**Comment by hjelmn** [comment]
@PHHargrove I have an idea of how to make CMA selection allow compile-time selection. Testing now.

**Comment by hjelmn** [comment]
@PHHargrove I improved the CMA detection. I still need to test this to ensure it works in all cases. The new configury attempts to use the CMA support in opal/include/opal/sys/cma.h and disabled CMA if it doesn't work.

**Comment by PHHargrove** [comment]
@hjelmn You wrote:
> I improved the CMA detection. I still need to test this to ensure it works in all cases. The new 
> configury attempts to use the CMA support in opal/include/opal/sys/cma.h and disabled CMA
> if it doesn't work.

My biggest concern with this PR right now is that the MIPS32 failure case I observed was a hang part way through a run of NetPipe.  Let me know if/when there is something to retest there.

**Comment by hjelmn** [comment]
I disabled MIPS32 for now but my hope is that the test will catch bad syscall numbers (which may be why NetPIPE was failing).

**Comment by PHHargrove** [comment]
I will try to retest on all of the target systems this week and hope to give my thumbs-up one I have done so.

**Comment by hjelmn** [comment]
Awesome, thanks!

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
I will go ahead an merge this. Will double-check MIPS32 before PRing to 2.x.

**Pull request merged**
