### PR TITLE
Refresh/romio32b1

### PR DESCRIPTION
**Pull request by ggouaillardet**
@hppritcha Howard, could you please review this ?

this is a romio refresh based on mpich 3.2b1 tarball.
i tried to use a more systematic method as we previously discussed and documented in ompi/mca/io/romio32b1/REFRESH_NOTES.txt

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 936 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_401/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_401/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_401/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/401/
Test PASSed.

**Comment by hppritcha** [comment]
sorry Gilles you should have asked before doing this.  the plan is to go
back to romio in the 3.1.4 release.

**Comment by hppritcha** [comment]
Gilles, would you be willing to do this over using, but using mpich 3.1.4 instead?  

This would be at commit
89fd7dc3 (HEAD, tag: v3.1.4, origin/3.1.x) Update libtool and automake versions in release.pl
of mpich.

We may need to cherry pick commits 53fd425a, 2b5c52f, and 24a6f14 to pick up some recent fixes from Rob.

**Comment by ggouaillardet** [comment]
ok, will do

btw, what is the reason why we do go with romio from mpich 3.2 ?

On Mon, Apr 20, 2015 at 12:02 AM, Howard Pritchard <notifications@github.com

**Comment by hppritcha** [comment]
Rob Latham suggested not taking picking up 3.2 at this point.  We can't use some of the features in 3.2 anyway that would be nice (like the nonblocking collective I/O).  So for the 1.9.0 we would like to go with 3.1.4.  Please keep this work in your repo though so we can pull it later when 3.2 is released.   Ought to be easier to update to 3.2 with this work, then from 3.1.4.

**Comment by hppritcha** [comment]
@ggouaillardet  Do you think you'll have a chance to look at merging 3.1.4 in to ompi master?

**Comment by ggouaillardet** [comment]
to be continued in #558 ...

**Pull request closed without merging**
