### PR TITLE
Consolidated: fix OFI configury / linking issues

### LINKED ISSUE #2519: Patch for linking libfabric
Linking libfabric breaks on Debian/Ubuntu systems (at least) without the following patch:

```
Author: Gianfranco Costamagna <locutusofborg@debian.org>

--- openmpi-2.0.1.orig/ompi/mca/mtl/ofi/Makefile.am
+++ openmpi-2.0.1/ompi/mca/mtl/ofi/Makefile.am
@@ -43,7 +43,7 @@ mca_mtl_ofi_la_SOURCES = $(mtl_ofi_sourc
mca_mtl_ofi_la_LDFLAGS = \
$(ompi_mtl_ofi_LDFLAGS) \
-module -avoid-version
-mca_mtl_ofi_la_LIBADD = $(ompi_mtl_ofi_LIBS) \
+mca_mtl_ofi_la_LIBADD = $(ompi_mtl_ofi_LIBS) $(opal_common_libfabric_LIBS) \
$(OPAL_TOP_BUILDDIR)/opal/mca/common/libfabric/lib@OPAL_LIB_PREFIX@mca_common_libfabric.la

noinst_LTLIBRARIES = $(component_noinst)
```

### PR DESCRIPTION
**Pull request by jsquyres**
This PR is a consolidation of several existing PRs -- this is simpler than having a bunch of individual PRs that may end up having merge ordering issues:

* Fixes #2519: initial report from @amckinstry
* Incorporates @ggouaillardet's patch from #6362: fix VPATH builds for MTL/OFI
* Obviates @ggouaillardet's patch from #6313: fix OFI configury
* And includes new commits to fix what we discussed at the bottom of #2519:
  * Revamp the `OPAL_CHECK_OFI` macro
  * Update btl/ofi, btl/usnic, and mtl/ofi to match
  * Remove opal/mca/common/ofi

Also includes some commits to remove pesky tabs.  Down with tabs!

FYI @rashikakheria

### CODE REVIEW

**Comment by jsquyres** [comment]
@rashikakheria Could you please try this PR and see if it resolves the issue for you?

**Comment by jsquyres** [comment]
Because that lets us run the OFI checks just once (vs. run the tests again for each component).

**Comment by ggouaillardet** [comment]
From `config/opal_check_openfabrics.m4`, the _core_ of the test is protected by a global `if test -z "$opal_check_openib_happy"` so it is ran only once. Only trivial stuff is ran once per component.

**Comment by jsquyres** [comment]
I somewhat prefer that the results end up in a documented single set of variables instead of 3 sets of variables (one each for btl/ofi, btl/usnic, and mtl/ofi).  But I don't feel strongly about this.

I know that other components do it the other way -- but this morning when I was coding it up:

* it seemed kinda silly to have multiple sets of variables that all have identical values (i.e., one for each component).
* it felt like having globally-scoped names really reflected what was being tested.  The 3 components have their needs, but they're all testing the same back-end thing: whether OFI/libfabric is available.  Hence, having the var names reflect the common back-end thing (vs. the components) just felt a little more natural to me this morning.

But again, I don't have strong feelings either way.  If you'd prefer that I put it back to having the output names reflect the components, I can do that.  Lemme know.  😄

**Comment by rashikakheria** [comment]
> @rashikakheria Could you please try this PR and see if it resolves the issue for you?

I can confirm that this fixes my linking issue. Thanks for all of your assistance!

**Comment by jsquyres** [comment]
@rashikakheria Awesome; thanks.  I think @ggouaillardet and I might iterate a little more to get the solution in its final state (he's many timezones away / asleep right now), but we're darn close.

**Comment by matcabral** [comment]
@jsquyres, I did effectively start looking at this but got pulled by other stuff (apologize). In any case, I also tested this PR and is working for me. thanks,

**Comment by ggouaillardet** [comment]
@jsquyres for maintainability purpose, I think `verbs` and `libfabric` should use a consistent approach. And I have no preference whether we should do things _a la_ `verbs` or _a la_ `libfabric`. But this is something we can change later, so for now, I am fine with this PR.

@bwbarrett do you want to comment on that PR ?

**Comment by jsquyres** [comment]
@ggouaillardet Ah -- there's an easy way to fix that: merge #6270 (I had forgotten that it *wasn't* already merged! 😜) . That gets rid of all the verbs stuff, and all we're left with is the "new" style libfabric stuff.

I've just rebased #6270; I'll merge it when I finish a few sanity tests and CI completes.

**Comment by jsquyres** [comment]
I rebased this on the HEAD of master, just for good measure.  After CI finishes and this PR is merged:

1. I have a v4.0.x cherry pick branch (with all the commits from this PR) ready to make a new v4.0.x PR.
2. Similarly, I have a v3.1.x cherry pick branch (with *only* f5e1a672cc and dd20174532 from this branch) ready to make a new v3.1.x PR.
3. I tried to make a v3.0.x cherry pick branch (with only the same 2 commits: f5e1a672cc and dd20174532), but it generated a ton of conflicts.

@matcabral I've sunk a lot of time in this already -- can I ask you to make the v3.0.x PR?  (i.e., cherry pick just those 2 commits and fix all the conflicts

**Comment by matcabral** [comment]
@jsquyres, sure, I'll look at 3.0.x, either today or tomorrow.

**Pull request merged**
