### PR TITLE
coll-portals4: implement collective operations using Portals4 triggered operations

### PR DESCRIPTION
**Pull request by tkordenbrock**
This commit implements the reduce, allreduce, barrier and broadcast 
collective operations using Portals4 triggered operations.

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 822 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//576/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/576/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/85/

**Build Log**
*last 20 lines*

 ```
[...truncated 5205 lines...]
  GENERATE psizeof_f.f90
  CC       pwin_complete_f.lo
  CC       pwin_call_errhandler_f.lo
  LN_S     pwin_attach_f.c
  LN_S     pwin_create_dynamic_f.c
ln: failed to create symbolic link `pwin_attach_f.c': File exists
make[3]: *** [pwin_attach_f.c] Error 1
make[3]: *** Waiting for unfinished jobs....
ln: failed to create symbolic link `pwin_create_dynamic_f.c': File exists
make[3]: *** [pwin_create_dynamic_f.c] Error 1
make[3]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi/mpi/fortran/mpif-h/profile'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi/mpi/fortran/mpif-h'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
GCM: Sending notification to: hpp
Setting status of a274d2795c796da1ad11eeb1a3a7c41ad4ceaef8 to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/85/ and message: Build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/585/

**Build Log**
*last 50 lines*

 ```
[...truncated 12049 lines...]
  CC       pwtime_f.lo
  CC       pwtick_f.lo
  CC       paccumulate_f.lo
  CC       praccumulate_f.lo
  CC       pget_f.lo
  CC       prget_f.lo
  CC       pget_accumulate_f.lo
  CC       pput_f.lo
  CC       prget_accumulate_f.lo
  CC       prput_f.lo
  CC       pcompare_and_swap_f.lo
  CC       pfetch_and_op_f.lo
  CC       pwin_allocate_f.lo
  CC       pwin_allocate_shared_f.lo
  CC       pwin_attach_f.lo
  CC       pwin_call_errhandler_f.lo
  CC       pwin_complete_f.lo
  CC       pwin_create_dynamic_f.lo
  CC       pwin_create_errhandler_f.lo
  CC       pwin_create_f.lo
  CC       pwin_create_keyval_f.lo
  CC       pwin_delete_attr_f.lo
  CC       pwin_detach_f.lo
  CC       pwin_fence_f.lo
  CC       pwin_free_f.lo
gcc: pwin_attach_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_attach_f.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
gcc: pwin_create_dynamic_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_create_dynamic_f.lo] Error 1
gcc: pwin_detach_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_detach_f.lo] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mpi/fortran/mpif-h/profile'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mpi/fortran/mpif-h'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/585/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/a0c7e4b0da20f4b80d97a0295b01bbbe42f6e759
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of a274d2795c796da1ad11eeb1a3a7c41ad4ceaef8 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/585/ and message: Build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
these failures should be fixed.
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/11/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/100/
Test PASSed.

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 815 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//604/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/24/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/113/
Test PASSed.

**Comment by regrant** [comment]
Build issues have been resolved. Merged.

**Pull request merged**
