### PR TITLE
remove embedded libfabric

### PR DESCRIPTION
**Pull request by jsquyres**
These commits remove the embedded libfabric and convert the usnic BTL and ofi MTL to only compile against external libfabric.

@yburette Can you please review and ensure that all is still cool for the OFI MTL?  Once this one is good, I'll make a PR for v1.1.0.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/33/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/122/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 790 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//613/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/613/

**Comment by yburette** [comment]
This works for me. Thank you.

**Pull request merged**
