### PR TITLE
ompi coverity fixes

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/80/

**Build Log**
*last 20 lines*

 ```
[...truncated 4947 lines...]
/opt/cray/alps/5.2.3-2.0502.9295.14.14.ari/include/alps/libalpslli.h:21:2: warning: #ident is a GCC extension
 #ident "$Id: libalpslli.h 9100 2014-10-13 20:41:14Z jhn $"
  ^
odls_alps_module.c: In function 'orte_odls_alps_launch_local_procs':
odls_alps_module.c:756:5: error: implicit declaration of function 'pmix_server_create_shared_segment' [-Werror=implicit-function-declaration]
     attr = pmix_server_create_shared_segment(job);
     ^
odls_alps_module.c:756:10: warning: assignment makes pointer from integer without a cast
     attr = pmix_server_create_shared_segment(job);
          ^
cc1: some warnings being treated as errors
make[2]: *** [mca_odls_alps_la-odls_alps_module.lo] Error 1
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte/mca/odls/alps'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
GCM: Sending notification to: hpp
Setting status of 632f829eb7352edbea76239130fdfd2c7cb2e7ff to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/80/ and message: Build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/582/

**Build Log**
*last 50 lines*

 ```
[...truncated 12046 lines...]
  CC       pwait_f.lo
  CC       pwaitsome_f.lo
  CC       pwtick_f.lo
  CC       pwtime_f.lo
  CC       paccumulate_f.lo
  CC       praccumulate_f.lo
  CC       pget_f.lo
  CC       prget_f.lo
  CC       pget_accumulate_f.lo
  CC       prget_accumulate_f.lo
  CC       pput_f.lo
  CC       prput_f.lo
  CC       pcompare_and_swap_f.lo
  CC       pfetch_and_op_f.lo
  CC       pwin_allocate_f.lo
  CC       pwin_allocate_shared_f.lo
  CC       pwin_attach_f.lo
  CC       pwin_call_errhandler_f.lo
  CC       pwin_complete_f.lo
  CC       pwin_create_dynamic_f.lo
  CC       pwin_create_errhandler_f.lo
  CC       pwin_create_f.lo
  CC       pwin_create_keyval_f.lo
  CC       pwin_delete_attr_f.lo
  CC       pwin_detach_f.lo
gcc: pwin_attach_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_attach_f.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
gcc: pwin_create_dynamic_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_create_dynamic_f.lo] Error 1
gcc: pwin_detach_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_detach_f.lo] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mpi/fortran/mpif-h/profile'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mpi/fortran/mpif-h'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/582/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/b89c4171fe4dd01074a363af45460cfad5aa6395
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 632f829eb7352edbea76239130fdfd2c7cb2e7ff to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/582/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/81/

**Build Log**
*last 20 lines*

 ```
GitHub pull request #620 of commit 69a0e1dd08c1666118bcef6788ef523f8ce8facb, no merge conflicts.
Setting status of 69a0e1dd08c1666118bcef6788ef523f8ce8facb to PENDING with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/81/ and message: Build started, sha1 is merged
Building remotely on edison (cray_cle) in workspace /global/homes/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02
Cloning the remote Git repository
Cloning repository https://github.com/open-mpi/ompi
 > git init /global/homes/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02 # timeout=10
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
GCM: Sending notification to: hpp
Setting status of 69a0e1dd08c1666118bcef6788ef523f8ce8facb to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/81/ and message: Build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/583/

**Build Log**
*last 50 lines*

 ```
[...truncated 12042 lines...]
  CC       punpack_f.lo
  CC       punpublish_name_f.lo
  CC       pwaitall_f.lo
  CC       pwaitany_f.lo
  CC       pwait_f.lo
  CC       pwaitsome_f.lo
  CC       pwtick_f.lo
  CC       pwtime_f.lo
  CC       paccumulate_f.lo
  CC       praccumulate_f.lo
  CC       pget_f.lo
  CC       prget_f.lo
  CC       pget_accumulate_f.lo
  CC       prget_accumulate_f.lo
  CC       pput_f.lo
  CC       prput_f.lo
  CC       pcompare_and_swap_f.lo
  CC       pfetch_and_op_f.lo
  CC       pwin_allocate_f.lo
  CC       pwin_attach_f.lo
  CC       pwin_allocate_shared_f.lo
  CC       pwin_call_errhandler_f.lo
  CC       pwin_complete_f.lo
  CC       pwin_create_dynamic_f.lo
  CC       pwin_create_errhandler_f.lo
  CC       pwin_create_f.lo
  CC       pwin_create_keyval_f.lo
gcc: pwin_create_dynamic_f.c: No such file or directory
gcc: no input files
  CC       pwin_delete_attr_f.lo
make[3]: *** [pwin_create_dynamic_f.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
gcc: pwin_attach_f.c: No such file or directory
gcc: no input files
make[3]: *** [pwin_attach_f.lo] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mpi/fortran/mpif-h/profile'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mpi/fortran/mpif-h'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/583/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/5c91fca0f5cdf35b49c6aa3acd3d3eab042c224b
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 69a0e1dd08c1666118bcef6788ef523f8ce8facb to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/583/ and message: Build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
bot:retest

a check again of IU jenkins

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/84/

**Build Log**
*last 20 lines*

 ```
[...truncated 7216 lines...]
  CC       pput_f.lo
  CC       prput_f.lo
  CC       pcompare_and_swap_f.lo
  CC       pfetch_and_op_f.lo
  CC       pwin_allocate_f.lo
  CC       pwin_allocate_shared_f.lo
  LN_S     pwin_attach_f.c
ln: failed to create symbolic link `pwin_attach_f.c': File exists
make[3]: *** [pwin_attach_f.c] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi/mpi/fortran/mpif-h/profile'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi/mpi/fortran/mpif-h'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
GCM: Sending notification to: hpp
Setting status of 69a0e1dd08c1666118bcef6788ef523f8ce8facb to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/84/ and message: Build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 810 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//601/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/23/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/112/
Test PASSed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/633/

**Pull request merged**
