### PR TITLE
pmix: fixed immediate request

### PR DESCRIPTION
**Pull request by karasevb**
This commit fixes a hang when using external PMIx v1 module

Signed-off-by: Boris Karasev <karasev.b@gmail.com>

refs #3977

### CODE REVIEW

**Comment by artpol84** [comment]
@karasevb
So this is only for a singletons?

**Comment by karasevb** [comment]
@artpol84 Not only for singletons. Also problem has existed for multi ranks.

**Comment by artpol84** [comment]
Need another PR for that?

**Comment by karasevb** [comment]
@artpol84 
No. This fix targeting to both cases. There are two fixes, one of them fixes the optional request for only singleton, and second fixes the info-key for the immediate request that leads to hang for both cases (for single and multi ranks).

**Comment by bwbarrett** [comment]
@jladd-mlnx, please don't add 3.0.0 milestone to a patch on master.  Feel free to add it to the issue (and add the blocker label so we won't release 3.0.0 before the issue is fixed), but this particular PR doesn't impact 3.0.0 directly and adding milestones just makes the release managers' job harder.

**Comment by jladd-mlnx** [comment]
@bwbarrett Roger that.

**Pull request merged**
