### PR TITLE
Update to PMIx/PRRTE tagged release candidates

### PR DESCRIPTION
**Pull request by rhc54**
PMIx v5.0.4rc1
PRRTE v3.0.7rc1

### CODE REVIEW

**Comment by rhc54** [comment]
@janjust

**Comment by janjust** [comment]
@rhc54 thank you!

**Comment by rhc54** [comment]
@janjust Just curious - why the skipped test?

**Comment by janjust** [comment]
@rhc54 I think with the mpi4py issue we've had in the past we made these tests optional, and to run them we need to apply the mpi4py label on the PR otherwise they get skipper. I don't remember if we ever fixed these but for now they remain optional.

**Comment by rhc54** [comment]
FWIW: looks like we have all that fixed now (kinda what I remembered, hence my question). Up to you if you want to just turn those tests "on". Note this are intended to be the last releases in those project branches, so you shouldn't see any more issues arising from that direction.

**Review by janjust — APPROVED** [review]

**Pull request merged**
