### PR TITLE
OSC/UCX: fixed hang on OSC UCX init - v4.0

### PR DESCRIPTION
**Pull request by hoopoepg**
- there worked progress was missed on startup which caused hang
  on one of ranks

picked up from https://github.com/open-mpi/ompi/pull/5452

Signed-off-by: Sergey Oblomov <sergeyo@mellanox.com>
(cherry picked from commit a081fba0465e0e03472fc45c9a4a7154f539e3f6)

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:mellanox:retest

**Comment by hoopoepg** [comment]
bot:mellanox:retest

**Comment by hoopoepg** [comment]
bot:mellanox:retest

**Comment by jladd-mlnx** [comment]
@hjelmn can you take a look at these UCT BTL build warnings/errors, please. 

@hppritcha @gpaulsen FYI

**Comment by hoopoepg** [comment]
@jladd-mlnx there are issues in build environment (fs sync)

**Comment by hoopoepg** [comment]
bot:mellanox:retest

**Pull request merged**
