### PR TITLE
btl/openib: fix compile problems when using experimental verbs

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@artpol84 This should fix the compile issue you saw. I unfortunately relied on jenkins to test the prior PR.

**Comment by hjelmn** [comment]
@miked-mellanox Is there a reason Mellanox Jenkins is not running?

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
checking it

**Comment by artpol84** [comment]
@hjelmn Yes, this fixes compilation problems.
@miked-mellanox I think you can merge the PR once you're done with Jenkins.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
