### PR TITLE
v5.0.x: Update PMIx and PRRTe submodule pointers.

### PR DESCRIPTION
**Pull request by awlauria**

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by gpaulsen** [comment]
What versions did these go to?  please add that to submodule update PRs

**Comment by rhc54** [comment]
PMIx v4.2.4 has been released, so you might want to update to that tag. PRRTE v3.0.1 remains under development for a little longer (probably another week).

**Pull request merged**
