### PR TITLE
Fix yalla PML: MPI_Recv does not return MPI_ERR_TRUNCATE upon overflow

### PR DESCRIPTION
**Pull request by derbeyn**
Applies commit from PR #3260 to v2.x
Signed-off-by: Nadia Derbey <Nadia.Derbey@atos.net>

### CODE REVIEW

**Comment by derbeyn** [comment]
@yosefe : can you review please?

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by derbeyn** [comment]
@yosefe can you merge this pr on v2.x please? We are waiting for the fix on our side. Thx

**Comment by yosefe** [comment]
@derbeyn i don't have permissions for that
@hppritcha can you pls merge?

**Pull request merged**
