### PR TITLE
V4.0.x Coll/hcoll: don't init opal memhooks unless explicitely requested

### PR DESCRIPTION
**Pull request by vspetrov**
V4.0.x version of #6690 

Signed-off-by: Valentin Petrov <valentinp@mellanox.com>

### CODE REVIEW

**Comment by gpaulsen** [comment]
How can we restart the Mellanox CI testing?

**Comment by jladd-mlnx** [comment]
bot:mellanox:retest

**Comment by yosefe** [comment]
@hppritcha can we merge this please?

**Comment by AboorvaDevarajan** [comment]
Can one of the admins verify this patch?

**Pull request merged**
