### PR TITLE
osc/rdma: fix typo in ompi_osc_rdma_lock_acquire_exclusive

### LINKED ISSUE #3571: concurrent accumulate osc=rdma
The following MPI_Accumulate() testcase fails on master using -np 3 and osc=rdma:
https://gist.github.com/markalle/3405203fb2970f94ad515cce23b4f602

I'm running on x86-64 (redhat 6 and/or 7) with mellanox infiniband.

This test has every rank accumulate the buffer [1 1 1 1 1 1 1 1] to every peer over and over in a loop and expects to see [n n n n n n n n] at the end, where n = nloops * (nranks - 1).

The standard says concurrent accumulates are supposed to be allowed.

Is there a build-time option or an info argument I should be using that's maybe turned off by default, or is this just not supported?

### PR DESCRIPTION
**Pull request by hjelmn**
Fixes #3571

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>
(cherry picked from commit b83c5dbee512e40566e45742909149777c71768f)
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
the pending state owes to a break in jenkins testing.

**Comment by hjelmn** [comment]
@markalle @gpaulsen Please review.

**Comment by hjelmn** [comment]
Anyone going to review this? It fixes the bug IBM reported.

**Comment by markalle** [comment]
Yes, my test is working with this change, so looks good to me - thanks!

**Comment by hppritcha** [comment]
Give OMPI Jenkins one more chance -

bot:ompi:retest

**Comment by jjhursey** [comment]
The CI test "open-mpi.pull_request" has been stalled for more than a week. I think that's because it should have been named "Pull Request Build Checker". GitHub uses that name string as a unique identifier to 'file' the CI test. So what I think happened is that when the build started the Jenkins CI was named "open-mpi.pull_request" but before the test finished it changed to "Pull Request Build Checker" which is where the final result was filed.

@bwbarrett Can you confirm that "open-mpi.pull_request" is stale and can be safely ignored?

**Pull request merged**
