### PR TITLE
Update the RML/OFI component

### PR DESCRIPTION
**Pull request by rhc54**
Combine a whole lot of commits from @anandhis branch to make just one that has been signed off. This updates the RML/OFI component to make it operational, leaving the opal_ignore in place

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@anandhis I'm not able to run this branch - getting error reports of "unreachable". Please see this gist for the output: https://gist.github.com/rhc54/c7abb70fa99deec8fecdaef52629aa80

**Comment by rhc54** [comment]
It looks to me like the conduit ID was never set, and so we are attempting to send to a non-existent conduit. This might be some error in the rebase I did - I compared code and everything now looks the same as it did on your ofi3 branch, but maybe something else is missing from another part of the code tree?

**Comment by anandhis** [comment]
Please get everything from under rml – the glue code is in the base, think I had to merge portions of it to the open-mpi code.

The latest ofi3 branch is building and running at my end, and code comparisons seem to have all my fixes on ofi3 branch.

Thanks,
Anandhi

**Comment by rhc54** [comment]
Sigh - updating from the source repo/branch is just a disaster. Will recreate it from scratch

**Pull request closed without merging**
