### PR TITLE
pmix/pmix3x: Fix internal PMIx discovery logic.

### PR DESCRIPTION
**Pull request by artpol84**
See https://github.com/open-mpi/ompi/issues/8823 for the details.

bot:notacherrypick

### CODE REVIEW

**Comment by artpol84** [comment]
The fixes for other branches will follow.

**Comment by artpol84** [comment]
I'm waiting for the guys from LANL to confirm that this is fixing their problem (should be later today).
Once I'll hear from them, I'll remove the "WIP" label and open PRs to other branches.

**Comment by artpol84** [comment]
@rhc54 what is "PMIX_ID" and do we want to still check against it?

**Comment by rhc54** [comment]
> @rhc54 what is "PMIX_ID" and do we want to still check against it?

I have no idea - it isn't even something we deprecated. I'd remove it.

**Comment by artpol84** [comment]
Just got the confirmation that on the system where the problem was observed this indeed fixes the issue:
```
$> OMPI_MCA_pmix_base_verbose=100 srun -n 2 --mpi=pmix_v3 ./a.out
...
[sn001.localdomain:35359] mca:base:select: Auto-selecting pmix components
[sn001.localdomain:35359] mca:base:select:( pmix) Querying component [isolated]
[sn001.localdomain:35359] mca:base:select:( pmix) Query of component [isolated] set priority to 0
[sn001.localdomain:35359] mca:base:select:( pmix) Querying component [pmix3x]
[sn001.localdomain:35359] mca:base:select:( pmix) Query of component [pmix3x] set priority to 100
[sn001.localdomain:35359] mca:base:select:( pmix) Querying component [s1]
[sn001.localdomain:35359] mca:base:select:( pmix) Query of component [s1] set priority to 10
[sn001.localdomain:35359] mca:base:select:( pmix) Querying component [s2]
[sn001.localdomain:35359] mca:base:select:( pmix) Selected component [pmix3x]
...
```

**Review by rhc54 — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
Which release branches is this PR relevant to?

**Comment by artpol84** [comment]
I think all of them

**Comment by artpol84** [comment]
I'm going to create PRs to 4.x and 3.x branches

**Comment by artpol84** [comment]
@jjhursey @gpaulsen please help with IBM failure

**Comment by jsquyres** [comment]
Ok.  After this PR is merged, can you cherry-pick to all relevant release branches?  Thanks.

**Comment by artpol84** [comment]
@jsquyres already opened.
I guess we don't want to go as far as v2.x, right?

**Comment by jsquyres** [comment]
> @jsquyres already opened.
> I guess we don't want to go as far as v2.x, right?

Correct.

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Review by hppritcha — APPROVED** [review]

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Pull request merged**
