### PR TITLE
v1.10: fix ompi_wrapper_script

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by rhc54** [comment]
Passing outside the 1.10.6 window

**Comment by jsquyres** [comment]
@rhc54 This PR was created against the v1.10 branch -- we unfortunately can't just bump the milestone to v2.x.

**Comment by jsquyres** [comment]
@ggouaillardet Can you add the signed-off-by lines to these commits?

**Comment by ggouaillardet** [comment]
@jsquyres both commits have been signed-off-by

**Pull request merged**
