### PR TITLE
opal/mca/ofi: Patch series to fix a crash due to double free on error path

### PR DESCRIPTION
**Pull request by wenduwan**
There is a bug in the current impl which attempts to compare local rank vs global rank. Furthermore, when this fails it triggers a double free on the error path, i.e. crash.

This change set addresss the root cause.

### CODE REVIEW

**Comment by wenduwan** [comment]
@lrbison Yes sir. Addressed.

**Review by lrbison — APPROVED** [review]
Thank you!

**Comment by wenduwan** [comment]
@lrbison Can we merge? I think 1 review is good enough for this PR.

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by wenduwan** [comment]
@gpaulsen Is it possible to share the IBM CI failure? Thanks

**Comment by gpaulsen** [comment]
Sorry, the IBM failure appears to be a firewall issue on our end.  Working to get it resolved soon.

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by gpaulsen** [comment]
IBM lab folks are still investigating the IBM CI failure this morning.

**Comment by awlauria** [comment]
@wenduwan it is not..it's a lab machine/hardware issue.

**Comment by wenduwan** [comment]
@lrbison Since we can bypass IBM CI, shall we merge this change?

**Pull request merged**
