### PR TITLE
oob/v2.0.x/msg drop

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by artpol84** [comment]
@jjhursey if I go by the link I see that test has passed. Can you check please?

**Comment by artpol84** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
@rhc54 Can you review?  Thanks.

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
