### PR TITLE
NEWS - update for 4.0.6rc3

### PR DESCRIPTION
**Pull request by hppritcha**
bot:notacherrypick

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by gpaulsen** [comment]
I bumped the date to June, and IBM's copyright.  Which Copyright do you use these days?

**Comment by gpaulsen** [comment]
Of course editing using the github browser will cause CI to fail due to:
```
Error:     * check_signed_off: does not contain a valid Signed-off-by line
```

repushing.

**Comment by hppritcha** [comment]
@jjhursey could you check what's going on with IBM PGI CI?

**Comment by jjhursey** [comment]
IBM CI (PGI) hit a local network blip. Should be good now.
bot:ibm:pgi:retest

**Review by gpaulsen — APPROVED** [review]
Howard and I did our due diligence to check VERSIONS and NEWS and all looks ready for rc3.

**Pull request merged**
