### PR TITLE
ompi/comm: make communicator.h safe for C++ bindings

### LINKED ISSUE #2055: Compilation fails for powerpc with --enable-mpi-cxx
Hi,

Enabling --enable-mpi-cxx leads to:

```
make[2]: Entering directory '/home/mckinstry/openmpi-2.0.1/ompi/mpi/cxx'
/bin/bash ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../opal/include -I../../../ompi/include -I../../../oshmem/include -I../../../opal/mca/hwloc/hwloc1112/hwloc/include/private/autogen -I../../../opal/mca/hwloc/hwloc1112/hwloc/include/hwloc/autogen -I../../../ompi/mpiext/cuda/c  -DOMPI_BUILDING_CXX_BINDINGS_LIBRARY=1 -DOMPI_SKIP_MPICXX=1 -I../../.. -I../../../orte/include -Wdate-time -D_FORTIFY_SOURCE=2   -I/usr//include -I/home/mckinstry/openmpi-2.0.1/opal/mca/event/libevent2022/libevent -I/home/mckinstry/openmpi-2.0.1/opal/mca/event/libevent2022/libevent/include  -DNDEBUG -g -O2 -fdebug-prefix-map=/home/mckinstry/openmpi-2.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -finline-functions -pthread -c -o mpicxx.lo mpicxx.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../opal/include -I../../../ompi/include -I../../../oshmem/include -I../../../opal/mca/hwloc/hwloc1112/hwloc/include/private/autogen -I../../../opal/mca/hwloc/hwloc1112/hwloc/include/hwloc/autogen -I../../../ompi/mpiext/cuda/c -DOMPI_BUILDING_CXX_BINDINGS_LIBRARY=1 -DOMPI_SKIP_MPICXX=1 -I../../.. -I../../../orte/include -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr//include -I/home/mckinstry/openmpi-2.0.1/opal/mca/event/libevent2022/libevent -I/home/mckinstry/openmpi-2.0.1/opal/mca/event/libevent2022/libevent/include -DNDEBUG -g -O2 -fdebug-prefix-map=/home/mckinstry/openmpi-2.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -finline-functions -pthread -c mpicxx.cc  -fPIC -DPIC -o .libs/mpicxx.o
In file included from ../../../opal/class/opal_object.h:128:0,
                 from ../../../ompi/errhandler/errhandler.h:32,
                 from mpicxx.cc:37:
../../../opal/threads/thread_usage.h: In function 'int32_t opal_thread_swap_32(volatile int32_t*, int32_t)':
../../../opal/threads/thread_usage.h:134:76: error: 'opal_atomic_swap_32' was not declared in this scope
         return opal_atomic_swap_ ## suffix ((volatile type *) ptr, newvalue); \
```

This fails because in opal/include/opal/sys/atomic.h: 

```
 #if defined(c_plusplus) || defined(__cplusplus)
/* We no longer support inline assembly for C++ as OPAL is a C-only interface */
#define opal_atomic_swap_32 0
#define OPAL_DEC_INLINE_ASSEMBLY 0
#define OPAL_XLC_INLINE_ASSEMBLY 0
```

and _opal_atomic_swap_32_ is conditionally only included if opal_atomic_swap_32 is set

### PR DESCRIPTION
**Pull request by hjelmn**
Fixes #2055

Signed-off-by: Nathan Hjelm hjelmn@me.com

### CODE REVIEW

**Comment by jsquyres** [comment]
@hjelmn Ready to merge?

**Comment by hjelmn** [comment]
Hoping to hear whether this fixed the issue. Otherwise it is ready.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ab054f4507df95b7ab46593d2e64efed

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
This commit does not quite fix the problem. I think there is more to do in maybe the `cxx_glue.h` file.

```shell
  CC       cxx_glue.lo
In file included from ../../../opal/class/opal_object.h:128:0,
                 from ../../../ompi/errhandler/errhandler.h:36,
                 from cxx_glue.h:18,
                 from datatype.cc:18:
../../../opal/threads/thread_usage.h: In function ‘int32_t opal_thread_swap_32(volatile int32_t*, int32_t)’:
../../../opal/threads/thread_usage.h:134:76: error: ‘opal_atomic_swap_32’ was not declared in this scope
         return opal_atomic_swap_ ## suffix ((volatile type *) ptr, newvalue); \
                                                                            ^
../../../opal/threads/thread_usage.h:147:1: note: in expansion of macro ‘OPAL_THREAD_DEFINE_ATOMIC_SWAP’
 OPAL_THREAD_DEFINE_ATOMIC_SWAP(int32_t, int32_t, 32)
 ^
In file included from ../../../opal/class/opal_object.h:128:0,
                 from ../../../ompi/errhandler/errhandler.h:36,
                 from cxx_glue.h:18,
                 from comm.cc:27:
../../../opal/threads/thread_usage.h: In function ‘int32_t opal_thread_swap_32(volatile int32_t*, int32_t)’:
../../../opal/threads/thread_usage.h:134:76: error: ‘opal_atomic_swap_32’ was not declared in this scope
         return opal_atomic_swap_ ## suffix ((volatile type *) ptr, newvalue); \
                                                                            ^
../../../opal/threads/thread_usage.h:147:1: note: in expansion of macro ‘OPAL_THREAD_DEFINE_ATOMIC_SWAP’
 OPAL_THREAD_DEFINE_ATOMIC_SWAP(int32_t, int32_t, 32)
```

**Comment by hjelmn** [comment]
I don't think this is necessary. The correct fix is in #3589.

**Pull request closed without merging**
