### PR TITLE
v4.0: Check for librt when building LSF support

### PR DESCRIPTION
**Pull request by jjhursey**
bot:notacherrypick

### CODE REVIEW

**Comment by jjhursey** [comment]
Open MPI v4.1.x version of PRRTE https://github.com/openpmix/prrte/pull/809

**Review by awlauria — APPROVED** [review]

**Review by gpaulsen — APPROVED** [review]

**Comment by jjhursey** [comment]
1 more commit coming from a review on PR #8564. Once that is 👍  then I'll cherry-pick it over here (and PRRTE).

**Comment by jjhursey** [comment]
I just pushed the refinement commit from PR #8564 - so the two match each other now.

This is good for review.

**Review by jsquyres — APPROVED** [review]
I can't test, but LGTM.

**Pull request merged**
