### PR TITLE
Update hwloc to v1.11.3

### PR DESCRIPTION
**Pull request by bgoglin**
Update hwloc to v1.11.3
    
Remove contrib/windows/
Merge hwlocXYZ/hwloc/README-ompi.txt back into hwlocXYZ/README-ompi.txt instead of having both.
Add README.txt in new automake-required directory contrib/systemd/
    
Keep the following patches applied since they are not in 1.11.3
        linux: actually enable libudev based on the result of AC_CHECK_LIB
        (cherry picked from open-mpi/hwloc@9549fd59af04dca2e2340e17f0e685f8c552d818)
        configure: check the actual may_alias syntax that we use
        (cherry picked from open-mpi/hwloc@0ab7af5e90fc2b58be30b2126cc2a73f9f7ecfe9)

### CODE REVIEW

**Comment by jsquyres** [comment]
:+1:

**Comment by ibm-ompi** [comment]
Test passed.

**Comment by bgoglin** [comment]
github autoclosed because I pushed OMPI's master to my branch (there was nothing to pull anymore). I pushed my updated branch properly and reopened.

**Comment by ibm-ompi** [comment]
Test passed.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
Thanks for the PR, @bgoglin.

**Pull request merged**
