### PR TITLE
Integrate PMIx 1.0 into OMPI master

### PR DESCRIPTION
**Pull request by rhc54**
I know I don't have all the rebasing done correctly just yet, but I'll get help on fixing it later. This PR will bring PMIx 1.0 into the master. It isn't quite complete yet - it passes most of the MTT tests, but there are a number of failures I need to address..

Still, the basic elements are here for people to being reviewing.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@rhc54 Perhaps I missed another case just like https://github.com/rhc54/ompi/commit/5cf622ef356cd8b95ccb5e33e41e61b1b13c05c2...?  (i.e., for a component that didn't compile on my system)

**Comment by rhc54** [comment]
I don't know what the Jenkins servers think they are doing - if I look at the "details", the errors bear no resemblance to the current code. They flag lines that don't exist after I merged your pull. So clearly something is screwed up here.

I'll try closing this PR and opening another to see if they get straightened out.

**Pull request closed without merging**
