### PR TITLE
v4.0.x/regex: fixed host ordering for different prefixes

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to https://github.com/open-mpi/ompi/pull/6306

### CODE REVIEW

**Comment by gpaulsen** [comment]
@hppritcha, I think we should merge into v4.0.1

**Comment by rhc54** [comment]
@jjhursey It occurs to me that we now are getting different answers from PMIx_resolve_node and friends then we get from OMPI. IIRC, you had users that were trying to utilize the PMIx functions. Do we need this change (and your "reverse" component) backported to PMIx?

**Comment by jjhursey** [comment]
As long as `PMIx_resolve_node` preserves ordering (which it does now in PMIx) then we are ok. From the `master` [testing](https://github.com/open-mpi/ompi/pull/6306#issuecomment-458800769) on this PR @karasevb verified that this patch fixes that case for OMPI too when using the forward regex component.

The reverse component was helpful in making a more compact representation for the customer than the forward component. So we are ok with the forward component as long as it works correctly, which this PR seems to address for OMPI. For PMIx, it would be nice to bring over the reverse functionality to improve compression for those hostnames, but if we are moving to a more general technique in PMIx then we can just wait for that.

**Comment by rhc54** [comment]
Interesting - I wonder what the difference is between the PMIx and OMPI regex components? I thought they were just copies of each other.

Yeah, we'll be moving to compression in PMIx as well. I also have a skeleton for a new regex parser that doesn't distinguish between alpha and numeric patterns, but that will have to come later.

**Pull request merged**
