### PR TITLE
Have rank=1 daemon always send its topology back as this is the most common use-case

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
@rhc54 @jsquyres 
It looks like Jenkins haven't catched this PR and no check was run. Can we revert, check and merge back?

**Pull request merged**
