### PR TITLE
build: Remove unused macros

### PR DESCRIPTION
**Pull request by bwbarrett**
Remove another round of macros that are no longer invoked by OMPI's
configure script.

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fd322018290b5571de8d3a561086a0f0

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/33dc8fa796c234e7a9845070ba4a5103

**Review by jsquyres — APPROVED** [review]

**Review by jsquyres — APPROVED** [review]
Amusingly, you removed the `m4` file that `autogen.pl` was using as a sentinel to ensure that it was at the top of the OMPI tree.  😄   I took the liberty of changing the sentinel file to be `config/ompi_mca.m4`, since that file is not going to disappear any time soon.

**Pull request merged**
