### PR TITLE
mpiext: keep include path for extension short

### PR DESCRIPTION
**Pull request by ggouaillardet**
in order to cope with the 72 characters per line limit, move
openmpi/ompi/mpiext/FOO/mpif-h/mpiext_FOO_mpifh.h to
openmpi/ompi/mpiext/FOO_mpifh.h

Refs. open-mpi/ompi#6019

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c5014c3991879e37b1ce077441828261

**Comment by kawashima-fj** [comment]
@ggouaillardet What is the status of this PR? Waiting @jsquyres's review? It looks good to me.

**Comment by kawashima-fj** [comment]
@ggouaillardet I understand. Thanks.

**Comment by ggouaillardet** [comment]
@kawashima-fj I made the changes for the `C` headers. Feel free to review once again and merge this PR, I will then PR for `v4.0.x`

**Comment by ggouaillardet** [comment]
@jsquyres the previous PR you are referring works because it is applied to a file in the build tree that is pre-processed by Fortran.

This PR deals with `<prefix>/include/mpif-ext.h` that might not be pre-processed by the Fortran compiler of the end user. A simple fix was to shorten the paths of the extension headers. An other option would have been to slurp these files into a huge and unique `<prefix>/include/mpif-ext.h`.

For the sake of consistency, I made similar changes to the C files, and yes, these changes are note required and do not fix anything. Otherwise we would have `<prefix>/include/openmpi/ompi/mpiext/pcollreq_mpifh.h` and `<prefix>/include/openmpi/ompi/mpiext/pcollreq/c/mpiext_pcollreq_c.h`

Note these files should never been used directly by the endusers.

**Comment by ggouaillardet** [comment]
This PR fixes the `include 'openmpi/ompi/mpiext/$component/mpif-h/$component_header'` issue (over 72 characters with `pcollreq`). This is independent of the directory Open MPI is built in (this was a separate issue that has been fixed in an other PR).

This line ends up in `<prefix>/include/mpif-ext.h>` (__not__ an _internal-to-OMPI_ file) and endusers are required to `include 'mpif-ext.h'` in order to use Fortran persistent collectives.
If we replace this with a `#include` (and restore or not the previous long path), that means endusers are now required to have their Fortran files preprocessed, and I do not think we want to add this new requirement.

Makes sense ?

**Comment by jsquyres** [comment]
Ok, I see.  Old way:

```
<prefix>/include/openmpi/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h
<prefix>/include/openmpi/ompi/mpiext/pcollreq/c/mpiext_pcollreq_c.h
<prefix>/include/openmpi/ompi/mpiext/pcollreq/c/pmpiext_pcollreq_c.h
<prefix>/include/openmpi/ompi/mpiext/cuda/c/mpiext_cuda_c.h
<prefix>/include/openmpi/ompi/mpiext/affinity/c/mpiext_affinity_c.h
```

New way:

```
<prefix>/include/openmpi/ompi/mpiext/affinity_c.h
<prefix>/include/openmpi/ompi/mpiext/pcollreq_c.h
<prefix>/include/openmpi/ompi/mpiext/pcollreq_mpifh.h
<prefix>/include/openmpi/ompi/mpiext/ppcollreq_c.h
<prefix>/include/openmpi/ompi/mpiext/cuda_c.h
```

@ggouaillardet After seeing these visually like this, I grok more of you're saying now -- indeed, I agree that the prefix `mpiext_` on the actual file name is redundant, for example.

I just created #6145 with an additional suggestion and some more discussion; let's continue the discussion there.

**Comment by jsquyres** [comment]
Just following up here in the original PR: I initially made PR #6145, but @ggouaillardet took that work and made new PR #6158, which ended up being the Right answer.

**Pull request merged**
