### PR TITLE
Update commit IDs of prrte and openpmix to the latest release commits 

### PR DESCRIPTION
**Pull request by vidsouza**
This patch updated the commit IDs of prrte and openpmix submodules based on the new release of each module

### CODE REVIEW

**Comment by wenduwan** [comment]
rocm CI failure
```
 Unpacking rocfft (1.0.23.50700-63~20.04) ...
dpkg: error processing archive /tmp/apt-dpkg-install-q6oKCW/62-rocfft_1.0.23.50700-63~20.04_amd64.deb (--unpack):
 cannot copy extracted data for './opt/rocm-5.7.0/lib/rocfft/rocfft_kernel_cache.db' to '/opt/rocm-5.7.0/lib/rocfft/rocfft_kernel_cache.db.dpkg-new': failed to write (No space left on device)
No apport report written because the error message indicates a disk full error
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package hipfft.
```

**Comment by awlauria** [comment]
I don't think this PR is correct. ompi main has tracked prrte and pmix main branches, not release branches.

**Comment by wenduwan** [comment]
@awlauria Thanks for pointing it out. So for ompi/main we track prrte/pmix/main, and v5.0.x etc we should track prrte/pmix release branch correct?

**Comment by wenduwan** [comment]
In that case @vidsouza we should close this PR, and submit another PR(add bot:notacherrypick) to v5.0.x branch with the same submodule pointers.

**Comment by lrbison** [comment]
@wenduwan yes, Austen already did it in https://github.com/open-mpi/ompi/pull/11952

**Comment by wenduwan** [comment]
Cool cool thank you!

**Comment by vidsouza** [comment]
Closing this PR based on the comments above.

**Comment by awlauria** [comment]
Thanks @vidsouza

**Pull request closed without merging**
