### PR TITLE
Use OPAL/ORTE_IDENT_STRING in mpirun/orterun --version

### PR DESCRIPTION
**Pull request by gpaulsen**
When configuring --with-ident-string="SomeString", put SomeString in mpirun --version output

### CODE REVIEW

**Comment by jjhursey** [comment]
👍  on Brian review. You can use `git commit --amend` to edit the commit message, then just update the PR to reflect.

**Comment by jsquyres** [comment]
@ggouaillardet I think it's `./configure --with-ident-string="Cisco rules"`

**Comment by gpaulsen** [comment]
@ggouaillardet yes, we use _./configure --with-ident-string="Cisco rules"_ but then we do some string mangling after that...  just ask Jeff about "Eunuchs".

**Comment by gpaulsen** [comment]
whoops.  I forgot to update commit message.  Thanks for heads up.

**Comment by jjhursey** [comment]
I fixed up the title of the PR, and remove the cherry-pick from the PR description. I think this is in good shape now.

**Comment by ggouaillardet** [comment]
@jjhursey i checked that and it works fine.

this PR tests the `OMPI_IDENT_STRING` that is not defined by default when building `orte` (the macro is in `ompi/include/ompi_config.h`)

even if that looks a bit fishy (and hence my initial comment), the outcome is the expected one.

**Comment by jjhursey** [comment]
@ggouaillardet Thanks for checking. I'm good with this change then.

**Comment by rhc54** [comment]
@gpaulsen Could you please put a comment in there to explain what is going on? I can guarantee that nobody will remember in the future.

**Comment by gpaulsen** [comment]
Sure, I'll capture this in a git commit --amend and repush.

**Comment by rhc54** [comment]
Urrr...I actually meant a comment in the code itself. Like you said, the code looks "fishy", so I'm sure a future developer will not understand and potentially remove it.

**Comment by jjhursey** [comment]
Something is fishy here. I tried a build with:
`./configure --prefix=/tmp/ompi-test --with-ident-string="IBM Rulz"`

Then when I run I get:
```
$$  mpirun --version
mpirun (Open MPI) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
$$ orterun --version
orterun (IBM Rulz) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
```

In the default build, note that `orterun` does not print `OpenRTE` but instead just prints the version string. I'm wondering if this mechanism was broken a bit before this PR.

Default build:
```
$$ mpirun --version
mpirun (Open MPI) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
$$ orterun --version
orterun (4.0.0a1) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
```

**Comment by rhc54** [comment]
To be honest, I don't recall ever supporting that in mpirun. We always just printed out basename and version string - this is how the code has looked forever:
```c
    /* see if print version is requested. Do this before
     * check for help so that --version --help works as
     * one might expect. */
     if (orte_cmd_options.version) {
        char *str, *project_name = NULL;
        if (0 == strcmp(orte_basename, "mpirun")) {
            project_name = "Open MPI";
        } else {
            project_name = "OpenRTE";
        }
        str = opal_info_make_version_str("all",
                                         OPAL_MAJOR_VERSION, OPAL_MINOR_VERSION,
                                         OPAL_RELEASE_VERSION,
                                         OPAL_GREEK_VERSION,
                                         OPAL_REPO_REV);
        if (NULL != str) {
            fprintf(stdout, "%s (%s) %s\n\nReport bugs to %s\n",
                    orte_basename, project_name, str, PACKAGE_BUGREPORT);
            free(str);
        }
        exit(0);
    }
```

**Comment by rhc54** [comment]
The ident-string option went into other places in the code - never into mpirun.

**Comment by jsquyres** [comment]
I agree w/ Ralph -- the ident string probably never went to `mpirun --version` output.

That being said: I think it's actually kinda natural to put it in `mpirun --version` output.  As long as it's done carefully / correctly.  😄

**Comment by gpaulsen** [comment]
Okay, I think I've fixed this for both cases now.

I configured with: `./configure --prefix=/Users/gpaulsen/ompi_install/Mar28 --with-package-string="Package String" --with-ident-string="Ident String"`

Now mpirun --version and orterun --version both print "Ident String" correctly.

**Comment by jjhursey** [comment]
From my testing:

`./configure --prefix=/tmp/ompi-gp --with-ident-string="IBM Rulz"`

```
$$ mpirun --version
mpirun (IBM Rulz) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
$$ orterun --version
orterun (IBM Rulz) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
```

`./configure --prefix=/tmp/ompi-gp2`

```
$$ mpirun --version
mpirun (4.0.0a1) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
$$ orterun --version
orterun (4.0.0a1) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
```
Should these be printing `Open MPI` and `OpenRTE` respectively?

**Comment by ggouaillardet** [comment]
Is there already a way to change the URL ?
If not, vendors might require that.

**Comment by rhc54** [comment]
Don't see how it could not be printing those names

**Comment by kawashima-fj** [comment]
@gpaulsen Fujitsu loves this PR. `strcmp`ing `mpiexec` in addition to `mpirun` is better.

@ggouaillardet The URL comes from `AC_INIT` in `configure.ac`. Fujitsu changes it manually.

**Comment by rhc54** [comment]
@jjhursey Yeah, there is a bug in here somewhere - this is with today's master:
```shell
$ mpirun --version
mpirun (Open MPI) 4.0.0a1

Report bugs to http://www.open-mpi.org/community/help/
```
So something is wrong when no ident string is defined.

**Comment by gpaulsen** [comment]
bot:ompi:retest

**Comment by AboorvaDevarajan** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
