### PR TITLE
Add opal_recursive_mutex_t support to qthreads

### PR DESCRIPTION
**Pull request by janciesko**
- Adds the opal_recursive_mutex_t type to qthreads.
- Fixes some segfaults when ompi is configured to qthreads.

### CODE REVIEW

**Review by hppritcha — APPROVED** [review]

**Comment by awlauria** [comment]
bot:retest

**Comment by awlauria** [comment]
ok to test

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by hppritcha** [comment]
ompi:bot:retest

**Comment by hppritcha** [comment]
not sure what's happening at aws jenkins
bot:ompi:retest

**Comment by hppritcha** [comment]
@janciesko looks like you need to rebase

**Comment by janciesko** [comment]
> @janciesko looks like you need to rebase

Rebased to v5.0.x

**Comment by hppritcha** [comment]
oops, @janciesko i meant to rebase on top of master since there was some conflict.

**Comment by janciesko** [comment]
> oops, @janciesko i meant to rebase on top of master since there was some conflict.

Rebased to master.

**Comment by hppritcha** [comment]
yes i'll cherry-pick over to the 5.0.x

**Pull request merged**
