### PR TITLE
osc/base: Detect unsupported data types and abort

### PR DESCRIPTION
**Pull request by jjhursey**
Using MPI_MINLOC or MPI_MAXLOC with the following data types
leads to data corruption:
 * MPI_DOUBLE_INT
 * MPI_LONG_INT
 * MPI_SHORT_INT
 * MPI_LONG_DOUBLE_INT

Detect this print a error message and abort.
This workaround should be removed once the following issue is resolved:
 * https://github.com/open-mpi/ompi/issues/1666

Signed-off-by: Joshua Hursey <jhursey@us.ibm.com>
(cherry picked from commit 94f92f6b49212545355123d711abc91af9647d8e)
Signed-off-by: Joshua Hursey <jhursey@us.ibm.com>

### CODE REVIEW

**Comment by jjhursey** [comment]
Refs PR #2832

**Comment by nysal** [comment]
@jjhursey I think this patch will only work for osc/pt2pt. osc/rdma will probably need a similar check in ompi_osc_rdma_rget_accumulate_internal()

**Comment by jjhursey** [comment]
I've updated this PR to reflect the changes in PR #2927 - I'll keep them in sync if there are any further changes necessary.

**Comment by jjhursey** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@hppritcha Once CI finishes, good to go

**Pull request merged**
