### PR TITLE
PMIx event library changes

### PR DESCRIPTION
**Pull request by hjelmn**
This PR fixes a number of abstraction violations and adds libev support to PMIx. I will add libev support to Open MPI in another PR.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/1e4a8661a61d4d84cd0422c61d6ed9bb

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/a49a596fe4de608bc62dfc96b4193c5e

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/623572be5ef1444588b8333eb8d8de1b

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/5dba67b3268b8305ac9157717dae2f99

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/7b1f5f61ccb9406624bcd98c16fffb48

**Comment by hjelmn** [comment]
http://libev.schmorp.de/bench.html has a comparison of libev vs libevent.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/7dc5b51531b5a5a97d169465a2d5bc59

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/f524b50cc8132496f0c5eda59ec9c60b

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/1b90843c77094f2ee24e069be7c829fe

**Comment by hjelmn** [comment]
Still 1-2 issues outstanding. Will fix tomorrow.

**Comment by hjelmn** [comment]
The outstanding issue is this is working on OS X but not Linux. Hoping to have it resolved today.

**Comment by jjhursey** [comment]
We'll need to make sure these changes get upstream into pmix since they extend beyond the opal wrapper portions. That's probably on the todo list, but just wanted to make a note so we don't forget once this PR gets closer to completion.

**Comment by jsquyres** [comment]
Just curious -- is this *just* for PMIx?  Or is it a larger effort to switch OMPI to libev, too?

**Comment by rhc54** [comment]
It's to do OMPI as well - @hjelmn is just starting with the PMIx changes.

**Comment by jsquyres** [comment]
👍

**Comment by hjelmn** [comment]
Turns out the issues I was seeing under linux were:

 - I need to add a wakeup for pmix_event_add. Otherwise the new event won't be noticed until either an event fires or the timeout is hit (60s).

 - libev calls itself "thread safe" and they are in the same sense as the uGNI library. You are ok as long as you make specific calls (ev_async_send) or never operate on the event base of another thread. This is a far cry from what we need. On the plus side it was fairly simple to make ev_io_start, ev_timer_start, and ev_feed_event (event_add/event_active) thread safe.

The first issue is trivial to fix without modifying libev directly. The second issue did require modification to libev. I will probably end up solving both issues via modifications to libev and commit that to Open MPI as a fork of libev. I will be testing the changes tonight and will update the PMIx support (including checking that libev is our version before using it) tomorrow. So far everything is looking good.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/014c04af2b6c70fec5a322a1726d43b5

**Comment by hjelmn** [comment]
Going to handle this through several PRs. Closing this one.

**Pull request closed without merging**
