### PR TITLE
rsh: robustify the check for plm_rsh_agent default value

### PR DESCRIPTION
**Pull request by jsquyres**
Don't strcmp against the default value -- the default value may change
over time.  Instead, check to see if the MCA var source is not
DEFAULT.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@rhc54 I'm not 100% sure this is the right robustification.

This check simply checks to ensure that the value was set by someone other than the default.  But what if someone set it to exactly the same value as the default value?

I guess my question is: what exactly do we need to test here?

**Comment by rhc54** [comment]
I think this is exactly what we need - if someone "sets" it to the default value, then they have "confirmed" that this is what they want and we should obey it. If they specified nothing, then we want to open the door to look for alternatives.

So I'd say this is fine and should be committed - can then PR it across to 2.0.1

**Comment by jsquyres** [comment]
@rhc54 +1  I'll merge.

I think this can wait until v2.0.2 -- unless you strongly feel it needs to be in v2.0.1?  I.e., I think your existing code is more-or-less fine; this is a bit stronger enforcement, but not a critical issue.  Thoughts?

**Comment by rhc54** [comment]
agreed, it can wait

**Pull request merged**
