### PR TITLE
platform/mellanox: disable btl-uct by default

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by yosefe** [comment]
bot:retest

**Comment by hjelmn** [comment]
#5957 is a better option.

**Comment by hjelmn** [comment]
If and when github stops misbehaving. The PR keeps disappearing.

**Comment by hjelmn** [comment]
Okay, not sure if my comments will come back. Something is really off with github today. #5957 is a better fix.

**Comment by hjelmn** [comment]
Err, #5958. The other PR was in a broken state due to github issues.

**Comment by hjelmn** [comment]
master now works with OpenUCX master. Will open a PR for v4.0.1

**Comment by yosefe** [comment]
@hjelmn thanks

**Pull request merged**
