### PR TITLE
v3.1.x: OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
Equivalent of https://github.com/open-mpi/ompi/pull/7175 for 3.1.x

### CODE REVIEW

**Comment by gpaulsen** [comment]
We anticipate this to fix Issue: https://github.com/open-mpi/ompi/issues/7188

**Comment by Akshay-Venkatesh** [comment]
@gpaulsen would it be possible to rerun the failing mellanox test? It's surprising that it failed here but not the 4.0.x PR.

**Comment by jsquyres** [comment]
@Akshay-Venkatesh you can re-run tests via

bot:mellanox:retest

**Comment by Akshay-Venkatesh** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 @yosefe We are getting `GATEWAY_TIMEOUT, bgate.mellanox.com` and can't see the details of the CI failure.  Please help.  Thanks.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@Akshay-Venkatesh You need to get someone to review a PR to release branches.

**Comment by Akshay-Venkatesh** [comment]
@artpol84 can you provide a review for this one too?

**Comment by Akshay-Venkatesh** [comment]
@gpaulsen Can you provide a review?

**Comment by gpaulsen** [comment]
@Akshay-Venkatesh For your information, the best way to request a review from someone is to select their name from the Reviewers list on the top right of the Pull Request.

**Comment by jsquyres** [comment]
False Cray failure.

bot:lanl:retest

**Comment by jsquyres** [comment]
False AWS errors this time.

bot:ompi:retest

**Pull request merged**
