### PR TITLE
opal: use opal_list_t convienience macros

### PR DESCRIPTION
**Pull request by hjelmn**
This commit cleans up code in opal to use OPAL_LIST_FOREACH(_SAFE),
OPAL_LIST_DESTRUCT, and OPAL_LIST_RELEASE.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
There are probably spots I missed but this gets a good chunk of them in opal.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d07009182d5e77720244c4d5c0947d6b

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0e4690f790df2120478eeb2ab58eaac6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ec1b6a97450890fd23c224a7ae0f5ccc

**Comment by hjelmn** [comment]
:bot:mellanox:retest

**Comment by hjelmn** [comment]
:bot:mellanox:retest

**Comment by jladd-mlnx** [comment]
bot:mellanox:retest

**Pull request merged**
