### PR TITLE
Update to hwloc 2.4.0

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
This picks up a PGI fix from upstream hwloc
 - https://github.com/open-mpi/hwloc/pull/428

**Comment by jjhursey** [comment]
I updated the PGI in our containers - retesting just to confirm that nothing is broken 🤞 
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c1b8720912812e48e5dbaddeb6c3780f

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/89040c784be27a8da2fa4ffe2dce57ef

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5061cc7814afa7735819bb4a0e193d99

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/da313dfe33ad2ca3c7d35058fd8b8b68

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/245f89199648c51d47f8e0d0a92999b9

**Comment by jjhursey** [comment]
I'll take a look at the PGI failure next Tuesday. I'm not sure if it is related to this PR or not. It's failing on `base/coll_base_topo.c` which is pretty strange.

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0d1b9712e47fee3bcd261dc314b5db28

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by jjhursey** [comment]
OK. I fixed the PGI issue - it was a CI setup issue, not PGI or this PR. So now we are using PGI `20.11-0`

**Comment by jjhursey** [comment]
I found another PGI'ism in hwloc and filed a bug for it.
 * https://github.com/open-mpi/hwloc/pull/439

So though the 2.4.0 release fixes the detection of PGI, there was still a bit more to do. We can take this in as a good thing to do. We might want to update again before branching for v5.

**Pull request merged**
