### PR TITLE
mtl/ofi: break from progress loop when events are read

### PR DESCRIPTION
**Pull request by badgerious**
Once any number of events are read, return immediately, rather than
waiting for fi_cq_read() to return FI_EAGAIN or an error. This can
improve observed latency if the user application is in a blocking call
waiting for us to return. Breaking here also means
ofi_progress_event_count serves as an upper bound for the total number
of events read in a single call (without it, we could read far more, as
long as new events continue to arrive).

Signed-off-by: Eric Badger <eric@badgerio.us>

### CODE REVIEW

**Comment by bwbarrett** [comment]
ok to test

**Comment by badgerious** [comment]
> However, given the rest of the loop, the right fix should be to remove the `while (true) {`, rather than just adding a `break`.

Good point. I've reorganized it to drop the while loop.

**Comment by bwbarrett** [comment]
bot:aws:retest - looks like clang37 had a hang running the connectivity test.

**Comment by awlauria** [comment]
bot:ompi:retest

**Comment by awlauria** [comment]
bot:ompi:retest

**Comment by awlauria** [comment]
bot:ompi:retest

**Comment by awlauria** [comment]
bot:ompi:retest

**Pull request merged**
