### PR TITLE
Clean up the conduit open code so we return detectable errors when co…

### PR DESCRIPTION
**Pull request by rhc54**
…nduit not opened.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@anandhis Snapshot of current state

**Comment by rhc54** [comment]
@anandhis Here is what I'm seeing when I run with oob for mgmt conduit and ofi for coll conduit:
```
$$ mpirun -npernode 2 -mca rml_base_verbose 100 -mca grpcomm_base_verbose 5 -mca rml_ofi_transports fabric -mca routed direct hostname

<lots of stuff>

[rhc001:56772] [[27676,0],0] grpcomm:base:xcast sending 1136 bytes to tag 1
[rhc001:56772] [[27676,0],0] grpcomm:base:create_dmns called with NON-NULL signature
[rhc001:56772] MSG SIZE: 1191
[rhc001:56772] [[27676,0],0] rml:base:send_buffer_nb() to peer [[27676,0],0] through conduit 1
[rhc001:56772] [[27676,0],0] rml_ofi_send_buffer_transport to peer [[27676,0],0] at tag 15
[rhc001:56772] [[27676,0],0] rml_send_iovec_to_self at tag 15
[rhc001:56772] [[27676,0],0] rml_send_to_self ofi callback executing for tag 15
[rhc001:56772] [[27676,0],0] message received from [[27676,0],0] for tag 15
[rhc001:56772] [[27676,0],0] grpcomm:direct:xcast:recv: with 1191 bytes
[rhc002.cluster:145619] [[27676,0],1] message received  bytes from [[27676,0],0] for tag 1 called callback
[rhc001:56772] [[27676,0],0] grpcomm:direct:xcast updating daemon nidmap
[rhc001:56772] [[27676,0],0] rml:base:update:contact:info got uri 1813774336.0;ofiaddr:2,192.168.0.161,38002;ofiaddr:2,10.10.10.1,43914;ofiaddr:2,192.168.122.1,44631;ofiaddr:2,172.17.0.1,46068;ofiaddr:2,127.0.0.1,45785;1813774336.0;tcp://192.168.0.161,10.10.10.1,172.17.0.1:57019
[rhc001:56772] [[27676,0],0] rml:base:set_contact_info()
[rhc001:56772] [[27676,0],0]: OFI set_contact_info to uri 1813774336.0;ofiaddr:2,192.168.0.161,38002;ofiaddr:2,10.10.10.1,43914;ofiaddr:2,192.168.122.1,44631;ofiaddr:2,172.17.0.1,46068;ofiaddr:2,127.0.0.1,45785;1813774336.0;tcp://192.168.0.161,10.10.10.1,172.17.0.1:57019
[rhc001:56772] [[27676,0],0]:OFI set_contact_info peer [[27676,0],0] is me
[rhc001:56772] [[27676,0],0]:OFI set_contact_info - HNP process so proceeding to add to hashtable
[rhc001:56772] [[27676,0],0] OFI convert_to_sockaddr uri strings got -> family = 2, InternetAddr = 192.168.0.161, port = 38002  
[rhc001:56772] [[27676,0],0] OFI convert_to_sockaddr() port = 0x9472 decimal-38002, InternetAddr = 192.168.0.161  
[rhc001:56772] [[27676,0],0]: ofi peer address inserted for peer [[27676,0],0] 
[rhc001:56772] [[27676,0],0]: ofi sock address length = 16 
[rhc001:56772] [[27676,0],0] OFI set_name() port = 0x9472, InternetAddr = 192.168.0.161  
[rhc001:56772] [[27676,0],0] OFI end of set_contact_info()
[rhc001:56772] [[27676,0],0] rml:base:update:contact:info got uri 1813774336.1;tcp://10.10.10.2:57315
[rhc001:56772] [[27676,0],0] rml:base:set_contact_info()
[rhc001:56772] [[27676,0],0]: OFI set_contact_info to uri 1813774336.1;tcp://10.10.10.2:57315
[rhc001:56772] [[27676,0],0] OFI end of set_contact_info()
[rhc001:56772] [[27676,0],0] grpcomm:direct:send_relay sending relay msg of 1191 bytes to [[27676,0],1]
[rhc001:56772] [[27676,0],0] rml:base:send_buffer_nb() to peer [[27676,0],1] through conduit 1
[rhc001:56772] [[27676,0],0] rml_ofi_send_buffer_transport to peer [[27676,0],1] at tag 15
[rhc001:56772] [[27676,0],0] Message posted at grpcomm_direct.c:563
[rhc001:56772] [[27676,0],0] message received  bytes from [[27676,0],0] for tag 15 called callback
[rhc001:56772] [[27676,0],0] message tag 15 on released
[rhc001:56772] [[27676,0],0] send_msg_transport to peer [[27676,0],1] at tag 15
[rhc001:56772] [[27676,0],0] calling OPAL_MODEX_RECV_STRING 
[rhc001:56772] [[27676,0],0] calling OPAL_MODEX_RECV_STRING for DAEMON peer [[27676,0],1]
[rhc001:56772] [[27676,0],0] rml:ofi: Send failed to get peer OFI contact info 
[rhc001:56772] [[27676,0],0] message received from [[27676,0],0] for tag 1
[rhc001:56772] [[27676,0],0] message received  bytes from [[27676,0],0] for tag 1 called callback
[rhc001:56772] [[27676,0],0] message tag 1 on released
rhc001
rhc001
<hang>
```
Note that send-to-self worked fine. However, the relay message to 0,1 is never sent. I see it prepped here:
```
[rhc001:56772] [[27676,0],0] rml:base:send_buffer_nb() to peer [[27676,0],1] through conduit 1
[rhc001:56772] [[27676,0],0] rml_ofi_send_buffer_transport to peer [[27676,0],1] at tag 15
```
But that is the last time it appears. I used the "direct" routed module because I was seeing multiple repeat messages being sent out of the grpcomm relay - somehow, the routed system was getting messed up. I'll look more into it.

**Comment by rhc54** [comment]
@anandhis I fixed the problem of multiple messages in the coll conduit. I'm still stuck on the above problem - the first time a message is sent via the coll conduit over OFI, it hangs:
```
[rhc002.cluster:146375] [[22885,0],1] rml_ofi_send_buffer_transport to peer [[22885,0],0] at tag 10
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 50 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 51 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 6 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 28 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 59 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 15 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 33 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 31 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 5 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 3 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 21 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 47 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 48 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] posting recv
[rhc002.cluster:146375] [[22885,0],1] posting persistent recv on tag 1 for peer [[WILDCARD],WILDCARD]
[rhc002.cluster:146375] [[22885,0],1] send_msg_transport to peer [[22885,0],0] at tag 10
[rhc002.cluster:146375] [[22885,0],1] calling OPAL_MODEX_RECV_STRING 
[rhc002.cluster:146375] [[22885,0],1] calling OPAL_MODEX_RECV_STRING for DAEMON peer [[22885,0],0]
[rhc002.cluster:146375] [[22885,0],1] rml:ofi: OFI peer contact info got from hash table
[rhc002.cluster:146375] [[22885,0],1] peer [[22885,0],0] epnamelen is 16, port = 33432 (or) 0x8298, InternetAddr = 0x192.168.0.161  
[rhc002.cluster:146375] [[22885,0],1] OPAL_MODEX_RECV succeded, [[22885,0],0] peer ep name obtained. length=16
[rhc002.cluster:146375] [[22885,0],1] Completed copying all data into ofi_send_req->data_blob, total data - 3016 bytes
[rhc002.cluster:146375] [[22885,0],1] datalen_per_pkt = 1048540, ofi_send_req->length= 3016, total packets = 1
[rhc002.cluster:146375] [[22885,0],1] Packet 1 -> data_in_pkt= 3016, header_size= 36, pkt_size=3052
[rhc002.cluster:146375] [[22885,0],1] Copying header, data into packets completed
[rhc002.cluster:146375] [[22885,0],1] adding packet 1 to list done successful
[rhc002.cluster:146375] [[22885,0],1] Sending Pkt[1] of total 1 pkts for msgid:1 to peer [[22885,0],0] with tag 10

<hang for many seconds>

[rhc002.cluster:146375] [[22885,0],1] End of send_msg_transport. fi_send completed to peer [[22885,0],0] with tag 10

<hang forever>
```

**Comment by anandhis** [comment]
Ralph,
I don’t see this issue at my end…  below is with both conduits on OFI the tag10 is received by daemon-0.  It is not clear what in ur setup might be causing it ..

All your fixes are they in the main open-mpi/ompi tree ?

Thanks,
Anandhi


[knl-26:281127] [[20349,0],1] send_msg_transport to peer [[20349,0],0] at tag 10
[knl-26:281127] [[20349,0],1] calling OPAL_MODEX_RECV_STRING
[knl-26:281127] [[20349,0],1] calling OPAL_MODEX_RECV_STRING for DAEMON peer [[20349,0],0]
[knl-26:281127] [[20349,0],1] rml:ofi: OFI peer contact info got from hash table
[knl-26:281127] [[20349,0],1] peer [[20349,0],0] epnamelen is 16, port = 36746 (or) 0x8f8a, InternetAddr = 0x192.168.1.35
[knl-26:281127] [[20349,0],1] OPAL_MODEX_RECV succeded, [[20349,0],0] peer ep name obtained. length=16
[knl-26:281127] [[20349,0],1] Completed copying all data into ofi_send_req->data_blob, total data - 165634 bytes
[knl-26:281127] [[20349,0],1] datalen_per_pkt = 1048540, ofi_send_req->length= 165634, total packets = 1
[knl-26:281127] [[20349,0],1] Packet 1 -> data_in_pkt= 165634, header_size= 36, pkt_size=165670
[knl-26:281127] [[20349,0],1] Copying header, data into packets completed
[knl-26:281127] [[20349,0],1] adding packet 1 to list done successful
[knl-26:281127] [[20349,0],1] Sending Pkt[1] of total 1 pkts for msgid:1 to peer [[20349,0],0] with tag 10
[knl-26:281127] [[20349,0],1] End of send_msg_transport. fi_send completed to peer [[20349,0],0] with tag 10
[knl-25:282263] [[20349,0],0] cq_progress_handler called for OFI Provider id 1
[knl-25:282263] [[20349,0],0] orte_rml_ofi_progress called for OFI ofi_provid 1
[knl-25:282263] [[20349,0],0] cq read for OFI ofi_provid 1 - wc.flags = 2000000000000402
[knl-25:282263] [[20349,0],0] Received message on OFI provider id 1
[knl-25:282263] [[20349,0],0] orte_rml_ofi_recv_handler called
[knl-25:282263] [[20349,0],0] Received packet -> msg id = 1 wc->len = 165670, msglen = 165634
[knl-25:282263] [[20349,0],0] header info of received packet -> cur_pkt_num = 1, tot_pkts = 1
[knl-25:282263] [[20349,0],0] Posting Recv for msgid 1, from peer - [[20349,0],1] , Tag = 10
[knl-25:282263] [[20349,0],0] Message posted at ../../../../../orte/mca/rml/ofi/rml_ofi_send.c:234
[knl-26:281127] [[20349,0],1] cq_progress_handler called for OFI Provider id 1
[knl-26:281127] [[20349,0],1] orte_rml_ofi_progress called for OFI ofi_provid 1
[knl-25:282263] [[20349,0],0] Empty cq for OFI provider id 1,exiting from ofi_progress()
[knl-25:282263] [[20349,0],0] message received from [[20349,0],1] for tag 10
[knl-25:282263] [[20349,0],0] rml:base:set_contact_info()
[knl-25:282263] [[20349,0],0]: OFI set_contact_info to uri 1333592064.1;ofiaddr:2,192.168.1.36,43379;1333592064.1;tcp://192.168.1.36:36593

Thanks,
Anandhi

**Comment by rhc54** [comment]
Once I commit this, all my fixes will be in the ompi master. I suspect that the fact we are seeing different degrees of progress indicates there is a thread race condition, probably with your progress thread. Remember, your progress thread cannot access any structures or data that might be "touched" by code external to that thread. What we usually do is have the progress thread only deal with the internals of the library it is servicing (in this case, libfabric) - and then take the data it recvs and push it into a libevent event so it can be serviced in a thread-safe manner.

I haven't looked closely at your code, but is it possible your progress thread is violating these rules?

**Comment by anandhis** [comment]
Ralph,
Can u pls send/attach the full log, I am hoping it is something simpler than that.

Thanks,
Anandhi

**Pull request merged**
