### PR TITLE
v5.0.x: Romio v3.4.1 update

### PR DESCRIPTION
**Pull request by awlauria**
Fixes https://github.com/open-mpi/ompi/issues/8858

### CODE REVIEW

**Comment by awlauria** [comment]
I purposely left out the very last mailmap commit, will address in another PR.

**Comment by awlauria** [comment]
Added mail-map commits to make `make-dist` happy.

**Comment by awlauria** [comment]
bot:aws:retest

java failures..

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
:point_up: another java failure.

**Review by gpaulsen — APPROVED** [review]

**Review by gpaulsen — APPROVED** [review]
This could be slightly cleaner without 990371bb2f73da, but that commit is mostly removed/updated by another commit in this same PR, and only deals with the gitignore file, so not worth the CI testing.

**Pull request merged**
