### PR TITLE
mpi/neighbor_allgatherv: fix copy&paste error and add helpers

### LINKED ISSUE #2324: Neighborhood Collectives
@jsquyres I've found serious issues in the implementation of neighborhood collectives. These issues showed up after a memory allocation optimization I've implemented in mpi4py in commit [c2eaa292](https://bitbucket.org/mpi4py/mpi4py/commits/c2eaa292b2aa1d4bf809c91a1c19d988629f009a), which failed badly with Open MPI 2.0.1 in this [Bitbucket Pipelines](https://bitbucket.org/mpi4py/mpi4py/addon/pipelines/home#!/results/%7B8c67bd67-9cd6-4251-94b9-c96bf375c7a3%7D) build.

After checking the source code in ompi/v2.x, I found a major issue for the case of intracommunicators with a topology. The code simply do not check the topology to determine the number or sources and destinations, and use ``ompi_comm_size()`` instead. This leads to wrong checks and reads after end of arrays.

In mpi4py, I'm using the following [code](https://bitbucket.org/mpi4py/mpi4py/src/master/src/mpi4py/MPI/commimpl.pxi?fileviewer=file-view-default#commimpl.pxi-49) to determine the number of sources and destinations. This piece of code only handles intracommunicators, but could be extended to intercommunicators.

BTW, the wording of the MPI standard seems to require a topology for neighborhood collectives, although supporting intracomms and intercomms seems possible and the result should be equivalent to regular allgather and alltoall. Or maybe the right thing to do is to just error in case of intercomms or intracomms with no topology.

Am I missing something?

PS: MPICH seems to implement neighbor collectives just for Cartesian/graph topologies, the helper routine `MPIR_Topo_canon_nhb_count` is quite similar to what I'm using in mpi4py (though the MPICH one fails in case of no topology). @roblatham00 Any comments to you competitors :-) about this?

```
$[dalcinl@localhost mpich.git]$ git grep MPIR_Topo_canon_nhb_count
src/include/mpir_topo.h:int MPIR_Topo_canon_nhb_count(MPIR_Comm *comm_ptr, int *indegree, int *outdegree, int *weighted);
src/mpi/topo/inhb_allgather.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_allgatherv.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_alltoall.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_alltoallv.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_alltoallw.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/topoutil.c:#define FUNCNAME MPIR_Topo_canon_nhb_count
src/mpi/topo/topoutil.c:int MPIR_Topo_canon_nhb_count(MPIR_Comm *comm_ptr, int *indegree, int *outdegree, int *weighted)
```

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds a helper function to get the inbound and outbound
neighbor count and updates the neighbor_allgatherv bindings to use the
correct count when checking the input parameters.

Fixes #2324

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>
(cherry picked from commit 3c0e94afab03a27364114dcf3d429943d15cd4f4)
Signed-off-by: Nathan Hjelm <hjelmn@me.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7207417c89d8eb1d72808ee3680cfe6d

**Comment by hjelmn** [comment]
Something missing. Checking....

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fb0879fab8f87ce54af920375f5b8a60

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
NOTE: `btl/openib` wasn't tested as per https://github.com/open-mpi/ompi/issues/3890.

**Comment by jsquyres** [comment]
@ggouaillardet Can you review this PR?  Thanks.

**Comment by hppritcha** [comment]
@hjelmn do we need 9b702fb?

**Comment by hjelmn** [comment]
@hppritcha Yes. We should also include 9b702fb9bd6ccf744af8b8d92aa7c4c5d2f58f2f.

**Comment by jsquyres** [comment]
@ggouaillardet Good now?

**Pull request merged**
