### PR TITLE
CUDA: Enhance MPIX_Query_cuda_support() with runtime support check 

### PR DESCRIPTION
**Pull request by bureddy**
fixes: https://github.com/open-mpi/ompi/issues/7963 & https://github.com/openucx/ucx/issues/5471#

@jsquyres @bosilca @yosefe @Akshay-Venkatesh

### CODE REVIEW

**Comment by bureddy** [comment]
example test:
```
#include <stdio.h>
#include "mpi.h"

#include "mpi-ext.h" /* Needed for CUDA-aware check */

int main(int argc, char *argv[])
{

    MPI_Init(&argc, &argv);

    if (MPIX_Query_cuda_support()) {
        printf("This MPI library has CUDA-aware support.\n");
    } else {
        printf("This MPI library does not have CUDA-aware support.\n");
    }
    MPI_Finalize();

    return 0;
}
```

UCX with cuda
```
mpirun -np 2 --mca pml ucx   ./a.out
This MPI library has CUDA-aware support.
This MPI library has CUDA-aware support.
```

UCX w/o cuda TLs
```
mpirun -np 2 --mca pml ucx  -x UCX_TLS=rc ./a.out
This MPI library does not have CUDA-aware support.
This MPI library does not have CUDA-aware support.

```

**Comment by bosilca** [comment]
@bureddy what is happening is you do not specify "--mca pml ucx" ? The flag you added shows when/if the OMPI side of the CUDA infrastructure has been initialized, and you made the assumption that this means the underlying communication infrastructure is able to seamlessly handle CUDA buffers. Is this always the case ?

**Comment by leofang** [comment]
Thanks for quickly putting together a solution and for tagging me, @bureddy. Forgive my tons of questions as I am not very familiar with Open MPI's internal:
1. What's the expected outcome for the following matrix (looks like 8 combinations, but really only 6 is meaningful):
   - Open MPI built without and with `--with-cuda`
   - Open MPI built without and with `--with-ucx`
   - UCX built without and with `--with-cuda`
2. I was under the impression from openucx/ucx#5471 that we must call `ucp_context_query()` to ensure CUDA support, is this already done somewhere not included in this PR?
3. What happens when we call this prior to calling `MPI_Init()`? Does it fail like `MPI_Query_thread()` as it should?
4. Can we please not change the semantics of existing API and create a new function for this query? This would break backward compatibility...

Tagging MVAPICH2 people @chingking to comment, as they recently followed Open MPI and supported the same API in v2.3.4.

**Comment by bureddy** [comment]
> @bureddy what is happening is you do not specify "--mca pml ucx" ? The flag you added shows when/if the OMPI side of the CUDA infrastructure has been initialized, and you made the assumption that this means the underlying communication infrastructure is able to seamlessly handle CUDA buffers. Is this always the case ?

@bosilca added more test results above with  ob1 pml.   OMPI side runtime cuda Intra is initialized(`mca_common_cuda_stage_one_init()` called) only when underlying communication (UCX, TCP, smcuda) can handles the CUDA buffers.

**Comment by bureddy** [comment]
> Thanks for quickly putting together a solution and for tagging me, @bureddy. Forgive my tons of questions as I am not very familiar with Open MPI's internal:
> 
> 1. What's the expected outcome for the following matrix (looks like 8 combinations, but really only 6 is meaningful):
>    
>    * Open MPI built without and with `--with-cuda`
>    * Open MPI built without and with `--with-ucx`
>    * UCX built without and with `--with-cuda`
```

OMPI build   --with-cuda | ompi build --with-ucx | ucx with --with-cuda | MPIX_Query_cuda_support
-- ----------------------| ----------------------| -------------------- | ------------------------------
                    0    |          x            |             x        |      0
                    0    |         x             |             x        |      0
                   1     |         0             |           N/A        |      1 - with tcp,smcuda,    0 -  other wise
                   1     |        1              |            0         |      0
                   1     |        1              |            1         |      1

```

  
            
> 2. I was under the impression from [openucx/ucx#5471](https://github.com/openucx/ucx/issues/5471) that we must call `ucp_context_query()` to ensure CUDA support, is this already done somewhere not included in this PR?

Yes. with UCX, OMPI side runtime support is called only after `ucp_context_query()` and veryfied that it support cuda buffer

> 3. What happens when we call this prior to calling `MPI_Init()`? Does it fail like `MPI_Query_thread()` as it should?

Returns False because the runtime is not initialized.

> 4. Can we please not change the semantics of existing API and instead create a new function for this query? Otherwise, it would break backward compatibility...
> 

I'm not sure it is worth complicating the things given that it is not standard API and we sort of fixing the semantics in a correct way. 

> Tagging MVAPICH2 people @chingking to comment, as they recently followed Open MPI and supported the same API in v2.3.4.

**Comment by leofang** [comment]
@bureddy Thanks. Please confirm the below table, in particular the 4th and 7th row.
 ompi --with-cuda | ompi --with-ucx | ucx --with-cuda | output | comment
------------------ | ---------------- | ----------------- | -------| ---------
0 | 0 | 0 | 0 | (trivial, no one has cuda)
0 | 0 | 1 | 0 | (trivial, ucx has cuda but unused)
0 | 1 | 0 | 0 | (trivial, no one has cuda)
0 | 1 | 1 | 0 or 1 | 1: ucx; 0: otherwise
1 | 0 | 0 | 0 or 1 | 1: tcp, smcuda; 0: otherwise
1 | 0 | 1 |  0 or 1 | 1: tcp, smcuda; 0: otherwise
1 | 1 | 0 | 0 or 1 | 1: tcp, smcuda; 0: otherwise
1 | 1 | 1 | 1 | tcp, smcuda, ucx, etc

**Comment by leofang** [comment]
> I'm not sure it is worth complicating the things given that it is not standard API and we sort of fixing the semantics in a correct way.

Well, the whole CUDA thing is not in the MPI standard, but we do it anyway 🙂

Perhaps @dalcinl has a different opinion. I imagine it's good to separate the two pieces of information, quoting from https://github.com/open-mpi/ompi/issues/7963#issuecomment-663746350:
> 1. Is the library compiled with CUDA support.
> 2. Is CUDA support enabled "right now" (for some definition of "right now").

In addition to being able to maintaining the same semantics, it also allows us to hint the users. For example, it could be that Open MPI/UCX is built with CUDA support, but needs to be turned on or configured at launch time. If the runtime query returns 0 but the compile time query returns 1, at least we can raise with a nice message like "the MPI library is built with CUDA support but is not enabled, please consult the user manual of your MPI library".

**Comment by bureddy** [comment]
> 0	1	1	0 or 1

4th, it will be 0. because OMPI not compiled with CUDA.  you might get limited support UCX/CUDA for pt2pt.

**Comment by bureddy** [comment]
> > I'm not sure it is worth complicating the things given that it is not standard API and we sort of fixing the semantics in a correct way.
> 
> Well, the whole CUDA thing is not in the MPI standard, but we do it anyway 🙂
> 
> Perhaps @dalcinl has a different opinion. I imagine it's good to separate the two pieces of information, quoting from [#7963 (comment)](https://github.com/open-mpi/ompi/issues/7963#issuecomment-663746350):
> 
> > 1. Is the library compiled with CUDA support.
> > 2. Is CUDA support enabled "right now" (for some definition of "right now").
> 
> In addition to being able to maintaining the same semantics, it also allows us to hint the users. For example, it could be that Open MPI/UCX is built with CUDA support, but needs to be turned on or configured at launch time. If the runtime query returns 0 but the compile time query returns 1, at least we can raise with a nice message like "the MPI library is built with CUDA support but is not enabled, please consult the user manual of your MPI library".

is Open MPI/UCX is built with CUDA support, you don't need to turn on anything at run time to enable cuda support. its default.

**Comment by chingking** [comment]
@leofang - thanks for tagging me. Yes, MVAPICH2 currently follows the same logic as Open MPI. That is, `MPIX_Query_cuda_support` returns 1 as long as the runtime is built with CUDA support (even not enabled at runtime). MVAPICH2 will print other warning messages if the CUDA feature is not properly enabled at runtime.

We are happy to work together and have a unified standard for this support. I personally agree with the enhancement proposed here and we could print a warning message if users call `MPIX_Query_cuda_support` before `MPI_Init`.

Adding the MVAPICH2 core developer @harisubramoni.

**Comment by leofang** [comment]
Thank you @chingking for engaging in this discussion! Would be great to have input from you and @harisubramoni.

**Comment by bureddy** [comment]
> Hi @bureddy Sorry I dropped the ball.
> 
> > 4th, it will be 0. because OMPI not compiled with CUDA. you might get limited support UCX/CUDA for pt2pt.
> 
> OK I would like to drag in @jsquyres for confirming this, because my impression from Jeff was that for this case Open MPI could still be CUDA-aware. @bureddy Are you saying collectives won't work but point-to-point could? Interesting...

Yes.

> 
> > if Open MPI/UCX is built with CUDA support, you don't need to turn on anything at run time to enable cuda support. its default.
> 
> I don't think this is true. In fact this is one of the motivations for the whole thing. In Conda-Forge we built Open MPI with the `--with-cuda` flag, but we shut it down by default by setting `OMPI_MCA_opal_cuda_support=0`. In this case, the compile time flag is 1 but the runtime flag should be 0.

I mean, default is enabled. you can shut it down by OMPI_MCA_opal_cuda_support=0.  With this PR (compile & runtime check), it returns support 0 because you disabled it run time. 

> 
> Equivalently, (without building against ucx) we can launch MPI progresses via `--mca btl ^smcuda ...` I hope these two cases make it clear why we are bothered by the status quo and seeking for improvements 🙂

**Comment by leofang** [comment]
> Yes. it might change in the future when UCX handle all datatypes pack/unpack and collectives

Great, thanks @bureddy! It's good to know. I am looking forward to it. (Is there a time table for this? 😇)

> > I don't think this is true. In fact this is one of the motivations for the whole thing. In Conda-Forge we built Open MPI with the `--with-cuda` flag, but we shut it down by default by setting `OMPI_MCA_opal_cuda_support=0`. In this case, the compile time flag is 1 but the runtime flag should be 0.
> 
> I mean, default is enabled. you can shut it down by OMPI_MCA_opal_cuda_support=0. With this PR (compile & runtime check), it returns support 0 because you disabled it run time.

Right, I also expect with this PR we get 0 for this case. But this is precisely one of the use cases we want to differentiate among all possible scenarios that I mentioned above:
>> In addition to being able to maintaining the same semantics, it also allows us to hint the users. For example, it could be that Open MPI/UCX is built with CUDA support, but needs to be turned on or configured at launch time. If the runtime query returns 0 but the compile time query returns 1, at least we can raise with a nice message like "the MPI library is built with CUDA support but is not enabled, please consult the user manual of your MPI library".

by knowing compile time support 0 and runtime support 1, we can print out nice error messages to the users. 

Actually MVAPICH2 is already kinda doing this: when using MVAPICH2-GDR (cuda support is built) but `MV2_USE_CUDA` is not set, they print out a nice warning. I expect to build a guard similar to that with the inclusion of this PR.

**Comment by bureddy** [comment]
> > Yes. it might change in the future when UCX handle all datatypes pack/unpack and collectives
> 
> Great, thanks @bureddy! It's good to know. I am looking forward to it. (Is there a time table for this? 😇)

These topics are in very early stage of design phase. don't have timelines yet.

> 
> > > I don't think this is true. In fact this is one of the motivations for the whole thing. In Conda-Forge we built Open MPI with the `--with-cuda` flag, but we shut it down by default by setting `OMPI_MCA_opal_cuda_support=0`. In this case, the compile time flag is 1 but the runtime flag should be 0.
> > 
> > 
> > I mean, default is enabled. you can shut it down by OMPI_MCA_opal_cuda_support=0. With this PR (compile & runtime check), it returns support 0 because you disabled it run time.
> 
> Right, I also expect with this PR we get 0 for this case. But this is precisely one of the use cases we want to differentiate among all possible scenarios that I mentioned above:
> 
> > > In addition to being able to maintaining the same semantics, it also allows us to hint the users. For example, it could be that Open MPI/UCX is built with CUDA support, but needs to be turned on or configured at launch time. If the runtime query returns 0 but the compile time query returns 1, at least we can raise with a nice message like "the MPI library is built with CUDA support but is not enabled, please consult the user manual of your MPI library".
> 
> by knowing compile time support 1 and runtime support 0, we can print out nice error messages to the users.
> 
> Actually MVAPICH2 is already kinda doing this: when using MVAPICH2-GDR (cuda support is built) but `MV2_USE_CUDA` is not set, they print out a nice warning, so apparently they have a way to detect the support at runtime. I expect to build a guard similar to that with the inclusion of this PR.
> 
> **(UPDATE)**: I fixed a few typos.

**Comment by gpaulsen** [comment]
@bureddy ?

**Comment by bureddy** [comment]
@jsquyres updated documentation. can you check it?

**Comment by leofang** [comment]
Hi @bureddy @jsquyres Could you confirm this PR would enable us to differentiate the case that the support is built but not enabled at runtime? See our earlier discussion:

> > > I don't think this is true. In fact this is one of the motivations for the whole thing. In Conda-Forge we built Open MPI with the `--with-cuda` flag, but we shut it down by default by setting `OMPI_MCA_opal_cuda_support=0`. In this case, the compile time flag is 1 but the runtime flag should be 0.
> > 
> > 
> > I mean, default is enabled. you can shut it down by OMPI_MCA_opal_cuda_support=0. With this PR (compile & runtime check), it returns support 0 because you disabled it run time.
> 
> Right, I also expect with this PR we get 0 for this case. But this is precisely one of the use cases we want to differentiate among all possible scenarios that I mentioned above:
> 
> > > In addition to being able to maintaining the same semantics, it also allows us to hint the users. For example, it could be that Open MPI/UCX is built with CUDA support, but needs to be turned on or configured at launch time. If the runtime query returns 0 but the compile time query returns 1, at least we can raise with a nice message like "the MPI library is built with CUDA support but is not enabled, please consult the user manual of your MPI library".
> 
> by knowing compile time support 1 and runtime support 0, we can print out nice error messages to the users.

**Comment by leofang** [comment]
@chingking @harisubramoni (MVAPICH2) @dalcinl (mpi4py) @pavanbalaji (MPICH): Any chance you could take a look at this PR? The runtime query for CUDA awareness in Open MPI is being done here. Thanks 🙏

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
@bureddy @Akshay-Venkatesh Can you guys answer @leofang's question from 2 Sep?

**Comment by awlauria** [comment]
@bureddy @Akshay-Venkatesh @leofang's re-ping. There is a v5.0.x branch now, so please cherry-pick there if wanted once this is merged to master. @gpaulsen

**Review by janjust — APPROVED** [review]

**Comment by janjust** [comment]
@awlauria ready to merge

**Comment by awlauria** [comment]
Thanks @janjust .

Unfortunately I don't think we can merge until that checker runs. @bureddy can you rebase and force push to retrigger it? I don't think there's a manual way to trigger that commit checker.

**Comment by awlauria** [comment]
Merging for @janjust

**Pull request merged**
