### PR TITLE
Topic/atomic fetch

### PR DESCRIPTION
**Pull request by bosilca**
Replace the current &lt;op&gt;_and_fetch type of atomic operations with fetch_and&lt;op&gt; (in other words returning the old value instead of the new one).

This patch is based on the [devel list discussion](http://www.open-mpi.org/community/lists/devel/2014/07/15327.php). Unfortunately, this patch is not complete. This PR is just a placeholder where volunteers can push their changes. There is not much left over: all __asm__ operations are converted, but someone needs to take a look at the generated asm code.

@goodell and @hjelmn please review.

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca Is this PR dead?

**Comment by hppritcha** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/615/


**Build Log**
*last 50 lines*

 ```
GitHub pull request #293 of commit eb995a292712b95e1fef70a7fbccc00023702bab, has merge conflicts.
Setting status of eb995a292712b95e1fef70a7fbccc00023702bab to PENDING with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/615/ and message: 'Build started, sha1 is original commit.'
Using conext: Mellanox
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/open-mpi/ompi
 > /usr/bin/git init /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2 # timeout=60
Fetching upstream changes from https://github.com/open-mpi/ompi
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git3800089339927181609.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
 > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
Pruning obsolete local branches
Fetching upstream changes from https://github.com/open-mpi/ompi
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git3624234005344318655.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/pull/*:refs/remotes/origin/pr/* --prune # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git rev-parse eb995a292712b95e1fef70a7fbccc00023702bab^{commit} # timeout=60
Merging Revision eb995a292712b95e1fef70a7fbccc00023702bab (detached) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='default', fastForwardMode='--ff'}
 > /usr/bin/git rev-parse origin/master^{commit} # timeout=60
 > /usr/bin/git config core.sparsecheckout # timeout=60
 > /usr/bin/git checkout -f origin/master # timeout=20
 > /usr/bin/git merge --ff eb995a292712b95e1fef70a7fbccc00023702bab # timeout=60
 > /usr/bin/git config core.sparsecheckout # timeout=60
 > /usr/bin/git checkout -f eb995a292712b95e1fef70a7fbccc00023702bab # timeout=20
ERROR: Branch not suitable for integration as it does not merge cleanly: Could not merge AnyObjectId[eb995a292712b95e1fef70a7fbccc00023702bab]
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/615/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/eb995a292712b95e1fef70a7fbccc00023702bab
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of eb995a292712b95e1fef70a7fbccc00023702bab to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/615/ and message: 'Build finished.'
Using conext: Mellanox
```

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/34/

**Build Log**
*last 20 lines*

 ```
[...truncated 9847 lines...]
Making all in mca/notifier
make[3]: Entering directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/orte/mca/notifier'
  CC       base/notifier_base_frame.lo
  CC       base/notifier_base_select.lo
  CC       base/notifier_base_fns.lo
../../../../../orte/mca/notifier/base/notifier_base_fns.c: In function 'orte_notifier_base_report':
../../../../../orte/mca/notifier/base/notifier_base_fns.c:118: error: 'ORTE_JOB_NOTIFICATIONS' undeclared (first use in this function)
../../../../../orte/mca/notifier/base/notifier_base_fns.c:118: error: (Each undeclared identifier is reported only once
../../../../../orte/mca/notifier/base/notifier_base_fns.c:118: error: for each function it appears in.)
make[3]: *** [base/notifier_base_fns.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/orte/mca/notifier'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/orte'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub'
make: *** [distcheck] Error 1
Build step 'Execute shell' marked build as failure
Setting status of eb995a292712b95e1fef70a7fbccc00023702bab to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/34/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/124/

**Build Log**
*last 20 lines*

 ```
[...truncated 4979 lines...]
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte/mca/iof'
Making all in mca/notifier
make[2]: Entering directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte/mca/notifier'
  CC       base/notifier_base_frame.lo
  CC       base/notifier_base_fns.lo
  CC       base/notifier_base_select.lo
base/notifier_base_fns.c: In function 'orte_notifier_base_report':
base/notifier_base_fns.c:118:54: error: 'ORTE_JOB_NOTIFICATIONS' undeclared (first use in this function)
     if (!orte_get_attribute(&req->jdata->attributes, ORTE_JOB_NOTIFICATIONS, (void**)modules, OPAL_STRING)) {
                                                      ^
base/notifier_base_fns.c:118:54: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [base/notifier_base_fns.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte/mca/notifier'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
Setting status of eb995a292712b95e1fef70a7fbccc00023702bab to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/124/ and message: Build finished.
```

Test FAILed.

**Pull request closed without merging**
