### PR TITLE
hwloc2: advance hwloc git submodule

### LINKED ISSUE #7316: HWLOC gitignore needs updating
Now that we are using a submodule for the embedded hwloc, I'm seeing the following after building OMPI:
```shell
$ git st
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   opal/mca/hwloc/hwloc2/hwloc (untracked content)
```
When I look into the hwloc directory, I find:
```shell
$ git st
HEAD detached at f1a2e22a
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	config/ltmain.sh.orig

nothing added to commit but untracked files present (use "git add" to track)
```
Someone needs to add that file to HWLOC's .gitignore

### PR DESCRIPTION
**Pull request by jsquyres**
Advance to hwloc-2.1.0rc2-33-g38433c0f, which includes a .gitignore
update that we want here in Open MPI.

***Be warned:*** this is actually 33 commits beyond the hwloc v2.1.0 tag.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Fixes #7316.
FYI @bgoglin

### CODE REVIEW

**Comment by jsquyres** [comment]
bot:lanl:retest

**Comment by jsquyres** [comment]
@bwbarrett @hppritcha Do you know why Jenkins is failing to check out hwloc on the Cray?

This PR is updating the hwloc submodule to https://github.com/open-mpi/hwloc/commit/38433c0f5fae0b761bd20e7b928c77f3ff2e76dc, which quite definitely exists upstream (obviously, since I linked to its github URL for that commit).

It has failed to check out on the Cray twice now (e.g., https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/5869/console), but I can see that Mellanox's CI has already successfully checked it out (e.g., https://dev.azure.com/mlnx-swx/mellanox-ompi/_build/results?buildId=207&view=logs&j=05ee1795-5e75-566a-c260-61630d0851a3&t=5e5b9f59-57ad-57f3-3f39-3adb82f7a3c6).  IBM's CIs have finished, so they assumedly checked out that hwloc commit, too.

🤷‍♂

**Comment by rhc54** [comment]
Probably the switch to "shallow" checkout...

**Comment by bwbarrett** [comment]
bot:aws:retest

**Comment by hppritcha** [comment]
@jsquyres do we need a certain git version or higher to support this?

**Comment by jsquyres** [comment]
I think Brian said the issue was the shallow copy -- not that it was dependent upon a certain version of git.

I don't know offhand the version where submodules were introduced, but I think they've been around for quite a while.

**Comment by bgoglin** [comment]
By the way, since you cannot cherry-pick hwloc fixes in the OMPI report anymore, feel free to request a 2.1-ompi branch upstream where we could cherry-pick exactly what you want for your submodule instead of taking all pending fixes in the official hwloc 2.1 branch.

**Comment by jsquyres** [comment]
> By the way, since you cannot cherry-pick hwloc fixes in the OMPI report anymore, feel free to request a 2.1-ompi branch upstream where we could cherry-pick exactly what you want for your submodule instead of taking all pending fixes in the official hwloc 2.1 branch.

Let's hope it doesn't come to this.  Because then it means we will have drafted @bgoglin as an unofficial Open MPI release manager.  And I sure he doesn't need the additional workload.  😉

**Comment by bwbarrett** [comment]
yes, issue was with the shallow copies, not the version of git.  The issue was that the way Jenkins checks out (cloning a bare repo, then doing a checkout) means that it grabs the 10 latest commits in the hwloc repo.  Which does not include the release commit that we wanted.  So we had to drop the shallow copies, because I don't have time to fight with Jenkins on doing the right clone.

**Pull request merged**
