### PR TITLE
osc/base: Detect unsupported data types and abort

### PR DESCRIPTION
**Pull request by jjhursey**
Using MPI_MINLOC or MPI_MAXLOC with the following data types
leads to data corruption:
 * MPI_DOUBLE_INT
 * MPI_LONG_INT
 * MPI_SHORT_INT
 * MPI_LONG_DOUBLE_INT

Detect this print a error message and abort.
This workaround should be removed once the following issue is resolved:
 * https://github.com/open-mpi/ompi/issues/1666

Signed-off-by: Joshua Hursey <jhursey@us.ibm.com>
(cherry picked from commit 94f92f6b49212545355123d711abc91af9647d8e)
Signed-off-by: Joshua Hursey <jhursey@us.ibm.com>

### CODE REVIEW

**Comment by jjhursey** [comment]
Refs PR #2832

**Comment by hjelmn** [comment]
These datatypes and ops need to die :-/.

**Comment by nysal** [comment]
@jjhursey I think this patch will only work for osc/pt2pt. osc/rdma will probably need a similar check in ompi_osc_rdma_rget_accumulate_internal()

**Comment by hjelmn** [comment]
osc/pt2pt *should* be trivial to update to support for minloc/maxloc. It is a slight modification to ```osc_pt2pt_accumulate_buffer```. The hetero #ifdef needs to be removed  and the if needs to check if the datatype is non-contiguous. I have no interest in making either operation work with osc/rdma (outside just treating MPI_SHORT_INT as contiguous) so I welcome a check that makes it error.

**Comment by jjhursey** [comment]
@nysal I updated the PR to include a commit for `ompi_osc_rdma_rget_accumulate_internal()` - can you and/or @hjelmn confirm that this is the correct/best placement for that logic in the `osc/rdma` component?

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
