### PR TITLE
configury + btl/openib: fix a typo

### PR DESCRIPTION
**Pull request by ggouaillardet**
test for existence of struct ibv_exp_device_attr.exp_atomic_cap.
That was previously mistyped struct ibv_exp_device_attr.ext_atomic_cap

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/6459b7a8aeef3e88d5d465d88ede70f2

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/41724f12308794cd7862b4e1eb287eb4

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/20363aff32be038842edc2db2c318112

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/269ae99da24897cb2c848c7c4049a84c

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
@hjelmn can you please double check this PR ?

**Comment by hjelmn** [comment]
@ggouaillardet Looks good. Will merge. Please PR the relevant part to 2.0.1 (the typo).

**Pull request merged**
