### PR TITLE
configury: abort when builtin atomics cannot be built and configure'd…

### PR DESCRIPTION
**Pull request by ggouaillardet**
… with --enable-builtin-atomics

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/745b7c7dad9eb0a931caa3c93d9781ec

**Comment by ggouaillardet** [comment]
@hjelmn can you please review this ?

since open-mpi/ompi@f33bbfd381015be1f3adf44bb7d878d91dc4a33b ```configure``` does not abort any more if ```--enable-builtin-atomic``` is used but builtin atomics cannot be built.
my guess is this is not the intended behavior, but i'd like to double check it before i commit.

fwiw, you can simply reproduce this with
```configure CFLAGS='-m32 -march=i386' CXXFLAGS='-m32 -march=i386'```

**Comment by jsquyres** [comment]
@ggouaillardet @hjelmn Is this PR now moot (with all the recent discussion about the ASM)?

**Comment by bwbarrett** [comment]
@jsquyres I don't think so, just different.  There's still builtin atomics vs. inline assembly to worry about.

@ggouaillardet, please don't add release branch labels to PRs destined for master (see https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests)

**Comment by ggouaillardet** [comment]
@jsquyres
i agree with @bwbarrett, this PR is unrelated to the recent ASM changes and is hence not moot.

**Comment by jsquyres** [comment]
@bwbarrett @ggouaillardet Got it.

**Comment by hppritcha** [comment]
@hjelmn please review, I'd like to get this in the rc1

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by rhc54** [comment]
@jjhursey Given that this PR introduces the "fail if sync builtin atomics fails", I don't think it can pass the PGI compiler test until we actually fix those atomics - yes?

**Comment by jjhursey** [comment]
@rhc54 That's what I want to check with this CI recheck (the previous test was over 2 weeks ago, so the log was cleared). It looks like it's passing fine so far. Just wanted to keep an eye on it. If PGI CI passes then we are good to continue with this PR.

**Comment by rhc54** [comment]
ok, then we have to figure out what is missing over in pmix as it fails this test, yet appears (to my scan) to have identical atomics now.

**Comment by hjelmn** [comment]
Why does this have a v2.1.2 milestone? We do not enable builtin atomics by default in v2.1.2.

**Comment by hjelmn** [comment]
Also not relevant for v3.0.0 anymore. builtins are not enabled by there by default either.

**Comment by rhc54** [comment]
Maybe we need to review the entire atomics thing at next week's meeting. I confess I'm getting confused and a little frustrated at the way the atomic support keeps jerking around. It doesn't seem that there is any coherent understanding right now as to what is actually being built, when it is to be built, and why.

**Comment by hjelmn** [comment]
v2.0.x, v2.1.x, and v3.0.x have no change from past behavior. That is we use inline asm unless ```--enable-builtin-atomics=yes``` is specified. On master we try builtins by default then try the inline asm. I do not want it failing if we have inline asm but no builtins unless the configure line says ```--enable-builtin-atomics=yes```.

**Comment by hjelmn** [comment]
I should also point out it is likely v3.1.x will use inline asm by default. The plan is to use C11 atomics for v4.0.x unless we hit a roadblock on requiring C11.

**Comment by hjelmn** [comment]
@ggouaillardet We need to figure out exactly what we want to be the behavior here. Looking at this I think it will be ok. Should have it figured out soon.

**Pull request merged**
