### PR TITLE
MPI-3.0+ Cleanup

### PR DESCRIPTION
**Pull request by hjelmn**
This PR cleans out all the functionality removed from MPI-3.0 in **2012**. This includes a number of C and fortran functions and the entirety of the C++ bindings. The PR is a WIP intended to start the discussion about cleaning up code that is no longer supported by the standard. The intent is to bring this into master targeting the Open MPI 4.0 release.

To finish the cleanup a number of internal components needed to be modified. These components used the removed functions. The cleanup is mostly straightforward but the romio changes need to be looked at since it is likely I updated some of them incorrectly. @roblatham00, @bosilca, @jsquyres Please take a look.

### CODE REVIEW

**Comment by hjelmn** [comment]
@edgargabriel I will probably break out the ompio update into another PR. Seems like something that should go in regardless of the removal of MPI_Address.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4e71c13f31addf3582580023322d025e

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/64e841ea11c9714a1e1e703698460be4

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3c408ea3ea770e61c8fc18df08c92d48

**Comment by edgargabriel** [comment]
@hjelmn sounds good to me.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9ab2c862f46a7721d951a0734202fa6d

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8ecd404b6e50c4423909bf6fdd0ca5fe

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fc34e75e3aab9f933005e92ecce695b8

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/62454c918af91d9c993ffe1e2cab8b29

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3dd7b71987dc550aade962b170ae2870

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ba03b56cc8bc2bc68bd03c8f6274ff81

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/70cbb2c8f3ceb8f7c1a189f030660d41

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/db3051addc70acec714a0dfa62b62812

**Comment by hjelmn** [comment]
:bot:retest:ompi

**Comment by hjelmn** [comment]
:bot:retest:mellanox

**Comment by hjelmn** [comment]
Kinda funny. This PR deletes ~ 1% of all the LOC in the project. -12000 lines.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5c6312268f03a40159e1c6dc621a384f

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4f88a6e41b8ad4f886c97948ba195908

**Comment by hjelmn** [comment]
Failure was yet another place that needs to be touched when modifying fortran datatypes! Fixed.

**Comment by awlauria** [comment]
It looks like this PR removed the cxx bindings (done in another pr), plus a bunch of other stuff. Per the 5.0 feature list - it looks like that "other stuff" was deferred to 6.0. Is there anything here still wanted for 5.0?

**Comment by jsquyres** [comment]
This is definitely 6.0/beyond.

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1d7a2d36b6c801a751ec3538fc8cab67

**Comment by hppritcha** [comment]
closing as too old

**Pull request closed without merging**
