### PR TITLE
odls/base: use the full app name when using an orte fork agent

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 could you please review this ?

if i ```mpirun --mca orte_fork_agent $HOME/wrapper.sh /foo/bar```, then orted ends up fork&exec'ing
```$HOME/wrapper.sh bar```
we miss the dirname ```/foo``` and it is not even available via some environment variable.

with this commit, orted fork&exec ```$HOME/wrapper.sh /foo/bar``` which is what i expect.

this commit is very minimal, but you might want to do things differently.
for example, at this stage, ```app->argv[0]``` has already been set to the basename, it could have been the full name, and then be replaced by its basename at the very end, right before the real fork&exec

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 690 errors for all

* Coverity found 7 errors for oshmem

* Coverity found 2 errors for fca

* Coverity found 1 errors for ucx
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr//2055/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rhc54** [comment]
Mellanox Jenkins error is unrelated: :+1:

**Pull request merged**
