### PR TITLE
Update PMIx/PRRTE pointers

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e0b5df6b0617c425c8c302e94d633af5

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/bd997c4d1c96c6bdebd547f2f356f2f3

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d0f977d297d62f3b91c836adb20a0cb6

**Comment by rhc54** [comment]
Hmmm...OMPI master is up-to-date, so this PR is totally stale

**Pull request closed without merging**
