### PR TITLE
fix for -am -tune options issue came from PR 520

### PR DESCRIPTION
**Pull request by elenash**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 910 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_443/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_443/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_443/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/443/
Test PASSed.

**Comment by miked-mellanox** [comment]
looks good

**Comment by hjelmn** [comment]
Is this also needed for 1.8.5?

**Comment by elenash** [comment]
No, 1.8.5 doesn't have -tune option. The problem occured just when both -amca and -tune are specified.

**Pull request merged**
