### PR TITLE
odls: fix handling of the orte fork agent

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 can you please review this ?
backport is only needed for the ```v3.x``` branch

you can simply evidence the issue with
```
strace -e execve -f mpirun --mca orte_fork_agent /bin/false -np 1 /bin/true
```

currently,
```
execve("/bin/true", ["/bin/false", "/bin/true"]
```
expected behavior is
```
execve("/bin/false", ["/bin/false", "/bin/true"]
```

**Comment by rhc54** [comment]
It's already in #3462

**Comment by ggouaillardet** [comment]
@rhc54 sorry for being late on that one.
this PR is for the ```master``` branch, and it has not been merged yet.
i'd like to review it before i merge it into master.

#3462 is for the ```v3.x``` branch, and so far, i did not see that commit was included in it

**Comment by rhc54** [comment]
FWIW: it looks ok to me

**Pull request merged**
