### PR TITLE
Openib dynamic add proc race conditions

### PR DESCRIPTION
**Pull request by artpol84**
@hjelmn This is relatively big PR so I'm postin it now to make you aware about it and to let you start the review during your daytime.
As for now I can say that this fixes problems I was observing with some of the OSU collectives tests. I've launched MTT to do more general evaluation. I will post the results when I'll get them.
Also this PR is not a final solution. If you'll be OK with it I will provide more fixes on top of it.

### CODE REVIEW

**Comment by artpol84** [comment]
:bot:retest

**Comment by artpol84** [comment]
aside the problems that are fixed with this changeset I'm seeing race conditions here: https://github.com/open-mpi/ompi/blob/master/opal/mca/btl/openib/btl_openib.c#L1021. Although `opal_pointer_array_add()` has lock-protection this protection is only enabled if OPAL thread support is enabled.
I've configured my OMPI by default with regad to this aspect. And I see that udcm is running in the service thread causing those race conditions.

**Comment by artpol84** [comment]
Update: MTT shows noticeable improvement: 2 errors after fix versus 27 before.

**Comment by hjelmn** [comment]
Why not also make the locks in add_procs not dependent on opal_using_threads(). The function is not in the critical path.

**Comment by hjelmn** [comment]
@hppritcha Will probably want this in 2.0.0 final. Should get this merged into master today or tomorrow.

**Comment by artpol84** [comment]
@hjelmn Not sure I understand what you're saying. Can you explain?

2015-12-21 22:25 GMT+06:00 Nathan Hjelm <notifications@github.com>:

> Why not also make the locks in add_procs not dependent on
> opal_using_threads(). The function is not in the critical path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/ompi/pull/1248#issuecomment-166349746>.
>



-- 
С Уважением, Поляков Артем Юрьевич
Best regards, Artem Y. Polyakov

**Comment by artpol84** [comment]
@hjelmn please, note that I've add one additional commit at the top of previous ones:
https://github.com/artpol84/ompi/commit/b39b1155a3ca254bac18486cbb740eb2710ef20d

this fixes problems with `opal_pointer_array_add()` I previously mentioned.

**Comment by hjelmn** [comment]
Looks good to me.

**Comment by artpol84** [comment]
@hjelmn ok, here is one more fix that I'd like to submit in this PR.
Tomorrow I'll work on more precise way to account the number of processes. Right now it is possible that one process will be accounted twice. This may only happen in race condition case so shouldn't affect much. But this certainly has to be fixed.
But I suggest to review this as part of the separate PR when this one will be merged.
This change is not yet tested, I'll check it, run MTT and report back in few hours.
This final fix is small and unlikely to cause problems.

**Comment by artpol84** [comment]
@hppritcha when does 2.0.0 scheduled?

**Comment by artpol84** [comment]
@hjelmn All my checks are passed. Please, feel free to merge it.

**Comment by jladd-mlnx** [comment]
Well done, Artem!

**Comment by hppritcha** [comment]
@artpol84 can't speak for @jsquyres but we'll have an rc2 likely in second week of 1/16.

**Comment by hppritcha** [comment]
@artpol84 please open a PR on v2.x for this.

**Comment by artpol84** [comment]
Are we ok to merge this?

среда, 23 декабря 2015 г. пользователь Howard Pritchard написал:

> @artpol84 <https://github.com/artpol84> please open a PR on v2.x for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/ompi/pull/1248#issuecomment-166707510>.
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by hjelmn** [comment]
Yup. Ok to merge.

**Comment by artpol84** [comment]
Cool, I'll PR to 2.x.

**Pull request merged**
