### PR TITLE
mca/base: fix source file name bug for synonyms

### PR DESCRIPTION
**Pull request by hjelmn**
This commit fixes synonyms so the source file is correctly printed out
by ompi_info. This commit also adds support for printing out the line
number where the variable is set.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca This fixes the issue you raised in http://www.open-mpi.org/community/lists/devel/2015/05/17393.php

**Comment by hjelmn** [comment]
Example:

```MCA mpi: parameter "mpi_preconnect_all" (current value: "true", data source: file (/Users/hjelmn/.openmpi/mca-params.conf:1), level: 9 dev/all, type: bool, deprecated, synonym of: mpi_preconnect_mpi)```

**Comment by bosilca** [comment]
Excellent,thanks for the quick fix.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/519/

**Build Log**
*last 50 lines*

 ```
[...truncated 15954 lines...]
  CC       predefined_gap_test.o
  CC       predefined_pad_test.o
  CC       dlopen_test.o
  CCLD     dlopen_test
  CCLD     predefined_pad_test
  CCLD     predefined_gap_test
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/debuggers'
make  check-TESTS
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/debuggers'
make[4]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/debuggers'
PASS: predefined_gap_test
PASS: predefined_pad_test
../../config/test-driver: line 107:  5382 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: dlopen_test
============================================================================
Testsuite summary for Open MPI gitclone
============================================================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ompi/debuggers/test-suite.log
Please report to http://www.open-mpi.org/community/help/
============================================================================
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/debuggers'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/debuggers'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/debuggers'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi'
make: *** [check-recursive] Error 1
+ exit 12
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/79659e27626b579dbc0c1b8dba220e779a8965a1
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 8969db5eff0493699e7d4dd5f5971ea1834c8bb5 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/519/ and message: Build finished.
```

Test FAILed.

**Comment by hjelmn** [comment]
@rolfv There were some problems with cuda support MCA variables. The second commit in this PR fixes the issues. Please take a look and let me know what you think.

**Comment by mellanox-github** [comment]
* Coverity found 910 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_520/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_520/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_520/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/520/
Test PASSed.

**Pull request merged**
