### PR TITLE
Update embedded libfabric to 1.0rc6

### PR DESCRIPTION
**Pull request by jsquyres**
@yburette Can you update the OFI MTL?  There's a minor compile error -- it may be trivial to fix.

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 905 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_486/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_486/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_486/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/486/
Test PASSed.

**Comment by yburette** [comment]
I believe this has been fixed in 1be185ed8791f258c8d6df9e110c3a9262969de4.
Please let me know if it still doesn't work.

**Comment by jsquyres** [comment]
@yburette Right you are -- thanks.

**Pull request merged**
