### PR TITLE
ompi: Avoid unnecessary PMIx lookups when adding procs (step 2).

### PR DESCRIPTION
**Pull request by artpol84**
Follow-up for 717f3fef62b193845e9add5aaaae3543c2f2ebfb.

Signed-off-by: Artem Polyakov <artpol84@gmail.com>
(cherry picked from commit 1f7a3a2d540ac85b2549ea2d94df016c1cbc4ac2)

### CODE REVIEW

**Comment by artpol84** [comment]
@hjelmn thank you!
Can you also check #3193 ?

**Comment by hppritcha** [comment]
@rhc54 could you review?  thanks.

**Comment by bwbarrett** [comment]
Why is this a 3.0 requirement?  Is there a bug fixed by this patch or is it just nice to have?

**Comment by rhc54** [comment]
helps with launch performance, but not a correctness bug - i.e., nothing is "broken"

**Comment by bwbarrett** [comment]
Punting to the v3.1.0 release (ie, the October release)

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Pull request merged**
