### PR TITLE
OSC: set UCX module used by default

### PR DESCRIPTION
**Pull request by hoopoepg**
- OSC/UCX module set priority to 200 to be used by default

Signed-off-by: Sergey Oblomov <sergeyo@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
@jladd-mlnx @xinzhao3 pls bless

**Comment by yosefe** [comment]
We reduced the priority of OSC/UCX because of missing functionality (emulation layer) in UCX.
Now that is available in UCX master (for v1.5 release) so we want to raise the priority

**Comment by rhc54** [comment]
Given that it won't be the correct priority for those with earlier versions of UCX, I'd suggest having a configure test for UCX version and then set the priority accordingly.

**Comment by hoopoepg** [comment]
@yosefe what do you think? add version check?

**Comment by yosefe** [comment]
let's add runtime version check

**Comment by hoopoepg** [comment]
bot:retest

**Comment by hoopoepg** [comment]
bot:retest

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Comment by yosefe** [comment]
@hoopoepg let's port to v4.0.x too

**Comment by hjelmn** [comment]
Umm, ok. You should have asked for my review before increasing the priority above 101. osc/rdma is still faster in most cases and is only enabled if btl/uct is explicitly enabled.

**Comment by yosefe** [comment]
@hjelmn @jsquyres would 60 be a good priority for ucx?

**Comment by hjelmn** [comment]
Yes, that would be better. Just need it higher than osc/pt2pt. If/when btl/uct becomes available by default we need to revisit and figure out how to handle the relative priorities of the osc/rdma and osc/ucx. That will likely be in the Open MPI v5.0.0 timeframe. I still need to make sure when btl/uct is enabled but not used it doesn't slow any other ucx components down or use up any resources.

**Pull request merged**
