### PR TITLE
Resolve a race condition for setting working directory

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by hppritcha** [comment]
looks like a variable wasn't declared and the code can't be compiled.

**Comment by hppritcha** [comment]
@jsquyres can you take a look at this PR?  Thanks

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/

**Comment by jjhursey** [comment]
bot:ibm:xl:retest

**Pull request merged**
