### PR TITLE
mtl: remove MXM MTL

### PR DESCRIPTION
**Pull request by bwbarrett**
Remove the MXM MTL, which has been deprecated in preference for
the Yalla PML.  This was discussed at the last developers meeting
and somehow I ended up with the action item to do the removal.

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
@jladd-mlnx there was some confusion in the release manager call today about whether Mellanox wanted to remove just the MXM MTL or all the MXM support.

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 The Mellanox CI is running some tests with `-mca pml cm -mca mtl mxm`, which will obviously fail (on master and future branches) once this PR is merged.

Can it be updated to skip those tests when the MXM MTL is not present?

**Comment by jsquyres** [comment]
@jladd-mlnx The following text about MXM is in the top-level README -- do you want to amend it by saying something about how Mellanox is favoring UCX these days / yadda yadda yadda?

```
- MXM is the Mellanox Messaging Accelerator library utilizing a full
  range of IB transports to provide the following messaging services
  to the upper level MPI/OpenSHMEM libraries:

  - Usage of all available IB transports
  - Native RDMA support
  - Progress thread
  - Shared memory communication
  - Hardware-assisted reliability
```

I also note that there's `oshmem/mca/atomic/mxm` and `oshmem/mca/spml/ikrit`.  Per your above note, should both of those be kept until MXM is removed from HPC-X?   Speaking of which, is there a public timeline for when MXM will be removed from HPC-X?

Thanks!

**Comment by artpol84** [comment]
@karasevb, please resolve Jenkins failures.

**Comment by jladd-mlnx** [comment]
No public date yet. Ideally, it would happen for our end of October release this year.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Pull request merged**
