### PR TITLE
opal: deprecate dead code 

### PR DESCRIPTION
**Pull request by wenduwan**
Manually apply https://github.com/openpmix/openpmix/commit/ae62cdf67b19e80fd821420816f09bf0a56a8166

### CODE REVIEW

**Comment by jsquyres** [comment]
> @jsquyres Good to go?

The v5.0.x RMs will merge this when they are ready (they usually merge v5.0.x PRs later in the week).

**Comment by wenduwan** [comment]
Hmmm I thought we first merge to main then I can backport to v5.0.x

**Comment by jsquyres** [comment]
Ok, the change looks good.  Can we wait and add one thing to this PR?

We're adding some language in the v4.1.x NEWS file about this whole situation, and how Open MPI users really aren't affected.  It might be good to put a commit with a `docs/` change here in this PR with similar language.  I.e., yes, we're making the change, but really, it doesn't matter, and users who are concerned about CVE-whatever do not need to be.

**Comment by wenduwan** [comment]
Sure sounds reasonable to me. I will add another commit later.

**Review by bwbarrett — CHANGES_REQUESTED** [review]
This is all dead code.  Just remove opal_pty.c (or `ptys_open()` if you want to change something here.  However, I'm not actually convinced there's any harm in this, given the permissions around /dev already.

**Comment by wenduwan** [comment]
> This is all dead code. Just remove opal_pty.c (or ptys_open() if you want to change something here. However, I'm not actually convinced there's any harm in this, given the permissions around /dev already.

@bwbarrett Thank you and done.

@jsquyres Given that we have removed the code entirely. Do you still think we need to explain our motivation in NEWS?

**Review by jsquyres — APPROVED** [review]
Nope, I don't think we need anything in NEWS.

**Comment by jsquyres** [comment]
@wenduwan You'll cherry pick to v5.0.x?

**Pull request merged**
