### PR TITLE
master: Bull 2020 update of coll/han

### PR DESCRIPTION
**Pull request by EmmanuelBRELLE**
This completes and fixes current code for coll/Han:
- a barrier is added
- a "simple" scatter is added
- some Doxygen documentation is added

Fix:
- compilation and cppcheck warnings
- corner case errors when parsing a rule file

Signed-off-by: Emmanuel Brelle <emmanuel.brelle@atos.net>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
ok to test

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/039abe769567af0561aabf4505a4ac4c

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/67857e77c32482be7217d179f6dcdd7f

**Comment by jjhursey** [comment]
IBM Ci had an issue over the weekend. Retrying. bot:ibm:retest

**Review by bosilca — APPROVED** [review]

**Comment by EmmanuelBRELLE** [comment]
Is there anything I can do to help the review ? Otherwise, could this PR be merged ?

**Comment by ggouaillardet** [comment]
since @bosilca already approved this PR, I am merging it

**Pull request merged**
