### PR TITLE
Shmem fixes v2.x

### PR DESCRIPTION
**Pull request by artpol84**
Corresponds to #1867 (backing up open-mpi/ompi-release#1329)
Don't merge until #2095 is merged. Once merged - need to rebase it and then good to go.

### CODE REVIEW

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@artpol84 This PR needs to be rebased (perhaps because #2123 was just merged...?).

**Comment by jladd-mlnx** [comment]
Closing this. Not relevant to v1.3.

**Pull request closed without merging**
