### PR TITLE
v2.x flag enumerators and accumulate_ordering info key

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres Once this is merged I have one more feature I want to bring over.

**Comment by hppritcha** [comment]
@hjelmn what is the "one more feature" to bring over?

**Comment by hjelmn** [comment]
@hppritcha It was discussed on the call last week. It is the support for directly using AMOs for MPI_Fetch_and_op and MPI_Compare_and_swap. I needed the mpool rewrite and this before I can do the cherry-pick to avoid dealing to merge conflicts.

**Comment by jsquyres** [comment]
@hjelmn Still need a review.

**Comment by jsquyres** [comment]
Doh!  I'm assigned as the reviewer.  I'll review...

**Comment by jsquyres** [comment]
bot:lanl:retest

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
