### PR TITLE
Remove Trailing Whitespace

### PR DESCRIPTION
**Pull request by a-szegel**
Removes trailing whitespace in one spot to allow IDE's to enable the auto-remove
trailing whitespace setting without adding a lot of extra diffs to
commits. When you make a 1 line change in a file and have 100 lines of
trailing whitespace changes in the diff, it is time consuming to review.

Signed-off-by: Seth Zegelstein <szegel@amazon.com>

### CODE REVIEW

**Review by bwbarrett — APPROVED** [review]
I'm ok with the changes, but I'm not sure if the trailing whitespace in the RST files has any special meaning.  @jsquyres should chime in on those changes before this gets committed.

**Comment by devreal** [comment]
This is the same as the infamous clang-format patch: it pollutes the git history and makes git blame virtually useless. The actual benefit of whitespace-only changes for the community is asymptotically approaching zero. IMHO, you should fix your editor to remove whitespaces only on lines or files you edited or at least provide a substantive change that justifies changing the files.

**Comment by a-szegel** [comment]
The trim trailing whitespace on only lines edited is a good idea, but it is still a feature idea with VSCode: https://github.com/microsoft/vscode/issues/1315 (for 5 years now). To fix git blame, you can do: `git blame --ignore-rev <this commit>` (and have the blame that you were looking for).  I think this change will make cleaner PRs in the future, which is worth the price of an extra argument to git blame, and 1 additional commit in the history.

**Comment by jsquyres** [comment]
@a-szegel I realize that the concept of a whitespace-fixing-only set of commits is a bit controversial, but would it be possible to separate out the whitespace fixes to files that end in `.rst`?  Those are just docs files, and it looks like there's only 1 line in each file that it's fixing (all the man page `*.rst` files were automatically generated, and perhaps we had a bug in the python that generated them that included a rogue line that contained just a space).

**Comment by jsquyres** [comment]
Since this PR became controversial, I extracted the part of this commit that fixes the whitespace in the RST man pages and put that in https://github.com/open-mpi/ompi/pull/10652.

**Comment by wckzhang** [comment]
Since it looks like we're not moving forward with this change, I'm closing this PR. Please re-open if necessary.

**Pull request closed without merging**
