### PR TITLE
fcoll/dynamic_gen2: Reduce number of realloc calls

### PR DESCRIPTION
**Pull request by raafatfeki**
keep track of the sizeof the blocklen_per_process and displs_per_process
on the aggregator datastructure to minimze the number of realloc function
calls required in the shuffle_init operation.

Signed-off-by: raafatfeki <fekiraafat@gmail.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by edgargabriel** [comment]
the problems reported by the Mellanox jenkins do not seem to be related to this pr:

18:58:47 [jenkins03:15755] Error: pshmem_init.c:73 - _shmem_init() SHMEM failed to initialize - aborting

**Comment by yosefe** [comment]
@edgargabriel Mellanox jenkins is now fixed

**Comment by edgargabriel** [comment]
@yosefe thank you!

**Pull request merged**
