### PR TITLE
PML UCX: handle synchronous send & unite code for all the sending modes

### PR DESCRIPTION
**Pull request by alinask**
Signed-off-by: Alina Sklarevich <alinas@mellanox.com>
(cherry picked from commit 49913c692a67cd5189b59fb1d62c2063a74ba219)

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe Can you please review?

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by bwbarrett** [comment]
internal compiler error on the mpi layer?  Seems unlikely to be related to this patch :(.

bot:ompi:retest

**Comment by alinask** [comment]
@hppritcha Can you please merge?

**Comment by alinask** [comment]
@jsquyres @hppritcha Can this be merged please?

**Comment by jladd-mlnx** [comment]
@bwbarrett @hppritcha any reason this cannot be merged? We'd like to get this covered under our MTT. It is UCX specific code refactoring.

**Comment by jladd-mlnx** [comment]
@bwbarrett Thank you, sir.

**Pull request merged**
