### PR TITLE
coll/cuda: always compile component

### PR DESCRIPTION
**Pull request by edgargabriel**
the coll/cuda component has been converted to use the accelerator framework. Hence, we can always compile it, no need for the configure logic.
Furthemore, the component will now disqualify itself if the accelerator component selected is the 'null' component.

### CODE REVIEW

**Comment by edgargabriel** [comment]
bot:ibm:retest

**Comment by wckzhang** [comment]
Should we be renaming the component? Also due to delayed initialization, the accelerator component can still have the cuda component selected even if the user isn't going to use cuda. I don't know if that matters here, but that's something to consider whenever we have this check
```
opal_accelerator_base_selected_component.base_version.mca_component_name,
                    "null"
```

**Comment by edgargabriel** [comment]
@wckzhang I wouldn't rename the component right now, that is a much more intrusive change than what I intended with this commit.  I need to look however into the lazy initialization aspect, I haven't thought of that. Thanks!

**Comment by edgargabriel** [comment]
@janjust I don't think this is a candidate for the 5.0 release. Maybe we could discuss it in the meeting next Tuesday, I am a bit nervous about removing the configure logic. It is strictly speaking not required anymore, but the component would suddenly be available in all builds, and I would like to make sure that there is community agreement on how to approach this.

**Review by janjust — APPROVED** [review]

**Pull request merged**
