### PR TITLE
fix grpcomm errors bug 1215

### PR DESCRIPTION
**Pull request by annu13**
This commit is a potential fix for grpcomm issue:
 https://github.com/open-mpi/ompi/issues/1215
The race condition identified can be avoided by setting up the job structure before starting the communications in ess_base_std_orted.c

### CODE REVIEW

**Comment by rhc54** [comment]
@annu13 I'm puzzled - I see the new code, but I don't see where the old code was removed. We were obviously setting all these infrastructure up prior to this commit, so I assume the old code is being removed, yes?

**Comment by annu13** [comment]
oops! that was a merge mistake, thanks a bunch for quickly pointing this. In fact I didn't add any code, I just moved the existing job setup section before comm setup.

**Comment by artpol84** [comment]
@annu13 it seems that you haven't rebased your OMPI branch. And tried to resolve something by hands. This doesn't seems right. Your PR must have only your changes while this one:
https://github.com/annu13/ompi/commit/1a8c351c2621bce550d9d7e0bdb822ab8f86cd3a
seems to be related to the already existing commit from @ggouaillardet:
https://github.com/open-mpi/ompi/commit/e918d75fae15cc15d23ee327c4427aeb38ad72b3

**Comment by ggouaillardet** [comment]
@rhc54 you made a PR from your master branch, and that will get you in trouble ...
(Well, it did already)

The way we work is by making a branch first, and the make a pr with that branch.
First, run got log to retrieve your commits.
Then, reset to the most recent commit that is common between your master and ompi master
git reset --hard e918d75
Then branch
git checkout -b topic/my_branch
Then cherry pick your commits
git cherry-pick <commit ids>
And then push your branch to your github, and make the pr

As pointed by @artpol84 , there should be only one commit so you need to rebase,
Let me know if you need any help with that

**Comment by rhc54** [comment]
I think you meant @annu13 , not me.

**Comment by annu13** [comment]
closing this as it contains incorrect commits.

**Comment by annu13** [comment]
@ggouaillardet I got into this mess in multiple ways and now I am unable
to fix it :-(. I followed the process but looks I missed out some steps or
did something else inadvertently. To begin with
(1)I made changes on branch grpcomm_bug,
(2) merged grpcomm_bug branch with my local master,
(3)synced my fork with upstream (I used fetch upstream and merge upstream
- I had to manually merge my changes)
(4) then I pushed the changes
(5) filed a PR again master.

- After seeing Ralph�s comment, I realized that I didn�t merge correctly
in step 3 so
(6) fixed my merge
(7) resync my fork
(8) committed the changes - this is when I picked up your changes :-(.

I am trying to remove your changes from annu13@1a8c351, with no luck.
I tried the steps that you listed but I couldn�t cherry-pick my commit
from the big overall commit. I used revert instead.
Here is what I did -
(a) I reverted 1a8c351 on my master
(b) created a new branch named fixup
(c) made my change and committed it
(d) pushed fixup branch
(e) created a new pull request from this br


I hope it works now. I am sorry hope if this has caused any inconvenience
to anyone.

Thanks,
Annu.

**Pull request closed without merging**
