### PR TITLE
io/romio321: refresh ROMIO based on latest stable MPICH 3.2.1

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs #1970 and #24.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/816cab10ad17f25556f35cecf850682c

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fcc071a9f4ce6098c75c9946ea4a7771

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/75651224260139d4dae91e1f6cfc29e5

**Comment by ggouaillardet** [comment]
@jjhursey currently, `MPI_File_i{read,write}_[at_]all()` will simply crash because some functions under the hood are not implemented.
In the short term , i can make the related functions `NULL` so Open MPI can fail with a nice message instead of a crash. Obviously, `MPI_File_i{read,write}_[at_]all()` are not implemented, but this can be a first step to upgrade ROM-IO and check for bug fixes and/or performance improvements.

I am not sure how to move forward with respect to `MPI_File_i{read,write}_[at_]all()`.
One option is to implement the same extensions than `MPICH` so it can work out of the box.
An other option is to make minimal changes in order to use Open MPI progress infrastructure.

Any thoughts ?

**Comment by hppritcha** [comment]
bot:retest

**Pull request merged**
