### PR TITLE
docs/../ofi.rst: Correct typographical error

### PR DESCRIPTION
**Pull request by fullerdj**
Cornelius -> Cornelis

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]
Thank you!  Can you cherry-pick to the v5.0.x branch when this merges?

**Comment by fullerdj** [comment]
Sure. How do you like your history? I probably can't cherry-pick the merge over to that branch (it'll conflict a bunch). Do you just want me to cherry-pick my individual commit and push it there?

**Comment by fullerdj** [comment]
n/m, no real conflicts, I just don't have permission to push to open-mpi. Let me know if you want me to do a PR.

**Comment by jsquyres** [comment]
@fullerdj Yes, please just make a PR to the v5.0.x branch.  Thanks!

(`main` and `v5.0.x` aren't that far apart, even though `v5.0.x` branched off quite a while ago)

**Pull request merged**
