### PR TITLE
New hooks update

### PR DESCRIPTION
**Pull request by hjelmn**
@PHHargrove This should be almost everything. If you can test with ARM before I get a chance let me know if it works.

### CODE REVIEW

**Comment by PHHargrove** [comment]
@hjelmn
Is this instead of or in addition to the previous pr? 
I suspect that I am effectively just testing compilation at this point if everything is now disabled, right? 
Will test when I get back to my desk.

**Comment by PHHargrove** [comment]
Ignore my question "Is this instead of or in addition to the previous pr?"
Viewing on my phone I had not noticed "ompi" vs "ompi-release".

**Comment by PHHargrove** [comment]
@hjelmn 
I have launched tests on this branch on

- linux/x86 (Pentium3)
- linux/x86-64
- linux/ia64
- linux/ppc32
- linux/ppc64 ("-m32" and "-m64")
- linux/ppc64el
- linux/mips64 ("-mabi=n32" and "-mabi=64")
- linux/mips64el ("-mabi=n32" and "-mabi=64")
- linux/arm
- linux/arm64
- netbsd-7/i386
- netbsd-7/amd64

**Comment by PHHargrove** [comment]
My tests include "make check", compiling the examples subdir, and running each `ring_*` example that could be built on the given platform.

The following tests PASSED:
- linux/x86 (Pentium3)
- linux/x86-64
- linux/ia64
- linux/ppc64 w/ -m64
- linux/ppc64el
- linux/mips64 (both "-mabi=n32" and "-mabi=64")
- netbsd-7/i386
- netbsd-7/amd64

Several platforms failed due to unrelated issues in master:

`libopen-pal.so: undefined reference to '__sync_add_and_fetch_8'` linking opal_wrapper
- linux/ppc32
- linux/ppc64 w/ -m32

`openmpi-gitclone/opal/include/opal/sys/cma.h:49:2: error: #error "Unsupported architecture for process_vm_readv and process_vm_writev syscalls"`
- linux/arm
- linux/arm64
- linux/mips64el (both "-mabi=n32" and "-mabi=64")

**Comment by hjelmn** [comment]
The __sync_add_and_fetch_8 should be fixed on master. This branch doesn't have that. Looks like the patcher is fixed. I will fix CMA tonight.

**Pull request merged**
