### PR TITLE
v2.0.x: add support for 'external32' representation

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Thomas Gastine for the report

Fixes open-mpi/ompi#2985

### CODE REVIEW

**Comment by ggouaillardet** [comment]
this is a cherry-pick of the commits from open-mpi/ompi#1509

**Comment by jsquyres** [comment]
@ggouaillardet Can you please sign off these commits?

**Comment by ggouaillardet** [comment]
@jsquyres these are old commits (e.g. long before we moved to the CA) i cherry-picked from master
in a previous PR, we agreed there was no need to have them signed off.
i still need to review the change requested by @bosilca, and if you insist, i will also sign off all the commits.
(note some of them are authored by @bosilca, shall i sign them off ? ask George to do it ? ask George to allow me to do it for him ?)

**Comment by bosilca** [comment]
@ggouaillardet feel free to sign them if they need to be signed. However, we should have a flexible rule that allows us to cherry-pick old commits (from a time where we were bound by the signed agreement).

**Comment by rhc54** [comment]
Indeed, we do have such a policy - cherry-picking of old commits does _not_ require a sign off. This is just an artifact of a limitation in the automated checker. We shouldn't set policy based on that limitation, and that is what we had previously agreed upon.

**Comment by jsquyres** [comment]
Ok.

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
