### PR TITLE
btl/vader: handle unexpected short read/write in process_vm_{read,write}v

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Heiko Bauke for the bug report.

Refs. open-mpi/ompi#4829

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@bosilca I also read

> (Partial transfers apply at the granularity of iovec elements.  These system calls won't perform a partial transfer that splits a single iovec element.)

Since our `iovec` has only one element, does this behavior points to a bug in `glibc`/kernel ?
(partial transfer is not permitted, and hence the returned value should be `0` or the full buffer)

**Comment by bosilca** [comment]
I concur. I run on 2 kernel versions and it is the same behavior, and I did not had the time to look further.

**Comment by jsquyres** [comment]
If this behavior is contrary to system man pages, I think you should definitely add a comment in both locations explaining why this code is necessary (and cite the specific system/OS/distro/version/whatever where the non-manpage-conforming behavior was seen).  This won't matter in the next few months, but 2 years from now, someone will look at this code and say "That code is unnecessary because the man page guarantees that the unit of granularity of transfer is a single iovec!" -- opening the door to a possible regression if they delete this extra logic.

**Comment by jsquyres** [comment]
Per 2018-02-20 webex:

1. We agree that the comments should be added to this PR (as cited above).
1. We should probably investigate why the man page digresses from the observed behavior.  E.g., is this a glibc issue?  Is it a kernel issue?  Is this a *regression* (e.g., it *used* to obey iovec boundaries)?  ...etc.
1. This is an important issue and we should fix it, but given that it has existed in all of our release branches for years and this is the first time we're hearing about it (@bosilca says it only happens when you try to send >2GB in a single message), it doesn't feel like a blocker for any just-about-to-be-released version.

**Comment by hjelmn** [comment]
@ggouaillardet Can you add the comments that @jsquyres mentioned. I would like to get this into master.

**Comment by ggouaillardet** [comment]
@hjelmn I made the changes and will merge when CI completes

**Pull request merged**
