### PR TITLE
Let Slurm know that our daemons are not MPI tasks

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>
(cherry picked from commit c04916444c8922b9b7d6c0def74db2fdbe73a8b7)

### CODE REVIEW

**Comment by gpaulsen** [comment]
The Cherry-picked reference is incorrect / expired.

This is a reference to https://github.com/openpmix/prrte/commit/1e800540bd410fe1d0eb69e838b3c0814cc43658.

**Comment by gpaulsen** [comment]
Looks like it fixes an issue report in PMIX: https://github.com/openpmix/openpmix/issues/2031

**Review by hppritcha — COMMENTED** [review]
Hmm... has something changed with the default for the srun --mpi option?  For our 20.02.5 install, the srun man page claims --mpi=none is the default

**Comment by rhc54** [comment]
Sys admins can change that default via a setting in the Slurm config file - hence the need to set it.

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
FYI: This is not a cherry-pick from master because this functionality moved to PRRTE.

**Pull request merged**
