### PR TITLE
Added workflow for self-hosted runner Nvidia/Mellanox

### PR DESCRIPTION
**Pull request by B-a-S**
Migration from AZURE pipeline to GitHub Actions (GA)
workflow file for GA (uses self-hosted runner Nvidia/Mellanox)
https://github.com/B-a-S/ompi/actions/runs/5348344132

### CODE REVIEW

**Comment by artemry-nv** [comment]
@jjhursey could you please check why IBM CI failed?

**Comment by jsquyres** [comment]
bot:ibm:retest

**Review by jsquyres — APPROVED** [review]

**Comment by Alexey-Rivkin** [comment]
Very nice and concise! One minor enh. suggestion:
The 'runs-on' might be set once, then referenced by each job, e.g.:
```
env:
  labels: [self-hosted, linux, x64, nvidia]
  
jobs:
  deployment:
    runs-on: ${{ env.labels }}
```

**Comment by B-a-S** [comment]
> 



> Very nice and concise! One minor enh. suggestion: The 'runs-on' might be set once, then referenced by each job, e.g.:
> 
> ```
> env:
>   labels: [self-hosted, linux, x64, nvidia]
>   
> jobs:
>   deployment:
>     runs-on: ${{ env.labels }}
> ```

A good idea, but this construction doesn't work.
run-on requires a static statement

**Comment by janjust** [comment]
@B-a-S @Alexey-Rivkin Just a minor suggestion - after the PR has been approved - I would suggest not to force push to the PR rather make any adjustments in follow up PR, unless the approved changes introduce bugs not caught by reviewers or CI.

Please let me know when this is ready to be merged.

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by B-a-S** [comment]
> @B-a-S @Alexey-Rivkin Just a minor suggestion - after the PR has been approved - I would suggest not to force push to the PR rather make any adjustments in follow up PR, unless the approved changes introduce bugs not caught by reviewers or CI.
> 
> Please let me know when this is ready to be merged.

It's ready. But I don't have some ideas why IBM checks are failed

**Comment by awlauria** [comment]
bot:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
@B-a-S Can you please cherry pick this to the v4.0.x, v4.1.x, and v5.0.x branches?

**Pull request merged**
