### PR TITLE
Re-spin of PR #1491: BTL TCP async progress

### PR DESCRIPTION
**Pull request by jsquyres**
@bosilca What do you think of this PR as a replacement for #1491?  I did two things:

1. Squashed most of the commits down and make Thananon the author (since you assumedly want him to get some credit, since the PR updates the AUTHOR files).
1. Cleaned up the whitespace from the changes.

Ok?

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca Does this code do what was suggested in https://github.com/open-mpi/ompi/issues/1406#issuecomment-196464864?

**Comment by bosilca** [comment]
I don't understand on what grounds are you altering someone else PR ?

**Comment by jsquyres** [comment]
I didn't alter your PR.  I have suggestions for your PR, so I filed this new one.  Here's why:

* Your initial PR had a few dozen commits.  
* You later closed that commit and squashed the commits down and filed PR #1491.  
* While reading that PR, I realized that you still had commits that added a bunch of code and then removed that same code.  I also saw a bunch of whitespace problems.
* Rather than suggest to you to make those changes, I figured I could save you some time and propose a new PR with exactly what I was suggesting: further squashing (to avoid the net-zero-change commits), and fix the whitespace problems.

It's just a suggestion, George.

Can you answer whether this PR (or #1491) does what was suggested in https://github.com/open-mpi/ompi/issues/1406#issuecomment-196464864?

**Comment by bosilca** [comment]
Thanks Jeff, but #1491 has been reduced to 4 commits for quite a few days now. I added there the space cleanup so I am not sure we need ticket this anymore.

**Comment by jsquyres** [comment]
Excellent; thanks @bosilca

**Pull request closed without merging**
