### PR TITLE
Mpirun man update

### PR DESCRIPTION
**Pull request by nrgraham23**
This pull request includes updates for the mpirun man page.  The first commit is a cherry-pick from master.  The second commit removes options that are not available in v2.x

@jsquyres @hppritcha

### CODE REVIEW

**Comment by hppritcha** [comment]
Approved modulo @jsquyres requested commit cherry pick comment

**Comment by nrgraham23** [comment]
Updated the cherry-picked commit.  Ill remember that -x option for next time.

**Comment by jsquyres** [comment]
Sweet; thanks @nrgraham23

**Comment by jsquyres** [comment]
This is a man page update; not waiting for CI.

**Pull request merged**
