### PR TITLE
fix: mca_base_env_var mca parameter is never handled if it's set from am...

### PR DESCRIPTION
**Pull request by elenash**
...ca conf file
The previous PR and the discussion is here:
https://github.com/open-mpi/ompi/pull/431

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1273 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_329/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_329/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_329/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/329/
Test PASSed.

**Comment by miked-mellanox** [comment]
@hjelmn - could you please review. Thanks

**Comment by hjelmn** [comment]
How does the problem not also affect other variables set in an amca file? Is there a reason why this on in particular is causing problems?

**Comment by elenash** [comment]
@hjelmn The problem occurred because of the check in orte/mca/schizo/ompi/schizo_ompi.c file parse_env function. This check is done just for this certain mca parameter (mca_base_env_list) because it's handled specifically. We can also remove this check but it leads to surplus function call which is needed just in case if this mca parameter is specified.

**Comment by hjelmn** [comment]
Seems weird to special case a variable in the mca system but ok.

**Pull request merged**
