### PR TITLE
Fixed atoi bug 

### PR DESCRIPTION
**Pull request by perrynzhou**
@jsquyres   @rhc54 @ggouaillardet  sorry, I send pr make a wrong branch to merge with the first time.  I already rename dev branch to fixed_atoi_bug.please check it and review code,thank you. detail  discuss about link #6735 ,related  issue #6729

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@perryn please squash both commits into one

**Comment by perryn** [comment]
Heh. I think you meant to mention @perrynzhou . I was very confused for a second there :)

**Comment by perrynzhou** [comment]
> second

@perryn  I'm sure, the second merge is right.now I just merge commit into one

**Comment by ggouaillardet** [comment]
yep, thanks for the correction and sorry for the confusion.

**Comment by perrynzhou** [comment]
> yep, thanks for the correction and sorry for the confusion.
@ggouaillardet  already  squash both commits into one, #6738  about details

**Comment by ggouaillardet** [comment]
I issued #6739 for that purpose (single signed-off commit with a note in the commit message)

**Pull request closed without merging**
