### PR TITLE
NEWS and VERSION updates for 4.1.1rc1

### PR DESCRIPTION
**Pull request by rajachan**
Signed-off-by: Raghu Raja <craghun@amazon.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@rajachan I added a commit with some updates to NEWS.  If you're ok with it, squash it down.

Can you also update the shared library versions in `VERSION`?

**Comment by gpaulsen** [comment]
Are you guys still thanking non-Open-MPI community members for their bug reports in the NEWS?  We do that on v4.0.x, and seems like a good tradition to continue.

**Comment by jsquyres** [comment]
Yes, I see 3 "thanks" in the v4.1.1 NEWS.  If we missed any, please let us know!

**Review by jsquyres — CHANGES_REQUESTED** [review]
Looking at `git logs --no-merges v4.1.0..HEAD`, it looks like the following changed:

1. liborte
2. libmpi
3. liboshmem

Can you update their CRA values, too?

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
