### PR TITLE
Correctly pass the process group for creating intra-communicators

### PR DESCRIPTION
**Pull request by abouteiller**
master: the ordering of parameters to comm_set changed, breaking comm_agree on intercoms

### CODE REVIEW

**Comment by abouteiller** [comment]
1. Yes, that doesn't change the patch beside the description of the PR :)
2. I need to double check, we had the same logic on c_contextid before it changed, and it worked (it does pass testings with c_index as well, probably because we use c_index only for matching and not to access again c_local_group, the only different field in shadowcomm compared to comm). 
3. The premise is that **repeated** agreements on the same Intercomm are not a common usage pattern thus not worth optimizing.

**Comment by bosilca** [comment]
It makes no sense to share the same context is on working communicators, because the send and receive will be dissociated between the peers (you dont have a unique communication context where messages can match). It is working in this particular instance, because we are not using the PML matching, but instead are registering our own TAG and using Active Messages, totally avoiding the matching logic. But, in that case why do we need to bless the communicator with a stolen cid ?

**Comment by abouteiller** [comment]
We double checked with @bosilca and the ERA agreement never uses MPI matching, instead uses `c_index` to match agreements with its' own BML callbacks, hence there is no problem (2.).

**Comment by awlauria** [comment]
is this ready to go?

**Review by bosilca — APPROVED** [review]

**Pull request merged**
