### PR TITLE
mpi conformance: fix prototypes

### PR DESCRIPTION
**Pull request by ggouaillardet**
- MPI_Compare_and_swap
- MPI_Fetch_and_op
- MPI_Raccumulate
- MPI_Win_detach

Thanks to Michael Knobloch and Takahiro Kawashima for bringing this
to our attention

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hjelmn could you please double check this ?

**Comment by hjelmn** [comment]
Yup. Those are definitely wrong. Probably has to do with the MPI-3 RMA stuff coming in after the const change.

**Comment by hjelmn** [comment]
PR to 1.10 and 2.x once merged.

**Comment by hjelmn** [comment]
BTW, thank you for making the changes in the osc framework. We still need to make the changes for the other MPI interfaces (pt2pt, io, etc).

**Comment by ggouaillardet** [comment]
where are the remaining changes to be made ?
i initially made mimimum changes at the MPI level, and then got a bunch of warnings/errors in the osc framework. now, there is no more warnings

**Comment by kawashima-fj** [comment]
grep -r XXX ompi/mpi/c
and
grep -r TODO ompi/mpi/c

You'll see comments like "do not cast away const".
ompi/mca/osc/osc.h still need to be update for put, accumulate etc.

**Comment by ggouaillardet** [comment]
i see, i am on it now, thanks !

**Pull request merged**
