### PR TITLE
Removed deadlock in find dynamic region

### PR DESCRIPTION
**Pull request by jotabf**
This is my solution to issue #10328. The problem with this code is that inside of `ompi_osc_rdma_refresh_dynamic_region` there is a `ompi_osc_rdma_lock_acquire_shared` to the same lock used in `ompi_osc_rdma_lock_acquire_exclusive` generation a deadlock. My solution was simply to remove the outermost lock. However, I don't know if this is the better solution, but, with these changes, my test codes ran as I expected.

### CODE REVIEW

**Comment by awlauria** [comment]
ok to test

**Comment by devreal** [comment]
@jotabf After looking through the code, I think your patch is correct. The exclusive is not needed and the shared lock in `ompi_osc_rdma_find_dynamic_region` is enough to ensure consistency. I'd like @hjelmn to confirm that though.

**Comment by awlauria** [comment]
@devreal is this relevant to main/v5?

**Review by devreal — APPROVED** [review]

**Comment by devreal** [comment]
I think this should go back to v5.x, too.

**Comment by awlauria** [comment]
@jotabf can you retarget this for `main` branch, and then cherry-pick back to the v4.1/v4.0/v5.0 branches?

**Comment by awlauria** [comment]
@jotabf since git is going to try and merge v4.1 to main (not what we want), you probably want to locally checkout `main`, port (or even cherry-pick might work, if there's no conflict) the fix over, and create a new branch and then open a new PR targeting main. Sorry for this pain :(

After that's over and merged we can cherry-pick it back to the release branches.

**Pull request closed without merging**
