### PR TITLE
Update add_procs support

### PR DESCRIPTION
**Pull request by hjelmn**
This PR updates the add_procs support to allow mtl and btl modules to signal at run time that the new dynamic add_procs behavior is not supported. This PR is needed to support Portal4 which under certain conditions requires we call add_procs with all the procs in the job.

@jsquyres, @tkordenbrock, @bosilca please comment.

@tkordenbrock let me know if this helps the portals4 btl and mtl implementations.

### CODE REVIEW

**Comment by hjelmn** [comment]
@tkordenbrock BTW, you need to set the btl flag in your btl init function at the latest. I think this should be ok.

**Comment by tkordenbrock** [comment]
@hjelmn I have updated the Portals4 components and created a pull request on your add_procs branch.

**Comment by jsquyres** [comment]
With a quick review, :+1:

**Comment by hjelmn** [comment]
@jsquyres Thanks! From what I see in the portals4 changes it looks like the flag approach makes it much easier for btl and mtl authors.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
Now that #943 has been merged to the master, re-submit to Jenkins, which should fix the disable-dlopen test.

bot:retest

**Comment by hjelmn** [comment]
@bosilca Any comments on this approach for signaling that dynamic add_procs is not available?

**Comment by bosilca** [comment]
the code looks good.

**Pull request merged**
