### PR TITLE
Add a new topo module: Treematch

### PR DESCRIPTION
**Pull request by bosilca**
This PR is a replacement for the failed #448. It adds a new topo module allowing for process reordering based on user-provided weights

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca This generally looks good.  Two minor comments:

1. Do you want to squash these down into 1 commit?  I.e., is there a reason to have the separate commits?
1. Do you need to add anything to README to explain what this new treematch module is?

**Comment by bosilca** [comment]
@jsquyres thanks for the suggestions. I synched with master, updated the README and squashed all commit into a single one.

**Comment by hppritcha** [comment]
Is this ready to merge?

Do we want this pushed back to v2.x?

**Comment by jsquyres** [comment]
Yes, this is ready to go.  Thanks @bosilca!

**Pull request merged**
