### PR TITLE
Work on providing info on a per-rank basis for all local values - e.g, cpusets

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/0f29fdeed9fe7af22b8b2bb749c47766

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ebcf8870b6e8d9cbb4b5e4776870c400

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request closed without merging**
