### PR TITLE
Update hwloc to 1.11.2 + Fix

### PR DESCRIPTION
**Pull request by hjelmn**
This update brings hwloc up to 1.11.2 and brings in a bug fix for Cray systems.

### CODE REVIEW

**Comment by hjelmn** [comment]
@hppritcha This fixes an error message printed out on Trinity due to abnormally long /proc/mounts lines. I discussed this with @jsquyres and it should be good to go into v2.0.0. Will open the PR as soon as this is merged on master.

**Comment by jsquyres** [comment]
@hjelmn Can you add a README-ompi.txt file in the new component directory that contains the hash of the commit that you cherry-picked?  That helps us track it (especially if the git commit logs aren't available for whatever reason).  Thanks.

**Comment by hjelmn** [comment]
@jsquyres Added to the second commit.

**Comment by hjelmn** [comment]
@jsquyres Looks like this is good to go if you are ok with it.

**Comment by jsquyres** [comment]
@hppritcha I'm good with this.  It fixes a real bug on the Cray systems, and fixes whatever other bugs hwloc fixed from 1.11.1 to 1.11.2.  Sound ok to you?

**Comment by jsquyres** [comment]
:+1:

**Comment by hjelmn** [comment]
Ok, will merge and open for v2.0.0.

**Pull request merged**
