### PR TITLE
cm: fix selection priority

### LINKED ISSUE #1035: PML selection issues
We are observing two issues with the way the PML is selected:

1) on Truescale, when mpirun is used without any argument, the openib BTL (ob1 PML) gets selected over the PSM MTL (cm PML). This is a problem because users would like to get the best performance (with the PSM MTL) out-of-the-box. Instead, they have to add --mca pml  cm.

2) currently, whichever of the ob1 or the cm PML gets initialized/loaded first wins! Unfortunately, the components are not always loaded in the same order...

### PR DESCRIPTION
**Pull request by hjelmn**
This patch removes a priority check that disables cm if the previous
pml had higher priority. The check was incorrect as coded and is
unnecessary as we finalize all but one pml anyway.

Fixes #1035

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by jsquyres** [comment]
Per https://github.com/open-mpi/ompi/issues/1035#issuecomment-148560757, should the same check be made to ob1?

**Comment by hjelmn** [comment]
@jsquyres Removed the ob1 check as well. I see no reason to disable any pml component in this manner.

**Comment by bosilca** [comment]
With this approach we don't need the field default_priority in the CM PLM.

**Comment by jsquyres** [comment]
@yburette Does this fix your openib / PSM issue?

**Comment by hjelmn** [comment]
@bosilca I will remove the default priority in CM completely in another commit. I want to have the mtl components set the priority of cm if a different manner. Should have the PR up soon.

**Comment by hjelmn** [comment]
For history's sake here is the commit that added the extra selection checks:
open-mpi/ompi@a94101fa

Since dr is dead I think it is safe to remove them.

**Comment by hjelmn** [comment]
Will handle this all in #1040.

**Pull request closed without merging**
