### PR TITLE
v4.1.x: Accept UCX 1.8 in configure of btl/uct

### PR DESCRIPTION
**Pull request by cniethammer**
Backport from #7673

### CODE REVIEW

**Comment by jsquyres** [comment]
@bwbarrett This seems pretty trivial.   You ok with it?

**Comment by bwbarrett** [comment]
I'm ok with the patch for 4.1, but I'd prefer someone who knows the UCT BTL does the code review.  The patch looks ok to me, but I have no idea if 1.8 is ok or not for the UCT BTL.

**Comment by jsquyres** [comment]
bot:aws:retest

**Comment by jsquyres** [comment]
bot:aws:retest

**Pull request merged**
