### PR TITLE
ofi: check if libfabric has FI_HMEM_ROCR at configure time

### PR DESCRIPTION
**Pull request by hpcraink**
This allows compiling ompi-5.0.0rc12 with btl/ofi and mtl/ofi on clusters not providing rocm.

### CODE REVIEW

**Comment by awlauria** [comment]
@hpcraink please fix the errors in this PR so It can be merged when you have a minute.

**Comment by janjust** [comment]
@hpcraink Please add the cherry-pick message to the commit

**Review by hppritcha — APPROVED** [review]
please redo with

git check-pick -x sha_of_commit_on_main

to make our commit checker happy.

Otherwise I approve this request.

**Comment by jsquyres** [comment]
@hpcraink Is this a cherry-pick from `main`, or is this a unique commit to the v5.0.x branch?  We prefer if stuff goes in on `main` first, and then we cherry pick it over to the release branches.  This ensures that the fix is in all future releases (i.e., from `main`) *and* in the specific release branch (`v5.0.x`).  Thanks!

**Comment by awlauria** [comment]
it is a cherry-pick from main - the main commit is here:

https://github.com/open-mpi/ompi/pull/11372

**Comment by hppritcha** [comment]
whoever did the cherry-pick forgot to include the -x argument.  There's no cherry-picked-from message in the body of the commit.  that's the reason why it failed CI.

**Comment by awlauria** [comment]
I think at this point we're going to have to re-post the PR. I don't think @hpcraink is monitoring his email/ompi contributions.

**Comment by jsquyres** [comment]
@awlauria We can't just re-post this -- this is Rainer's patch.  He has to give the sign off / approval that we can use his patch.

**Comment by awlauria** [comment]
@jsquyres I don't understand. This is a cherry-pick of a main commit. We do this all of the time bringing back patches from main to release branches. Why is this any different?

**Comment by awlauria** [comment]
Oh never mind, I think I understand what you are saying. @hpcraink please fix this, or do you want us to close it and repost it (you will lose your contribution in that case, though)

**Comment by jsquyres** [comment]
> Oh never mind, I think I understand what you are saying. @hpcraink please fix this, or do you want us to close it and repost it (you will lose your contribution in that case, though)

Actually, @awlauria, I think **you** are right -- this is just a cherry pick, it's not Rainer's patch.  So, yes: any one of us can just fix the commit message on this PR and re-push to Rainer's branch (because github automatically gives all of us permissions on this PR's branch).  Then we'll be ok.

Good catch.

**Review by jsquyres — APPROVED** [review]
I amended the git commit message on this PR to include the proper cherry-picked notice, and also added the ROCM CI github action fix commit from #11937 to get CI to pass properly.  Now all looks good.

**Comment by awlauria** [comment]
Thanks @jsquyres

**Pull request merged**
