### PR TITLE
news-main: Remove 'Master' reference.

### PR DESCRIPTION
**Pull request by awlauria**
Replace with 'Main'.

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Comment by awlauria** [comment]
I amended this to remove the '=' to make it more inline.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request merged**
