### PR TITLE
Minor fix in cmd line parser help

### PR DESCRIPTION
**Pull request by cniethammer**
Fix wrong enum type in default command line option category assignment
Update out of sync in code documentation for opal_cmd_line_create()

### CODE REVIEW

**Comment by cniethammer** [comment]
Note: This fix affects the display of the help as
`OPAL_CMD_LINE_OTYPE_NULL != OPAL_CMD_LINE_TYPE_NULL`

**Comment by cniethammer** [comment]
@rhc54: This code seems also present in openpmix and prrte and will need updating there as well.

**Comment by rhc54** [comment]
This won't have any impact in master - OPAL isn't used to parse the PRRTE cmd line.

**Comment by jsquyres** [comment]
bot:aws:retest

**Pull request merged**
