### PR TITLE
Fixup

### PR DESCRIPTION
**Pull request by annu13**
This PR only contains one change in file ess_base_std_orted.c, the rest of the commits are a result of some rebase and incorrect merge operations.

### CODE REVIEW

**Comment by artpol84** [comment]
@annu13 this is steel incorrect. 
Commit list has to be just one commit. If you need to merge you're doing something wrong. 
In short you need to checkout fresh master, push it as a new branch in your fork and apply you the only one commit. and then do the PR.

**Comment by rhc54** [comment]
@artpol84 I don't understand your concern - there is only one commit in this PR. This looks just fine.

**Comment by artpol84** [comment]
Now it's OK. Note that @annu13 has changed the PR after my comment (according to the timeline). It wasn't OK but now it's fine.

**Comment by rhc54** [comment]
Ah, ok - thx!

**Pull request merged**
