### PR TITLE
pml_ucx: fix debug macros, and initialize mpi request properly.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox

**Comment by miked-mellanox** [comment]
:+1:

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by shamisp** [comment]
:+1:

**Comment by yosefe** [comment]
@hppritcha do you know why LANL build failed? I can't see how this can be related to this commit

**Pull request merged**
