### PR TITLE
osc/rdma: fix datatype extent usage in ompi_osc_rdma_rget_accumulate_…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…internal()

Refs open-mpi/ompi#3569

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hjelmn could you please double check this before i commit ?

i am confident this fixes the issue reported in #3569 but not so sure the ```extent``` is correctly handled if ```module->acc_single_intrinsic```

**Comment by ggouaillardet** [comment]
@bwbarrett fair enough, i updated both the patch and commit message

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ca23fd28bf3b17c00d42663723c42860

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e0a7590976439674086250d53cd264de

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/223798cfbdf6845fb92c8d56848e9d0d

**Comment by ggouaillardet** [comment]
:bot:mellanox:retest

**Comment by hjelmn** [comment]
Please PR to v3.0, v2.x, and v2.0.x.

**Comment by ggouaillardet** [comment]
@hjelmn i made PRs for ```v3.x``` and ```v2.x``` (```v2.0.x``` is a bit different)

while doing that, i found the fix was not quite right, so i made #3600 
can you please review it ?
then i will cherry-pick the commit into both PRs

**Pull request merged**
