### PR TITLE
mpool/rcache rewrite

### PR DESCRIPTION
**Pull request by hjelmn**
This PR brings in a complete rewrite of the mpool and rcache frameworks.

@vvenkates27 please verify memkind usability.

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres, @bosilca, @hppritcha Comments on the new interfaces are welcome. Let me know soon if you see any problems or things that can be improved. This is targeted for 2.0.0.

**Comment by vvenkates27** [comment]
Hi Nathan, 

Thanks for putting this together. I tested this out. It worked for the MPI_Alloc_mem.
 MPI_Free_mem was not picking up right mpool module because the allocated address was not added to the rb-tree maintained in the base module in mca_mpool_base_alloc.c:99. "mem" needs to be added as the key to the rb-tree. Doing that fixes that issue. 

I will let you know if I find any other issues. 

Thanks
Vish

**Comment by hjelmn** [comment]
Fixed the red-black tree issue. Still trying to track down the mellanox issue.

**Comment by hjelmn** [comment]
:bot:retest

Can't reproduce the Mellanox Jenkins failure.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
PR got screwed up on rebase. Fixing.

**Comment by jsquyres** [comment]
@hjelmn Any idea what's going wrong at btl_openib_endpoint.c:356?

**Comment by hppritcha** [comment]
Assuming this isn't addressing a bug in the existing mpool/rcache implementation,  I think this is too large a change to go in to 2.0 at this point.  It looks like a good candidate for 2.1.

**Comment by hjelmn** [comment]
Should be working now. @bosilca, @jsquyres Any comments on the new interfaces?

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
@miked-mellanox I can't tell what in the Mellanox Jenkins failed.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
@miked-mellanox This looks like a false failure. When I run your env_mpi by hand with valgrind I get this:

```
==12372== Invalid read of size 8
==12372==    at 0x40082D: main (in /lustre/scratch1/yellow/hjelmn/ibm/env_mpi)
==12372==  Address 0xe132510 is 0 bytes inside a block of size 960 free'd
==12372==    at 0x4C27C20: realloc (vg_replace_malloc.c:662)
==12372==    by 0x56AD3FC: __add_to_environ (setenv.c:143)
==12372==    by 0x4C2B679: setenv (mc_replace_strmem.c:1756)
==12372==    by 0x50A2E34: ompi_mtl_mxm_component_open (mtl_mxm_component.c:216)
==12372==    by 0x698B9FE: open_components (mca_base_components_open.c:125)
==12372==    by 0x698B91B: mca_base_framework_components_open (mca_base_components_open.c:68)
==12372==    by 0x699A4B2: mca_base_framework_open (mca_base_framework.c:176)
==12372==    by 0x511281B: mca_pml_cm_component_open (pml_cm_component.c:112)
==12372==    by 0x698B9FE: open_components (mca_base_components_open.c:125)
==12372==    by 0x698B91B: mca_base_framework_components_open (mca_base_components_open.c:68)
==12372==    by 0x50E6AA9: mca_pml_base_open (pml_base_frame.c:183)
==12372==    by 0x699A49C: mca_base_framework_open (mca_base_framework.c:174)
==12372== 
```

If I include unistd.h and use __environ instead the test program works. Looks like this happens because the values of env and __environ differ if setenv or putenv is called anywere in the program. You will have to drop the usage of the non-standard three-argument main.

**Comment by hjelmn** [comment]
Rebased off master.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
fixed a usnic compile issue.

**Comment by hjelmn** [comment]
@miked-mellanox Is the Mellanox Jenkins running the updated version of env_mpi?

**Comment by miked-mellanox** [comment]
@hjelmn - yep

**Comment by hjelmn** [comment]
@miked-mellanox This failure makes no sense to me. Here is the failure:

```
00:44:30.369 + echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
00:44:30.370 ++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
00:44:30.370 ++ grep '^XXX_'
00:44:30.370 ++ wc -l
00:44:30.756 + val=0
00:44:30.756 + '[' 0 -ne 10 ']'
00:44:30.756 + exit 1
```

Where are you setting mca_base_env_list? I see no -mca mca_base_env_list and no OMPI_MCA_mca_base_env_list= anywhere. Is the variable set in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf somewhere?

If I try to run this on one of my systems (with setting mca_base_env_list) it succeeds with the mpool_rewrite branch:

```
bash$ export XXX_C=3 XXX_D=4 XXX_E=5
bash$ mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' ./env_mpi | grep ^XXX | wc -l
10
```

**Comment by hjelmn** [comment]
@miked... Wait. I see what it is supposed to do. It should be putting the string ```mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E`` into the amca file then run the test. That is working for me as well. Can you double-check the test is doing what it is supposed to do?

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

Made some changes to Mellanox Jenkins that should help indicate what is failing.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
@sjeaugey Thanks for running MTT on the branch. I was able to fix what I think was causing the problems.

Also, I making an attempt to put CUDA support in vader. Should have something ready this week.

**Comment by bosilca** [comment]
@hjelmn I would suggest you don't do it based on current SM support. We have a big PR coming with a significantly better approach (and also better performance). Would you be interested in attempting to add support in vader there ?

**Comment by hjelmn** [comment]
@bosilca Sure, I will wait. Once I get positive MTT results I will commit this PR. I will wait until your PR to look at smcuda.

**Comment by hjelmn** [comment]
@sjeaugey Looks like the updated PR wasn't run last night. Can you check what revision was run?

**Comment by sjeaugey** [comment]
@hjelmn I don't understand why it didn't run. Running is manually right now.

**Comment by hjelmn** [comment]
@sjeaugey Any results? If this is working I want to get it merged in as soon as possible.

**Comment by hjelmn** [comment]
@sjeaugey Looks like it ran last night and it looks clean. I will merge this later today.

**Comment by hjelmn** [comment]
:bot:retest

**Comment by sjeaugey** [comment]
@hjelmn Indeed it looks cleaner, except for one cuda test. However, I noticed yesterday that when running without any --mca btl argument (in fact when running with the default configuration) I got a segmentation fault on all the tests I tried. I don't know what we're using in this case (yalla?) but there seem to be an issue.

**Comment by hjelmn** [comment]
Might be worth adding a -mca pml_base_verbose 100 to see what pml is being selected.

**Comment by hjelmn** [comment]
@sjeaugey Found the bug that is causing the MTT failure. Will push after some testing.

**Comment by hjelmn** [comment]
@sjeaugey Ok, should be good for real now.

**Comment by sjeaugey** [comment]
@hjelmn looks indeed good now !

**Comment by sjeaugey** [comment]
@nhjelmn Oh wait. The test count in MTT is not right. The IBM test were not run. Need to figure out why.

**Comment by hjelmn** [comment]
@sjeaugey Should be ok. Those tests don't have any CUDA specific so should be no different than what I see on my mlx4 systems.

**Pull request merged**
