### PR TITLE
v4.0.x: orte/timeout: Upon timeout terminate orted's instead of abandoning them

### PR DESCRIPTION
**Pull request by awlauria**
* When `orterun` is terminating due to a timeout, it should first
   order the daemons to cleanup and exit before terminating itself. This
   prevents the opporunity for the child processes to become orphaned.

bot:notacherrypick

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Review by gpaulsen — APPROVED** [review]

**Review by rhc54 — CHANGES_REQUESTED** [review]
Errrr...so what happens if the reason we timed out is that the daemons are unresponsive? Looks to me like this simply hangs. You probably need to ensure that you have a timeout set so that mpirun can terminate if the daemons fail to die.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by jjhursey** [comment]
That concern is worth double-checking. I thought we did that check when we made this change internally a while back, but it doesn't hurt to double check. Let's put this as a WIP until that happens.

**Comment by awlauria** [comment]
@rhc54 are you implying that ` if (ORTE_SUCCESS != (ret = orte_plm.terminate_orteds()) ) {` can hang if the orteds are unresponsive and not just return an error?

Would adding a timer here be a safety valve, or a plausible scenario?

**Comment by rhc54** [comment]
If the terminate_orteds call returns an error, then you know that the remote daemons will never terminate. In that case, best just to exit.

If terminate_orteds returns success, there still is no guarantee that the remote daemons will properly terminate so mpirun can cleanly exit. If you look a little further down in the code, you'll see where we protect ourselves from a similar problem when requesting stack traces:
```c
        /* we will terminate after we get the stack_traces, but set a timeout
         * just in case we never hear back from everyone */
        if( orte_stack_trace_wait_timeout > 0 ) {
            OBJ_CONSTRUCT(&stack_trace_timer, orte_timer_t);
            opal_event_evtimer_set(orte_event_base,
                                   stack_trace_timer.ev, stack_trace_timeout, NULL);
            opal_event_set_priority(stack_trace_timer.ev, ORTE_ERROR_PRI);
            stack_trace_timer.tv.tv_sec = orte_stack_trace_wait_timeout;
            opal_event_evtimer_add(stack_trace_timer.ev, &stack_trace_timer.tv);
        }
```
I'd suggest just adding the same code here.

**Comment by awlauria** [comment]
Thanks @rhc54 . I pushed up a commit to address this.

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
@rhc54 is this good with you?

**Review by rhc54 — APPROVED** [review]

**Comment by rhc54** [comment]
Yes, thanks! Just to clarify a bit, this change is actually not required. When `mpirun` exits, any remaining daemons will see their connection to `mpirun` drop. This triggers a "suicide" operation that includes local cleanup of all session directories plus forcible termination of any child processes.

If the cleanup isn't happening in that case, then that is a bug in the daemons that needs to be fixed. After all, it is always possible that `mpirun` could segfault or otherwise disappear - so the "unclean" termination mode needs to work. Otherwise, you are treating the symptom as opposed to fixing the root problem.

That said, there is no harm in providing a "clean" termination code path here so long as the timeout is included.

**Comment by jsquyres** [comment]
@rhc54 I'm assuming https://github.com/open-mpi/ompi/pull/9273 (the v4.1.x version of this PR) is similar.  Can you check that one?  Thanks!

**Review by jjhursey — APPROVED** [review]

**Comment by jsquyres** [comment]
This hides the real problem, right?

- the real problem is that the daemons are not suiciding cleanly, right?
- what is the actual problem?  is it that they're not suiciding, or not suidicing and cleaning up session dirs?

**Comment by awlauria** [comment]
@jsquyres - this was seen when using the --timeout option of mpirun. The child ranks were not getting killed. You can reproduce this by doing:

`mpirun --timeout 5 --np 2 sleep 20`

The orteds will go away, but the ranks will remain. This commit/patch fixes it so the child ranks are also terminated.

This can be especially problematic for CI, as it can leave hung MPI ranks everywhere.

**Comment by rhc54** [comment]
So it sounds like you have two root problems that need addressing:

1. orted's are not reaping their children before exiting upon suicide
2. MPI procs are not suiciding when their local daemon goes away

Both are serious problems that need to be addressed as those scenarios are encountered in the wild.

**Comment by awlauria** [comment]
I can confirm that killing `mpirun` with and without this patch will result in the termination of the ranks. It seems specifically tied to the usage of `-- timeout`.

I can't comment whether this is the 'correct' fix to make `--timeout` work or not. However - it has been in smpi for several years now and used with our CI testing, and has made a difference in making sure that they exit with `--timeout` is hit.

**Comment by rhc54** [comment]
The only possibly relevant difference I can find between `timeout` and killing `mpirun` is that `timeout` results in an orderly shutdown of `mpirun`. This includes calling `shutdown` on the TCP socket connecting `mpirun` to each daemon prior to closing the file descriptor. I suppose it is possible that `shutdown` somehow causes the remote daemon to not see the socket actually close - but that seems odd.

If we look at what happens when the peer's socket drops, you find us jumping to the "lost_connection" function of the oob:
```c
    if (!orte_finalizing) {
        /* activate the proc state */
        if (ORTE_SUCCESS != orte_routed.route_lost(pop->rtmod, &pop->peer)) {
            ORTE_ACTIVATE_PROC_STATE(&pop->peer, ORTE_PROC_STATE_LIFELINE_LOST);
        } else {
            ORTE_ACTIVATE_PROC_STATE(&pop->peer, ORTE_PROC_STATE_COMM_FAILED);
        }
    }
```
Assuming the routed component correctly identifies this as our lifeline, it jumps you into the errmgr:
```c
    if (ORTE_PROC_STATE_LIFELINE_LOST == state ||
        ORTE_PROC_STATE_UNABLE_TO_SEND_MSG == state ||
        ORTE_PROC_STATE_NO_PATH_TO_TARGET == state ||
        ORTE_PROC_STATE_PEER_UNKNOWN == state ||
        ORTE_PROC_STATE_FAILED_TO_CONNECT == state) {
        OPAL_OUTPUT_VERBOSE((2, orte_errmgr_base_framework.framework_output,
                             "%s errmgr:orted lifeline lost or unable to communicate - exiting",
                             ORTE_NAME_PRINT(ORTE_PROC_MY_NAME)));
        /* set our exit status */
        ORTE_UPDATE_EXIT_STATUS(ORTE_ERROR_DEFAULT_EXIT_CODE);
        /* kill our children */
        killprocs(ORTE_JOBID_WILDCARD, ORTE_VPID_WILDCARD);
        /* terminate - our routed children will see
         * us leave and automatically die
         */
        orte_quit(0, 0, NULL);
        goto cleanup;
    }
```
where you can see we kill our local procs and then quit - exactly as we should. This is the same whether timeout is used or mpirun is simply killed.

So I think the correct question to ask is: why is `timeout` behaving so differently? Did anyone set `state_base_verbose=5` to track where the orted's were going in their state machine?

Note: as I've said several times, I don't really care about the OMPI v4 series. I'm only trying to educate people on how to track down the root cause of these problems as opposed to applying bandaids to solve an immediate problem.

**Pull request closed without merging**
