### PR TITLE
Add post_config hook for MPI extensions

### PR DESCRIPTION
**Pull request by bwbarrett**
Two patches to provide a post_config hook for MPI extensions, similar to the one available for MCA components, to help @bosilca  with one of his projects.

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Review by bosilca — APPROVED** [review]

**Comment by awlauria** [comment]
Should this be ported to v5.0.x?

**Comment by jsquyres** [comment]
Probably so.  But you might want to let @bwbarrett roll up all the configury-related stuff in 5.0.x PRs.

**Comment by awlauria** [comment]
ok - since this is older than the others just wanted to make sure it wasn't missed. thanks

**Comment by bwbarrett** [comment]
It wouldn't be harmfull (nor hard), but unless @bosilca is planning on backporting the extension that needed this functionality, I'm not sure it's worth the small effort.

**Comment by bosilca** [comment]
No such plans on our side, our extensions target master and 5.0

**Comment by bwbarrett** [comment]
we were talking about whether this patch was required for 5.0.  Sounds like it is; I'll file a PR to backport it to 5.0 today.

**Pull request merged**
