### PR TITLE
Add fence_nb to flux pmix

### PR DESCRIPTION
**Pull request by samiilvonen**
Flux runs segfault in MPI_Finalize if ucx pml is used. It seems that opal_common_ucx_mca_pmix_fence calls opal_pmix.fence_nb without checking if the fence_nb is implemented or not. This patch adds a 'fake' fence_nb call that uses PMI_Barrier similarly to the fence call.

### CODE REVIEW

**Comment by jjhursey** [comment]
ok to test

**Comment by jjhursey** [comment]
Do you also need to apply this to `v4.1.x`?

**Comment by samiilvonen** [comment]
> Do you also need to apply this to `v4.1.x`?

I don't have a test setup for v4.1.x yet, but opal_common_ucx_mca_pmix_fence seem to be identical in v4.1.x so the fix is probably needed there too.

**Comment by jjhursey** [comment]
This seems ok. It does make the nonblocking call (`fence_nb`) a blocking call (`PMI_Barrier`) under the hood, but I don't think that will break anything in OMPI so it's fine for this component IMHO.

It might be useful to fix `opal_common_ucx_mca_pmix_fence` to call the blocking interface if it is provided, but that should be a PR against OMPI master the UCX folks should probably review. So that can be a separate activity.

**Review by jjhursey — APPROVED** [review]

**Comment by jsquyres** [comment]
Is this needed on master?

If so, I'd prefer if it went to master first, and then to v4.0.x and v4.1.x.

Thanks!

**Comment by rhc54** [comment]
There is no flux plugin on master, Jeff - strictly PMIx

**Pull request merged**
