### PR TITLE
openib btl: remove BTL_OPENIB_FAILOVER_ENABLED code

### PR DESCRIPTION
**Pull request by larrystevenwise**
Remove BTL_OPENIB_FAILOVER_ENABLED code in the openib btl source.

Remove the failover-specific files from the openib btl.

Update the openib/Makefile.am accordingly.

Remove the -enable-openib-failover config logic.

Signed-off-by: Steve Wise <swise@opengridcomputing.com>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by hppritcha** [comment]
add to whitelist

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
this PR needs a reviewer

**Pull request merged**
