### PR TITLE
v5.0.x PRRTe and OpenPMIx pointer update.

### PR DESCRIPTION
**Pull request by awlauria**
bot:notacherrypick

### CODE REVIEW

**Comment by awlauria** [comment]
Reverting the spec file change since this is now fixed in prrte. Just closing the loop on it.

**Review by janjust — APPROVED** [review]

**Comment by janjust** [comment]
Yes @awlauria discussed this - the point of this was to actually update the updates, you're tagged because we reverted the patch

**Review by jsquyres — APPROVED** [review]
It's 2 commits -- I see.  Got it!

**Comment by janjust** [comment]
Ralph said he'll cut another release when we're absolutely sure we're going to release, but it does include a few updates we'd like to have in the rc

**Pull request merged**
