### PR TITLE
No-Op comment change

### PR DESCRIPTION
**Pull request by gpaulsen**
I suspect this no-op change may fail CI.

[skip ci]
bot:notest

Signed-off-by: Geoffrey Paulsen <gpaulsen@us.ibm.com>

### CODE REVIEW

**Comment by gpaulsen** [comment]
Even when using `[skip ci]` and `bot:notest`, the github actions CI and readthedocs CI gets triggered (probably intentionally)

Unfortunately the Mellanox CI actually FAILS for some reason.

**Comment by gpaulsen** [comment]
@open-mpi/ucx  - Can you please take a look?

```
Starting: Initialize containers
/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.40'
Docker daemon API version: '1.40'
/usr/bin/docker version --format '{{.Client.APIVersion}}'
'1.40'
Docker client API version: '1.40'
/usr/bin/docker ps --all --quiet --no-trunc --filter "label=212c59"
/usr/bin/docker network prune --force --filter "label=212c59"
/usr/bin/docker pull rdmz-harbor.rdmz.labs.mlnx/hpcx/ompi_ci:latest
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
##[warning]Docker pull failed with exit code 1, back off 1.431 seconds before retry.
/usr/bin/docker pull rdmz-harbor.rdmz.labs.mlnx/hpcx/ompi_ci:latest
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
##[warning]Docker pull failed with exit code 1, back off 1.201 seconds before retry.
/usr/bin/docker pull rdmz-harbor.rdmz.labs.mlnx/hpcx/ompi_ci:latest
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
##[error]Docker pull failed with exit code 1
Finishing: Initialize containers
```

**Comment by jsquyres** [comment]
@gpaulsen The UCX team is not the right team to ping for CI issues.  Please ping @artemry-nv for Mellanox CI problems.

@artemry-nv Can you please see what's going wrong with the Mellanox CI on this PR?  Thanks!

**Comment by artemry-nv** [comment]
> @gpaulsen The UCX team is not the right team to ping for CI issues. Please ping @artemry-nv for Mellanox CI problems.
> 
> @artemry-nv Can you please see what's going wrong with the Mellanox CI on this PR? Thanks!

There's disk exhaustion issue on our internal container registry - working on the fix.

**Comment by artemry-nv** [comment]
azp /run

**Pull request closed without merging**
