### PR TITLE
romio: make romio use internal opal_random instead of rand(3).

### PR DESCRIPTION
**Pull request by thananon**
Cross referenced to #1877 

As I'm not familiar with romio, I don't know how to test this properly. Please review.
The code does compile.

### CODE REVIEW

**Comment by jsquyres** [comment]
@Edgargabriel can you recommend a test for this PR?

**Comment by edgargabriel** [comment]
without knowing too much about opal_srand etc. , but I can have a look at it and run some tests. Will let you know.

**Comment by jsquyres** [comment]
Sorry -- what I meant was: is there a simple MPI File-based test we could run to just verify simple functionality?  I was kinda hoping you were pseudo-familiar with the internals of ROMIO to know what top-level MPI_File_* function(s) call ADIOI_Shfp_fname.  😄

**Comment by edgargabriel** [comment]
it is a shared file pointer operation, so I *think* anything using e.g. MPI_File_write_shared etc. should invoke that.

**Comment by jsquyres** [comment]
@edgargabriel Cool.  Do we have any shared file pointer tests in ompi-tests?

**Comment by edgargabriel** [comment]
yes, of course. E.g. you can go to
ompi-tests/mpi2basic_tests/file

adjust the Makefile.in one level above, and compile e.g. the write_shared or the read_shared test
make write_shared read_shared

You have to run them with exactly 6 processes on a file system that support file locking (e.g. local laptop/desktop should be fine most of the time), forcing using romio314. I just confirmed on my machine that those two test cases do pass with romio314

**Comment by edgargabriel** [comment]
I can run those tests on this branch if you want, but I need to finish something else first urgently

**Comment by jsquyres** [comment]
Excellent; thanks for running them for us!

:+1:

**Comment by jsquyres** [comment]
Hah; we commented at the same time.  We can run the tests - you gave us all the relevant info. 

Arm: why not run the tests Edgar mentioned, just to be sure.

**Comment by thananon** [comment]
All mpi2basic_tests/file passed 👍

**Comment by edgargabriel** [comment]
just to make sure, you did add --mca io romio314 to your execution? Otherwise it would use ompio

**Comment by thananon** [comment]
I did not. Will retest soon.
Thank you for catching this.

**Comment by edgargabriel** [comment]
ok, just make sure to compile and run only write_shared and read_shared, one of the other testcases leads to a problem with ROMIO, but those two should work.

**Comment by thananon** [comment]
test with -mca io romio read_shared and write_shared passed 👍

**Comment by jsquyres** [comment]
Arm: please pr to v2.0.1

**Pull request merged**
