### PR TITLE
MCA variable scope and coll tuned rules file update onto v4.1.x

### PR DESCRIPTION
**Pull request by burlen**
Pick MCA variable scope and coll tuned rules file update onto v4.1.x

bot:notacherrypick

### CODE REVIEW

**Comment by burlen** [comment]
I see. I was not aware. I want them on v4.1.x to be a part of the NVIDIA HPC-X release. HPC-X is the deployment vehicle for several of the systems I use. It sounds like there will be at least one more HPC-X release on v4.1.x branch. https://github.com/open-mpi/ompi/pull/12897

**Review by janjust — APPROVED** [review]

**Comment by bwbarrett** [comment]
We may never do a release, but I'm happy to merge these in.  Were these changes a backport from main or something unique to this branch?  Just trying to figure out how to make the commit format checker pass.

**Comment by burlen** [comment]
I may have missed the boat on getting these into the release. I'm not sure what the schedule for moving to v5 in hpcx is. All but f7011c6ef18137d117b629bcf012fd924a92b232 is cherry-picked from main. f7011c6ef18137d117b629bcf012fd924a92b232 addresses some issues because some files in v4 branch are not in sync with main

**Comment by jsquyres** [comment]
@bwbarrett I don't remember offhand, but the cherry-pick checker may well not look for `bot:notacherrypick` in commit messages -- it may only look for it in the PR description...?  I don't remember why we would have done that, though.

**Comment by rhc54** [comment]
> it may only look for it in the PR description...?

Correct - it has to be in the upper description

**Comment by bwbarrett** [comment]
Just in the PR description, because bot:notacherrypick doesn't belong in the commit history of the code.

**Pull request merged**
