### PR TITLE
pr/nb collective I/O part2

### PR DESCRIPTION
**Pull request by edgargabriel**
second part of the non-blocking collective I/O changes. @hppritcha would you mind to have a look at the interfaces and io framework changes to make sure it is correct?

### CODE REVIEW

**Comment by hppritcha** [comment]
thanks, reviewing.

**Comment by hppritcha** [comment]
I'm having problems compiling:
  PPFC     file_iwrite_at_all_f08.lo
file_iread_at_all_f08.F90:12.25:

   use :: mpi_f08, only : ompi_file_iread_at_all_f
                         1
Error: Symbol 'ompi_file_iread_at_all_f' referenced at (1) not found in module 'mpi_f08'
file_iread_at_all_f08.F90:23.51:

   call ompi_file_iread_at_all_f(fh%MPI_VAL,offset,buf,count,&
                                                   1
Error: Assumed-type argument buf at (1) requires an explicit interface
  PPFC     file_iwrite_shared_f08.lo
make[2]: *** [file_iread_at_all_f08.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
  PPFC     file_iwrite_all_f08.lo
file_iread_all_f08.F90:12.25:

   use :: mpi_f08, only : ompi_file_iread_all_f
                         1
Error: Symbol 'ompi_file_iread_all_f' referenced at (1) not found in module 'mpi_f08'
file_iread_all_f08.F90:22.41:

   call ompi_file_iread_all_f(fh%MPI_VAL,buf,count,datatype%MPI_VAL,request%MPI_VAL,c_ierror)
                                         1
Error: Assumed-type argument buf at (1) requires an explicit interface
make[2]: *** [file_iread_all_f08.lo] Error 1
file_iwrite_at_all_f08.F90:12.25:

I'm using the gfortran 4.9.2.  Odd that the jenkins test didn't try to build the f08.

**Comment by edgargabriel** [comment]
hm, ok, I'll have a look at it, my desktop has 4.8.1, so I guess that interface was not building.

**Comment by edgargabriel** [comment]
Howard, sorry for the trouble, I think I fixedit. I installed gcc 5.1 on my PC, and it seems to compile now.

**Comment by hppritcha** [comment]
new code compiles.  will try a test case from mpich.

**Comment by hppritcha** [comment]
works for lustre with the mpi2basic_tests filetest case. going on and merging.
@edgargabriel  could you open a PR on v2.x for this.  Thanks for doing this work.

**Pull request merged**
