### PR TITLE
iof/base: (try to) set the winsize to the pty of the spawned tasks

### PR DESCRIPTION
**Pull request by ggouaillardet**
This is a backport from the prrte project.
bot:notacherrypick

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

(back-ported from openpmix/prrte@795de884b71afe0cf6a8499bca02fb9e5f8320dd)

### CODE REVIEW

**Review by jsquyres — CHANGES_REQUESTED** [review]
Let's get the same git commit message update that was applied to #9118.

**Comment by gpaulsen** [comment]
@ggouaillardet ?

**Comment by ggouaillardet** [comment]
@jsquyres @gpaulsen done!

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:cray:retest

**Comment by jsquyres** [comment]
bot:ompi:retest

**Pull request merged**
