### PR TITLE
dl/dlopen/libltdl: Allow opal_dl_open to take a NULL filename.

### PR DESCRIPTION
**Pull request by jjhursey**
Discussion on the mailing list here:
 * https://www.open-mpi.org/community/lists/devel/2016/05/18912.php

### CODE REVIEW

**Comment by jsquyres** [comment]
👍

**Comment by jjhursey** [comment]
My functional testing passed. I'll wait on the last of the CI tests to finish then merge into master and create a PR for v2.0.0.

Thanks!

**Comment by jjhursey** [comment]
Looks like a localized problem with the mellanox build. They are failing in autogen, which this commit does not impact.

**Comment by jjhursey** [comment]
bot:retest

**Pull request merged**
