### PR TITLE
docs: Transition Omni-Path references to Cornelis Networks

### PR DESCRIPTION
**Pull request by jack-morrison**
Also, fix a typo 'TrueScale' -> 'True Scale'

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]
Thanks!

**Comment by jsquyres** [comment]
@jack-morrison Can you make a PR to `git cherry-pick -x ...` this commit over to the v5.0.x branch?

Thanks!

**Comment by jack-morrison** [comment]
> Can you make a PR to `git cherry-pick -x ...` this commit over to the v5.0.x branch?

Will do!

**Comment by jack-morrison** [comment]
@jsquyres, please see #12766 for these changes targeting `v5.0.x`.

**Pull request merged**
