### PR TITLE
Topic/fixes

### PR DESCRIPTION
**Pull request by bosilca**
Fixes a bunch of issues related to OMPI compilation (incorrect use of defines, missing SPC constants) and an issue related to error returning from MPI_Start. Need to be pushed on all branches.

### CODE REVIEW

**Review by devreal — APPROVED** [review]
Sorry about that, I copied the wrong code from `startall.c`. I realized that `MPI_Startall` does not check the return from the start call at all and always returns `MPI_SUCCESS` :/ See https://github.com/open-mpi/ompi/blob/main/ompi/mpi/c/startall.c#L120

**Comment by bosilca** [comment]
It is not very clear to me what `MPI_Startall` should return nor, assuming some error state, in what state it should leave the requests who did not generate the error. The current assumption is that as long as the requests are valid and can be started, the error code will be returned upon completion.

**Review by hppritcha — APPROVED** [review]

**Comment by devreal** [comment]
> It is not very clear to me what MPI_Startall should return nor, assuming some error state, in what state it should leave the requests who did not generate the error. The current assumption is that as long as the requests are valid and can be started, the error code will be returned upon completion.

So should we instead revert my patch that introduced the error code check to always return `MPI_SUCCESS` from `MPI_Start`? In test/wait we have at least a chance to fill a status....

**Comment by awlauria** [comment]
@devreal @bosilca do these fixes need to go to v4.0.x? It looks like this was merged: https://github.com/open-mpi/ompi/pull/10553

**Comment by bosilca** [comment]
It seems you're right, this PR needs to be ported on the release branches.

**Comment by jsquyres** [comment]
Just to confirm these changes were brought to v5.0.x in #10603.

**Pull request merged**
