### PR TITLE
Test PGI compiler - part 2

### PR DESCRIPTION
**Pull request by rhc54**
Just add new dstore code - no other changes

DO NOT MERGE THIS PR

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/30d96e65f317c8c80adf9fe6375f40e9

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7a27548bc18a22679a8b064b85e15803

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6511de3665aa6e5a1ddf5fbaee29c59b

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cc3e8cfad03b24e8d42fb140ad6a2f32

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ef4e72da697da398b764019e61af905b

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5a0e0edee36cf2b5e39a8dfdd66275de

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/76e924cb93ae82dabc887188f7d09051

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/07eb98d63bf8440b833e6d45f78b3eb8

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/402540c70afea8f48732ba5b836b11f7

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1c3fa4b56d41d5d0be6a5eb6ae71976b

**Comment by rhc54** [comment]
This is compiling - the error is being hit deep into the oshmem layer and is due to "no space left on device". Looks like the disk is overflowing.

@jjhursey @gpaulsen Can someone address that problem?

**Comment by rhc54** [comment]
@gpaulsen cleared the disks, so let's complete the verification. I'll then push a commit into @karasevb's pmix PR to complete the repair.

bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/39412e8c069753ebb6a47ef2f3dd6836

**Comment by rhc54** [comment]
@hjelmn I'm not sure I have the attribute test for ```__extension__```correct - could you please take a gander? It's in the pmix_check_attributes.m4 file.

**Comment by gpaulsen** [comment]
Ralph, so why was adding the check for the __extension__ attribute configury not enough?  Is it because these code changes REQUIRED __extension__ attribute, and it was easier to revert than to implement both sides?

**Comment by rhc54** [comment]
I'm not sure what you are asking - the revert is required because the function pointer code isn't acceptable to PGI. The extension configury is desirable because the code otherwise always has the attribute, even if the compiler didn't support it.

**Comment by rhc54** [comment]
Test complete - can reproduce any time.

**Pull request closed without merging**
