### PR TITLE
Pull in the topology early and set cache line size

### PR DESCRIPTION
**Pull request by rhc54**
Init PMIx and get the topology immediately after setting up opal
util as neither of those operations requires any real OPAL support.
This fills in the cache line size before anything else is opened.

Fixes https://github.com/open-mpi/ompi/issues/7937

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7e5536247077c0c661828c6ff54e5017

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ace4c8195ed58b318a11c0ae665d1765

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2b661cf31fd09df25cb26f857f042986

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fc6d895a7d6935dbbf581717c188fe1b

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5c7ba6f9cc77b59a4680c6e8861241b3

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/90b33a1b9cea3a9fe7b57b97c0c9ebf4

**Review by gpaulsen — APPROVED** [review]
Looks good.  Note this PR also includes a prrte submodule pointer update.

**Pull request merged**
