### PR TITLE
Adding latest ConnectX-5 adapter vendor part id to OpenIB device params.

### PR DESCRIPTION
**Pull request by jladd-mlnx**
Signed-off-by: Joshua Ladd <jladd.mlnx@gmail.com>

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by jsquyres** [comment]
@hppritcha I think the hwloc stuff is busted on LANL CI.

**Comment by hppritcha** [comment]
Not sure why this is failing.  It fails in make distcheck in hwloc191:

```
make[2]: Entering directory `/home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/opal/mca/hwloc/hwloc191'
Making distclean in hwloc
make[3]: Entering directory `/home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/opal/mca/hwloc/hwloc191/hwloc'
make[3]: *** No rule to make target `distclean'.  Stop.
make[3]: Leaving directory `/home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/opal/mca/hwloc/hwloc191/hwloc'
make[2]: *** [distclean-recursive] Error 1
make[2]: Leaving directory `/home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/opal/mca/hwloc/hwloc191'
make[1]: *** [distclean-recursive] Error 1
make[1]: Leaving directory `/home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/opal'
make: *** [distclean-recursive] Error 1
```

jenkins is configured to scrub the workspace prior to each build, so its not like old stuff should be hanging around.

**Comment by jsquyres** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
LANL bot is only failing on 1.10.x. Someone might want to check if make distclean abnd friends still work on 1.10.x

**Comment by hppritcha** [comment]
@jsquyres checked this morning and problem is make distcheck``` following a configure requesting use of an external hwloc doesn't work in the 1.10.x branch.

**Comment by ggouaillardet** [comment]
:bot:lanl:retest

**Comment by ggouaillardet** [comment]
@hppritcha i will backport the two needed commits

**Comment by jsquyres** [comment]
@ggouaillardet It probably isn't worth it.  😄

**Comment by ggouaillardet** [comment]
@jsquyres is this because you already did it ? or there will be no ```v1.10.7``` ?

**Comment by rhc54** [comment]
I don't know if there will be a 1.10.7 or not - I think that's what he meant. Nobody has backported anything so far. If it is truly trivial, then fine. I'd just hate to see you spend valuable time on it.

**Comment by ggouaillardet** [comment]
@rhc54 thanks, that was an easy backport and i was already half way.
i just made #3132 for that

**Comment by rhc54** [comment]
bot:lanl:retest

**Pull request merged**
