### PR TITLE
v2.x ppc fixes

### PR DESCRIPTION
**Pull request by hjelmn**
Assembly workarounds for PGI.

### CODE REVIEW

**Comment by jjhursey** [comment]
I just tested this branch and it failed to build with the PGI compiler.

```shell
shell$ uname -m
ppc64le
shell$ pgcc --version

pgcc 16.9-beta linuxpower target on Linuxpower 
The Portland Group - PGI Compilers and Tools
Copyright (c) 2016, NVIDIA CORPORATION.  All rights reserved.
shell$ ./configure --without-x CC=pgcc CXX=pgc++ FC=pgfortran
...
shell$ make
...
make[2]: Entering directory `/tmp/jjh-core/ompi-test/ompi-v2.x-ppc/opal/tools/wrappers'
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_sc_64'
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_ll_64'
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_swap_64'
make[2]: *** [opal_wrapper] Error 2
make[2]: Leaving directory `/tmp/jjh-core/ompi-test/ompi-v2.x-ppc/opal/tools/wrappers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/jjh-core/ompi-test/ompi-v2.x-ppc/opal'
make: *** [all-recursive] Error 1
```

Does this PR depend on PR #2180 ?

**Comment by hjelmn** [comment]
Will pull a commit out of #2180 in case that PR is not accepted. The commit will make the inline assembly work with PGI.

**Comment by hjelmn** [comment]
@jjhursey Should be working now.

**Comment by jjhursey** [comment]
The updated branch builds and passes some basic testing (`make check` and `ring_c`).
Thanks!

**Comment by hppritcha** [comment]
@jsquyres I think this is ready to go.

**Pull request merged**
