### PR TITLE
lanl: help out lanl admins

### PR DESCRIPTION
**Pull request by hppritcha**
LANL admins want platform files and *.conf
files so oblige them.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
bot:retest
weirdness on VM at IU.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
looks like we're having sha updated problems from the IU jenkins.  Ignoring that check. going ahead and merging.

**Pull request merged**
