### PR TITLE
V4.1.x coll/hcoll: svatterv inplace fix

### PR DESCRIPTION
**Pull request by vspetrov**
V4.1.x of #8210

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
@janjust  - please review.

**Review by janjust — APPROVED** [review]

**Comment by janjust** [comment]
@vspetrov same here - signed off missing

**Review by jsquyres — CHANGES_REQUESTED** [review]
Please add the cherry-pick line in the commit message (this is required for all release branch commits that are cherry picked from master).  You can use `git cherry-pick -x ...` to generate the line if you don't want to type it yourself.

**Comment by vspetrov** [comment]
> Please add the cherry-pick line in the commit message (this is required for all release branch commits that are cherry picked from master). You can use `git cherry-pick -x ...` to generate the line if you don't want to type it yourself.

done

**Comment by jsquyres** [comment]
Cool, thanks.  Once the master PR is merged, this one can be eligible to be merged to v4.1.x.

Do you want to make an equivalent PR for v4.0.x?

**Comment by vspetrov** [comment]
> Cool, thanks. Once the master PR is merged, this one can be eligible to be merged to v4.1.x.
> 
> Do you want to make an equivalent PR for v4.0.x?

Not needed since in v4.0.x we don't have the issue (scatterv was only added in coll/hcoll of v4.1.x)

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
Master PR is merged, and the "cherry picked" git commit on this PR matches.  Good to go.

**Pull request merged**
