### PR TITLE
sm dstore: set pmix segment size to proper value

### PR DESCRIPTION
**Pull request by nkogteva**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/393/

**Build Log**
*last 50 lines*

 ```
[...truncated 355 lines...]
+++ '[' '\u@\h \w \n\$' = '\s-\v\$ ' ']'
+++ shopt -q login_shell
++ source /hpc/local/etc/hpc_profile
+++ '[' -f /usr/share/Modules/init/bash ']'
+++ . /usr/share/Modules/init/bash
++++ export -f module
++++ MODULESHOME=/usr/share/Modules
++++ export MODULESHOME
++++ '[' tools/hpc = '' ']'
++++ '[' /usr/share/Modules/modulefiles:/etc/modulefiles:/hpc/local/etc/modulefiles:/opt/mellanox/bupc/2.18.0/modules = '' ']'
++++ '[' 4 -ge 3 ']'
++++ '[' -r /usr/share/Modules/init/bash_completion ']'
++++ . /usr/share/Modules/init/bash_completion
+++++ complete -o default -F _module module
+++ module load tools/hpc
++++ /usr/bin/modulecmd bash load tools/hpc
+++ eval SSH_ASKPASS= ';export' 'SSH_ASKPASS;'
++++ SSH_ASKPASS=
++++ export SSH_ASKPASS
+++ export PATH=/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+++ PATH=/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+++ export 'PS1=\u@\h \w \n\$'
+++ PS1='\u@\h \w \n\$'
++ BLACK='\[\033[0;0m\]'
++ RED='\[\033[0;31m\]'
++ RED_BOLD='\[\033[01;31m\]'
++ BLUE='\[\033[01;94m\]'
++ GREEN='\[\033[0;32m\]'
++ CYAN_BOLD='\[\033[1;36m\]'
++ YELLOW_BOLD='\[\033[1;33m\]'
++ WHITE_BOLD='\[\033[1;37m\]'
+ export PATH=/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ PATH=/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ rm -rf jenkins_scripts
+ git clone https://github.com/mellanox-hpc/jenkins_scripts
Cloning into 'jenkins_scripts'...
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi/commit/e2701bffebec65fc0734b53e333ee6f5349f6c40
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of a828eada98a303105a0a6712afa3821f1719b724 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/393/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 913 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_394/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_394/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_394/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/394/

**Build Log**
*last 50 lines*

 ```
[...truncated 33861 lines...]
malloc debug: Request for 4 zeroed elements of size 0 (grpcomm_rcd.c, 99)
malloc debug: Request for 4 zeroed elements of size 0 (grpcomm_rcd.c, 99)
malloc debug: Request for 4 zeroed elements of size 0 (grpcomm_rcd.c, 99)
malloc debug: Request for 4 zeroed elements of size 0 (grpcomm_rcd.c, 99)
[jenkins01:02737] 1 more process has sent help message help-mpi-btl-openib.txt / default subnet prefix
[jenkins01:02737] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
+ val=10
+ '[' 10 -ne 10 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'Check if the dist mapping policy is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
Check if the dist mapping policy is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/ompi_info --level 9 --param rmaps base
++ grep dist
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test the dist mapping policy in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
test the dist mapping policy in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpicc -o ./mindist_test ./mindist_test.c
gcc: ./mindist_test.c: No such file or directory
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/394/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/394/tap-master-files/cov_stat.tap].
not ok - coverity detected 913 failures in all_394 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_394/output/errors/index.html
not ok - coverity detected 5 failures in oshmem_394 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_394/output/errors/index.html
ok - coverity found no issues for yalla_394
ok - coverity found no issues for mxm_394
not ok - coverity detected 2 failures in fca_394 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_394/output/errors/index.html
ok - coverity found no issues for hcoll_394

TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_394/output/errors/index.html
coverity_for_oshmem	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_394/output/errors/index.html
coverity_for_fca	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_394/output/errors/index.html
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi/commit/e2701bffebec65fc0734b53e333ee6f5349f6c40
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of a828eada98a303105a0a6712afa3821f1719b724 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/394/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 913 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_395/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_395/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_395/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/395/
Test PASSed.

**Pull request merged**
