### PR TITLE
dist: bump version to 3.0.1rc3

### PR DESCRIPTION
**Pull request by bwbarrett**
3.0.1rc2 is tagged; on to rc3.

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi_retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Pull request merged**
