### PR TITLE
[v5.0.x] Adding new oshmem APIs for oshmem v1.5

### PR DESCRIPTION
**Pull request by MamziB**
This PR adds OSHMEM v1.5 spec APIs.

Co-authored-by: Tomislav Janjusic tomislavj@nvidia.com
Co-authored-by: Manjunath Gorentla Venkata manjunath@nvidia.com

Signed-off-by: Mamzi Bayatpour mbayatpour@nvidia.com
(cherry picked from commit 6cb22c8db68d686b70391483b6f3a1968d7fa507)

### CODE REVIEW

**Comment by awlauria** [comment]
ok to test

**Comment by gpaulsen** [comment]
bot:aws:retest

**Comment by gpaulsen** [comment]
Ah, need to wait for #9631 to be merged before commit checker will pass.

**Review by awlauria — APPROVED** [review]

**Comment by janjust** [comment]
@MamziB please update this branch with the coverity fix commit from master

**Pull request merged**
