### PR TITLE
fcoll/two_phase: remove component

### PR DESCRIPTION
**Pull request by edgargabriel**
This component is not used now anymore, vulcan has replaced it in all scenarios.
No point in keeping it around.

Intended for ompi 5.0 onward.

Signed-off-by: Edgar Gabriel <egabriel@central.uh.edu>

### CODE REVIEW

**Review by raafatfeki — COMMENTED** [review]
I think we should also remove two_phase from the selection function in mca/fcoll/base/fcoll_base_file_select.c.

**Comment by edgargabriel** [comment]
@raafatfeki thank you, I completely forgot about that. It is fixed and squashed the two commits.

**Review by raafatfeki — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/606242fe437068526b91eb76e80f6ef9

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c4c945921faca65d1da44caf7f146d0b

**Comment by hjelmn** [comment]
@edgargabriel Yup. That shouldn't have failed compilation though. I will fix the redefinition warning now.

**Comment by hjelmn** [comment]
@edgargabriel #8456 fixes the redefinition warning. Looks like a stale line in atomic_impl.h.

**Comment by edgargabriel** [comment]
@hjelmn excellent, thanks. I will rebase once it hits master

**Comment by jjhursey** [comment]
IBM Ci had an issue over the weekend. Retrying. bot:ibm:retest

**Pull request merged**
