### PR TITLE
v4.1.x: coll/ucc: add reduce scatter block

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**
Adding reduce scatter block to ucc coll component

Signed-off-by: Sergey Lebedev <sergeyle@nvidia.com>
bot:notacherrypick

### CODE REVIEW

**Comment by janjust** [comment]
This is the only reason, we want to move onto v5.0.x but are not ready yet and HPC-X will ship with v4.1.x for at least another release cycle.

**Comment by jsquyres** [comment]
Ok.  This is entirely within your component, so... so be it.

But please move to v5.0.x as soon as you can.  😈

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by janjust** [comment]
Thank you 🙏

**Pull request merged**
