### PR TITLE
pmix: Override some of the pmix env if internal component in use

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/77c743d005e80b49ff9f634ce0400a16

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4f78a112912d78c19c6c04c11e648da7

**Comment by jjhursey** [comment]
The treematch PR build errors are odd and seems unrelated to this PR. I wonder if @bosilca 's merge of PR #3960 didn't introduce a regression into `master`. Until that's resolved I would expect all PRs to fail to pass CI 😞

**Comment by rhc54** [comment]
I'm afraid this isn't quite correct - I'll take a crack at it tonight

**Pull request closed without merging**
