### PR TITLE
Fix the BTL API conversion for the SMCUDA BTL

### PR DESCRIPTION
**Pull request by bosilca**
This is a first step, there are still changes to be made in the OB1 PML.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by hjelmn** [comment]
Maybe we can add an additional context pointer to the receive struct so smcuda can store the frag pointer.

**Comment by bosilca** [comment]
I need to refresh my memory on how this works, it is possible we don't need it.

**Comment by bosilca** [comment]
Short story the smcuda BTL has a bunch of crippled and untested capabilities. I disabled some of it, that I found unreliable. I think this BTL only works in a pt2pt scenario, with the send operation. Not sure it is worth saving.

**Comment by gpaulsen** [comment]
I believe this PR is intended to address the issue raised in https://github.com/open-mpi/ompi/issues/7928

**Comment by hjelmn** [comment]
Probably should add an no build to it for now. Then commit the ob1 fixes. If Nvida wants to fix it they can do so. I would prefer CUDA support in sm.

**Comment by bosilca** [comment]
It is currently working with these changes for all the pt2pt tests I run on it (not many support GPU memory thou). At this point I am mostly concerned about the HWLOC changes.

**Pull request merged**
