### PR TITLE
5.0.x/opal/cuda: Handle stream-ordered allocations and assign primary device 

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
Port of https://github.com/open-mpi/ompi/pull/12835

### CODE REVIEW

**Review by bosilca — APPROVED** [review]

**Comment by Akshay-Venkatesh** [comment]
@janjust I'm guessing [this ](https://github.com/open-mpi/ompi/actions/runs/11169734232/job/31051104735?pr=12843#step:2:826) issue goes way once parent branch has been merged. Is that correct?

**Comment by janjust** [comment]
correct

**Review by janjust — APPROVED** [review]

**Comment by janjust** [comment]
@Akshay-Venkatesh please do another cherry-pick amend, I think after you opened this PR, and then forced push to the main PR, the hash is different now, thus the commit checker will fail.

**Comment by jsquyres** [comment]
Rebased to pick up mpi4py github action fix.

**Pull request merged**
