### PR TITLE
Topic/pr7201 to v40x

### PR DESCRIPTION
**Pull request by hppritcha**

### CODE REVIEW

**Comment by hppritcha** [comment]
@gpaulsen for some reason the opal_asprintf not being defined in @bgoglin 's original commit was causing build to fail for me so had to patch in an include to opal/util/print.h.

Verified test case passes.

**Comment by gpaulsen** [comment]
I'll give it a build / test tomorrow and then merge this after a review.

**Comment by hppritcha** [comment]
@gpaulsen don't merge yet.  this will break backward compatibility with hwloc 1 series.

**Comment by gpaulsen** [comment]
I assume the issues you're referring to are resolved by https://github.com/open-mpi/ompi/pull/7366 ?

**Comment by bgoglin** [comment]
@gpaulsen Yes, they should.

**Comment by gpaulsen** [comment]
Okay, I pushed the commit from https://github.com/open-mpi/ompi/pull/7366 to this branch as well.

**Comment by bgoglin** [comment]
@gpaulsen It's actually the other commit from #7366 that is important: 907ad854b46b42ae7cb1e9c87238691a5cc25e36
The one you took is only for fixing warnings.

**Comment by gpaulsen** [comment]
oops.  Thanks for double checking.  I'll cherry-pick again in the next hour.

**Comment by gpaulsen** [comment]
Ok, please re-review.

Note that I also changed https://github.com/open-mpi/ompi/pull/7356/commits/f136804c453a75763241158d9821ccee4ac4b5f7#diff-f4ec0cf4c6659e1c4af03b7a807378d8R2262 to asprintf.  I think that was correct, but wanted to point it out.

**Comment by hppritcha** [comment]
@gpaulsen looks good and ready to merge

**Pull request merged**
