### PR TITLE
Recovering oshmem functionality

### PR DESCRIPTION
**Pull request by igor-ivanov**
This PR should resolve issues in oshmem observed after https://github.com/open-mpi/ompi/pull/849
@hjelmn, @jladd-mlnx , @alex-mikheev, @miked-mellanox could you review

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
Looks good. Thank you for reworking the proc code.

**Comment by rhc54** [comment]
Is this PR not committed for some reason? Or did someone just forget to do so?

**Comment by miked-mellanox** [comment]
@rhc54 - waiting for @igor-ivanov to comment to my question above before "merge".

**Comment by igor-ivanov** [comment]
@miked-mellanox i modified your notice

**Comment by igor-ivanov** [comment]
@miked-mellanox, @hjelmn I added help message for scoll:mpi and scoll:fca

**Comment by hjelmn** [comment]
Developers are encouraged to always build in debug mode when testing. Debug mode enables assert.

**Comment by igor-ivanov** [comment]
Added assertion

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
