### PR TITLE
v4.0.1: Update to PMIx 3.1.2

### PR DESCRIPTION
**Pull request by rhc54**
Update the OPAL glue configure code to correctly link the opal/pmix3
component to the hwloc used by OMPI instead of defaulting to the
system-level hwloc. Required a corresponding update to the PMIx hwloc
configure code so we treat hwloc the same way we handle libevent in
embedded scenarios. Roll to PMIx v3.1.0 for plugging of memory leaks and
addition of faster PMIx_Get response

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Ref #6267

**Comment by ggouaillardet** [comment]
`PMIx` 3.1.0 was DOA, I will I update and rename this PR shortly with PMIx 3.1.1

**Comment by rhc54** [comment]
Might as well wait for 3.1.2 - will be out this week. Had a report of a problem when direct launching in Slurm (with PMIx support).

**Comment by ggouaillardet** [comment]
ok, thanks for the heads up

**Comment by ggouaillardet** [comment]
The PR was updated with `PMIx 3.1.2`

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
@ggouaillardet could you please review this PR?  thanks.

**Comment by rhc54** [comment]
@hppritcha Looks okay to me

**Pull request merged**
