### PR TITLE
fix: mca_base_env_var mca parameter wasn't handled for native pmi when s...

### PR DESCRIPTION
**Pull request by elenash**
...et in an amca conf file.

Probably this fix is not needed, I saw Ralph is working on new schizo component in orte and it might be a right way to handle it.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/296/
Test PASSed.

**Comment by miked-mellanox** [comment]
@rhc54 - where do you think is a good place?

**Comment by rhc54** [comment]
I'm still trying to understand the problem. The comment implies that MCA params from the environment are indeed processed correctly unless they specifically come from an amca file. Since orterun is the only place those get processed, and those values are supposed to just be placed in the environment like any other, I'm scratching my head as to the problem.

Can someone clarify what problem they are trying to solve?

**Comment by elenash** [comment]
@rhc54 This affects only mca_base_env_list mca variable. The matter is that if it's specified in the command line, it's working. However, if it's specified in amca conf file, this functionality (parse its value and set env variables) is never handled. You made some fixes for this functionality in October and put explicit calls to trigger this handling to pmi_init functions of different pmi components (s1,s2,cray) so there is no such problem when job is running under srun. But pmix_native component didn't call it and the required handling was never called. That's why I just added this call to pmix_native component as it was done in other pmi components.

**Comment by elenash** [comment]
I've just found that this is not the only problem. My fix doesn't work for non-mpi applications because it calls for mca_base_var_process_env_list from mpi_init.
The reason why mca_base_var_process_env_list isn't called from schizo component is that OMPI_MCA_mca_base_env_list variable isn't being set if specified in conf file but not from command line. We can set it in mca_base_var_init and ask not to overwrite the value after registration of mca_base_env_list if it returns non-null value. What do you think?

Something like that:
if (NULL != mca_base_env_list) {
      char *name;
      (void) mca_base_var_env_name ("mca_base_env_list", &name);
      if (NULL != name) {
          opal_setenv(name, mca_base_env_list, false, &environ);
          free(name);
      }
}

**Comment by rhc54** [comment]
The problem here is that your environment forwarding only works for the case where we launch by mpirun - it won't work (at least, not reliably) when the app is launched using srun. Simple reason is that in the srun case, we cannot affect the environment until they call mpi_init. Changing system envars at that point is a _very_ bad idea. I have no idea why this call was added to the slurm/cray pmi components - if you say I did it, I believe you, but it was a bad mistake and should be removed.

This is why mpirun is supposed to pick up those "forwarded" envars and add them to the app's env array so the daemon fork/exec's it with the complete environment already set. It sounds like the real issue here is that orterun isn't picking up the variable from the conf file as it should. This is what needs to be fixed.

**Comment by rhc54** [comment]
Would you please provide me with an appfile that exhibits this problem?

**Comment by miked-mellanox** [comment]
here it goes, copy&paste from jenkins script.

``` shell

cat>$WORKSPACE/env_mpi.c<<EOF
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
int main(int argc, char **argv, char **env)
{
    int i=0;
    char *astr;
    MPI_Init(&argc,&argv);
    astr=env[i];
    while(astr) {
        printf("%s\n",astr);
        astr=env[++i];
    }
   MPI_Finalize();
}
EOF
            $OMPI_HOME/bin/mpicc -o $WORKSPACE/env_mpi $WORKSPACE/env_mpi.c
            echo "mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E" > $WORKSPACE/test_amca.conf
            export XXX_C=3 XXX_D=4 XXX_E=5
            val=$($OMPI_HOME/bin/mpirun -np 2 -am $WORKSPACE/test_amca.conf $WORKSPACE/env_mpi |grep ^XXX_|wc -l)
            if [ $val -ne 10 ]; then
                    exit 1
            fi
```

**Comment by elenash** [comment]
@rhc54 You can also just simply run non-MPI application like 'env' instead of this executable.
echo "mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E" > $WORKSPACE/test_amca.conf
            export XXX_C=3 XXX_D=4 XXX_E=5
            val=$($OMPI_HOME/bin/mpirun -np 2 -am $WORKSPACE/test_amca.conf env |grep ^XXX_|wc -l)
            if [ $val -ne 10 ]; then
                    exit 1
            fi

**Comment by rhc54** [comment]
Best I can tell is that you aren't using the option correctly. The "-am" option just sets a path prefix - it doesn't point to an amca file itself. The param system then looks for a specific filename format in that location.

I'd suggest you look at mca_base_var.c starting at line 332, or ask @hjelmn for help.

**Comment by elenash** [comment]
Looking at mca_base_var.c (332) I see that "mca_base_param_file_prefix" variable (and its synonym -am) are used to specify exact param file with absolute or relative path to allow looking for mca variables not only in files with specific filename format but in user defined files as well. 
@hjelmn Could you, please, comment on this?

**Comment by mellanox-github** [comment]
* Coverity found 1273 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_327/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_327/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_327/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/327/
Test PASSed.

**Pull request closed without merging**
