### PR TITLE
v4.0.x: UCX: added missing UCX libs to UCX detection

### PR DESCRIPTION
**Pull request by hoopoepg**
backport from https://github.com/open-mpi/ompi/pull/5666

Signed-off-by: Sergey Oblomov <sergeyo@mellanox.com>
(cherry picked from commit c982645a464147ab9a0824979530cb74e8d8d4b4)

### CODE REVIEW

**Comment by hoopoepg** [comment]
@gpaulsen incorrect commit message: I cherry-picked both commits, and squashed it into single commit to simplify logging

**Comment by gpaulsen** [comment]
@hoopoepg Ah.  In general we prefer if master -> release branch cherry-picks are one for one (as in number of commits) to help with future git archeology if needed.
I'm worried that this will be quite confusing if this says it's a cherry-pick of one commit, but really it's a cherry-pick and a squash of two commits.
Would you mine please re-doing without the squash for the release branches?

**Comment by hoopoepg** [comment]
re-cherry-pick without squash?
ok, will do bit later

**Comment by gpaulsen** [comment]
okay thanks.

**Comment by hoopoepg** [comment]
@gpaulsen done

**Comment by hoopoepg** [comment]
bot:retest

**Comment by gpaulsen** [comment]
Thanks.

**Pull request merged**
