### PR TITLE
MPI_T Events

### PR DESCRIPTION
**Pull request by cchambreau**
This PR includes Nathan Hjelm's reworking of PERUSE functionality to implement the MPI_T Events API as specified in the MPI 4.0 proposal.  Subsequent minor changes to the MPI_T Events API were made and included here.  The API and an initial set of events were tested against Marc-André Hermann's MEL tracing tool and other test cases.  History, a description of the API and experience with tools can be found in "Enabling callback-driven runtime introspection via MPI_T."

### CODE REVIEW

**Comment by jsquyres** [comment]
Thank you, @cchambreau!

Can you make sure that each of the commits are signed off, [per our contribution guidelines](https://github.com/open-mpi/ompi/blob/master/.github/CONTRIBUTING.md#contributors-declaration)?  Probably before this is merged, we'll want to squash it all down into a smaller number of commits (e.g., I see some "WIP" commits in here, which I'm guessing you'r including for historical context).

**Comment by cchambreau** [comment]
Sure, I will work on getting the commits signed-off.  Yes, I was including Nathan's commits for historical context but can squash various commits for clarity.

**Comment by jjhursey** [comment]
ok to test

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cf9aaba4f89964d805133070b42b3744

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/07cbd52d7910bb6c1d625712e6f2f17d

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/85a9de624980ca96fa860bedb2d2b14c

**Comment by cchambreau** [comment]
Between the unexpected build failures and squash and sign-off changes, I'd like to close this for the time being and create a new PR once I have these issues addressed.

**Comment by jsquyres** [comment]
No worries.  Fun fact about github: the PR just shows the current status of the branch.  I.e., if you change the branch -- even with a force push to replace old commits -- the PR will update to show whatever the current status of the branch is.

**Pull request closed without merging**
