### PR TITLE
Topic/missing files

### PR DESCRIPTION
**Pull request by ggouaillardet**
use a PR to force a fresh build and double check i did not forget any git add

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/87/

**Build Log**
*last 20 lines*

 ```
[...truncated 5205 lines...]
  GENERATE psizeof_f.f90
  CC       pwin_call_errhandler_f.lo
  LN_S     pwin_attach_f.c
  CC       pwin_complete_f.lo
  LN_S     pwin_create_dynamic_f.c
ln: failed to create symbolic link `pwin_attach_f.c': File exists
make[3]: *** [pwin_attach_f.c] Error 1
make[3]: *** Waiting for unfinished jobs....
ln: failed to create symbolic link `pwin_create_dynamic_f.c': File exists
make[3]: *** [pwin_create_dynamic_f.c] Error 1
make[3]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi/mpi/fortran/mpif-h/profile'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi/mpi/fortran/mpif-h'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/ompi'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
GCM: Sending notification to: hpp
Setting status of bf38f82dc20113a4f5f2971f341a8865039db96e to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/87/ and message: Build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
* Coverity found 816 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//586/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/586/
Test PASSed.

**Comment by ggouaillardet** [comment]
@hppritcha can you have a look at this Jenkins failure ?
i was able to build ompi on my workstation from a fresh clone, and mellanox jenkins is fine too.

is this issue related to cray environment or lanl jenkins environment (e.g. do not start from an empty directory) ?
for example, at the very beginning (e.g. autogen.pl) i noticed the following logs that indicates
the source tree is not fresh from github
```
2. Running template-generating scripts

=== ompi/include/mpif-values.pl
creating Fortran header files (with common constants)...
./ompi/include/mpif-handles.h unchanged; not written
./ompi/include/mpif-constants.h unchanged; not written
./ompi/include/mpif-io-handles.h unchanged; not written
./ompi/include/mpif-io-constants.h unchanged; not written
./ompi/mpi/fortran/use-mpi-f08/constants.h unchanged; not written
```

**Comment by hppritcha** [comment]
@ggouaillardet I think you're correct about the lanl behavior.  Thanks for pointing this out.

**Pull request merged**
