### PR TITLE
pml_ucx: fix uninitialized field req_status->_cancelled.

### PR DESCRIPTION
**Pull request by yosefe**
#2327 

Signed-off-by: Yossi Itigin <yosefe@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
@jladd-mlnx @miked-mellanox

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/be5c2b2f10cfad71e66e77c517b03bd9

**Comment by jladd-mlnx** [comment]
👍  @jjhursey are these IBM failures false alarms?

**Comment by jjhursey** [comment]
IBM CI failure due to internal system issue that is still in the process of being resolved this morning. Disregard the IBM CI failures for now.

**Comment by hppritcha** [comment]
@jladd-mlnx you need to sign off in review options

**Pull request merged**
