### PR TITLE
bump mpi version to 3.1

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres @hppritcha This should be merged if we are 3.1 compliant on master. Probably can move it to 2.x immediately after merging here.

**Comment by bosilca** [comment]
True only once open-mpi/ompi#1007 gets in isn't it ?

**Comment by hjelmn** [comment]
I think so. Merge of this will be dependent on #1007.

**Comment by hppritcha** [comment]
I'm going to kill of the LANL-cray XC run.  The hopper homedir file system is really hosed up.  I will be looking at alternatives using /tmp.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
bot:retest

**Pull request merged**
