### PR TITLE
Update the opal_progress_thread API

### PR DESCRIPTION
**Pull request by jsquyres**
@rhc54 Per our discussion this morning, have a look.  The diff might be hard to read; it may be easier to read the final opal_progress_thread.h and .c.

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres would it make sense to simplify a bit further and say that a NULL passed to opal_progress_thread_<foo> APIs equates to "use the default async progress thread"? Then you can static the name and nobody needs to know it.

**Comment by jsquyres** [comment]
@rhc54 Oh ya, that's better.  Let me adjust.

**Comment by jsquyres** [comment]
@rhc54 New commits pushed: NULL now means "The OPAL-wide async progress thread."

**Comment by rhc54** [comment]
:+1:

**Pull request merged**
