### PR TITLE
3rd-party: bump prrte to latest v3.0 branch

### PR DESCRIPTION
**Pull request by wenduwan**
bot:notacherrypick

### CODE REVIEW

**Comment by rhc54** [comment]
Hooray! Please let me know how the AWS CI does. I'd like to ensure we get PRRTE updated for your release, if at all possible.

**Comment by wenduwan** [comment]
AWS CI passed.

I'm running more tests manually to cover more platforms.

**Comment by wenduwan** [comment]
This PR fails on AMD with hwloc 1.11.

```
[ip-172-31-44-98.us-west-2.compute.internal:14273] [[10462,1],79] selected pml ob1, but peer [[10462,1],0] on ip-172-31-44-98 selected pml cm

[ip-172-31-33-160.us-west-2.compute.internal:134572] [[10462,1],350] selected pml ob1, but peer [[10462,1],0] on ip-172-31-44-98 selected pml cm

--------------------------------------------------------------------------

MPI_INIT has failed because at least one MPI process is unreachable

from another.  This *usually* means that an underlying communication

plugin -- such as a BTL or an MTL -- has either not loaded or not

allowed itself to be used.  Your MPI job will now abort.


You may wish to try to narrow down the problem;


 * Check the output of ompi_info to see which BTL/MTL plugins are

   available.

 * Run your application with MPI_THREAD_SINGLE.

 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,

   if using MTL-based communications) to see exactly which

   communication plugins were considered and/or discarded.

```

**Comment by rhc54** [comment]
Nothing to do with PMIx or PRRTE or HWLOC - this is a typical issue in the MPI layer. The procs on the two nodes are making a different PML selection.

**Comment by wenduwan** [comment]
@hpcraink Tommy is on vacation so could you please do a review?

**Comment by hppritcha** [comment]
@wenduwan this solves the old hwloc + ARM issue correct?

**Comment by wenduwan** [comment]
@hppritcha Yes I verified on Intel, AMD and ARM with both new and old hwloc. So far no issues.

**Review by hppritcha — APPROVED** [review]

**Pull request merged**
