### PR TITLE
Switch OMPI from OPAL_CHECK_PACKAGE to OAC_CHECK_PACKAGE

### PR DESCRIPTION
**Pull request by bwbarrett**
Follow-on to https://github.com/open-mpi/ompi/pull/10165, moving the rest of the OMPI tree from OPAL_CHECK_PACKAGE to OAC_CHECK_PACKAGE.  This changes a number of packages, so it would be good if all the vendors can try on their particular systems.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/96dfaedceb5046f9caa02d6443013637

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/61c2104baedeb335e1cd0fa192083d70

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/760cf73107a095579de19de7c000c77b

**Comment by bwbarrett** [comment]
bot:ibm:retest (it's been running for 18 hours; that doesn't seem good)

**Comment by awlauria** [comment]
@bwbarrett is this ready for test/review? Is the last force push just a rebase?

**Comment by bwbarrett** [comment]
Yeah, it's ready for review.  I did fix one bug today with the netlink stuff (man, that was overly complicated), but the last push was just rebasing.

**Review by janjust — APPROVED** [review]
Did basic sanity tests with cuda/ucx/ucc - dso, static builds - and basic runs, seems to check out

**Pull request merged**
