### PR TITLE
Revert "Bump prrte and openpmix to latest release tags"

### PR DESCRIPTION
**Pull request by wenduwan**
This reverts commit f06b1d9562597151e6dfb91f2852599c721c0eca.

The new openpmix breaks compatibility with hwloc 1.11 in debug mode. Temporarily reverting the change.

### CODE REVIEW

**Comment by rhc54** [comment]
Just to be clear: the above statement is inaccurate. "Debug mode" simply exposed the bug - it didn't cause it. Without the `--enable-devel-check`, the code was silently incorrectly compiling against an ancient version of HWLOC.

FWIW: the problem change is in PMIx v4.2.7 and above, so this has been around for awhile - and undetected until we re-enabled the devel-check by default code.

**Comment by wenduwan** [comment]
@rhc54 Thanks a lot for the quick fix. I don't think it's a bug in pmix but unfortunately fixing the bug caused a surprise.

I don't imagine there will be a 4.2.10 release - so I'm inclined to pin pmix to 4.2.8 for the moment.

Also I just realized that openpmix also requires min hwloc 1.11 https://docs.openpmix.org/en/latest/installing-pmix/required-support-libraries.html

**Comment by rhc54** [comment]
It actually is a bug in PMIx, and it goes all the way back to the v4.2.7 release. You'd have to back down to v4.2.6 to get away from it. Only reason you haven't been impacted is because you are ignoring the warnings being emitted during build - and the change in v4.2.9 forced those warnings to be treated as errors (thereby stopping the build) when building from a Git clone.

There will be no 4.2.10 release - ever. You can either default to v4.2.6 or move up to v5.0.2 (soon to be released). Or just don't care about the potential errors and release with v4.2.8 - and let your users live with any resulting problems. I'll warn folks from over here about using OMPI v5.x in that case and recommend building against an external correct PMIx instead.

**Comment by wenduwan** [comment]
@rhc54 Curious is this issue also on pmix 5.0? I'm planning to test out the integration in a PR soon.

**Comment by rhc54** [comment]
No, I just backported the fix to it this morning 😄

**Comment by wenduwan** [comment]
@janjust I opened a PR on main branch to test the latest pmix(master, not 5.0) and found issues. https://github.com/open-mpi/ompi/pull/12342

I think we need to spend some more time to figure out the upgrade path - for the moment I'm inclined to merge this PR and pin us to 4.2.8.

Do you have a different opinion?

**Comment by rhc54** [comment]
The NVIDIA CI failure is a failure in their CI during setup.

The mpi4py failure is (I believe) a known problem that @hppritcha is working on - hard for me to do anything about it when some unknown test simply says "it didn't work".

**Review by janjust — APPROVED** [review]

**Comment by janjust** [comment]
revert so that CI's can pass, then we'll bump

**Comment by wenduwan** [comment]
@rhc54 I ran #12342 through AWS internal CI and it is also broken. I need to look into that.

**Pull request merged**
