### PR TITLE
hwloc: rename the hwloc framework into something else

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs. open-mpi/ompi#2616

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/e3dc606df6bb24606487f4e95e99060e

**Comment by jsquyres** [comment]
I suggest that we might not want to rename anything with the string "xxx" in it.  😳

**Comment by ggouaillardet** [comment]
@jsquyres i cheched　```hwlocxxx``` is not used anywhere, so it will be painless to do a ```sed``` and a few ```git mv``` once we decide the final name for this framework

**Comment by rhc54** [comment]
Please - let's not do this. You are swatting a mosquito with a sledgehammer. There are much simpler solutions to this problem. Will address on the issue.

**Comment by jsquyres** [comment]
We went with #2955 instead of this one.

**Pull request closed without merging**
