### PR TITLE
Provide locality for all procs on node

### PR DESCRIPTION
**Pull request by rhc54**
Refs #6823

### CODE REVIEW

**Comment by hppritcha** [comment]
@hjelmn could you take a look?  If you don't have time we'll get someone else to review.

**Comment by gpaulsen** [comment]
Looking forward to submodules.  It will make PRs like this much easier to review. :)

**Comment by gpaulsen** [comment]
FYI - I just Merged https://github.com/open-mpi/ompi/pull/6885, in case this PR needs to be rebased due to that on v4.0.x

**Comment by rhc54** [comment]
I've updated this to just include the dpm changes - also did the rebase just in case.

**Pull request merged**
