### PR TITLE
io/romio32b1: ROM-IO refresh based on MPICH 3.2b1

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a81cca5cf8e51d1a4da9ec837cef0d75

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f5434267cdd9a3f320e66f3bc0c9da96

**Comment by ggouaillardet** [comment]
i checked the patch for ROM-IO, and what i did is add a bunch of `#ifdef HAVE_MPI_GREQUEST_EXTENSIONS` around what involves MPICH extensions to `MPI_Grequest`.
unsurprisingly, when ompi configury does `#undef HAVE_MPI_GREQUEST_EXTENSIONS`

**Comment by ggouaillardet** [comment]
this is now outdated (and has a few issues), let's follow-up in #4520

**Pull request closed without merging**
