### PR TITLE
rewrite ddt_pack test

### PR DESCRIPTION
**Pull request by ggouaillardet**
so make check works without make install

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 902 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_510/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_510/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_510/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/510/
Test PASSed.

**Comment by jsquyres** [comment]
Sweet; thanks @ggouaillardet

**Comment by bosilca** [comment]
I am not sure that extracting highly specialized code from deep inside an MPI function , and adding it in a test is a legitimate solution to the problem.

**Comment by ggouaillardet** [comment]
I can agree with that.
my concern is this test cannot be moved to the ibm test suite because it calls a few internal functions.
and this test is a good one since it was able to evidence a real issue.
so on top of my head, this was the best / less worst solution.
can you suggest a better way to do achieve similar result ?

**Comment by bosilca** [comment]
As I said in a previous comment, based on the limitation we currently have with "make install" I don't think there is a safe/correct way of doing this test.

**Comment by ggouaillardet** [comment]
an other idea is to export the functions that are needed so this test can be moved to the ibm test suite : 
OMPI_Datatype_pack or MPIX_Datatype_unpack
imho, that is an overkill, but a safe/correct one

**Pull request merged**
