### PR TITLE
oshmem: Remove JAVA support

### PR DESCRIPTION
**Pull request by igor-ivanov**
There is a conclusion to remove java support
(see https://github.com/open-mpi/ompi-release/pull/787)
issue https://github.com/open-mpi/ompi/issues/1170

@jsquyres could you look at this

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by igor-ivanov** [comment]
Mellanox jenkins was aborted for unknown reason
bot:retest

**Comment by hppritcha** [comment]
@nrgraham23 if you have time could you double check this to make sure nothing's broken wrt to building the MPI java bindings?

**Comment by nrgraham23** [comment]
Yes.  Ill check it out later today.

**Comment by hppritcha** [comment]
works for me on nersc systems.  no java oshmem, but mpi java components work nominally.

**Comment by nrgraham23** [comment]
I didn't have any issues either.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
