### PR TITLE
v5.0.x: mpi4py: Run accept/connect tests unconditionally

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Lisandro Dalcin <dalcinl@gmail.com>
(cherry picked from commit 1d29af4ba31703f203ff4b7a02780eff54180f2c)

This is a v5.0.x PR corresponding to main PR #12477

FYI @dalcinl

### CODE REVIEW

**Comment by dalcinl** [comment]
@wenduwan I think there is no matching change in v5.0.x, simply because the issue never hit that branch? @hppritcha is this correct? I'm talking about #12465.

**Comment by wenduwan** [comment]
I think the root cause is also present on v5.0.x but not revealed. Perhaps we should backport the fix more than else.

**Comment by dalcinl** [comment]
Just In case, I'm manually running [this mpi4py branch](https://github.com/mpi4py/mpi4py/tree/testing/ompi-dynproc) against current ompi at v5.0.x.
https://github.com/mpi4py/mpi4py-testing/actions/runs/8790349763/job/24122172405
If all goes well, I will merge the mpi4py branch. Then you can re-run the mpi4py workflow here.

**Comment by dalcinl** [comment]
> I think the root cause is also present on v5.0.x but not revealed. Perhaps we should backport the fix more than else.

You may be definitely right. @hppritcha, your input is much needed here.

**Review by hppritcha — APPROVED** [review]

**Comment by hppritcha** [comment]
@dalcinl are you referring to the cid fix in #12465  ?

I could cherry-pick that (and #12474 ) back to v5.0.x if you think it helps.  I thought it wasn't necessary yet as the commit which revealed this problem - 23df181bd5c1b04def4e8ebbac5fad9476285cde - hasn't been cherry-picked back to v5.0.x.

**Comment by dalcinl** [comment]
> @dalcinl are you referring to the cid fix in #12465 ?

Yes.

>  I thought it wasn't necessary yet as the commit which revealed this problem - 23df181 - hasn't been cherry-picked back to v5.0.x.

IMHO, uses of stack variables like the one fixed by 23df181bd5c1b04def4e8ebbac5fad9476285cde are really hideous bugs that stay dormant until they trigger a disaster (hard to debug memory corruption). Therefore, that fix should already have gone to v5.0.x! Then your work from #12465 would be needed. Would it be to hard to backport everything related to v5.0.x in one shot?

**Comment by hppritcha** [comment]
I'll open an omnibus pr that cherry-picks these commits over in one step.

**Comment by hppritcha** [comment]
well this is kind of a mess.  looks like there were a number of preceeding commits that touched ompi/communicator/comm_cid.c which haven't been ported back to 5.0.x yet.

**Comment by wenduwan** [comment]
@hppritcha Good point. I don't think those commits need backport - is it possible to make the change without cherrypick?

**Comment by hppritcha** [comment]
if we don't need https://github.com/open-mpi/ompi/commit/23df181bd5c1b04def4e8ebbac5fad9476285cde then i can manually patch for https://github.com/open-mpi/ompi/pull/12465.
the former is tied up with a series of commits to support disjoint proc feature.

**Comment by wenduwan** [comment]
That's right we don't need the disjoint flags. Thank you!

**Pull request merged**
