### PR TITLE
[5.0.x] osc/rdma: fix compiler warnings in osc_rdma_accumulate.c

### PR DESCRIPTION
**Pull request by devreal**
Ensure const-correctness of the compare_addr argument to atomic CAS.

### CODE REVIEW

**Comment by janjust** [comment]
@devreal could you add the cherry-pick message for CI to pass?

**Review by janjust — APPROVED** [review]

**Comment by janjust** [comment]
oh I see - the main isn't merged yet, can you merge it please - I'd like to pick this up in v5.0 before rc goes out (hopefully today)

**Comment by wenduwan** [comment]
Change on main https://github.com/open-mpi/ompi/pull/12154

**Review by jsquyres — CHANGES_REQUESTED** [review]
@devreal Can you please add the cherry-pick message to the git commit message?

**Comment by devreal** [comment]
Done, sorry I missed the bot message. Rebased and with proper cherry-pick message now.

**Comment by jsquyres** [comment]
@devreal CI will still fail until https://github.com/open-mpi/ompi/pull/12154 is merged (this prevents us from merging a cherry pick until the commit it is cherry-picking from actually exists up on `main`).  Can you merge your `main` PR?  Thanks!

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
