### PR TITLE
Pr/sharedfp append fix v2.x

### PR DESCRIPTION
**Pull request by edgargabriel**
Fixes a bug reported on the mailing list. ompio did only reposition the individual
file pointer when the file was opened in append mode. Set the shared file
pointer also to point to the end of the file, similarly to the individual
file pointer.

This is the equivalent to commit d3a8d38
on master, cannot be cherry-picked because of differences in the organization
of the ompio files ( usage of mca/common/ompio on master).

### CODE REVIEW

**Comment by jsquyres** [comment]
Just like #2787:

@edgargabriel Got a compile fail:

```
io_ompio_file_open.c: In function 'ompio_io_ompio_file_open':
io_ompio_file_open.c:257:17: error: 'shared_fp_base_module' undeclared (first use in this function)
                 shared_fp_base_module = ompio_fh->f_sharedfp;
                 ^
io_ompio_file_open.c:257:17: note: each undeclared identifier is reported only once for each function it appears in
```

Can you have a look?

**Comment by edgargabriel** [comment]
argh, copy-and-paste error, a line is missing, Will fix.

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Comment by jsquyres** [comment]
Shoot -- @edgargabriel just mentioned on the v2.0.x version (https://github.com/open-mpi/ompi/pull/2787#issuecomment-274885235) that we should have waited merging.  My fault for not seeing that fast enough... ☹️

**Comment by edgargabriel** [comment]
I will provide a separate pr for 2.x for the outstanding item. its probably more important to get it in correctly for 2.0.x right now

**Comment by jsquyres** [comment]
Thanks @edgargabriel

**Pull request merged**
