### PR TITLE
Fix launch_id matching of -hosts

### PR DESCRIPTION
**Pull request by rhc54**
Need to check the entire value instead of just the last N digits. Otherwise, "-host 15" will match nid0015, nid0115, and any other launch id ending in 15

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@marksantcroos Can you please check that this is correct?

**Comment by marksantcroos** [comment]
@rhc54 I see indeed that the previous version matched to loosely, but this additional commit breaks it altogether.

**Comment by rhc54** [comment]
@marksantcroos Yeah, strtol fooled me - it can apparently return either a NULL _or_ a zero-length string, and I wasn't checking for that option. Should be fixed now

**Comment by marksantcroos** [comment]
Thanks, it works now! Will wait for the tests to complete and then do the merge.

**Pull request merged**
