### PR TITLE
4.1.x: Stat portability fix

### PR DESCRIPTION
**Pull request by roblatham00**
Here's a pull request against 4.1.1 but the ROMIO directory structure has changed in master

Refs #9629 

bot:notacherrypick

### CODE REVIEW

**Comment by gpaulsen** [comment]
ok to test

**Review by jsquyres — APPROVED** [review]
Thank you @roblatham00!

**Comment by jsquyres** [comment]
@roblatham00 Sorry to bug, could you `git commit --amend -s` and `git push --force`?  That will add the signed-off-by line, indicating your agreement to our [contributors declaration](https://github.com/open-mpi/ompi/wiki/Administrative-rules#contributors-declaration).

**Comment by jsquyres** [comment]
Thanks @roblatham00

**Pull request merged**
