### PR TITLE
Test for rdmacm hang fix

### PR DESCRIPTION
**Pull request by hjelmn**
This commit is an attempt to fix a hang in finalize of rdmacm.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
Need mellanox to retest but it isn't responding.

**Comment by jsquyres** [comment]
Remember that Jenkins runs are serialized.  You can look and see what the Mellanox Jenkins is doing by looking at http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/.

**Comment by hjelmn** [comment]
@jsquyres It had a red X and didn't turn yellow :-/.

**Comment by jsquyres** [comment]
It's had a busy day.  Give it time.  😄

**Comment by jladd-mlnx** [comment]
@hjelmn This failure is clearly related to the request handling. Another race?

**Comment by hjelmn** [comment]
@jladd-mlnx Yup, fixed in #1835 I think. Not sure how that didn't come up during testing. Jenkins passed all threading tests, @artpol84 didn't report anything, and I didn't see the hang. It now happens 100% of the time. Phase of the moon maybe.

**Comment by hjelmn** [comment]
Going ahead and merging this one. It got further than any other PR has gotten (past rdmacm at least).

**Pull request merged**
