### PR TITLE
Refresh/romio314

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hppritcha could you please review this ?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/487/

**Build Log**
*last 50 lines*

 ```
[...truncated 1186 lines...]
autoreconf: running: /hpc/local/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:39: installing './compile'
configure.ac:26: installing './config.guess'
configure.ac:26: installing './config.sub'
configure.ac:16: installing './install-sh'
configure.ac:16: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'

=== Processing subdir: /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314/romio
--- Found autogen.sh; running...
Running: ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I confdb --force -I confdb
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `confdb'.
libtoolize: copying file `confdb/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `confdb'.
libtoolize: copying file `confdb/libtool.m4'
libtoolize: copying file `confdb/ltoptions.m4'
libtoolize: copying file `confdb/ltsugar.m4'
libtoolize: copying file `confdb/ltversion.m4'
libtoolize: copying file `confdb/lt~obsolete.m4'
autoreconf: running: /hpc/local/bin/autoconf --include=confdb --force
autoreconf: running: /hpc/local/bin/autoheader --include=confdb --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:41: installing 'confdb/ar-lib'
configure.ac:38: installing 'confdb/compile'
configure.ac:43: installing 'confdb/config.guess'
configure.ac:43: installing 'confdb/config.sub'
configure.ac:34: installing 'confdb/install-sh'
configure.ac:34: installing 'confdb/missing'
automake: error: cannot open < Makefile.options: No such file or directory
autoreconf: automake failed with exit status: 1
Command failed: ./autogen.sh
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/8081020434921c0f0247f8d90be587370066f0d9
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of ee048d0ae563440f415f94ff80d3914d2cbc3f63 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/487/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/488/

**Build Log**
*last 50 lines*

 ```
[...truncated 13065 lines...]
libtool: install: /usr/bin/install -c .libs/mca_io_ompio.so /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_io_ompio.so
libtool: install: /usr/bin/install -c .libs/mca_io_ompio.lai /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_io_ompio.la
libtool: finish: PATH="/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin:/sbin" ldconfig -n /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi
----------------------------------------------------------------------
Libraries have been installed in:
   /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/ompio'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/ompio'
Making install in mca/io/romio314
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314'
Making install in romio
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314/romio'
make[4]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314/romio'
make[4]: *** No rule to make target `include/io_romio_conv.h', needed by `all-am'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314/romio'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314/romio'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/io/romio314'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/e8806205b50a61c31a30212da3596c4887a2952b
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of da4f142b5c7730c5383d44744597eaa3381b10b0 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/488/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/489/

**Build Log**
*last 50 lines*

 ```
[...truncated 13065 lines...]
libtool: install: /usr/bin/install -c .libs/mca_io_ompio.so /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib/openmpi/mca_io_ompio.so
libtool: install: /usr/bin/install -c .libs/mca_io_ompio.lai /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib/openmpi/mca_io_ompio.la
libtool: finish: PATH="/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin:/sbin" ldconfig -n /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib/openmpi
----------------------------------------------------------------------
Libraries have been installed in:
   /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib/openmpi

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/ompio'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/ompio'
Making install in mca/io/romio314
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/romio314'
Making install in romio
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/romio314/romio'
make[4]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/romio314/romio'
make[4]: *** No rule to make target `include/io_romio_conv.h', needed by `all-am'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/romio314/romio'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/romio314/romio'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/io/romio314'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/e8806205b50a61c31a30212da3596c4887a2952b
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 3fc3a7f3e37e059eaefae9e3bc8eec8a736c54bc to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/489/ and message: Merged build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
@ggouaillardet  looks like you left out copying io_romio_conv.h from old romio into new romio314/romio/include.  I'm seeing if I can fix this.  Thanks for all the other work here though.

**Comment by ggouaillardet** [comment]
@hppritcha this file (among two others) was incorrectly ignored by some .gitignore
so far, i could not figure out why and i will double check this today

**Comment by mellanox-github** [comment]
* Coverity found 920 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_499/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_499/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_499/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/499/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 903 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_500/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_500/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_500/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/500/
Test PASSed.

**Comment by jsquyres** [comment]
@hppritcha If this looks good to you, I say: merge it!

**Comment by hppritcha** [comment]
This looks good.  Did some MTT testing, but could probably use more.

**Pull request merged**
