### PR TITLE
TEST CI: ompi vs prrte

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ggouaillardet** [comment]
@rhc54 this is a PR to test CI before openpmix/prrte#269 is merged and the submodule index updated.

so far, Open MPI builds correctly, but fail to run the tests because `mpirun` does not correctly grok the --hostfile option
(there is a single physical slot, so a hostfile is needed here so two slots can be used)

**Comment by ggouaillardet** [comment]
I also "aliased" `autogen.pl --no-orte` to `autogen.pl --no-ompi` to make AWS CI happy.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/19cc43e8facdc43fa6589451cded8721

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/47bd4c99e98d853d0710b1d1b8fff30f

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b3977ec5789db72b103910a52af403e0

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b16acbbb4cf41b7bcb10df617e24314e

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
@ggouaillardet Hold off a bit, Gilles - I'm working a parallel path and am a little ahead of you. I'll cross-check my fixes with these and sync us up. Should have something posted later tonight (my time). Will flag you when ready so you can cross-check me.

**Comment by ggouaillardet** [comment]
i was about to go to bed ...
openpmix/prrte#271 is imho ready for merge.

the jenkins failure (minx, arm and cray) are likely caused by their lack of support for git submodules.

note i also "restored" the `autopen.pl --no-orte` option to make CI happy

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ggouaillardet** [comment]
@hppritcha could you please have a look at the error reported by CI on cray ?

at first glance, it looks a bit fishy and hard to troubleshoot without access to a cray


```
  CCLD     libprtemca_common_alps.la
libtool:   error: CURRENT '-L/opt/cray/alps/6.6.56-7.0.1.1_4.30__g2e60a7e4.ari/lib64' must be a nonnegative integer
libtool:   error: '-L/opt/cray/alps/6.6.56-7.0.1.1_4.30__g2e60a7e4.ari/lib64' is not valid version information
make[3]: *** [Makefile:852: libprtemca_common_alps.la] Error 1
```

**Comment by hppritcha** [comment]
hmm... somethings going on with the Cray alps stuff.  This may be legit.

**Comment by hppritcha** [comment]
I suspect prrte commit bb3261e410969982acc478157a5b174939def181 may have broken something.  I can't build prrte now on cray, get the same error.

**Comment by hppritcha** [comment]
I looked at this further, git bisect indicates prrte commit 837c95987eafa8c3ec2599a504bbdc355cce0851 broke things

**Comment by rhc54** [comment]
Please see https://github.com/openpmix/prrte/pull/274 for fix of the alps issue

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ggouaillardet** [comment]
the original PR is up-to-date, so I am closing this one.

**Pull request closed without merging**
