### PR TITLE
Some ompio code cleanup and reoarganization

### PR DESCRIPTION
**Pull request by edgargabriel**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by edgargabriel** [comment]
I don't think the failure in the Mellanox build has anything to do with the code that I changed. I will rerun the tests in a couple of days, didn't plan to merge this commit before the 2.0 release anyway.

**Comment by jladd-mlnx** [comment]
@edgargabriel The failure is due to the ompi request refactor and not a result of your changes.

**Comment by hjelmn** [comment]
@jladd-mlnx Nothing to do with the request refactor. As we have explained Mellanox Jenkins is binding all 16 threads to 2 cores. This causes the test to run extremely slow most of the time. The test is timing out.

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
Seems like a failure with depcomp that was rising sometime in the past.
```
10:10:01 make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
10:10:01 make[2]: warning: -jN forced in submake: disabling jobserver mode.
10:10:01 make[2]: *** No rule to make target `../config/depcomp', needed by `distdir'.  Stop.
10:10:01 make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
10:10:01 make[1]: *** [distdir] Error 1
10:10:01 make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace'
10:10:01 make: *** [dist] Error 2
10:10:01 Make dist failed.  Aborting
```

**Comment by artpol84** [comment]
bot:retest

**Comment by jsquyres** [comment]
@artpol84 Yeah, I don't think we've figured out the root cause on the periodic Mellanox `depcomp` issues.  We discussed this on https://github.com/open-mpi/ompi/pull/1824#issuecomment-229392343 recently, where I noted that sometimes the Mellanox Jenkins complains that something else happened elsewhere on the system, and it fails to copy `depcomp` as part of the Autotools run.  This implies that something else is happening on the server at the same time as the Jenkins build, and is affecting the Autotools run.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by edgargabriel** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by edgargabriel** [comment]
bot:retest

**Pull request merged**
