### PR TITLE
v1.10: Add arguments to rpmbuild script and update README.

### PR DESCRIPTION
**Pull request by martinkontsek**
We have update buildrpm script with external arguments. Script was tested on RedHat 7.3

### CODE REVIEW

**Comment by jsquyres** [comment]
Master equivalent PR is in #2451.

**Comment by rhc54** [comment]
@jsquyres Is this okay to go, given you approved the same for a different branch?

**Comment by jsquyres** [comment]
@rhc54 Heh; you're reminding me that I need to go review @martinkontsek's latest changes to the PR (I've been delinquent in doing so...!).  Let's get this merged to master first, and then worry about the release branches.

**Comment by jsquyres** [comment]
@martinkontsek Can you update this to the latest state from #2451?

**Comment by martinkontsek** [comment]
Hello, @jsquyres I have updated this branch.

**Comment by jsquyres** [comment]
Can you please pull in the fixes from https://github.com/open-mpi/ompi/commit/5ecd271934e1906d66752edc6e28f81ab3509ed3?  Thanks.

**Comment by martinkontsek** [comment]
Changes from 5ecd271 pulled.

**Pull request merged**
