### PR TITLE
Timing2/master

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54  I don't know for sure the status of this code. Will know later today and update you.

**Comment by rhc54** [comment]
Couldn't compile on my Linux box:
```shell
runtime/orte_init.c: In function ‘orte_init’:
runtime/orte_init.c:156:49: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "initializations");
                                                 ^
runtime/orte_init.c:164:43: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "opal_init");
                                           ^
runtime/orte_init.c:175:49: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_locks_init");
                                                 ^
runtime/orte_init.c:183:54: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_register_params");
                                                      ^
runtime/orte_init.c:191:53: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_show_help_init");
                                                     ^
runtime/orte_init.c:196:53: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "opal_error_register");
                                                     ^
runtime/orte_init.c:204:48: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_proc_info");
                                                ^
runtime/orte_init.c:219:65: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
         OPAL_TIMING_ENV_NEXT(tmng, "pmix_server_register_params");
                                                                 ^
runtime/orte_init.c:230:56: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "framework_open(schizo)");
                                                        ^
runtime/orte_init.c:237:57: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_schizo_base_select");
                                                         ^
runtime/orte_init.c:242:74: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
         OPAL_TIMING_ENV_NEXT(tmng, "orte_schizo.check_launch_environment");
                                                                          ^
runtime/orte_init.c:252:53: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "framework_open(ess)");
                                                     ^
runtime/orte_init.c:259:54: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_ess_base_select");
                                                      ^
runtime/orte_init.c:276:47: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "orte_ess.init");
                                               ^
runtime/orte_init.c:298:42: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "finalize");
                                          ^
util/hostfile/hostfile_lex.c: In function ‘orte_util_hostfile__scan_bytes’:
util/hostfile/hostfile_lex.c:2042:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for ( i = 0; i < _yybytes_len; ++i )
                 ^
rmaps_rank_file_lex.c: In function ‘orte_rmaps_rank_file__scan_bytes’:
rmaps_rank_file_lex.c:1813:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for ( i = 0; i < _yybytes_len; ++i )
                 ^
runtime/ompi_mpi_init.c:123:2: warning: #ident is a GCC extension
 #ident OMPI_IDENT_STRING
  ^~~~~
runtime/ompi_mpi_init.c: In function ‘ompi_mpi_init’:
runtime/ompi_mpi_init.c:486:38: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("initialization");
                                      ^
runtime/ompi_mpi_init.c:516:32: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("rte_init");
                                ^
runtime/ompi_mpi_init.c:646:38: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("rte_init-modex");
                                      ^
runtime/ompi_mpi_init.c:665:29: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("modex");
                             ^
runtime/ompi_mpi_init.c:826:37: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("modex-barrier");
                                     ^
runtime/ompi_mpi_init.c:844:31: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("barrier");
                               ^
runtime/ompi_mpi_init.c:953:9: error: ‘OMPI_TIMING_ENV_FINALIZE’ undeclared (first use in this function)
         OMPI_TIMING_ENV_FINALIZE;
         ^~~~~~~~~~~~~~~~~~~~~~~~
runtime/ompi_mpi_init.c:953:9: note: each undeclared identifier is reported only once for each function it appears in
runtime/ompi_mpi_init.c:978:38: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OMPI_TIMING_NEXT("barrier-finish");
```

**Comment by rhc54** [comment]
seems to build and run okay on the Cray with SLURM, though your branch is slightly stale and doesn't include the Cray+slurm enablement commit

**Comment by artpol84** [comment]
@karasevb
Please fix and update. We need this asap!

**Comment by rhc54** [comment]
There is also a missing function down in pmix:

```shell
ompi/lib/libpmix.so.0: undefined symbol: pmix_timing_clocksync_read
```

**Comment by artpol84** [comment]
We aware, PMIx timing is enabled when OMPI is configured with them.
Can you take care of it?

**Comment by rhc54** [comment]
Sure, I can do that - I can also remove the symbol, if you like.

**Comment by karasevb** [comment]
I'm working on it, and plan finish the working variant today.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d46b6e167ce2820953811d75eab3bc9a

**Pull request closed without merging**
