### PR TITLE
Neighbor alltoall fix

### PR DESCRIPTION
**Pull request by bosilca**
This is a replacement for @hjelmn #7063.

### CODE REVIEW

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
@hppritcha @bwbarrett Any idea how this PR is failing CI in configure when @bosilca didn't touch any configury in this PR?

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
@bosilca @hjelmn Is there anything else to do on this PR, or is https://github.com/mpi-forum/mpi-issues/issues/153 now fully fixed?

**Comment by bosilca** [comment]
We are now fully MPI compliant, at least from the neighbor collective point of view. As for what is left to be done: we need to push this into the stable branches.

**Pull request merged**
