### PR TITLE
Revert "fix memory leaks and valgrind errors"

### PR DESCRIPTION
**Pull request by miked-mellanox**
Reverts open-mpi/ompi#520

### CODE REVIEW

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 909 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_442/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_442/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_442/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/442/
Test PASSed.

**Comment by miked-mellanox** [comment]
elena fixed it in  #532

**Pull request closed without merging**
