### PR TITLE
fortran: Correct named constants and a datatype name

### PR DESCRIPTION
**Pull request by kawashima-fj**
This PR consists of four commits and three of them are trivial. The third commit (b5c34c1) may require discussion. Please read my lengthy commit message. This issue was previously discussed in #1753 but I forgot it for a while so the chance to keep the compatibility between master and v2.x was lost. Sorry.

If this PR is pulled to master, I'll make a PR for v2.x but modify the commit to keep the binary compatibility of `MPI_C_COMPLEX` between v2.0.0 and v2.0.x.

@bosilca please review

Closes open-mpi/ompi#1753

### CODE REVIEW

**Comment by bosilca** [comment]
@kawashima-fj Down in the datatype engine I prefer to keep the full name of the type, ompi_mpi_c_float_complex instead of ompi_mpi_c_complex (to keep the consistency with the other similar types such as ompi_mpi_c_double_complex).

**Comment by kawashima-fj** [comment]
@bosilca Do you mean `MPI_C_COMPLEX` in `mpi.h` and `mpif.h` should point `ompi_mpi_c_float_complex` (C) and its index (Fortran) instead of `ompi_mpi_c_complex`? In other words,  make `ompi_mpi_c_float_complex` the canonical name and make `ompi_mpi_c_complex` the alias of it (or delete `ompi_mpi_c_complex`) in Open MPI implementation? If this understanding is correct, I'll update the PR.

**Comment by bosilca** [comment]
@kawashima-fj this is indeed what I meant. thanks.

**Comment by kawashima-fj** [comment]
@bosilca I updated the PR. I didn't delete `ompi_mpi_c_complex` this time because it is used some other places especially `ompi_datatype_basicDatatypes` array.

**Comment by bosilca** [comment]
👍

**Pull request merged**
