### PR TITLE
Cleanup the ras simulator capability, and the relay route thru grpcomm

### PR DESCRIPTION
**Pull request by rhc54**
direct. Don't resend wireup info if nothing has changed

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@hjelmn

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/784538c8a90ca5a0806643d5f53e0d83

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ccfbb993a0ffe00f5ac68580142ecfad

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/bf1c1a02bbb403dae12418b4b2cedb15

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/369343b3ca36b6e925e8b7630f8f0ed9

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/0b4b497daf2c8609b364866d831fe0cb

**Comment by rhc54** [comment]
@jjhursey I have search everywhere in the IBM CI and cannot find an error. Could you please point me at it?

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/69592050e6abced2faf23da99b7d86a5

**Comment by jjhursey** [comment]
@rhc54 The Gist preview might only be showing the top 1/2 of the output file. You'll need to click on the `view the full file` link in the gist to get the full message.

It looks like the build is fine, but when the hello_c program is run then we get an error message or segv depending on the CI Test:
 * [GNU Compiler Log](https://gist.githubusercontent.com/ibm-ompi/369343b3ca36b6e925e8b7630f8f0ed9/raw/bb8c37653fed1b44d64417c9323d2a1d77c9ffb4/output.txt)
```
timeout --preserve-status -k 22s 20s mpirun -np 2 -mca btl tcp,vader,sm,self hello_c
[p10a602:134789] [[3879,0],0] ORTE_ERROR_LOG: Not found in file base/odls_base_default_fns.c at line 266
```
 * [PGI Compiler Log](https://gist.githubusercontent.com/ibm-ompi/69592050e6abced2faf23da99b7d86a5/raw/ac72e66c54ba5f2faa1695a9648fac610c4bb043/output.txt)
```
+ timeout --preserve-status -k 22s 20s mpirun -np 2 -mca btl tcp,vader,sm,self hello_c
[p10a602:65496] *** Process received signal ***
[p10a602:65496] Signal: Segmentation fault (11)
[p10a602:65496] Signal code: Address not mapped (1)
[p10a602:65496] Failing at address: (nil)
[p10a602:65496] [ 0] [0x3fffb4700478]
[p10a602:65496] [ 1] /lib/powerpc64le-linux-gnu/libc.so.6(+0xaf0e8)[0x3fffb412f0e8]
[p10a602:65496] [ 2] [0x3]
[p10a602:65496] [ 3] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-pal.so.0(opal_argv_append_nosize+0xa4)[0x3fffb451d73c]
[p10a602:65496] [ 4] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-rte.so.0(orte_dt_unpack_job+0x150)[0x3fffb462b0e8]
[p10a602:65496] [ 5] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-pal.so.0(opal_dss_unpack_buffer+0xa0)[0x3fffb44f94d8]
[p10a602:65496] [ 6] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-pal.so.0(opal_dss_unpack+0x10c)[0x3fffb44f93d4]
[p10a602:65496] [ 7] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-rte.so.0(orte_odls_base_default_construct_child_list+0x350)[0x3fffb46752d8]
[p10a602:65496] [ 8] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/openmpi/mca_odls_default.so(+0x20b8)[0x3fffb00720b8]
[p10a602:65496] [ 9] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-rte.so.0(orte_daemon_recv+0x1bc)[0x3fffb464aac4]
[p10a602:65496] [10] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-rte.so.0(orte_rml_base_process_msg+0x17c)[0x3fffb4694dc4]
[p10a602:65496] [11] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-pal.so.0(+0x8c1b8)[0x3fffb453c1b8]
[p10a602:65496] [12] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-pal.so.0(+0x8c5bc)[0x3fffb453c5bc]
[p10a602:65496] [13] /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master_pgi/ompi-install/lib/libopen-pal.so.0(opal_libevent2022_event_base_loop+0x394)[0x3fffb453d14c]
[p10a602:65496] [14] mpirun[0x10001714]
[p10a602:65496] [15] mpirun[0x1000109c]
[p10a602:65496] [16] /lib/powerpc64le-linux-gnu/libc.so.6(+0x24d00)[0x3fffb40a4d00]
[p10a602:65496] [17] /lib/powerpc64le-linux-gnu/libc.so.6(__libc_start_main+0xc8)[0x3fffb40a4ef8]
[p10a602:65496] *** End of error message ***
timeout: the monitored command dumped core
./run-ci-test.sh: line 101: 65495 Segmentation fault      timeout --preserve-status -k 22s 20s mpirun -np 2 $OMPI_RUNTIME_ARGS hello_c
```

**Comment by rhc54** [comment]
frustration...

**Pull request merged**
