### PR TITLE
Cherry-pick regx framework

### PR DESCRIPTION
**Pull request by sam6258**

### CODE REVIEW

**Comment by jjhursey** [comment]
add to whitelist

**Comment by jjhursey** [comment]
On `master`, this started as a bug fix for machines with multiple sets of digits (e.g., `foo123bar567bip42`) where the nidmap was doing the wrong thing resulting in hangs above the radix value of the routed tree. That is why it is labeled as a "bug" here.

To make `v3.1.x` more in-line with `master` (and thus extend it's life) we are bringing the whole set of commits from `master` which move `orte/util/nidmap.h` into a framework in `orte/mca/regx`.

**Comment by sam6258** [comment]
Ah, great! Thanks for the review Gilles, as I'm new to the ompi community. Will make changes in the morning.

**Comment by jjhursey** [comment]
@jsquyres I thought we had to sign off all of the cherry picks even if we didn't change them for legal reasons. Scott is 'contributing' the cherry pick, but no code content. But the PR merge will have his name on it...

I'm fine with either signing or not, just want to be clear on that point.

**Comment by bwbarrett** [comment]
@jjhursey we have not been picky about a clean cherry pick.  Modify the code, you should sign off.

**Comment by bwbarrett** [comment]
@ggouaillardet can you update your review?

**Comment by ggouaillardet** [comment]
It seems commit 51440a3aa0b107dd1f0809fb3b996488e91e88f7 was a backport instead of a straightforward cherry-pick, so the commit message should reflect that.

fwiw, i manually replace `(cherry picked from commit ...)` with `(back-ported from commit ...)`.
i also get rid of the list of conflict files, but this is a personal preference and not a rule.

if i correctly understand @bwbarrett previous comment, this back port commit should be signed-off too.

**Comment by sam6258** [comment]
@ggouaillardet I added the message for "back-ported from" and signed off on the changes as well.

**Comment by jjhursey** [comment]
I think this is good to go now. Thanks!

**Comment by jjhursey** [comment]
@rhc54 @ggouaillardet Any reservations about putting the regx framework in the v3.1.x series?
If not, then I think this PR is ready to go.

**Comment by ggouaillardet** [comment]
I already approved this PR, everything is fine for me.

**Comment by rhc54** [comment]
no issues from me

**Comment by jjhursey** [comment]
@bwbarrett @hppritcha This PR is good to go.

**Comment by bwbarrett** [comment]
Not sure why the commit email checker is hung up, but manually verified all the patches and they look ok.  Merging anyway.

**Comment by jsquyres** [comment]
I could not figure out how to kick the email checker (I actually even re-delivered the webhook that I think corresponded to it, and it delivered a "success" reply back to Github... so I don't know why it kept showing as not having received a reply).  Shrug.  So I temporarily disabled the "required" part of this hook, will merge, and then will reset it back to being required.

**Pull request merged**
