### PR TITLE
configury: support flang-new

### PR DESCRIPTION
**Pull request by ggouaillardet**
patch auto-generated configure in order to support flang-new

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by lrbison** [comment]
Needs backport to v5.0.x too

**Comment by hppritcha** [comment]
any reason not to merge this?

**Comment by jsquyres** [comment]
@hppritcha I approved this months ago; I was good with it then, and I'm good with it now.

**Comment by jsquyres** [comment]
@hppritcha Can you open the cherry pick to v5.0.x?

**Comment by adegomme** [comment]
Not exactly related, but a bit, so I'm not opening a new ticket right now (it might be on the flang side):

I was trying to build openmpi with this patch and latest flang-new, but I still see issues, including one which seems quite recent (only with flang-new 18 recent enough to handle TKR ignore flags, apparently, as it worked before summer )

in the logs : 
checking for Fortran compiler support of !DIR$ IGNORE_TKR... yes

... and then in the end
```
make[2]: Entering directory '/var/tmp/ompi/ompi/mpi/fortran/use-mpi-ignore-tkr'
  GENERATE mpi-ignore-tkr-sizeof.h
  GENERATE mpi-ignore-tkr-sizeof.f90
  PPFC     mpi-ignore-tkr.lo
  FC       mpi-ignore-tkr-sizeof.lo
  FCLD     libmpi_usempi_ignore_tkr.la
flang-new: error: unknown argument: '-shared'
make[2]: *** [Makefile:1911: libmpi_usempi_ignore_tkr.la] Error 1
make[2]: Leaving directory '/var/tmp/ompi/ompi/mpi/fortran/use-mpi-ignore-tkr'```

Has the build been tested recently with this patch and a current version of llvm/flang-new ? 
I don't have many ideas on how to fix it, I guess -Wl,-shared should be the flag instead, but I don't know at what point it is generated (libtool issue?).

**Comment by jsquyres** [comment]
@adegomme I don't know if anyone is regularly testing with flang-new 18.  If there is an actual issue, it would be good to open a new issue so that we can track it properly.  Thanks!

**Comment by kawashima-fj** [comment]
> I was trying to build openmpi with this patch and latest flang-new, but I still see issues, including one which seems quite recent (only with flang-new 18 recent enough to handle TKR ignore flags, apparently, as it worked before summer )

@adegomme It's a problem in the Flang side. Flang reorganized its option handling code in the `main` branch in August and the `-shared` option (and some other options) is unavailable now. [The community is about to fix the problem](https://github.com/llvm/llvm-project/pull/66702) and it will be available again in official Flang 18 release hopefully.

**Comment by adegomme** [comment]
oh, great, thanks! I missed it when I looked. Sorry for the noise, then.

**Pull request merged**
