### PR TITLE
ompi: disable functions removed from MPI-3.0 by default

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds a new configure option: --enable-mpi1-compat. Without
this option we will no longer provide APIs, typedefs, and defines that
were removed from the standard in MPI-3.0. This option will exist for
one major release (Open MPI v4.x.x) and then the option and associated
code will be removed in Open MPI v5.x.x. Open MPI has already
internally prepared for this change. Please prepare your codes
accordingly.
    
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7173676ce0449dd15d4d2dd1de736707

**Comment by hjelmn** [comment]
bot:ompi:retest

**Comment by hjelmn** [comment]
Hah, failing on --enable-mpi-cxx. Won't bother fixing as that PR will probably go in before this one.

**Comment by hjelmn** [comment]
Looks like this is the way forward. Merging.

**Pull request merged**
