### PR TITLE
Fix support for external PMIx v2.0 with legacy PMIx_Get()

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by jjhursey** [comment]
Ref Issue #5048
I would suggest getting this into v3.1.0 if the window is still open.

**Comment by artpol84** [comment]
@ggouaillardet Can you explain more about the problem?
We are using OMPI v3.1 with PMIx 1.2.5 without problems.

**Comment by artpol84** [comment]
Ok, I didn't noticed the link to the issue, will go through.

**Comment by artpol84** [comment]
Probably for us it was Slurm direct launch and we were not using PLM component.
@ggouaillardet @kawashima-fj @jjhursey is it correct to say that if using direct launch this problem is not exist?

**Comment by hjelmn** [comment]
@ggouaillardet This doesn't seem to quite fix the issue. I patched master with the parts of this that are for some reason not in master and it still fails with a not found error. This appears to be happening because the daemon namespace is unknown when storing locally. I can get it to run on a single node by making pmix1_store_local always return success but that probably isn't the right fix.

**Comment by ggouaillardet** [comment]
@hjelmn i fixed the title which was misleading.

This fix is necessary for PMIx < v2.1, and though it is sufficient for PMIx v2.0, some more changes are needed for PMIx v1.2.
This is discussed in #5048 

Open MPI v3.0.x does things differently and hence support PMIx v1.2

> I patched master with the parts of this that are for some reason not in master and it still fails with a not found error.

As far as I am concerned, `master` and `v3.1.x` with this PR do things similar, so I am puzzled with your previous statement. Did it apply to `v3.1.x` or `v3.0.x` ?
In the latter case, some code was removed from `master`, and that was backported to `v3.1.x` but not `v3.0.x`. In the former case, can you please share your patch ?

**Comment by hjelmn** [comment]
@ggouaillardet I guess my patch just pulled in what was removed from master. The only other change was to always return OPAL_SUCCESS. That somehow worked. Probably because it was on a single node.

From what I can tell the only thing that isn't working with PMIx v1.2.3-v1.2.5 (after the changes you have already made to master) is storing the daemon uri. This is due to the non-existent namespace for the daemon jobid.

**Comment by hjelmn** [comment]
@bwbarrett This plus the fix headed to master in #5103 should be all we need to get v3.1.0 out the door.

**Pull request merged**
