### PR TITLE
Sync to PMIx v2.1.2rc

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/36fa9103b05dd800230e8ab9da4c78ae

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/36d120a2bf28443196c5d4bf6a8a22c3

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b39d9bde380974c5c5db9ac22421c4c2

**Comment by rhc54** [comment]
@bwbarrett This is required to restore forward cross-version compatibility and to avoid a potential thread deadlock during abort

**Pull request merged**
