### PR TITLE
fix libfabric user intent

### PR DESCRIPTION
**Pull request by jsquyres**
@rhc54 This should fix the problem you found.

Also: minor tweaks to the OPAL summary output.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@hppritcha That looks like some kind of local failure on the LANL-Cray XC jenkins -- can you have a look?

**Comment by hppritcha** [comment]
more /tmp problems on nersc login nodes.  I think its fixed now.
bot:retest

**Comment by rhc54** [comment]
:+1: 

Thanks!

**Pull request merged**
