### PR TITLE
Correct typo to properly check for PMIx 4

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b2fbdb522bb01664aa43ee11e6dfea67

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/586fc88c5967ab1db2f58723b29016b0

**Comment by rhc54** [comment]
Sigh - looks like the OMPI PR checker aborted the other builds (including the ARM one I was trying to test) when one of them failed, so no diagnostic output from the platform of interest.

I give up - someone else is going to have to try and figure out what is wrong with the ARM CI.

**Comment by rhc54** [comment]
Updated atomics (which includes some ARM updates) to see if that is the problem - it's the only area of the code that has something ARM-specific.

**Comment by rhc54** [comment]
Looks like it was an atomics issue!

**Pull request merged**
