### PR TITLE
v3.0.x: OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
Equivalent of https://github.com/open-mpi/ompi/pull/7175 for 3.0.x

### CODE REVIEW

**Comment by hppritcha** [comment]
mellanox doesn't like this

**Comment by Akshay-Venkatesh** [comment]
@hppritcha Is it possible to get a log of the error? I'm guessing you don't have access already. Can you tag a relevant Mellanox dev? Thanks

**Comment by jsquyres** [comment]
@Akshay-Venkatesh Just click the "Details" link next to the failed Mellanox CI.

**Comment by Akshay-Venkatesh** [comment]
@jsquyres I just get an "Unable to connect" error on the details page here: http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/10614/

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 @yosefe Is something wrong with Mellanox's Jenkins?

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 @yosefe We are getting `GATEWAY_TIMEOUT, bgate.mellanox.com` and can't see the details of the CI failure.  Please help.  Thanks.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
@jsquyres I’m checking

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@Akshay-Venkatesh You need to get someone to review a PR to release branches.

**Comment by Akshay-Venkatesh** [comment]
@artpol84 can you provide a review please?

**Comment by Akshay-Venkatesh** [comment]
@gpaulsen Can you provide a review?

**Comment by Akshay-Venkatesh** [comment]
@jsquyres @gpaulsen Finally getting a chance to look at this. 

I'm most likely missing something but I never cherry-picked a commit from master to generate this PR. As with this PR, I had a patch that I had applied to ToT and generated PRs for each of 3.0.x, [3.1.x](https://github.com/open-mpi/ompi/pull/7179), and [4.0.x](https://github.com/open-mpi/ompi/pull/7175). 

When we merged [4.0.x](https://github.com/open-mpi/ompi/pull/7175) PR, we brought up why we didn't apply the changes to master first and then cherry-pick for each of 3.*, and 4.0.x branches but the reason for that was because `openib` btl was wiped out in master. 

With all this said, what should be the next step for this PR and for [3.1.x](https://github.com/open-mpi/ompi/pull/7179) ? Thanks in advance

**Comment by jsquyres** [comment]
@Akshay-Venkatesh Oh _right_.  Given that we keep asking this question (apparently over and over again), can you edit the commit message and say _why_ this is not a cherry-pick from master?  I.e., this commit was made after `openib` was removed from master, but it is still addressing a need on this particular release branch blah blah blah...

**Comment by Akshay-Venkatesh** [comment]
> @Akshay-Venkatesh Oh _right_. Given that we keep asking this question (apparently over and over again), can you edit the commit message and say _why_ this is not a cherry-pick from master? I.e., this commit was made after `openib` was removed from master, but it is still addressing a need on this particular release branch blah blah blah...

Sure @jsquyres I'll amend git commit message to include the details.

**Comment by Akshay-Venkatesh** [comment]
@jsquyres @gpaulsen I went ahead created a new PR because I didn't want to force push. I'll close this and 3.1.x PR once I get the green signal on the new PRs https://github.com/open-mpi/ompi/pull/7278 and https://github.com/open-mpi/ompi/pull/7277

**Comment by jsquyres** [comment]
Don't worry about force pushing -- we force push on PR's all the time.

Just to be clear: force pushing on a PR branch is just about the _only_ socially-acceptable place to do a git force push.  😄 

git-push-force

**Comment by Akshay-Venkatesh** [comment]
> 
> 
> Don't worry about force pushing -- we force push on PR's all the time.
> 
> Just to be clear: force pushing on a PR branch is just about the _only_ socially-acceptable place to do a git force push. 😄
> 
> git-push-force

Done :)

**Pull request merged**
