### PR TITLE
smsc/accelerator: add new smsc component

### PR DESCRIPTION
**Pull request by edgargabriel**
- add smsc component based on the accelerator API IPC functionality.
- adjust smsc base selection logic to enable a pass-through mechanism with the new smsc/accelerator component

### CODE REVIEW

**Comment by wenduwan** [comment]
@edgargabriel Could you explain how this change can be tested? We can run it through AWS CI.

**Comment by edgargabriel** [comment]
@wenduwan Assuming that you do not have AMD GPUs, I think the prerequisite for testing this PR would require the accelerator/cuda component to implement the missing IPC functionality.

**Comment by bosilca** [comment]
Give me a week or so to add support for CUDA.

**Comment by edgargabriel** [comment]
btw. I have no clue why the continuous-integration/jenkins/pr-head is marked as 'failed'. If you click on Details, all tests seemed to have passed correctly

**Comment by wenduwan** [comment]
distcheck failed
```
make[5]: Entering directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468/opal/mca/smsc/accelerator'

make  distdir-am

make[6]: Entering directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468/opal/mca/smsc/accelerator'

make[6]: *** No rule to make target 'post_configure.sh', needed by 'distdir-am'.  Stop.

make[6]: Leaving directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468/opal/mca/smsc/accelerator'

make[5]: *** [Makefile:1585: distdir] Error 2

make[5]: Leaving directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468/opal/mca/smsc/accelerator'

make[4]: *** [Makefile:2029: distdir-am] Error 1

make[4]: Leaving directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468/opal'

make[3]: *** [Makefile:2025: distdir] Error 2

make[3]: Leaving directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468/opal'

make[2]: *** [Makefile:1604: distdir-am] Error 1

make[2]: Leaving directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468'

make[1]: *** [Makefile:1598: distdir] Error 2

make[1]: Leaving directory '/home/ubuntu/workspace/pen-mpi.pull_request-v2_PR-12468'

make: *** [Makefile:1702: dist] Error 2

script returned exit code 2
```

**Comment by wenduwan** [comment]
I find jenkins pipeline graph visually misleading. The pipeline steps page shows the failure
https://jenkins.open-mpi.org/jenkins/job/open-mpi.pull_request-v2/job/PR-12468/7/flowGraphTable/

**Comment by edgargabriel** [comment]
Will create a new PR to avoid confusion

**Pull request closed without merging**
