### PR TITLE
ompio: fix misc memory leaks

### PR DESCRIPTION
**Pull request by ggouaillardet**
This is a test PR
(i just need the coverity log indeed ...)

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 867 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_544/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_544/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_544/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/544/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 866 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_545/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_545/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_545/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/545/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 856 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_546/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_546/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_546/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/546/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 854 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_547/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_547/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_547/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/547/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/4/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/93/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 788 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//590/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/590/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/6/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/95/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 785 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//591/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/591/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/15/

**Build Log**
*last 20 lines*

 ```
[...truncated 9261 lines...]
  CC       output.lo
  CC       path.lo
../../../../opal/util/os_dirpath.c: In function 'opal_os_dirpath_create':
../../../../opal/util/os_dirpath.c:114: error: 'EEXIST' undeclared (first use in this function)
../../../../opal/util/os_dirpath.c:114: error: (Each undeclared identifier is reported only once
../../../../opal/util/os_dirpath.c:114: error: for each function it appears in.)
../../../../opal/util/os_dirpath.c:114: error: expected statement before ')' token
make[4]: *** [os_dirpath.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal/util'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal/util'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub'
make: *** [distcheck] Error 1
Build step 'Execute shell' marked build as failure
Setting status of 4323ee5879a3b9a4013d3a0b01b5b62b2aa31be0 to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/15/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/104/

**Build Log**
*last 20 lines*

 ```
[...truncated 4327 lines...]
make  all-am
make[3]: Entering directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/include'
make[3]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/include'
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/include'
Making all in asm
make[2]: Entering directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/asm'
  CC       asm.lo
  CPPAS    atomic-asm.lo
/bin/sh: ../../config/depcomp: No such file or directory
make[2]: *** [asm.lo] Error 127
make[2]: *** Waiting for unfinished jobs....
/bin/sh: ../../config/depcomp: No such file or directory
make[2]: *** [atomic-asm.lo] Error 127
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/asm'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
Setting status of 4323ee5879a3b9a4013d3a0b01b5b62b2aa31be0 to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/104/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/16/

**Build Log**
*last 20 lines*

 ```
[...truncated 9261 lines...]
  CC       output.lo
  CC       path.lo
../../../../opal/util/os_dirpath.c: In function 'opal_os_dirpath_create':
../../../../opal/util/os_dirpath.c:117: error: 'EEXIST' undeclared (first use in this function)
../../../../opal/util/os_dirpath.c:117: error: (Each undeclared identifier is reported only once
../../../../opal/util/os_dirpath.c:117: error: for each function it appears in.)
../../../../opal/util/os_dirpath.c:117: error: expected statement before ')' token
make[4]: *** [os_dirpath.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal/util'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal/util'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub'
make: *** [distcheck] Error 1
Build step 'Execute shell' marked build as failure
Setting status of cca933f5bde194eef5c70a561d4f08e46fe1d19c to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/16/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/105/

**Build Log**
*last 20 lines*

 ```
[...truncated 4408 lines...]
  CC       output.lo
os_dirpath.c: In function 'opal_os_dirpath_create':
os_dirpath.c:117:26: error: 'EEXIST' undeclared (first use in this function)
         if ((0 != ret && EEXIST != ret) || 0 != stat(tmp, &buf))) { 
                          ^
os_dirpath.c:117:26: note: each undeclared identifier is reported only once for each function it appears in
os_dirpath.c:117:65: error: expected statement before ')' token
         if ((0 != ret && EEXIST != ret) || 0 != stat(tmp, &buf))) { 
                                                                 ^
make[3]: *** [os_dirpath.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/util'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal/util'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/opal'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
Setting status of cca933f5bde194eef5c70a561d4f08e46fe1d19c to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/105/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/17/

**Build Log**
*last 20 lines*

 ```
[...truncated 9258 lines...]
  CC       opal_pty.lo
  CC       os_dirpath.lo
  CC       os_path.lo
  CC       output.lo
  CC       path.lo
../../../../opal/util/os_dirpath.c: In function 'opal_os_dirpath_create':
../../../../opal/util/os_dirpath.c:118: error: expected statement before ')' token
make[4]: *** [os_dirpath.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal/util'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal/util'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub/opal'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/jenkins/workspace/ompi_master_pr_distcheck/openmpi-gitclone/_build/sub'
make: *** [distcheck] Error 1
Build step 'Execute shell' marked build as failure
Setting status of a610b759a8553541d325b7105213e55d979d549a to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/17/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/106/

**Build Log**
*last 20 lines*

 ```
[...truncated 935 lines...]
configure: WARNING: -Wall -Wundef -Wno-long-long has been added to CXXFLAGS (--enable-picky)
checking if g++ supports -finline-functions... yes
configure: WARNING:  -finline-functions has been added to CXXFLAGS
checking if C and C++ are link compatible... mv: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Error 23
./configure: line 4679: /usr/bin/sed: Too many open files in system
no
**********************************************************************
* It appears that your C++ compiler is unable to link against object
* files created by your C compiler.  This generally indicates either
* a conflict between the options specified in CFLAGS and CXXFLAGS
* or a problem with the local compiler installation.  More
* information (including exactly what command was given to the
* compilers and what error resulted when the commands were executed) is
* available in the config.log file in this directory.
**********************************************************************
configure: error: C and C++ compilers are not link compatible.  Can not continue.
sed: error while loading shared libraries: libc.so.6: cannot open shared object file: Error 23
Build step 'Execute shell' marked build as failure
Setting status of a610b759a8553541d325b7105213e55d979d549a to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/106/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/18/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/107/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 783 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//598/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/19/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/108/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/20/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 781 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//599/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 781 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//600/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/109/
Test PASSed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 780 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//602/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/22/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/111/
Test PASSed.

**Comment by jsquyres** [comment]
@miked-mellanox What failed in the Mellanox jenkins run?

**Comment by rhc54** [comment]
??? I see passes all around - nothing failed

**Comment by jsquyres** [comment]
@rhc54 If you look at the web interface, the status on the PR says that the Mellanox build failed.

**Comment by miked-mellanox** [comment]
from the console log:

``` shell
20:57:43 + timeout -s SIGKILL 10m mpirun -np 8 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-3/ompi_install1/examples/hello_c
20:57:43 [jenkins01:26474] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp) of (/tmp/openmpi-sessions-2848@jenkins01_0/51592/0/0), mkdir failed [-1]
20:57:43 [jenkins01:26474] [[51592,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 110
20:57:43 [jenkins01:26474] [[51592,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 386
20:57:43 [jenkins01:26474] [[51592,0],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 319
20:57:43 --------------------------------------------------------------------------

```

**Comment by jsquyres** [comment]
Is something wrong on your Jenkins build machine -- e.g., is `/tmp` missing?  I note that it didn't put a comment here on github indicating failure, either.

**Comment by miked-mellanox** [comment]
* I get same error when run it manually
* /tmp seems fine, why orte tries to create /tmp? 

``` shell
$df -hl /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       9.7G  191M  9.0G   3% /tmp

$cd /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-3/ompi_install1/bin
jenkins@jenkins01 /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-3/ompi_install1/bin
$./mpirun -np 8 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-3/ompi_install1/examples/hello_c
[jenkins01:15597] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp) of (/tmp/openmpi-sessions-2848@jenkins01_0/37391/0/0), mkdir failed [-1]
[jenkins01:15597] [[37391,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 110
[jenkins01:15597] [[37391,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 386
[jenkins01:15597] [[37391,0],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 319
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
jenkins@jenkins01 /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-3/ompi_install1/bin

```

**Comment by miked-mellanox** [comment]
re jenkins comment - new jenkins github plugins is buggy, we reverted to latest stable and comment should work now

**Comment by rhc54** [comment]
@jsquyres I see what happened - I have an email saying it passed, but then it was changed.

Can we somehow get a handle on all this automated testing? It's getting more confusing by the day to try and figure out what is broken vs what works. It just about has hit the "less than useful" stage.

**Comment by miked-mellanox** [comment]
* strace shows that opal_os_dirpath_create cannot handle EEXIST rc?

``` shell
open("/tmp/openmpi-sessions-2848@jenkins01_0/37652", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
getuid()                                = 2848
stat("/tmp/openmpi-sessions-2848@jenkins01_0/37652/0/0", 0x7fffffffdd70) = -1 ENOENT (No such file or directory)
stat("/tmp/openmpi-sessions-2848@jenkins01_0/37652/0/0", 0x7fffffffdd50) = -1 ENOENT (No such file or directory)
mkdir("/tmp/openmpi-sessions-2848@jenkins01_0/37652/0/0", 0700) = -1 ENOENT (No such file or directory)
mkdir("/tmp", 0700)                     = -1 EEXIST (File exists)
write(2, "[jenkins01:15862] opal_os_dirpat"..., 164[jenkins01:15862] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp) of (/tmp/openmpi-sessions-2848@jenkins01_0/37652/0/0), mkdir failed [-1]
) = 164
write(2, "[jenkins01:15862] [[37652,0],0] "..., 93[jenkins01:15862] [[37652,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 110
```

**Comment by ggouaillardet** [comment]
this is a bug in my commits related to this pr.
as I wrote in my initial comment, this is a test pr do you can disregard the Jenkins statuses.
sorry for the confusion

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/30/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/119/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 780 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//610/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/610/

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/37/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/127/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 776 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//618/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/618/

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/52/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/146/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 771 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//632/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/632/

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/634/


**Build Log**
*last 50 lines*

 ```
[...truncated 48502 lines...]
[jenkins01:10690] *** MPI_ERR_INTERN: internal error
[jenkins01:10690] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[jenkins01:10690] ***    and potentially your MPI job)
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/634/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/0f95ee144a66fa8619772b4d532b941700b19878
ERROR: Publisher 'Set build status on GitHub commit' aborted due to exception: 
java.io.IOException: {"message":"No commit found for SHA: 0f95ee144a66fa8619772b4d532b941700b19878","documentation_url":"https://developer.github.com/v3/repos/statuses/"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:496)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:127)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1769)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/open-mpi/ompi/statuses/0f95ee144a66fa8619772b4d532b941700b19878
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/open-mpi/ompi/statuses/0f95ee144a66fa8619772b4d532b941700b19878
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 2cef2d0fe6b1599e6c0ae6d151fe9b361c6f11bd to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/634/ and message: 'Build finished.'
Using conext: Mellanox
```

**Pull request merged**
