### PR TITLE
Silence warnings and ignore test binary

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Here we go again - ARMv8 failing on "setenv":
```
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
```
This change couldn't possibly impact that scenario, so something is clearly busted on the CI for that platform.

**Comment by shamisp** [comment]
@rhc54 what is the error Code ?

**Comment by rhc54** [comment]
It doesn't provide one - it just reports the setenv failure and then logs the test as having failed. We have started seeing these somewhat randomly, but no idea why.

**Comment by jlinford** [comment]
Is this related to the network issue previously documented here?  https://github.com/open-mpi/ompi/pull/5247

And what is the value of PMIX_SERVER_TMPDIR?  Is it longer than 4095 characters?

**Comment by jsquyres** [comment]
@shamisp @jlinford Looks like the issue was resolved (by removing the `setenv`): see https://github.com/open-mpi/ompi/issues/5278#issuecomment-397894228

**Pull request merged**
