### PR TITLE
dvm: add daemonize and set-sid options

### PR DESCRIPTION
**Pull request by naughtont3**
Add `--daemonize` and `--set-sid` options to `orte-dvm` from standard `orted`.

### CODE REVIEW

**Comment by rhc54** [comment]
@naughtont3 Please add a " Signed-off-by: Thomas Naughton \<email address\>" to your commit.

**Comment by rhc54** [comment]
bot:mellanox:retest

**Comment by naughtont3** [comment]
@rhc54 OK, I will add the signoff.  I saw that `git commit --amend --signoff` should do the trick.  However, it creates a new SHA for that commit.  Is that ok since I already published stuff?  Or is there a "better" way?  (sorry for git newbie question)

**Comment by jjhursey** [comment]
@naughtont3 Yeah that is ok since you are (force) pushing to your private branch (`naughtont3:tjn-ortedvm-daemonize`).

**Comment by naughtont3** [comment]
OK, thanks Josh

**Comment by naughtont3** [comment]
OK, so I added `--force` to my push line and pushed to private branch (`naughtont3:tjn-ortedvm-daemonize`), which seems to have made the above checks happy. Thanks @jjhursey and @rhc54.

**Pull request merged**
