### PR TITLE
xl: Use C11 builtin atomics if available.

### PR DESCRIPTION
**Pull request by awlauria**
If unavailable, fallback to gcc builtins.
Some configury work was needed to force include
stdatomic.h. Currently xl doesn't have it in its search
path.

Tested with xl V16.1.1.

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/87387a129d5df1b5818dd106b4baaf5c

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
I do see a fair sized regression with opal_lifo/opal_fifo make check tests from the current master in-line assembly xl atomics on power9. So adding the WIP label. it would appear that the c11 atomics via xl are not the way to go performance wise.

What I can do is allow xl + c11 if explicitly requested in configure, otherwise use the powerpc atomic headers by default.
There are xl builtins that may perform just as well/better than the assembly, I'll see if there's any merit to working those in.

**Comment by hjelmn** [comment]
For better performance for the lifo/fifo split out the LL/SC atomics as done for AArch64. See #8412

**Comment by hjelmn** [comment]
CAS is not a native concept on Power or AArch64. It can be implemented on top of LL/SC but the the CAS128 implementation of the lifo/fifo used in Open MPI are for avoiding ABA problems. LL/SC on its own is sufficient to avoid ABA. I did one more test with CAS128 with a CPU release (such as the one used in the LL/SC implementation) and even there the pure LL/SC lifo/fifo beat the CAS128 implementation by more than a factor of 2.

**Comment by awlauria** [comment]
Thanks for the tips @hjelmn - I will be working on making those changes today.

**Comment by awlauria** [comment]
Closing for #8649

**Pull request closed without merging**
