### PR TITLE
v2.x: pmix: fix PMIx_server_register_nspace() usage

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:lanl:retest

**Comment by hppritcha** [comment]
We have a regression with --disable-open on v2.x

**Comment by ggouaillardet** [comment]
@hppritcha is it a really a regression or a jenkins issue ?
(see a previous comment of mine)
basically
- i cannot reproduce the issue (i tried OpenSUSE Leap 42.2)
- at the beginning of ```./autogen.pl```
```
./ompi/include/mpif-handles.h unchanged; not written
./ompi/include/mpif-constants.h unchanged; not written
./ompi/include/mpif-io-handles.h unchanged; not written
./ompi/include/mpif-io-constants.h unchanged; not written
./ompi/mpi/fortran/use-mpi-f08/constants.h unchanged; not written
```
that suggests the working directory is not empty when Jenkins starts building a PR

since i cannot make any sense of this error, i am thinking the root cause could be some leftover in Jenkins.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Pull request merged**
