### PR TITLE
OSHMEM/SMPL/UCX: Add real fence support - 3.1.x

### PR DESCRIPTION
**Pull request by brminich**
+ Add quiet method to SPML, so it can have different implementation with fence.
+ Use ucp_worker_fence for spml_fence method of UCX SPML.

Signed-off-by: Mikhail Brinskii <mikhailb@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
ok to test

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by bwbarrett** [comment]
Does someone from Mellanox want to review this patch?

**Comment by brminich** [comment]
@yosefe, plz review

**Comment by yosefe** [comment]
let's keep it in master-only for now

**Pull request closed without merging**
