### PR TITLE
pmix: silence various warnings from pmix1xx

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by rhc54** [comment]
Hmmm...please don't commit this yet. There are some changes here that don't look right - I assume some of these warnings are for unused functions? May just be that we haven't finished implementing some of the features yet.

Could you post these warnings? I'm not seeing anything, and I'm also running on a CentOS7 box, so I suspect this is a case of different compilers.

**Comment by ggouaillardet** [comment]
basically, there are four kind of changes
- handle ```PMIX_BOOL``` in two ```switch``` statements
- remove unused functions
- remove unused variable
- add missing function prototypes (make them ```static``` since they are not used anywhere)

ompi was configure'd with ```'--enable-debug' '--enable-picky' 'CFLAGS=-g -O0 -pipe'```

```
$ cd opal/mca/pmix/pmix1xx
$ make
Making all in pmix
make[1]: Entering directory `/home/gilles/build/ompi-master/opal/mca/pmix/pmix1xx/pmix'
make[2]: Entering directory `/home/gilles/build/ompi-master/opal/mca/pmix/pmix1xx/pmix'
  CC       src/class/pmix_object.lo
  CC       src/class/pmix_list.lo
  CC       src/class/pmix_pointer_array.lo
  CC       src/class/pmix_hash_table.lo
  CC       src/include/pmix_globals.lo
  CC       src/buffer_ops/copy.lo
  CC       src/buffer_ops/internal_functions.lo
  CC       src/buffer_ops/open_close.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/open_close.c:38:2: warning: #ident is a GCC extension [enabled by default]
 #ident PMIX_VERSION
  ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/open_close.c: In function 'opal_pmix_pmix1xx_pmix_value_load':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/open_close.c:409:9: warning: enumeration value 'PMIX_BOOL' not handled in switch [-Wswitch]
         switch(type) {
         ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/open_close.c: In function 'opal_pmix_pmix1xx_pmix_value_unload':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/open_close.c:497:9: warning: enumeration value 'PMIX_BOOL' not handled in switch [-Wswitch]
         switch(type) {
         ^
  CC       src/buffer_ops/pack.lo
  CC       src/buffer_ops/print.lo
  CC       src/buffer_ops/unpack.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/unpack.c: In function 'pmix_bfrop_unpack_bool':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/unpack.c:149:16: warning: unused variable 'k' [-Wunused-variable]
     int32_t i, k;
                ^
  CC       src/util/argv.lo
  CC       src/util/error.lo
  CC       src/util/printf.lo
  CC       src/util/output.lo
  CC       src/util/pmix_environ.lo
  CC       src/util/crc.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/util/crc.c:43:6: warning: "PMIX_ALIGNMENT_LONG" is not defined [-Wundef]
 #if (PMIX_ALIGNMENT_LONG == 8)
      ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/util/crc.c:45:8: warning: "PMIX_ALIGNMENT_LONG" is not defined [-Wundef]
 #elif (PMIX_ALIGNMENT_LONG == 4)
        ^
  CC       src/util/progress_threads.lo
  CC       src/util/fd.lo
  CC       src/util/timings.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/util/timings.c:36:5: warning: "PMIX_COMPILE_TIMING" is not defined [-Wundef]
 #if PMIX_COMPILE_TIMING
     ^
  CC       src/util/os_path.lo
  CC       src/util/basename.lo
  CC       src/util/hash.lo
  CC       src/usock/usock.lo
  CC       src/usock/usock_sendrecv.lo
  CC       src/client/pmix_client.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c: In function 'opal_pmix_pmix1xx_pmix_client_process_nspace_blob':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c:859:19: warning: unused variable 'val' [-Wunused-variable]
     pmix_value_t *val;
                   ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c: At top level:
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c:61:13: warning: 'myerrhandler' defined but not used [-Wunused-function]
 static void myerrhandler(pmix_status_t status,
             ^
  CC       src/client/pmix_client_fence.lo
  CC       src/client/pmix_client_get.lo
  CC       src/client/pmix_client_pub.lo
  CC       src/client/pmix_client_spawn.lo
  CC       src/client/pmix_client_connect.lo
  CC       src/server/pmix_server.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c: In function 'PMIx_server_register_nspace':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:545:12: warning: unused variable 'i' [-Wunused-variable]
     size_t i;
            ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c: In function '_execute_collective':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:572:27: warning: unused variable 'pbkt' [-Wunused-variable]
     pmix_buffer_t bucket, pbkt, xfer;
                           ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c: In function '_register_client':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:657:30: warning: unused variable 'lcdnext' [-Wunused-variable]
     pmix_dmdx_local_t *lcd, *lcdnext;
                              ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:657:24: warning: unused variable 'lcd' [-Wunused-variable]
     pmix_dmdx_local_t *lcd, *lcdnext;
                        ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:656:10: warning: unused variable 'found' [-Wunused-variable]
     bool found;
          ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c: In function '_dmodex_req':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:784:25: warning: unused variable 'xfer' [-Wunused-variable]
     pmix_buffer_t pbkt, xfer;
                         ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c: In function '_mdxcbfunc':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:1570:18: warning: unused variable 'kp' [-Wunused-variable]
     pmix_kval_t *kp;
                  ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c: At top level:
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c:1809:13: warning: '_cnct' defined but not used [-Wunused-function]
 static void _cnct(int sd, short args, void *cbdata)
             ^
  CC       src/server/pmix_server_ops.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:83:15: warning: no previous prototype for '_satisfy_local_req' [-Wmissing-prototypes]
 pmix_status_t _satisfy_local_req(pmix_nspace_t *nptr, pmix_rank_info_t *info,
               ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:117:15: warning: no previous prototype for '_satisfy_remote_req' [-Wmissing-prototypes]
 pmix_status_t _satisfy_remote_req(pmix_nspace_t *nptr, int rank,
               ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c: In function 'pmix_pending_request':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:158:12: warning: unused variable 'sz' [-Wunused-variable]
     size_t sz;
            ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:157:11: warning: unused variable 'data' [-Wunused-variable]
     char *data;
           ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:156:19: warning: unused variable 'val' [-Wunused-variable]
     pmix_value_t *val;
                   ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:155:25: warning: unused variable 'xfer' [-Wunused-variable]
     pmix_buffer_t pbkt, xfer;
                         ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:155:19: warning: unused variable 'pbkt' [-Wunused-variable]
     pmix_buffer_t pbkt, xfer;
                   ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c: In function 'get_tracker':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:516:27: warning: unused variable 'ns' [-Wunused-variable]
     pmix_nspace_t *nptr, *ns;
                           ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:516:20: warning: unused variable 'nptr' [-Wunused-variable]
     pmix_nspace_t *nptr, *ns;
                    ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:515:17: warning: unused variable 'all_def' [-Wunused-variable]
     bool match, all_def;
                 ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:513:30: warning: unused variable 'info' [-Wunused-variable]
     pmix_rank_info_t *iptr, *info;
                              ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:513:23: warning: unused variable 'iptr' [-Wunused-variable]
     pmix_rank_info_t *iptr, *info;
                       ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c: In function 'new_tracker':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:581:10: warning: unused variable 'match' [-Wunused-variable]
     bool match, all_def;
          ^
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c: In function '_process_dmdx_reply':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c:896:1: warning: label 'cleanup' defined but not used [-Wunused-label]
 cleanup:
 ^
  CC       src/server/pmix_server_regex.lo
  CC       src/server/pmix_server_listener.lo
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_listener.c: In function 'pmix_server_authenticate':
../../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_listener.c:365:43: warning: unused variable 'ptr' [-Wunused-variable]
     char *msg, *nspace, *version, *cred, *ptr;
                                           ^
  CC       src/sec/pmix_sec.lo
  CC       src/sec/pmix_native.lo
  CC       src/sec/pmix_munge.lo
  CCLD     libpmix.la
make[2]: Leaving directory `/home/gilles/build/ompi-master/opal/mca/pmix/pmix1xx/pmix'
make[1]: Leaving directory `/home/gilles/build/ompi-master/opal/mca/pmix/pmix1xx/pmix'
make[1]: Entering directory `/home/gilles/build/ompi-master/opal/mca/pmix/pmix1xx'
  CC       mca_pmix_pmix1xx_la-pmix_pmix1_component.lo
  CC       mca_pmix_pmix1xx_la-pmix_pmix1.lo
../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix_pmix1.c:90:31: warning: 'errhandler' defined but not used [-Wunused-variable]
 static pmix_notification_fn_t errhandler = NULL;
                               ^
../../../../../../src/ompi-master/opal/mca/pmix/pmix1xx/pmix_pmix1.c:92:13: warning: 'notification_fn' defined but not used [-Wunused-function]
 static void notification_fn(int status,
             ^
  CC       mca_pmix_pmix1xx_la-pmix1_client.lo
  CC       mca_pmix_pmix1xx_la-pmix1_server_south.lo
  CC       mca_pmix_pmix1xx_la-pmix1_server_north.lo
  CCLD     mca_pmix_pmix1xx.la
make[1]: Leaving directory `/home/gilles/build/ompi-master/opal/mca/pmix/pmix1xx'
```

**Comment by rhc54** [comment]
@ggouaillardet I have no issue except with the second one - the removal of the unused functions. Could you please leave those for now?

**Comment by rhc54** [comment]
@ggouaillardet aha! I have found the bug in the PMIx repo's configury that is causing us to miss all these gems! Thanks for pointing it out - I'll fix some of this upstream.

**Comment by rhc54** [comment]
@ggouaillardet I'm going to close this and bring them across from the upstream tarball just so we keep it all in sync. Thx!

**Pull request closed without merging**
