### PR TITLE
Topic/external support

### PR DESCRIPTION
**Pull request by ggouaillardet**
this is for test only
i cannot reproduce the failure of test/datatype/external32 on centos7 nor OS X, so let's try to see what travis says about that

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
@bosilca i pushed open-mpi/ompi@7279472104391518cf33d77c927174ccd02b78e2 in order to fix heterogeneous support (without this commit, opal_convertor_send swap bytes on hetero architecture,
but we only want that in MPI_Pack_external

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by ggouaillardet** [comment]
:bot:retest

**Pull request closed without merging**
