### PR TITLE
mpi_f08: correctly implements MPI_{COMM,TYPE,WIN}_{DUP,NULL_{COPY,DEL…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…ETE}}_FN

Fixes open-mpi/ompi#1323

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres did you get any chance to review this ?

**Comment by jsquyres** [comment]
@ggouaillardet Sorry for the delay.

Looks like you left out `MPI_NULL_COPY_FN` and `MPI_NULL_DELETE_FN`. I found this by trying to compile ompi-tests/simple/attr (yes, it's a little suite hidden away in a subdirectory... perhaps it should be moved into the ibm test suite...).

**Comment by ggouaillardet** [comment]
are these really f08 bindings ?

**Comment by jsquyres** [comment]
I just checked MPI-3.1, and you're correct -- they were deprecated in MPI-2.0, and therefore not included in the mpi_f08 bindings.  Let me go update the test...

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@ggouaillardet Can you make v1.10.x and v2.x PRs for this?  Thanks!

**Pull request merged**
