### PR TITLE
v5.0.x: Update to PMIx v4.0 branch and sync PRRTE master

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@gpaulsen I am unable to build the branch on my Macs pending backport of the ptrdiff_t fix. Figured we could just give CI a shot at it.

**Comment by rhc54** [comment]
Looks like PRRTE failed to configure on AWS for some reason. @bwbarrett Can you spot the problem?

**Comment by rhc54** [comment]
bot:aws:retest

**Comment by bwbarrett** [comment]
It's a real failure.  You have to scroll up a bunch, because someone decided that we needed to dump a bunch of stuff to stdout after the failure.  Here's the error message:

```
*** Compiler flags
checking need zlib support... 
configure: WARNING: AN EARLY VERSION OF PMIx HAS BEEN USED THAT DOES NOT
configure: WARNING: INCLUDE SUPPORT FOR COMPRESS/DECOMPRESS OF LARGE MESSAGES.
configure: WARNING: PRRTE REQUIRES SUCH SUPPORT TO BUILD. PLEASE ENSURE
configure: WARNING: THAT ZLIB IS AVAILABLE SO THAT PRRTE CAN DIRECTLY BUILD
configure: WARNING: AGAINST IT
configure: error: CANNOT CONTINUE
configure: ===== done with 3rd-party/prrte configure =====
configure: error: PRRTE configuration failed.  Cannot continue.
```

**Comment by rhc54** [comment]
I see - okay, you guys will need to install zlib on those boxes. It also means that you really haven't been testing PMIx in the way it will be used in the field as without zlib we don't do any compression/decompression of RTE messages. This is true in _all_ OMPI release branches.

**Comment by rhc54** [comment]
Just to clarify: you'll need `zlib` and `zlib-devel`

**Comment by rhc54** [comment]
Discussed the zlib dependency with @jsquyres. Just to further clarify here, we use `zlib` to compress the launch message and other RTE messages for launch scalability. If we don't have it, we can still run - but people with large systems will see a significant impact on startup.

I realize that this doesn't apply to everyone. However, while building this PR I realized that we were "silently" failing over into this "non-optimal" behavior. Hence the configure error to detect/highlight the problem so we would see it.

@jsquyres and I think the right solution is to:

* for PMIx v4.1 and above, print out a warning that compression is not available during configure. We always allow it to complete and build anyway, but this at least may serve as an alert to people
* PRRTE built on PMIx v4.0 (which doesn't expose the compression APIs) includes its own copy of the PMIx v4.1 code (properly prevented from compiling if not needed). In this case, print the warning if PRRTE doesn't detect `zlib`
* Add a runtime check if we were unable to compress the launch message (as that is the _big_ one) and emit a warning that can be turned off by MCA param. The compression support checks to see if compression actually helped and returns a flag indicating whether or not we actually compressed, so we can only emit the warning when it really would have made a difference. We can debate how big a difference to require before warning.

Unless someone objects and/or proposes something better, I'll update PRRTE and PMIx accordingly and then update the PR.

This will resolve the CI issue here. We also agreed that we really need a wiki entry for all three projects listing their required and optional dependencies, perhaps separated into which ones impact behavior/performance and which provide additional features. Seemed best if we have each project create their own page and then cross-link as necessary (ompi->prrte+pmix, prrte->pmix).

**Comment by bwbarrett** [comment]
> This will resolve the CI issue here. We also agreed that we really need a wiki entry for all three projects listing their required and optional dependencies, perhaps separated into which ones impact behavior/performance and which provide additional features. Seemed best if we have each project create their own page and then cross-link as necessary (ompi->prrte+pmix, prrte->pmix).

I think a README-packagers.md might work best.  I was going to propose one for Open MPI this afternoon.

**Comment by rhc54** [comment]
I have updated the both PRRTE and PMIx according to the prior design comment.

**Comment by rhc54** [comment]
Looks like Amazon had problems retrieving the PRRTE repo.

bot:aws:retest

**Review by gpaulsen — APPROVED** [review]
PMIx v4.0 for the win!

**Pull request merged**
