### PR TITLE
Remove Checkpoint/Restart Infrastructure

### LINKED ISSUE #7437: Remove all the rest of the FT code
There's still a bunch of FT things left over in the code base that should be removed:

* opal/tools/opal-checkpoint
* opal/tools/opal-restart
* Various AM_CONDITIONALs, such as `WANT_FT`, `WANT_FT_CR`, `WANT_FT_THREAD`
* config/opal_setup_ft.m4
* `OPAL_ENABLE_FT_*` preprocessor macros
* ...possibly more?  I stopped looking

### PR DESCRIPTION
**Pull request by jjhursey**
Fixes #7437

Summary:
 - Remove opal-checkpoint and opal-restart tools
 - Remove crcpw PML wrapper
 - Remove crcp framework
 - Throw a error message about the removal of C/R support in Open MPI
   if a user tries to specify it on the configure line.
 - Remove `WANT_FT_CR` blocks
 - Remove WANT_FT_THREAD and OPAL_ENABLE_FT_THREAD blocks
 - Remove OPAL_ENABLE_FT_CR code blocks, crs framework
 - Remove interface level CR hooks
   - `OPAL_CR_ENTER_LIBRARY` / `OPAL_CR_EXIT_LIBRARY` / `OPAL_CR_NOOP_PROGRESS`
 - Remove OPAL_CRS_ ft_event contents
   - All `ft_event` functions return success, and are never called.
   - We did not remove the functions from the component structure since it
     would change the structure impacting all components.

Signed-off-by: Joshua Hursey <jhursey@us.ibm.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b4133df5b435fec179f31b39bf226634

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8c9df0cd15503d634d7250fbbdbf46e5

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/10a4bffcb59e50bb17dce22df9203bc9

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e6740fa16356ef5e7ef428d37e65d98a

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1b24196ba9115190a4e3c71517652bf8

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0bee77e65debe305389d9eee499c4ea3

**Comment by jjhursey** [comment]
Moving forward collaborating on PR #8312 - closing this for now, but will leave the branch around until that PR is done.

**Pull request closed without merging**
