### PR TITLE
Fix experimental verbs support

### PR DESCRIPTION
**Pull request by igor-ivanov**
This commit fixes issues related https://github.com/open-mpi/ompi/pull/1160

@hjelmn could you review

### CODE REVIEW

**Comment by artpol84** [comment]
@igor-ivanov 
isn't this a duplication of https://github.com/open-mpi/ompi/pull/1164?

**Comment by igor-ivanov** [comment]
Yes, it should resolve the same issue but seems using another way

**Comment by miked-mellanox** [comment]
do we need it in addition to fix in #1164?

**Comment by igor-ivanov** [comment]
@miked-mellanox I think that both resolve issue. One note from me: https://github.com/open-mpi/ompi/pull/1164  uses two structures for device attribute (standard and experimental) at the same time in case experimental verbs is available. So a payment is sizeof(struct ibv_device_attr) for every device object.

**Comment by hjelmn** [comment]
I am good either way. I wanted to avoid extra #if statements but there is the small added cost of the extra attribute struct. I will add #1164 to the 2.x PR and if this one ends up going in I will add it as well.

**Comment by igor-ivanov** [comment]
I think that this PR can be closed because of another PR as https://github.com/open-mpi/ompi/pull/1164 was accepted.

**Pull request closed without merging**
