### PR TITLE
btl/uct: restrict to using UCT 1.7 or older API for now

### PR DESCRIPTION
**Pull request by hppritcha**
related to #7128

The UCX crew is no longer guaranteeing that the UCT API is going to be frozen, so this is kind of a whack-a-mole problem trying to keep the BTL UCT working with various changing UCT APIs.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by jsquyres** [comment]
You might want to list the UCX versions supported in the “failure” ACMSGRESULT message (because that will be the user’s first question upon getting a failure).

**Comment by hppritcha** [comment]
> You might want to list the UCX versions supported in the “failure” ACMSGRESULT message (because that will be the user’s first question upon getting a failure).

oh good idea.

**Comment by jsquyres** [comment]
Paired with #7144, do you want to bump up the checked version to v1.7, and then cherry pick both this and #7144 to v4.0.x?

**Comment by hppritcha** [comment]
yes that was the plan.

**Comment by hppritcha** [comment]
@jsquyres check now

**Pull request merged**
