### PR TITLE
btl/uct: configure option to explicitly enable/disable this

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by amaslenn** [comment]
@yosefe @hjelmn

**Comment by hjelmn** [comment]
Not need. The MCA already supports this. --enable-mca-no-build=btl-uct    Why do need this option?

**Comment by amaslenn** [comment]
@hjelmn `--enable-mca-no-build=btl-uct` doesn't work for me, it doesn't exclude `btl=uct` from the build.
Does it work in your env?

**Comment by hjelmn** [comment]
@amaslenn That option is as probably old as the MCA. Works for me. We typically use it to remove components we do not need: ```--enable-mca-no-build=btl-tcp,osc-pt2pt``` for example.

You will see something like this in the config.log:
```
configure:5915: --- MCA component osc:pt2pt (m4 configuration macro)
configure:331090: checking for MCA component osc:pt2pt compile mode
configure:331096: result: dso
configure:331602: checking if MCA component osc:pt2pt can compile
configure:331604: result: no
```

And, again, is there a problem in the UCT btl that needs to be fixed?

**Comment by amaslenn** [comment]
Right now this BTL is not compatible with UCX@master. And since I don't need it, I want to completely disable it from my build. Error is:
```sh
btl_uct_tl.c: In function ‘mca_btl_uct_context_create’:
btl_uct_tl.c:323:44: error: ‘UCT_CB_FLAG_SYNC’ undeclared (first use in this function)
                                   context, UCT_CB_FLAG_SYNC);
                                            ^
```
I missed that I use platform config and it takes priority over this option, sorry to bother.

Thanks!

**Comment by amaslenn** [comment]
Right now this BTL is not compatible with UCX@master. And since I don't need it, I want to completely disable it from my build. Error is:
```sh
btl_uct_tl.c: In function ‘mca_btl_uct_context_create’:
btl_uct_tl.c:323:44: error: ‘UCT_CB_FLAG_SYNC’ undeclared (first use in this function)
                                   context, UCT_CB_FLAG_SYNC);
                                            ^
```
I missed that I use platform config and it takes priority over this option, sorry to bother.

Thanks!

**Comment by amaslenn** [comment]
Right now this BTL is not compatible with UCX@master. And since I don't need it, I want to completely disable it from my build. Error is:
```sh
btl_uct_tl.c: In function ‘mca_btl_uct_context_create’:
btl_uct_tl.c:323:44: error: ‘UCT_CB_FLAG_SYNC’ undeclared (first use in this function)
                                   context, UCT_CB_FLAG_SYNC);
                                            ^
```
I missed that I use platform config and it takes priority over this option, sorry to bother.

Thanks!

**Comment by amaslenn** [comment]
Right now this BTL is not compatible with UCX@master. And since I don't need it, I want to completely disable it from my build. Error is:
```sh
btl_uct_tl.c: In function ‘mca_btl_uct_context_create’:
btl_uct_tl.c:323:44: error: ‘UCT_CB_FLAG_SYNC’ undeclared (first use in this function)
                                   context, UCT_CB_FLAG_SYNC);
                                            ^
```
I missed that I use platform config and it takes priority over this option, sorry to bother.

Thanks!

**Comment by amaslenn** [comment]
Right now this BTL is not compatible with UCX@master. And since I don't need it, I want to completely disable it from my build. Error is:
```sh
btl_uct_tl.c: In function ‘mca_btl_uct_context_create’:
btl_uct_tl.c:323:44: error: ‘UCT_CB_FLAG_SYNC’ undeclared (first use in this function)
                                   context, UCT_CB_FLAG_SYNC);
                                            ^
```
I missed that I use platform config and it takes priority over this option, sorry to bother.

Thanks!

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by amaslenn** [comment]
Right now this BTL is not compatible with UCX@master. And since I don't need it, I want to completely disable it from my build. Error is:
```sh
btl_uct_tl.c: In function ‘mca_btl_uct_context_create’:
btl_uct_tl.c:323:44: error: ‘UCT_CB_FLAG_SYNC’ undeclared (first use in this function)
                                   context, UCT_CB_FLAG_SYNC);
                                            ^
```
I missed that I use platform config and it takes priority over this option, sorry to bother.

Thanks!

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request closed without merging**
