### PR TITLE
mpi4py: Run accept/connect tests unconditionally

### PR DESCRIPTION
**Pull request by dalcinl**
It looks like recent fixes from @hppritcha solved outstanding mpi4py testing issues related to accept/connect.
Here you have fresh runs to confirm: https://github.com/mpi4py/mpi4py-testing/actions/runs/8759119662

This PR removes the conditional run of accept/connect. However, note that I have not yet pushed to mpi4py/mpi4py@master the required changes https://github.com/mpi4py/mpi4py/commit/24ba042c0ee08fc324a04c5190d5dbc41d32e023 .

cc @jsquyres

### CODE REVIEW

**Comment by dalcinl** [comment]
@wenduwan Can you help me get #12384 into v5.0.x? I'm not really sure what's the usual git/github workflow for backporting bugfixes to release branches. After that, I can merge the mpi4py side of things (updating testsuite for the know failures), and finally, we can get this one merged (and eventually in v5.0.x).

**Review by jsquyres — APPROVED** [review]

**Comment by wenduwan** [comment]
@dalcinl I can open a backport for #12384

**Comment by dalcinl** [comment]
> @dalcinl I can open a backport for #12384

Please do! Thanks!

**Comment by wenduwan** [comment]
There we go #12487

**Pull request merged**
