### PR TITLE
Revert "create the opal_common_verbs_want_fork_support parameter."

### PR DESCRIPTION
**Pull request by miked-mellanox**
Reverts open-mpi/ompi#438

### CODE REVIEW

**Comment by miked-mellanox** [comment]
@jsquyres - could you please suggest a proper way to resolve it?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/316/
Test PASSed.

**Comment by jsquyres** [comment]
I believe there were multiple problems that stemmed from #415:

* The btl_openib_want_fork_support MCA param disappeared.  This is bad for backwards compat.
* opal_verbs_want_fork_support was the wrong name -- should be opal_common_verbs_want_fork_support.
* The instantiation of the global variable backing that MCA param should be in opal/mca/common/verbs, not the core.

George made several commits after that, but I didn't follow all of them, so I don't know exactly where this all ended up.  I'm not sure his last commit into common_verbs_mca.c was correct (e.g., shouldn't it be "opal", "opal_common", "verbs", "want_fork_support"?).

Look to the OPAL common verbs warn_nonexistent_if MCA var for an example of how the OPAL common want_fork_support MCA var should be done.

(SIDENOTE: although I think warn_nonexistent_if should probably be LEVEL2, and want_fork_support could be LEVEL4 or LEVEL5 :-) )

As for the backwards compat / not deleting btl_openib_want_fork_support: I think you raised a valid point: that creating an alias has corner cases that were not anticipated.  This seems like a larger issue, and should be addressed as such.  For this PR, it's probably sufficient to make btl_openib_want_fork_support consistent with other MCA vars that use the alias system.

Then a new issue can be created the larger problem of "what happens when MCA var XYZ is set to value A by the user, but then later alias ABC is set to (different) value B?". Could you create a small reproducer and attach it to the new issue to show the problem?  The new issue can then be used to track fixing *all* of the aliased MCA vars, not just this one.

**Comment by alinask** [comment]
@jsquyres Thanks for the comments!
* The opal_common_verbs_want_fork_support parameter is currently instantiated in opal/mca/common/verbs so this part is taken care of.
* If I use "opal", "opal_common", "verbs", "want_fork_support" then this parameter isn't created at all and I dont see it in ompi_info. Do you know why?
* About warn_nonexistent_if, since the opal_common_verbs_mca_register function isn't being called, no synonym is created and so the only parameter in ompi_info is btl_openib_warn_nonexistent_if. Am I missing something here?
* I think that you are right about the need for a seperate issue for the aliases but if it's not fixed before this commit is pushed then we will get the wrong behavior from opal_common_verbs_want_fork_support since we won't be able to control the fork support from the command line.

**Comment by bosilca** [comment]
On Tue, Mar 3, 2015 at 9:13 AM, Jeff Squyres <notifications@github.com>
wrote:

> I believe there were multiple problems that stemmed from #415
> <https://github.com/open-mpi/ompi/pull/415>:
>
>    - The btl_openib_want_fork_support MCA param disappeared. This is bad
>    for backwards compat.
>    - opal_verbs_want_fork_support was the wrong name -- should be
>    opal_common_verbs_want_fork_support.
>    - The instantiation of the global variable backing that MCA param
>    should be in opal/mca/common/verbs, not the core.
>
>  This is ugly as it forces all common parts to have their own registration
function, protected for single initializations, and that should be called
from all components using in order to make sure we see the MCA parameters
during ompi_info.

>
>
> George made several commits after that, but I didn't follow all of them,
> so I don't know exactly where this all ended up. I'm not sure his last
> commit into common_verbs_mca.c was correct (e.g., shouldn't it be "opal",
> "opal_common", "verbs", "want_fork_support"?).
>
If we want to see it as a particular component parameter (such as
"ompi_info --param opal common") then the call should have been different.

  George.

**Comment by jsquyres** [comment]
> > This is ugly as it forces all common parts to have their own registration
> function, protected for single initializations, and that should be called
> from all components using in order to make sure we see the MCA parameters
> during ompi_info.

Yes, that's how things are in other common components.

Common components are not part of the core -- at least for this respect, they are treated just like any other component: MCA vars (and the C vars backing them) should be wholly contained in their respective components.

> > George made several commits after that, but I didn't follow all of them,
> > so I don't know exactly where this all ended up. I'm not sure his last
> > commit into common_verbs_mca.c was correct (e.g., shouldn't it be "opal",
> > "opal_common", "verbs", "want_fork_support"?).
> >
> If we want to see it as a particular component parameter (such as
> "ompi_info --param opal common") then the call should have been different.

I think that it should follow the same convention as the warn_nonexistent_if param (right above it).  I only looked at the code quickly (frankly, I'm preparing for the MPI Forum meeting right now...!); I'm not sure which of the two is correct.  The project is opal, the framework is common, and the component name is verbs.

**Comment by jsquyres** [comment]
> 	• The opal_common_verbs_want_fork_support parameter is currently instantiated in opal/mca/common/verbs so this part is taken care of.

Ok, sweet.

> 	• If I use "opal", "opal_common", "verbs", "want_fork_support" then this parameter isn't created at all and I dont see it in ompi_info. Do you know why?

I just replied to George -- I'm not sure which is correct, offhand, sorry.

(more below)

> 	• About warn_nonexistent_if, since the opal_common_verbs_mca_register function isn't being called, no synonym is created and so the only parameter in ompi_info is btl_openib_warn_nonexistent_if. Am I missing something here?

It seems like this function accidentally got orphaned somehow -- probably some bit rot over time.  It seems like it should be getting called from the components that need to alias these MCA vars (e.g., the ones that are calling the fork support setup stuff).

If it's never getting called, that's why opal_common_verbs_warn_nonexistent_if and opal_common_verbs_want_fork_support are never created.

Just like want_fork_support, btl openib's warn_nonexistent_if should probably be an alias, too.

> 	• I think that you are right about the need for a seperate issue for the aliases but if it's not fixed before this commit is pushed then we will get the wrong behavior from opal_common_verbs_want_fork_support since we won't be able to control the fork support from the command line.

I'm not sure I understand -- you should be able to "mpirun --mca opal_common_verbs_want_fork_support X ...", and it should work fine, right?  It only won't/might not work properly if you "mpirun --mca btl_openib_want_fork_support X ...", right? (i.e., if X is not the same as the default value)

(hence my off-ticket email to Nathan; I'll see him in person in about 2 hours and will try to find time to talk to him about the larger issue today)

-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by jsquyres** [comment]
Arrgh.  Github really munged my last email reply.  Let me paste it here in the web UI:

>	• The opal_common_verbs_want_fork_support parameter is currently instantiated in opal/mca/common/verbs so this part is taken care of.

Ok, sweet.

>	• If I use "opal", "opal_common", "verbs", "want_fork_support" then this parameter isn't created at all and I dont see it in ompi_info. Do you know why?

I just replied to George -- I'm not sure which is correct, offhand, sorry.

(more below)

>	• About warn_nonexistent_if, since the opal_common_verbs_mca_register function isn't being called, no synonym is created and so the only parameter in ompi_info is btl_openib_warn_nonexistent_if. Am I missing something here?

It seems like this function accidentally got orphaned somehow -- probably some bit rot over time.  It seems like it should be getting called from the components that need to alias these MCA vars (e.g., the ones that are calling the fork support setup stuff).

If it's never getting called, that's why opal_common_verbs_warn_nonexistent_if and opal_common_verbs_want_fork_support are never created.

Just like want_fork_support, btl openib's warn_nonexistent_if should probably be an alias, too.

>	• I think that you are right about the need for a seperate issue for the aliases but if it's not fixed before this commit is pushed then we will get the wrong behavior from opal_common_verbs_want_fork_support since we won't be able to control the fork support from the command line.

I'm not sure I understand -- you should be able to "mpirun --mca opal_common_verbs_want_fork_support X ...", and it should work fine, right?  It only won't/might not work properly if you "mpirun --mca btl_openib_want_fork_support X ...", right? (i.e., if X is not the same as the default value)

(hence my off-ticket email to Nathan; I'll see him in person in about 2 hours and will try to find time to talk to him about the larger issue today)

**Comment by alinask** [comment]
* I meant  that if I do call opal_common_verbs_mca_register and use 
"opal", "opal_common", "verbs", "want_fork_support"
then this parameter isn't created.
If I use
"opal", "opal", NULL, "common_verbs_want_fork_support"
then it is created.

* If the components that are calling this function are the components that call the fork support setup, then it would mean that openib would have to create this parameter, but we need to use it before - in oob/ud.

* Yes, it only won't work properly if I run "mpirun --mca btl_openib_want_fork_support X ... and this is why I think this parameter shouldn't be used and be removed :-)

**Comment by jsquyres** [comment]
On Mar 3, 2015, at 7:07 AM, alinask <notifications@github.com> wrote:
> 
> 	• I meant that if I do call opal_common_verbs_mca_register and use 
> "opal", "opal_common", "verbs", "want_fork_support"
> then this parameter isn't created.
> If I use
> "opal", "opal", NULL, "common_verbs_want_fork_support"
> then it is created.

According to mca_base_var.h, shouldn't the 2nd parameter be "common", not "opal_common"?

Perhaps warn_nonexistent_if is wrong, too (my comment and looking to that one to see an example of how it is done was referring to having all the code be in opal/mca/common/verbs -- not splitting across core and opal/mca/common/verbs).

> 	• If the components that are calling this function are the components that call the fork support setup, then it would mean that openib would have to create this parameter, but we need to use it before - in oob/ud.

Shouldn't oob ud also warn about nonexistent interfaces?

I think there's some misconceptions here.

The point of the common verbs code is that it is *common* -- it is used between multiple components.  Part of the reason that it's common is because the components that use it are similar.  E.g., oob ud and btl openib use verbs and interact with similar network devices.  As such, the common code can therefore enforce some similarity in the user experience between these components.  E.g., things like setting fork support is a global/process-level decision (not a component-level decision).  And if we warn about non-existant verbs-based interfaces, we should do that for *all* verbs-based components, not just one or the other.

Hence, both oob ud and btl openib (and anyone else who is using common/verbs) should have common behavior in these areas, and therefore should likely call this common/verbs bootstrap stuff at the very beginning of their lifecycles, and react to the common/mca var param values the same way.

So if btl openib warns about non-existant interfaces (which our users have repeatedly told them is a very good/desirable feature), then oob ud should also do the same.

> 	• Yes, it only won't work properly if I run "mpirun --mca btl_openib_want_fork_support X ... and this is why I think this parameter shouldn't be used and be removed :-)

I don't know how to say this differently: this name can't be removed because of backwards compatibility reasons.

It *did* work at one point in time.  So there are quite possibly users who are actively using it and expecting that it works.  So we need to a) keep the name, and b) fix it, since it's a regression that it no longer works.  That's what I'll be speaking to Nathan about later today.

-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by jsquyres** [comment]
@miked-mellanox Are you waiting for something else to merge this?  There's breakage on the trunk; if this fixes it (I don't have time to test it, sorry...), then it should be committed.  Or the nightly build will fail again tonight.

**Comment by miked-mellanox** [comment]
@jsquyres - this PR is a result of "revert" of the code which breaks "make distclean".
why need to merge it again? or missing something?

**Comment by bosilca** [comment]
On Tue, Mar 3, 2015 at 11:33 AM, Jeff Squyres <notifications@github.com>
wrote:

> On Mar 3, 2015, at 7:07 AM, alinask <notifications@github.com> wrote:
> >
> > • I meant that if I do call opal_common_verbs_mca_register and use
> > "opal", "opal_common", "verbs", "want_fork_support"
> > then this parameter isn't created.
> > If I use
> > "opal", "opal", NULL, "common_verbs_want_fork_support"
> > then it is created.
>
> According to mca_base_var.h, shouldn't the 2nd parameter be "common", not
> "opal_common"?
>

The first parameter is utterly ignored, so if you want your MCA to stick by
OPAL you have to either use ("opal", "opal_common", ...) or ("opal",
"opal", NULL, "common_verbs_want_fork_support").

**Comment by bosilca** [comment]
Meanwhile the code doesn't compile on a OSX box.

```
 CC       libmca_common_verbs_la-common_verbs_basics.lo
../../../../../ompi/opal/mca/common/verbs/common_verbs_basics.c:30:30: fatal error: infiniband/verbs.h: No such file or directory
 #include <infiniband/verbs.h>
```

**Comment by miked-mellanox** [comment]
sorry, my bad. though "revert button" does it.

**Pull request merged**
