### PR TITLE
man: remove man pages of removed MPI1 subroutines

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1590468bea3b2a5c2e910269a3a98914

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1bfca13418a4ba3759ca6e15c0fef5d5

**Comment by ggouaillardet** [comment]
@gpaulsen @hppritcha should we also remove the man pages from `v4.0.x` unless `--enable-mpi1compatibility` is used ?

**Comment by hppritcha** [comment]
I'd favor simplicity and leave things like they are in v4.0.x.

**Pull request merged**
