### PR TITLE
romio:  add comment per Rob Latham's request

### PR DESCRIPTION
**Pull request by hppritcha**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/301/

**Build Log**
*last 50 lines*

 ```
[...truncated 19653 lines...]
Running /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c 
+ '[' yes == yes ']'
+ timeout -s SIGKILL 10m mpirun -np 8 -bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1 -mca pml ob1 -mca btl self,openib /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      jenkins01
Framework: btl
Component: openib
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  mca_bml_base_open() failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/301/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/301/tap-master-files/cov_stat.tap].
ok - coverity found no issues for all_301
ok - coverity found no issues for oshmem_301
ok - coverity found no issues for yalla_301
ok - coverity found no issues for mxm_301
ok - coverity found no issues for fca_301
ok - coverity found no issues for hcoll_301

TAP Reports Processing: FINISH
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 65fb9a3b0857cf1221b80883e8c4db9e748c1950 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/301/ and message: Merged build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
rather curious that this failed.  I just added a comment.  Wonder if master is still busted.

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
did a rebase to master to see if that helps

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/305/

**Build Log**
*last 50 lines*

 ```
[...truncated 31000 lines...]
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test mca_base_env_list option in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
test mca_base_env_list option in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ export XXX_C=3 XXX_D=4 XXX_E=5
+ XXX_C=3
+ XXX_D=4
+ XXX_E=5
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
++ grep '^XXX_'
++ wc -l
+ val=10
+ '[' 10 -ne 10 ']'
+ cat
+ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpicc -o /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/env_mpi /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/env_mpi.c
+ echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/env_mpi
++ grep '^XXX_'
++ wc -l
+ val=6
+ '[' 6 -ne 10 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/305/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/305/tap-master-files/cov_stat.tap].
ok - coverity found no issues for all_305
ok - coverity found no issues for oshmem_305
ok - coverity found no issues for yalla_305
ok - coverity found no issues for mxm_305
ok - coverity found no issues for fca_305
ok - coverity found no issues for hcoll_305

TAP Reports Processing: FINISH
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/d897893fbb0df67feb4ba16abbe1930519b9c794
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8ac297fe357bbe93c134b198103e2bf6a4f39e8f to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/305/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
this is a new test added to jenkins. 
the trunk has no fix yet for it. (-am file.conf not working)
will disable it till fix goes in.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/306/

**Build Log**
*last 50 lines*

 ```
[...truncated 5226 lines...]
mv -f .deps/libltdlc_la-lt__alloc.Tpo .deps/libltdlc_la-lt__alloc.Plo
/bin/sh ./libtool --tag=CC   --mode=link gcc  -DNDEBUG -O3 -g -fvisibility=hidden -module -avoid-version  -o dlopen.la  dlopen.lo -ldl -ldl  -lrt -lm -lutil   -lrt -lm -lutil  
mv -f .deps/libltdlc_la-lt_dlloader.Tpo .deps/libltdlc_la-lt_dlloader.Plo
mv -f .deps/libltdlc_la-preopen.Tpo .deps/libltdlc_la-preopen.Plo
libtool: link: ar cru .libs/dlopen.a .libs/dlopen.o 
libtool: link: ranlib .libs/dlopen.a
libtool: link: ( cd ".libs" && rm -f "dlopen.la" && ln -s "../dlopen.la" "dlopen.la" )
mv -f .deps/libltdlc_la-slist.Tpo .deps/libltdlc_la-slist.Plo
mv -f .deps/libltdlc_la-ltdl.Tpo .deps/libltdlc_la-ltdl.Plo
/bin/sh ./libtool --tag=CC   --mode=link gcc  -DNDEBUG -O3 -g -fvisibility=hidden -no-undefined -dlpreopen dlopen.la   -o libltdlc.la  libltdlc_la-preopen.lo libltdlc_la-lt__alloc.lo libltdlc_la-lt_dlloader.lo libltdlc_la-lt_error.lo libltdlc_la-ltdl.lo libltdlc_la-slist.lo lt__strl.lo -ldl  -lrt -lm -lutil   -lrt -lm -lutil  
libtool: link: rm -f .libs/libltdlc.nm .libs/libltdlc.nmS .libs/libltdlc.nmT
libtool: link: (cd .libs && gcc -DNDEBUG -O3 -g -fvisibility=hidden -c -fno-builtin  -fPIC -DPIC "libltdlcS.c")
libtool: link: rm -f ".libs/libltdlcS.c" ".libs/libltdlc.nm" ".libs/libltdlc.nmS" ".libs/libltdlc.nmT"
libtool: link: (cd .libs/libltdlc.lax/dlopen.a && ar x "/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/libltdl/./.libs/dlopen.a")
libtool: link: ar cru .libs/libltdlc.a .libs/libltdlc_la-preopen.o .libs/libltdlc_la-lt__alloc.o .libs/libltdlc_la-lt_dlloader.o .libs/libltdlc_la-lt_error.o .libs/libltdlc_la-ltdl.o .libs/libltdlc_la-slist.o .libs/lt__strl.o .libs/libltdlcS.o  .libs/libltdlc.lax/dlopen.a/dlopen.o 
libtool: link: ranlib .libs/libltdlc.a
libtool: link: rm -fr .libs/libltdlc.lax
libtool: link: ( cd ".libs" && rm -f "libltdlc.la" && ln -s "../libltdlc.la" "libltdlc.la" )
make[4]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/libltdl'
test -z "/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib" || /bin/mkdir -p "/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib"
test -z "/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/include" || /bin/mkdir -p "/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/include"
test -z "" || /bin/mkdir -p ""
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/libltdl'
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/libltdl'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/libltdl'
Making install in asm
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/asm'
rm -f atomic-asm.S
  CC       asm.lo
ln -s "../../opal/asm/generated/atomic-local.s" atomic-asm.S
/bin/sh: ../../config/depcomp: No such file or directory
make[2]: *** [asm.lo] Error 127
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/asm'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make: *** [install-recursive] Error 1
+ exit 10
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/d897893fbb0df67feb4ba16abbe1930519b9c794
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8ac297fe357bbe93c134b198103e2bf6a4f39e8f to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/306/ and message: Merged build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/309/
Test PASSed.

**Comment by hppritcha** [comment]
This commit addresses a request by @roblatham00 in #430 to add a more verbose comment about the MPIO_DATATYPE_ISCOMMITTED macro.

**Pull request merged**
