### PR TITLE
v2.x: updated API oshmem examples to OSHMEM 1.3

### PR DESCRIPTION
**Pull request by karasevb**
cherry picked from commit e894a89

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/cbe90989627c156718a3ec91b5360b9e

**Comment by hppritcha** [comment]
This PR needs a reviewer

**Comment by jsquyres** [comment]
I do not see a corresponding commit on master.

All PRs to release branches must contain commits that exist on / are cherry-picked+ported from master.

**Comment by jsquyres** [comment]
@karasevb If you could update the commit message to include the cherry-pick notice, that would be great.  Thanks.

Git pro tip: If you `git cherry-pick -x ...` (i.e., use the `-x` option), it pre-seeds your commit message with a last line that looks like this:

```
(cherry picked from commit e894a89)
```

To fix the commit on this PR, you can just `git commit --amend` and manually put that line at the bottom of the message, and then `git push --force` to your branch (fixing up a PR like this is just about the *only* valid reason to force push).  If you do that, the new commit+message will show up here on the PR.

**Comment by karasevb** [comment]
@jsquyres Please check.
Thank you for the tip!

**Comment by jsquyres** [comment]
@karasevb Perfect; thanks.

@hppritcha When CI finishes, this PR is good to go.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Pull request merged**
