### PR TITLE
mtl/ofi: Remove unused variables, and check ompi_ret

### PR DESCRIPTION
**Pull request by lrbison**
Fix two issues in mtl/ofi found by Coverity.

### CODE REVIEW

**Comment by jsquyres** [comment]
FWIW: We typically uniquely identify the Coverity issue(s) found and fixed in the Git commit messages.  E.g., "CID 12345".

**Review by jsquyres — APPROVED** [review]
I can attest to the fact that the CID messages are in the commit messages, but another OFI person should review the content of the code changes.  They look nominally correct to me, but I have no way of testing them.

**Review by wenduwan — APPROVED** [review]
Change lgtm. Thanks!

**Review by hppritcha — APPROVED** [review]

**Comment by wenduwan** [comment]
@lrbison Any plan to merge this?

**Comment by lrbison** [comment]
Forgot about this one.  Let me rebase and merge it.  Thanks for the reminder!

**Comment by wenduwan** [comment]
Running AWS internal CI

**Pull request merged**
