### PR TITLE
SSHMEM/COLL: added sshmem/mpi implementation for shmem_collect call

### PR DESCRIPTION
**Pull request by hoopoepg**
- added MPI based implementation of shmem_collect call

Signed-off-by: Sergey Oblomov <sergeyo@mellanox.com>

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:retest

**Comment by hoopoepg** [comment]
bot:retest

**Comment by yosefe** [comment]
bot:retest

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Comment by hoopoepg** [comment]
@jsquyres @hppritcha I see that OMPI failed to build due to infrastructure issues. could you point me to owner of that system to resolve issue?

**Comment by hoopoepg** [comment]
bot:retest

**Pull request merged**
