### PR TITLE
Fix osc/rdma gcc warnings + possible race

### PR DESCRIPTION
**Pull request by awlauria**

### CODE REVIEW

**Comment by hjelmn** [comment]
See #8469.

**Comment by hjelmn** [comment]
Please review #8469 and let me know if there are still issues. The warnings fixes look ok to me.

**Comment by awlauria** [comment]
@hjelmn thanks - didn't see your pr. Merged, I'll rebase this PR if there's anything left.

**Comment by awlauria** [comment]
@hjelmn I rebased with your pr + another fix - I found that this test was failing with  `OMPI_ERR_RMA_RANGE` on a relatively low task count (>= 3):
https://scm.nowlab.cse.ohio-state.edu/svn/mpi/mvapich2/trunk/test/mpi/rma/linked_list_bench_lock_all.c

it looks like a timing gap where rank A hasn't quite finished exposing the memory while B is looking for it. I attempted to patch it, and the test now runs clean for me at 40+ ranks with --oversubscribe. Can you take a look?

**Comment by hjelmn** [comment]
@awlauria Well. For dynamic memory windows they must use an external synchronization method. MPI_Barrier for example. Will look at the test.

**Comment by hjelmn** [comment]
Hmm, though in that test the attach should be complete before the pointer is put in the list. Hmmm. I may need to root cause this.

**Comment by awlauria** [comment]
@hjelmn thanks - I took another look. I think I found some spots where the exclusive lock could use some tightening around some shared variables, specifically when caching the region count. The test is running pretty clean for me now at 100 procs per run on one node - but I'll keep it running for a while to see how it goes.

**Comment by awlauria** [comment]
@hjelmn I took out the 'retry code' and ran these commits over-night. All passed over 10k runs.

**Comment by jsquyres** [comment]
Do we need this on v4.1 as well?

**Comment by awlauria** [comment]
If @hjelmn agrees with the change, then yeah I think it should go to the 4.x.x branches.

**Review by hjelmn — APPROVED** [review]

**Pull request merged**
