### PR TITLE
Fix singleton operations

### PR DESCRIPTION
**Pull request by rhc54**
Cherry-pick several commits from master to fix singleton operations. Includes some partial custom repair of singleton comm_spawn - still some problems that need to be resolved.

Refs #2897 

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
yeah, the rest of the problem with singleton comm_spawn is in the orte layer - i'll address it tomorrow

**Comment by rhc54** [comment]
@hppritcha @jsquyres I would suggest going ahead with this PR and #2897 for now. With the changes in this PR, singletons will work just fine with dstore enabled or disabled. Singleton comm_spawn hangs, but that is a secondary problem and can be dealt with later. I don't have time right now, so I'd suggest someone file an issue for v2.1 and we'll deal with it when time is available.

**Comment by jsquyres** [comment]
@hppritcha Signed-off-by checker failed because @rhc54 cherry-picked some master commits from before we required signed-off-by.  They're commits from @ggouaillardet, who a) is a proven community member, and b) has a signed contribution form on file for commits from before we required signed-off-by.

My $0.02: good to go.

**Comment by hppritcha** [comment]
Note I have a pr in a similar signature sign off issue.   Do we give founding members who commit directly to master without sign offs a pass?   Note that isn't the case with this PR.

**Comment by rhc54** [comment]
This isn't a question of getting a "pass". All we are doing is porting a commit already in our code base over to a release branch. There is no code being introduced into the repository, and so technically no sign-off is required.

New code requires a sign-off, regardless of who is committing it.

**Comment by jsquyres** [comment]
👍  on @rhc54's answer.

**Pull request merged**
