### PR TITLE
v2.x: oshmem: Align OSHMEM API with spec v1.3 

### PR DESCRIPTION
**Pull request by igor-ivanov**
See related PR https://github.com/open-mpi/ompi-release/pull/1041

:bot:assign: @hppritcha
:bot:label:enhancement
:bot:milestone:v2.0.0

@jladd-mlnx please look at this.

### CODE REVIEW

**Comment by jsquyres** [comment]
@igor-ivanov Two things:

1. You don't need to use the `bot:` commands any more -- you can just directly set labels / milestones / assignees.
1. Please rebase on top of the `v2.x` branch again; I literally just merged a fix for the Travis issue.

**Comment by jsquyres** [comment]
@igor-ivanov I'm sorry -- one more clarification: the `bot:` commands *do not work any more*.  So you *need* to go set the label/milestone/assignee(s) yourself.  Sorry for not being clear.

**Comment by jladd-mlnx** [comment]
Non-blocking put and gets.

**Comment by jsquyres** [comment]
@igor-ivanov @jladd-mlnx Is this PR milestoned incorrectly?  It is currently marked for v2.x.  Please update if you intended it for v2.1.0.

**Comment by miked-mellanox** [comment]
:bot:milestone:v2.1.0

**Comment by jladd-mlnx** [comment]
@jsquyres This is ready to go.

**Pull request merged**
