### PR TITLE
osc/rdma, btl: fix two issues with one-sided

### PR DESCRIPTION
**Pull request by wzamazon**
This PR contains a series of patches that aims to fix 

https://github.com/open-mpi/ompi/issues/8983

and 

https://github.com/open-mpi/ompi/issues/7830

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/37f2b0805c6ce06764bb9c85e9542070

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e62bf6d29d28dbe7485e433e33d4a2ab

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d6cd677f88a124039f111dd524099019

**Comment by awlauria** [comment]
bot:aws:retest

java failure.

**Comment by wzamazon** [comment]
Replaced by 3 PRs:

https://github.com/open-mpi/ompi/pull/9694
https://github.com/open-mpi/ompi/pull/9695
https://github.com/open-mpi/ompi/pull/9696

**Pull request closed without merging**
