### PR TITLE
Address Github issue #11532 by translating legacy parameters for direct launches

### PR DESCRIPTION
**Pull request by qkoziol**
Borrow code from the OMPI schizo module in PRRTE that translates legacy MCA parameters when an application is direct launched (PRRTE will translate legacy parameters when natively launched).

Addresses issue https://github.com/open-mpi/ompi/issues/11532

### CODE REVIEW

**Comment by qkoziol** [comment]
Requires PRRTE PR:  https://github.com/openpmix/prrte/pull/1777  and OpenPMIX PR: https://github.com/openpmix/openpmix/pull/3133

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
Hmmmm....why would an MPI process care about PRRTE params? It has no involvement with PRRTE, so the params will just be ignored.

You certainly would want the PMIx values as the MPI proc uses that library - but I cannot see any reason to handle PRRTE params.

**Comment by qkoziol** [comment]
> Hmmmm....why would an MPI process care about PRRTE params? It has no involvement with PRRTE, so the params will just be ignored.
> 
> You certainly would want the PMIx values as the MPI proc uses that library - but I cannot see any reason to handle PRRTE params.

OK - I had a feeling that might be the case.  I'll update this PR to just the refactor of the schizo ompi file then, and remove the other work that creates the framework header.

**Comment by qkoziol** [comment]
Revised to just check PMIX params, and to use the existing PMIX framework header.

**Comment by qkoziol** [comment]
bot:nvidia:retest

**Comment by lrbison** [comment]
bot:nvidia:retest

**Comment by lrbison** [comment]
CI cannot find the file:

```
base/pmix_base_fns.c:43:10: fatal error: pmix/src/include/pmix_frameworks.h: No such file or directory
   43 | #include "pmix/src/include/pmix_frameworks.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I saw in https://github.com/openpmix/openpmix/pull/3133 we expected it to be in ${PREFIX}/include/pmix/src/include.  I'm not sure what the disconnect is here, do we search PREFIX?

**Comment by qkoziol** [comment]
> CI cannot find the file:
> 
> ```
> base/pmix_base_fns.c:43:10: fatal error: pmix/src/include/pmix_frameworks.h: No such file or directory
>    43 | #include "pmix/src/include/pmix_frameworks.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```
> 
> I saw in [openpmix/openpmix#3133](https://github.com/openpmix/openpmix/pull/3133) we expected it to be in ${PREFIX}/include/pmix/src/include. I'm not sure what the disconnect is here, do we search PREFIX?

🤔   It's installed when I compile against the latest OpenPMIX.  I'll try against the internal PMIX submodule and see what I find.  We might need to bump the submodule pointer?

**Comment by rhc54** [comment]
>  43 | #include "pmix/src/include/pmix_frameworks.h"

You are probably hitting an issue between when you build OMPI against an internal vs external version of PMIx. The external reference should be just `src/include/pmix_frameworks.h`. The internal reference would be `pmix/src/include/pmix_frameworks.h` unless you are adding a `-I` option that takes care of the `pmix/` prefix for you.

**Comment by rhc54** [comment]
Yeah, I confirmed that the problem is in the `include` statement - it should be:
```c
#include "src/include/pmix_frameworks.h"
```
Your configure code already adds the necessary `-I` flag to point you at the correct place. It was working for @qkoziol solely because there is another `-I` that points to the OMPI include location that allowed the `pmix/src/include` path to be resolved. Doesn't work if you use an external PMIx installation.

**Comment by awlauria** [comment]
@rhc54 could you review this ?

**Review by jsquyres — APPROVED** [review]

**Comment by qkoziol** [comment]
> @qkoziol can you open up the v5.0 cherrypick

https://github.com/open-mpi/ompi/pull/11921

**Pull request merged**
