### PR TITLE
Use malloc instead of posix_memalign for small (<= sizeof(void *)) alignments

### PR DESCRIPTION
**Pull request by benmenadue**
This works around issue #4564.

Signed-off-by: Ben Menadue <ben.menadue@nci.org.au>

### CODE REVIEW

**Comment by hjelmn** [comment]
Though I did not intend this function to called with an alignment smaller than the malloc alignment. Something is not working as intended but this fix is ok with me.

**Comment by benmenadue** [comment]
The call that triggers it is line 77 of opal/mca/mpool/base/mpool_base_alloc.c:
```
mem = mpool->mpool_alloc (mpool, size, 0, 0);
```

**Comment by hjelmn** [comment]
Yeah, that is a typo. Should have align == 8. Either fixing that typo or allowing a 0 alignment work for me.

**Comment by benmenadue** [comment]
Okay, I've changed the alignment request to `sizeof(void *)` in `mca_mpool_base_alloc`. Other mpools already handle to zero-alignment case (e.g. memkind replaces it with the page size), so I'd suggest keeping the other patch as well.

**Comment by hjelmn** [comment]
Ok, once CI completes I will merge this. I will open the PRs to the release branches.

**Pull request merged**
