### PR TITLE
Libtool 2 4 6

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by rhc54** [comment]
FWIW: we technically also require automake 1.15, but the configury hasn't been updated for it

**Comment by ggouaillardet** [comment]
@rhc54 thanks, i updated the PR accordingly
fwiw, UH does not meet the requirements (and i already reported it to Brian and Edgar).
also, it seems there is not a ready-to-use ```libtool``` package for travis on linux

**Comment by bwbarrett** [comment]
ompi:bot:retest

Think I now have the new autotools installed everywhere...

**Comment by bwbarrett** [comment]
ompi:bot:retest

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by ggouaillardet** [comment]
:bot:ompi:retest

**Comment by ggouaillardet** [comment]
@bwbarrett there is something really odd with this platform

```
  GitHub pull request #3602 of commit 44922e882f9f7dfc2fe7c15fd17518423425e538, no merge conflicts.
```
so far so good
```
Checking out Revision 22631832cebeceede6fe17e55b5f37cfde817943 (refs/remotes/origin/master)
```
a bit odd to me, but maybe this is the way Jenkins is working

```
--> running ./autogen.pl 
Open MPI autogen (buckle up!)

1. Checking tool versions

   Searching for autoconf
     Found autoconf version 2.69; checking version...
       Found version component 2 -- need 2
       Found version component 69 -- need 69
     ==> ACCEPTED
   Searching for libtoolize
     Found libtoolize version 2.4.2; checking version...
       Found version component 2 -- need 2
       Found version component 4 -- need 4
       Found version component 2 -- need 2
     ==> ACCEPTED
   Searching for automake
     Found automake version 1.13.4; checking version...
       Found version component 1 -- need 1
       Found version component 13 -- need 12
     ==> ACCEPTED
```
first, we did not test this PR, since the requirement should have been ```libtool``` >= ```2.4.6```.
incidentally, the "old" libtool is still used on this platform

**Comment by bwbarrett** [comment]
@ggouaillardet I'm not sure where you're pulling that info from.  The reason it hasn't passed CI is that CI used the system autotools.  It was never intended for Open MPI to *REQUIRE* those newer versions of AM and LT; the autogen.pl ones were the earliest we *knew* worked.  Unfortunately, PMIx took a different strategy and we now are scrambling to fix the CI test suites to have newer versions of the autotools.  So CI will basically be broken until we do.  sigh.

**Comment by ggouaillardet** [comment]
@bwbarrett i am sorry i failed to include the link. the console logs are available at  https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/459/Platform=amazon_linux_17.03/console

there are two points here
1. this PR should have failed at the very beginning of ```autogen.pl```, since this PR explicitly requires ```libtool``` >= ```2.4.6``` (so it will not fail later in PMIx). It looks jenkins tested the master branch instead of the this PR (for debugging purpose, you might invoke ```git log | head -n 100``` before invoking ```autogen.pl``` in https://raw.githubusercontent.com/open-mpi/ompi-scripts/master/jenkins/open-mpi-build-script.sh
2. your previously wrote "Think I now have the new autotools installed everywhere..." . unless i misunderstood this statement, i wanted to point that the latest autotools (```libtool >=2.4.6``` and ```automake >= 1.15.0``` are not used (installed ? at the right place ?) on the ```amazon_linux_17.03``` platform

fwiw, i do not remember any email stating newest autotools are now required (e.g. the ones provided by RHEL7 cannot be used any more), but that being said, the web site is up-to-date https://www.open-mpi.org/source/building.php

**Comment by bwbarrett** [comment]
From that web page:
```The following table lists the versions that are used to make nightly Open MPI tarballs. Other versions may work, but these are the versions that we know work.```

So those are not the minimums, they're how we build tarballs.  Not the same thing.  But it doesn't matter, because PMIx has now raised the minimum.  Sigh.

**Comment by ggouaillardet** [comment]
fair enough.
sadly, my two points are still valid

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by rhc54** [comment]
@jsquyres and I had a long chat about the "intent" of the web page vs how people interpret it. Worth a discussion in the f2f in July. Needless to say, I do not agree with the interpretation put forward here, nor does Intel in general as it caused considerable issues here.

**Comment by bwbarrett** [comment]
What's the big problem at Intel?  Besides, you've already made the decision for everyone, so why have the discussion?

**Comment by rhc54** [comment]
Sigh. I keep saying this over and over, so let me try once again. I couldn't possibly care less _what_ versions we require, so long as we _test_ for them. @jsquyres pointed out that we raised these levels for a very good reason - there were problems on some distros at the lower levels, and we hit them when going thru rc testing. So if we need to leave them higher, then we should _test_ for them.

**Comment by bwbarrett** [comment]
This is ridiculous.  The web page is clear.  We should test for the features we need and the versions that provide those features.  Let's talk in person if you want to continue this insanity.  But I've just spent the entire day cleaning up the mess that was pushing this update without discussion and I'm too tired to continue arguing.   I was the one who wrote all the checks how ever many years ago when we originally had this discussion, and the whole point to requiring back versions was because developers didn't like installing the most recent versions when the older versions worked (which, as these tests have seen), they still do in most cases.

**Comment by ggouaillardet** [comment]
bottom line, PMIx was updated and no more requires ```libtool >= 2.4.6``` nor ```automake > 1.15.0```, so there is no more point to keep this PR open..

**Comment by jsquyres** [comment]
I had written up an RFC last night with the result of my conversations with everyone yesterday (@rhc54, @bwbarrett, ..etc.).  I didn't send it out last night because I wanted to re-read (and edit) it this morning with a clear head.

It looks like the issue is still not entirely settled, so I'll modify the focus of it and send it out a bit.  I'll put the timeout as the F2F meeting.

In the meantime, since we all keep arguing about the wording of the web page, I'll just change the wording of the web page to be exactly what the current definition of those values are

***sidenote:*** Github seems to be having serious problems right now; I don't know if/when this comment will actually get posted

**Pull request closed without merging**
