### PR TITLE
sessions: fix hetero builds

### PR DESCRIPTION
**Pull request by hppritcha**
related to #9097
related to #9972

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by jsquyres** [comment]
@hppritcha I still get a compile failure:

```
$ git rev-parse HEAD
6a5a87ff746c3662b12b54a89e22495eb1b97687

$ ./configure --prefix=/home/jsquyres/bogus --enable-heterogeneous --enable-mpirun-prefix-by-default --enable-debug --enable-mem-debug --enable-mem-profile --enable-mpi-fortran
...

$ make
...
make[1]: Entering directory `/home/jsquyres/git/ompi/ompi/mca/pml/ob1'
  CC       pml_ob1.lo
In file included from pml_ob1.h:42,
                 from pml_ob1.c:55:
pml_ob1_hdr.h: In function ‘mca_pml_ob1_send_cid’:
pml_ob1_hdr.h:553:1: error: inlining failed in call to always_inline ‘ob1_hdr_hton_intr’: function not considered for inlining
 ob1_hdr_hton_intr(mca_pml_ob1_hdr_t *hdr, const uint8_t hdr_type,
 ^~~~~~~~~~~~~~~~~
pml_ob1_hdr.h:551:5: note: called from here
     ob1_hdr_hton_intr((mca_pml_ob1_hdr_t*)h, t, p)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pml_ob1_hdr.h:592:6: note: in expansion of macro ‘ob1_hdr_hton’
      ob1_hdr_hton (next_hdr, next_hdr->hdr_common.hdr_type, proc);
      ^~~~~~~~~~~~
make[1]: *** [pml_ob1.lo] Error 1
make[1]: Leaving directory `/home/jsquyres/git/ompi/ompi/mca/pml/ob1'
make: *** [all-recursive] Error 1
```

**Comment by hppritcha** [comment]
@jsquyres what compiler version are you using?  i'm using gcc 9.1.0.

**Comment by jsquyres** [comment]
```
$ gcc --version
gcc (GCC) 8.2.0
```

I can try again with gcc 10.something.

**Comment by jsquyres** [comment]
I get the same error with gcc 10.2.  Is it perhaps the other configure flags I'm using?

```
$ ./configure --prefix=/home/jsquyres/bogus --enable-heterogeneous --enable-mpirun-prefix-by-default --enable-debug --enable-mem-debug --enable-mem-profile --enable-mpi-fortran
...
```

**Review by bosilca — APPROVED** [review]

**Comment by jsquyres** [comment]
I'm not sure why this PR was merged, it may fix *a* problem, but it doesn't fix *all* the heterogeneous build problems.

As I stated above, I'm still getting compile errors, even after this PR was merged:

```
[6:44] savbu-usnic-a:~/g/o/o/m/p/ob1 (master)
$ make
  CC       pml_ob1.lo
In file included from pml_ob1.h:42,
                 from pml_ob1.c:55:
pml_ob1_hdr.h: In function ‘mca_pml_ob1_send_cid’:
pml_ob1_hdr.h:553:1: error: inlining failed in call to ‘always_inline’ ‘ob1_hdr_hton_intr’: function not considered for inlining
  553 | ob1_hdr_hton_intr(mca_pml_ob1_hdr_t *hdr, const uint8_t hdr_type,
      | ^~~~~~~~~~~~~~~~~
pml_ob1_hdr.h:551:5: note: called from here
  551 |     ob1_hdr_hton_intr((mca_pml_ob1_hdr_t*)h, t, p)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pml_ob1_hdr.h:592:6: note: in expansion of macro ‘ob1_hdr_hton’
  592 |      ob1_hdr_hton (next_hdr, next_hdr->hdr_common.hdr_type, proc);
      |      ^~~~~~~~~~~~
make: *** [pml_ob1.lo] Error 1
```

This error is occurring squarely in the middle of a `#if OPAL_ENABLE_HETEROGENEOUS_SUPPORT` block.

**Comment by bosilca** [comment]
It did fix the hetero compilation for me.

**Comment by jsquyres** [comment]
> It did fix the hetero compilation for me.

Good for you.  😄   But I clearly stated above, multiple times, that this PR did not solve the problem.

**Pull request merged**
