### PR TITLE
OSHMEM: Initial fix for the memory scaling issue

### PR DESCRIPTION
**Pull request by artpol84**
TODO: open the PR against master.

### CODE REVIEW

**Comment by hoopoepg** [comment]
@artpol84 it seems failed check of e-mail address

**Comment by hppritcha** [comment]
What's the issue associated with this PR?

**Comment by artpol84** [comment]
@hppritcha no issue, I can create one

**Comment by artpol84** [comment]
Closing this one, a correct fix will be opened soon.

**Pull request closed without merging**
