### PR TITLE
io/ompio: move io/ompio functionality to common/ompio

### PR DESCRIPTION
**Pull request by edgargabriel**
- set up the infrastructure for mca/common/ompio 
- move the printqueue functionality to its new location
- move internal read/write/open/close functionality to its new location

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/56872b8a6e4819a04736383bc540bc5a

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/bcc226e062d6899a1aadedf52dd3a3f8

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/e5a54ec28f368e254569b6b5e82f67ce

**Comment by edgargabriel** [comment]
bot:retest

**Comment by edgargabriel** [comment]
the mellanox error has nothing to do with this pr. Will retry later again

--2016-07-28 23:12:28--  (try: 6)  http://www.mcs.anl.gov/~thakur/thread-tests/thread-tests-1.1.tar.gz
23:12:28 Connecting to www.mcs.anl.gov|140.221.6.95|:80... failed: Connection timed out.
23:13:31 Retrying.

**Comment by jsquyres** [comment]
@Di0gen @jladd-mlnx I've been told by the MPICH team that ANL's DNS can be flakey at times.  You might want to get the 1.1 thread tests from the ompi-tests git repo instead...?  Might be more reliable.

**Comment by edgargabriel** [comment]
bot:mellanox:retest

**Comment by edgargabriel** [comment]
As a small heads up: since this commit will require to re-autogen the source tree, I will wait until later tonight to merge it. It touches a lot of files (73), but all within the ompio universe. Most changes are also fairly minuscule (i.e. very often just changing an include statement in the file etc.)

**Comment by jsquyres** [comment]
I wouldn't worry about requiring a re-autogen in the middle of the work day any more.

We used to, but a) autogen is faster these days, and b) laptops/servers are faster these days.

So while I appreciate your consideration of others, I don't think you need to wait.  😄

**Comment by edgargabriel** [comment]
ok, sounds good :-) will merge .

**Pull request merged**
