### PR TITLE
MCA component aliasing support

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca, @jsquyres, @hppritcha The commits in this PR give one way we could handle component aliasing. There is one downside and that is that when scanning for available DSO components it is required that DSO component be dlopen'ed to find the name alias.

Please take a look and make comments.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by bosilca** [comment]
On some systems opening all the DSO components might be a very costly operation. How about adding yet another MCA parameter to enable this behavior? Small systems can have the aliasing enabled by default, and sysadmins of large systems will be able to turn it off in the etc config file (and educate their users accordingly).

**Comment by hjelmn** [comment]
Thats probably the best way forward. Sysadmins of larger systems could make btl/vader a static component if they want the alias.

**Comment by ibm-ompi** [comment]
Test passed.

**Pull request closed without merging**
