### PR TITLE
Update PMIx/PRRTE submodule pointers

### PR DESCRIPTION
**Pull request by rhc54**
Remove debug and silence errant error message.

Refs https://github.com/open-mpi/ompi/issues/12195

### CODE REVIEW

**Comment by rhc54** [comment]
@wenduwan This will silence the errant warning/error messages on the `main` branch

**Comment by wenduwan** [comment]
Testing this PR in AWS internal CI.

**Comment by wenduwan** [comment]
Internal CI passed.

**Comment by wenduwan** [comment]
@dalcinl Do you want to test this PR for https://github.com/open-mpi/ompi/issues/12195?

**Review by wenduwan — APPROVED** [review]

**Comment by rhc54** [comment]
Probably better to commit this so the warnings and debug output go away - fixing the other problem will probably take a few days.

**Review by dalcinl — APPROVED** [review]

**Review by bosilca — APPROVED** [review]

**Pull request merged**
