### PR TITLE
Expose PMIx tools

### PR DESCRIPTION
**Pull request by rhc54**
Provide users with a mechanism for seeing how the embedded PMIx was
built and what PMIx MCA params are supported. Fix a strange issue with
how the PMIX_CONFIGURE_CLI value gets passed to pmix_info.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a8fa7507dbdda7770bd98ef53096bc94

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
I'm not aware of us coming up with any suggestions on a solution to the disable-dlopen problem here. Unless someone has one, I propose to (sadly) abandon the attempt. The only option I could think of would be to just not expose the tools if disable-dlopen is given, but I don't know if that is acceptable.

**Comment by rhc54** [comment]
Abandoning as "don't know how to do it"

**Pull request closed without merging**
