### PR TITLE
[v5.0.x] opal/ofi: package rank calculation bugfix

### PR DESCRIPTION
**Pull request by wenduwan**
The current implementation has an out-of-bound bug that process_info->my_local_rank could exceed package_ranks array length. This patch eliminates package_ranks array and fixes the bug.

Signed-off-by: Wenduo Wang <wenduwan@amazon.com>
(cherry picked from commit 9046276bdfd9f42ac9cdfb6c4a19e66314cb29de)

This commit was missed in https://github.com/open-mpi/ompi/pull/11739

### CODE REVIEW

**Comment by wenduwan** [comment]
@gpaulsen @awlauria Hi could you please review the change? The current v5.0.x branch is broken for MTL OFI without this backport.

**Review by hppritcha — APPROVED** [review]

**Comment by wenduwan** [comment]
@hppritcha Thanks for looking! Shall we merge directly?

**Comment by wenduwan** [comment]
Rebased branch.

**Comment by wenduwan** [comment]
Ready for merge.

**Pull request merged**
