### PR TITLE
v4.0.x: usnic fixes and optimizations

### PR DESCRIPTION
**Pull request by jsquyres**
See individual commit messages for more details.

### CODE REVIEW

**Comment by gpaulsen** [comment]
Sorry, too late for v4.0.2, moving to v4.0.3

**Comment by jsquyres** [comment]
@gpaulsen @hppritcha Can you approve and merge?  I have no one left in the OMPI community who can review usNIC stuff, so I got a co-worker to review it for me (but he doesn't have write perms to the OMPI repo, so his review "doesn't count" in terms of github's requirements).  

Thanks.

**Comment by jsquyres** [comment]
Yes, I probably could/should have made that explanation better.

The real reason was that I merged the commits on master before getting the code review.  In the code review, it came out that it really wasn't necessary to increase the timeout -- 5 miliseconds is long enough already.  The real reason for (effectively) that timeout being too short was the lack of a cap on retransmitting during a single iteration of usNIC progress.  I.e., when sending many large messages to a very large number of peers, we could get into a situation where the retransmit queue got *so* long that it effectively took longer to retransmit everything than the retrans timers on the sends.  Hence, by the time we finished retransmitting everything, at least some of the timers had already expired, which would then lead to immediately retransmitting again, ...etc.  Meaning: the retrans timer wasn't the issue.  The amount of work we allowed to happen during a single iteration of usNIC progress was the problem.

**Comment by gpaulsen** [comment]
Thanks @bwbarrett for reviewing.
@hppritcha and I haven't yet opened the v4.0.x for merging, but once we open that, we'll get this in.

**Comment by hppritcha** [comment]
Ready to merge imho

**Pull request merged**
