### PR TITLE
v4.1: Ignore receive buffer at non-root for cuda reduce collective

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
cherry pick of https://github.com/open-mpi/ompi/pull/10329

### CODE REVIEW

**Comment by Akshay-Venkatesh** [comment]
Hi @jsquyres. Can you review this PR? Also, when possible, can you point out why git commit checker was unhappy? Thanks!

**Comment by jsquyres** [comment]
@Akshay-Venkatesh If you click through the details link of the git commit checker, it tells you why it was unhappy:

Screen Shot 2022-04-27 at 2 22 49 PM

**Comment by Akshay-Venkatesh** [comment]
> @Akshay-Venkatesh If you click through the details link of the git commit checker, it tells you why it was unhappy:
> 
> Screen Shot 2022-04-27 at 2 22 49 PM

@jsquyres Strange because it's not a cherry-pick commit.

**Comment by awlauria** [comment]
@Akshay-Venkatesh the usual work-flow is to bring this to `main` first and cherry-pick from there.

**Comment by jsquyres** [comment]
You can just make a master PR and get that merged.  Then update the commit on this PR to include the cherry pick message, referring to the final commit hash of the corresponding master commit.  Then the git commit checker will be happy.

Remember: cherry picks aren't _actually_ tracked by git.  All the git commit checker checks for on the v4.1.x branch is that there is a cherry pick message in the git commit message, and that the hash(es) that it refers to exist in the main Open MPI git repo (i.e., you're not referring to a commit that either doesn't exist, or refers to a commit on a PR that hasn't been merged yet).

Make sense?

**Review by bosilca — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:aws:retest

**Pull request merged**
