### PR TITLE
test conda with OSX

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs #2068

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/1c0802e7daeff8b5aa6889d53fdd37d0

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/2746fecf92fda4d80ff1b80b23edbfc7

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/56872b8a6e4819a04736383bc540bc5a

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/2746fecf92fda4d80ff1b80b23edbfc7

**Comment by jjhursey** [comment]
Something is broken with the internal IBM CI script - disregard the IBM CI failures for now. I'll look into the problem tomorrow. For now I have disabled the IBM CI tests.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ggouaillardet** [comment]
test was successful, now closing this PR

**Pull request closed without merging**
