### PR TITLE
Cleanup handle verbose messages

### PR DESCRIPTION
**Pull request by rolfv**
Some updates due to @jsquyres review on release branch.

### CODE REVIEW

**Comment by jsquyres** [comment]
@miked-mellanox Got some kind of oshmem_init() failure in this jenkins test.  Is that related to this PR, or is it a different issue?

**Comment by miked-mellanox** [comment]
looking at it

**Comment by hjelmn** [comment]
@miked-mellanox I see the problem. memheap is using opal_dss incorrectly. I will submit a fix shortly.

**Comment by miked-mellanox** [comment]
yep, it came from the "merge" which is donefor every PR

Merge was done on Sept 12:

see http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-merge/

from build number 680.

**Comment by miked-mellanox** [comment]
I can set set jenkins to send email to the list if "merge event" build fails.
Now it sends email only to me 
(for merge build there is no place in the github to update visual status)

what do you think?

**Comment by jsquyres** [comment]
Sure, let's try it and see how it goes.  Thanks!

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by jsquyres** [comment]
@rolfv This is one now good to go, so I think if you add it to open-mpi/ompi-release#580, it should also be good to go.

**Pull request merged**
