### PR TITLE
Topic/orte cr continue like restart

### PR DESCRIPTION
**Pull request by adrianreber**
Enabling the FT code breaks compilation (again). This series tries to fix the compiler errors. This is again only fixing the compiler errors without any warranty that the result might actually support FT again.

Most of the code I am touching with these patches is #ifdef'd FT and once this is committed I would also like to start a FT enabled MTT to early catch FT code breakage.

@jjhursey

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/177/
Test PASSed.

**Comment by jsquyres** [comment]
@rhc54 I note in the 2nd patch:

> The FT code used barrier mechanisms which have been removed
> with aec5cd0. This patch replaces
> all those different barriers with opal_pmix.fence(NULL, 0);
> I am not sure this is completely correct but at least a starting
> point for a review.

Can you comment on this?

**Comment by rhc54** [comment]
@adrianreber What would be required to let this code build all the time so we quit breaking it? With the new attributes capability, can we change this to a conditional use as opposed to conditional build?

**Comment by adrianreber** [comment]
@rhc54 I can try to move the FT code to be runtime selectable. What would be the right way to make the decision during runtime to take the FT code paths? Can you point me at an example where the attributes are already used to  make similar runtime decisions?

**Comment by mellanox-github** [comment]
* Coverity found 916 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_343/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_343/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_343/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/343/
Test PASSed.

**Comment by adrianreber** [comment]
As discussed via mail with @rhc54. I rebased these PR and would like to merge it. Right now it touches only FT code.

**Comment by rhc54** [comment]
Go for it!

**Pull request merged**
