### PR TITLE
v2.0.x: disable hwloc CUDA support when relevant

### PR DESCRIPTION
**Pull request by jsquyres**
Refs #4248.

@hppritcha I'm not 100% convinced, but it *may* be desirable to commit this fix to the v2.0.x branch.

### CODE REVIEW

**Comment by hppritcha** [comment]
@jsquyres yeah let's fix this in 2.0.x too.

**Comment by jsquyres** [comment]
Working through issues identified on #4251.

**Comment by jsquyres** [comment]
@ggouaillardet New commit added to this v2.x PR.

**Comment by jsquyres** [comment]
@hppritcha This v2.0.x PR updated.  Can you review?

**Comment by hppritcha** [comment]
had to kill off armv8 testing.
bot:lanl:retest

**Comment by jsquyres** [comment]
bot:ompi:retest

**Pull request merged**
