### PR TITLE
osc/pt2pt multithread fixes

### PR DESCRIPTION
**Pull request by jjhursey**
Fixes for Issue #2614 

Currently a work in progress.

### CODE REVIEW

**Comment by hjelmn** [comment]
@jjhursey I am addressed these issues. Looks like I forgot to change some things when I added the synchronization structure. Will have a PR up soon.

**Comment by jjhursey** [comment]
@hjelmn The sounds good. Once you have your version of the PR we can close this one, and @markalle and I will test/review. Thanks!

**Comment by hjelmn** [comment]
@jjhursey Sorry it took so long for me to look at this. The commits here helped me narrow down some of the more egregious errors... Did I ever mention I intensely dislike active target? We really need to remove that from the standard. What an odd concept.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ac6a1f2f8a43992f5432c6f872195c8d

**Comment by jjhursey** [comment]
@markalle @hjelmn Do we need this PR any more?

**Comment by jjhursey** [comment]
This PR has grown stale. We can reopen if we need it later. @markalle If the problem is still present let's make sure there is an Issue to track progress.

**Pull request closed without merging**
