### PR TITLE
rmaps/base: remove debugging "DONE" message

### PR DESCRIPTION
**Pull request by jsquyres**
Thanks for Ben Menadue for reporting and supplying the patch.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
@artpol84 @Di0gen Is Mellanox Jenkins having connectivity problems?  It couldn't git clone this PR.

bot:mellanox:retest

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by artpol84** [comment]
@jsquyres looks like this time it worked fine

**Pull request merged**
