### PR TITLE
11392 cp v5.0.x beautification

### PR DESCRIPTION
**Pull request by zerothi**
Cherry-picked #11392 to v5.0.x
```shell
git log --pretty=format:%H 15d969085~..9f7c9bb5ee > docs-cp
git cherry-pick -x $(tac docs-cp)
```

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Review by jsquyres — APPROVED** [review]
TIL `tac`

**Comment by zerothi** [comment]
> 

?

**Comment by jsquyres** [comment]
TIL = today I learned 😄

**Comment by zerothi** [comment]
> TIL = today I learned smile

TIL TIL

**Comment by gpaulsen** [comment]
Thanks for these important Doc updates!

**Comment by zerothi** [comment]
Hope it will be of use to the community!

**Pull request merged**
