### PR TITLE
ompi/oshmem: fix bug in shmem_alltoall in mca/scoll/basic.

### PR DESCRIPTION
**Pull request by xinzhao3**
Signed-off-by: Xin Zhao <xinz@mellanox.com>

### CODE REVIEW

**Comment by xinzhao3** [comment]
ref to #4984

**Comment by xinzhao3** [comment]
@jladd-mlnx @bureddy

**Comment by xinzhao3** [comment]
@bwbarrett re-pushed, please review again.

**Comment by jladd-mlnx** [comment]
🍒 -picked from af32c30

**Pull request merged**
