### PR TITLE
Update the PMIx and PRRTE pointers

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jsquyres** [comment]
Oops -- didn't mean to have the PMIx PR close this PR.

**Comment by rhc54** [comment]
@jsquyres Not sure why this would be the only place to hit such an error:
```
  CC       libpmixglobal.lo
In file included from ../../../../../../3rd-party/openpmix/src/include/libpmixglobal.c:20:0:
/home/ubuntu/workspace/open-mpi.build.distcheck/src/openmpi-gitclone/_build/sub/3rd-party/openpmix/src/include/pmix_config.h:29:41: fatal error: src/include/pmix_config_top.h: No such file or directory
compilation terminated.
```

**Comment by rhc54** [comment]
Hmmm....got same error when AWS is trying to build the nightly PMIx tarball:
```
Starting build for master
Found new revision 2a0f0b7
Exceuting run-with-autotools.sh failed:
make  all-am
make[4]: Entering directory '/mnt/data/nightly-tarball/scratch/pmix/master-202011030225/pmix.git/pmix-master-202011030225-2a0f0b7/_build/sub/src/include'
 CC       libpmixglobal.lo
In file included from ../../../../src/include/libpmixglobal.c:20:0:
/mnt/data/nightly-tarball/scratch/pmix/master-202011030225/pmix.git/pmix-master-202011030225-2a0f0b7/_build/sub/src/include/pmix_config.h:29:41: fatal error: src/include/pmix_config_top.h: No such file or directory
compilation terminated.
Makefile:784: recipe for target 'libpmixglobal.lo' failed
```

**Comment by rhc54** [comment]
Seeing the following when doing "make_dist_tarball" on the Mac:
```
make[3]: warning: -jN forced in submake: disabling jobserver mode.
  CC       pevent.o
/bin/sh: ../../../../../config/getdate.sh: No such file or directory
  CCLD     pevent
```
I also see that `pmix_config_top.h` is not in the build include tree, so that might be the issue. Again, though, it doesn't fail on my Mac. I suspect it is failing only on the one AWS platform because that is the only place that does "make distcheck".

**Comment by rhc54** [comment]
@jsquyres I'm getting reports of broken builds of PMIx due to variations in Python behavior across specific versions. I think we are going to have to remove dictionary.h from automatic generation and go back to generating it prior to release where we have more control of the environment.

In our efforts to fix the integration problem, we appear to have broken something in the PMIx build system. I suspect the best path forward is for me to first take us back on the dictionary generation, and then try to figure out what is going on with the srcdir issue for getdate as that is a separate problem. I'll tackle the dictionary part in the morning.

**Comment by rhc54** [comment]
@jsquyres Well, we are down to this error:
```
Traceback (most recent call last):
  File "../../../../../../3rd-party/openpmix/contrib/construct_dictionary.py", line 247, in main
    constants = open(outpath, "w+")
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/workspace/open-mpi.build.distcheck/src/openmpi-gitclone/3rd-party/openpmix/include/dictionary.tmp'
```
Not sure how to get around that one! It is during "make distcheck".

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
