### PR TITLE
mtl/ofi: require libfabric 1.9 or higher

### PR DESCRIPTION
**Pull request by hppritcha**
one way to address issue #10954

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
(cherry picked from commit 0c5f275fb2741dd62ba46c37907a7ccdb3546a20)

### CODE REVIEW

**Comment by awlauria** [comment]
@wckzhang please review.

**Comment by gpaulsen** [comment]
@wckzhang can you please review?

**Comment by wckzhang** [comment]
I'll look at this today

**Review by wckzhang — APPROVED** [review]

**Comment by jsquyres** [comment]
Per my comments on #10954, I'm not a fan of this PR.  It effectively means that RHEL7 users can't use libfabric without upgrading.

**Pull request closed without merging**
