### PR TITLE
Update submodules: openpmix, prrte and config/oac

### PR DESCRIPTION
**Pull request by raafatfeki**

### CODE REVIEW

**Comment by raafatfeki** [comment]
@bwbarrett and @jsquyres  Could you please review this pr? 
Also, I am not sure why some of the tests fail unlike branch v5.0.x

**Comment by jsquyres** [comment]
@raafatfeki Can you please update this PR?

**Comment by raafatfeki** [comment]
I'm not sure what causes the problem with Jenkins CI. I cannot check the details of failing check: (jenkins.open-mpi.org took too long to respond.) Also, the branch seems to have some conflicts.

**Comment by jsquyres** [comment]
> I'm not sure what causes the problem with Jenkins CI. I cannot check the details of failing check: (jenkins.open-mpi.org took too long to respond.) Also, the branch seems to have some conflicts.

I cited the problem, above (see https://github.com/open-mpi/ompi/pull/11456#issuecomment-1456442976) -- it's during `make distcheck`.

**Comment by rhc54** [comment]
If I might make two suggestions:

1. remove the 3rd-party/openpmix and 3rd-party/prrte submodule updates from this PR - there are separate PRs regularly updating those submodule pointers and you cannot possibly keep up with it
2. someone please provide some advice to @raafatfeki as to how to resolve the problem. I'm not sure myself how he resolves it - it might require some changes to the code that constructs the "authors" file.

**Comment by bwbarrett** [comment]
The issue is that the script which generates the AUTHORS file requires a single email name be found in the git logs for any email address.  Previous commits had the user name "raafatfeki", but this commit has the user name "Raafat Feki".  The easiest way to fix this is to add a change to the .mailmap file:

```
% git diff                                                              130 ↵ ✹
diff --git a/.mailmap b/.mailmap
index cc7a39bf49..bfb9340fa6 100644
--- a/.mailmap
+++ b/.mailmap
@@ -134,3 +134,5 @@ William P. LePera <lepera@us.ibm.com>
 George Katevenis <gkatev@ics.forth.gr>
 
 Brian Barrett <brian@bbarrett.org>
+
+Raafat Feki <fekiraafat@gmail.com>
```

**Pull request closed without merging**
