### PR TITLE
Ensure we fail if remote nodes cannot find executable

### PR DESCRIPTION
**Pull request by jjhursey**
* Ref PR #4792

### CODE REVIEW

**Comment by jsquyres** [comment]
@jjhursey could you add commit b643852 to this PR?

**Comment by jjhursey** [comment]
It didn't apply cleanly, so I'll have to investigate a bit. I'll try to get it done today.

**Comment by bosilca** [comment]
Outside the errors in the CI things looks good. I confirm that the original patch works in master.

**Comment by jjhursey** [comment]
@bosilca I tested the current v3.1.x HEAD without this patch and it seems to be working correctly.

Can you double check the commands below that I am trying to reproduce the same problem you are encountering.

```
[jjhursey@node03] orte-dvm --host node03:2,node04:2,node05:2 --system-server &
[1] 104250
DVM ready

[jjhursey@node03] prun -n 1 -H node05 ./bogus
[node03:104285] Job failed to spawn: The specified executable could not be executed
[jjhursey@node03] prun -npernode 1 -H node05 hostname
node05
[jjhursey@node03] prun -npernode 1 -H node04,node05 hostname
node05
node04
[jjhursey@node03] prun -n 1 -H node05 hostname
node05
[jjhursey@node03] prun -npernode 1 -H node04,node05 ./bogus
[node03:104351] Job failed to spawn: The specified executable could not be executed
[jjhursey@node03] prun -npernode 1 -H node04,node05 bogus
[node03:104357] Job failed to spawn: The specified executable could not be found
[jjhursey@node03] prun -npernode 1 -H node05 bogus
[node03:106523] Job failed to spawn: The specified executable could not be found
[jjhursey@node03]
```

**Comment by bosilca** [comment]
I confirm this is not necessary on the current 3.1. Thanks @jjhursey for investigating.

**Comment by jjhursey** [comment]
Ok. I'll close this PR then, and the one for v3.0.x. Thank for the confirmation.

**Pull request closed without merging**
