### PR TITLE
Topic/v4.0.x/from pr7190 7192

### PR DESCRIPTION
**Pull request by gpaulsen**
Fix spelling mistakes in comments.

### CODE REVIEW

**Comment by gpaulsen** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

not sure what's going on.  output from autogen.pl looks different from when I run by hand on same file system at cori.

**Comment by gpaulsen** [comment]
@hppritcha uh... that's weird.  Do we need to diagnose before we create v4.0.3rc1 ?   How different is it?

**Pull request merged**
