### PR TITLE
Add support for FI_CONTEXT2 in OFI MTL and BTL.

### PR DESCRIPTION
**Pull request by mwheinz**
This change reserves more space, allowing the OFI MTL and BTL to work
with both providers that use FI_CONTEXT and those that use FI_CONTEXT2.

Refs: #8928

Signed-off-by: Michael Heinz <mheinz@cornelisnetworks.com>

### CODE REVIEW

**Comment by mwheinz** [comment]
Cherry-picked from #8931

**Comment by mwheinz** [comment]
Okay - what's the required format for the missing cherry-pick message in the commit?

**Comment by awlauria** [comment]
Just need to add `-x` to the cherry-pick.

**Comment by mwheinz** [comment]
Sigh. Okay. Still having problems with dragging in other changes. Killing this PR.

**Pull request closed without merging**
