### PR TITLE
v2.0.x: pmix: fix PMIx_server_register_nspace() usage

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by hppritcha** [comment]
@ggouaillardet door is closed on 2.0.2.  it will probably be released tomorrow's

**Comment by ggouaillardet** [comment]
@hppritcha that should not be a big deal since i only ran into this bug with master so far

**Comment by hppritcha** [comment]
trying out LANL's OS-X check with this PR
bot:lanl:retest

**Comment by hppritcha** [comment]
okay fix the script for os-x.  try again
bot:lanl:retest

**Comment by hppritcha** [comment]
well just compile using os-x for now.
bot:lanl:retest

**Comment by hppritcha** [comment]
ignore os-x build problems.

**Comment by ggouaillardet** [comment]
:bot:lanl:retest

**Pull request merged**
