### PR TITLE
v4.1.x: UCX: initialize cuda from ucx pml component

### PR DESCRIPTION
**Pull request by bureddy**
Signed-off-by: Devendar Bureddy <devendar@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
why is this needed?

**Comment by awlauria** [comment]
Please add the -x to the cherry-pick, so we know what master commit it came from. Thanks!

**Comment by awlauria** [comment]
@yosefe are you asking about the change in general or why it is needed for 4.1? Master/5.0 pr is here:
https://github.com/open-mpi/ompi/pull/7893

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Review by yosefe — APPROVED** [review]

**Review by brminich — APPROVED** [review]

**Pull request merged**
