### PR TITLE
romio 3.4b1 refresh

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hppritcha I was able to setup a Lustre testbed, and found that the root cause of the hdf5 failure in #8249 is ROMIO 3.3.2.
it can be evidenced with mpich 3.3.2 configure'd with `--with-file-system=ufs+nfs+lustre`.

This new PR (ROMIO 3.4b) passes the `testphdf5`, could you please give it a try?

**Comment by hppritcha** [comment]
I'll try this next week.

**Comment by hppritcha** [comment]
this PR appears to address the HDF5 failures I was seeing with master.

**Comment by ggouaillardet** [comment]
@hppritcha As far as I am concerned, this PR is ready for a final review and primetime

**Comment by ggouaillardet** [comment]
@markalle could you please give this PR a try?

are any of the 3 patches you referenced in #6871 needed here?

**Comment by ggouaillardet** [comment]
Note to myself, MPICH `3.4rc1` has been released.

I will either update this PR, or open a new one if this `3.4b1` refresh gets merged before.

**Comment by jsquyres** [comment]
Thanks for continuing to monitor MPICH upstream, @ggouaillardet.  Given that OMPIO is now the default for Lustre, I think we might as well hold off on merging this PR until MPICH 3.4 goes final.

**Comment by awlauria** [comment]
FYI: @markalle has two pending PR's to MPICH:

https://github.com/pmodels/mpich/pull/4948
https://github.com/pmodels/mpich/pull/4956

Not sure when they will be picked up. @markalle are others pending?

@jsquyres

**Comment by ggouaillardet** [comment]
Closing this PR in favor of #8343 (based on MPICH 3.4)

**Pull request closed without merging**
