### PR TITLE
v4.1.x: Fix compilation issue in OFI with CUDA

### PR DESCRIPTION
**Pull request by jtamzn**
This patch to fix compilation issue in #11381

bot:notacherrypick

### CODE REVIEW

**Comment by jsquyres** [comment]
Thanks for the fix!  Does this fix also apply to the `main` branch?

**Comment by wenduwan** [comment]
> Thanks for the fix! Does this fix also apply to the `main` branch?

Thanks for looking at the issue! `main` branch does not have this problem so we do not need to apply the fix.

**Comment by jtamzn** [comment]
@jsquyres no, we believe main/5.0.x is good. I think it only applies to v4 branch.

**Comment by jsquyres** [comment]
Ok, if it's not needed on `main`, then `bot:notacherrypick` is appropriate -- I see you already added that.

**Review by lrbison — APPROVED** [review]

**Review by bwbarrett — CHANGES_REQUESTED** [review]
I don't think this is the wrong fix for what is actually a bad merge in 55d35010bd0.

**Comment by gbkokq278** [comment]
> I don't think this is the wrong fix for what is actually a bad merge in [55d3501](https://github.com/open-mpi/ompi/commit/55d35010bd0c624c2763ca2e4ac28177b1d4eaab).

ok. This could be the case, but could you elaborate it? The commit you mentioned is >1 years ago. Did you mean these lines should not be merged at all?
```
#if OPAL_CUDA_SUPPORT
    mca_common_cuda_fini();
#endif
```

**Comment by bwbarrett** [comment]
Yeah, there's no reason for the OFI MTL on the 4.1.x series to have any CUDA code in it at all.  It shouldn't be closing it, and it looks like it's just a bad merge that brought it in.

**Comment by gbkokq278** [comment]
> Yeah, there's no reason for the OFI MTL on the 4.1.x series to have any CUDA code in it at all. It shouldn't be closing it, and it looks like it's just a bad merge that brought it in.

That sounds more reasonable. I was thinking there were some backported CUDA code there. If it is a bad merge we should remove CUDA code around.

**Comment by jtamzn** [comment]
> Yeah, there's no reason for the OFI MTL on the 4.1.x series to have any CUDA code in it at all. It shouldn't be closing it, and it looks like it's just a bad merge that brought it in.

Oh I forget switching github account.

Actually this sounds more reasonable to me. I was thinking that could be a backported CUDA code. If not, we should remove it.

**Comment by jtamzn** [comment]
@bwbarrett I updated the PR to remove blocking cuda related code here. However, upon checking the file, there is an additional block also calling in Line 911 as 
```
#if OPAL_CUDA_SUPPORT
    /**
     * Some providers do not require the use of the CUDA convertor
     * in OMPI and its use will cause performance degradation. The
     * following providers will disable it when selected.
     */
    if (!strncmp(prov->fabric_attr->prov_name, "psm3", 4)
        || !strncmp(prov->fabric_attr->prov_name, "psm2", 4))
    {
        ompi_mtl_ofi.base.mtl_flags |= MCA_MTL_BASE_FLAG_CUDA_INIT_DISABLE;
    }
#endif /* OPAL_CUDA_SUPPORT */
```
It doesn't preventing compilation and compiled bin can pass OSU microbenchmark. Are these lines legit here? If not, we should remove them, too.

**Comment by bwbarrett** [comment]
I think that code should be fine, and since it doesn't reference any CUDA calls, doesn't need the include you asked about.

**Review by bwbarrett — APPROVED** [review]

**Pull request merged**
