### PR TITLE
fix f08 bindings

### PR DESCRIPTION
**Pull request by ggouaillardet**
only define the unique fortran symbol depending on
 - CAPS
 - PLAIN
 - SINGLE_UNDERSCORE
 - DOUBLE_UNDERSCORE
and bind the f08 symbol to the uniquely defined C symbol

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres let's close #232 and continue with #432 
from now, i will focus on code generation in order to replace 4-way "#if UPPER_CASE / #elif LOWER_CASE / #elif ..." conditional blocks as you advised

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/297/

**Build Log**
*last 50 lines*

 ```
GitHub pull request #432 of commit c4c60ff880f4eb10c5b929c2b244a3f81f52149d automatically merged.
Setting status of c4c60ff880f4eb10c5b929c2b244a3f81f52149d to PENDING with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/297/ and message: Merged build started.
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/open-mpi/ompi
 > /usr/bin/git init /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace # timeout=60
Fetching upstream changes from https://github.com/open-mpi/ompi
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git4393568473600312755.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
 > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
Pruning obsolete local branches
Fetching upstream changes from https://github.com/open-mpi/ompi
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git5484424241543218031.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/pull/*:refs/remotes/origin/pr/* --prune # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
Build was aborted
Aborted by anonymous
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of c4c60ff880f4eb10c5b929c2b244a3f81f52149d to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/297/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/303/
Test PASSed.

**Comment by ggouaillardet** [comment]
@jsquyres i wrote mpi-gen-mangling.sh in order to generate the include files
(this is a shell script, i simply cannot write perl ...)

**Comment by ggouaillardet** [comment]
@jsquyres i wont be able to look at this before thursday (this is golden week in Japan)

**Comment by jsquyres** [comment]
@ggouaillardet No prob.  Thanks!

**Comment by jsquyres** [comment]
Just to put the audit trail here on Github, I filed a PR against @ggouaillardet's tree with some changes to this PR: https://github.com/ggouaillardet/ompi/pull/2

**Comment by hppritcha** [comment]
Can one of the admins verify this patch?

**Comment by ggouaillardet** [comment]
i will work on that today

**Comment by ggouaillardet** [comment]
will continue tomorrow ... the initial problem is not (yet) fixed :-(

**Comment by mellanox-github** [comment]
* Coverity found 911 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_518/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_518/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_518/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/518/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 911 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_522/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_522/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_522/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/522/
Test PASSed.

**Comment by ggouaillardet** [comment]
@jsquyres could you please review this (again) ?
i squashed quite a lot of commits to make it easier to read.
assuming we can agree on the f08 bind'ing to C mangled symbols, this PR is ready for primetime

**Comment by hppritcha** [comment]
bot:retest

**Comment by jsquyres** [comment]
Heh -- I made some comments on the 2nd commit, and then realized that the 3rd commit pretty much entirely reverts the first 2 commits.  :-)

You should probably squash these all together, then, and make a good commit message for the resulting 1 commit.

**Pull request merged**
