### PR TITLE
Topic/ime: Bring over IME component from master to v4.1

### PR DESCRIPTION
**Pull request by raafatfeki**
Bring over IME component from master, compatible with the version 4.1.
PS: In order to avoid conflicts, this pull request is based on the branch 4.1 + the code changes related to gpfs component. So, I recommend to process the gpfs pull request #7814 first.

This pull request contains the equivalent of all commits in master related to IME:
ccc96efc2ebbbb9a9e8ccdbbf7010ea4fa63c86a, 7b2d83c898bf43def11b16762d7f8403b72f3a7b (Applied IME related changes only to avoid any changes on lustre or pvfs2 component), 01ae0c22b8d7f4ddbbb0fa45064e22b926c05e26, f16d2903aa4254adc33c72253b48ed114f998c96.

### CODE REVIEW

**Comment by jsquyres** [comment]
@raafatfeki @edgargabriel Looks like merging in #7814 caused some conflicts in this PR.  😦  Can you guys have a look?

**Comment by raafatfeki** [comment]
> @raafatfeki @edgargabriel Looks like merging in #7814 caused some conflicts in this PR. frowning Can you guys have a look?
> 
> (the conflicts look pretty trivial to resolve)
We rebased our branch and solved the conflicts, it should be alright now.

**Comment by jsquyres** [comment]
> We rebased our branch and solved the conflicts, it should be alright now.

Thanks!

**Comment by bwbarrett** [comment]
bot:aws:retest

**Pull request merged**
