### PR TITLE
pr-checks: compile with rocm support

### PR DESCRIPTION
**Pull request by edgargabriel**
add a github actions workflow to perform a compilation including the rocm software stack.

Signed-off-by: Edgar Gabriel <Edgar.Gabriel@amd.com>
(cherry picked from commit 67cbfd1eb4238e0b449c34c4d98a5bd64198e0d1)

### CODE REVIEW

**Comment by jsquyres** [comment]
bot:ibm:retest

**Review by jsquyres — APPROVED** [review]

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Pull request merged**
