### PR TITLE
Cherry pick commits from master to fix help text output regarding PSM2_CUDA

### PR DESCRIPTION
**Pull request by aravindksg**

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
Your commit messages mention conflicts.

Does this mean that PSM2 in this PR is diverging from master?  Is that what you intended?

More specifically: is there a reason to have PSM2 diverge from master?  (that might be ok -- I'm just asking if you thought through those scenarios)

**Comment by aravindksg** [comment]
@jsquyres : Yes, There are couple of commits missing from this branch. Both are not critical to be pulled into this branch as yet (commit 6fb81f2 and commit 701a1d0). The conflicts itself were minor: Regarding copyright lines in header and in `ompi_mtl_psm2_component_register()` function.

**Comment by aravindksg** [comment]
@jsquyres : Any further concerns?

**Comment by jsquyres** [comment]
I have no further concerns.  @matcabral should probably review.

**Comment by matcabral** [comment]
It looks OK to me.

**Pull request merged**
