### PR TITLE
v5.0.x: docs: update for Python 3.12

### PR DESCRIPTION
**Pull request by jsquyres**
Use "r" (raw) strings for the regexp.

Signed-off-by: Jeff Squyres <jeff@squyres.com>
(cherry picked from commit 208dabec651e420784276ff72d2ad00e90beb4bd)

This is the v5.0.x version of main PR #12311

### CODE REVIEW

**Comment by wenduwan** [comment]
Will merge after 5.0.2 release.

**Comment by wenduwan** [comment]
@jsquyres Could you please fix the conflict?

**Comment by jsquyres** [comment]
> @jsquyres Could you please fix the conflict?

What conflict?

**Comment by wenduwan** [comment]
Github complains your branch is out-of-date - I clicked rebase just now. I think it should work.

**Review by wenduwan — APPROVED** [review]

**Comment by jsquyres** [comment]
@wenduwan There was no conflict.  Being out-of-date as not a problem.

**Pull request merged**
