### PR TITLE
v5.0.x: bugfix/#11257 mca atomic ucx cswap stack smashing

### PR DESCRIPTION
**Pull request by roiedanino**
Signed-off-by: Roie Danino <rdanino@nvidia.com>
(cherry picked from commit ae529715bb9343e03f8751fc6164116ae69fd872)

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
bot:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
The IBM CI is tripping over the `.gitmodules` on the `v5.0.x` branch vs `main`. In particular the `v5.0.x` branch is missing [this](https://github.com/open-mpi/ompi/commit/7dbfbeea4cc71b7b1b467b6dc30c6c3c40669e8f) commit.

It looks like PR https://github.com/open-mpi/ompi/pull/11309 is already posted for `v5.0.x` to fix this issue. @open-mpi/ompi-rm-5-0-x Please merge PR 11309 then retest this branch.

**Comment by janjust** [comment]
bot:retest

**Comment by janjust** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
@roiedanino I need to ask a favor. Can you rebase this cherry-pick branch on the latest `v5.0.x` to pick up the submodule pointer update? It's not an issue with the PR but a limitation of the current IBM CI pipeline (it uses your branch, not a merge of your branch -- something we need to fix).

**Comment by roiedanino** [comment]
@jjhursey Is this ok?

**Comment by jjhursey** [comment]
It's almost there, but what you have will make CI happy. I think you need to update your `v5.0.x` branch first. Something like (assuming `upstream` points to the Open MPI upstream repo):
```
git checkout v5.0-bugfix/#11257-mca-atomic-ucx-cswap-stack-smashing
git fetch upstream
git rebase upstream/v5.0.x
git push
```

Thanks for your patience and help. I almost have the backed IBM CI sorted out to avoid this issue in the future.

**Comment by janjust** [comment]
@jjhursey is this ready to merge?

**Comment by jjhursey** [comment]
Yep, this is good to merge. Thanks for your help and patience!

**Pull request merged**
