### PR TITLE
ess/hnp: add support for forwarding additional signals

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds support to the hnp ess module to forward additional
signals beyond the default SIGUSR1, SIGUSR2, SIGSTP, and SIGCONT.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@rhc54 Would like this for 1.10.6 but we can do local patching if you do not want to accept it. It is technically an enhancement but in 1.8.x because the user's processes were in the same process group as mpirun they were able to catch the SIGURG (23) signal from rank 0. This was a fluke but they were relying on it.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/aec9ef4b7a317f4c1e8ad235dd28d455

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/0d7a8780827f4ea0e7ab464298117db8

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/8d6c625722cb2b5240fb577a12c8566e

**Comment by rhc54** [comment]
I submitted a PR against this branch to generalize things a bit - see what you think

**Comment by hjelmn** [comment]
Looks good. Would you be ok with that in 1.10.6? I think the only real difference between ess/hnp in master and v1.10 is the orte_forward_job_control stuff.

**Comment by rhc54** [comment]
Yeah, I think so - it resolves a regression in terms of behavior, so it should be okay.

**Comment by hjelmn** [comment]
Ok, I cleaned out the show help I had added now that it is unused. Squished it into my original commit.

**Comment by hjelmn** [comment]
Found a minor leak. If you are ok with it I will do a fixup into your commit.

**Comment by rhc54** [comment]
sure - thx!

**Comment by rhc54** [comment]
@hjelmn I think I goofed and included SIGTERM in that list - IIRC, we don't forward that signal, but rather trap it separately. You might want to check and ensure we don't include anything in the forwarding list that is being handled separately.

**Comment by hjelmn** [comment]
@rhc54. Yeah. Looks like SIGTERM is handled here:

https://github.com/open-mpi/ompi/blob/master/orte/mca/ess/hnp/ess_hnp_module.c#L191

Will double-check the others.

**Comment by hjelmn** [comment]
Looks like the only other one is SIGHUP.

**Comment by hjelmn** [comment]
Ok. That should do it:

```
mpirun -mca ess_hnp_forward_signals SIGTERM hostname
[mordor.lanl.gov:50511] CAN NOT FORWARD SIGNAL: SIGTERM
mpirun -mca ess_hnp_forward_signals SIGFOO hostname
[mordor.lanl.gov:50522] UNSUPPORTED SIGNAL: SIGFOO
mpirun -mca ess_hnp_forward_signals 10b hostname
[mordor.lanl.gov:50532] INVALID SIGNAL: 10b
```

Let me know if it all looks ok.

**Comment by hjelmn** [comment]
Ok, made it a little better. Now only does one search for existing signal and can catch trying to forward SIGTERM by signal number. Also added SIGKILL to the can not forward list.

**Comment by rhc54** [comment]
My apologies, but I'm sure someone (ahem) will complain if we don't use ```show_help``` for error messages. See what you think of this last PR: https://github.com/hjelmn/ompi/pull/11

**Comment by jsquyres** [comment]
Oh, interesting -- the signed-off-by-checker dinged the merge commit for not being signed.  I would ignore this.  Someday maybe I'll have cycles to add an exception for that (i.e., signed-off-by checker should probably ignore merge commits).

**Comment by hjelmn** [comment]
@jsquyres Ok. Going to merge this now so I can get the v1.10, v2.0, and v2.x PRs open.

**Pull request merged**
