### PR TITLE
sys limits: fixed soft limit setting if it is less than hard limit

### LINKED ISSUE #7728: mpirun was unable to start the specified application as it encountered an error code: 63
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
master, v4.0.x and possibly older

### Please describe the system on which you are running

* Operating system/version: Red Hat Enterprise Linux Server 7.6 
* Computer hardware: AMD EPYC 7702

-----------------------------

## Details of the problem
Starting mpirun at single node results in the following error:
```bash
export PRRTE_MCA_prrte_set_max_sys_limits=1
mpirun -n 128 hostname

--------------------------------------------------------------------------
mpirun was unable to start the specified application as it encountered an
error:

Error code: 63
Error name: Proc appears to be stalled
Node: jazz12

when attempting to start process rank 0.
--------------------------------------------------------------------------
```

Check ulimits:
```bash
$ulimit -a
...
open files                      (-n) 1024
...

// Current and max limits
$cat /proc/594/limits
Limit                     Soft Limit           Hard Limit           Units
...
Max open files            1024                 2048                 files
...
```

Manually set `ulimit -n 2048` avoids the problem. But according exported `set_max_sys_limits=1` prte should altered the limit to the max value (2048), that is not happens:
```
Breakpoint 1, prrte_util_init_sys_limits (errmsg=0x7fffffffc990) at sys_limits.c:110
110        char **lims, **lim=NULL, *setlim;
(gdb) n
111        int i, rc = PRRTE_ERROR;
(gdb)
115        if (NULL == prrte_set_max_sys_limits) {
(gdb)
120        lims = prrte_argv_split(prrte_set_max_sys_limits, ',');
(gdb)
121        if (NULL == lims) {
(gdb)
126        for (i=0; NULL != lims[i]; i++) {
(gdb)
127            lim = prrte_argv_split(lims[i], ':');
(gdb)
128            if (1 == prrte_argv_count(lim)) {
(gdb)
129                setlim = "max";
(gdb)
138            if (0 == strcmp(lim[0], "1")) {
(gdb)
141                    prrte_setlimit(RLIMIT_NOFILE, "max", &value)) {
(gdb)
140                if (PRRTE_SUCCESS !=
(gdb)
145                prrte_sys_limits.num_files = value;
(gdb) p value
$1 = 1024    <- the limit value didn't changed
```

As far as I understand, the supposed fix should be:
```patch
diff --git a/src/util/sys_limits.c b/src/util/sys_limits.c
index 1ed14755bb..fba3337f0f 100644
--- a/src/util/sys_limits.c
+++ b/src/util/sys_limits.c
@@ -76,7 +76,7 @@ static int prrte_setlimit(int resource, char *value, rlim_t *out)
 
     if (0 <= getrlimit(resource, &rlim)) {
         if (rlim.rlim_max < maxlim) {
-            rlim_set.rlim_cur = rlim.rlim_cur;
+            rlim_set.rlim_cur = rlim.rlim_max;
             rlim_set.rlim_max = rlim.rlim_max;
         } else {
             rlim_set.rlim_cur = maxlim;
```
@rhc54 Please confirm if that is the correct limit alternation.

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to https://github.com/openpmix/prrte/pull/553
Closes #7728

Should be cherry-picked to v4.0.x

### CODE REVIEW

**Comment by rhc54** [comment]
ok to test

**Comment by karasevb** [comment]
@bwbarrett could you please take a look at Amazon CI?

**Comment by jsquyres** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
@karasevb would you mind cherry-picking to the 4.0.x branch? Thanks.

**Pull request merged**
