### PR TITLE
Unable to compile the PSM2 MTL due to missing #include.

### PR DESCRIPTION
**Pull request by mwheinz**
This fixes issue #8684 by adding the include for minmax.h.

### CODE REVIEW

**Comment by jsquyres** [comment]
@mwheinz Did you include @awlauria's 3 commits on purpose?  I.e., are you showing an implicit dependency on some other PR?

**Comment by mwheinz** [comment]
> @mwheinz Did you include @awlauria's 3 commits on purpose? I.e., are you showing an implicit dependency on some other PR?

No, I did not intend to... not sure how that happened.

**Comment by mwheinz** [comment]
I'm going to close this till I figure out what happened.

**Comment by awlauria** [comment]
I've done this before as well. Git can be fickle. You could have rebased those commits out of this branch and force-pushed. But whatever is easiest.

**Comment by mwheinz** [comment]
In this case it was easier to just nuke the branch and redo it.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request closed without merging**
