### PR TITLE
sessions: plug hole in support for sessions erh

### PR DESCRIPTION
**Pull request by hppritcha**
related to #11407

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
@jjhursey please review when you have a chance

**Review by jjhursey — APPROVED** [review]

**Review by abouteiller — APPROVED** [review]

**Pull request merged**
