### PR TITLE
ompi: pml ucx: fix race when ompi request is released

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe  please review
Signed-off-by: Alex Mikheev <alexm@mellanox.com>

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
os-x issue may be due to not scrubbing build area before starting.  try again
bot:lanl:retest

**Comment by yosefe** [comment]
@hppritcha can we merge this? 10x

**Comment by jsquyres** [comment]
@yosefe Howard and I are not the release managers for v1.10 -- Ralph (@rhc54) is.  You guys need to remember to set milestones on non-master PRs.

**Pull request merged**
