### PR TITLE
ompi_datatype_create_subarray: fix lower and upper bound.

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Daniel Garmann for reporting this issue

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@bosilca can you please have a look
that fixes the issue initially reported at http://www.open-mpi.org/community/lists/users/2015/12/28142.php

**Comment by hppritcha** [comment]
@miked-mellanox could you check these hcoll mlnx failures?

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by bosilca** [comment]
@ggouaillardet I would prefer to go with a slightly more optimized version (bosilca/ompi@feeab178). Moreover, I think a similar fix is missing in the darray case, which my patch provides.

**Comment by ggouaillardet** [comment]
@bosilca @edgargabriel i pushed your commits and credited the users who reported this.
i will make the PRs from now, assign them to me and mark them as reviewed

**Comment by hppritcha** [comment]
@jsquyres do we need this in 2.0.0 rc2?

**Comment by jsquyres** [comment]
@ggouaillardet Did this not get PR'ed to v2.0.0?

**Comment by ggouaillardet** [comment]
Iirc, @basilica did commit his slightly different fix, and did pr this for
v1.10 and v2.x

I will double check this on Monday

**Comment by jsquyres** [comment]
@ggouaillardet Thanks!

**Comment by ggouaillardet** [comment]
i did commit @bosilca fix for the missing resize, and @edgargabriel for the ompio issue.
all three commits landed into the v1.10 branch, but two did not land into the v2.x branch (!)

i made PR open-mpi/ompi-release#915 and open-mpi/ompi-release#916 for that

when they pass the tests, i will assign these PR to myself and mark them as reviewed (i did not author these fixes)

**Comment by jsquyres** [comment]
Thanks @ggouaillardet

**Pull request merged**
