### PR TITLE
Topic/configury xrc 4

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
@jsquyres could you please give this PR a try on RHEL6.5 (which has broken ibverbs devel headers) ?

i also updated the PR for the 3 release branches
- open-mpi/ompi-release#384
- open-mpi/ompi-release#385
- open-mpi/ompi-release#386

**Comment by rhc54** [comment]
@ggouaillardet Jeff is on vacation this week. However, I note that this PR failed one of the Jenkins tests - you might want to click on Details and then the Console button to find out why

**Comment by ggouaillardet** [comment]
i did ... and to me, that looks like a jenkins issue specific to LANL-Cray XC
@hppritcha can you please have a look at this ?

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
