### PR TITLE
v4.0.x: oshmem: remove unnecessary dependencies to ORTE

### PR DESCRIPTION
**Pull request by hppritcha**
either use OPAL or OMPI layers, since ORTE layer
is not present when PMIx RTE is used

related to #8106

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>
(cherry picked from commit 10cb9f6f9ea4c32f0efcda1b96606b965f8f9da0)

Conflicts:
	oshmem/info/info.c
	oshmem/mca/memheap/base/memheap_base_select.c
	oshmem/mca/spml/ikrit/spml_ikrit_component.c

### CODE REVIEW

**Comment by jsquyres** [comment]
@hppritcha Do we need this in v4.1.x as well?

**Comment by hppritcha** [comment]
PR #8981

**Comment by bwbarrett** [comment]
Is there a benefit to this patch, given that ORTE will remain in the 4.0/4.1 series?  I worry about some of these changes from a side-effect impact (like changing the orte -> ompi show help behaviors.  If there's an advantage we should do it, but this seems like a big change to bring in on a release branch.  I'm really uncomfortable with this for the 4.1 release branch, for example.

**Review by gpaulsen — APPROVED** [review]

**Comment by gpaulsen** [comment]
This should prevent oshmem from needing to link against orte.

**Comment by gpaulsen** [comment]
Waiting on input from nVidia.  @janjust

**Comment by janjust** [comment]
Closing due to concerns over the potential side effects this may bring into release branches. Issue #8106 will remain open until further discussion.

**Pull request closed without merging**
