### PR TITLE
Plug two memory leaks in rdma osc

### PR DESCRIPTION
**Pull request by devreal**
Detected while working on #5915 

Signed-off-by: Joseph Schuchart <schuchart@hlrs.de>

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by hjelmn** [comment]
Please PR to v4.0.x.

**Pull request merged**
