### PR TITLE
Minor makefile updates

### PR DESCRIPTION
**Pull request by jsquyres**
See individual commit messages.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2f33ed1906e24791f992fbf7e4887ed5

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6f9fb7a891275f51e4e7cdac18b393ee

**Review by bosilca — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
IBM CI had a bad weekend (sorry about that). We should be all good now.

**Pull request merged**
