### PR TITLE
v5.0.x: Fix script ompi/tools/wrappers/ompi_wrapper_script.in

### PR DESCRIPTION
**Pull request by jolivain**
When open-mpi is compiled with script wrapper compilers option:

    ./configure --prefix=/path/to/ompi --enable-script-wrapper-compilers

The final generated wrapper fails to execute.  For example, with command:

    /path/to/ompi/bin/mpicc -o /tmp/hello_c -O2 -Wall /path/to/sources/ompi/examples/hello_c.c
    ...
    Execution of /path/to/ompi/bin/mpicc aborted due to compilation errors.

There is several minor issues fixed in this pull request.  The detail of each issue is described in each commit message.

This pull request was tested on Fedora 36 x86_64 (Perl v5.34.1, gcc 12.2.1).
The hello_c example was successfully compiled with the `mpicc` wrapper and executed with `./mpirun /tmp/hello_c`

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Review by jsquyres — APPROVED** [review]
@bwbarrett Can you review as well?

**Comment by jsquyres** [comment]
@jolivain These commits are excellent -- thank you! Note that our development process is to first PR changes to `main` and then cherry-pick / port them across to the relevant release branches.  You'll notice that one of the CI tests on this PR failed because these commits are not cherry picks from main.

Can you PR these commits to main, and then update the commits in this PR with the typical `git cherry-pick -x ...` message (`(cherry picked from commit ...)`) indicating their "source" commits on the `main` branch?

**Comment by jolivain** [comment]
Hi @jsquyres

Thanks for the review.  Sorry about the wrong branch submission.  As my first contribution to open-mpi, github redirected me here https://docs.open-mpi.org/en/main/contributing.html
There was no mention about this flow.  As a small improvement, I suggest you add a note about that (i.e. version branches are restricted to cherry-pick from main).

As discussed, I'll create a new PR with those commits on main branch.  Once merged, I'll update this one with the cherry-picked message.

Thanks!

**Comment by jsquyres** [comment]
> Thanks for the review. Sorry about the wrong branch submission. As my first contribution to open-mpi, github redirected me here https://docs.open-mpi.org/en/main/contributing.html There was no mention about this flow. As a small improvement, I suggest you add a note about that (i.e. version branches are restricted to cherry-pick from main).

Good point -- will do.
 
> As discussed, I'll create a new PR with those commits on main branch. Once merged, I'll update this one with the cherry-picked message.

Excellent; thanks!

**Review by bwbarrett — APPROVED** [review]

**Comment by jsquyres** [comment]
@jolivain We just merged #10792 on `main` -- can you update the commit messages on this PR to have the appropriate `(cherry picked....)` messages?

**Comment by jsquyres** [comment]
@jolivain Thank you!

**Pull request merged**
