### PR TITLE
ompi: remove obsolete c++ bindings

### PR DESCRIPTION
**Pull request by hjelmn**
The C++ bindings were removed from the standard in MPI-3.0. This
commit removes the entirety of the C++ bindings as well as the
support configury.

Signed-off-by: Nathan Hjelm <hjelmn@google.com>

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres If you prefer I can close this PR so you can do this yourself. Let me know.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a2d1a142428d066d5d543ae8dc0de051

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9934e6d4356519ebceebc099c0b244a5

**Comment by jsquyres** [comment]
@hjelmn CI and I found a few more things to be deleted.  I'm out of time at the moment, but will keep looking for more things to delete.

I don't care if this is your PR/commit or mine.  😉

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c5198903bb64e393817888803df56e1e

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fa3d0b748bd66a54037d692d3e38ab82

**Comment by jsquyres** [comment]
@hjelmn Rebased and re-added the `--with-cxx-*` `configure` CLI options to make a hard-fail if someone uses them.

**Comment by jsquyres** [comment]
As expected, the "enable C++" CI testing is failing.

**Comment by rhc54** [comment]
@jsquyres Can we go ahead and commit this? I need to add some more things to the "deleted" configure option m4.

**Comment by jsquyres** [comment]
@rhc54 No, this PR isn't ready yet.  Do you want to cherry pick the 5aea4446288db9207fbc60f23ee903b149217121 commit out of this (i.e., rename deprecated -> deleted), and then do whatever you want to do on top of that?

I'll deal with any conflicts that creates for this PR.

**Comment by rhc54** [comment]
will do

**Comment by hjelmn** [comment]
So, who updates Jenkins to not enable the C++ bindings?

**Comment by jsquyres** [comment]
Let me have a look in ompi-scripts.

**Comment by jsquyres** [comment]
bot:aws:retest

**Comment by jsquyres** [comment]
@hjelmn I just fixed conflicts and force pushed.  We'll see how CI does.  Should we squash down to a single commit?  I.e., is there value in multiple commits on this PR?

**Comment by hjelmn** [comment]
@jsquyres Squished. Please review.

**Comment by jjhursey** [comment]
@artemry-mlnx is the Mellanox pipeline stuck? I see jobs queued, but nothing has run since yesterday.
 * https://dev.azure.com/mlnx-swx/mellanox-ompi/_build?definitionId=12&_a=summary&view=runs

**Comment by artemry-mlnx** [comment]
@jjhursey 
Thanks for the follow up.
The CI agent was crashed. I've restarted it.
I'll check what was wrong and need to think about agent health monitoring.

**Comment by jsquyres** [comment]
@hppritcha Looks like there's still a Jenkins pipeline job to run `--enable-mpi-cxx` configuration.  Can you disable that job for master?

https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.configure_options/6082/

**Comment by hppritcha** [comment]
> @hppritcha Looks like there's still a Jenkins pipeline job to run `--enable-mpi-cxx` configuration. Can you disable that job for master?
> 
> https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.configure_options/6082/

yes I'll turn that off

**Comment by hppritcha** [comment]
> > @hppritcha Looks like there's still a Jenkins pipeline job to run `--enable-mpi-cxx` configuration. Can you disable that job for master?
> > https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.configure_options/6082/
> 
> yes I'll turn that off

turned off, but for all branches.  looks like its not straightforward to have different options for different branches.  would take some exploring and don't have time at the moment.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
Sorry @hjelmn -- I found some more C++ stuff that had to be deleted.  Check out the additional commit I pushed.

**Comment by hjelmn** [comment]
Squashed.

**Pull request merged**
