### PR TITLE
v2.0.x: fortran/base: rename strings.h into fortran_base_strings.h

### PR DESCRIPTION
**Pull request by ggouaillardet**
rename ompi/mpi/fortran/base/strings.h so it does not get pulled
when /usr/include/strings.h is expected.

Refs open-mpi/ompi#3639

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

(cherry picked from commit open-mpi/ompi@08526e8adc63d2985fbb2db45125484baa134b77)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@bwbarrett i checked (only) the free bsd platform.
build was successful, but the overall test failed because ```--get-stack-traces``` is a mpirun option that is valid only from ```v2.x```
could you please update your jenkins scripts accordingly ?

**Comment by bwbarrett** [comment]
yeah, there's a check in the script for version to avoid that bug; not sure what's happening.  Unfortunately, I won't be able to look at it in the next week due to meetings and vacation.

**Comment by jsquyres** [comment]
@bwbarrett Looks like the PRB failed because it's trying to use `--get-stack-traces`, but that isn't understood here on the v2.0.x branch.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by bwbarrett** [comment]
@jsquyres yeah, I got that part.  I found the bug; a bad regex for the versions that do / do not support --get-stack-traces.  We matched the 1.x series, but not the 2.0.x series properly.  Fixed now (I think), although Howard's current build is going to fail same as the first one...

**Comment by hppritcha** [comment]
are we ready to have jenkins get another go at this one?

**Comment by bwbarrett** [comment]
Yeah, I pushed what I think is the fix on Thursday.

bot:ompi:retest

**Comment by hppritcha** [comment]
hmm.. looks like we're still picking up the ```--get-stack-traces```

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
(https://github.com/open-mpi/ompi-scripts/pull/2 should have fixed the `--get-stack-traces` issue on BSD)

**Comment by jsquyres** [comment]
Try again, with https://github.com/open-mpi/ompi-scripts/pull/3...

bot:ompi:retest

**Pull request merged**
