### PR TITLE
Moving PMIx and PRRTE submodules to latest master

### PR DESCRIPTION
**Pull request by gpaulsen**
Updating PMIx and PRRTE submodule pointers.

    PMIx Changes:

     ba351884 - Fix visibility of CLI classes
     5a9a846c - Remove unnecessary parameters from MCA var registration
     196c9b5c - First pass at cleaning up MCA parameter registration
     3a6c3d8b - Remove stale "data" field from component structure
     ac6515b6 - Begin setup for transition of MCA infrastructure
     c84ccdfc - Expose the class and thread code for reuse
     fb59671e - Remove unnecessary sys/sysctl.h includes
     cc290e41 - Clean up unused return value warnings
     902e277c - pmix_iof.c: malloc buffer before memcpy().
     61165a6a - Expose PMIx utilities for reuse by PRRTE
     db4ea963 - test: Fix dereference issue in environ test
     9694f90a - Sync the library to the Standard
     eb07bc13 - Try modified Mellanox Dockerfile to get it to build
     5319cc86 - Fix typo - should be not-equal
     d8ec7ba6 - Remove block of hwloc 2.5 - 2.7
     ec0daf39 - Be defensive against string literals in env
     644d3f35 - Initialize the mutex when constructing an object
     a98fbbc8 - Remove unneeded atomics code
     0fe74524 - Begin stripping configure of unnecessary checks
     a6d66e29 - Sync NEWS with v4.1.1 release
     8b2ec7d8 - Update the hwloc version checking
     c5d7c89a - Protect against HWLOC issues
     1333b033 - Tweak the progress thread bind support
     d167a63f - Enable ability to bind PMIx progress thread
     9fd4012f - Fix the client-get function
     650d3af7 - Remove the Docker Auth GitHub Environment
     79a7280a - GitHub Action for xversion testing
     d8ef0331 - Fix race condition when processing pending get requests
     3696dce7 - Fix typo in configure script
     961ec8d6 - Fix the wrapper compiler txt file path

    PRRTE Changes:

     24eb3bfb - Fix --mca processing.
     cdfa5eb8 - Update TM configure logic to include tm library location
     8d137bad - Ensure tool procs are not counted against resource limits
     831d6115 - Tag the TM launcher as a "launcher"
     af121792 - Fix typo
     8e20022c - Fix the command line parser
     d2d38e76 - Fix the param and show-version options of prte_info
     e8243872 - Enable per-job specification of the exec agent
     373ddde9 - Use correct data source when loading info
     1d9bd24d - Address missed comments to correct a couple of options
     0c85702e - Address review comments
     11e490bb - Ensure the cmd lien parser exits when it hits the application name
     cb7b061a - Silence warning
     8f20eb4b - Silence multiple output of deprecation warnings
     accbe039 - Split out setting of default placement policies
     138abd5a - Redesign the command line system to provide isolation
     ee0fdaad - Cleanup a bit in prep for PMIx sync to v5 std
     12c62fb6 - Remove HWLOC version block
     daa6ec2f - Revert "Isolate the fault tolerance support"
     38cb89d5 - Revert "Allow multiple FT methods to be enabled"
     c9f75753 - Revert "Rename rmaps/resilient to rmaps/rcm and allow mult-enable"
     bd99a53f - Revert "Fix the race condition in normal operations"
     afed70b1 - Fix the race condition in normal operations
     c476e9e0 - Rename rmaps/resilient to rmaps/rcm and allow mult-enable
     d6761a5a - Allow multiple FT methods to be enabled
     3125d5da - Isolate the fault tolerance support
     d073028d - Add missing examples to tarball
     71895c5e - Ensure an error gets reported when rankfile fails
     ed19915e - Sync NEWS from v2.0.1 release
     1e88cd28 - Update the hwloc version checking
     165f4b01 - Protect against HWLOC issues
     2482abbd - Cleanup handling of allocated node names
     440e188d - Always build the PBS scheduler support
     0828725d - Enable binding internal PRRTE progress thread

    Signed-off-by: Geoffrey Paulsen <gpaulsen@us.ibm.com>

### CODE REVIEW

**Review by rhc54 — APPROVED** [review]
Assuming it makes it thru CI, it should be okay - I haven't tried building it with OMPI. I expect it should work.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9b70739c481adccfda3495efff78fdb0

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/09a9ed459865110279a4c0decdc14ac4

**Comment by jjhursey** [comment]
@rhc54 The CI error seems to point to a CLI parsing issue in PRRTE:
```
ssh c656f6n02 timeout --preserve-status -k 300s 300s   docker exec -i --env WORKSPACE=/workspace -u 59674:59674 -w /workspace/ompi-src/examples a9109e7fb696 'timeout --preserve-status -k 310s 310s  /workspace/exports/ompi/bin/mpirun --hostfile /workspace/hostfile.txt --map-by ppr:4:node  --mca btl_tcp_if_include eth0 --mca oob_tcp_if_include eth0 --mca pml ob1 --mca osc ^ucx --mca btl tcp,vader,self hello_c'
########################################
--------------------------------------------------------------------------
Error: an MCA parameter was listed more than once on the command line, or
multiple times in one or more files, but with conflicting values:

  Param:  btl_tcp_if_include
  Value:  ob1
  Value:  eth0

We cannot determine which value was intended, and therefore are unable to proceed.
Please correct your command line.
--------------------------------------------------------------------------
```

The command line is:
```
mpirun --hostfile /workspace/hostfile.txt --map-by ppr:4:node  --mca btl_tcp_if_include eth0 --mca oob_tcp_if_include eth0 --mca pml ob1 --mca osc ^ucx --mca btl tcp,vader,self hello_c
```
So you can see that `btl_tcp_if_include` is included only once.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/53b7eddc8e65abf731d0b35dc967e1e1

**Comment by awlauria** [comment]
I think the prrte command line doesn't like multiple mca's, even if they are different.

**Comment by rhc54** [comment]
> I think the prrte command line doesn't like multiple mca's, even if they are different.

I doubt that - what is happening is that schizo/ompi looks at the `btl_tcp_if_include` and automatically adds an `oob_tcp_if_include` since there is an implied overlap to PRRTE that people may not be aware of - and then it sees the second `oob_tcp_if_include` and errors out. If you don't want the implied overlap behavior, you should edit schizo/ompi to revise it.

Remember - schizo/ompi is now _your_ responsibility, not mine 😄

**Comment by jjhursey** [comment]
Mellanox CI hit the same issue, but with a different command line:
```
++ /__w/1/ompi/ompi_install/bin/mpirun --mca pml ucx --mca btl '^vader,tcp,openib,uct' --np 2 --mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
++ grep --count '^XXX_'
--------------------------------------------------------------------------
Error: an MCA parameter was listed more than once on the command line, or
multiple times in one or more files, but with conflicting values:

  Param:  pml
  Value:  ^vader,tcp,openib,uct
  Value:  ucx

We cannot determine which value was intended, and therefore are unable to proceed.
Please correct your command line.
--------------------------------------------------------------------------
```
So it doesn't seem to be (or at least isolated to) a `btl_tcp_if_include` vs `oob_tcp_if_include` issue.

**Comment by rhc54** [comment]
> I'll retest, but when I was trying a week or two ago something like:

Perhaps it would be better if you had reported it then? 🤷‍♂️  I can take a look a little later today.

**Comment by awlauria** [comment]
Yes I should have when I saw it. That is my fault - forgot about it until now.

**Comment by awlauria** [comment]
```
$. git diff src/mca/schizo/ompi/schizo_ompi.c
diff --git a/src/mca/schizo/ompi/schizo_ompi.c b/src/mca/schizo/ompi/schizo_ompi.c
index b9a3ff5505..335e61c00f 100644
--- a/src/mca/schizo/ompi/schizo_ompi.c
+++ b/src/mca/schizo/ompi/schizo_ompi.c
@@ -1300,7 +1300,7 @@ static int parse_env(char **srcenv, char ***dstenv,
             p3 = strchr(opt->values[i], '=');
             *p3 = '\0';
             ++p3;
-            p1 = opt->values[0];
+            p1 = opt->values[1];
             /* check if this is one of ours */
             if (check_generic(p1)) {
                 /* treat mca_base_env_list as a special case */
```
fixes it - it was passing "mca" to the cache, so it would reject the second. Looks like --omca and --gomca have the same problem in that block of code. Should they also be changed?

**Comment by rhc54** [comment]
I should think so, yes - thx!

**Comment by awlauria** [comment]
sure, will post a pr shortly.

**Comment by awlauria** [comment]
PR to prrte master posted: https://github.com/openpmix/prrte/pull/1213

**Comment by awlauria** [comment]
@gpaulsen the prrte change has been merged. can you update the pointer?

**Comment by gpaulsen** [comment]
Force pushed after updating to include https://github.com/openpmix/prrte/pull/1213

**Review by awlauria — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/af48e4eee7d284f23f3df45ea3398007

**Comment by awlauria** [comment]
Looks like a real failure, I'll look at it.

**Comment by awlauria** [comment]
Can't reproduce..trying again..

bot:ibm:gnu:retest

**Pull request merged**
