### PR TITLE
OMPI/OSC/UCX: set priority to 0. （v3.1.x)

### PR DESCRIPTION
**Pull request by xinzhao3**
cherry-picked from #5134

### CODE REVIEW

**Comment by xinzhao3** [comment]
@hjelmn @bwbarrett

**Comment by xinzhao3** [comment]
@jladd-mlnx @hjelmn looks like I am not authorized to merge. Can we merge this one?

**Comment by jsquyres** [comment]
@xinzhao3 The release managers are the only ones with merge authority on the release branches.

**Comment by xinzhao3** [comment]
@jsquyres I see. Thanks for your clarify.

**Pull request merged**
