### PR TITLE
v3.1.x: remove stale rml ofi component

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Ralph Castain <rhc@pmix.org>
(cherry picked from commit 8794077520b4b4ae86be3a09cfc1abbf7bcab8ad)

@bwbarrett This was already merged on master, v3.0.x., and v4.0.x.  Looks like we missed v3.1.x.

Did we not remove it from v3.1.x for a reason?  Backwards compatibility, maybe?  (or is there another PR for this that hasn't been merged yet, and I missed it?)

If we leave it on v3.1.x, we need to clean up some warnings that are appearing in autogen output:

```
autoreconf: running: automake --add-missing --copy --force-missing --warnings=all,no-obsolete,no-override
configure.ac:1100: warning: MCA_opal_common_ofi_CONFIG is m4_require'd but not m4_defun'd
orte/mca/rml/ofi/configure.m4:22: MCA_orte_rml_ofi_CONFIG is expanded from...
config/opal_mca.m4:577: MCA_CONFIGURE_M4_CONFIG_COMPONENT is expanded from...
config/opal_mca.m4:356: MCA_CONFIGURE_FRAMEWORK is expanded from...
config/opal_mca.m4:256: MCA_CONFIGURE_PROJECT is expanded from...
config/opal_mca.m4:39: OPAL_MCA is expanded from...
```

### CODE REVIEW

**Comment by bwbarrett** [comment]
I think this was just incompetence on my part that we missed removing in 3.1.

**Comment by bwbarrett** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
FWIW: Mellanox's CI might still be inoperable.  They were having problems with it last week, and @artpol84 told me (in person / in Chattanooga) that it might take a few days to fix it.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request merged**
