### PR TITLE
BTL 3.0

### PR DESCRIPTION
**Pull request by hjelmn**
Master pull request for updating to BTL 3.0

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres @rolfv  This is up for testing of the completed work. Once smcuda and usnic are ready I will use this pull request to bring everything into master.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/167/

**Build Log**
*last 50 lines*

 ```
[...truncated 6565 lines...]
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/vader'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/vader'
Making install in mca/btl/openib
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/openib'
  CC       btl_openib.lo
  CC       btl_openib_component.lo
  CC       btl_openib_endpoint.lo
  CC       btl_openib_frag.lo
  CC       btl_openib_proc.lo
  LEX      btl_openib_lex.c
  CC       btl_openib_mca.lo
  CC       btl_openib_ini.lo
  CC       btl_openib_async.lo
  CC       btl_openib_xrc.lo
  CC       btl_openib_fd.lo
  CC       btl_openib_ip.lo
  CC       btl_openib_put.lo
  CC       btl_openib_get.lo
  CC       btl_openib_atomic.lo
  CC       connect/btl_openib_connect_base.lo
  CC       connect/btl_openib_connect_rdmacm.lo
  CC       connect/btl_openib_connect_empty.lo
  CC       connect/btl_openib_connect_udcm.lo
  CC       connect/btl_openib_connect_sl.lo
  CC       btl_openib_lex.lo
connect/btl_openib_connect_udcm.c: In function 'udcm_endpoint_init_self_xrc':
connect/btl_openib_connect_udcm.c:524: error: too few arguments to function 'udcm_xrc_recv_qp_connect'
connect/btl_openib_connect_udcm.c:530: error: 'struct mca_btl_base_endpoint_t' has no member named 'xrc_recv_qp_num'
btl_openib_put.c: In function 'mca_btl_openib_put':
btl_openib_put.c:99: error: 'mca_btl_openib_put_frag_t' has no member named 'sr_desc'
make[2]: *** [btl_openib_put.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [connect/btl_openib_connect_udcm.lo] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/openib'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/168/

**Build Log**
*last 50 lines*

 ```
[...truncated 6561 lines...]
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/vader'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/vader'
Making install in mca/btl/openib
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/openib'
  CC       btl_openib.lo
  CC       btl_openib_component.lo
  CC       btl_openib_endpoint.lo
  CC       btl_openib_frag.lo
  CC       btl_openib_proc.lo
  LEX      btl_openib_lex.c
  CC       btl_openib_mca.lo
  CC       btl_openib_ini.lo
  CC       btl_openib_async.lo
  CC       btl_openib_xrc.lo
  CC       btl_openib_ip.lo
  CC       btl_openib_fd.lo
  CC       btl_openib_put.lo
  CC       btl_openib_get.lo
  CC       btl_openib_atomic.lo
  CC       connect/btl_openib_connect_base.lo
  CC       connect/btl_openib_connect_empty.lo
  CC       connect/btl_openib_connect_rdmacm.lo
  CC       connect/btl_openib_connect_sl.lo
  CC       connect/btl_openib_connect_udcm.lo
  CC       btl_openib_lex.lo
btl_openib_put.c: In function 'mca_btl_openib_put':
btl_openib_put.c:99: error: 'mca_btl_openib_put_frag_t' has no member named 'sr_desc'
make[2]: *** [btl_openib_put.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/openib'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/169/

**Build Log**
*last 50 lines*

 ```
[...truncated 20622 lines...]
Process 6 exiting
Process 5 gets message from 6 (8 processes in ring)
Process 5 exiting
Process 2 gets message from 3 (8 processes in ring)
Process 2 exiting
Process 0 gets message from 1 (8 processes in ring)
Process 0 exiting
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/oshmem_circular_shift
Process 5 gets message from 6 (8 processes in ring)
Process 5 exiting
Process 2 gets message from 3 (8 processes in ring)
Process 2 exiting
Process 7 gets message from 0 (8 processes in ring)
Process 7 exiting
Process 1 gets message from 2 (8 processes in ring)
Process 1 exiting
Process 4 gets message from 5 (8 processes in ring)
Process 4 exiting
Process 3 gets message from 4 (8 processes in ring)
Process 3 exiting
Process 6 gets message from 7 (8 processes in ring)
Process 6 exiting
Process 0 gets message from 1 (8 processes in ring)
Process 0 exiting
+ '[' yes == yes ']'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/oshmem_circular_shift
Process 3 gets message from 4 (8 processes in ring)
Process 3 exiting
Process 7 gets message from 0 (8 processes in ring)
Process 7 exiting
Process 5 gets message from 6 (8 processes in ring)
Process 5 exiting
Process 4 gets message from 5 (8 processes in ring)
Process 4 exiting
Process 6 gets message from 7 (8 processes in ring)
Process 6 exiting
Process 0 gets message from 1 (8 processes in ring)
Process 0 exiting
Process 2 gets message from 3 (8 processes in ring)
Process 2 exiting
Process 1 gets message from 2 (8 processes in ring)
Process 1 exiting
--------------------------------------------------------------------------
oshrun noticed that process rank 0 with PID 0 on node jenkins01 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/170/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/171/
Test PASSed.

**Comment by hjelmn** [comment]
This branch will be rebased/retested daily until it is ready to come into trunk.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/172/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/173/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/176/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/182/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/191/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/212/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/217/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/219/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/222/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/223/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/232/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/233/
Test PASSed.

**Comment by hjelmn** [comment]
Cleaned out the opal_ignore commits now that all components are updated

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/234/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/239/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/241/
Test PASSed.

**Pull request merged**
