### PR TITLE
Fix typo in MPI_Cart_shift doc

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
@blegat Thanks for finding / fixing that typo!

I hate to do this, but we require all commits to have a "Signed-off-by" attribution (per the last paragraph in https://github.com/open-mpi/ompi/wiki/Admistrative-rules#open-mpi-membership).  If you could just `git commit --amend -s` and then force-push back up to this PR, that would take care of it.

Thank you!

**Comment by blegat** [comment]
Sure ! Sorry for not checking the contribution guidelines

**Comment by jsquyres** [comment]
Heh.  This PR made me go check and I notice that we don't have the handy github contribution guidelines link thingy setup (I think we just have to put a special `.md` file somewhere...); sorry about that.  I took a to-do item to do that.

**Pull request merged**
