### PR TITLE
PSM and PSM2 MTLs to detect drivers and link

### PR DESCRIPTION
**Pull request by matcabral**
Update in PSM and PSM2 MTLs to detect entries created by drivers for
Intel TrueScale and Intel OmniPath, and detect a link in ACTIVE state.
This fix addresses the scenario reported in the below OMPI users email,
including formerly named Qlogic IB, now Intel True scale. Given the
nature of the PSM/PSM2 mtls this fix applies to OmniPath:
https://www.open-mpi.org/community/lists/users/2016/04/29018.php

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by matcabral** [comment]
Any ideas way first test is failing ?

**Comment by rhc54** [comment]
@matcabral It's an issue on the Mellanox Jenkins system due to some connection issue - I believe they have addressed it, so let's try again

bot:retest

**Comment by matcabral** [comment]
bot:retest

**Comment by rhc54** [comment]
This is a known unrelated failure - all looks good

**Pull request merged**
