### PR TITLE
btl/openib/udcm: add support for connection across subnets

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds the code necessary to support forming connections across
subnets. The primary changes are to 1) add the gid to the modex, and 2)
use the gid to create the address handle.

Signed-off-by: Nathan Hjelm hjelmn@me.com

### CODE REVIEW

**Comment by hjelmn** [comment]
@artpol84 This PR should make udcm work across a router. Once it passes the CI can you check if this actually works? I don't yet have a router to play with.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/adab39acf1e224c93d957e8cd9db442a

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/6ef767d7c35b3984594203cb5840c8f5

**Comment by artpol84** [comment]
I'll take it internally and will get back to you

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by artpol84** [comment]
Sorry for the late response regarding a router.
Unfortunately we don't have a multi-net setup now.

**Comment by jladd-mlnx** [comment]
@gvallee can ORNL test this? I believe you have a router connecting multiple subnets for CORAL testing.

**Comment by hjelmn** [comment]
bot:retest:

**Comment by bwbarrett** [comment]
@hjelmn: the travis builder is dead, so I think you'll either have to submit a new PR or (shame on us) commit without the green checkmark.  I'd just merge without the checkmark in this case...

**Pull request merged**
