### PR TITLE
Topic/get element fix

### PR DESCRIPTION
**Pull request by bosilca**
Fix the calculation of the number of elements in the datatype. As the loop variable has been set outside the internal loop, we were not correctly updating the loop stats, and we were counting more elements than actually existing in the datatype representation.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2f5b1e23de66e06b8982acd00e2c336f

**Comment by artpol84** [comment]
@jladd-mlnx @Di0gen @yosefe 
@jsquyres just pinged me about this Jenkins failure.
It looks like ompi can’t find UCX. Can someone have a look?

**Comment by jsquyres** [comment]
I pushed a missing include file fix to this PR.  If it passes CI, I'll squash it back down to George's original commit and then we can merge.

**Comment by bosilca** [comment]
I compile in debug mode, and the output was available there. I'll squash.

**Comment by jsquyres** [comment]
@bosilca Cool -- thanks!

**Comment by alinask** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
@alinask thanks!

**Comment by edgargabriel** [comment]
Are we good to merge this pr, i.e. has the squash been already done?

**Comment by jsquyres** [comment]
@edgargabriel Yes, squash has been done -- we're good to go.

**Comment by jsquyres** [comment]
@bosilca This PR changed the default value of the MCA param `opal_cuda_verbose` from 0 to -1.

Was that intended?  That doesn't seem to have anything to do with this GET_ELEMENT fix.

**Comment by jsquyres** [comment]
@bosilca Is this fix also applicable to v2.1.x?  The cherry picks did not apply anywhere close to clean for me.

**Comment by bosilca** [comment]
@jsquyres the opal_cuda_verbose was not supposed to be part of this. Fortunately, it has no impact on the code. I will change back in master, I have another cleanup pending.

The bug is present in 2.1,e and as you noticed this patch will not apply as is. One will have to search for the lines in this patch and apply them by hand. I am on not available for the next week, but I'll try to send you a quick patch to test.

**Pull request merged**
