### PR TITLE
libnbc: fix warning

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e3a950e629fa8d365784235843679729

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6b2a7c6c263579381acfc9c49bcb94fe

**Comment by rhc54** [comment]
LOL - glad it was that trivial! Thanks!

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/eb00199bd2aa291665e1636452ac6a19

**Comment by jjhursey** [comment]
bot:ibm:retest (CI script broke, should be fixed now)

**Comment by hjelmn** [comment]
bot:ibm:retest

**Comment by hjelmn** [comment]
bot:ibm:retest

**Comment by bosilca** [comment]
This looks like a subset of #5943.

**Comment by hjelmn** [comment]
@bosilca Didn't see that one. Lets go with #5943.

**Pull request closed without merging**
