### PR TITLE
pmix/ext3x: bring external component up-to-date with the embedded pmix3x

### PR DESCRIPTION
**Pull request by ggouaillardet**
add the callback prototype for the upcoming PMIx_IOF_push() API

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 the `pmix/ext3x` will only build if the external component includes the upcoming IOF RFC pmix/pmix#612
I let you decide if you want to merge this PR or improve it (e.g. autodetect the IOF RFC and acts accordingly).

**Comment by rhc54** [comment]
This is fine - the IOF code is officially coming soon anyway. As I stated on other PR, I thought that ext3x.h was generated from pmix3x, but I guess not?

**Comment by rhc54** [comment]
Just checked - nope, it is committed. My bad. Thanks for fixing things!

**Comment by ggouaillardet** [comment]
i do not remember `ext3x.h` was automatically generated from `pmix3x`.

the snippet above is only part of `ext3x.h` and would not be here if it was automatically generated.
but maybe we should protect that with a macro and automatically generate this file in order to ease maintenance.

```c
#ifdef OPAL_C_HAVE_VISIBILITY
#define PMIX_HAVE_VISIBILITY 1
#else
#undef PMIX_HAVE_VISIBILITY
#endif
```

**Comment by rhc54** [comment]
if it is easily done, then it would make sense - i'm not sure why that visibility definition would be in ext3x.h. It cannot possibly influence the external pmix build.

**Comment by ggouaillardet** [comment]
on second though, `ext3x/Makefile.am` contains
```
nodist_headers = \
        ext3x.h
```

plus other things that make me think we forgot to `git rm opal/mca/pmix/ext3x/ext3x.h`

and fwiw, `opal/mca/pmix/ext3x/ext3x.h` is not part of the tarballs.

let me know if I should simply remove this file from the repository (and add the automatically generated files to `.gitignore` too)

for the record, here is a patch that would have the visibility thing only for the ext3x component.

```patch
diff --git a/opal/mca/pmix/ext3x/Makefile.am b/opal/mca/pmix/ext3x/Makefile.am
index 61da6be063..ad4defd037 100644
--- a/opal/mca/pmix/ext3x/Makefile.am
+++ b/opal/mca/pmix/ext3x/Makefile.am
@@ -56,7 +56,7 @@ mcacomponent_LTLIBRARIES = $(component_install)
 mca_pmix_ext3x_la_SOURCES = $(sources)
 nodist_mca_pmix_ext3x_la_SOURCES = $(nodist_sources)
 mca_pmix_ext3x_la_CFLAGS = $(opal_pmix_ext3x_CFLAGS)
-mca_pmix_ext3x_la_CPPFLAGS =$(opal_pmix_ext3x_CPPFLAGS)
+mca_pmix_ext3x_la_CPPFLAGS =$(opal_pmix_ext3x_CPPFLAGS) -DOPAL_EXTERNAL_PMIX=1
 mca_pmix_ext3x_la_LDFLAGS = -module -avoid-version $(opal_pmix_ext3x_LDFLAGS)
 mca_pmix_ext3x_la_LIBADD = $(top_builddir)/opal/lib@OPAL_LIB_PREFIX@open-pal.la \
        $(opal_pmix_ext3x_LIBS)
@@ -65,7 +65,7 @@ noinst_LTLIBRARIES = $(component_noinst)
 libmca_pmix_ext3x_la_SOURCES =$(sources)
 nodist_libmca_pmix_ext3x_la_SOURCES = $(nodist_sources)
 libmca_pmix_ext3x_la_CFLAGS = $(opal_pmix_ext3x_CFLAGS)
-libmca_pmix_ext3x_la_CPPFLAGS = $(opal_pmix_ext3x_CPPFLAGS)
+libmca_pmix_ext3x_la_CPPFLAGS = $(opal_pmix_ext3x_CPPFLAGS) -DOPAL_EXTERNAL_PMIX=1
 libmca_pmix_ext3x_la_LDFLAGS = -module -avoid-version $(opal_pmix_ext3x_LDFLAGS)
 libmca_pmix_ext3x_la_LIBADD = $(opal_pmix_ext3x_LIBS)
 
diff --git a/opal/mca/pmix/pmix3x/Makefile.am b/opal/mca/pmix/pmix3x/Makefile.am
index f95fcb5729..a6bc26f960 100644
--- a/opal/mca/pmix/pmix3x/Makefile.am
+++ b/opal/mca/pmix/pmix3x/Makefile.am
@@ -1,7 +1,7 @@
 #
 # Copyright (c) 2014-2017 Intel, Inc. All rights reserved.
 # Copyright (c) 2015      Cisco Systems, Inc.  All rights reserved.
-# Copyright (c) 2015      Research Organization for Information Science
+# Copyright (c) 2015-2018 Research Organization for Information Science
 #                         and Technology (RIST). All rights reserved.
 # Copyright (c) 2017      IBM Corporation.  All rights reserved.
 # $COPYRIGHT$
@@ -43,7 +43,7 @@ mcacomponent_LTLIBRARIES = $(component_install)
 mca_pmix_pmix3x_la_SOURCES = $(sources)
 mca_pmix_pmix3x_la_CFLAGS = $(opal_pmix_pmix3x_CFLAGS)
 mca_pmix_pmix3x_la_CPPFLAGS = \
-        -I$(srcdir)/pmix/include $(opal_pmix_pmix3x_CPPFLAGS)
+        -I$(srcdir)/pmix/include $(opal_pmix_pmix3x_CPPFLAGS) -DOPAL_EXTERNAL_PMIX=0
 mca_pmix_pmix3x_la_LDFLAGS = -module -avoid-version $(opal_pmix_pmix3x_LDFLAGS)
 mca_pmix_pmix3x_la_LIBADD = $(top_builddir)/opal/lib@OPAL_LIB_PREFIX@open-pal.la \
        $(opal_pmix_pmix3x_LIBS)
@@ -52,7 +52,7 @@ mca_pmix_pmix3x_la_DEPENDENCIES = $(opal_pmix_pmix3x_DEPENDENCIES)
 noinst_LTLIBRARIES = $(component_noinst)
 libmca_pmix_pmix3x_la_SOURCES =$(sources)
 libmca_pmix_pmix3x_la_CFLAGS = $(opal_pmix_pmix3x_CFLAGS)
-libmca_pmix_pmix3x_la_CPPFLAGS = $(opal_pmix_pmix3x_CPPFLAGS)
+libmca_pmix_pmix3x_la_CPPFLAGS = $(opal_pmix_pmix3x_CPPFLAGS) -DOPAL_EXTERNAL_PMIX=0
 libmca_pmix_pmix3x_la_LDFLAGS = -module -avoid-version $(opal_pmix_pmix3x_LDFLAGS)
 libmca_pmix_pmix3x_la_LIBADD = $(opal_pmix_pmix3x_LIBS)
 libmca_pmix_pmix3x_la_DEPENDENCIES = $(opal_pmix_pmix3x_DEPENDENCIES)
diff --git a/opal/mca/pmix/pmix3x/pmix3x.h b/opal/mca/pmix/pmix3x/pmix3x.h
index cbf73f644f..d92ec8dd9b 100644
--- a/opal/mca/pmix/pmix3x/pmix3x.h
+++ b/opal/mca/pmix/pmix3x/pmix3x.h
@@ -37,6 +37,14 @@
 
 BEGIN_C_DECLS
 
+#if OPAL_EXTERNAL_PMIX
+#ifdef OPAL_C_HAVE_VISIBILITY
+#define PMIX_HAVE_VISIBILITY 1
+#else
+#undef PMIX_HAVE_VISIBILITY
+#endif
+#endif
+
 typedef struct {
     opal_pmix_base_component_t super;
     pmix_proc_t myproc;
```

**Comment by rhc54** [comment]
I agree - I saw the Makefile.am entry, and that's why I thought it was being generated. I previously updated the rest of the ignore files - I'll take care of this one too.

**Pull request merged**
