### PR TITLE
HCOLL: fix hang in hcoll barrier called from finalize for MXM/yalla

### PR DESCRIPTION
**Pull request by jladd-mlnx**
tear down

HCOLL barrier may not complete if HCOLL progress is not called periodically.
which is the case in HCOLL teardown progress in the finalize.
(cherry picked from commit 793244d75dd94d1d5e0243bcccf6d04318750f3f)

This is in 1.10.x but needs to be in master and 2.x.

### CODE REVIEW

**Comment by jsquyres** [comment]
@jladd-mlnx Needed for v2.0.0?  Or can it defer to v2.0.1?

**Comment by jladd-mlnx** [comment]
@jsquyres Can defer to 2.0. Looks like someone busted our mindist mapper...

**Comment by jsquyres** [comment]
Per discussion on 2016-05-03, putting this on the v2.0.0.

**Comment by jladd-mlnx** [comment]
bot:retest

**Pull request merged**
