### PR TITLE
Add OPAL_ASSERT() macro to wrap assert().

### PR DESCRIPTION
**Pull request by awlauria**
This will prevent the generation of core files on assert() unless run
with '--mca opal_enable_assert_core 1'

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by awlauria** [comment]
Here's what the error looks like:

```
ERROR: ompi_foo.c:42: ompi_osc_rdma_component_register: Assertion  '0' failed.
WARNING: No core file will be generated.
If you would like to generate a core file, please rerun with: '--mca opal_enable_assert_core 1'
Exiting.
```

**Comment by rhc54** [comment]
Errr...you mistakenly pushed this PR branch onto the main OMPI repo 😄

**Comment by awlauria** [comment]
Gah, rats..will fix.

**Comment by awlauria** [comment]
Done, thanks @rhc54 for pointing that out.

**Comment by rhc54** [comment]
Only one suggestion: you need to change the default around. @jsquyres is the only one with this problem - he should set the param to _prevent_ generation of core files. Others will be annoyed if they are trying to debug something that takes hours to replicate, only to be told they have to run it again to get the core file.

**Comment by jsquyres** [comment]
Agreed!

**Comment by bosilca** [comment]
Anyone can control the generation of core files with ulimit. This is just another level of potential mishaps, where users will wonder why there are no core files on legitimate cases. 👎

**Pull request closed without merging**
