### PR TITLE
coll/hcoll mpi datatypes support

### PR DESCRIPTION
**Pull request by vspetrov**
Adds support for MPI Derived types with libhcoll v >=3.6.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/2fd152a589a32e8faafb3f2a3e0d4726

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/bfc0d575d57dd6210e0a39aaa91506bd

**Comment by jjhursey** [comment]
The IBM CI test failure is due to a local cluster issue. I'm working on resolving it.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jladd-mlnx** [comment]
PMIx error due to hostname length. This code has passed extensive internal testing and code review. 
:+1:

**Comment by jsquyres** [comment]
Shouldn't PMIx be able to handle hostnames up to length `MAXHOSTNAMLEN`?

**Comment by rhc54** [comment]
it did, last i looked - is there a specific place where it failed?

**Pull request merged**
