### PR TITLE
Conditionally destroy job session directory.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**
Only destroy the contents rooted at opal_process_info.job_session_dir if we setup the root path. We now keep track of this information because we may be using run-time infrastructure that manages the job's session directory for us (e.g., OpenPMIx). If we setup this session directory structure, then we shall cleanup after ourselves. Otherwise, let infrastructure like OpenPMIx manage it for us.

This fixes a crash in the sessions_init_twice test where shared-memory information managed by OpenPMIx was deleted prematurely.

Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>
(cherry picked from commit ffa52edbfd634c274baf88daaafa832469b888fc)

### CODE REVIEW

**Comment by hppritcha** [comment]
somethings messed up with the sphinx being used for read the docs:
```
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

```

**Comment by jsquyres** [comment]
I have filed a trouble ticket with RTD to see if the problem is a transient infra issue on their end, or if something is wonky in our build process.

**Comment by jsquyres** [comment]
Looks like it was a transient RTD failure.  I re-triggered the RTD CI test and now it has passed.

**Comment by samuelkgutierrez** [comment]
@hppritcha can you review this for me please?

**Review by hppritcha — APPROVED** [review]

**Pull request merged**
