### PR TITLE
v4.0.x: Update Internal PMIx to OpenPMIx v3.2.1rc1

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Review by gpaulsen — APPROVED** [review]

**Review by hppritcha — APPROVED** [review]

**Comment by hppritcha** [comment]
I'd like to check this PR at NERSC before we merge.  
@rhc54 please take a look when you have a chance

**Review by rhc54 — APPROVED** [review]
Most of this falls into a few areas:

* cleanup of iquotes versus std location brackets on includes
* removal of stale assembly code (ported from OMPI)
* meaningless copyright changes due to commit of update from a different developer
* actual bug fixes (the smallest area of change)

Note that there is still some "leakage" of PMIx v4 definitions (e.g., the PMIX_GROUP_xxx_CMD constants). However, these are all harmless as nothing uses them in this version of PMIx and OMPI.

**Comment by hppritcha** [comment]
I tested at NERSC but single and multi-node spawn and the test passes.

**Comment by hppritcha** [comment]
@gpaulsen i'm good with merging this.

**Pull request merged**
