### PR TITLE
Update to hwloc v1.11.7

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9f8f872fcd17e41ad236d66fe17bcd8f

**Comment by rhc54** [comment]
Fixes #3992

**Comment by PHHargrove** [comment]
I have tried again on FreeBSD-11.1/amd64 with this PR branch and unfortunately fine #3992 *still* occurs.

**Comment by rhc54** [comment]
That's odd - I simply used the v1.11.7 tarball from the hwloc web site. You sure they didn't do some patch they failed to upstream?

**Comment by PHHargrove** [comment]
@rhc54 
There are no patches in their build tree: /usr/ports/devel/hwloc  
They configure with `--enable-static --disable-opencl --disable-cuda --disable-nvml --disable-gl` and have a build dependency on libpciaccess.

I was expecting this PR to fix my observed problems, and am as confused as you are.

**Comment by bwbarrett** [comment]
This doesn't fix the FreeBSD issue, but it looks like a good thing to bring in, so we decided on the dev call to pull this into 3.0.0 anyway.

**Pull request merged**
