### PR TITLE
Ensure we don't send a kill signal to pid=0 as that hits ourselves and initiates an infinite loop.

### LINKED ISSUE #4577: orted forwards SIGCONT to itself in HNP mode
When orted is launched in HNP mode under Slurm 15.08 (perhaps others), it propagates SIGCONT to itself in an infinite loop.  This issue occurs in at least OpenMPI 2.0.2, 2.0.3, and 3.0.0.

The orted process looks like this:

```
fennm    11160  1.1  0.0 323332  6768 ?        SNsl 20:56   0:00 orted --hnp --set-sid --report-uri 8 --singleton-died-pipe 9 -mca state_novm_select 1
```

Upon sending a SIGCONT to it, it goes to 100% CPU:

```
# kill -CONT 11160
```

Top output
```
top - 20:57:03 up 13 days,  3:40,  3 users,  load average: 0.50, 0.87, 0.85
Tasks: 318 total,   4 running, 312 sleeping,   0 stopped,   2 zombie
%Cpu(s):  0.1 us,  7.4 sy,  7.1 ni, 85.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65684672 total, 61694952 free,  1534848 used,  2454872 buff/cache
KiB Swap: 67960832 total, 67960832 free,        0 used. 63154472 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11159 fennm     21   1 13.898g 661728 216424 R 100.0  1.0   0:16.36 gdesmond-a+
11160 fennm     21   1  323332   6880   2588 R  99.7  0.0   0:04.23 orted
11193 root      20   0 68.363g  87328  67532 R  63.5  0.1   0:01.91 gpu-health
```

And does not respond to any signals other than SIGKILL:

```# kill -TERM 11160
# ps aux | grep orted
fennm    11160 70.3  0.0 323332  6880 ?        RNsl 20:56   0:29 orted --hnp --set-sid --report-uri 8 --singleton-died-pipe 9 -mca state_novm_select 1
root     11224  0.0  0.0 112648   960 pts/1    S+   20:57   0:00 grep --color=auto orted
```

While I can reproduce this by sending signals on the command line, where it really bites us is that slurmstepd always sends a SIGCONT before a SIGTERM when a job is canceled.  Here is an example of strace output in this case.  You can see that orted (PID 12557) gets an initial signal from PID 12389, which is slurmstepd, and then loops sending SIGCONT to 0, which means everything in orted's process group.  In this case, orted is the only thing in the process group because it gets started with `--set-sid`.

```
# strace -f -esignal -p 12557 2>&1 | head -20
Process 12557 attached with 5 threads
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12389, si_uid=0} ---
[pid 12561] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid 12557] kill(0, SIGCONT)            = 0
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12557, si_uid=13052} ---
[pid 12561] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid 12557] kill(0, SIGCONT)            = 0
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12557, si_uid=13052} ---
[pid 12561] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid 12557] kill(0, SIGCONT)            = 0
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12557, si_uid=13052} ---
[pid 12561] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid 12557] kill(0, SIGCONT)            = 0
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12557, si_uid=13052} ---
[pid 12561] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid 12557] kill(0, SIGCONT)            = 0
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12557, si_uid=13052} ---
[pid 12561] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid 12557] kill(0, SIGCONT)            = 0
[pid 12561] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=12557, si_uid=13052} ---
```

In the job output, I see plenty of:

```
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
(null): Forwarding signal 18 to job
```

I think that orted needs to take care avoid send non-fatal signals such as SIGCONT to the whole process group via kill(0,...), otherwise you get into this infinite loop.

### PR DESCRIPTION
**Pull request by rhc54**
Thanks to Michael Fenn for the report.

Fixes #4577 

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@fennm would you mind giving this a try and see if it fixes the problem?

**Comment by fennm** [comment]
I applied the patch to 2.0.3 and it worked great!  Sending a SIGCONT to orted works like expected with the patch:

```[fennm@swdev0008 ~]$ strace -esignal -f -p 7467
Process 7467 attached with 5 threads
[pid  7469] --- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=7584, si_uid=13052} ---
[pid  7469] rt_sigreturn()              = -1 EINTR (Interrupted system call)```

**Comment by rhc54** [comment]
very good - many thanks! I will commit and file the appropriate pull requests

**Comment by fennm** [comment]
Thanks for fixing it so quickly! 👍

**Pull request merged**
