### PR TITLE
test xcode8

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by hjelmn** [comment]
@ggouaillardet You can test multiple xcode versions using the matrix support.

**Comment by jsquyres** [comment]
@ggouaillardet Is this PR now moot?

**Comment by ggouaillardet** [comment]
We do not use travis anymore, so let's close this PR

**Pull request closed without merging**
