### PR TITLE
yoda: avoid useless memcpy in mca_spml_yoda_get when the btl is get capa...

### PR DESCRIPTION
**Pull request by ggouaillardet**
...ble

### CODE REVIEW

**Comment by jsquyres** [comment]
@alex-mikheev @ggouaillardet @miked-mellanox Is this PR still relevant?  If so, is it ready to go?

**Comment by hppritcha** [comment]
Can one of the admins verify this patch?

**Comment by hppritcha** [comment]
Where are we with this PR now?  Given this is more than 6 months old seems to be time to decide whether to close or merge.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/8/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/97/
Test PASSed.

**Comment by jsquyres** [comment]
Last activity on this PR was in 2014.  I'm guessing it isn't relevant any more.

Feel free to re-open if that's and incorrect assumption.

**Pull request closed without merging**
