### PR TITLE
Fix segfault in TCP/BTL

### PR DESCRIPTION
**Pull request by rhc54**
Correctly check the sa_family and cast the data correctly before passing it to inet_nop, and don't be quite as fancy with the pointer arithmetic as the combination was causing us to segfault every time this debug message was called.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit 470452cba03b7b5c684d9d99acc0a73c6c47746a)

### CODE REVIEW

**Comment by bosilca** [comment]
We have special functions for checking the family. I had a patch but I can't find it right now, give me a moment to redo it.

**Comment by bwbarrett** [comment]
@bosilca any luck with your patch?  (4 days == 1 moment ;) )

**Comment by hppritcha** [comment]
@bosilca any luck finding the patch?

**Comment by jsquyres** [comment]
@bosilca Ping!

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest

**Comment by hppritcha** [comment]
I vote for merging this as is.

**Comment by hppritcha** [comment]
@jsquyres go ahead and review and we'll merge if its okay with you.

**Pull request merged**
