### PR TITLE
fix build error if greq extensions not available

### LINKED ISSUE #426: compiling ROMIO with PVFS2 support
compiling the ompi master and enabling PVFS2 support in ROMIO will lead to an error at compile time

adio/ad_pvfs2/ad_pvfs2_aio.c: In function 'ADIOI_PVFS2_AIO_contig':

adio/ad_pvfs2/ad_pvfs2_aio.c:126:6: error: implicit declaration of function 'PMPIX_Grequest_class_create' [-Werror=implicit-function-declaration]
      MPIX_Grequest_class_create(ADIOI_GEN_aio_query_fn,
      ^

adio/ad_pvfs2/ad_pvfs2_aio.c:131:2: error: implicit declaration of function 'PMPIX_Grequest_class_allocate' [-Werror=implicit-function-declaration]
  MPIX_Grequest_class_allocate(ADIOI_PVFS2_greq_class, aio_req, request);
  ^

Note, that Open MPI sets the --disable-aio flag when configuring ROMIO. My suspicion is that there is 
some protection through macros (HAVE_MPI_GREQUEST_EXTENSIONS or one of the AIO macros) is missing from this file, but not entirely sure.

@roblatham00 Any ideas/suggestions how to resolve that?

### PR DESCRIPTION
**Pull request by roblatham00**
Fall back to immediately completing the non-blocking request if we are
unable to use the extended generalized request routines.

Closes #426

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found  errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_291/

* Coverity found  errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_291/

* Coverity found  errors for yalla: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/yalla_291/

* Coverity found  errors for mxm: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/mxm_291/

* Coverity found  errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_291/

* Coverity found  errors for hcoll: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/hcoll_291/ <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/291/
Test PASSed.

**Comment by jsquyres** [comment]
@hppritcha Can you have a look?

**Comment by hppritcha** [comment]
yes

**Pull request merged**
