### PR TITLE
Add a common/libfabric component

### PR DESCRIPTION
**Pull request by rhc54**
@jsquyres @jithinjosepkl @yburette See what you think. I created the skeleton and linked it in to the MTL/OFI component as an example.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@rhc54 Looks like "make distcheck" failed (see http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/81/console).  Perhaps `help-mpi-common-libfabric.txt` isn't in EXTRA_DIST...?

**Comment by rhc54** [comment]
@jsquyres <lol> yeah, forgot to git add the file. coming in a minute

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/659/


**Build Log**
*last 50 lines*

 ```
[...truncated 36851 lines...]
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/shmem'
 (cd mca/timer && make -j32 top_distdir=../../../openmpi-2.0.0a1 distdir=../../../openmpi-2.0.0a1/opal/mca/timer \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/timer'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/timer'
 (cd mca/common/cuda && make -j32 top_distdir=../../../../openmpi-2.0.0a1 distdir=../../../../openmpi-2.0.0a1/opal/mca/common/cuda \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/cuda'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/cuda'
 (cd mca/common/ugni && make -j32 top_distdir=../../../../openmpi-2.0.0a1 distdir=../../../../openmpi-2.0.0a1/opal/mca/common/ugni \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/ugni'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/ugni'
 (cd mca/common/sm && make -j32 top_distdir=../../../../openmpi-2.0.0a1 distdir=../../../../openmpi-2.0.0a1/opal/mca/common/sm \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/sm'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/sm'
 (cd mca/common/verbs && make -j32 top_distdir=../../../../openmpi-2.0.0a1 distdir=../../../../openmpi-2.0.0a1/opal/mca/common/verbs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/verbs'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/verbs'
 (cd mca/common/libfabric && make -j32 top_distdir=../../../../openmpi-2.0.0a1 distdir=../../../../openmpi-2.0.0a1/opal/mca/common/libfabric \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/libfabric'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: *** No rule to make target `help-mpi-common-libfabric.txt', needed by `distdir'.  Stop.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/common/libfabric'
make[2]: *** [distdir] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace'
make: *** [dist] Error 2
Make dist failed.  Aborting
+ exit 11
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/659/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/6a1eda61e376d1cc214d0488eb0cde778d8d587a
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of a822a088ed5b44d1c7993d2003edaa2df48c7960 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/659/ and message: 'Build finished.'
Using conext: Mellanox
```

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/660/

**Comment by jithinjosepkl** [comment]
Looks good to me :+1:

**Comment by jsquyres** [comment]
:+1:

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/666/

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/668/

**Comment by yburette** [comment]
I tested it with OFI MTL over PSM. Looks good to me now.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/669/

**Pull request merged**
