### PR TITLE
Revert "add libopen-orted-mpir when statically linking"

### PR DESCRIPTION
**Pull request by jsquyres**
Reverts open-mpi/ompi#9609

bot:notacherrypick

### CODE REVIEW

**Comment by gpaulsen** [comment]
@jsquyres Can you please add some rational for reverting #9609?  I'm not familiar with the issue, and it'd be good to document here.

**Comment by gpaulsen** [comment]
Ah, rational on https://github.com/open-mpi/ompi/pull/9609

**Review by ggouaillardet — APPROVED** [review]

**Comment by ggouaillardet** [comment]
@gpaulsen the issue on the latest official releases were already and correctly fixed (see https://github.com/open-mpi/ompi/commit/952328c3827). moreover, this PR on top of the right fix breaks the wrappers(!)

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
Looks like this is missing the sign-off.

**Comment by jsquyres** [comment]
It's a revert, and the git commit cherry picker ignores reverts in terms of needing a signoff.

It failed the git commit cherry picker because I neglected to include `bot:notacherrypick` in the PR description.  Fixed.

**Review by bwbarrett — APPROVED** [review]

**Pull request merged**
