### PR TITLE
Javadoc warnings fix

### PR DESCRIPTION
**Pull request by nrgraham23**
Added missings @params and @throws as well as adding definitions for the @throws tags.

There are a few places where adding the @param for the variable
javadoc wants does not make sense, so I added suppression statements
in those areas.

Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>

@jsquyres  @hppritcha

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by nrgraham23** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
the hopper node seems to be having github connectivity issues right now.
bot:retest

**Comment by hppritcha** [comment]
looks good merging.

**Pull request merged**
