### PR TITLE
OMPI/OSC/UCX: adding atomic lock for fetch_and_op and compare_and_swap

### PR DESCRIPTION
**Pull request by xinzhao3**
Signed-off-by: Xin Zhao <xinz@mellanox.com>

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
Fixes #4688

**Comment by artpol84** [comment]
@jladd-mlnx @xinzhao3 Was this closed intentionally?

**Comment by artpol84** [comment]
@hjelmn thanks!

**Comment by artpol84** [comment]
@bwbarrett this is good to go.

**Pull request merged**
