### PR TITLE
Purge whitespace from the repo

### PR DESCRIPTION
**Pull request by rhc54**
@jsquyres @hjelmn see what you think

### CODE REVIEW

**Comment by hppritcha** [comment]
This is all fine, but unless we have a recommended pre-commit hook that all developers use before committing, we'll just have to do this over and over.

At a minimum I'd recommend using the ```exec git diff-index --check --cached $against --``` in the pre-commit.sample that comes with git by default.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/646/


**Build Log**
*last 50 lines*

 ```
[...truncated 48823 lines...]
++ wc -l
+ val=10
+ '[' 10 -ne 10 ']'
+ echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
++ grep '^XXX_'
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
++ wc -l
+ val=10
+ '[' 10 -ne 10 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
++ grep mca_base_envar_file_prefix
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ wc -l
+ val=1
+ '[' 1 -gt 0 ']'
+ echo 'test -tune option in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
test -tune option in /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ echo '-x XXX_A=1   --x   XXX_B = 2 -x XXX_C -x XXX_D --x XXX_E'
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -tune /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_tune.conf -x XXX_A=6 /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
++ sed -n -e 's/^XXX_.*=//p'
++ sed -e ':a;N;$!ba;s/\n/+/g'
++ bc
+ val=40
+ '[' 40 -ne 40 ']'
+ echo '-mca mca_base_env_list "XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E"'
++ sed -n -e 's/^XXX_.*=//p'
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -tune /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_tune.conf /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
++ sed -e ':a;N;$!ba;s/\n/+/g'
++ bc
+ val=30
+ '[' 30 -ne 30 ']'
+ echo '-mca mca_base_env_list "XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E"'
++ sed -n -e 's/^XXX_.*=//p'
++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -tune /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_tune.conf -mca mca_base_env_list 'XXX_A=7;XXX_B=8' /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
++ sed -e ':a;N;$!ba;s/\n/+/g'
++ bc
+ val=57
+ '[' 57 -ne 54 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/646/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/4f9254c2f206197837f29c80a6dff285d0df2caa
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 869041f770d6b52896f28fdd3e1f1a7c34219397 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/646/ and message: 'Build finished.'
Using conext: Mellanox
```

**Comment by rhc54** [comment]
@hppritcha I agree, but I also committed the script so we can run this purge periodically. Once we get the script correct, it should be relatively painless to clean up every so often, given that nobody can completely control the accidental insertion of whitespace.

**Comment by rhc54** [comment]
@miked-mellanox Any idea why this was marked as failed? The details button reports "no identified problem". Sadly, the link to the Jenkins results yields a "not found" error for me - don't know if that's a permissions issue or not.

**Comment by miked-mellanox** [comment]
@rhc54 - checking

**Comment by miked-mellanox** [comment]
-tune option got broken, @elenash - could you please provide more details?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/648/

**Pull request merged**
