### PR TITLE
Fcoll dynamic gen2

### PR DESCRIPTION
**Pull request by edgargabriel**
will not merge it yet, but want to see the reporst from jenkins

### CODE REVIEW

**Comment by hppritcha** [comment]
@edgargabriel can you point me to a test to run on lustre that will show the problems you were getting on Cray at HLRS?

**Comment by edgargabriel** [comment]
@hppritcha I have an update: this last commit made the hang being exposed again on the cray, this time even with debug built. Digging into that I do *not* see something wrong in the component, but it looks to me like a progression problem. 

I can now even reproduce the hang *without* the new component on my regular cluster as long as I use multiple nodes. It seems that processes are hanging in the poll function of the progress engine in an allreduce operation. I will continue looking into that, but I am 99% sure that the problem is not from my component.

**Comment by hppritcha** [comment]
@edgargabriel on your cluster, which BTL/MTL is being used for inter-node messaging?

**Comment by edgargabriel** [comment]
openib. Everything is also running very slow, but I did not have time to check  what's the reason for that.

**Comment by edgargabriel** [comment]
to refine my previous: I obviously don't know whether the hang on the Cray and on my InfiniBand cluster are related or not. The 'old' components work well on Cray, I see a hang only with the new component. On my IB cluster, we seem to be hanging even with the previous code that used to work without any issues. The two things might not be related.

**Comment by edgargabriel** [comment]
A small update on this item. I have identified the problem with the IB stuff on my network. I (used to) have a flag set for openib in my configuration file, namely 

btl_openib_flags = 305

It looks like removing the flag makes things work fast again. Otherwise, the performance of the openib device drops to ~20MB/s (instead of 2000MB/s). I will check whether this resolves the hangs on my cluster. I also double checked, that the flag does not leave to this performance degradation with the 1.8 series, so its 'new' on master.

**Comment by edgargabriel** [comment]
After resolving the InfiniBand and configure issues on my cluster, I was able to test the module, and everything looks. Tests up to 512 processors finished without any deadlocks etc. Our own as well as the HDF5 testsuite pass all tests for this new module. I will therefore merge the component into trunk.

**Pull request merged**
