### PR TITLE
Update PMIx and PRRTe minimum versions

### PR DESCRIPTION
**Pull request by awlauria**
Update PRRTe and PMIx to latest releases.

### CODE REVIEW

**Review by janjust — APPROVED** [review]

**Review by bwbarrett — CHANGES_REQUESTED** [review]
Can you add a justification?  What thing that was only added in these versions causes us to need to bump the minimum supported version?  It's pretty lame to push customers to update here, particularly when we want a world where these are being provided by the OS distro.

**Comment by awlauria** [comment]
That is a good point. These branches (v2.0 pre and v4.1 pmix) are no longer supported, but we can work on a more detailed justification.

**Comment by bwbarrett** [comment]
No longer supported by Ralph doesn't mean not shipped somewhere.  Again, I'm pushing because we need to build the right muscles here for the long term.

**Comment by rhc54** [comment]
Yeah, I wouldn't justify this based on "support" as that is always going to be a problem.

PRRTE v2.0 doesn't support your `mpirun` options, so that's kind of a non-starter. One could argue that v3.0.0 has a number of bugs that have been fixed, and that you made a number of changes to the ompi schizo component since then. Guess the bottom line being that anything less than what you ship in OMPI v5 is going to either have known bugs or different cmd line behavior.

You currently will not compile with anything less than PMIx v4.2.x (I think x=2 is the min, but you could check that), though you probably could go back and add protections to work around that limitation. We have steadily worked thru some issues you and others have uncovered to get v4.2.4 in good shape, but you could drop the limit down to whatever minimally compiles and then just tell people to update when they hit problems.

Something else to consider: you've been testing solely against PRRTE, which provides a lot of information the Standard "requires". Not everyone will provide all of that, including those RMs that wrote their PMIx support before some of that data was added to the Standard. One solution is to try and "recv" a piece of info, and if not found, then "put" the info so it can be circulated during the modex and retrieve it afterwards.

Example: suppose the RM doesn't provide local rank for each proc. When that is detected, each proc could determine the local rank and "put" it for itself, and then retrieve the local rank for its peers after the modex completes. Not as efficient, but would avoid not being able to operate in that environment

**Pull request closed without merging**
