### PR TITLE
Topic/v4.0.x/fix pmix detection

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Review by rhc54 — APPROVED** [review]
Just struck me that all the pmix component priorities will be the same. I don't think that will really matter for OMPI, but I'm also not sure which of these components is going to wind up being used. @jsquyres Any idea or is it non-deterministic?

**Comment by bwbarrett** [comment]
Theoretically, if all the priorities are the same, it will be the first to be selected, which is the first in readdir() output, which is basically random.

**Review by hppritcha — APPROVED** [review]

**Comment by hppritcha** [comment]
@artpol84 could you ping nvidia/mellanox ci person?  mellanox ci seems to be hosed up.

**Comment by artpol84** [comment]
@hppritcha will do

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artemry-nv** [comment]
> @artpol84 could you ping nvidia/mellanox ci person? mellanox ci seems to be hosed up.

There's a DHCP issue in our lab - working on this.

**Comment by artemry-nv** [comment]
> > @artpol84 could you ping nvidia/mellanox ci person? mellanox ci seems to be hosed up.
> 
> There's a DHCP issue in our lab - working on this.

Fixed.

**Pull request merged**
