### PR TITLE
Treematch cleanups

### PR DESCRIPTION
**Pull request by bwbarrett**
Fix a couple issues with treematch's configure, ability to build in `--enable-shared --enable-static` cases, and remove the ability to build against the (no longer available) external library.

### CODE REVIEW

**Review by bosilca — COMMENTED** [review]
How do we check if the external treematch is compatible with what we need ? Before there was a check using OPAL_CHECK_PACKAGE, but I don't see anything related to package validation in the new code.

**Comment by bwbarrett** [comment]
I think you missed the "remove the ability to build against the (no longer available) external library" part of the commit message?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ec3ab83303258575fbc40d986ef25aee

**Comment by bwbarrett** [comment]
The topomatch library is called libtopomatch, not libtreematch, so wouldn't have worked against the external code anyway.  I'm happy if we want to support libtopomatch, but are you agreed we can drop support for external treematch libraries?

**Review by bosilca — APPROVED** [review]

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest

**Pull request merged**
