### PR TITLE
topo/base: Fix module reference in collective call

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jsquyres** [comment]
@jjhursey I assume you will PR this to v2.0.x and v2.x, right?

**Comment by jjhursey** [comment]
Yeah. Just waiting for CI - although I don't expect any problems.

**Comment by jjhursey** [comment]
Travis is stuck. I'm going to go ahead an merge.

**Comment by jjhursey** [comment]
@jsquyres  Three PRs for three release branches: #2412 #2413 #2414

**Pull request merged**
