### PR TITLE
v5.0.x: Add Part Comm component

### PR DESCRIPTION
**Pull request by tkordenbrock**
Closes https://github.com/open-mpi/ompi/issues/9554

FYI @open-mpi/ompi-gatekeeper-5-0-x

### CODE REVIEW

**Comment by jsquyres** [comment]
Why was this merged?  Per the discussion above, it looks like @mdosanjh was still going to do something additional...?

**Comment by awlauria** [comment]
@mdosanjh can you bring any changes back to master and then cherry-pick to v5.0.x?

**Comment by mdosanjh** [comment]
> @mdosanjh can you bring any changes back to master and then cherry-pick to v5.0.x?

Yes, I'm working on a fix for the issue brought up, I'll submit a pull request and a cherry-pick once it's done.

**Comment by awlauria** [comment]
v5.0.x fix: #10077

**Pull request merged**
