### PR TITLE
btl/uct: bump allowed version to v1.9.x

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@google.com>

### CODE REVIEW

**Comment by hjelmn** [comment]
Builds fine with the latest v1.9.x branch. Please confirm no major API change from v1.8.x.

**Comment by bosilca** [comment]
This fix has been waiting on my branches for a while. It fixes parts of the rndv protocol over UCT, but I still noticed deadlocks even for simple ping/pong tests.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/10139af7717421d991d80e3cb1d4df96

**Comment by hjelmn** [comment]
@bosilca Ok, good to know. I can probably fix it but I need to find a IB system to test on. Will check at UNM on Monday.

**Comment by jjhursey** [comment]
IBM Ci had an issue over the weekend. Retrying. bot:ibm:retest

**Review by gpaulsen — APPROVED** [review]
Looks good.

**Pull request merged**
