### PR TITLE
MPI4: move pcollreq into the MPI namespace

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ac6d06b249bfbb022f86c9ecb4c6032f

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2face426c876925b264c63fbb14c8577

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fb533447aad192d2ad4378ab2b037a57

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f88377b10eaf28d18bdd5dc6501a4d29

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b12c028f4ed2de9f4dd1161e002c1425

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6562a5c1f2b825ab306a8241d297f479

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c27818233f0cefef38ec0153ddf8ca0a

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/afac02818ba6729d93117a26f83d9bd2

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/87d7d72e997e6516a4df5a0f872702e5

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3d8fb5062fd7026d1330f0bcf5c27649

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/593f8f56c4b4d391ec635fa23dae5c94

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a22c589d3d59d910e8793137d9de0306

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7cf2435fcf2622e2d62ad4c437597650

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3638a57c6208876e12f04b0fd24ea8bb

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/30cff2147a4f3f9e32f3a4bc293324b2

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/64f86af742dd94222cd81d11152cc8ce

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7c30b03e4dccd9608c6c1624a516055c

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/292c0b57fc78f809e5e05237cdcb7af1

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b3fbd1f4c677e828835cc2a973713f9b

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/dcf4c53ec14a4253b8f3da86a2497bd5

**Comment by hppritcha** [comment]
@ggouaillardet is this ready to be non-drafty?

**Comment by hppritcha** [comment]
@ggouaillardet ping we'd like to merge this if its ready.  Could you move it out of draft state?

**Comment by ggouaillardet** [comment]
@hppritcha let me squash the commits and give it a final review

**Comment by ggouaillardet** [comment]
I will update the ibm test suite to handle both `MPI_` (new) and `MPIX_` (old) names before I mark this PR as non drafty

**Comment by jsquyres** [comment]
An alternative: update the test suite to only build/run if the `MPI_foo` symbols are present (i.e., ignore the `MPIX_foo` case).

**Comment by ggouaillardet** [comment]
@jsquyres that would make things easier indeed!

**Comment by ggouaillardet** [comment]
Done in open-mpi/ompi-tests#151

**Comment by ggouaillardet** [comment]
@hppritcha The PR is now ready for review.
I did not squash the commits in order to ease the review process, but I will be happy to do so if needed before the merge.

Also, this PR should not be merged before open-mpi/ompi-tests#151 (otherwise non persistent collectives won't be tested at all in the `master` branch).

**Review by hppritcha — APPROVED** [review]

**Pull request merged**
