### PR TITLE
Remove openib and affiliated stuff

### LINKED ISSUE #6265: BTL openib clang compiler errors
On master, openib is failing to compile with clang 5/6/7 with the following errors.  I have not checked any of the release branches.

Do we care any more?  Or is it time to `rm -rf openib` (per the v5.0.0 plans -- see https://github.com/open-mpi/ompi/wiki/5.0.x-FeatureList)?

```
  CC       btl_openib_endpoint.lo
btl_openib_endpoint.c:388:32: error: address argument to atomic operation must be a pointer to _Atomic type ('void **' invalid)
            void *alloc_base = opal_atomic_swap_ptr (&endpoint->eager_rdma_local.alloc_base, NULL);
                               ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../opal/include/opal/sys/atomic_stdc.h:96:43: note: expanded from macro 'opal_atomic_swap_ptr'
#define opal_atomic_swap_ptr(addr, value) atomic_exchange_explicit (addr, value, memory_order_relaxed)
                                          ^                         ~~~~
/cm/shared/apps/clang/6.0.0/lib/clang/6.0.0/include/stdatomic.h:138:34: note: expanded from macro 'atomic_exchange_explicit'
#define atomic_exchange_explicit __c11_atomic_exchange
                                 ^
1 error generated.
make: *** [btl_openib_endpoint.lo] Error 1
```

and

```
  CC       connect/btl_openib_connect_udcm.lo
connect/btl_openib_connect_udcm.c:2154:14: error: address argument to atomic operation must be a pointer to _Atomic type ('int32_t *' (aka 'int *') invalid)
    if (0 == opal_atomic_swap_32 (&m->cm_message_event_active, 1)) {
             ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../opal/include/opal/sys/atomic_stdc.h:94:42: note: expanded from macro 'opal_atomic_swap_32'
#define opal_atomic_swap_32(addr, value) atomic_exchange_explicit (addr, value, memory_order_relaxed)
                                         ^                         ~~~~
/cm/shared/apps/clang/6.0.0/lib/clang/6.0.0/include/stdatomic.h:138:34: note: expanded from macro 'atomic_exchange_explicit'
#define atomic_exchange_explicit __c11_atomic_exchange
                                 ^
connect/btl_openib_connect_udcm.c:2212:5: error: address argument to atomic operation must be a pointer to _Atomic type ('int32_t *' (aka 'int *') invalid)
    opal_atomic_swap_32 (&m->cm_message_event_active, 0);
    ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../opal/include/opal/sys/atomic_stdc.h:94:42: note: expanded from macro 'opal_atomic_swap_32'
#define opal_atomic_swap_32(addr, value) atomic_exchange_explicit (addr, value, memory_order_relaxed)
                                         ^                         ~~~~
/cm/shared/apps/clang/6.0.0/lib/clang/6.0.0/include/stdatomic.h:138:34: note: expanded from macro 'atomic_exchange_explicit'
#define atomic_exchange_explicit __c11_atomic_exchange
                                 ^
2 errors generated.
make: *** [connect/btl_openib_connect_udcm.lo] Error 1
```

### PR DESCRIPTION
**Pull request by jsquyres**
Per https://github.com/open-mpi/ompi/wiki/5.0.x-FeatureList, remove the openib BTL.

As a consequence, also:

* Update README
* Move the `ibv_fork_check` functionality to `oshmem/mca/sshmem/verbs`
* Remove `opal/mca/common/verbs` and `opal/mca/common/verbs_usnic`

Need to check with Mellanox on the status of `oshmem/mca/sshmem/verbs`.  If it's still used, we can fold much of `config/opal_check_openfabrics.m4` and `config/opal_check_verbs.m4` into `oshmem/mca/sshmem/verbs`.  If it's no longer used / deprecated, we can just remove all of that functionality.

@hoopoepg @yosefe Can you guys comment on whether `oshmem/mca/sshmem/verbs` is still used?  I.e., should I fold the verbs configury stuff up into `oshmem/mca/sshmem/verbs`?  Or should `oshmem/mca/sshmem/verbs` go away, along with all the verbs configury?

Fixes #6265.

### CODE REVIEW

**Comment by yosefe** [comment]
@jsquyres oshmem/mca/sshmem/verbs is deprecated.
BTW, how do we plan to run OpenMPI now with iWarp devices, for example?

**Comment by thananon** [comment]
Just giving my 2 cents here...

1. btl/uct is still not ready to fully replace btl/openib for infiniband. At least on the multithreaded part, sometimes uct segfaults. I can provide full detail on that later. Right now I'm using openib as a 'fallback' btl. That being said, I can maintain openib btl in a separated branch.

2. Mellanox is pushing pml/ucx. With the btl, maybe it adds more confusion.

**Comment by jsquyres** [comment]
Rats -- we forgot to talk about this today on the 2019-01-15 webex...

**Comment by jsquyres** [comment]
@yosefe Just to be clear: should I also remove oshmem/mca/sshmem/verbs as part of this PR?

**Comment by yosefe** [comment]
@jsquyres yes, need to remove also oshmem/mca/sshmem/verbs

**Comment by jsquyres** [comment]
@yosefe Updated. Could you please check to make sure I didn't break anything in the OSHMEM layer?

**Comment by hppritcha** [comment]
bot:ompi:retest

**Pull request merged**
