### PR TITLE
Topic/dynamic rules

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
Here is a PR that solves the issue discussed in http://www.open-mpi.org/community/lists/devel/2015/05/17425.php

**Comment by mellanox-github** [comment]
* Coverity found 898 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_535/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_535/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_535/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/535/
Test PASSed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 873 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//548/Coverity_Reports <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/548/

**Build Log**
*last 50 lines*

 ```
[...truncated 32741 lines...]
+ '[' 0 -ne 0 ']'
+ for hca_dev in '$(ibstat -l)'
++ cat /sys/class/infiniband/mlx5_0/device/numa_node
+ var=0
+ export TEST_CLOSEST_NUMA=0
+ TEST_CLOSEST_NUMA=0
+ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 8 -mca mpi_warn_on_fork 0 -mca btl_openib_warn_default_gid_prefix 0 --map-by dist -mca rmaps_dist_device mlx5_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test

Success rank - 5: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.

Success rank - 7: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.

Success rank - 4: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ set -e
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/548/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/548/tap-master-files/cov_stat.tap].
not ok - coverity detected 873 failures in all # SKIP
not ok - coverity detected 5 failures in oshmem # TODO
ok - coverity found no issues for yalla
ok - coverity found no issues for mxm
not ok - coverity detected 2 failures in fca # TODO
ok - coverity found no issues for hcoll

There are failed test cases and the job is configured to mark the build as failure. Marking build as FAILURE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/548/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/a5b3ffe34ae9a083597c850aa55d7bb99aa8a08a
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] TAP test failed
[BFA] Done. 0s
Setting status of 03202fcf07574c05be49685cbd52f87f7ce92f5f to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/548/ and message: Build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 873 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//549/Coverity_Reports <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/549/

**Build Log**
*last 50 lines*

 ```
[...truncated 32741 lines...]
+ '[' 0 -ne 0 ']'
+ for hca_dev in '$(ibstat -l)'
++ cat /sys/class/infiniband/mlx5_0/device/numa_node
+ var=0
+ export TEST_CLOSEST_NUMA=0
+ TEST_CLOSEST_NUMA=0
+ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 8 -mca mpi_warn_on_fork 0 -mca btl_openib_warn_default_gid_prefix 0 --map-by dist -mca rmaps_dist_device mlx5_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test

Success rank - 4: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.

Success rank - 7: only one NUMA is scheduled.

Success rank - 5: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ set -e
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/549/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/549/tap-master-files/cov_stat.tap].
not ok - coverity detected 873 failures in all # SKIP
not ok - coverity detected 5 failures in oshmem # SKIP
ok - coverity found no issues for yalla
ok - coverity found no issues for mxm
not ok - coverity detected 2 failures in fca # SKIP
ok - coverity found no issues for hcoll

There are failed test cases and the job is configured to mark the build as failure. Marking build as FAILURE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/549/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/a5b3ffe34ae9a083597c850aa55d7bb99aa8a08a
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] TAP test failed
[BFA] Done. 0s
Setting status of 03202fcf07574c05be49685cbd52f87f7ce92f5f to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/549/ and message: Build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 873 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//550/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/550/

**Build Log**
*last 50 lines*

 ```
[...truncated 32427 lines...]
2492.064177
2429.830028
2488.225310
2473.912481
2538.224555
+ '[' no == yes ']'
++ ompi_info --param pml all --level 9
++ grep yalla
++ wc -l
+ local val=4
++ ibstat -l
+ for hca_dev in '$(ibstat -l)'
+ '[' -f /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/bw_th ']'
+ local hca=mlx4_0:1
+ mca='-bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1'
+ echo 'Running /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/bw_th 8'
Running /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/bw_th 8
+ '[' no == yes ']'
+ timeout -s SIGKILL 10m mpirun -np 2 -bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1 -mca pml cm -mca mtl mxm /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/bw_th 8
Bandwidth (Mbits/s)
712.456984
664.649636
653.353369
639.795207
639.669536
629.261517
./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh: line 169: 25560 Killed                  $timeout_exe mpirun -np $np $mca -mca pml cm -mca mtl mxm ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/550/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/550/tap-master-files/cov_stat.tap].
not ok - coverity detected 873 failures in all # SKIP
not ok - coverity detected 5 failures in oshmem # SKIP
ok - coverity found no issues for yalla
ok - coverity found no issues for mxm
not ok - coverity detected 2 failures in fca # SKIP
ok - coverity found no issues for hcoll

There are failed test cases. Marking build as UNSTABLE
TAP Reports Processing: FINISH
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-master-pr/builds/550/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/a5b3ffe34ae9a083597c850aa55d7bb99aa8a08a
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 03202fcf07574c05be49685cbd52f87f7ce92f5f to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/550/ and message: Build finished.
```

Test FAILed.

**Comment by bosilca** [comment]
The rules are supposed to be put in the file in their logical sequence (aka. sorted), otherwise they can hardly define intervals that can be used by the engine.

**Comment by hppritcha** [comment]
@bosilca From your comment, it sounds like this PR should be closed, no?

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/7/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/96/
Test PASSed.

**Comment by bosilca** [comment]
:+1:

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/21/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/110/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 815 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//603/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jsquyres** [comment]
Ok, this one is now good -- @ggouaillardet note that the "default" jenkins entry here reflects an old Mellanox Jenkins run (that has now been replaced with a "Mellanox" jenkins run).  Meaning: the old failed "default" build won't go away.

**Comment by bosilca** [comment]
As stated earlier during the discussion the rules are supposed to be defined in their logical sequence (aka. sorted), otherwise they can hardly define intervals that can be used by the engine. As such this PR should be closed.

**Pull request closed without merging**
