### PR TITLE
osc/base: Detect unsupported data types and abort

### PR DESCRIPTION
**Pull request by jjhursey**
Using MPI_MINLOC or MPI_MAXLOC with the following data types
leads to data corruption:
 * MPI_DOUBLE_INT
 * MPI_LONG_INT
 * MPI_SHORT_INT
 * MPI_LONG_DOUBLE_INT

Detect this print a error message and abort.
This workaround should be removed once the following issue is resolved:
 * https://github.com/open-mpi/ompi/issues/1666

### CODE REVIEW

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by jjhursey** [comment]
@nysal What do you think about bringing this protection into the branch as a mitigation for Issue #1666 ?

**Comment by gpaulsen** [comment]
@jjhursey Please create PR for v2.0.x and v2.x.

**Comment by jjhursey** [comment]
@gpaulsen PR's filed #2927 and #2928

**Comment by nysal** [comment]
@jjhursey I think its better than the silent data corruption we have at the moment. @jsquyres has requested some changes in #2927 though.

**Comment by nysal** [comment]
I think this patch will only work for osc/pt2pt. osc/rdma will probably need a similar check in ompi_osc_rdma_rget_accumulate_internal()

**Pull request merged**
