### PR TITLE
configury: misc fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs. #6349 #5539

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@gbossu this PR fixes (among other things) an abstraction violation when `io/ompio` invokes a function in an other component ( `fs/ime` here). I have no way to test it nor even build it. Could you please give it a try ?

@edgargabriel FYI

**Comment by AboorvaDevarajan** [comment]
Can one of the admins verify this patch?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/24630333a51b534f947191ea0cff2e7e

**Comment by gpaulsen** [comment]
@ggouaillardet @edgargabriel,

It seems like we'd like this PR.  What do you think?  I could try to rebased this and test it, if you think.

**Comment by edgargabriel** [comment]
@gpaulsen I am fundamentally fine with that as well, just need to find to ping DDN to test the change for the ime component. 

@ggouaillardet the pr is marked as WIP-DNM Did you have other fixes in working for this pr?

**Comment by ggouaillardet** [comment]
@edgargabriel @gpaulsen I rebased the PR and fixed the conflicts.
I marked it as "Work In Progress" pending on DDN's review (or anyone else that can test is on a IME enabled filesystem).

Feel free to remove this label and merge the PR.
If needed, I can split it into two PR with one for IME's stuff only.

**Comment by gbossu** [comment]
> @gbossu this PR fixes (among other things) an abstraction violation when `io/ompio` invokes a function in an other component ( `fs/ime` here). I have no way to test it nor even build it. Could you please give it a try ?
> 
> @edgargabriel FYI

Hi @ggouaillardet , unfortunately I am not working at DDN Storage anymore and cannot test it right now. I remember we had a wrapper library for testing purposes, but I don't know if it is up to date. Maybe @sydidelot could help with the issue.

**Comment by sydidelot** [comment]
> @edgargabriel @gpaulsen I rebased the PR and fixed the conflicts.
> I marked it as "Work In Progress" pending on DDN's review (or anyone else that can test is on a IME enabled filesystem).
> 
> Feel free to remove this label and merge the PR.
> If needed, I can split it into two PR with one for IME's stuff only.

@ggouaillardet sorry for the late reply. I just noticed the discussion.
I can help wih the issue. As @gbossu suggested, there is a wrapper library that you can use to test if OpenMPI compiles with IME: https://github.com/DDNStorage/ime_2_posix
You can give it a try. In the meantime, I will verify if the PR compiles with IME. I keep you posted.

**Comment by awlauria** [comment]
bot:retest

**Comment by awlauria** [comment]
@sydidelot were you able to verify that this patch works?

**Comment by gpaulsen** [comment]
@ggouaillardet Do we still want this for v5.0?  Can you please rebase or close?

**Review by bwbarrett — APPROVED** [review]

**Comment by awlauria** [comment]
@ggouaillardet if you want to rebase/fix the conflict, I think it's ready to go

**Pull request merged**
