### PR TITLE
Remove mxm

### PR DESCRIPTION
**Pull request by bartonski**
Signed-off-by: Barton Chittenden <bartonski@gmail.com>

#hacktoberfest

### CODE REVIEW

**Comment by hppritcha** [comment]
I think we need some context.  Do you work for Mellanox/Nvidia?

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
@hppritcha This PR came from a [Hacktoberfest](https://hacktoberfest.digitalocean.com/) session that I led tonight (an annual event to encourage participation in open source).  This PR is because I asked @jladd-mlnx earlier today if the MXM component on master is still relevant.  He said it wasn't, and they'd remove it.  I asked if it was ok for one of my Hacktoberfest attendees to submit a PR to do this, and Josh was ok with it.

**Comment by jsquyres** [comment]
Oops -- looks like I gave @bartonski some bad advice on this one; looks like there's more MXM in there than I thought.  I'll look at this in more detail tomorrow.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3dba2029d4a998f158468b42a285b151

**Comment by ggouaillardet** [comment]
@jladd-mlnx is `hcoll` still relevant? or should it be removed as well?

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b63ab5364de7ba5926b9a2137dc4bca2

**Comment by jsquyres** [comment]
Yes, `hcoll` is still relevant, as I understand it.

I'm checking with @jladd-mlnx (via email) to see if Mellanox wants to move forward here, because `yalla` is still in the tree, too.

**Comment by gpaulsen** [comment]
@bartonski This one might take some time to resolve...

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by gpaulsen** [comment]
IBM CI is failing because we explicitly include Yalla.

**Comment by jjhursey** [comment]
The IBM CI configure isn't explicitly including yalla. What's happening is that the `pml/yalla/configure.m4` is calling the `OMPI_CHECK_MXM` macro [here](https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/yalla/configure.m4#L18-L20) which no longer exists since this PR removed the `ompi_check_mxm.m4`. I would suggest adding back the `config/ompi_check_mxm.m4` file to this PR. That should get it through CI.

If the move is to also take out `ompi/mca/pml/yalla` then we can likely remove the `ompi_check_mxm.m4`

A quick grep around shows the `OMPI_CHECK_MXM` is also used by some of the OpenShmem components:
 * `oshmem/mca/atomic/mxm`
 * `oshmem/mca/spml/ikrit`

**Comment by jsquyres** [comment]
I understand what's happening in CI.  I'm waiting for Mellanox / @jladd-mlnx's reply (probably in email?) to decide what to do with this PR (i.e., fully remove MXM or fully leave MXM).  There's nothing to be done until Mellanox replies.

**Comment by jsquyres** [comment]
@jladd-mlnx and I conferred in email.  He confirms to me that all MXM-related components can be removed (there's a few that do not have "MXM" in the name).

@bartonski Can you please squash the following into your existing commit?

```
git rm -rf \
    ompi/mca/pml/yalla \
    oshmem/mca/spml/irkit
```

That should trigger CI again, and everything should be fine with this build.

Huzzah for CI!

**Comment by bartonski** [comment]
Jeff, did you mean oshmem/mca/spml/ikret?

**Comment by jsquyres** [comment]
@yosefe Please check with @jladd-mlnx -- he confirmed to me in email that removing the MXM components from master was ok...?  (you were CC'ed on that email thread)

Can Mellanox please give us a definitive ruling?  Thanks!

**Comment by jsquyres** [comment]
Great -- Mellanox just signed off on this PR.  Thanks!

@bartonski Could you rebase this PR to the top of master/HEAD?  There's some conflicts, and there's also somehow a mystery 2nd commit on this PR.

**Comment by awlauria** [comment]
@bartonski ping - please rebase on top of master and force push. Another commit snuck into this pr.

**Comment by jsquyres** [comment]
I gave up waiting and fixed this PR myself.

**Pull request merged**
