### PR TITLE
Update to the TCP-based version of PMIx

### PR DESCRIPTION
**Pull request by rhc54**
Not an official release at this time, but worth checking in the wild.

### CODE REVIEW

**Comment by rhc54** [comment]
MTT results:

```shell
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                          |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| MPI Install | my installation | 3.0.0a1     | 00:02    | 1    |      |          |      | MPI_Install-my_installation-my_installation-3.0.0a1-my_installation.html |
| Test Build  | trivial         | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Build-trivial-my_installation-3.0.0a1-my_installation.html          |
| Test Build  | ibm             | 3.0.0a1     | 00:44    | 1    |      |          |      | Test_Build-ibm-my_installation-3.0.0a1-my_installation.html              |
| Test Build  | intel           | 3.0.0a1     | 01:28    | 1    |      |          |      | Test_Build-intel-my_installation-3.0.0a1-my_installation.html            |
| Test Build  | java            | 3.0.0a1     | 00:02    | 1    |      |          |      | Test_Build-java-my_installation-3.0.0a1-my_installation.html             |
| Test Build  | orte            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Build-orte-my_installation-3.0.0a1-my_installation.html             |
| Test Run    | trivial         | 3.0.0a1     | 00:12    | 8    |      |          |      | Test_Run-trivial-my_installation-3.0.0a1-my_installation.html            |
| Test Run    | ibm             | 3.0.0a1     | 14:04    | 489  |      |          |      | Test_Run-ibm-my_installation-3.0.0a1-my_installation.html                |
| Test Run    | spawn           | 3.0.0a1     | 00:26    | 7    |      |          |      | Test_Run-spawn-my_installation-3.0.0a1-my_installation.html              |
| Test Run    | loopspawn       | 3.0.0a1     | 10:04    | 1    |      |          |      | Test_Run-loopspawn-my_installation-3.0.0a1-my_installation.html          |
| Test Run    | intel           | 3.0.0a1     | 21:13    | 474  |      |          | 4    | Test_Run-intel-my_installation-3.0.0a1-my_installation.html              |
| Test Run    | intel_skip      | 3.0.0a1     | 16:39    | 431  |      |          | 47   | Test_Run-intel_skip-my_installation-3.0.0a1-my_installation.html         |
| Test Run    | java            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Run-java-my_installation-3.0.0a1-my_installation.html               |
| Test Run    | orte            | 3.0.0a1     | 00:45    | 19   |      |          |      | Test_Run-orte-my_installation-3.0.0a1-my_installation.html               |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
```

**Comment by rhc54** [comment]
bot:lanl:retest

**Comment by rhc54** [comment]
@ggouaillardet I'm having problems with the new PTL/TCP component in PMIx. The disable-dlopen test keeps failing here, but I cannot replicate the problem. It looks to be some kind of memory corruption, but valgrind doesn't report it, and I can't get a debugger to trip on it.

The error seems to stem from the ptl_tcp_component.c, setup_listener function, but I cannot completely confirm that finding.

Can you spend a few cycles on this and help me figure out what is going on? Even just localizing the source of the problem would be of great help.

**Comment by rhc54** [comment]
I should also note that everything runs fine when using a default build - it is only the disable-dlopen build that is failing.

**Comment by ggouaillardet** [comment]
@rhc54 ok will do
any hints on how to reproduce the issue ?
(e.g. number of nodes, tasks per node, kind of test ?)

**Comment by ggouaillardet** [comment]
@rhc54 i do see an error in singleton mode
the environment passed in ```orted_uri``` is
```PMIX_NAMESPACE=1093664769,PMIX_RANK=0,PMIX_SERVER_URI2=pmix-server.3512;tcp4://127.0.0.1:36789,PMIX_SERVER_URI=pmix-server:3512:/tmp/pmix-3512,PMIX_SECURITY_MODE=native,none,PMIX_PTL_...```

the issue here is
```PMIX_SECURITY_MODE=native,none```
since we ```opal_argv_split(..., ',')```, we endup "parsing" ```none``` which is not ```A=B``` and an assert fails

something is odd in my environment ... configury fails in libevent unless i ```--disable-dlopen```, so i could not confirm what happens in this case.

btw, are you positive the issue is ```--disable-dlopen``` and not the singleton usage ?

**Comment by rhc54** [comment]
The disable-dlopen test is failing on an "mpirun -n 1 ./hello_c" command, not a singleton. I'll check singleton (I hadn't done that yet), but I suspect the problem is some kind of memory corruption that triggers the LANL environment when disable-dlopen is used - probably because the offending area is placed in memory near something that gets touched.

**Comment by ggouaillardet** [comment]
@rhc54 i will double check that, can you also double check it too ?

here is the jenkins output for ```LANL-disable-dlopen``` from https://jenkins.open-mpi.org/jenkins/job/ompi_master_pr_disable_dlopen/416/console

```mpirun -np 2 ...``` works fine
 
```
+ timeout -s SIGKILL 3m mpirun -np 2 ./hello_usempif90.x
Hello, world, I am  1 of  2: Open MPI v3.0.0a1, package: Open MPI hppritcha@ompi Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3288-g815f9937, Unreleased developer copy                                                                                                                 
Hello, world, I am  0 of  2: Open MPI v3.0.0a1, package: Open MPI hppritcha@ompi Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3288-g815f9937, Unreleased developer copy                                                                                                                 
+ '[' 0 '!=' 0 ']'
+ echo 'Run of f90 usempif90  hello world SUCCESS'
Run of f90 usempif90  hello world SUCCESS
```

then singleton fails
```
+ timeout -s SIGILL 3m ./hello_c.x
[ompi:06395] *** Process received signal ***
[ompi:06395] Signal: Segmentation fault (11)
[ompi:06395] Signal code: Address not mapped (1)
[ompi:06395] Failing at address: (nil)
[ompi:06395] [ 0] /lib64/libpthread.so.0(+0xf9f0)[0x7fdf0ea289f0]
[ompi:06395] [ 1] /home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/ompi_install/lib64/libopen-rte.so.0(+0x7c293)[0x7fdf0e3c6293]
[ompi:06395] [ 2] /home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/ompi_install/lib64/libopen-rte.so.0(orte_init+0x286)[0x7fdf0e373196]
[ompi:06395] [ 3] /home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/ompi_install/lib64/libmpi.so.0(ompi_mpi_init+0x2dd)[0x7fdf0ecb16bd]
[ompi:06395] [ 4] /home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/ompi_install/lib64/libmpi.so.0(MPI_Init+0x5b)[0x7fdf0ecd865b]
[ompi:06395] [ 5] ./hello_c.x[0x400989]
[ompi:06395] [ 6] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fdf0e68cbe5]
[ompi:06395] [ 7] ./hello_c.x[0x400889]
[ompi:06395] *** End of error message ***
/tmp/hudson6269131936731817830.sh: line 82:  6394 Segmentation fault      timeout -s SIGILL 3m ./hello_c.x
```

so i do not see ```mpirun -np 1 ...``` here



singleton is broken regardless ```dlopen``` is enabled or not

here is a fix (use space separator instead of comma)

```patch
diff --git a/orte/mca/ess/singleton/ess_singleton_module.c b/orte/mca/ess/singleton/ess_singleton_module.c
index 7ba5699..83af063 100644
--- a/orte/mca/ess/singleton/ess_singleton_module.c
+++ b/orte/mca/ess/singleton/ess_singleton_module.c
@@ -633,7 +633,7 @@ static int fork_hnp(void)
         orte_process_info.my_hnp_uri = orted_uri;
 
         /* split the pmix_uri into its parts */
-        argv = opal_argv_split(cptr, ',');
+        argv = opal_argv_split(cptr, ' ');
         count = opal_argv_count(argv);
         /* push each piece into the environment */
         for (i=0; i < count; i++) {
diff --git a/orte/orted/orted_main.c b/orte/orted/orted_main.c
index 65784f6..9e09c67 100644
--- a/orte/orted/orted_main.c
+++ b/orte/orted/orted_main.c
@@ -612,7 +612,7 @@ int orte_daemon(int argc, char *argv[])
         opal_argv_append_nosize(&singenv, env_str);
         free(env_str);
 
-        nptr = opal_argv_join(singenv, ',');
+        nptr = opal_argv_join(singenv, ' ');
         opal_argv_free(singenv);
         /* create a string that contains our uri + sysinfo + PMIx server URI envars */
         orte_util_convert_sysinfo_to_string(&sysinfo, orte_local_cpu_type, orte_local_cpu_model);
```

**Comment by rhc54** [comment]
sigh - you are quite correct, I misread the output. I'd prefer to split on something solid and not a space - testing something now. thx!

**Comment by ggouaillardet** [comment]
with a bit of rework, we could "split" on ```'\0'```
(so we can correctly handle ```A=B=C```)

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/1c0802e7daeff8b5aa6889d53fdd37d0

**Comment by rhc54** [comment]
I just set it up to split on an asterisk, which should be okay. Got a weird error from IBM/PGI, but the link says it passed...

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
broken repo

**Pull request closed without merging**
