### PR TITLE
stale-bot config

### PR DESCRIPTION
**Pull request by jsquyres**
Initial configuration for the Probot stale bot:
https://github.com/probot/stale.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
Proposal to discuss at the 2019-03-19 webex: Probot stale bot (https://github.com/probot/stale).  The config options I put in here are just the starting point for a discussion.

PROs:
* Auto-close all those issues that, realistically, we won't get to
* Put a label on them to easily find them again someday, if needed

CONs:
* This would take effect of *all* of our old issues and/or PRs (can't limit it to just "new" issues to try it out)

**NOTE:** I initially proposed the "lock" bot at the RM meeting on 2019-03-18 (https://probot.github.io/apps/lock/), without realizing that it actually *prevents any further discussion on an issue/PR* (i.e., it *locks* them).  The lock bot allows selectively applying to issues/PRs after a certain date.  This one -- the stale bot -- does not: it would apply to *all* of our open issues/PRs.

If we want to start using the the stale bot, we might want to manually do something about all of our old/stale bugs before enabling it.

**Comment by jsquyres** [comment]
Put out for comment on the OMPI dev list: https://www.mail-archive.com/devel@lists.open-mpi.org/msg20868.html

**Comment by jsquyres** [comment]
It looks like we're leaning towards running this bot on our own node.js server (e.g., on aws.open-mpi.org).  One of the OMPI organizations may be able to provide a resource to actually get this done within the next month or so.

There's no real rush on this, so let's wait until that resource becomes available.

**Comment by gpaulsen** [comment]
As discussed in today's web-ex, Brian has created a wiki for Bot tasks for this summer:

    * Github wiki page under open mpi for 'CI development tasks'
    | ¦* Wishlist wiki: https://github.com/open-mpi/ompi/wiki/GitHub-Robot-Tasks
    | ¦* Auto adding labels to PRs.
    | ¦* Would all run on AWS Jenkins server
    | ¦* Nice framework is in NODE.js

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
@bwbarrett Did we decide not to do the stale bot?  Or was this just waiting for us to set up our own probot instance?

**Comment by lrbison** [comment]
🧟 I think this one is OBE by https://github.com/open-mpi/ompi/pull/12329, can we close it?

**Pull request closed without merging**
