### PR TITLE
atomic: add support for __atomic builtins

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds support for the gcc __atomic builtins. The __sync
builtins are deprecated and have been replaced by these atomics. In
addition, the new atomics support atomic exchange which was not
supported by __sync.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca This is a work in progress. Might make it part of a larger change to the atomics that adds C11 support.

**Comment by hjelmn** [comment]
@bosilca Can you double-check the memory-model arguments? I am pretty sure they match the intended semantics of the opal_atomic_* functions.

**Comment by bosilca** [comment]
I think our code assume that opal_atomic_cmpset_32 uses the ACQUIRE memory model and not the RELAXED. IF we want to change this we should audit the code to make sure we are not assuming a stricter memory model (based on the semantic of the sync_* atomic intrinsics).

**Comment by hjelmn** [comment]
I think you are correct. I updated the PR to use acquire for opal_cmpset_*.

**Comment by bosilca** [comment]
Looks good. 👍

**Pull request merged**
