### PR TITLE
Topic/misc pmix fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by rhc54** [comment]
So are you available to commit this, or do you need me to do it? I can fix the one typo after the commit if you are out this week. Just need to know as I'm actively trying to work on this code area, and don't want to be blocked all week.

**Comment by ggouaillardet** [comment]
please go ahead and fix&commit my changes since I will not work on that till monday.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
