### PR TITLE
Update the PMIx2 support to include the latest shared memory optimizations

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/aa48c0242349f045df400f244b2cd21a

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/dc9f38adec8d05ee25bcc22e3e32b1bc

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/e0b0ef1534b98145997610c18a69eba0

**Comment by rhc54** [comment]
@artpol84 @yosefe Looks like some commit broke UCX compile - can you please fix?

**Comment by artpol84** [comment]
@rhc54 we will take care. Thank you!

**Comment by artpol84** [comment]
@Di0gen

**Comment by rhc54** [comment]
bot:mellanox:retest

**Pull request merged**
