### PR TITLE
Remove stale defunct tools

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
@gpaulsen @hppritcha None of these tools work any more, nor are they maintained

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fdd3a855eb327b9a7cecd0f1097f294f

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7d9218e61ac8b55c5ed7d96ccf7437f9

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1f07d2738523a1b59df3c61739b20d9b

**Pull request merged**
