### PR TITLE
grpcomm rcd:remove unnecessary malloc warning when number of daemons == 1

### PR DESCRIPTION
**Pull request by nkogteva**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 923 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_404/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_404/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_404/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/404/
Test PASSed.

**Comment by jsquyres** [comment]
This may be a naieve question, but I don't immediately see how `coll` is allocated, so I'll ask: does it need to be set to NULL in the `0 == coll->ndmns` case?

**Comment by nkogteva** [comment]
@jsquyres it is set to NULL in constructor and should be kept == NULL until allgather is called on appropriate daemon. NULL value is used in algorithm logic to avoid possible problem with race condition.

**Comment by jsquyres** [comment]
Perfect.  Then: :+1: on this PR.

Thanks!

**Comment by jsquyres** [comment]
Oops -- I didn't see @miked-mellanox's comment until after I submitted mine.  :-)  I was :-1:'ing the "it's already set to NULL" comment.

**Comment by nkogteva** [comment]
@miked-mellanox I think it doesn't make sense because there are other places like orte_grpcomm_base_mark_distance_recv and orte_grpcomm_base_check_distance_recv functions, where type of distance mask is visibly specified (in function's notation, for example). The main purpose of that PR is just remove warning about allocation of 0 sized memory.

**Comment by miked-mellanox** [comment]
agree. :+1:

**Pull request merged**
