### PR TITLE
btl/openib: enhance the verbosity level when using rdmacm without a first PP QP

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@jladd-mlnx / @hjelmn can you please take a look?

**Comment by jladd-mlnx** [comment]
:+1:

**Comment by hjelmn** [comment]
Gotta add some more logic. Do not want this warning if another CPC can run.

**Comment by jladd-mlnx** [comment]
@hjelmn All this does is allow one to see that it was skipped with btl_base_verbose set.

**Comment by hjelmn** [comment]
Ah, yes. I see. It required verbose 5. Good.

**Pull request merged**
