### PR TITLE
v4.0.x: Cherry-pick fixes for issue #6258 from master (vader fixes)

### PR DESCRIPTION
**Pull request by bosilca**
A quick fix for issue #6258.

### CODE REVIEW

**Comment by hppritcha** [comment]
@jjhursey could you check what's going on with IBM CI?

**Comment by hppritcha** [comment]
@jjhursey any hope to get IBM CI working?  I'd like to merge this in today and cut an rc2.

**Comment by jjhursey** [comment]
@hppritcha Let's kick it off again and I'll watch.
bot:ibm:retest

**Comment by jjhursey** [comment]
@hppritcha Both of the IBM CI tests passed, but the update did not get pushed to GitHub because we are hitting a GitHub usage limit. I'll investigate a bit this morning to see if I can settle things down.

But from IBM CI this is good to go.

**Comment by jjhursey** [comment]
I think the rate limit issue has settled down now. We can retest, but this is good to merge if you need to do so before the CI comes back.
bot:ibm:retest

**Pull request merged**
