### PR TITLE
Dismantle the Tuned collective

### PR DESCRIPTION
**Pull request by bosilca**
As decided during our last developer meeting, all the collective algorithms provided by our tuned module are now part of the base. Thus, they become available to any other module (including basic), allowing for simpler and more straightforward integrations of new collective modules.

As a result, the tuned is now a simple decision layer, providing an environment for simple selection of the base algorithms. The current decision is based on an old study (2008) over a OpenIB 10G cluster, and might be slightly out-dated. I strongly encourage vendors looking to get the most out of available collection of collective algorithms to provide their own collective layer (based on the current tuned module), either as text files or as C code.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/283/

**Build Log**
*last 50 lines*

 ```
[...truncated 10589 lines...]
  CC       base/bml_base_frame.lo
  CC       base/bml_base_ft.lo
  CCLD     libmca_bml.la
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/bml'
make[3]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/include/openmpi/ompi/mca/bml'
 /usr/bin/install -c -m 644  bml.h '/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/include/openmpi/ompi/mca/bml/.'
 /bin/mkdir -p '/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/include/openmpi/ompi/mca/bml/base'
 /usr/bin/install -c -m 644  base/base.h base/bml_base_btl.h '/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/include/openmpi/ompi/mca/bml/base'
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/bml'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/bml'
Making install in mca/coll
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/coll'
  CC       base/coll_base_comm_select.lo
  CC       base/coll_base_comm_unselect.lo
  CC       base/coll_base_find_available.lo
  CC       base/coll_base_frame.lo
  CC       base/coll_base_bcast.lo
  CC       base/coll_base_scatter.lo
  CC       base/coll_base_topo.lo
  CC       base/coll_base_allgather.lo
  CC       base/coll_base_allgatherv.lo
  CC       base/coll_base_util.lo
  CC       base/coll_base_allreduce.lo
  CC       base/coll_base_alltoall.lo
  CC       base/coll_base_alltoallv.lo
  CC       base/coll_base_gather.lo
  CC       base/coll_base_reduce.lo
  CC       base/coll_base_barrier.lo
  CC       base/coll_base_reduce_scatter.lo
base/coll_base_gather.c: In function 'ompi_coll_base_gather_intra_linear_sync':
base/coll_base_gather.c:220: error: redefinition of 'reqs'
base/coll_base_gather.c:217: note: previous definition of 'reqs' was here
make[2]: *** [base/coll_base_gather.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi/mca/coll'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/ompi'
make: *** [install-recursive] Error 1
+ exit 10
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 962ae4559f8095ecb6621fab747d20229e6e46d4 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/283/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
* Coverity found 7 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_284/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/284/
Test PASSed.

**Comment by hppritcha** [comment]
checking this on a cluster here at LANL.

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/299/

**Build Log**
*last 50 lines*

 ```
GitHub pull request #423 of commit 649fac0ee6220ceae963c0db52216247b58084b0.
Setting status of 649fac0ee6220ceae963c0db52216247b58084b0 to PENDING with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/299/ and message: Build started.
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/open-mpi/ompi
 > /usr/bin/git init /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace # timeout=60
Fetching upstream changes from https://github.com/open-mpi/ompi
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git5966121856955541691.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
 > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
Pruning obsolete local branches
Fetching upstream changes from https://github.com/open-mpi/ompi
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git5223917315005759733.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/pull/*:refs/remotes/origin/pr/* --prune # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git rev-parse 649fac0ee6220ceae963c0db52216247b58084b0^{commit} # timeout=60
Merging Revision 649fac0ee6220ceae963c0db52216247b58084b0 (detached) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='default', fastForwardMode='--ff'}
 > /usr/bin/git rev-parse origin/master^{commit} # timeout=60
 > /usr/bin/git config core.sparsecheckout # timeout=60
 > /usr/bin/git checkout -f origin/master # timeout=20
 > /usr/bin/git merge --ff 649fac0ee6220ceae963c0db52216247b58084b0 # timeout=60
 > /usr/bin/git config core.sparsecheckout # timeout=60
 > /usr/bin/git checkout -f 649fac0ee6220ceae963c0db52216247b58084b0 # timeout=20
ERROR: Branch not suitable for integration as it does not merge cleanly: Could not merge AnyObjectId[649fac0ee6220ceae963c0db52216247b58084b0]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 649fac0ee6220ceae963c0db52216247b58084b0 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/299/ and message: Build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@miked-mellanox Is there something wrong with Jenkins?

**Comment by miked-mellanox** [comment]
@hppritcha - jenkins now tries to merge with upstream before running building. merge fails.
you need to rebase or we can disable "merge before test" feature.

**Comment by jsquyres** [comment]
@miked-mellanox Scratch that; never mind -- I understand the error message now.

@hppritcha I think the problem is that the branch does not merge.  Jenkins is basically refusing to test for that reason.

**Comment by hppritcha** [comment]
George could you rebase?
@bosilca

**Comment by bosilca** [comment]
Not really. I moved, deleted and split files, and git is totally confused about this. This is a mess.

**Comment by jsquyres** [comment]
@bosilca and I are webexing to try to fix his rebase woes...

**Comment by bosilca** [comment]
git cherry-pick is my friend. This is now my new mantra.

**Comment by hppritcha** [comment]
I did test on cluster here at LANL and looks okay modulo the merge conflict.

**Comment by jsquyres** [comment]
George just rebased (and fixed a few conflicts in the process).  Should probably test again with the current state of this PR.

**Comment by hppritcha** [comment]
okay will do

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/300/
Test PASSed.

**Pull request merged**
