### PR TITLE
Update opal to use C11 atomics if available

### PR DESCRIPTION
**Pull request by hjelmn**
This PR introduces a new set of types to be used for all opal atomics (opal_atomic_*) and adds support for C11 atomics. If C11 atomics are detected they are used exclusively.

This PR should be safe for v4.0.0 if we want to merge it today. I have no opinion either way.

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca Can you take a look?

@jsquyres @bwbarrett @hppritcha It is my opinion we should always use the language support if it is available. I am sure there will be disagreement so I would like to know how we should proceed. I cab make configure prefer C11 atomics and give a way to force either sync builtins or the hand-written atomics.

**Comment by hjelmn** [comment]
Needs some more work. Will update later today.

**Comment by gpaulsen** [comment]
Would be great for v4.0, but don't hold v4.0 branch.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7832bb04e798446707b0ac52e47527d9

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ab76997b2815f1eae341a336c3c5136e

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0be403e8444be4a21229f9663bd1f7a9

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cf4640237473d5b8edb264c75c9f95db

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8e5e337de32c43533f58991136c52258

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a058c68ac4829512d88a0b4232b0053e

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a055fba3c5299f29ee47b75aa42a9bbe

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6fdd419eac82cfdfbe9c52fe785b01a6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/397d5205c3f19bfd63fc3a8c6dd76d88

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2b0e8832c7bdf06cda64ed6ff383a92b

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b04e4bed5d87773219091b5ef0bc08ef

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4f8d46cdb7e6aa638839f36c0f3ca410

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/73169869ea7c3e51f149e86b7bb41946

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/74073c7233367ad5edd2374a897497a5

**Comment by hjelmn** [comment]
Think I fixed everything. The opal_atomic_*_ptr functions were changed to work on ```c intptr_t``` instead of ```c void *```. This is due to the fact that in C11 there is no ```c atomic_void *```. We could always define one but ```c intptr_t``` is the intended type. Didn't quite get everything updated correctly on the first go.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by gpaulsen** [comment]
What's the down side to using language support if it's available?  I can only imagine that it might bring in more run-time support dependencies (i.e. at run-time the code might be less portable), or that some might object because it might be harder to maintain if there are bugs?  Any other down side that I'm not seeing?

**Comment by gpaulsen** [comment]
Also are any of the structs in here that changed exposed to user's applications (or change the size of structs that are exposed to user's apps)?  I.e. would this PR cause a bump in the .so version?

**Comment by hjelmn** [comment]
No user-facing things changed. All this is completely internal.

**Comment by hjelmn** [comment]
As for downsides, I don't think there are any vs what we already have with the gcc/icc builtins (__sync, __atomic). In fact, __atomic is likely the underlying implementation of the C11/C++11 atomics.

I plan to run some performance tests today to make sure there is no slowdown with the C11 atomics. I do not expect one but need to be sure.

**Comment by hjelmn** [comment]
Ok, that should make the pull request build checker happy. Forgot the int128_t C11 atomics on x86_64 with gcc are not lock-free. The workaround is to use __sync builtins for the 128-bit CAS.

**Comment by hjelmn** [comment]
@hoopoepg The ARM64 tests failed for something unrelated to this PR. Looks like it is in oshmem. Can you take a look at the errors in https://jenkins.open-mpi.org/jenkins/job/open-mpi.build.platforms/3283/Platform=ARMv8/

**Comment by hjelmn** [comment]
Ok, looks good to go now. The only failure appears to be unrelated to this PR.

**Comment by hoopoepg** [comment]
@hjelmn https://github.com/open-mpi/ompi/pull/5473 will work?

**Comment by hjelmn** [comment]
@hoopoepg perfect. thanks!

**Comment by hjelmn** [comment]
:bot:retest

**Comment by hjelmn** [comment]
Ok, so far so good. I have to address one bug then this is good to go. Turns out the implicit memory order is ```memory_order_seq_cst```. We want many of the atomics to be ```memory_order_relaxed```. Will fix and push the update.

**Comment by hjelmn** [comment]
@bosilca Any comments on this?

**Comment by bosilca** [comment]
I only have positive comments. Maybe the only concern I have with this patch is the overwhelming number of functions for atomic support with most of them never used and doubtfully needed in the future. I might have preferred a smaller patch, one that only provide the _strong version of the atomic functions (which is the only one we currently use if I'm not mistaken).

**Pull request merged**
