### PR TITLE
romio: update REFRESH_NOTES to accommodate the random() patch.

### PR DESCRIPTION
**Pull request by thananon**
From patch: open-mpi/ompi@23b27c510c2c626a09457abad7699cfc4740d1eb

### CODE REVIEW

**Comment by jsquyres** [comment]
@thananon I totally missed that this never got merged.  ☹️   It's trivial -- but we just voted in a policy of requiring "signed off by" lines on commits.  If you update this PR and ping me, I'll merge it.  Thanks!

**Comment by thananon** [comment]
Hey @jsquyres , I think there's some complication with this. 

I'm under the impression that there is another PR from @ggouaillardet that fixed this issue and somehow merged this in?

**Comment by jsquyres** [comment]
@thananon Do you mean that your one-line patch to REFRESH_NOTES is no longer necessary because patching 24a6f1425734eb3e6ffb9e37f510507a4a65ebd1 is no longer necessary?

I ask because your PR does not have any merge conflicts, meaning that an equivalent change has not already been committed to REFRESH_NOTES.

**Comment by thananon** [comment]
@jsquyres Please review

**Pull request merged**
