### PR TITLE
ompi/dpm: make procs consistent before calling PMIx_Connect()

### PR DESCRIPTION
**Pull request by wzamazon**
ompi_dpm_connect_accept() call PMIx_Connect() to establish
connection, with "procs" as an argument.

PMIx requires "procs" to be consistent accross clients.

When it is used to set up inter-communicator communication,
ompi_dpm_connect_accept() does not maintain the order of
proc in "procs". This is because the function is called
by both MPI_Comm_connect() and MPI_Comm_accept(), and
it always put processes in local communicator in "procs"
first, followed by processes in remote communicator.

However, for caller of MPI_Comm_connect() and MPI_Comm_accept(),
local communicator and remote communicator are different.

This patch fixed the issue by sorting "procs" before
it is used to call PMIx_Connect(), this ensures that "procs"
are consistent accross processes.

Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Review by hppritcha — APPROVED** [review]

**Comment by wzamazon** [comment]
@rhc54

FYI.

**Comment by wzamazon** [comment]
need to be back ported to v5.0.x

**Review by jjhursey — APPROVED** [review]

**Comment by wzamazon** [comment]
Is there anything I need to do to get this PR merged?

**Comment by hppritcha** [comment]
sorry i thought you had merge capability on main

**Comment by wzamazon** [comment]
> sorry i thought you had merge capability on main

Unfortunately, no. :)

**Comment by jjhursey** [comment]
I think we need this in the v5.0.x branch but not the v4.x branches. Is that accurate?

**Comment by hppritcha** [comment]
the 4 branches do this quite differently.  would probably require a very different patch.    @wzamazon were you seeing mtt problems for intercomm tests for the 4.1.x branch?

**Comment by jjhursey** [comment]
IBM MTT only saw the issue on main and v5.0.x IIRC

**Comment by wzamazon** [comment]
> I think we need this in the v5.0.x branch but not the v4.x branches. Is that accurate?

Correct. This is because `orte` and `prrte` implement the `pmix_server_connect_fn` function differently. prrte will call `grpcomm.allgather`, orte does not.

For your reference, prrte implementation is 

https://github.com/openpmix/prrte/blob/06254c35d99c9f185ba1e85ff0ab0f475a01ceb9/src/prted/pmix/pmix_server_dyn.c#L1150

orte implementation is:

https://github.com/open-mpi/ompi/blob/4fdd439e1ef85983570141c6c0b06945c34483b8/orte/orted/pmix/pmix_server_dyn.c#L734

**Comment by wzamazon** [comment]
back port https://github.com/open-mpi/ompi/pull/10564 to v5.0.x branch

**Comment by rhc54** [comment]
FWIW: I am now sorting the procs in PMIx to avoid this issue. Turned out that people were pre-sorting before giving them to PMIx, and backend environments were sorting the arrays given to them by PMIx - all to avoid order sensitivity. As the intermediary, it makes sense to simply do it there and let both ends avoid the overhead.

So feel free to revert this once you update again - or you can leave it if you like (will just be duplicate effort, but fairly harmless).

@wzamazon My thanks for your prior code submission. I couldn't take it as the branch was gone, and it wasn't entirely complete - but I was able to use what you had done to guide the changes. Much appreciated.

**Pull request merged**
