### PR TITLE
in-place conversion macro writes into INPUT argument

### PR DESCRIPTION
**Pull request by markalle**
merge of 0a7f1e3cc58dabe536df00ae9c97f7e9d27103ad
https://github.com/open-mpi/ompi/pull/6448
into v4.0.x

### CODE REVIEW

**Comment by gpaulsen** [comment]
Mellanox CI failed due to out of space.
retesting...

**Comment by gpaulsen** [comment]
retest

**Comment by gpaulsen** [comment]
bot:retest

**Comment by ggouaillardet** [comment]
@markalle we generally `git cherry-pick -x <commitid>` so git will automatically generate a message with a reference to the commit id in the `master` branch.

**Comment by markalle** [comment]
I did cherry-pick x, so the commit itself has the full text with
```
(cherry picked from commit 0a7f1e3)
```
at the bottom.

Maybe the part that made it look weird is that when I created the github pull request I replaced the text of the commit that would have normally been the top item in the pull request.

**Comment by jsquyres** [comment]
Cray keeps failing for some reason.  Try again.

bot:ompi:retest

**Pull request merged**
