### PR TITLE
MTL/PSM2: fix check for PSM2_LIB_REFCOUNT_CAP

### PR DESCRIPTION
**Pull request by hppritcha**
to honor non-default installs of psm2.h

related to #8651

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
(cherry picked from commit c010cb2b597696e546709ca1101406aeaced8357)

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by mwheinz** [comment]
Do we know why the PR build checker failed for this?

**Comment by jsquyres** [comment]
That looks like a transient error.  Try running again.  If it happens again, then we look closer.

**Comment by jsquyres** [comment]
bot:ompi:retest

**Review by mwheinz — APPROVED** [review]

**Comment by hppritcha** [comment]
@jsquyres LANL is complaining that this isn't in the 4.1.1 release

**Pull request merged**
