### PR TITLE
ROMIO: refresh to 3.3.2

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hppritcha @jsquyres @bwbarrett @jjhursey this is a refresh to romio from mpich 3.3.2

it compiles, but I did not implement `MPIR_Get_node_id()` yet, so it might not work (did not try yet)

There has been some recent discussions about it (hdf5 related issue), so let me know if you are open to delay the release of `4.1.0` to include the latest romio.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/429fd4d0ae5b1a2600d70166ca3924ee

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/16eeef95dbff4d77823e1d9d507ab181

**Comment by jsquyres** [comment]
Howard is going to test this on his Lustre system and see if it fixes the problem.

**Comment by jsquyres** [comment]
Howard replied that this upgrade seemed to fix the lustre problem.  How difficult would it be to finish this import and then also bring it to v4.1.x?

I.e., perhaps the Right answer is "let's have this in v4.1.0".

**Comment by ggouaillardet** [comment]
@jsquyres I still need to implement `MPIR_Get_node_id()` (I am a bit surprised this did not cause a crash yet ...)
Then back porting to the `v4.1.x` branch should be straightforward.

As far as I am concerned, I do not have the resources to find and cherry-pick the ROMIO commit from upstream that fixes this issue (everyone else is obviously free to issue a PR).

Also, from my point of view, upgrading ROMIO is the way to go, even if `4.1.0` is a bit delayed.

I leave the decision up to the Release Managers.

**Comment by ggouaillardet** [comment]
I double checked `MPIR_Get_node_id()` and it turned out it cannot be called by Open MPI.

So the PR is good for review and test!

**Comment by rhc54** [comment]
@ggouaillardet Would it be possible to move ROMIO to the 3rd-party area and then let the component work against it from there? We have moved hwloc, libevent, pmix, and prrte to that location to make it clear they are not OMPI code, and to provide a clean, hopefully common method for supporting internal/external locations. IIRC, ROMIO may no longer be separately distributed from MPICH, but it would still server to clarify that it needs to be left alone and might make it easier to update.

**Comment by hppritcha** [comment]
Unfortunately my previous results posted in issue #8246 weren't accurate as I was not using the --with-io-romio option needed to trigger the lustre issue.

Now that I've gotten that fixed, I'm getting mixed results here using the hdf5 make check script - see issue #6871.  With head of master and using the configure options used in #6871 I observe the hang in the make check reported in #6871 - or at least something similar.  With the update in this PR, the make check no longer hangs but I'm getting a SIGBUS:

```
Program terminated with signal SIGBUS, Bus error.
#0  0x00002aaab3306bb1 in mca_btl_sm_component_progress () from /users/hpp/ompi/install_test/lib/openmpi/mca_btl_sm.so
[Current thread is 1 (Thread 0x2aaaaab30a80 (LWP 18589))]
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.26-13.48.1.x86_64 liblzma5-debuginfo-5.2.3-4.3.1.x86_64 libnuma1-debuginfo-2.0.11-2.18.x86_64 libpciaccess0-debuginfo-0.14-1.16.x86_64 libunwind-debuginfo-1.2.1-2.13.x86_64 libxml2-2-debuginfo-2.9.7-3.22.1.x86_64 libz1-debuginfo-1.2.11-3.12.1.x86_64
(gdb) bt
#0  0x00002aaab3306bb1 in mca_btl_sm_component_progress () from /users/hpp/ompi/install_test/lib/openmpi/mca_btl_sm.so
#1  0x00002aaaac27716c in opal_progress () from /users/hpp/ompi/install_test/lib/libopen-pal.so.0
#2  0x00002aaaab98a8a5 in ompi_request_default_wait () from /users/hpp/ompi/install_test/lib/libmpi.so.0
#3  0x00002aaaab9ec0da in ompi_coll_base_sendrecv_actual () from /users/hpp/ompi/install_test/lib/libmpi.so.0
#4  0x00002aaaab9ed142 in ompi_coll_base_allreduce_intra_recursivedoubling () from /users/hpp/ompi/install_test/lib/libmpi.so.0
#5  0x00002aaaab9edee1 in ompi_coll_base_allreduce_intra_ring () from /users/hpp/ompi/install_test/lib/libmpi.so.0
#6  0x00002aaaba696845 in ompi_coll_tuned_allreduce_intra_dec_fixed () from /users/hpp/ompi/install_test/lib/openmpi/mca_coll_tuned.so
#7  0x00002aaaab9a6fd8 in PMPI_Allreduce () from /users/hpp/ompi/install_test/lib/libmpi.so.0
#8  0x00002aaac0a23798 in mca_io_romio_dist_MPI_File_set_view () from /users/hpp/ompi/install_test/lib/openmpi/mca_io_romio332.so
#9  0x00002aaac0a1ca2f in mca_io_romio332_file_set_view () from /users/hpp/ompi/install_test/lib/openmpi/mca_io_romio332.so
#10 0x00002aaaab9b7dcb in PMPI_File_set_view () from /users/hpp/ompi/install_test/lib/libmpi.so.0
#11 0x00002aaaaadab07c in H5FD_mpio_read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#12 0x00002aaaaada71c2 in H5FD_read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#13 0x00002aaaaad95359 in H5F__accum_read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#14 0x00002aaaaad983e6 in H5F_block_read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#15 0x00002aaaaad790cc in H5D__mpio_select_read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#16 0x00002aaaaad75c77 in H5D__final_collective_io () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#17 0x00002aaaaad75e0e in H5D__inter_collective_io () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#18 0x00002aaaaad791d2 in H5D__contig_collective_read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#19 0x00002aaaaad73aad in H5D__read () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#20 0x00002aaaaad74ba4 in H5Dread () from /lustre1/hpp/hdf5_bug/src/hdf5-1.8.21/src/.libs/libhdf5.so.10
#21 0x000000000040f865 in dataset_readAll ()
#22 0x0000000000442d33 in PerformTests ()
#23 0x00000000004055fb in main ()

```

**Comment by ggouaillardet** [comment]
@rhc54 This is something I have to check.

Unlike other 3rd party packages:
 - ROMIO is patched for Open MPI (some changes should be pushed upstream, but other are pretty specific for ompi and could never make it upstream)
 - ROMIO does depends on the MPI layer, and I am not sure this is a scenario currently supported by `autogen.pl` and `configury` stuff.

**Comment by rhc54** [comment]
> ROMIO is patched for Open MPI (some changes should be pushed upstream, but other are pretty specific for ompi and could never make it upstream)

That sounds really bad - could you please identify those and perhaps why it was done? Maintaining OMPI-specific changes in a 3rd party package is downright something we should not be doing.

> ROMIO does depends on the MPI layer, and I am not sure this is a scenario currently supported by autogen.pl and configury stuff.

I suspect we can fix that readily enough - if it can work from within a component, no reason it can't work from the 3rd party area. Bigger issue is removing these OMPI customizations from the package.

**Comment by hppritcha** [comment]
I did more testing using the HDF5 make check in #6871 and generally found things not so good

- using 3.1.x branch, make check passes
- using 4.0.x branch, testphdf5 times out
- using 4.1.x branch, testphdf5 times out
- using master, testphdf5 times out
- using this PR, get the SIGBUS reported above

It doesn't appear that upgrading ROMIO is helping with the hdf5 make check test when using a lustre fs.

**Comment by ggouaillardet** [comment]
@hppritcha thanks for the tests!

I am unable to build romio on the lustre flavor I have access to ... but will be trying something else.

Meanwhile, can you build and test MPICH 3.3.2 on lustre?
I'd like to know if the issue is in MPICH or the way (correct) ROMIO is integrated into Open MPI.

**Comment by loveshack** [comment]
What's wrong with the current romio?  As I posted on the user list, I got it embedded and passing the hdf5 test, and also romio's except for syshints, which ompio fails too.

**Comment by rhc54** [comment]
Can you post your patch somewhere that we could look at it? It sounds like you've got something that works, so maybe we should just look at taking it or at least understanding the difference to what @ggouaillardet has done.

**Comment by hppritcha** [comment]
@ggouaillardet using mpich 3.3.2 the HDF5 make check runs successfully on lustre - at least for me.

**Review by hppritcha — APPROVED** [review]

**Comment by rhc54** [comment]
I'm puzzled - why would we approve this PR? We know that the correct ROMIO works and that this version doesn't. Seems to me we need to dig deeper into why we made changes to ROMIO and figure out how we get back to unchanged versions before committing this update.

**Comment by ggouaillardet** [comment]
Since the outcome of the tests are pointing to an issue with ROMIO integration (read upstream ROMIO is fine), I have to agree with @rhc54 so I moved this PR to a draft so it does not get merged prematurely.

**Comment by ggouaillardet** [comment]
@hppritcha could you please apply https://github.com/open-mpi/ompi/pull/8249/commits/dbfcd5788fa9bdc57993a4d6cfd72c7d969fb9af (stop using MPI-1 subroutines that have been removed) on top of MPICH 3.3.2 and see if the hdf5 still passes?

**Comment by loveshack** [comment]
It would be a huge patch.  If you accept contributions now, I'll put a
repo up when I'm off leave.

**Comment by rhc54** [comment]
> It would be a huge patch. If you accept contributions now, I'll put a repo up when I'm off leave.

All we require is a `Signed-off-by: name <email>` line in the commit message acknowledging it is contributed as open source and that you have the right to do so.

> , I'll put a repo up when I'm off leave

We'd appreciate it!

**Comment by loveshack** [comment]
I have pushed changes to the romio34b1 branch of
https://github.com/loveshack/ompi.  They're still under romio321.  (Why
isn't it just romio so that the component doesn't keep changing?)
Presumably that needs to be re-done if the commit messages are wrong.

That passes the test set on lustre, apart from syshints (which I haven't
tried to debug, but looks as if it's reporting junk buffer contents),
and possibly error; I'm not sure if error really has an error in the
error.  The tests need --enable-mpi1-compatibility to build, though.  I
tried to fix that quickly per the FAQ, but it broke the ones I changed,
and we probably need the option anyway.

**Comment by loveshack** [comment]
After trusting that you'd now accept external contributions, I find what I had working has been re-done (assuming it actually passes the tests), and I've wasted considerable time on this.  I obviously won't do any more work getting it into a state that might be OK for the mpich distribution.

**Comment by jsquyres** [comment]
@loveshack I think you may have misunderstood what happened.  We actually used your repo (heavily) to compare what had already been done on our side and see what the differences were.  Your repo is now unavailable, so I can't check for sure, but I didn't think it included all the extra OMPI-isms that @ggouaillardet carried forward in his...?  Additionally, we had to compare against multiple different versions of ROMIO (3.4b1 and 3.3.2) and had conversations with @roblatham00 about when the beta version would go final, etc.  Much happened behind the scenes, but your (now unavailable) repo was extremely helpful in paring down what needed to happen.

You'll certainly be cited in the final work.

**Comment by loveshack** [comment]
So I understand that I was encouraged to go away and produce something
in better shape (cleanly, from scratch) while others were doing "behind
the scenes" what was actually going to be used.

Obviously I checked history to try to make sense of it all.  I wanted to
eliminate OMPI kludges, whether or not that's impossible, before
suggesting changes for the mpich version.  I was looking at recent
changes to see if they were actually necessary after passing all the
tests I had without them.  That wasn't for credit, just trying for an
MPI that would at least pass basic tests (and not only for mpi-io).

**Comment by ggouaillardet** [comment]
ROMIO 3.3.2 does not pass the parallel `hdf5` tests, but ROMIO 3.4b1 does.

Closing this PR in favor of #8279.

**Pull request closed without merging**
