### PR TITLE
Fix output of XPMEM detection in configure summary

### PR DESCRIPTION
**Pull request by mkre**
Signed-off-by: Moritz Kreutzer <mokreutzer@gmail.com>

Refs open-mpi/ompi#5377

### CODE REVIEW

**Comment by rhc54** [comment]
ok to test

**Comment by hoopoepg** [comment]
@jsquyres there were issues on jenkins03 system (some troubles in fs sync). for now it should work. could you restart bots?

**Comment by hppritcha** [comment]
bot-mellanox-retest

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
(thanks @hoopoepg !)

**Comment by jsquyres** [comment]
@hppritcha @hjelmn Which release branches does this need to be cherry-picked to?  (I don't know when the XPMEM configure error crept in, so I don't know on which release branches it is needed)

**Pull request merged**
