### PR TITLE
Adjust TCP Keepalive and Errmgr message

### PR DESCRIPTION
**Pull request by jjhursey**
Cherry picking these two PRs as they are related:
 * https://github.com/open-mpi/ompi/pull/2991
 * https://github.com/open-mpi/ompi/pull/3004

### CODE REVIEW

**Comment by jjhursey** [comment]
Since this is a parameter change I think it's only appropriate to pull it into v2.x. I'm happy to file other PRs to the other release branches if folks want.

**Comment by jsquyres** [comment]
@hppritcha These 2 PRs are in v2.0.x, so they should be in v2.1.x as well.

**Comment by jjhursey** [comment]
@jsquyres I don't think these are in v2.0.x yet. Do you want me to make a PR over there for them?

**Comment by jsquyres** [comment]
@jjhursey Oh!  My bad -- I apparently only did this on master and did not PR to v2.0.x.  Mmph.

Yes, please file a PR for v2.0.x, if you wouldn't mind...

**Comment by jjhursey** [comment]
@jsquyres Done PR #3047

**Comment by hppritcha** [comment]
this needs to get into 2.1.x

**Pull request merged**
