### PR TITLE
Be more helpful when OPAL_PREFIX is wrong

### PR DESCRIPTION
**Pull request by rhc54**
If none of the provided search directories for plugins exists, then we really have a non-recoverable problem. As things stand, we fail with a completely unhelpful message from the first framework that tries to open components, finds nothing, and errors out because it needs at least one to work.

The use-case that tripped this was an incorrect setting of OPAL_PREFIX to point to a non-existent location due to a typo. It took significant debugging to find that it wasn't the framework that was the problem - it was the envar.

Try to detect that and provide a more useful error message.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Refs https://github.com/open-mpi/ompi/issues/3980

**Comment by rhc54** [comment]
I'm seeing weird random failures in the opal_fifo tests that can't have anything to do with this PR - does anyone have any ideas?

**Comment by rhc54** [comment]
bot:ompi:retest

**Comment by rhc54** [comment]
@bwbarrett I'm going to need some help here. I cannot make the opal_fifo tests fail on my machines, even copying the autogen/configure lines used here. Nothing in this PR relates to opal_fifo or touches anything to do with it. So I'm at a total loss as to what might be going on here.

**Comment by jjhursey** [comment]
I added a comment to the PMIx version of this:
  * https://github.com/pmix/pmix/pull/446#discussion_r131763877
It describes my testing of this PR. It is working now how I would expect.

One future feature request might be to clarify what happens if I have two directories in my `mca_base_component_path` both valid directories with components (let's say that they are non-overlapping/conflicting for the moment). For example, there is a system installed Open MPI (with headers) and a couple 'custom' components in my home directory. Are the union of the components in those two directories taken? Just those from the first directory? Just lost from the last directory?

**Comment by hjelmn** [comment]
Looks like the pull request checker is borked.

**Comment by rhc54** [comment]
bot:ompi:retest

**Comment by rhc54** [comment]
@jjhursey Based on what I see in the code, we work thru every directory in the search path, slurping up all components for the given framework. So it is the union of the directories. I'm not sure what happens if dlopen sees two components of the same name.

**Comment by rhc54** [comment]
Sigh - I give up. Now we are back to getting opal_fifo test errors when --no-ompi, --no-oshmem, or --no-orte is given to autogen.

**Comment by hjelmn** [comment]
I will try to reproduce the issue tomorrow. Failures in just about all the tests that call opal_init_util ().

**Comment by rhc54** [comment]
What the heck is this one?
```
08:39:12 make[3]: Leaving directory `/scrap/jenkins/jobs/gh-ompi-master-pr/workspace/test/dss'
08:39:12 make[2]: Leaving directory `/scrap/jenkins/jobs/gh-ompi-master-pr/workspace/test/dss'
08:39:12 Making check in symbol_name
08:39:12 make[2]: Entering directory `/scrap/jenkins/jobs/gh-ompi-master-pr/workspace/test/symbol_name'
08:39:12 make  check-TESTS
08:39:12 make[3]: Entering directory `/scrap/jenkins/jobs/gh-ompi-master-pr/workspace/test/symbol_name'
08:39:12 Test expects env var MYBASE set to base dir
08:39:12 (where ompi/ opal/ orte/ test/ etc live)
08:39:12 And optionally OMPI_LIBMPI_NAME should be set
08:39:12 if MPI is configured with some name other than
08:39:12 "mpi" for that.
08:39:12 FAIL: nmcheck_prefix
08:39:12 ========================================================
08:39:12 1 of 1 test failed
08:39:12 Please report to http://www.open-mpi.org/community/help/
```

**Comment by jjhursey** [comment]
IBM added a feature to rename `libmpi*` to `libFOO` if you pass `--with-libmpi-name=FOO`. That's probably what it's encountering.
IBM uses this in our MTT testing, but not our CI testing (though we probably should).

**Comment by rhc54** [comment]
Is there some way to remove this for now so we can get past it? Or update the OMPI internal tests so it passes?

**Comment by rhc54** [comment]
Just wondering: since this PR doesn't touch that functionality, how did this get thru CI before?

**Comment by jjhursey** [comment]
Humm not sure how that would have gotten through CI (that option has been in there for quite a while now). Let me see if I can reproduce locally.

**Comment by rhc54** [comment]
FWIW: I can reproduce on my machine as well. I'm wondering is someone changed the tests as opposed to the option itself? I thought I saw something go thru just this morning about it...

**Comment by rhc54** [comment]
Bingo! #4036 is what broke things.

**Comment by rhc54** [comment]
or at least, it touched this test - the PR saids it passed CI...?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/bc4da5d8ac768cb48d19dd61f38764ff

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3d7eed5bfc477b62a7bdcb4c628ee1f2

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8b9489e4997f2958a84e0f66ce50401d

**Comment by jjhursey** [comment]
Hard as I try I cannot reproduce the symbol test issue. I've tried with the configure parameters Ralph sent me offline, and the ones from Mellanox CI.

Maybe there is an environment variable conflict for `MYBASE` which is why the error is being generated. @markalle Do you have any ideas on why it might fail like [this](https://github.com/open-mpi/ompi/pull/4028#issuecomment-321000281)?

**Comment by rhc54** [comment]
interesting - and I cannot get it to pass on my machines! I don't have any envar like MYBASE set. Yet it consistently fails for me with that message.

**Comment by rhc54** [comment]
Tried configuring with nothing other than a prefix, but same problem:
```
make  check-TESTS
make[1]: Entering directory `/home/common/openmpi/ompi/test/symbol_name'
make[2]: Entering directory `/home/common/openmpi/ompi'
make[2]: Leaving directory `/home/common/openmpi/ompi'
make[2]: Entering directory `/home/common/openmpi/ompi'
make[2]: Leaving directory `/home/common/openmpi/ompi'
Test expects env var MYBASE set to base dir
(where ompi/ opal/ orte/ test/ etc live)
And optionally OMPI_LIBMPI_NAME should be set
if MPI is configured with some name other than
"mpi" for that.
FAIL: nmcheck_prefix
========================================================
1 of 1 test failed
Please report to http://www.open-mpi.org/community/help/
========================================================
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/home/common/openmpi/ompi/test/symbol_name'
make: *** [check-am] Error 2
```

**Comment by rhc54** [comment]
Aha - here is what is needed to make this test pass:
```
$ export MYBASE=/home/common/openmpi/ompi
$ make check
make[1]: Entering directory `/home/common/openmpi/ompi'
make[1]: Leaving directory `/home/common/openmpi/ompi'
make[1]: Entering directory `/home/common/openmpi/ompi'
make[1]: Leaving directory `/home/common/openmpi/ompi'
make  check-TESTS
make[1]: Entering directory `/home/common/openmpi/ompi/test/symbol_name'
make[2]: Entering directory `/home/common/openmpi/ompi'
make[2]: Leaving directory `/home/common/openmpi/ompi'
make[2]: Entering directory `/home/common/openmpi/ompi'
make[2]: Leaving directory `/home/common/openmpi/ompi'
NOTE: found static /home/common/openmpi/ompi/ompi/mca/bml/.libs/libmca_bml.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/coll/.libs/libmca_coll.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/crcp/.libs/libmca_crcp.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/fbtl/.libs/libmca_fbtl.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/fcoll/.libs/libmca_fcoll.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/fs/.libs/libmca_fs.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/io/.libs/libmca_io.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/mtl/.libs/libmca_mtl.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/op/.libs/libmca_op.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/osc/.libs/libmca_osc.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/pml/v/.libs/libmca_pml_v.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/pml/.libs/libmca_pml.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/rte/orte/.libs/libmca_rte_orte.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/rte/.libs/libmca_rte.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/sharedfp/.libs/libmca_sharedfp.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/topo/.libs/libmca_topo.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/vprotocol/.libs/libmca_vprotocol.a
NOTE: found static /home/common/openmpi/ompi/ompi/mca/hook/.libs/libmca_hook.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/allocator/.libs/libmca_allocator.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/backtrace/execinfo/.libs/libmca_backtrace_execinfo.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/backtrace/.libs/libmca_backtrace.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/base/.libs/libmca_base.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/btl/.libs/libmca_btl.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/compress/.libs/libmca_compress.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/crs/.libs/libmca_crs.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/dl/dlopen/.libs/libmca_dl_dlopen.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/dl/.libs/libmca_dl.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/event/libevent2022/.libs/libmca_event_libevent2022.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/event/.libs/libmca_event.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/hwloc/hwloc2a/.libs/libmca_hwloc_hwloc2a.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/hwloc/.libs/libmca_hwloc.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/if/linux_ipv6/.libs/libmca_if_linux_ipv6.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/if/posix_ipv4/.libs/libmca_if_posix_ipv4.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/if/.libs/libmca_if.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/installdirs/config/.libs/libmca_installdirs_config.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/installdirs/env/.libs/libmca_installdirs_env.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/installdirs/.libs/libmca_installdirs.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/memchecker/.libs/libmca_memchecker.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/memcpy/.libs/libmca_memcpy.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/memory/patcher/.libs/libmca_memory_patcher.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/memory/.libs/libmca_memory.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/mpool/.libs/libmca_mpool.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/patcher/.libs/libmca_patcher.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/.libs/libmca_pmix.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/gds/.libs/libmca_gds.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pdl/pdlopen/.libs/libmca_pdl_pdlopen.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pdl/.libs/libmca_pdl.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pif/linux_ipv6/.libs/libmca_pif_linux_ipv6.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pif/posix_ipv4/.libs/libmca_pif_posix_ipv4.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pif/.libs/libmca_pif.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pinstalldirs/config/.libs/libmca_pinstalldirs_config.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pinstalldirs/env/.libs/libmca_pinstalldirs_env.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pinstalldirs/.libs/libmca_pinstalldirs.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pnet/.libs/libmca_pnet.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/psec/.libs/libmca_psec.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/.libs/libmca_bfrops.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/preg/.libs/libmca_preg.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/psensor/.libs/libmca_psensor.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/pshmem/.libs/libmca_pshmem.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pmix/pmix2x/pmix/src/mca/ptl/.libs/libmca_ptl.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/pstat/.libs/libmca_pstat.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/rcache/.libs/libmca_rcache.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/reachable/.libs/libmca_reachable.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/shmem/.libs/libmca_shmem.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/timer/linux/.libs/libmca_timer_linux.a
NOTE: found static /home/common/openmpi/ompi/opal/mca/timer/.libs/libmca_timer.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/dfs/.libs/libmca_dfs.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/errmgr/.libs/libmca_errmgr.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/ess/.libs/libmca_ess.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/filem/.libs/libmca_filem.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/grpcomm/.libs/libmca_grpcomm.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/iof/.libs/libmca_iof.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/notifier/.libs/libmca_notifier.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/odls/.libs/libmca_odls.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/oob/.libs/libmca_oob.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/plm/.libs/libmca_plm.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/ras/.libs/libmca_ras.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/rmaps/.libs/libmca_rmaps.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/rml/.libs/libmca_rml.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/routed/.libs/libmca_routed.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/rtc/.libs/libmca_rtc.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/schizo/.libs/libmca_schizo.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/snapc/.libs/libmca_snapc.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/sstore/.libs/libmca_sstore.a
NOTE: found static /home/common/openmpi/ompi/orte/mca/state/.libs/libmca_state.a
NOTE: found static /home/common/openmpi/ompi/oshmem/mca/atomic/.libs/libmca_atomic.a
NOTE: found static /home/common/openmpi/ompi/oshmem/mca/memheap/.libs/libmca_memheap.a
NOTE: found static /home/common/openmpi/ompi/oshmem/mca/scoll/.libs/libmca_scoll.a
NOTE: found static /home/common/openmpi/ompi/oshmem/mca/spml/.libs/libmca_spml.a
NOTE: found static /home/common/openmpi/ompi/oshmem/mca/sshmem/.libs/libmca_sshmem.a
Checking for bad symbol names in the main libs:
checking /home/common/openmpi/ompi/ompi/.libs/libmpi.so
checking /home/common/openmpi/ompi/ompi/mpi/fortran/mpif-h/.libs/libmpi_mpifh.so
checking /home/common/openmpi/ompi/orte/.libs/libopen-rte.so
checking /home/common/openmpi/ompi/opal/.libs/libopen-pal.so
PASS: nmcheck_prefix
=============
1 test passed
=============
make[1]: Leaving directory `/home/common/openmpi/ompi/test/symbol_name'
01:30:12  {topic/mca} /home/common/openmpi/ompi/test/symbol_name$ 
```

**Comment by rhc54** [comment]
@jjhursey Do you have MYBASE set somewhere? I'm wondering if this perl script in the directory is somehow trying to set it, but is using a specific shell syntax that isn't correct for everyone? I'm using bashrc, which I think is what the test environment uses.

**Comment by rhc54** [comment]
Here it is, right in the beginning of the test:
```
sub main {
    if (!$ENV{MYBASE}) {
        print "Test expects env var MYBASE set to base dir\n";
        print "(where ompi/ opal/ orte/ test/ etc live)\n";
        print "And optionally OMPI_LIBMPI_NAME should be set\n";
        print "if MPI is configured with some name other than\n";
        print "\"mpi\" for that.\n";
        exit -1;
    }

# env var MYBASE should be the top dir where ompi/ opal/ orte/ test/ etc live.
```
So this test cannot run unless MYBASE is set.

**Comment by jjhursey** [comment]
I don't have it set in my environment (I'm using bash as well). The `Makefile.am` in that directory should be setting it appropriately:
```
AM_TESTS_ENVIRONMENT = MYBASE='$(top_builddir)'; OMPI_LIBMPI_NAME=@OMPI_LIBMPI_NAME@; export MYBASE OMPI_LIBMPI_NAME;
```

**Comment by rhc54** [comment]
digging...digging...well, the automake docs say it is okay to use ```AM_TESTS_ENVIRONMENT``` by the developer, so that doesn't seem to be the issue. However, for whatever reason, it isn't setting the environment on my machine, nor on the test machines.

**Comment by jjhursey** [comment]
Curious. What version of automake are you using? I'm at `1.15`.

From [here](https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html) I would think that `AM_TESTS_ENVIRONMENT` is what we want since we are the system and not the user (which is supposed to use `TESTS_ENVIRONMENT`). But if you are using the serial executor then there is a note that `AM_TESTS_ENVIRONMENT` will not work...

**Comment by rhc54** [comment]
What I have done is push a change to that script so it doesn't error out with a failed test if the envar isn't set. It just skips the test. This seems like a better test to me as the feature it is testing is purely optional.

I'm using 1.15 as well - I believe the Jenkins tester is also.

**Comment by jjhursey** [comment]
@rhc54 I think that's fair. I'd like someone (*cough* @markalle *cough*) to see if they can reproduce separate from this PR (as this is a digression on the PR) and sort through the issue. What I don't want is to somehow have it that the test is never run and no one notices.

**Comment by rhc54** [comment]
Okay, we are back to dlopen_test failing on various platforms. @hjelmn You have any thoughts as to why? I simply cannot replicate anywhere.

**Comment by rhc54** [comment]
not worth my time

**Pull request closed without merging**
