### PR TITLE
docs: conditionally install wrapper compiler man pages

### PR DESCRIPTION
**Pull request by jsquyres**
Only install the C++, Fortran, and/or Java wrapper compiler pages if configure determines that we're actually building bindings for the corresponding language.

Ensure to *always* include all the wrapper compiler pages in the tarball, though.

Thanks to Orion Poplawski for identifying the problem and suggesting an initial fix.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

FYI @opoplawski: This PR should replace #10991.

### CODE REVIEW

**Review by bwbarrett — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
Hmm.  Got a legit fail with `./autogen.pl --no-ompi`.  Need to think about what the Right Thing to do is here...

**Comment by jsquyres** [comment]
> Hmm. Got a legit CI fail with `./autogen.pl --no-ompi`. Need to think about what the Right Thing to do is here...

@bwbarrett You and I should probably have a conversation about what we think `--no-ompi` and/or `--no-oshmem` should mean for installing the docs.

**Comment by jsquyres** [comment]
Hey @bosilca -- Brian and I were chatting, and we were wondering if we could kill the `--no-ompi` and `--no-oshmem` CLI options to `autogen.pl` to solve this problem.  Do you need them for anything these days?

More detail: the problem identified by the CI test on this PR goes away if we kill the `--no-ompi` + `--no-oshmem` CLI options.  Now that ORTE is gone, we can't think of a good reason why either of these switches are valuable any more -- unless you're using them somehow...?

**Comment by bosilca** [comment]
They were useful to compile libopen-pal by itself, without the rest. We moved away from this approach, we are now importing the code (we all agree it is a terrible approach and a nightmare to maintain, but less terrible than having to precompile your own libopal).

**Comment by jsquyres** [comment]
@bosilca confirmed to me in Slack that they don't use `--no-ompi` or `--no-oshem` any more.  I'll add a commit to this PR to remove those options.

**Review by bwbarrett — APPROVED** [review]

**Pull request merged**
