### PR TITLE
v4.0.x: fortran/use-mpi-f08: revamp mpi_f08 constants

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres can you please review this?

I incidentally noted some stuff is missing. For example `type(MPI_Op) :: MPI_NO_OP` is defined in the `master` branch but not in the `v4.0.x` branch. Is this something intentional ?

**Comment by jsquyres** [comment]
Have you tested that this doesn't break ABI w.r.t. all the constants changing types?

I can't think of a reason why `MPI_NO_OP` wouldn't be here on v4.0.x.  I wonder if that's a prior mistaken conflict resolution on a cherry pick to v4.0.x, or something along those lines...?

**Comment by kawashima-fj** [comment]
@ggouaillardet I added `MPI_NO_OP` of `mpi_f08` in #6174 but probablly forgot to cherry-pick it to release branches. Can you checy-pick (or manually add without an additional commit) it to this PR?

**Comment by hppritcha** [comment]
Why do we want this in v4.0.x?  Aside from the discussion about missing ```MPI_NO_OP```, is it just to get the f08 bindings to work with the old llvm fortran front end?  It does look like #6174 should be pulled in however.

**Comment by jsquyres** [comment]
@hppritcha This is in reference to #7091 (i.e., bug fix for the ARM complier).

**Comment by hppritcha** [comment]
@shamisp what's allinea's opinion of this flang problem?

**Comment by jsquyres** [comment]
@ggouaillardet We talked about this yesterday on the RM call.  Seems like it's two issues:

1. MPI_NO_OP: That should definitely come over to v4.0.x.
1. The flang fixes: Do we know if this is desired and/or necessary on the v4.0.x branch?  I.e., we know it's a problem for flang, but does anyone care (given that -- at least as we understand it -- flang is old / may not be used much longer)?
1. Do we know for sure that the changes don't impact ABI?  I.e., did you test with an app compiled against v4.0.x and then try to run it with this PR?  And what happens if we have some objects compiled with v4.0.x and some objects compiled with this PR -- does it all work properly (i.e., can an MPI_COMM_WORLD from one of the old v4.0.0 objects be passed to an object compiled with this PR)?

**Comment by ggouaillardet** [comment]
1. yes, and I also backported #5811 (it seems it has been forgotten a while ago)

2. I have some hard time undertanding this argument.
 - `armflang` and maybe PGI are `flang` based
 - `f18` is still relying on `pgf90` to work

 so yes, the plan is to move away from `flang` and use `f18` instead, but we are not quite there, so I'd rather revamp Open MPI (assuming it is impact free) than waiting an unknown amount of time for `flang`, ARM and PGI to fix their compilers.

3. the plan was to be ABI backward compatible, but I will run some more tests from now.

**Comment by ggouaillardet** [comment]
I made some tests and found no ABI issues.

**Comment by jsquyres** [comment]
Ok, good to know.  The discussion on the Monday+Tuesday Webexes was that `flang` was no longer relevant; if that's inaccurate, then it does change the equation.

@shamisp Can someone from ARM please chime in here?

**Comment by ggouaillardet** [comment]
I discussed flang vs f18 at SC, and I can confirm f18 is not quite yet ready to replace flang (f18 currently requires `pgf90` to work). Also, armflang and pgf90 are currently based on flang, and we can expect it will take some extra time before they rebase on top of f18. Last but not least, we have no guarantee that f18 will behave differently from flang on that matter.
My best bet is to move forward is merge this PR.
I can also PR vs the `v3.1.x` release branch if needed.

**Comment by gpaulsen** [comment]
@hppritcha I'm ready to merge this to v4.0.x as @ggouaillardet has tested this for ABI compatibility issues, and found none.

**Pull request merged**
