### PR TITLE
MTL/PSM2: fix check for PSM2_LIB_REFCOUNT_CAP

### PR DESCRIPTION
**Pull request by hppritcha**
to honor non-default installs of psm2.h

related to #8651

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>

### CODE REVIEW

**Comment by mwheinz** [comment]
Howard, I’m out of the office tomorrow; I’m going to add Brendan as a reviewer in case this is needed for 4.1.1.

**Comment by gpaulsen** [comment]
Please cherry-pick to v5.0.x once this goes in.

**Review by mwheinz — APPROVED** [review]
Looks good.

**Comment by awlauria** [comment]
This was cherry-picked to v5.0.x here:
https://github.com/open-mpi/ompi/pull/8714

**Pull request merged**
