### PR TITLE
Always include the stddef.h header.

### LINKED ISSUE #8583: Build errors due to ptrdiff_t and missing/misplaced stddef.h
## Background information
I encounter `unknown type name ‘ptrdiff_t’` errors due to missing/misplaced `#include <stddef.h>` in the developer build from a git checkout

### What version of Open MPI are you using?
master / 76eaffa6b8017999b0d014714ee29a37ca1d60b8

git submodule status 
+517d954a4a3929fe27e69f35cbe00a419c143dbf 3rd-party/openpmix (v1.1.3-2836-g517d954a)
+67addf25843e7765d6aee19b51a3165d08a9eace 3rd-party/prrte (dev-30952-g67addf2584)

### Please describe the system on which you are running
* Operating system/version: Arch Linux
* Computer hardware: AMD/x86_64
* autotolls:  autoconf 2.71,  libtool 2.4.6.42,  automake 1.16.3
* gcc 10.2.0 and clang 11.1.0

## Details of the problem

>   CC       libompi_dbg_msgq_la-ompi_msgq_dll.lo
> In file included from ompi/ompi/ompi/include/ompi_config.h:29,
>                  from ompi/ompi/ompi/debuggers/ompi_msgq_dll.c:72:
> ../../opal/include/opal_config.h:1317:28: error: unknown type name ‘ptrdiff_t’
>  1317 | #define OMPI_MPI_AINT_TYPE ptrdiff_t
>       |                            ^~~~~~~~~
> ../../ompi/include/mpi.h:402:9: note: in expansion of macro ‘OMPI_MPI_AINT_TYPE’
>   402 | typedef OMPI_MPI_AINT_TYPE MPI_Aint;
>       |         ^~~~~~~~~~~~~~~~~~

The `#include <stddef.h>` required for `ptrdiff_t` is missing here.

Inserting `stddef.h` by hand to the top of `ompi_config.h` triggers the related error in `mpi.h`:

>   CC       mpi-io/close.lo
> In file included from ompi/ompi/ompi/mca/io/romio321/romio/adio/include/adio.h:72,
>                  from ompi/ompi/ompi/mca/io/romio321/romio/mpi-io/mpioimpl.h:17,
>                  from ompi/ompi/ompi/mca/io/romio321/romio/mpi-io/close.c:8:
> ./../../../../../ompi/include/mpi.h:157:28: error: unknown type name ‘ptrdiff_t’
>   157 | #define OMPI_MPI_AINT_TYPE ptrdiff_t
>       |                            ^~~~~~~~~
> ./../../../../../ompi/include/mpi.h:402:9: note: in expansion of macro ‘OMPI_MPI_AINT_TYPE’
>   402 | typedef OMPI_MPI_AINT_TYPE MPI_Aint;
>       |         ^~~~~~~~~~~~~~~~~~
> In file included from ompi/ompi/ompi/mca/io/romio321/romio/adio/include/adio.h:72,
>                  from ompi/ompi/ompi/mca/io/romio321/romio/mpi-io/mpioimpl.h:17,
>                  from ompi/ompi/ompi/mca/io/romio321/romio/mpi-io/close.c:8:
> ./../../../../../ompi/include/mpi.h:436:5: error: unknown type name ‘size_t’
>   436 |     size_t _ucount;
>       |     ^~~~~~

In `mpi.h.in` the required `stddef.h` is included too late and guarded by some OPAL_STDC_HEADERS:
> /* type to use for ptrdiff_t, if it does not exist, set to ptrdiff_t if it does exist */
> #undef ptrdiff_t
> ..
> /* include for ptrdiff_t */
> #ifdef OPAL_STDC_HEADERS
> #include <stddef.h>
> #endif

Not clear how to fix this to me as `OMPI_MPI_AINT_TYPE` is set via `AC_DEFINE_UNQUOTED` and there are several *h.in files as well as a `AH_TOP` header in `configure.ac`

### PR DESCRIPTION
**Pull request by bosilca**
Fixes #8583 

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
I question whether we really need this macro anymore, if it's declared obsolete by autoconf, why do we still need it?

Not a question we need to worry about now, but it might be something to consider for ompi 6.0.

I guess we can throw that on the heap with 32bit support.

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by rhc54** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
@bosilca can you cherry-pick back to v5.0.x?

**Pull request merged**
