### PR TITLE
debug fix for DVM early quit

### LINKED ISSUE #2987: dvm: daemons quit after exceed available slots
The DVM is not usable after exceeding available resources (i.e., non-oversubscribe case).  It seems like the next invocation runs into previous invocation's error and things shutdown. 

Brief summary with simplified setup (localhost w/ 2 slots) :
 - Run command that exceeds resources (e.g., `mpirun --hnp file:dvmuri -np 3 hello` but only 2 slots available) we get error 
 - Then run a valid command (e.g., `-np 2`) and the DVM calls `orte_quit()` b/c it thinks nobody is alive (e.g., `orte/mca/routed/base/routed_base_fns.c:281`).
- This early termination of DVM is why the frontend command fails (orterun) as it loses lifeline to HNP.

Steps for reproducing on a single host (few debug prints prefixed by DBG):
```
$ cat hosts-tiny 
sal9000 slots=2
```
```
  # DVM case
$ orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
$ ps auwx | grep orte-dvm | grep -v grep
3t4      14684  0.2  0.2 776176  4436 ?        Ssl  11:04   0:00 orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
$ orterun --hnp file:dvmuri -np 2 ./hello_c
[ORTE] Task: 0 is launched! (Job ID: [6429,1])
[sal9000:14787] Hello, world, I am 0 of 2
[sal9000:14788] Hello, world, I am 1 of 2
[sal9000:14787] (rank-0) Used Version: Open MPI v3.0.0a1, package: Open MPI 3t4@sal9000 Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3722-g578d881, Unreleased developer copy
[ORTE] Task: 0 returned: 0 (Job ID: [6429,1])
$ echo $?
0
$ ps auwx | grep orte-dvm | grep -v grep
3t4      14684  0.1  0.2 915676  5564 ?        Ssl  11:04   0:00 orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
 #
 # NOTE: DVM launched but exceeded resources
 #
$ orterun --hnp file:dvmuri -np 3 ./hello_c
$ echo $?
69
 #
 # NOTE: DVM process still running
 # 
$ ps auwx | grep orte-dvm | grep -v grep
3t4      14684  0.1  0.2 915676  5596 ?        Ssl  11:04   0:00 orte-dvm --hostfile hosts-tiny --report-uri dvmuri --daemonize
  #
  # NOTE: Run a valid '-np 2' case, which triggers early orte_quit() for DVM
  #
$ orterun --hnp file:dvmuri -np 2 ./hello_c
$ echo $?
0
$
```
```
  #
  # Normal case w/o DVM (limiting to 2 slots so '-np 3' exceeds resources)
  # To show that we fail as expected at '-np 3'
  #
$ mpirun --hostfile hosts-tiny -np 2 ./hello_c
[sal9000:14047] Hello, world, I am 0 of 2
[sal9000:14048] Hello, world, I am 1 of 2
[sal9000:14047] (rank-0) Used Version: Open MPI v3.0.0a1, package: Open MPI 3t4@sal9000 Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3722-g578d881, Unreleased developer copy
$ echo $?
0
$ mpirun --hostfile hosts-tiny -np 3 ./hello_c
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 3 slots
that were requested by the application:
  ./hello_c
.
Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
[sal9000:14090] DBG: MAP_FAILED rc=-43
[sal9000:14090] DBG: NOBODY KNOWN ALIVE SO WE DIE!
$ echo $?
1
$ mpirun --hostfile hosts-tiny -np 2 ./hello_c
[sal9000:14147] Hello, world, I am 0 of 2
[sal9000:14148] Hello, world, I am 1 of 2
[sal9000:14147] (rank-0) Used Version: Open MPI v3.0.0a1, package: Open MPI 3t4@sal9000 Distribution, ident: 3.0.0a1, repo rev: v2.x-dev-3722-g578d881, Unreleased developer copy
$ echo $?
0
```

Testing environment:
 - OMPI master at 578d8819cffaa5aafe721c5bdaaef1c57f3e5b68
 - Build line:
     ```
      ./configure \
          --enable-orterun-prefix-by-default \
          --enable-debug \
         --prefix=/nfsscratch/tjn/local-ompi-dvmtest \
     && make && make install
     ```
 - Versions:
    ```
    autoconf: autoconf (GNU Autoconf) 2.69
    automake: automake (GNU automake) 1.14.1
    m4: m4 (GNU M4) 1.4.17
    libtool: libtool (GNU libtool) 2.4.2
    gcc: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
    ```

### PR DESCRIPTION
**Pull request by naughtont3**
Fixes #2987

### CODE REVIEW

**Comment by rhc54** [comment]
Couple of things. First, you need to add a "signed-off-by" line to your commits or else we cannot accept them. Second, while this fixes the immediate error, we'll just hit more of them. What we really need to do is detect if the error is happening during DVM launch - in that case, we do need to exit. Otherwise, we just want to notify the job submitter of the error and then continue along.

I'll try to give you a patch this weekend. I apologize for the delay - just a little buried right now.

**Comment by rhc54** [comment]
@naughtont3 I filed a PR against your branch that contains some changes that I _think_ will resolve the problem. You were actually much closer than I had originally realized - your fix was okay, but needed to apply to all states that are not associated with the DVM job itself.

See if that PR helps solve the problem, and add your signed-off-by line so we can commit what you did. Thanks for digging into this!

**Comment by jsquyres** [comment]
@naughtont3 You might want to rebase / squash some of these commits (e.g., squash the merge commit), and you might also want to remove the "WIP" from your early commit once it is ready.  I.e., we don't want a commit hitting master that is still marked as "WIP".

Ping me offline if you need some help with git rebasing / squashing / etc.

**Comment by naughtont3** [comment]
@rhc54 Hi Ralph, I worked through edits with Jeff to cleanup the PR.  Things passed my local test.  If you're good with changes, I believe this is ready to be merged.  Thanks!

**Pull request merged**
