### PR TITLE
fortran: add missing MPI_xxx_DUP_FN bindings

### PR DESCRIPTION
**Pull request by ggouaillardet**
- MPI_COMM_DUP_FN
- MPI_TYPE_DUP_FN
- MPI_WIN_DUP_FN

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres can you have a look at this ?
f08 bindings were added in #623 but nothing for mpifh nor usempi.
i cannot remember whether we had a good reason not to add them...

**Comment by jsquyres** [comment]
Are the declarations in `mpif-h/prototypes_mpi.h` and the definitions in `base/attr_fn_f.c` insufficient?

**Comment by ggouaillardet** [comment]
@jsquyres it is enough for ```mpif-h``` but not for ```use-mpi-tkr``` since this ```mpif-h/prototypes_mpi.h``` is not used when building ```mpi.mod```
i amended the commit message to make this crystal clear

**Comment by jsquyres** [comment]
Ok.  Looks like you're right.

Can you also add some MTT tests to make sure we test for DUP_FN in the mpi and mpi_f08 modules?

**Pull request merged**
