### PR TITLE
libevent/external: Add opal_event_include to this component

### PR DESCRIPTION
**Pull request by jjhursey**
* Adds a parameter to adjust the method used by libevent.
   - Matches that of the libevent2022 component.

Refs PR #2807

### CODE REVIEW

**Comment by gpaulsen** [comment]
:bot:retest

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/e41aa29bd81c240bf84642dfdf585137

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/267138989ce0dd4b6d227ebc167c4d1b

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/983527c8d1518ccc31192b5db72c74e2

**Comment by gpaulsen** [comment]
:bot:retest

**Pull request merged**
