### PR TITLE
opal/atomics: Add acquire semantics back for spinlocks

### PR DESCRIPTION
**Pull request by nysal**
This was introduced in commit 9d0b3fe9

Signed-off-by: Nysal Jan K.A <jnysal@in.ibm.com>

### CODE REVIEW

**Comment by jjhursey** [comment]
@nysal do we need this in the 4.x series?

**Comment by nysal** [comment]
Yes, I've opened https://github.com/open-mpi/ompi/pull/6502

**Comment by gpaulsen** [comment]
@nysal Can you please confirm if these are needed on v3.0.x or v3.1.x?

**Comment by nysal** [comment]
@gpaulsen v3.0.x and v3.1.x don't need this fix

**Comment by gpaulsen** [comment]
I confirmed with @nysal that this is a correctness fix.

**Pull request merged**
