### PR TITLE
add a --disable-io-ompio option

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
this can be merged __after__ #2018

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/72bdc8f390f2f98718ecc5153166804b

**Comment by ggouaillardet** [comment]
there is obviously something wrong when ```--disable-io-ompio``` is not used
i will investigate this later

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/63aba401e927726e6694948ae56f9757

**Comment by ggouaillardet** [comment]
this PR has been rebased on top of the latest #2018 and updated

**Comment by jsquyres** [comment]
@ggouaillardet:

* Is this still a WIP / DNM?  (that label is still on here)
* Do you need to rebase on top of master head to effectively remove the first commit on this PR?
* You might want to put "Closes #1934" in here somewhere since this PR will fix that issue.

Also, since this is an enhancement, it needs to go to v2.1.0.  I updated the milestone.

**Comment by ggouaillardet** [comment]
Will update tomorrow

Since the first commit has been merged, merging the request should be fine.
That could be a github bug, since the first commit should have been removed from the PR

**Comment by ggouaillardet** [comment]
@jsquyres we should be good now
i confirm github does not remove commits that have been merged from a PR

**Comment by jjhursey** [comment]
Thanks!

**Pull request merged**
