### PR TITLE
Remove build time sym links

### PR DESCRIPTION
**Pull request by jsquyres**
One reason that we make compile-time sym links is because waaaaay back in olden days, SVN couldn't track sym links.  So we made sym links at compile time and avoided the problem.

Per @siegmargross' usage, however, perhaps we should not make compile-time sym links any more.  Instead, just:

* git commit sym links to one directory back
* remove the compile-time logic to make sym links
* update .gitignore

The "make dist" tarballs will actually contain *copies* of files (not sym links), but that's ok -- the sym link is actually useful to *developers*, not *end users*.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/38/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/130/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 812 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//620/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/620/

**Comment by mellanox-github** [comment]
* Coverity found 812 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//623/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/623/

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/40/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/133/
Test PASSed.

**Comment by jsquyres** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/43/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/136/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 812 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//625/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/625/

**Comment by hppritcha** [comment]
not sure why the LANL pull request builder's status didn't show up. Trying again.
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/137/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/44/
Test PASSed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/138/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/45/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 812 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//626/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/626/

**Comment by jsquyres** [comment]
I talked this over with @goodell -- it doesn't seem like this PR has any real positive value.

Unless someone has a strong reason, I'm likely to throw this PR / branch away.

**Comment by hppritcha** [comment]
has small positive value right now because it seems to bring out some issue with jenkins and/or github and or something. One more time with this.

bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/46/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/139/
Test PASSed.

**Pull request closed without merging**
