### PR TITLE
dist: Prep for 3.0.6

### PR DESCRIPTION
**Pull request by bwbarrett**
3.0.5 has shipped, on to 3.0.6

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 @yosefe Can someone please investigate the Mellanox Jenkins failure?  This looks like a false failure.

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
@jsquyres it passes now. SM was down.

**Comment by jsquyres** [comment]
@yosefe Thanks!

**Pull request merged**
