### PR TITLE
Several fixes related to session directories:

### PR DESCRIPTION
**Pull request by artpol84**
* enable OMPI to retrieve paths from RM through PMIx
* cleanups related to tempdirs.

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54 This is a draft of what we were talking about on PMIx call. I'm still verifying the code but the conception is clear. Could you take a look and see if you are OK with this.

I will also add the PMIx keys to indicate that RM has created directories and that it will clean them up for OMPI as we discussed. I will implement this as a separate commit.

**Comment by artpol84** [comment]
The keys are added but I need to test them with SLURM.

**Comment by artpol84** [comment]
@rhc54 This works well for me now! Please have a look.

**Comment by rhc54** [comment]
As per today's PMIx telecon, this looks fine. Just replace your ```TODO``` comments with a note that we decided to let MCA params override the RM directive and we should be good.

Thanks!

👍

**Comment by jladd-mlnx** [comment]
#2072 Has a dependency.

**Pull request merged**
