### PR TITLE
Change how cm's priority is calculated

### PR DESCRIPTION
**Pull request by hjelmn**
@bosilca Please comment. This is a companion to or replacement for #1039.

### CODE REVIEW

**Comment by bosilca** [comment]
Looks good. :+1:

**Comment by yburette** [comment]
@hjelmn With this priority scheme, one needs to specify which PML to use in order to be able to use the OFI MTL. Is there a way around this?

`--mca mtl ofi --mca mtl_ofi_provider_include "psm"` doesn't work; still selects ob1
`--mca mtl ofi --mca mtl_ofi_provider_include "psm" --mca pml cm` works

**Comment by hjelmn** [comment]
I didn't adjust ofi's priority. I didn't think it was considered ready for prime time. You can set using -mca mtl_ofi_priority 100 to force it to run. Should we increase the priority?

**Comment by yburette** [comment]
I don't think we need to increase the priority yet.

I was just hoping there would be a way to automagically select cm when an MTL is specified on the command line :-)

**Comment by hjelmn** [comment]
You need to still force cm (or bump ofi's priority) because it shouldn't be selected before ob1 in production. Right now the component initialization code can not tell the difference between only one component being available and the user selecting a single component.

**Comment by hjelmn** [comment]
I should not it worked before because someone added ofi as one of the components that bumped cm's priority to 30.

**Comment by yburette** [comment]
So if I understand well, we should increase OFI MTL's priority to 30 in order to have what we had before the change, right?

**Comment by hjelmn** [comment]
Sort of. We need to bump psm to 31 first to keep it ahead of ofi. I left ofi's relative priority alone here (10).

**Comment by bosilca** [comment]
My understanding of the code is that the CM and PML will now inherit the priorities of their underlying modules (the CM the max of all available MTL, and OB1 the max of all available BTL), or is getting it's own priority form the corresponding MCA parameter. Thus if we have a purely priority-based solution we can make everything work.

By default we can order the MTL in whatever order we consider adequate, but always higher than any BTL. Thus, as the OB1 will inherit the max priority of the BTLs, if any MTL is ready to work the CM (who will inherit this priority) will be picked up. Selecting the OB1 PML become as simple as increasing it's priority to something larger than any MTL.

Sounds simple to implement, and pretty logical for the users. It does change the default (MTL instead of PML), but the change is sensible and desirable.

**Comment by hjelmn** [comment]
@bosilca Pretty much. The only difference is the BTLs don't have a priority since there may be many transports in use. So right now ob1 uses its own priority. In the future it might be useful to determine the priority for ob1 using the active btls. This way we could select ob1 when running only intra-node since vader is much faster than both mxm and psm.

**Pull request merged**
