### PR TITLE
grpcomm brcks: fix copy-paste bug which affects performance

### PR DESCRIPTION
**Pull request by nkogteva**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 20 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_276/c/output/errors/index.html

* Coverity found 2 errors for mxm: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/mxm_276/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/276/
Test PASSed.

**Comment by rhc54** [comment]
@nkogteva I'm a little puzzled - this looks more like a correctness issue. If you leave the data out, will things still work? In other words, does this data need to be there, or was it just being overwritten or ignored?

**Comment by nkogteva** [comment]
@rhc54 This line was duplicated. Data is still present.

**Pull request merged**
