### PR TITLE
Update submodule pointers - do not commit

### PR DESCRIPTION
**Pull request by rhc54**
Just testing the configuration changes in PMIx/PRRTE

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by rhc54** [comment]
@janjust The Mellonxo CI is failing on test of an MCA param `--mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'`. I suspect this was relying on PMIx to pick it up, which it no longer does as that MCA param has nothing to do with PMIx.

Is this a behavior you wish to preserve? You might need to pick it up in the schizo/ompi component. Note that we do pick up the same behavior from the cmd line in PRRTE - just not as an MCA param.

**Comment by rhc54** [comment]
@jsquyres @gpaulsen Can you please bring this up on today's telecon? You folks need to decide what to do about Mellanox CI and the path forward so you can commit PRRTE/PMIx updates.

**Comment by gpaulsen** [comment]
Our consensus was that we'll implement something in `schizo/ompi` component for v5.
Shorter term, mellanox will remove the test(s) so that we can update our submodule pointers until we have the new `schizo/ompi` code, then they will re-enable the `mca_base_env_list` tests to test long term.

**Pull request closed without merging**
