### PR TITLE
v4.0.x: fortran/use-mpi-f08: clean [p]ompi_FOO_f bindings

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by hppritcha** [comment]
@gpaulsen I think we should pull this in.

**Comment by gpaulsen** [comment]
I noticed that this file was deleted in this PR, is that intentional?
`ompi/mpi/fortran/use-mpi-f08/pmpi-f-interfaces-bind.h`

**Comment by ggouaillardet** [comment]
@gpaulsen this is intentional. The rationale is we do not need the bindings for the internal `pompi_*` subroutines

**Comment by hppritcha** [comment]
@jsquyres please review when you have some cycles

**Pull request merged**
