### PR TITLE
memory/linux: make memory_linux_memalign an enum

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres can you double check that and tell me whether it is a fit for open-mpi/ompi#967

**Comment by jsquyres** [comment]
@ggouaillardet I agree with @igor-ivanov .  Thanks for filing the PR.

**Comment by ggouaillardet** [comment]
@igor-ivanov i updated the PR, you can now merge and cherry-pick this commit into open-mpi/ompi-release#967

**Comment by ggouaillardet** [comment]
:bot:retest

**Pull request merged**
