### PR TITLE
Merge opal_free_list_t and ompi_free_list_t

### PR DESCRIPTION
**Pull request by hjelmn**
Now that the mpool is down in opal there is no reason to maintain separate free list implementations. This pull request merges the two free lists (opal_free_list_t and ompi_free_list_t).

See http://www.open-mpi.org/community/lists/devel/2015/02/17003.php.

Some notes about this pull request:

 - There are no longer multiple initialization functions (ompi_free_list_init, ompi_free_list_init_new, ompi_free_list_init_new_ex, etc). Instead there is a single initialization function. This should make the code cleaner.

 - I added an additional initialization field for opal_free_list_init: unused0. This will later be used to pass an optional allocator module to use for all allocation in the free list. Passing NULL will use the default allocator.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/249/

**Build Log**
*last 50 lines*

 ```
[...truncated 7387 lines...]
btl_usnic_frag.h:559: error: 'item' undeclared (first use in this function)
btl_usnic_frag.h:562: error: 'opal_btl_usnic_module_t' has no member named 'ack_segs'
btl_usnic_frag.h: In function 'opal_btl_usnic_ack_segment_return':
btl_usnic_frag.h:587: error: 'opal_btl_usnic_module_t' has no member named 'ack_segs'
btl_usnic_frag.h:587: error: 'opal_btl_usnic_segment_t' has no member named 'us_list'
In file included from btl_usnic_send.h:15,
                 from btl_usnic_send.c:41:
btl_usnic_ack.h: In function 'opal_btl_usnic_piggyback_ack':
btl_usnic_ack.h:94: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
btl_usnic_ack.h:96: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
btl_usnic_ack.h:102: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
In file included from btl_usnic_send.c:41:
btl_usnic_send.h: In function 'opal_btl_usnic_check_rts':
btl_usnic_send.h:39: error: 'struct opal_btl_usnic_module_t' has no member named 'endpoints_with_sends'
btl_usnic_send.h: In function 'opal_btl_usnic_post_segment':
btl_usnic_send.h:67: error: 'opal_btl_usnic_module_t' has no member named 'mod_channels'
btl_usnic_send.h:93: error: 'opal_btl_usnic_segment_t' has no member named 'us_type'
btl_usnic_send.h:99: error: 'opal_btl_usnic_module_t' has no member named 'stats'
make[2]: *** [btl_usnic_recv.lo] Error 1
btl_usnic_send.h:100: error: 'opal_btl_usnic_channel_t' has no member named 'num_channel_sends'
btl_usnic_send.h: In function 'opal_btl_usnic_post_ack':
btl_usnic_send.h:117: error: 'opal_btl_usnic_module_t' has no member named 'mod_channels'
btl_usnic_send.h:142: error: 'opal_btl_usnic_module_t' has no member named 'stats'
btl_usnic_send.h:143: error: 'opal_btl_usnic_channel_t' has no member named 'num_channel_sends'
btl_usnic_send.h: In function 'opal_btl_usnic_endpoint_send_segment':
btl_usnic_send.h:188: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
btl_usnic_send.h:192: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
In file included from btl_usnic_send.c:41:
btl_usnic_send.h:233: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
btl_usnic_send.h:243: error: 'opal_btl_usnic_module_t' has no member named 'stats'
btl_usnic_send.h:245: error: 'opal_btl_usnic_module_t' has no member named 'stats'
make[2]: *** [btl_usnic_cclient.lo] Error 1
btl_usnic_send.h: In function 'opal_btl_usnic_release_send_segment':
btl_usnic_send.h:294: error: 'opal_btl_usnic_segment_t' has no member named 'us_type'
make[2]: *** [btl_usnic_frag.lo] Error 1
btl_usnic_send.c: In function 'opal_btl_usnic_finish_put_or_send':
btl_usnic_send.c:155: error: 'opal_btl_usnic_segment_t' has no member named 'us_hdr'
make[2]: *** [btl_usnic_util.lo] Error 1
make[2]: *** [btl_usnic_send.lo] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/usnic'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make: *** [install-recursive] Error 1
+ exit 10
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 78d648eb3585cd64d8280def07e6fe72eaea8ad5 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/249/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
I take it that this is my invitation to update the usnic BTL for your new changes...?  :-)

Can't do it today -- can do it tomorrow.

**Comment by bosilca** [comment]
What happened to OMPI_FREE_LIST_RETURN_MT ? Which version is not thread
safe and which one is not?

**Comment by hjelmn** [comment]
@bosilca There are three flavors:

opal_free_list_*_st - single-threaded
opal_free_list_*_mt - multi-threaded
opal_free_list_*      - conditioned off opal_using_threads ()

I have no problem changing this up if there are objections to the naming scheme.

**Comment by hjelmn** [comment]
@jsquyres Yup. I will leave usnic to you. Please file a pull request when you are ready.

**Comment by hjelmn** [comment]
@bosilca Also, remember that OMPI_FREE_LIST_GET_MT and the like were conditioned off opal_using_threads(). I kept that in mind when updating the code base.

**Comment by bosilca** [comment]
From a programming perspective I really like when we have a clear naming scheme. I don't mind changing it, but once we settle for one it would be really good if it is reflected in the entire code base.

**Comment by jsquyres** [comment]
PR filed for the usnic changes (https://github.com/hjelmn/ompi/pull/2), but it looks like there's still some other uses of the old free_list API in the tree.

**Comment by hjelmn** [comment]
@bosilca What do you think of the naming scheme in this PR?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/270/

**Build Log**
*last 50 lines*

 ```
[...truncated 13265 lines...]
libtool: finish: PATH="/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin:/sbin" ldconfig -n /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib/openmpi
----------------------------------------------------------------------
Libraries have been installed in:
   /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib/openmpi

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/mtl/ofi'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/mtl/ofi'
Making install in mca/mtl/mxm
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/mtl/mxm'
  CC       mtl_mxm_cancel.lo
  CC       mtl_mxm.lo
  CC       mtl_mxm_component.lo
  CC       mtl_mxm_endpoint.lo
  CC       mtl_mxm_probe.lo
  CC       mtl_mxm_recv.lo
  CC       mtl_mxm_send.lo
mtl_mxm_recv.c: In function 'ompi_mtl_mxm_imrecv':
mtl_mxm_recv.c:192: error: too many arguments to function 'opal_free_list_wait'
make[2]: *** [mtl_mxm_recv.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/mtl/mxm'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi'
make: *** [install-recursive] Error 1
+ exit 10
Build step 'Execute shell' marked build as failure
Publish TAP Results is waiting for a checkpoint on gh-ompi-master-pr #269
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/jenkins_sidelinks.txt (No such file or directory)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 2cd919b3791311bf52ec5ec439827feaf8307bf8 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/270/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/273/

**Build Log**
*last 50 lines*

 ```
[...truncated 13545 lines...]
pml_yalla_request.c:262: warning: passing argument 9 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'int' but argument is of type 'void *'
pml_yalla_request.c:262: warning: passing argument 11 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'int' but argument is of type 'void *'
pml_yalla_request.c:262: error: too few arguments to function 'opal_free_list_init'
pml_yalla_request.c:265: warning: passing argument 3 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'size_t' but argument is of type 'struct opal_class_t *'
pml_yalla_request.c:265: warning: passing argument 9 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'int' but argument is of type 'void *'
pml_yalla_request.c:265: warning: passing argument 11 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'int' but argument is of type 'void *'
pml_yalla_request.c:265: error: too few arguments to function 'opal_free_list_init'
pml_yalla_request.c:268: warning: passing argument 3 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'size_t' but argument is of type 'struct opal_class_t *'
pml_yalla_request.c:268: warning: passing argument 9 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'int' but argument is of type 'void *'
pml_yalla_request.c:268: warning: passing argument 11 of 'opal_free_list_init' makes integer from pointer without a cast
../../../../opal/class/opal_free_list.h:127: note: expected 'int' but argument is of type 'void *'
pml_yalla_request.c:268: error: too few arguments to function 'opal_free_list_init'
pml_yalla.c: In function 'mca_pml_yalla_irecv_init':
pml_yalla.c:291: warning: initialization from incompatible pointer type
pml_yalla.c: In function 'mca_pml_yalla_irecv':
pml_yalla.c:308: warning: initialization from incompatible pointer type
make[2]: *** [pml_yalla_datatype.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
pml_yalla.c: In function 'mca_pml_yalla_isend_init':
pml_yalla.c:362: warning: initialization from incompatible pointer type
pml_yalla.c: In function 'mca_pml_yalla_bsend':
pml_yalla.c:378: warning: initialization from incompatible pointer type
pml_yalla.c: In function 'mca_pml_yalla_isend':
pml_yalla.c:431: warning: initialization from incompatible pointer type
pml_yalla.c: In function 'mca_pml_yalla_imrecv':
pml_yalla.c:594: warning: initialization from incompatible pointer type
make[2]: *** [pml_yalla_request.lo] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi/mca/pml/yalla'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi'
make: *** [install-recursive] Error 1
+ exit 10
Build step 'Execute shell' marked build as failure
Publish TAP Results is waiting for a checkpoint on gh-ompi-master-pr #272
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/jenkins_sidelinks.txt (No such file or directory)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 673d7f3e157a8e6902c0cbd531e077b0397482f7 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/273/ and message: Merged build finished.
```

Test FAILed.

**Comment by bosilca** [comment]
Consistency is the keyword. As long as we propagate the same changes everywhere, I don't care which one we prefer.

**Comment by mellanox-github** [comment]
* Coverity found 20 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_277/c/output/errors/index.html

* Coverity found 3 errors for mxm: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/mxm_277/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hjelmn** [comment]
On the call today it sounded like we have a consensus on the naming scheme. Once this PR passes jenkins I will merge it.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/277/
Test PASSed.

**Comment by hjelmn** [comment]
Ok, looks good. Merging.

**Pull request merged**
