### PR TITLE
hwloc/hwloc1116: fix CPPFLAGS when CUDA support is requested

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Siegmar Gross for the report.

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@siegmargross can you please give this PR a try ?
note you need recent autotools in order to test it

@jsquyres can you please review this ?
strictly speaking, we only need to add ```$opal_datatype_cuda_CPPFLAGS``` to ```CPPFLAGS``` in order to build the embedded ```hwloc```. this is not a standalone component (with its own ```configure.ac```) but its configury stuff is slurped into Open MPI. bottom line, i only know how to add ```opal_datatype_cuda_CPPFLAGS``` __globally__ to __all__ ```CPPFLAGS```
is there a more subtle way to only do what is strictly required ?

**Comment by siegmargross** [comment]
Your PR fixes the problem, so that --with-cuda=/usr/local/cuda is enough to build everything. Thank you very much for your help.

**Comment by ggouaillardet** [comment]
@jsquyres until now, ```$opal_datatype_cuda_CPPFLAGS``` was only required to build ```opal/mca/common/cuda``` so there was no real point to add this to the global ```CPPFLAGS```.

if the only option is to add this globally, then what about this patch (that replaces this PR)
```patch
diff --git a/config/opal_check_cuda.m4 b/config/opal_check_cuda.m4
index fd7816e..8aa0793 100644
--- a/config/opal_check_cuda.m4
+++ b/config/opal_check_cuda.m4
@@ -17,7 +17,7 @@ dnl Copyright (c) 2009      Los Alamos National Security, LLC.  All rights
 dnl                         reserved.
 dnl Copyright (c) 2009-2011 Oak Ridge National Labs.  All rights reserved.
 dnl Copyright (c) 2011-2015 NVIDIA Corporation.  All rights reserved.
-dnl Copyright (c) 2015      Research Organization for Information Science
+dnl Copyright (c) 2015-2017 Research Organization for Information Science
 dnl                         and Technology (RIST). All rights reserved.
 dnl
 dnl $COPYRIGHT$
@@ -117,8 +117,7 @@ AC_MSG_CHECKING([if have cuda support])
 if test "$opal_check_cuda_happy" = "yes"; then
     AC_MSG_RESULT([yes (-I$opal_cuda_incdir)])
     CUDA_SUPPORT=1
-    opal_datatype_cuda_CPPFLAGS="-I$opal_cuda_incdir"
-    AC_SUBST([opal_datatype_cuda_CPPFLAGS])
+    CPPFLAGS="$CPPFLAGS -I$opal_cuda_incdir"
 else
     AC_MSG_RESULT([no])
     CUDA_SUPPORT=0
diff --git a/opal/mca/common/cuda/configure.m4 b/opal/mca/common/cuda/configure.m4
index 6083e08..2f6459f 100644
--- a/opal/mca/common/cuda/configure.m4
+++ b/opal/mca/common/cuda/configure.m4
@@ -4,6 +4,8 @@
 # Copyright (c) 2013      The University of Tennessee and The University
 #                         of Tennessee Research Foundation.  All rights
 #                         reserved.
+# Copyright (c) 2017      Research Organization for Information Science
+#                         and Technology (RIST). All rights reserved.
 # $COPYRIGHT$
 #
 # Additional copyrights may follow
@@ -27,8 +29,4 @@ AC_DEFUN([MCA_opal_common_cuda_CONFIG],[
           [$1],
           [$2])
 
-    # Copy over the includes needed to build CUDA
-    common_cuda_CPPFLAGS=$opal_datatype_cuda_CPPFLAGS
-    AC_SUBST([common_cuda_CPPFLAGS])
-
 ])dnl
diff --git a/opal/mca/hwloc/hwloc1116/configure.m4 b/opal/mca/hwloc/hwloc1116/configure.m4
index de1ff24..04f89cc 100644
--- a/opal/mca/hwloc/hwloc1116/configure.m4
+++ b/opal/mca/hwloc/hwloc1116/configure.m4
@@ -70,6 +70,9 @@ AC_DEFUN([MCA_opal_hwloc_hwloc1116_CONFIG],[
     # Hwloc needs to know if we have Verbs support
     AC_REQUIRE([OPAL_CHECK_VERBS_DIR])
 
+    # make sure that CUDA-aware checks have been done
+    AC_REQUIRE([OPAL_CHECK_CUDA])
+
     AC_CONFIG_FILES([opal/mca/hwloc/hwloc1116/Makefile])
 
     OPAL_VAR_SCOPE_PUSH([HWLOC_VERSION opal_hwloc_hwloc1116_save_CPPFLAGS opal_hwloc_hwloc1116_save_LDFLAGS opal_hwloc_hwloc1116_save_LIBS opal_hwloc_hwloc1116_save_cairo opal_hwloc_hwloc1116_save_xml opal_hwlo
@@ -119,8 +122,6 @@ AC_DEFUN([MCA_opal_hwloc_hwloc1116_CONFIG],[
     # this without "picky" flags.
     opal_hwloc_hwloc1116_save_cflags=$CFLAGS
     CFLAGS=$OPAL_CFLAGS_BEFORE_PICKY
-    AS_IF([test -n "$opal_datatype_cuda_CPPFLAGS"],
-          [CPPFLAGS="$CPPFLAGS $opal_datatype_cuda_CPPFLAGS"])
 
     HWLOC_SETUP_CORE([opal/mca/hwloc/hwloc1116/hwloc],
               [AC_MSG_CHECKING([whether hwloc configure succeeded])
```

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by bgoglin** [comment]
@ggouaillardet This seems identical to #3412

**Comment by ggouaillardet** [comment]
@bgoglin yep, I will now close #3412 and update both the PR and inline patch.

**Comment by ggouaillardet** [comment]
Well, we now build `hwloc` with `enable_cuda=no` in all supported branches, so this PR is no more relevant and I am closing it.

**Pull request closed without merging**
