### PR TITLE
Cherrypick/6683

### PR DESCRIPTION
**Pull request by bosilca**
Fixed SPC/MPI_T initialization error.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/563b9df0daf9b9319b79ef3823ec804d

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/651de5bee57ce2d4583d7ff7d74c5122

**Comment by hppritcha** [comment]
think this pr needs some work.  can't even compile

**Comment by hppritcha** [comment]
@ggouaillardet could you review when you have time?

**Comment by gpaulsen** [comment]
I reviewed the code, and it looks okay to me.

**Pull request merged**
