### PR TITLE
mpiext: keep paths short

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
This PR is to be merged __after__ #6035

**Comment by jsquyres** [comment]
@ggouaillardet will amend this PR with the commits from #6158.

**Comment by gpaulsen** [comment]
Added WIP-DNM label until previous comment is addressed.

**Comment by ggouaillardet** [comment]
@jsquyres I did amend the PR and CI passed so I removed the `WIP-DNM!` label, can you please give it a final review ?

**Pull request merged**
