### PR TITLE
Address Github issue #11532 by translating legacy parameters for direct launches

### PR DESCRIPTION
**Pull request by qkoziol**
Borrow code from the OMPI schizo module in PRRTE that translates legacy MCA parameters when an application is direct launched (PRRTE will translate legacy parameters when natively launched).

(cherry picked from commit 5d236e9fb322a34618f7fe64cc23f620d728ce1d)

### CODE REVIEW

**Comment by qkoziol** [comment]
Updated my v5.0.x branch correctly and re-opened this PR.

**Review by janjust — APPROVED** [review]

**Comment by jsquyres** [comment]
Just like #11916, CI is still failing.

Is there a reason you didn't just fix #11916?  It is preferable to just fix existing PRs rather than close them and re-open new PRs (which effectively loses context and history).

**Comment by awlauria** [comment]
my guess is a submodule update is needed for v5

**Comment by rhc54** [comment]
Yeah, this is failing because it is looking at old PMIx code. Commit #11920 and then rebase this and it should be okay.

**Comment by qkoziol** [comment]
Looks like I don't have #11920 underneath this in my 5.0.x branch yet.  I'll pull it in and rebase, then force push this.

**Comment by awlauria** [comment]
@qkoziol the PR to v5 was merged, let's give this another ci run before closing/force pushing.

**Comment by awlauria** [comment]
and too late..

**Comment by awlauria** [comment]
Please do another force push to resolve the conflicts.

**Comment by jsquyres** [comment]
@qkoziol Please stop closing PR's and opening new PR's.  Please just fix your original PR.

**Comment by qkoziol** [comment]
Looks like "syncing my branch" in Github is what keeps closing the PR @jsquyres

**Comment by jsquyres** [comment]
> Looks like "syncing my branch" in Github is what keeps closing the PR @jsquyres

Hahah!  You anticipated my comment.  😄

**Comment by jsquyres** [comment]
@qkoziol I don't know what you're doing, but if you bring the branch on this PR up to the HEAD of the target branch of this PR (i.e., `v5.0.x`), I think Github may close your PR because it determines that there's no difference between your branch and the target branch...?

**Comment by qkoziol** [comment]
> @qkoziol I don't know what you're doing, but if you bring the branch on this PR up to the HEAD of the target branch of this PR (i.e., `v5.0.x`), I think Github may close your PR because it determines that there's no difference between your branch and the target branch...?

Not certain ¯\_(ツ)_/¯

I'm just going to stay away from the "sync branch" option, when the branch has an open PR...

**Pull request closed without merging**
