### PR TITLE
Remove dead code related to PPC Big Endian

### LINKED ISSUE #4102: Remove PowerPC Big Endian integration
Follow-on to Issue #4053 there are some places in the code that still refer to:
  `powerpc-*|powerpc64-*|ppc-*`

These should be removed since they represent dead code. It may take a while to identify all of the spots, so we are doing so separately.

### PR DESCRIPTION
**Pull request by jjhursey**
* Resolves #4102

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey Do we need to port the configure changes relating to #4102 to the PMIx code as well?

**Comment by jjhursey** [comment]
@rhc54 Yeah we should. I'll take point on that. It should be a slight variation on the patch in #4053

**Comment by hjelmn** [comment]
I think the consensus is to bring back BE support.

**Comment by hppritcha** [comment]
@jjhursey what's happening with this PR?  Should it be closed?

**Comment by jsquyres** [comment]
Yes, per https://github.com/open-mpi/ompi/issues/4349#issuecomment-374970982, we should close this PR without merging.

**Pull request closed without merging**
