### PR TITLE
Protect the tcp_endpoints list from concurrent accesses.

### PR DESCRIPTION
**Pull request by bosilca**
This patch will fix some [hopefully all] of the segfaults when TCP progress thread is on. Thanks Gilles for your help.

### CODE REVIEW

**Comment by hppritcha** [comment]
Is there a corresponding commit on master?

**Comment by bosilca** [comment]
This is the PR for master, that will be pulled in once we agree on the solution.

**Comment by jsquyres** [comment]
@ggouaillardet @bosilca Should we merge to master / PR to v2.0.x and v2.x?

**Comment by bosilca** [comment]
I will let @ggouaillardet comment and merge it if he is happy with.

**Comment by ggouaillardet** [comment]
i read the patch and it looks good to me, so i will go ahead and merge it.

i will fully test it next week, and then PR to the release branches

**Pull request merged**
