### PR TITLE
Do a partial rework of LICENSE file

### PR DESCRIPTION
**Pull request by hppritcha**
I'll push an update to master and v2.x later.

@jsquyres 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by jsquyres** [comment]
There's no real need to wait for CI on this -- it's a doc update.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/c09986dfcf22b5b5df46e8077b88a565

**Pull request merged**
