### PR TITLE
update bml.h

### PR DESCRIPTION
**Pull request by jo-pillar**
BML is short for BTL Management Layer instead of BML Ma…nagement Layer. I have corrected it. #11243 

Signed-off-by: zhuodong <jopillar11@gmail.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
@jo-pillar Thank you!

**Comment by jo-pillar** [comment]
> @jo-pillar Thank you!

my pleasure

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
@jo-pillar Can you PR this to the v5.0.x branch?  We require cherry-pick and signed-off-by notations for commits on our release branches.  You can do something like the following:

```sh
# Pull down the latest from the Open MPI community repo
git checkout main
git pull --rebase

# Check out the v5.0.x branch
git checkout v5.0.x
git pull --rebase
git submodule update

# Cherry pick your commit on the "main" branch
git cherry-pick -x 19b515f15f3d0e6a7b6faa5f75861fcf89e04440

# Replase yourfork with the git remote name for your github fork
git push yourfork
```

**Comment by jo-pillar** [comment]
> @jo-pillar Can you PR this to the v5.0.x branch? We require cherry-pick and signed-off-by notations for commits on our release branches. You can do something like the following:
> 
> ```shell
> # Pull down the latest from the Open MPI community repo
> git checkout main
> git pull --rebase
> 
> # Check out the v5.0.x branch
> git checkout v5.0.x
> git pull --rebase
> git submodule update
> 
> # Cherry pick your commit on the "main" branch
> git cherry-pick -x 19b515f15f3d0e6a7b6faa5f75861fcf89e04440
> 
> # Replase yourfork with the git remote name for your github fork
> git push yourfork
> ```

ok, I have pushed the commit to branch v5.0.x.

**Pull request merged**
