### PR TITLE
btl/sm: effectively delete the SM BTL

### PR DESCRIPTION
**Pull request by jsquyres**
If a user explicitly asks for the "sm" BTL, print a show_help message
saying that the SM BTL is dead, and the user should be using "vader".

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>
(cherry picked from commit 5cf64e65557d3ac3dfc2155dd5162e1fe4c6923e)

CI won't pass until #3897 (remove Yoda SPML) is merged.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4dc609ee2ee3a1469d1e6e9e44c55b3c

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/51ac739cda665e73e4561322cf5ae0b7

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c2f6091e49036c46af3a0d90728463a6

**Comment by jsquyres** [comment]
Added 6e35cfc19aa0019793309c1c210d939483cde142 (Coverity fix from @ggouaillardet).  CI will continue to fail on this PR until #3897 (remove Yoda SPML) is merged.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/86fc88dacaa06f2ec9d007351ee131b6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b839eba4abba389b0413f45039b585cd

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f95e19ed6ce236f8f06d54c8e901fab0

**Comment by bwbarrett** [comment]
#3897 is merged, so this should pass now.

bot:retest

**Comment by hppritcha** [comment]
bot:ompi:rebuild

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by bwbarrett** [comment]
ok, let's try this again...  The OMPI Build checker was using the source repo of the merge for the build, which means Jeff would have to rebase for this to work.  We've gone back and forth about that vs. using the merged commit series that GitHub provides, which is a more accurate assessment of how the merge is going to work anyways.  Switched jenkins to the merge commit, so hopefully we'll have success.

bot:ompi:retest

**Comment by hppritcha** [comment]
@bwbarrett good to go

**Pull request merged**
