### PR TITLE
ompi/comm: Improve MPI_Comm_create algorithm (v3.x)

### PR DESCRIPTION
**Pull request by artpol84**
Force only procs that are participating in the ne Comm to decide what
    CID is appropriate. This will have 2 advantages:
    * Speedup Comm creation for small communicators: non-participating procs
      will not interfere
    * Reduce CID fragmentation: non-overlaping groups will be allowed to use
      same CID.

Signed-off-by: Artem Polyakov <artpol84@gmail.com>
(cherry picked from commit 50a6d106f655d5c36aae62aad59121547f60648a)

### CODE REVIEW

**Comment by artpol84** [comment]
## Efficiency verification
https://github.com/open-mpi/ompi/pull/3375#issuecomment-295864721

**Comment by artpol84** [comment]
## MTT verification
https://github.com/open-mpi/ompi/pull/3375#issuecomment-296007724

**Comment by jsquyres** [comment]
Do not merge until #3375 is merged.

**Comment by bwbarrett** [comment]
Is this a bug or an enhancement?  It really feels like an enhancement that we shouldn't backport into all the releases...

**Comment by bwbarrett** [comment]
Closing this PR, as we aren't going to pull this enhancement into 3.0; it will be in the fall release, since it's already in master.

**Pull request closed without merging**
