### PR TITLE
Romio fixes from mpich

### PR DESCRIPTION
**Pull request by markalle**
These are the fixes from MPICH's romio related to this issue with HDF5:
https://github.com/open-mpi/ompi/issues/6871

I think it's really just the darray + flatten portions of the fix that HDF5 needs, but this includes a couple other small fixes that seem safe and that I wasn't completely sure weren't also hit by HDF5 or similar apps.

The sieving fix isn't merged into mpich at the present time (https://github.com/open-mpi/ompi/issues/6871), but it's gone through some reviews already and I think it's about to get merged.

### CODE REVIEW

**Comment by hppritcha** [comment]
I'll check this on one of our systems with luste fs

**Comment by hppritcha** [comment]
@markalle this works for me on a couple of systems with lustre fs.

**Comment by gpaulsen** [comment]
So, @hppritcha, We need to decide if we want to take this patch on top of our ROMIO, or if we want to wait for MPICH/ROMIO to release with these fixes (if they ever will).
My understanding is that they've taken 1 of these 3 commits, but are possibly still iterating on the others.
If we wait, we can decide if we hold v4.0.6 for this, or pick it up in a future v4.0.x patch, or only pick it up in v4.1.x, or v5 streams (since it would be a new ROMIO update).

**Comment by ggouaillardet** [comment]
fwiw, I finalized #8343 (ROMIO 3.4 refresh) for v5.

**Comment by markalle** [comment]
For v5 I like the goal of having a straight drop of romio directly into ompi.  Even though I'm skeptical about it ever being that clean it's a nice direction to attempt and we can certainly get closer to it.  But for v4 I figured there wouldn't be major revision of romio so we whould just keep putting fixes into the version we have

**Review by gpaulsen — APPROVED** [review]
This has been through IBM Specturm MPI on GPFS, and through Open-MPI on Lustre with HDF5 make check.

**Pull request merged**
