### PR TITLE
v4.0.x: autogen.pl: patch libtool.m4 for OSX Big Sur

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks FX Coudert for reporting this issue and pointing
to a solution.

Refs. open-mpi/ompi#8218

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

(back-ported from commit open-mpi/ompi@3f45ceda1bda3eafe2d2b6f65c48a0c4faf7db88)

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Review by jsquyres — APPROVED** [review]

**Comment by hppritcha** [comment]
This patch fixes the internal hwloc and pmix as well.

**Comment by bgoglin** [comment]
@hppritcha Did anybody actually observe an issue with hwloc? If so, I'd like to get details on how to reproduce.

**Comment by rhc54** [comment]
No - we were only conjecturing if we would need to patch it as well.

**Pull request merged**
