### PR TITLE
Fix coredump for unaligned atomics. 

### PR DESCRIPTION
**Pull request by awlauria**

### CODE REVIEW

**Comment by awlauria** [comment]
Opened as an alternative to https://github.com/open-mpi/ompi/pull/8574

**Review by bosilca — APPROVED** [review]

**Review by hjelmn — APPROVED** [review]
LGTM

**Comment by devreal** [comment]
I'm not sure I understand how this deals with misaligned atomics at all levels. We might still end up doing misaligned CPU atomics in `mca_btl_base_am_atomic_64`, no?

**Comment by hjelmn** [comment]
The BTL atomics should never be used with unaligned values. If we enforce that requirement this is sufficient since we have no other path that would attempt it.

**Comment by awlauria** [comment]
@devreal the test where I found this, [c_reqops.c,](https://github.com/open-mpi/ompi-tests/blob/master/ibm/onesided/c_reqops.c) passes with this change as well as #8574.

**Pull request merged**
