### PR TITLE
monitoring lib: rename to ompi_monitoring_prof.so

### PR DESCRIPTION
**Pull request by jsquyres**
The library that is installed is specific to Open MPI, so put an "ompi_" prefix on it.

Also do some minor line wrappings and cleanups of text.

Signed-off-by: Jeff Squyres jsquyres@cisco.com

@bosilca I added an "ompi_" prefix to the library name so that it is clear that the installed library is specific to Open MPI, and did some other minor text cleanups.  Please review.  Did you have a milestone in mind for bringing this monitoring stuff over to the v2.x branch?

### CODE REVIEW

**Comment by bosilca** [comment]
The library was never intended to be used by a wider community. It was intended for our internal testing purposes (which explains why we put it in the test directory).

I would like to bring this in the 2.x asap.

**Comment by jsquyres** [comment]
Should it be a noinst ?  Right now, it's installed.

Sent from my phone. No type good.

On Feb 20, 2016, at 12:54 PM, bosilca <notifications@github.com<mailto:notifications@github.com>> wrote:


The library was never intended to be used by a wider community. It was intended for our internal testing purposes (which explains why we put it in the test directory).

I would like to bring this in the 2.x asap.

-

**Comment by bosilca** [comment]
The test itself is installed and will not work without the library.

**Comment by jsquyres** [comment]
@bosilca If it's a test, why is the test installed?

I.e., you argued both ways: 1) it's a test, and shouldn't be used by anyone, 2) but we install it anyway.

My $0.02 -- it either:

* Is installed by default and is intended for a wide audience
* Is not installed by default and is intended for a narrow (developer-only) audience

**Comment by bosilca** [comment]
I should have been more clear. The test itself is not installed, but the library is. This library provides the minimal support for using the monitoring PML (via the PMPI interface), it trigger the pvars to generate and save the communication matrix that can be then used for other things (weights for the topology as an example). So, while it is a convenience library, we need it installed in order to be able to play with the topologies.

**Comment by jsquyres** [comment]
Let's discuss in person this week.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by ibm-ompi** [comment]
Test passed.

**Comment by jsquyres** [comment]
Please add a Signed-off-by line to this PR's commit.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/bc8012219390509c64005eb8c016e840

**Comment by jjhursey** [comment]
PGI CI failure is an internal problem - should be fixed soon.

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by jsquyres** [comment]
@bosilca I rebased yesterday and merged.

**Pull request merged**
