### PR TITLE
Update PMIx and PRRTe pointers.

### PR DESCRIPTION
**Pull request by awlauria**

### CODE REVIEW

**Comment by jsquyres** [comment]
@awlauria Any idea why CI failed?

Is this updating to release versions of PMIx / PRTE, or off-release commits?

**Comment by awlauria** [comment]
This is main, so only bumping to the latest. I don't have any insight to the ci failures unfortunately.

**Comment by janjust** [comment]
I'm having Andrii look at it - a bit strange that it failed, it seemed to have run locally just fine.

ubuntu@ompi-ci-1:/$ /GIT/ompi-434-2/ompi_install/examples/hello_c
Hello, world, I am 0 of 1, (Open MPI v5.1.0a1, package: Open MPI ubuntu@ompi-ci-1 Distribution, ident: 5.1.0a1, repo rev: 03f5b70, Unreleased developer copy, 129)
ubuntu@ompi-ci-1:/$ echo $?
0

**Comment by jsquyres** [comment]
> This is main, so only bumping to the latest. 

Gotcha; I missed that.  Thanks.

**Comment by janjust** [comment]
I see that @jsquyres docs PR passed without issues, are we sure this isn't a ptr update issue? I can't see what it is though.

**Comment by rhc54** [comment]
According to the CI log:
```
Building OMPI, UCX and tests
env: '/GIT/ompi-434-4/jenkins_scripts/jenkins/ompi/run.sh': No such file or directory
command terminated with exit code 127
Error: Process completed with exit code 127.
```
Looks to me like a CI failure

**Comment by rhc54** [comment]
Update the pointers again - found a cmd line parser problem. I don't think it impacts the current failure, but worth the update.

**Comment by awlauria** [comment]
Updated the pointers.

**Review by janjust — APPROVED** [review]

**Pull request merged**
