### PR TITLE
ofi: follow user specified include/exclude list to select providers

### PR DESCRIPTION
**Pull request by wenduwan**
This PR addresses https://github.com/open-mpi/ompi/issues/12233

Since 5.0.x, we introduced an optional `FI_HMEM` capability in ofi provider selection logic(both mtl and btl) in order to support accelerator memory.  As described in the issue, this introduced a bug that can cause the wrong ofi provider to be selected, even if the user explicitly includes/excludes the provider name.

This change refactors the selection logic to correctly handle the include/exclude list, and therefore fixes the bug.

### CODE REVIEW

**Review by hppritcha — APPROVED** [review]

**Comment by hppritcha** [comment]
@BrendanCunningham i don't know if opx supports FI_HMEM but esp. if it does can you double check this?

**Comment by shijin-aws** [comment]
I think we should still add FI_REMOTE_COMM in the hints' caps. It doesn't make sense to pick shm even if user explicitly include it.

**Review by shijin-aws — APPROVED** [review]

**Comment by wenduwan** [comment]
@shijin-aws I talked to Brian about this and learned that btl/sm is expected to handle same-node communication, so btl/ofi should only worry about inter-node. I added a commit for this.

@hppritcha Please see my second commit which adds `FI_REMOTE_COMM` capability.

**Comment by wenduwan** [comment]
Hi @BrendanCunningham did you find any issue with the change? AWS is currently blocked by this. We would like to include it in the upcoming Open MPI 5.0.2 release.

**Comment by wenduwan** [comment]
@BrendanCunningham I checked with Howard. We agree to merge this fix first - please let me know if you find out any issues.

**Comment by tmh97** [comment]
Hey @wenduwan I'll take a look on Monday and will let you know if OPX has any issues with this change, thanks!

**Comment by shijin-aws** [comment]
>@BrendanCunningham i don't know if opx supports FI_HMEM but esp. if it does can you double check this?

I am a bit confused, if opx supports FI_HMEM, it should be picked up by btl/ofi even without the PR. 

If opx doesn't support FI_HMEM, this PR should fix the bug that will cause shm to be selected (and then excluded)

What is the goal of the check here?

**Comment by tmh97** [comment]
@wenduwan @hppritcha Verified this change! OPX provider is found without issue, I tested using OSU MB's, and with the following options, which are typically preferred for OPX runs --mca mtl ofi --mca btl self,vader

**Pull request merged**
