### PR TITLE
v2.x: Improve x86-64 timer performance

### PR DESCRIPTION
**Pull request by matcabral**
porting PR #2926 to v2.x

### CODE REVIEW

**Comment by bosilca** [comment]
I found an interesting reading on this issue (http://akaros.cs.berkeley.edu/lxr/akaros/kern/arch/x86/rdtsc_test.c). We might want to have a reference on it somewhere.

**Comment by bosilca** [comment]
The changes in opal/runtime/opal_progress.c are good. I have added a comment regarding the lack of documentation on why lfence+rdtsc is a better approach.

**Comment by jsquyres** [comment]
@bosilca Thanks for the sanity check. 👍

**Comment by hppritcha** [comment]
@hjelmn please double check this PR.

**Pull request merged**
