### PR TITLE
v3.1.x: Backport a fix for pgcc18 to pmix.

### PR DESCRIPTION
**Pull request by awlauria**
Refs openpmix/openpmix#1628

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a45516bdb7a820fe776e5d8f510fc4dc

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest

**Comment by jjhursey** [comment]
PMIx 2.x will likely not have another release. However, @awlauria Can you file a PR against the v2.2 branch of OpenPMIx so if anyone goes looking for the fix they can find it in the repo?

I'd suggest that the RM's take this patch to the branch. This patch should have come over with https://github.com/open-mpi/ompi/pull/7391

**Comment by jsquyres** [comment]
Per developer discussions, it sounds like this is not a regression against v3.1.x.  So we're not including it in v3.0.6.  It will be merged after the formal v3.0.6 release, meaning that it'll be in the nightly snapshot tarball for any users who need it.

**Pull request merged**
