### PR TITLE
Optimizations to PML-CM, MTL-OFI

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- PML-CM Send/Recv optimizations
- Use direct pack/unpack for contiguous datatypes in homogeneous build
- Inline MTL OFI, datatype pack/unpack

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 910 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_413/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_413/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_413/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/413/

**Build Log**
*last 50 lines*

 ```
[...truncated 21900 lines...]
+ timeout -s SIGKILL 10m mpirun -np 8 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/ring_c
ring_c: opal_convertor.c:227: opal_convertor_pack: Assertion `(pConv)->bConverted < (pConv)->local_size' failed.
[jenkins01:09010] *** Process received signal ***
[jenkins01:09010] Signal: Aborted (6)
[jenkins01:09010] Signal code:  (-6)
Process 0 sending 10 to 1, tag 201 (8 processes in ring)
[jenkins01:09010] [ 0] /lib64/libpthread.so.0[0x3d6980f710]
[jenkins01:09010] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x3d69032925]
[jenkins01:09010] [ 2] /lib64/libc.so.6(abort+0x175)[0x3d69034105]
[jenkins01:09010] [ 3] /lib64/libc.so.6[0x3d6902ba4e]
[jenkins01:09010] [ 4] /lib64/libc.so.6(__assert_perror_fail+0x0)[0x3d6902bb10]
[jenkins01:09010] [ 5] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libopen-pal.so.0(opal_convertor_pack+0xbf)[0x7ffff76605e0]
[jenkins01:09010] [ 6] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_btl_tcp.so(mca_btl_tcp_prepare_src+0x164)[0x7ffff229f7cc]
[jenkins01:09010] [ 7] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_pml_ob1.so(+0x1b481)[0x7ffff208b481]
[jenkins01:09010] [ 8] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_send_request_start_prepare+0x4e)[0x7ffff208da3f]
[jenkins01:09010] [ 9] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_pml_ob1.so(+0xe655)[0x7ffff207e655]
[jenkins01:09010] [10] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_pml_ob1.so(+0xe8b1)[0x7ffff207e8b1]
[jenkins01:09010] [11] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_send+0x56e)[0x7ffff207f866]
[jenkins01:09010] [12] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(PMPI_Send+0x2d4)[0x7ffff7d0e996]
[jenkins01:09010] [13] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/ring_c[0x400942]
[jenkins01:09010] [14] /lib64/libc.so.6(__libc_start_main+0xfd)[0x3d6901ed1d]
[jenkins01:09010] [15] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/ring_c[0x4007a9]
[jenkins01:09010] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node jenkins01 exited on signal 13 (Broken pipe).
--------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/413/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/413/tap-master-files/cov_stat.tap].
not ok - coverity detected 910 failures in all_413 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_413/output/errors/index.html
not ok - coverity detected 5 failures in oshmem_413 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_413/output/errors/index.html
ok - coverity found no issues for yalla_413
ok - coverity found no issues for mxm_413
not ok - coverity detected 2 failures in fca_413 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_413/output/errors/index.html
ok - coverity found no issues for hcoll_413

TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_413/output/errors/index.html
coverity_for_oshmem	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_413/output/errors/index.html
coverity_for_fca	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_413/output/errors/index.html
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi/commit/00ac99de64a0a4bbbe3856230346b0534b2a93c1
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of bd7e4e1abdf41886b51549f0492e6eacc6e03ce3 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/413/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@jithinjosepkl Are you sure about these convertor changes?  That's the only thing here that could have caused the failure in the TCP BTL, I think...?

**Comment by jithinjosepkl** [comment]
Yes, Let me quickly check it. Looks like its an assertion failure.
I had tried my tests with no-dbg and --with-mpi-param-check=never config options.

**Comment by jithinjosepkl** [comment]
I think this is a missing flag set. 
I had run my tests with --with-mpi-param-check=never. Let me fix t

**Pull request closed without merging**
