### PR TITLE
pml_ucx: fix uninitialized field req_status->_cancelled.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jladd-mlnx** [comment]
@yosefe  Please add 'signed-off-by' on the commit message.

**Comment by yosefe** [comment]
@hppritcha can you pls review?

**Comment by miked-mellanox** [comment]
+1

**Comment by miked-mellanox** [comment]
@yosefe - please merge into v2.x, v1.10(?)

**Pull request merged**
