### PR TITLE
Added a script called nrofftomdconversion.py 

### PR DESCRIPTION
**Pull request by Colton-K**
nrofftomdconversion.py will convert files to md files with only occasional hiccups. Note: need to install pandoc to run the script

Signed-off-by: Colton Kammes <ckammes@nd.edu>

### CODE REVIEW

**Comment by jjhursey** [comment]
Can you move this script into `contrib/`? That's where we put helpful scripts like this one.
Additionally, can you add a header to the script showing an example of how it should be used?

Thanks!

**Comment by jsquyres** [comment]
> Can you move this script into `contrib/`? That's where we put helpful scripts like this one.
> Additionally, can you add a header to the script showing an example of how it should be used?

One more thing -- can you rename the script to be `nroff-to-md-conversion.py`?  😄

**Comment by gpaulsen** [comment]
@jsquyres did you see this?

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
Comments on this were addressed @jsquyres @jjhursey . I haven't tested the script though.

**Comment by jsquyres** [comment]
This script ended up being used as a starting point for the off-repo scripts that we are using in the larger convert-to-Sphinx-and-ReStructured-Text effort in #8329.  I'm closing this PR without merging, but know that we used all of this work as part of the behind-the-scenes work in #8329.

**Pull request closed without merging**
