### PR TITLE
Small style changes to libnbc

### PR DESCRIPTION
**Pull request by planetA**
I also have a question, why the code checks return value of ompi_datatype_get_extent? This function always returns 0. Can I just remove error checking here?

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca Can you respond?  Thanks!

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by bosilca** [comment]
Why would you remove the error check ? The function returns an int and not a void, it makes sense to always check the return value (in case one day we change the return from opal_datatype_get_extent). You can add an OPAL_LIKELY/OPAL_UNLIKELY to hint the compiler if you think this is a performance hit.

**Comment by planetA** [comment]
@bosilca OK. I see your point.

**Comment by hppritcha** [comment]
discussed at OMPI F2F and decided to close.  @planetA can open a new PR if desired.

**Pull request closed without merging**
