### PR TITLE
oshmem: Fix unsigned type comparisons

### PR DESCRIPTION
**Pull request by gleon99**
Port https://github.com/open-mpi/ompi/pull/10920

### CODE REVIEW

**Comment by gleon99** [comment]
@yosefe  actually some types (e.g [SHMEM_UINT32_T](https://github.com/open-mpi/ompi/blob/v4.1.x/oshmem/include/oshmem/constants.h#L87)) are not defined in this branch at all,
so can't fix the comparisons without adding the missing types
https://github.com/open-mpi/ompi/pull/10972/files#diff-14a08f8f032f0d391cbf90aa64b61062f642ad287a8912d8f084149b405f7926L123

Should we backport them as well?

**Comment by jsquyres** [comment]
Note that this PR failed the Mellanox CI (a compile failure).  Please update.

**Comment by bwbarrett** [comment]
@open-mpi/ompi-gatekeeper-4-1-x Testing the ability to tag RMs; please ignore.

**Comment by gleon99** [comment]
@jsquyres fixed

**Review by yosefe — APPROVED** [review]

**Comment by gleon99** [comment]
@jsquyres @hppritcha  can merge please?

**Pull request merged**
