### PR TITLE
coll/basic: Expand check for negative input values

### PR DESCRIPTION
**Pull request by jjhursey**
* negative values are parameter errors

### CODE REVIEW

**Comment by bosilca** [comment]
Why is this done deep inside the collective framework instead of being part of the MPI_PARAM_CHECK in the MPI API ?

**Comment by jjhursey** [comment]
@bosilca That's a good point. Putting it at the `mpi/c` layer is more broadly applicable. I'll work on an alternative PR (marking this as WIP for now).

**Comment by jjhursey** [comment]
bot:mellanox:retest

**Comment by jjhursey** [comment]
@bosilca I updated the commit to move the error check to the `mpi/c` layer. Do you want to take another look?

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by bosilca** [comment]
@jjhursey thanks, this looks good. This topology validation shouldn't be something that all [blocking and non-blocking] neighborhood collective ?

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by jjhursey** [comment]
Per comment from @bosilca I can extend this PR to add the check in the other neighborhood collectives. Adding the WIP flag until I can update the PR.

**Comment by jjhursey** [comment]
@bosilca I don't know if you are interested, but I updated the PR with the param check in all of neighborhood collectives. I think this PR is ready to go after CI is done with it.

**Pull request merged**
