### PR TITLE
Ensure buffer_unload leaves the buffer in a clean state

### PR DESCRIPTION
**Pull request by rhc54**
Silence a warning in orte/nidmap

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Refs #6954 

@ggouaillardet Alternative solution - see what you think

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d9ae3d469eddd9b94440498b5f31c567

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7683f43f69a91c493cbf3ed732da784d

**Comment by ggouaillardet** [comment]
Thanks! now merging (and closing my PR)

**Pull request merged**
