### PR TITLE
v3.1.x: Bring the git commit checker GitHub action to v3.1.x

### PR DESCRIPTION
**Pull request by jsquyres**
Bring the git commit checker GitHub action to the v3.1.x branch, and enforce cherry picks on this release branch.

bot:notacherrypick

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/013b265ceb47c187c24367f2684814c9

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b075829d2de475bf9b60d62af8e9642d

**Comment by jsquyres** [comment]
@jjhursey Got core dumps on the IBM CI runs -- any idea what happened there?

**Review by bwbarrett — APPROVED** [review]

**Review by bwbarrett — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
Humm. Not sure about the IBM CI. Must have been sunspots or something. I'll look on the box to see if the cores are still there. Sorry about that.

**Comment by jsquyres** [comment]
@jjhursey Not worth it.  The sunspots are now gone. 

image

**Pull request merged**
