### PR TITLE
opal/cuda: Handle CUDA VMM pointers in accelerator check_addr function

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
Support CUDA VMM pointers

### CODE REVIEW

**Comment by jsquyres** [comment]
@Akshay-Venkatesh Why did you put `bot:notacherrypick` on this PR?

**Comment by Akshay-Venkatesh** [comment]
> @Akshay-Venkatesh Why did you put `bot:notacherrypick` on this PR?

@jsquyres I've addressed this now

**Comment by jsquyres** [comment]
> > @Akshay-Venkatesh Why did you put `bot:notacherrypick` on this PR?
> 
> @jsquyres I've addressed this now

I still see `bot:notacherrypick` in the description of this PR.

You can find a description of what `bot:notacherrypick` is supposed to be used for in https://docs.open-mpi.org/en/v5.0.x/developers/git-github.html#git-branch-scheme.  Please use it approrpiately.

**Review by bosilca — CHANGES_REQUESTED** [review]
I left comments on the PR for the 4.1. Please address them here as well

**Comment by Akshay-Venkatesh** [comment]
> I left comments on the PR for the 4.1. Please address them here as well

@bosilca Thanks for catching the leaked handle. I've made relevant fixes to handle VMM pointers in general. Please review when you get a chance and thanks in advance.

**Review by janjust — APPROVED** [review]

**Review by bosilca — APPROVED** [review]

**Pull request merged**
