### PR TITLE
Enable AVX support with Intel compilers

### PR DESCRIPTION
**Pull request by bosilca**
Refs #8334

### CODE REVIEW

**Review by ggouaillardet — APPROVED** [review]
minor typo in the first commit message ("not not"), otherwise looks good to me

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
@rajachan Can you try this patch with your app performance test?

**Comment by jsquyres** [comment]
Corresponding 4.1.x PR: #8373 8373

**Review by rajachan — APPROVED** [review]
Tested the PR, looks good to me. I no longer observe the performance degradation when op/avx component is used.

**Comment by jsquyres** [comment]
@rajachan Just curious -- is AVX2 being used?  And if so, do you see any performance benefit?

**Comment by rajachan** [comment]
This PR disables AVX2 as well. Assuming you were asking about AVX, I see a marginal (~1%) improvement in the loop time for the specific test case I was running. I have not evaluated microbenchmarks yet.

**Comment by bosilca** [comment]
This PR only fixes the support for icc. The restrictions in AVX support are now in #8376.

**Comment by rajachan** [comment]
The icc fix is good to go, thanks for splitting out the restrictions change to a separate PR.

**Pull request merged**
