### PR TITLE
support MPI_IN_PLACE in MPI_Ialltoall*

### PR DESCRIPTION
**Pull request by ggouaillardet**
Fixes open-mpi/ompi#2150

### CODE REVIEW

**Comment by ggouaillardet** [comment]
Refs #2150

**Comment by bosilca** [comment]
@ggouaillardet I am not sure I understand how the scheduling in libnbc works, but for scalability reasons in the a2a_sched_inplace function I would have round-robin starting from the current rank instead of starting every process from 0.

**Comment by ggouaillardet** [comment]
@bosilca 
current implementation clearly does *not* scale from a performance point of view,
but from a memory usage point of view, it only requires one buffer, regardless the communicator size.

the pseudo blocking equivalent algo is
```c
for (int r = 0; r < p; r++) {
    MPI_Isend(from user buffer, to rank r);
    MPI_Irecv(into a temporary, from rank r);
   MPI_Waitall(2);
   MPI_Sendrecv(from temporary buffer, into user buffer, with myself);
}
```
so starting from the current rank, or doing something similar to pairwise algo will either deadlock or require more temporary buffers.

an other option is to mimick the ```ompi_coll_base_alltoall_intra_basic_linear``` algo
(a comment in the code states it is slow and should be replaced)

yet an other option is to
```c
for (int r = 1; r < p; r++) {
    peer = myrank ^ r;
    MPI_Isend(from user buffer, to peer);
    MPI_Irecv(into a temporary, from peer);
   MPI_Waitall(2);
   MPI_Sendrecv(from temporary buffer, into user buffer, with myself);
}
```
that works fine when communicator size is a power of 2, additional steps are required otherwise.

note that in any cases, all these algos require all peers communicate with each other, and establishing all connections can take a while at scale.

any thoughts ?

**Comment by ggouaillardet** [comment]
@bosilca 

i refactored ```nbc_ialltoall*``` and mimicked ```ompi_coll_base_alltoall_intra_basic_linear```
i left the previous version for reference, i might remove it before merging

**Comment by bosilca** [comment]
No doubt that all connections would be made, but we can at least try to spread the load, and prevent all ranks from hammering the same rank. Repetitively.

If you do a version of the pairwise, where you receive from r - step and send to r + step, and then you do the inverse (receive from r + step and send to r - step), you obtain a nicely spread shift of data between the ranks.

**Comment by ggouaillardet** [comment]
@bosilca i just pushed my latest changes (i realized i pushed none of them yesterday)

If i implement the pairwise version you describe, that basically means i have to allocate and copy about half the user buffer, and this is what i want to avoid, for scalability reason.

to keep it simple, let's consider ```MPI_Ialltoall``` of n ```MPI_BYTE``` on a communicator of size ```p```
the data to be transferred is ```n * (p-1)``` bytes
my initial implementation allocates a temporary buffer of ```n``` bytes
the pairwise version requires a temporary buffer of ```n * p / 2``` bytes

i finally implemented a "xor-based" version for ```MPI_IN_PLACE``` and left other and unused versions for reference

**Comment by bosilca** [comment]
@ggouaillardet you would have to allocate only the largest buffer sent or received. Still pretty scalable.

Let's take a case where at step i a rank will exchange data with (r+i and r-i). This is divided in 2 parts send to r+i and receive from r-i (in a temporary), and then send to r-i and receive from r+i (in the real position because the data has been already sent to r+i right before). Then it is enough to copy the temporary into the location of the r-i and the step is done in place.

**Comment by ggouaillardet** [comment]
@bosilca that is clever and i will implement it
thanks for the guidance !

**Comment by ggouaillardet** [comment]
@bosilca this PR should be ready for primetime now,
would you mind having a look at it first ?

**Pull request merged**
