### PR TITLE
opal/list: Fix the bug in function opal_list_insert

### PR DESCRIPTION
**Pull request by jywangx**
related to #11058 

Fix the bug that calls to `opal_list_insert()` with `idx=0` will make `list->opal_list_length` increase twice.

Signed-off-by: Jinyuan Wang [wangjingyuan@mail.nwpu.edu.cn](wangjingyuan@mail.nwpu.edu.cn)

### CODE REVIEW

**Comment by jywangx** [comment]
> Can one of the admins verify this patch?
yes

**Review by jsquyres — CHANGES_REQUESTED** [review]
@jywangx In https://github.com/open-mpi/ompi/pull/11059#issuecomment-1312215350, @bosilca makes a good point: we don't use this function anywhere. A better solution might be to remove it. Could you update this PR?  Thanks!

**Comment by jywangx** [comment]
> @jywangx In [#11059 (comment)](https://github.com/open-mpi/ompi/pull/11059#issuecomment-1312215350), @bosilca makes a good point: we don't use this function anywhere. A better solution might be to remove it. Could you update this PR? Thanks!

Oh I see, so you mean remove the function `opal_list_insert()` and calls in `test/`?

**Review by jsquyres — APPROVED** [review]
Excellent -- thank you!

@bosilca Are you good with this?

**Review by bosilca — APPROVED** [review]

**Comment by jsquyres** [comment]
Thank you @jywangx.  Can you cherry-pick this fix to the v5.0.x branch as well? See the https://docs.open-mpi.org/en/v5.0.x/developers/git-github.html#git-branch-scheme and search in there for "cherry pick" for how we require a cherry pick notice in the commit message.  Thanks!

**Comment by jywangx** [comment]
> Thank you @jywangx. Can you cherry-pick this fix to the v5.0.x branch as well? See the https://docs.open-mpi.org/en/v5.0.x/developers/git-github.html#git-branch-scheme and search in there for "cherry pick" for how we require a cherry pick notice in the commit message. Thanks!

Is this the right way to go?
#11072

**Comment by jsquyres** [comment]
> Is this the right way to go? #11072

Perfect -- thank you!

**Pull request merged**
