### PR TITLE
v2.x: configure: add the --disable-io-ompio configure option

### PR DESCRIPTION
**Pull request by ggouaillardet**
--disable-io-ompio is a shortcut that disable the following
frameworks and components
- fbtl
- fcoll
- sharedfp
- common/ompio
- io/ompio

Fixes open-mpi/ompi#1934

(back-ported from commit 6b57b77ecb7f4ceee8e5d5da72e96d7692975bb5)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
quite some stuff is missing from ```README```

i did a copy/paste of ```configure --help``` and here is the patch.
if the wording is good for you, i will commit into master and add it into the ```v2``` branches

```patch
diff --git a/README b/README
index 8c6a9b9..2d2d76b 100644
--- a/README
+++ b/README
@@ -1240,12 +1240,24 @@ MPI FUNCTIONALITY
 
   See "Open MPI API Extensions", below, for more details.
 
+--disable-mpi-io
+  Disable built-in support for MPI-2 I/O, likely because an externally-provided
+  MPI I/O package will be used. Default is to use the internal framework
+  system that uses the ompio component and a specially modified version of ROMIO
+  that fits inside the romio314 component
+
+--disable-io-romio
+  Disable the ROMIO MPI-IO component
+
 --with-io-romio-flags=flags
   Pass flags to the ROMIO distribution configuration script.  This
   option is usually only necessary to pass
   parallel-filesystem-specific preprocessor/compiler/linker flags back
   to the ROMIO system.
 
+--disable-io-ompio
+  Disable the ompio ROM-IO component
+ 
 --enable-sparse-groups
   Enable the usage of sparse groups. This would save memory
   significantly especially if you are creating large
```

**Comment by edgargabriel** [comment]
Can you please also change the line that says "Disable the ompio ROM-IO component'" to "Disable the ompio MPI-IO component"?

**Comment by ggouaillardet** [comment]
good catch @edgargabriel 

the updated patch is below

```patch
diff --git a/README b/README
index 8c6a9b9..eb7e36b 100644
--- a/README
+++ b/README
@@ -1240,12 +1240,24 @@ MPI FUNCTIONALITY
 
   See "Open MPI API Extensions", below, for more details.
 
+--disable-mpi-io
+  Disable built-in support for MPI-2 I/O, likely because an externally-provided
+  MPI I/O package will be used. Default is to use the internal framework
+  system that uses the ompio component and a specially modified version of ROMIO
+  that fits inside the romio314 component
+
+--disable-io-romio
+  Disable the ROMIO MPI-IO component
+
 --with-io-romio-flags=flags
   Pass flags to the ROMIO distribution configuration script.  This
   option is usually only necessary to pass
   parallel-filesystem-specific preprocessor/compiler/linker flags back
   to the ROMIO system.
 
+--disable-io-ompio
+  Disable the ompio MPI-IO component
+ 
 --enable-sparse-groups
   Enable the usage of sparse groups. This would save memory
   significantly especially if you are creating large
diff --git a/config/ompi_configure_options.m4 b/config/ompi_configure_options.m4
index 01fdff4..3301df0 100644
--- a/config/ompi_configure_options.m4
+++ b/config/ompi_configure_options.m4
@@ -265,7 +265,7 @@ AC_ARG_ENABLE([mpi-io],
 
 AC_ARG_ENABLE([io-ompio],
     [AC_HELP_STRING([--disable-io-ompio],
-        [Disable the ompio ROM-IO component])])
+        [Disable the ompio MPI-IO component])])
 
 ])dnl
 
```

**Comment by jsquyres** [comment]
One last comment: I'd remove the phrase "that fits inside the romio314 component", because we'll never remember to update that when we update the ROMIO component.  😄

**Comment by jsquyres** [comment]
@ggouaillardet Do you have an ETA for this one, perchance?

**Comment by ggouaillardet** [comment]
Oops, will do tomorrow !

**Comment by ggouaillardet** [comment]
@jsquyres i pushed the change and updated the PR

**Comment by jsquyres** [comment]
@ggouaillardet Looks good now.  Can you rebase on top of the travis OS X fix?

**Comment by ggouaillardet** [comment]
@jsquyres done !

**Comment by jsquyres** [comment]
@hppritcha This is good to go.

**Pull request merged**
