### PR TITLE
oshmem: updated API oshmem examples to OSHMEM 1.3

### PR DESCRIPTION
**Pull request by karasevb**
This PR addresses the issue described in #2164

### CODE REVIEW

**Comment by karasevb** [comment]
@jsquyres @rhc54 please review

**Comment by jsquyres** [comment]
@karasevb @artpol84 @jladd-mlnx @miked-mellanox This is the same error we've seen out of the Mellanox jenkins before -- it implies that one Jenkins job is adversely affecting another.

bot:mellanox:retest

**Comment by jsquyres** [comment]
@karasevb Github pro tip: if you put the string "Fixes #2164" in your commit message, it will automatically close that issue when this PR is merged.

**Comment by karasevb** [comment]
@jsquyres Thanks for the tip

**Pull request merged**
