### PR TITLE
openib btl: remove BTL_OPENIB_FAILOVER_ENABLED code

### PR DESCRIPTION
**Pull request by larrystevenwise**
Remove BTL_OPENIB_FAILOVER_ENABLED code in the openib btl source.

Remove the failover-specific files from the openib btl.

Update the openib/Makefile.am accordingly.

Remove the -enable-openib-failover config logic.

Signed-off-by: Steve Wise <swise@opengridcomputing.com>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by larrystevenwise** [comment]
why are there 3 lanl-ompi bots?  Are 3 better than 1? :-)

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/1790434e76f9b82baf999371637948bc

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by hppritcha** [comment]
add to whitelist
there are three lanl bot tests for three different jenkins projects.
you're not on the ompi whitelist, ask jeff to be put on it

**Comment by jsquyres** [comment]
What whitelist are you referring to?  Can't we just build all PRs?

**Comment by hppritcha** [comment]
does Larry have write permissions on open-mpi/ompi repo?

**Comment by jsquyres** [comment]
He's an occasional contributor, so we haven't given him write perms.

We don't get DDOSed on PRs; I think it's fine to allow building all PRs, even if they're not in the org / don't have write perms.

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
