### PR TITLE
Fix libevent / hwloc includedir --with-devel-headers stuff

### PR DESCRIPTION
**Pull request by jsquyres**
@rhc54 Does this fix your problem?

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
@jsquyres Not quite correct - I got things to work correctly with the attached patch, both for the OMPI master and my ORCM branch

[xfer.txt](https://github.com/open-mpi/ompi/files/12125/xfer.txt)

**Comment by jsquyres** [comment]
@rhc54 Ah, I had a typo in the hwloc configure.m4 - now fixed.

It isn't necessary to move up the opalincludedir stuff in configure.ac.

Could you try again?

**Comment by rhc54** [comment]
@jsquyres I agree about the configure.ac change - I had just tried it and didn't reset it before making the diff. I'll give this version a try.

**Comment by jsquyres** [comment]
@rhc Doh!  I missed that fix.  Will do that now...

**Comment by jsquyres** [comment]
@rhc54 Ok, new commit pushed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@hppritcha Any idea why the Cray XC jenkins keeps running into the "can't find a hash to test" bug?

**Comment by rhc54** [comment]
:+1:  thanks!

**Pull request merged**
