### PR TITLE
Fix the isolated pmix component. Cleanup the ess/singleton component …

### PR DESCRIPTION
**Pull request by rhc54**
…- we shouldn't be automatically discovering the local topology as that is now done on-demand.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
@jjhursey What gives with the IBM Jenkins?

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
I'm seeing an intermittent DNS issue on those machines. Jenkins is falling over because it cannot resolve `github.com` 😢  But not always. I've sent a note to the admin to see if they can figure it out.

**Pull request merged**
