### PR TITLE
oob_tcp: fix peer->state wrong check

### PR DESCRIPTION
**Pull request by federeghe**
Hi! I think I have found a small bug in process_ping function, see the commit.

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca The TCP BTL is your baby -- can you have a look?

**Comment by jsquyres** [comment]
@bosilca Apparently, I can't read.  Disregard my prior comment.  :-)

@rhc54 The OOB TCP is your baby -- can you have a look?

**Comment by rhc54** [comment]
@federeghe I don't think the reported failure has anything to do with this change as the code path being modified isn't one that is used in OMPI today. It only gets executed if we were to "ping" another peer via OOB, which we don't do.

@miked-mellanox Can you confirm what happened with the test? Can we get a line number where it failed?

**Comment by rhc54** [comment]
bot:retest

**Pull request merged**
