### PR TITLE
lanl-ci: sync v5.0.x yml file with main

### PR DESCRIPTION
**Pull request by hppritcha**
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
(cherry picked from commit 79844c24b554f981971aeebcc9c4b9213b06af04)

(cherry picked from commit 82847313246513d1bfc05e287a90855ccc7ba359)

(cherry picked from commit 86fa54691d95d4ce648767e0203b3c62a190ce9e)

(cherry picked from commit ef07de608eb81f7a80f3e35984827ca12e3542fe)

(cherry picked from commit fb1718569b3b62e58272545fe68eeac60366fe28)

(cherry picked from commit 325913e8519bc047827fc57133e66d8b221e06e3)

(cherry picked from commit 604824442de03efe935a499a28921fcffae3184c)

(cherry picked from commit 2001b5e9bcb4f0c8e449e440c82af6b676722d52)

(cherry picked from commit 93c10cabe8e80b821779bd072ec9b5bb0eccc35b)

(cherry picked from commit 0f928634a64dbfb768763b82e7376cbc6803e533)

(cherry picked from commit b1c2244cd20b79eedb324837006f732b33604629)

(cherry picked from commit 0ccf1c17f6857e5ad0e535e7995543b60589af1b)

(cherry picked from commit c314fdfb70ac918cf7c42d58a503213201884be2)

(cherry picked from commit 6648a831bf2c2493ca88ee306a8c58a2f264e462)

(cherry picked from commit b8788cd16df29d8f62c3d683552368defcd82529)

(cherry picked from commit 0d2f45c69e2c63704c2052b60a2e67205280d5a7)

(cherry picked from commit 29fe00f7ea6e538ea53865c869bcd6fb33a1ea46)

### CODE REVIEW

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by hppritcha** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Pull request merged**
