### PR TITLE
hwloc 1.9.x updates

### PR DESCRIPTION
**Pull request by jsquyres**
Bring over all relevant commits from the open-mpi/hwloc since the hwloc v1.9.1 tag:

* Users have been running into the issue fixed by open-mpi/hwloc@790aa2e1e62be6b4f37622959de9ce3766ebc57e (e.g., @petergottesman)
* We already had most of open-mpi/hwloc@f705a23a0494a4daccc08c8ee95616147a0b971e applied
* I skipped all non-relevant commits (e.g., commits to docs/, utils/, etc. -- i.e., directories of the hwloc tree that we do not embed in Open MPI)

Specifically, the "Lhwloc1" duplicate symbol issue is real/was reported by @petergottesman recently.  @bgoglin reports that this issue was fixed after hwloc v1.9.1, but we never picked it up here in OMPI (there is no hwloc v1.9.2, which is likely why we didn't previously just wholesale upgrade our embedded hwloc).  Googling around shows that other people have run into this "Lhwloc1" dup symbol issue and gone back to Open MPI 1.6.x in frustration.  :-(

On master, we can fix this by upgrading to hwloc v1.10.1, but that's not desirable in the Open MPI v1.8 series.  In OMPI v1.8.x, it's more desirable to simply grab all (relevant) hwloc post-v1.9.1 commits to get the most recent bug fixes (including fixing the "Lhwloc1" issue).

This PR is doing just that: getting all (relevant) hwloc post-v1.9.1 commits.  We can then verify this on OMPI master, and then bring them over to the OMPI v1.8 branch.  Once OMPI v1.8.x. is verified, we should probably upgrade OMPI master to hwloc v1.10.1.

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 913 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_385/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_385/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_385/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by bgoglin** [comment]
You may ignore these:
* hwloc: configure: fix the check for X11/Xutil.h …  (only needed for lstopo)
* hwloc: API: clearly state that os_index isn't unique while logical_index (API change only)
* hwloc: synthetic: Misc levels are not allowed in the synthetic description (OMPI doesn't use synthetic topos)

And you could add this one but it likely doesn't matter for OMPI:
commit e7b192b101237fda8ca006fb031f0c1dc74e2e91
Author: Brice Goglin <Brice.Goglin@inria.fr>
Date:   Tue Feb 17 16:09:57 2015 +0100
    pci: fix bridge depth

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/385/
Test PASSed.

**Comment by jsquyres** [comment]
@bgoglin I actually grabbed *all* post-v1.9.1 commits that would apply; I skipped those that would not apply (e.g., those in util/, docs/, etc.).

It looks like open-mpi/hwloc@e7b192b101237fda8ca006fb031f0c1dc74e2e91 had files in just tests/ and utils/, neither of which are in the OMPI tree.

**Comment by jsquyres** [comment]
@bgoglin Bah - clicked "comment" too soon.

I grabbed *all* post-v1.9.1 commits, regardless of whether they looked useful or not.  I.e., it's (slightly) easier to say "we took all commits up to open-mpi/hwloc@4e23b12, rather than to say "we cherry picked commits X, Y, Z."

**Comment by bgoglin** [comment]
OK
open-mpi/hwloc@e7b192b has changes in src/pci-common.c too.

**Comment by jsquyres** [comment]
Gah!  You're right -- my eyes looked just at the "conflicts" list, not the actual list of files.  Thanks -- I'll add it in the sequence.

**Comment by mellanox-github** [comment]
* Coverity found 913 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_386/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_386/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_386/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/386/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 913 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_387/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_387/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_387/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/387/
Test PASSed.

**Pull request merged**
