### PR TITLE
autogen.pl: ignore all excluded components

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
Makes sense to me. But I'll hold off merging until someone more familiar looks.

**Review by rhc54 — APPROVED** [review]
Took me a while to figure out what problem this actually fixed, but it looks correct. Would be nice if the commit explained the problem.

If multiple components in a framework were excluded, then only the first one in the list was being checked - which means that only the first one in the list was actually being excluded. All others were missed by the current code. This change actually searches the entire list of excluded components to see if the one we found matches any of the list members.

**Comment by ggouaillardet** [comment]
Thanks @rhc54!

i copy/pasted the commit message from openpmix/prrte#1079

**Review by jsquyres — APPROVED** [review]

**Comment by awlauria** [comment]
v5.0.x: https://github.com/open-mpi/ompi/pull/9355

**Pull request merged**
