### PR TITLE
v5.0.x: datatype fixes port

### PR DESCRIPTION
**Pull request by awlauria**

### CODE REVIEW

**Comment by gpaulsen** [comment]
This has the fixes needed for v5.0.x for #8466.

**Comment by bosilca** [comment]
This is mostly ready, but before merging I would wait until we figure out what's the root cause in #8856.

**Comment by awlauria** [comment]
I added the two additional commits (2c509be and 2c509be) since they are a direct result of the datatype changes, and they should go in together.

**Comment by awlauria** [comment]
bot:aws:retest

**Comment by awlauria** [comment]
@bosilca should we merge this as it's already in master and v4.1? We can always bring any new changes over, unless you think we may want to omit some of these commits. We're just trying to keep v5 up-to-dateish with master right now.

**Review by bosilca — APPROVED** [review]

**Pull request merged**
