### PR TITLE
romio Type_create_darray (mirroring previous Type_create_darray fix)

### PR DESCRIPTION
**Pull request by markalle**
The romio code for Type_create_darray had the same bug I fixed a while back in the main MPI lib's Type_create_darray.  Basically the cyclic() function is the main function that's considered right, and block() is an optimization that left out a necessary piece of code to resize the datatype it created.

For what it's worth I took the conservative approach and made block() match cyclic(). I like the code a bit better in the main MPI library (ompi_datatype_create_darray.c) that uses opal_datatype_resize() where the implementation of cyclic() matches the current MPI standard's description. The romio code uses LB/UB and Type_struct, and I'm presuming that matched the older MPI standard's description of Type_create_darray.

Anyway I didn't change to the new style, I just made block() match cyclic() in the romio code.

I don't have a complete testcase handy, but can make one if needed. Basically it involves creating a new datatype with Type_create_darray (mixing BLOCK and CYCLIC) and then
```
    MPI_File_set_view(fd, 0, MPI_INT, newtype, "native", MPI_INFO_NULL);
    MPI_File_write(fd, sbuf, count, MPI_INT, MPI_STATUS_IGNORE);
```
and then you can read from the file or hexdump it etc and the data will be written in the wrong locations.

### CODE REVIEW

**Comment by markalle** [comment]
This is the previous fix for the Type_create_darray in the main MPI lib:
https://github.com/open-mpi/ompi/pull/3672

**Comment by markalle** [comment]
retest

**Comment by markalle** [comment]
bot:retest

**Comment by markalle** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by markalle** [comment]
And here's a testcase that can be used to see the original bug and that this fixes it:
    https://gist.github.com/markalle/940de93d64fd779e304ee124855b8e6a
mpicc -o x darray_bug_romio.c
mpirun -mca io romio321 -np 1 ./x

**Comment by AboorvaDevarajan** [comment]
Can one of the admins verify this patch?

**Comment by gpaulsen** [comment]
@markalle This PR is really old.  Is it still needed on master?  Can we just close this?
I'm adding WorkInProgress label until we can verify if this PR is still desirable.

**Comment by awlauria** [comment]
@markalle do we still want this? Status?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
Hey @markalle Is this PR still needed?

**Comment by markalle** [comment]
I repushed.  Over in Spectrum MPI I had made several related fixes toward syncing up the Count and Flatten functions, but that's been a loosing battle that keeps re-breaking.  So in this version I'm taking the simpler fix where Count is only used to allocate the arrays that are filled by Flatten, and even then I put an extra safety valve to resize those arrays if needed (I don't think that code ever gets activated though).  Anyway the final flat->count is then reset based on the *curr_index which I think is the best book-keeping variable for keeping track of the count since it was used every time data is written into those arrays

**Comment by rhc54** [comment]
As I stated on the user mailing list, this PR should _not_ be committed. It modifies an imported software package without a corresponding upstream fix. This leaves the OMPI community responsible for maintaining ROMIO - a position we cannot absorb.

This PR should instead be filed against ROMIO itself, and then monitored for acceptance so we can update OMPI once ROMIO is updated.

**Comment by gpaulsen** [comment]
Mark has submitted a ROMIO PR upstream here: https://github.com/pmodels/mpich/pull/4943
we still need to go through their contributor process, so it may take some time.

**Comment by markalle** [comment]
So what about OMPI 4.0.x? That presumably won't get a romio update, so once 4943 goes into mpich I should plan to to merge that into 4.0.x?

**Comment by gpaulsen** [comment]
Hopefully once the fix gets into romio, they will spin a bugfix release on whatever branch v4.0.x's ROMIO is based on and then we can pull that into v4.0.x  But I'm not ceratin of the details or the branch mappings between projects.

**Comment by markalle** [comment]
I'll close this one.  The overall status of getting things into MPICH and getting them back from mpich into our branches is far from done, but this one is at least fixed in MPICH master so it can be closed here.  And the job of making sure we have a merge from MPICH master of important fixes back to our various branches is ongoing.

**Pull request closed without merging**
