### PR TITLE
COMMON/UCX: suppressed coverity warnings - v4.0

### PR DESCRIPTION
**Pull request by hoopoepg**
COMMON/UCX: suppressed coverity warnings  …
- suppressed coverity warnings - added log messages on failed calls

backport from https://github.com/open-mpi/ompi/pull/5934

Signed-off-by: Sergey Oblomov <sergeyo@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
@hoopoepg can you re-push the commit? looks like because of github issues some checks did not run

**Comment by yosefe** [comment]
@gpaulsen ok to merge?

**Comment by gpaulsen** [comment]
@yosefe we're announcing v4.0.0rc5 today, and hopefully release v4.0.0 within a week.
Since this PR isn't critical we've pushed it back to the v4.0.1 milestone which should begin soon after we release v4.0.0

**Comment by yosefe** [comment]
@gpaulsen ok

**Comment by hoopoepg** [comment]
merged via https://github.com/open-mpi/ompi/pull/5995

**Pull request closed without merging**
