### PR TITLE
pml_ucx: fix uninitialized field req_status->_cancelled.

### PR DESCRIPTION
**Pull request by yosefe**
#2327

Signed-off-by: Yossi Itigin <yosefe@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
@jladd-mlnx @miked-mellanox

**Comment by miked-mellanox** [comment]
:+1:

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/60a76edc4b80fe7fedc3f899d8bfbd01

**Comment by jladd-mlnx** [comment]
Looks good. @rhc54 Please merge so that we may cover under our MTT.

**Comment by jladd-mlnx** [comment]
@jjhursey Are these IBM failures false alarms?

**Comment by jjhursey** [comment]
IBM CI failure due to internal system issue that is still in the process of being resolved this morning. Disregard the IBM CI failures for now.

**Comment by jladd-mlnx** [comment]
@rhc54 Please merge so that we can cover under our nightly MTT.

**Pull request merged**
