### PR TITLE
v5: MPI 4: Add MPI_COMM_TYPE_HW_UNGUIDED and MPI_COMM_TYPE_HW_GUIDED

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
This cherry-picks:
 * PR #10630
 * PR #10681
 * PR #10702 (I'll take this PR out of draft once 10702 is merged - assuming no changes)

**Comment by dalcinl** [comment]
@jjhursey Just FYI, all is good on mpi4py's side [[link]](https://github.com/mpi4py/mpi4py-testing/runs/7978001200?check_suite_focus=true)

**Comment by jjhursey** [comment]
The `main` PR #10702 has been merged. I updated this PR with one additional commit from that PR. It is ready for review.

**Comment by jjhursey** [comment]
FYI: I just pushed on a missing help message PR #10778 from `main`

**Review by awlauria — APPROVED** [review]

**Pull request merged**
