### PR TITLE
v4.0.x: mpi: mark MPI_COMBINER_{HVECTOR,HINDEXED,STRUCT}_INTEGER removed

### PR DESCRIPTION
**Pull request by ggouaillardet**
unless configure'd with --enable-mpi1-compatibility

This is a one-off commit for the v4.0.x branch since these symbols were
simply removed from master.

Thanks Lisandro Dalcin for reporting this.

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by jsquyres** [comment]
FYI @dalcinl

**Comment by ggouaillardet** [comment]
@jsquyres I made the requested changes. The CI failure on Cray is unrelated to this PR.

**Comment by ggouaillardet** [comment]
:bot:cray:retest

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by jsquyres** [comment]
@ggouaillardet Ok to remove the WIP label now?

**Comment by ggouaillardet** [comment]
@jsquyres I just removed the WIP label, this PR is now ready for primetime

**Pull request merged**
