### PR TITLE
new fbtl using direct I/O

### PR DESCRIPTION
**Pull request by edgargabriel**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@edgargabriel Looks like Travis actually found an error here in the OS X build.  You can see the build error at the bottom of the full / raw build log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/101080685/log.txt

**Comment by edgargabriel** [comment]
hm, the error that I see does not come from directio fbtl, but from 
somewhere else. The directio seems to compile correctly, and 
monitoring_prof seems to fail.
Nevertheless, I am still working on the directio component, have a 
couple of other smaller items, will not merge it yet.


On 1/8/2016 10:05 AM, Jeff Squyres wrote:
>
> @edgargabriel <https://github.com/edgargabriel> Looks like Travis 
> actually found an error here in the OS X build. You can see the build 
> error at the bottom of the full / raw build log: 
> https://s3.amazonaws.com/archive.travis-ci.org/jobs/101080685/log.txt
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/open-mpi/ompi/pull/1290#issuecomment-170040768>.
>

-- 
Edgar Gabriel
Associate Professor
Parallel Software Technologies Lab      http://pstl.cs.uh.edu
Department of Computer Science          University of Houston
Philip G. Hoffman Hall, Room 524        Houston, TX-77204, USA
Tel: +1 (713) 743-3857                  Fax: +1 (713) 743-3335
--

**Comment by edgargabriel** [comment]
Not merging the branch, the performance of the direct I/O component is disappointing. Keeping the code in the branch however around.

**Pull request closed without merging**
