### PR TITLE
Openib updates

### PR DESCRIPTION
**Pull request by hjelmn**
Fix a couple of outstanding bugs and cleanup send/sendi code.

@miked-mellanox Please take a look.

### CODE REVIEW

**Comment by hjelmn** [comment]
I should also mention that this also fixes a long outstanding bug that occurs when the openib btl attempts to coalesce fragments but runs out of descriptors. Looking for the bug id now.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/160/

**Build Log**
*last 50 lines*

 ```
[...truncated 6557 lines...]
Making install in mca/btl/openib
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/openib'
  CC       btl_openib.lo
  CC       btl_openib_component.lo
  CC       btl_openib_endpoint.lo
  CC       btl_openib_frag.lo
  CC       btl_openib_proc.lo
  LEX      btl_openib_lex.c
  CC       btl_openib_mca.lo
  CC       btl_openib_ini.lo
  CC       btl_openib_async.lo
  CC       btl_openib_xrc.lo
  CC       btl_openib_fd.lo
  CC       btl_openib_ip.lo
  CC       connect/btl_openib_connect_base.lo
  CC       connect/btl_openib_connect_empty.lo
  CC       connect/btl_openib_connect_rdmacm.lo
  CC       connect/btl_openib_connect_udcm.lo
  CC       connect/btl_openib_connect_sl.lo
  CC       btl_openib_lex.lo
btl_openib_endpoint.c: In function 'mca_btl_openib_endpoint_post_send':
btl_openib_endpoint.c:89: error: 'mca_btl_base_descriptor_t' has no member named 'des_segments'
btl_openib_endpoint.c: In function 'mca_btl_openib_endpoint_destruct':
btl_openib_endpoint.c:392: warning: 'ibv_unreg_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:204)
btl_openib.c: In function 'create_srq':
btl_openib.c:328: warning: 'ibv_create_xrc_srq' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:89)
btl_openib_xrc.c: In function 'mca_btl_openib_open_xrc_domain':
btl_openib_xrc.c:65: warning: 'ibv_open_xrc_domain' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:72)
btl_openib_xrc.c: In function 'mca_btl_openib_close_xrc_domain':
btl_openib_xrc.c:83: warning: 'ibv_close_xrc_domain' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:102)
btl_openib_async.c: In function 'mca_btl_openib_load_apm_xrc_rcv':
btl_openib_async.c:663: warning: 'ibv_query_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:168)
btl_openib_async.c:680: warning: 'ibv_modify_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:152)
make[2]: *** [btl_openib_endpoint.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
connect/btl_openib_connect_udcm.c: In function 'udcm_xrc_recv_qp_connect':
connect/btl_openib_connect_udcm.c:2491: warning: 'ibv_reg_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:185)
connect/btl_openib_connect_udcm.c: In function 'udcm_xrc_recv_qp_create':
connect/btl_openib_connect_udcm.c:2516: warning: 'ibv_create_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:126)
connect/btl_openib_connect_udcm.c:2528: warning: 'ibv_modify_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:152)
connect/btl_openib_connect_udcm.c:2569: warning: 'ibv_modify_xrc_rcv_qp' is deprecated (declared at /usr/include/infiniband/ofa_verbs.h:152)
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal/mca/btl/openib'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/opal'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by hjelmn** [comment]
Hmm, looks like I missed something pulling this out of my btl branch. Please ignore until I get this fixed.

**Comment by hjelmn** [comment]
Should be good now.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/164/
Test PASSed.

**Comment by hjelmn** [comment]
@miked-mellanox Please let me know what you think of the changes.

**Comment by hjelmn** [comment]
@jladd-mlnx Does Mellanox have an opinion on this pull request? If not I will go ahead and merge it.

**Comment by jladd-mlnx** [comment]
@hjelmn I was only waiting to see what the issue was that @abouteiller was reporting regarding message coalescing. Seems like your patch does indeed resolve his issue. I've reviewed you code and it looks fine. With regard to re-enabling message coalescing in 1.8.x; I think that we are of the opinion that we really don't care one way or the other. Maybe @hppritcha or @miked-mellanox have a burning desire to see it re-enabled, but @bureddy and myself do not.

**Comment by hppritcha** [comment]
I vote against re-enabling message coalescing in 1.8.X.

**Comment by rhc54** [comment]
Regardless of the "vote", I'm not going to re-enable it in the 1.8 series as it is of little (if any) value, and caused trouble.

**Comment by abouteiller** [comment]
Nathan, 

remember that I set the coalescing MCA param to default to “false” yesterday. If you feel coalescing should be on by default, do not forget to revert that change. 

Have fun, 
Aurelien 
--
          ~~~ Aurélien Bouteiller, Ph.D. ~~~
             ~ Research Scientist @ ICL ~
The University of Tennessee, Innovative Computing Laboratory
1122 Volunteer Blvd, suite 309, Knoxville, TN 37996
tel: +1 (865) 974-9375       fax: +1 (865) 974-8296
https://icl.cs.utk.edu/~bouteill/




> Le 15 janv. 2015 à 16:05, Nathan Hjelm <notifications@github.com> a écrit :
> 
> Merged #332 <https://github.com/open-mpi/ompi/pull/332>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/open-mpi/ompi/pull/332#event-219699730>.
>

**Pull request merged**
