### PR TITLE
v2.x: disable hwloc CUDA support when relevant

### PR DESCRIPTION
**Pull request by jsquyres**
Refs #4248.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:xl:retest

**Comment by jsquyres** [comment]
Working through issues identified on #4251.

**Comment by jsquyres** [comment]
@ggouaillardet New commit added to this v2.x PR.

**Comment by jsquyres** [comment]
@hppritcha Updated this v2.x PR.  Can you review?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest

**Comment by hppritcha** [comment]
had to kill off armv8 testing.
bot:lanl:retest

**Pull request merged**
