### PR TITLE
v2.1.x: Use malloc instead of posix_memalign for small (<= sizeof(void *)) alignments

### PR DESCRIPTION
**Pull request by hjelmn**
See #4564 

FYI @benmenadue

### CODE REVIEW

**Comment by jsquyres** [comment]
See https://github.com/open-mpi/ompi/pull/4573#pullrequestreview-81588946

**Comment by hppritcha** [comment]
@shamisp 
Could you check UCX setup on ThunderX1?
```
make[2]: Entering directory '/var/lib/jenkins/ompi-master/workspace/open-mpi.build.platforms/Platform/ARMv8/src/ompi/mca/pml/ucx'
  CC       pml_ucx_request.lo
  CC       pml_ucx_datatype.lo
  CC       pml_ucx.lo
  CC       pml_ucx_component.lo
  CCLD     mca_pml_ucx.la
libtool:   error: require no space between '-L' and '-lrt'
Makefile:1755: recipe for target 'mca_pml_ucx.la' failed
make[2]: *** [mca_pml_ucx.la] Error 1
make[2]: Leaving directory '/var/lib/jenkins/ompi-master/workspace/open-mpi.build.platforms/Platform/ARMv8/src/ompi/mca/pml/ucx'
Makefile:3347: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/jenkins/ompi-master/workspace/open-mpi.build.platforms/Platform/ARMv8/src/ompi'
Makefile:1807: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by shamisp** [comment]
odd. Where is it looking by default ?

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
@shamisp Any news on the ARM testing problem with UCX?

**Comment by jsquyres** [comment]
bot:ompi:retest

**Pull request merged**
