### PR TITLE
Retrieve the modex of all jobs during accept/connect

### LINKED ISSUE #11724: MPI_Intercomm_merge not working after second ULFM shrink.
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v5.0.x branch, hash 907350a

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Git clone, compiled with ../configure --with-ft=ulfm

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

 f34a7ce21e7a89aba44fa396eb84de1bebde3ad3 3rd-party/openpmix (v4.2.4rc1-16-gf34a7ce2)
 c4925aa5cc03159da04b94dcda9f559329150724 3rd-party/prrte (v3.0.1rc2-17-gc4925aa5cc)
 c1cfc910d92af43f8c27807a9a84c9c13f4fbc65 config/oac (heads/main)

### Please describe the system on which you are running

* Operating system/version: Red Hat 8.6
* Computer hardware: Arm Cavium ThunderX2
* Network type: single node

-----------------------------

## Details of the problem

The following code, which uses ULFM functionalities to recover from two faults, hangs in a deadlock.
```C
#include <assert.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include "mpi.h"

#include "mpi-ext.h"

#define FIRST_FAIL 1
#define SECOND_FAIL 0

int main(int argc, char** argv)
{
    MPI_Init(&argc, &argv);
    MPI_Comm comm, parent, temp, inter, inter2, unordered;
    int rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_get_parent(&parent);
    int len, rc, error;
    char errstr[MPI_MAX_ERROR_STRING];
    if (parent == MPI_COMM_NULL)
    {
        MPI_Comm_dup(MPI_COMM_WORLD, &comm);
        MPI_Comm_set_errhandler(comm, MPI_ERRORS_RETURN);
        MPI_Barrier(comm);
        printf("%d, after first barrier\n", rank);
        if (rank == FIRST_FAIL)
            raise(SIGINT);
        rc = MPI_Barrier(comm);

        MPI_Error_string(rc, errstr, &len);
        printf("%d: Second barrier: %s\n", rank, errstr);
        MPIX_Comm_shrink(comm, &temp);
        MPI_Comm_free(&comm);
        char** spawn_argv = (char**)malloc(sizeof(char*) * 2);
        spawn_argv[0] = (char*)malloc(sizeof(char) * 2);
        sprintf(spawn_argv[0], "%d", FIRST_FAIL);
        spawn_argv[1] = NULL;
        MPI_Comm_spawn(argv[0], spawn_argv, 1, MPI_INFO_NULL, 0, temp, &inter, &error);
        MPI_Intercomm_merge(inter, 0, &unordered);
        MPI_Comm_split(unordered, 0, rank, &comm);
        MPI_Comm_free(&unordered);
        MPI_Comm_set_errhandler(comm, MPI_ERRORS_RETURN);
        MPI_Barrier(comm);
        printf("%d, after second barrier\n", rank);

        if (rank == SECOND_FAIL)
            raise(SIGINT);
        rc = MPI_Barrier(comm);
        MPI_Error_string(rc, errstr, &len);
        printf("%d: Last barrier: %s\n", rank, errstr);
        MPIX_Comm_shrink(comm, &temp);
        MPI_Comm_free(&comm);
        sprintf(spawn_argv[0], "%d", SECOND_FAIL);
        MPI_Comm_spawn(argv[0], spawn_argv, 1, MPI_INFO_NULL, 0, temp, &inter2, &error);
        MPI_Intercomm_merge(inter2, 0, &unordered);
        MPI_Comm_split(unordered, 0, rank, &comm);
        MPI_Comm_free(&unordered);
        MPI_Comm_set_errhandler(comm, MPI_ERRORS_RETURN);
        MPI_Barrier(comm);
        printf("%d, after last barrier\n", rank);
    }
    else
    {
        rank = atoi(argv[1]);
        printf("%d: respawned\n", rank);
        if (rank == FIRST_FAIL)
        {
            MPI_Intercomm_merge(parent, 0, &unordered);
            MPI_Comm_split(unordered, 0, rank, &comm);
            MPI_Comm_free(&unordered);
            MPI_Comm_set_errhandler(comm, MPI_ERRORS_RETURN);
            MPI_Barrier(comm);
            printf("%d, after second barrier\n", rank);

            rc = MPI_Barrier(comm);
            MPI_Error_string(rc, errstr, &len);
            printf("%d: Last barrier: %s\n", rank, errstr);
            MPIX_Comm_shrink(comm, &temp);
            MPI_Comm_free(&comm);
            char** spawn_argv = (char**)malloc(sizeof(char*) * 2);
            spawn_argv[0] = (char*)malloc(sizeof(char) * 2);
            sprintf(spawn_argv[0], "%d", SECOND_FAIL);
            spawn_argv[1] = NULL;
            MPI_Comm_spawn(argv[0], spawn_argv, 1, MPI_INFO_NULL, 0, temp, &inter2, &error);
            MPI_Intercomm_merge(inter2, 0, &unordered);
            MPI_Comm_split(unordered, 0, rank, &comm);
            MPI_Comm_free(&unordered);
            MPI_Comm_set_errhandler(comm, MPI_ERRORS_RETURN);
            MPI_Barrier(comm);
            printf("%d, after last barrier\n", rank);
        }
        else if (rank == SECOND_FAIL)
        {
            MPI_Intercomm_merge(parent, 0, &unordered);
            MPI_Comm_split(unordered, 0, rank, &comm);
            MPI_Comm_free(&unordered);
            MPI_Comm_set_errhandler(comm, MPI_ERRORS_RETURN);
            MPI_Barrier(comm);
            printf("%d, after last barrier\n", rank);
        }
    }
    MPI_Finalize();
    return 0;
}
```
In particular, a run with -np 4 --with-ft ulfm produces the following output:

```
1, after first barrier
0, after first barrier
2, after first barrier
3, after first barrier
2: Second barrier: MPI_ERR_PROC_FAILED: Process Failure
3: Second barrier: MPI_ERR_PROC_FAILED: Process Failure
0: Second barrier: MPI_ERR_PROC_FAILED: Process Failure
1: respawned
0, after second barrier
3, after second barrier
1, after second barrier
2, after second barrier
1: Last barrier: MPI_ERR_PROC_FAILED: Process Failure
2: Last barrier: MPI_ERR_PROC_FAILED: Process Failure
3: Last barrier: MPI_ERR_PROC_FAILED: Process Failure
0: respawned
```
and then terminates due to the time limit. Trying to analyse the problem a bit deeper, it seems that the MPI_Intercomm_merge between the second spawned process and all the others does not complete. The processes are spawned correctly (as shown by the "respawned" lines). Moreover, I managed to make the example work sometimes changing the ranks of the processes to fail.
I should perform an MPIX_Agree right after the barrier to be sure that all the processes see the same outcome, but they still see the same outcome as shown in the output.
Is there something wrong with my example or is it a problem with the current v5.0.x branch?
Thanks in advance

### PR DESCRIPTION
**Pull request by bosilca**
The original code was merging the local modex with the modex of the local processes on the first jobid. This lead to incorrect, and mismatched, information among processes when joining multiple jobid processes (such as on the second spawn merged).

This patch iterate over all the jobid on the list of "to connect" processes and adds their information to the local modex.

Fixes #11724.

### CODE REVIEW

**Comment by rhc54** [comment]
FWIW: I tried this patch with the reproducer provided [here](https://gist.github.com/Robyroc/482fd8e72e260bd7db75db9ad9939f74) by the original reporter, but it generated a bunch of failures for me:
```shell
$ mpirun -n 4 ./spawn
1, after first barrier
1: Second barrier: MPI_SUCCESS: no errors
0, after first barrier
0: Second barrier: MPI_SUCCESS: no errors
3, after first barrier
3: Second barrier: MPI_SUCCESS: no errors
2, after first barrier
2: Second barrier: MPI_SUCCESS: no errors
4: spawned
3, after second barrier
2, after second barrier
1, after second barrier
0, after second barrier
4, after second barrier
2: Last barrier: MPI_SUCCESS: no errors
1: Last barrier: MPI_SUCCESS: no errors
3: Last barrier: MPI_SUCCESS: no errors
0: Last barrier: MPI_SUCCESS: no errors
4: Last barrier: MPI_SUCCESS: no errors
5: spawned
3, after last barrier
1, after last barrier
2, after last barrier
0, after last barrier
5, after last barrier
4, after last barrier
[Ralphs-iMac-2][[45637,1],2][btl_tcp_endpoint.c:667:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier: got [[45637,1],0] expected [[45637,3],0]
[Ralphs-iMac-2][[45637,1],1][btl_tcp_endpoint.c:667:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier: got [[45637,1],0] expected [[45637,3],0]
[Ralphs-iMac-2][[45637,3],0][btl_tcp_proc.c:400:mca_btl_tcp_proc_create] opal_modex_recv: failed with return value=-46
[Ralphs-iMac-2][[45637,2],0][btl_tcp_proc.c:400:mca_btl_tcp_proc_create] opal_modex_recv: failed with return value=-46
[Ralphs-iMac-2.local:09882] dpm_disconnect_init: error -12 in isend to process 1
[Ralphs-iMac-2.local:09881] dpm_disconnect_init: error -12 in isend to process 1
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[45637,3],0]) is on host: Ralphs-iMac-2
  Process 2 ([[45637,1],1]) is on host: unknown
  BTLs attempted: tcp self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[Ralphs-iMac-2][[45637,2],0][btl_tcp_proc.c:400:mca_btl_tcp_proc_create] opal_modex_recv: failed with return value=-46
[Ralphs-iMac-2][[45637,3],0][btl_tcp_proc.c:400:mca_btl_tcp_proc_create] opal_modex_recv: failed with return value=-46
[Ralphs-iMac-2.local:09882] dpm_disconnect_init: error -12 in isend to process 1
[Ralphs-iMac-2.local:09882] Error in comm_disconnect_waitall
[Ralphs-iMac-2:09882] *** Process received signal ***
[Ralphs-iMac-2:09882] Signal: Segmentation fault: 11 (11)
[Ralphs-iMac-2:09882] Signal code: Address not mapped (1)
[Ralphs-iMac-2:09882] Failing at address: 0x10
[Ralphs-iMac-2:09882] *** End of error message ***
[Ralphs-iMac-2.local:09881] dpm_disconnect_init: error -12 in isend to process 1
[Ralphs-iMac-2][[45637,2],0][btl_tcp_proc.c:400:mca_btl_tcp_proc_create] opal_modex_recv: failed with return value=-46
[Ralphs-iMac-2.local:09881] dpm_disconnect_init: error -12 in isend to process 1
[Ralphs-iMac-2.local:09881] Error in comm_disconnect_waitall
[Ralphs-iMac-2:09881] *** Process received signal ***
[Ralphs-iMac-2:09881] Signal: Segmentation fault: 11 (11)
[Ralphs-iMac-2:09881] Signal code: Address not mapped (1)
[Ralphs-iMac-2:09881] Failing at address: 0x10
[Ralphs-iMac-2:09881] *** End of error message ***
5 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
--------------------------------------------------------------------------
An MPI communication peer process has unexpectedly disconnected.  This
usually indicates a failure in the peer process (e.g., a crash or
otherwise exiting without calling MPI_FINALIZE first).

Although this local MPI process will likely now behave unpredictably
(it may even hang or crash), the root cause of this problem is the
failure of the peer -- that is what you need to investigate.  For
example, there may be a core file that you can examine.  More
generally: such peer hangups are frequently caused by application bugs
or other external events.

  Local host: Ralphs-iMac-2
  Local PID:  9879
  Peer host:  Ralphs-iMac-2
--------------------------------------------------------------------------
1 more process has sent help message help-mca-bml-r2.txt / unreachable proc
1 more process has sent help message help-mpi-btl-tcp.txt / peer hung up

```

**Comment by bosilca** [comment]
@rhc54 based on the output ('after last barrier'), all the processes (including the newly spawned ones) have reached `MPI_Finalize`. The errors are related to 1) your MCA environment limits the BTL to `TCP,self`and 2) the BTL TCP not being very MAC friedly. Adding `sm` to the list of allowed BTL should fix this issue.

**Comment by bosilca** [comment]
Here is the important snippet from your output
```text
3, after last barrier
1, after last barrier
2, after last barrier
0, after last barrier
5, after last barrier
4, after last barrier
```
This shows that all the processes (4+1+1) completed the last `MPI_)Barrier` and went into `MPI_Finalize`. The fact that all processes were able to successfully complete a barrier, tells that the communication capabilities of the entire job are functional. Thus, you can safely ignore the errors, they are not related to this PR.

**Comment by Robyroc** [comment]
I cherry-picked the commit in v5.0.x branch and can confirm that it fixes the issues also on my platform. I could not make it work on the main branch due to some problems compiling PMI, but they should be out of the scope of this PR

**Comment by bosilca** [comment]
We have some internal discussions on the most efficient way to gather the modex across multiple jobs. I'll get back to this later tomorrow.

**Review by abouteiller — APPROVED** [review]

**Comment by bosilca** [comment]
We decide to move forward with this as is, and if we notice a performance impact at scale we can reassess.

**Comment by janjust** [comment]
ok great - please open up v5.0 cherry-pick

**Pull request merged**
