### PR TITLE
configury: remove the --disable-mpi-io option

### PR DESCRIPTION
**Pull request by ggouaillardet**
Fixes open-mpi/ompi#2185

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/44128fc24d3b84545dd91f503ffe4be4

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/14d6aaa19e5a0779f853141957e63667

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/56872b8a6e4819a04736383bc540bc5a

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/2746fecf92fda4d80ff1b80b23edbfc7

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/1c0802e7daeff8b5aa6889d53fdd37d0

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9a0c872727b30171ad21ea7d99139fb0

**Comment by bwbarrett** [comment]
@ggouaillardet, do you still want to push this to master?  Obviously, you'll have to rebase...

**Pull request merged**
