### PR TITLE
edited HACKING

### PR DESCRIPTION
**Pull request by davecampbell**
for #hacktoberfest

### CODE REVIEW

**Comment by jsquyres** [comment]
Hey @davecampbell: somehow you ended up with a merge commit in here.  Want to ping me in email and I can talk you through how to fix this?

**Comment by davecampbell** [comment]
i can re-do or just move on...not sure of a few steps that occurred there.

**Comment by davecampbell** [comment]
let's try this again.

**Comment by davecampbell** [comment]
sorry - took many wrong turns getting this here.
took a better route and have another PR submitted.

**Pull request closed without merging**
