### PR TITLE
Fix add-host support by including the location for procs of prior jobs when spawning new daemons.

### LINKED ISSUE #4555: OpenMPI 3.0.0 MPI_COMM_SPAWN child fails to MPI_INIT
I have a very simple code: 
master (houprg118061) spawns a slave (houprg118069) 
slave connects to master
master sends value = 500 to slave
slave adds 1
slave sends 501 back to master
master prints 501
everyone shuts down.

Code works perfectly with OpenMPI 1.6.4 and with mpich 3.2.1. However OpenMPI 3.0.0 fails. Actually even OpenMPI 3.0.0 succeeds if spawning on the same host. Spawning on remote host(s) though, fails systematically. Please do let me know if you have a cure/workaround for this. I would love to stay with OpenMPI 3.0.0 and not switch to mpich. OS is Debian 6

```
MASTER MPIINIT
MASTER houprg118061 TRies Spawn
SLAVE houprg118069 STARTS
SLAVE houprg118069 TRIES MPIINIT
[houprg118069:17124] [[42756,0],1] ORTE_ERROR_LOG: Not found in file orted/pmix/pmix_server_fence.c at line 198
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[42756,2],0]) is on host: houprg118069
  Process 2 ([[42756,1],0]) is on host: unknown!
  BTLs attempted: self tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_dpm_dyn_init() failed
  --> Returned "Unreachable" (-12) instead of "Success" (0)
--------------------------------------------------------------------------
[houprg118069:17128] *** An error occurred in MPI_Init_thread
[houprg118069:17128] *** reported by process [46912434864130,140733193388032]
[houprg118069:17128] *** on a NULL communicator
[houprg118069:17128] *** Unknown error
[houprg118069:17128] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[houprg118069:17128] ***    and potentially your MPI job)
[houprg118069:17128] [[42756,2],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 433
```

Master code:

```cxx
#include <iostream>
#include <cstring>
#include <mpi.h>
#include <unistd.h>
#include <limits.h>

using namespace std;

int main() {
  char slavejobtospawn[500];
  strcpy(slavejobtospawn, "/rdfs/home/ggavaza/mpitry/stdal/stdal");
  
  MPI_Comm worker_comm_;
  MPI_Info minfo;
  int mpistat;

  // == init MPI
  int mpiInitialized;
  char localhost[HOST_NAME_MAX];
  mpistat = gethostname(localhost, HOST_NAME_MAX);
  mpistat = MPI_Initialized(&mpiInitialized);
  if(!mpiInitialized) {
    int provided;
    mpistat = MPI_Init_thread(0, 0, MPI_THREAD_MULTIPLE, &provided);
//     mpistat = MPI_Init_thread(0, 0, MPI_THREAD_SINGLE, &provided);
    if (provided < MPI_THREAD_MULTIPLE) {
      cout << "ERROR: The MPI library does not have full thread support" << endl;
      mpistat = MPI_Abort(MPI_COMM_WORLD, 1);
    };
    cout << "MASTER MPIINIT" << endl;
  };
  
  char hostin[120];
  strcpy(hostin, "lamhosts_tmp");
  
  cout << "MASTER " << localhost << " TRies Spawn" << endl;
  
  mpistat = MPI_Info_create(&minfo);
  mpistat = MPI_Info_set(minfo, "add-hostfile", hostin);
  mpistat = MPI_Comm_spawn(slavejobtospawn, MPI_ARGV_NULL, 
           1, minfo, 0, MPI_COMM_WORLD, &worker_comm_, MPI_ERRCODES_IGNORE);
   
  cout << "MASTER " << localhost << " SPAWNED SUCCESS" << endl;
  
  int value = 500;
  cout << "value =" << value << endl;
  mpistat = MPI_Send(&value, 1, MPI_INT, 0, 0, worker_comm_);
  MPI_Status MPIerr;
  mpistat = MPI_Recv(&value, 1, MPI_INT, 0, 0, worker_comm_, &MPIerr);
  cout << "updated value =" << value << endl;
  
  
  
  // == stop MPI
  mpistat = MPI_Finalize();
  cout << "MASTER " << localhost << "  SHUTTING DOWN" << endl;        
  return 0;
}
```

Slave code:

```cxx
#include <iostream>
#include <mpi.h>
#include <unistd.h>
#include <limits.h>

using namespace std;

int main() {
  int rank_;
  int master_;
  MPI_Comm slave_Comm_;
  MPI_Status MPIerr;
  int mpistat;
  // == init MPI
  int mpiInitialized;
  char localhost[HOST_NAME_MAX];
  mpistat = gethostname(localhost, HOST_NAME_MAX);
  cout << "SLAVE " << localhost << " STARTS" << endl;
  mpistat = MPI_Initialized(&mpiInitialized);
  if(!mpiInitialized) {
    int provided;
    cout << "SLAVE " << localhost << " TRIES MPIINIT" << endl;
    mpistat = MPI_Init_thread(0, 0, MPI_THREAD_MULTIPLE, &provided);
    if (provided < MPI_THREAD_MULTIPLE) {
      cout << "ERROR: The MPI library does not have full thread support" << endl;
      mpistat = MPI_Abort(MPI_COMM_WORLD, 1);
    };
    cout << "SLAVE " << localhost << " DONE SOME MPIINIT" << endl;
  };
  master_ = 0;
  mpistat = MPI_Comm_get_parent(&slave_Comm_);
  
  cout << "SLAVE " << localhost << " CONNECTED TO PARENT" << endl;
  
  int value;
  mpistat = MPI_Recv(&value, 1, MPI_INT, 0, 0, slave_Comm_, &MPIerr);
  value++;
  mpistat = MPI_Send(&value, 1, MPI_INT, 0, 0, slave_Comm_);
  
  // == stop MPI
  mpistat = MPI_Finalize();
  cout << "SLAVE " << localhost << " SHUTTING DOWN" <<endl;
  return 0;
}
```

Cheers,
George

### PR DESCRIPTION
**Pull request by rhc54**
Thanks to CalugaruVaxile for the report

Fixes #4555 

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@ CalugaruVaxile Could you please give this a spin and see if it fixes your problem?

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

many thanks for the fix; I am currently away and I hopefully returning to activity on Monday. I will test it then

Cheers,
George

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

may I know how to download your branch? I have downloaded the nightly build of Dec 8, but it doesn't have these fixes. Looking into orte/mca/odls/base/odls_base_default_fns.c for example (and checking it against the diffs in the other tab), it does not look like you have used the source in the nightly build as the "base" source for your version. I do apologize, I am not familiar with github.

One other question is: can I get a version of the code which does not require running  autogen.pl? I can't have installed either Autoconf: 2.69 or Automake: 1.12.2

Cheers,
George

**Comment by rhc54** [comment]
Try copying the following and paste it into a file in the head directory of your v3.0.0 source:
```
diff --git a/orte/mca/odls/base/odls_base_default_fns.c b/orte/mca/odls/base/odls_base_default_fns.c
index 0732129..dccde4e 100644
--- a/orte/mca/odls/base/odls_base_default_fns.c
+++ b/orte/mca/odls/base/odls_base_default_fns.c
@@ -115,6 +115,8 @@ int orte_odls_base_default_get_add_procs_data(opal_buffer_t *buffer,
     void *nptr;
     uint32_t key;
     char *nidmap;
+    int32_t n;
+    orte_proc_t *proc;
 
     /* get the job data pointer */
     if (NULL == (jdata = orte_get_job_data_object(job))) {
@@ -207,6 +209,17 @@ int orte_odls_base_default_get_add_procs_data(opal_buffer_t *buffer,
                         OBJ_DESTRUCT(&jobdata);
                         return rc;
                     }
+                    /* pack the location of each proc */
+                    for (n=0; n < jptr->procs->size; n++) {
+                        if (NULL == (proc = (orte_proc_t*)opal_pointer_array_get_item(jptr->procs, n))) {
+                            continue;
+                        }
+                        if (ORTE_SUCCESS != (rc = opal_dss.pack(&jobdata, &proc->parent, 1, ORTE_VPID))) {
+                            ORTE_ERROR_LOG(rc);
+                            OBJ_DESTRUCT(&jobdata);
+                            return rc;
+                        }
+                    }
                     ++numjobs;
                 }
                 rc = opal_hash_table_get_next_key_uint32(orte_job_data, &key, (void **)&jptr, nptr, &nptr);
@@ -280,6 +293,7 @@ int orte_odls_base_default_construct_child_list(opal_buffer_t *buffer,
     orte_std_cntr_t cnt;
     orte_job_t *jdata=NULL, *daemons;
     orte_node_t *node;
+    orte_vpid_t dmnvpid, v;
     int32_t n, k;
     opal_buffer_t *bptr;
     orte_proc_t *pptr, *dmn;
@@ -336,6 +350,31 @@ int orte_odls_base_default_construct_child_list(opal_buffer_t *buffer,
                     /* yep - so we can drop this copy */
                     jdata->jobid = ORTE_JOBID_INVALID;
                     OBJ_RELEASE(jdata);
+                    continue;
+                }
+                /* unpack the location of each proc in this job */
+                for (v=0; v < jdata->num_procs; v++) {
+                    if (NULL == (pptr = (orte_proc_t*)opal_pointer_array_get_item(jdata->procs, v))) {
+                        pptr = OBJ_NEW(orte_proc_t);
+                        pptr->name.jobid = jdata->jobid;
+                        pptr->name.vpid = v;
+                        opal_pointer_array_set_item(jdata->procs, v, pptr);
+                    }
+                    cnt=1;
+                    if (ORTE_SUCCESS != (rc = opal_dss.unpack(bptr, &dmnvpid, &cnt, ORTE_VPID))) {
+                        ORTE_ERROR_LOG(rc);
+                        OBJ_RELEASE(jdata);
+                        goto REPORT_ERROR;
+                    }
+                    /* lookup the daemon */
+                    if (NULL == (dmn = (orte_proc_t*)opal_pointer_array_get_item(daemons->procs, dmnvpid))) {
+                        ORTE_ERROR_LOG(ORTE_ERR_NOT_FOUND);
+                        rc = ORTE_ERR_NOT_FOUND;
+                        goto REPORT_ERROR;
+                    }
+                    /* connect the two */
+                    OBJ_RETAIN(dmn->node);
+                    pptr->node = dmn->node;
                 }
             }
             /* release the buffer */
diff --git a/orte/mca/plm/base/plm_base_launch_support.c b/orte/mca/plm/base/plm_base_launch_support.c
index 237bfa4..4ea3a70 100644
--- a/orte/mca/plm/base/plm_base_launch_support.c
+++ b/orte/mca/plm/base/plm_base_launch_support.c
@@ -172,6 +172,8 @@ void orte_plm_base_daemons_reported(int fd, short args, void *cbdata)
     if (orte_display_allocation) {
         orte_ras_base_display_alloc();
     }
+    /* ensure we update the routing plan */
+    orte_routed.update_routing_plan(NULL);
 
     /* progress the job */
     caddy->jdata->state = ORTE_JOB_STATE_DAEMONS_REPORTED;
@@ -1330,8 +1332,9 @@ void orte_plm_base_daemon_callback(int status, orte_process_name_t* sender,
         } else {
             jdatorted->num_reported++;
             OPAL_OUTPUT_VERBOSE((5, orte_plm_base_framework.framework_output,
-                                 "%s plm:base:orted_report_launch recvd %d of %d reported daemons",
+                                 "%s plm:base:orted_report_launch job %s recvd %d of %d reported daemons",
                                  ORTE_NAME_PRINT(ORTE_PROC_MY_NAME),
+                                 ORTE_JOBID_PRINT(jdatorted->jobid),
                                  jdatorted->num_reported, jdatorted->num_procs));
             if (jdatorted->num_procs == jdatorted->num_reported) {
                 bool dvm = true;
```
Then (assume your filename is addhost.diff) do the following:
```
$ patch -p1 < addhost.diff
```
You should then be able to just do a "make install" and test.

**Comment by jsquyres** [comment]
Here's a tarball with the fix from this PR, and is fully Autotools-bootstrapped (this link will become stale after a while): http://jeff.squyres.com/unofficial/openmpi-pr-4586-add-host-fix.tar.bz2

**Comment by CalugaruVaxile** [comment]
Many thanks, Jeff! It installed perfectly

Cheers,
George

**Comment by rhc54** [comment]
I’ll fix that error log output, but it isn’t affecting anything here. I’m not seeing anything wrong in the code - what does your hostfile contain? What is in your original hostfile?

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

the hostfile contains

houprg118069
houprg118070
houprg118071

And what I expect when I invoke

mpistat = MPI_Info_create(&minfo);
mpistat = MPI_Info_set(minfo, "add-hostfile", hostin);
mpistat = MPI_Comm_spawn(slavejobtospawn, MPI_ARGV_NULL,
           3, minfo, 0, MPI_COMM_WORLD, &worker_comm_, MPI_ERRCODES_IGNORE);

is to see three processes spawned, one in each host. Currently there are
three processes spawned, but all of them in the first host. As far as I
know,

houprg118069

is equivalent to

houprg118069:1

but I think the code behaves like the entry in the hostfile would be

houprg118069:3

I admit, this is just a speculation, I don't know how to further probe into
the issue.
It may also be that I have built OpenMPI incorrectly, this is why I asked
about the config/make commands I used.

./configure --prefix /dio/openmpi/3.0.0.gg --enable-static --without-verbs
--enable-mpirun-prefix-by-default --enable-orterun-prefix-by-default CC=icc
CXX=icpc FC=ifort

Cheers,
George

**Comment by rhc54** [comment]
You need to add ```slots=1``` to each line. Otherwise, we will look at each node and set the number of slots equal to the number of cores we find there.

**Comment by rhc54** [comment]
Or tell us ```--map-by node``` on your mpirun cmd line so we cycle across the nodes when assigning locations

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

--map-by node works!!

Is there a way to make it default (so I don't need to specify this option
for each job)?

Cheers,
George

**Comment by rhc54** [comment]
You have two options:

1. put``` OMPI_MCA_rmaps_base_mapping_policy=node``` in your environment

1. add ```rmaps_base_mapping_policy=node``` to your default MCA parameter file

**Comment by rhc54** [comment]
Since this appears to solve the problem, I'll commit it and setup the PRs for the release branches.

**Comment by CalugaruVaxile** [comment]
Hi Ralph,

this works perfectly, too!! Thank you a lot! If you could just fix the
hwloc error messages, that would be pretty much it. According to my tests,
there are as many error messages as host entries in the hostfile. This
makes me think that the issue is at

mpistat = MPI_Info_set(minfo, "add-hostfile", hostin);

interestingly,

mpistat = MPI_Info_set(minfo, "add-host", "houprg118070,houprg118071");

produces exactly the same error messages. But otherwise it works correctly.

I hope this helps

Cheers,
George

**Comment by rhc54** [comment]
I addressed those in a separate PR that was just committed to master. I'll have to check and see if that code is relevant elsewhere

**Comment by CalugaruVaxile** [comment]
Excellent, thank you for support!

**Pull request merged**
