### PR TITLE
refresh ROMIO based on v3.2a2-84-gef1cf14

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by hppritcha** [comment]
@ggouaillardet Thanks for doing this.  Here are some general comments, then I'll have a few specific code ones in some subsequent comments.  There are a number of white space file changes - particularly in the confdb m4 files.  Not sure why that happened, but it would be nice to avoid them next time.

I'm not entirely happy with the README_OMPI just referencing the enclosed patch file.  For source code changes in particular, I'd prefer to use known OMPI macros to indicate where source file changes.  I realize this is not part of your PR, just an idea for some improvements.  Would you mind
retaining the original content of README_OMPI (minus your header changes) and add the reference to the patch file?

Also, does OMPI really need the config.rpath file in confdb?

**Comment by hppritcha** [comment]
@ggouaillardet I'm having problems using the PR fileview mode to make nicely formed comments because there are too many file changes in the PR request.  It would probably have worked better
if you'd staged the work as a series of separate commits into your topic branch.  

Anyway, at line 115 in file io_romio_conv.h reads
extern int MPI_FILE_NULL_undef;

Is this really correct?

Also,  for adio/common/ad_iread_coll.c and ad_iwrite_coll.c was there a reason for the changes
from the original ROMIO source, other than the use of the ROMIO_HAVE_WORKING_AIO?

**Comment by ggouaillardet** [comment]
@hppritcha i pushed (--force) a new commit
in io_romio_conv.h, this was some debug i forgot to remove, thank for catching this
i revamped the changes ad_i{read,write}_coll.c (bottom line, this cannot be compiled in ompi yet)
i removed confdb/config.rpath
i did not update the README yet, nor add some OMPI macro in order to clearly identify the changes.

basically, what i did is import romio from mpich, apply the necessary changes (based on what is done on the current version)

so if you look at the PR, yes, there are many changes, including white space changes ...
/* some white space changes were made in ompi repo only before */
assuming you trust the mpich folks, there is no real need to review this PR :
all you need to do is review the changes i made to mpich, and they are in ompi.patch
if you want to review the romio changes, i recommend you run git diff on the mpich repo instead.
i ll extend the OMPI readme and explain how to refresh romio from mpich.
does that make sense ?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/162/
Test PASSed.

**Comment by hppritcha** [comment]
@ggouaillardet 
Sent Rob Latham an email asking whether there are any known bugs in the romio in mpich 3.2 pre-release that we should know about.  If he gives the all clear, I'll merge this pr.

**Comment by hppritcha** [comment]
@ggouaillardet 
@roblatham00

Just for record, the mpich trac for open romio issues at the time of this merge are
2011, 2012, 2088, 2182, 2212, 2214, 1085, 2197

See

https://trac.mpich.org/projects/mpich/query?status=!closed&component=romio

**Comment by jsquyres** [comment]
Just to close the loop on this: we talked about this PR on the call today.

1. Next time, we might want to adopt the "make a new component for a new version of ROMIO" philosophy that we've adopted for hwloc and libevent.  I.e., when we bring in a new ROMIO, make a new component with the version number in it somewhere.  This allows us to test the old ROMIO alongside the new ROMIO.  When we're happy with the new ROMIO, we can just rm -rf the old ROMIO component.
1. We might also want to do a single git commit with the new ROMIO version, and then have separate successive commits with the OMPI-specific modifications after the big first commit.  This will make it easier to track / look back in history to see what is OMPI-specific in a given ROMIO import.
1. For release versions of OMPI, it would likely be good to import the ROMIO that was included in MPICH releases -- it just makes it easier to describe what version of ROMIO is contained in a given version of OMPI.  But note that it's also ok to put in patches after that, if we need to (e.g., we've done that with hwloc -- e.g., we import hwloc 1.7.2 + patches A, B, and C to fix known hwloc bugs).  To be clear: it would be good to get an MPICH-released version of ROMIO before the v1.9.0 release.

**Pull request merged**
