### PR TITLE
v5.0.x pml/ob1: Fix typo succedded

### PR DESCRIPTION
**Pull request by wckzhang**
Signed-off-by: William Zhang <wilzhang@amazon.com>
(cherry picked from commit e7ae8699a3a06fc87ec03269e091c775351bd606)

### CODE REVIEW

**Comment by wckzhang** [comment]
Backport of - https://github.com/open-mpi/ompi/pull/10950

**Review by lrbison — APPROVED** [review]

**Comment by wckzhang** [comment]
dist check  looks like some sort of credentials error

**Comment by wckzhang** [comment]
aws:bot:retest

**Review by jsquyres — APPROVED** [review]

**Comment by awlauria** [comment]
bot:as:retest

**Pull request merged**
