### PR TITLE
Fix PMIX_DECLSPEC conversions to PMIX_EXPORT, and fix unused var warning

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
looks like the Cray worker lost connection

bot:ompi:retest

**Comment by rhc54** [comment]
my, my - the cray worker is definitely having trouble today.

bot:ompi:retest

**Comment by jsquyres** [comment]
Cray is offline today for scheduled maintenance.  @hppritcha is seeing if he can disable it in Brian's Jenkins workflow.

**Comment by hppritcha** [comment]
bot:ompi:retry

**Comment by hppritcha** [comment]
uff, 
bot:ompi:retest

**Comment by hppritcha** [comment]
I pulled the cray nodes out of the matrix.  let's try again.
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

**Pull request merged**
