### PR TITLE
osc/pt2pt: fix typo

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@me.com>

### CODE REVIEW

**Comment by hppritcha** [comment]
is this relevant to an issue or something on the user mail list?

**Comment by jsquyres** [comment]
I confirm that this fixes the memory problem.

However, all the ibm/onesided communication tests now hang (whereas on the v2.x branch, they all complete within a few seconds).

**Comment by jsquyres** [comment]
@hppritcha This fixes the issue with osc/pt2pt described in #3226, but it surfaces another problem (perhaps hidden by the issue described by #3226) -- one sided test programs using osc/pt2pt are now hanging.

**Comment by jsquyres** [comment]
This is needed to fix the memory problem (which is killing Cisco's MTT).  But per my above comment, there's still another problem to fix (the hang).

**Comment by hppritcha** [comment]
Thanks.  It would have been nice for this info to be in the commit message.

**Pull request merged**
