### PR TITLE
openib thread fixes

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
This PR depends on #827.

@miked-mellanox Please take a look. With these fixes and #827 the openib btl runs without issue with MPI_THREAD_MULTIPLE. I know mellanox only cares about mxm these days but there are benefits to having the btl work.

**Comment by miked-mellanox** [comment]
@hjelmn - 
* jenkins does not run openib w/ threads, it is disabled
* I can re-enable it
* tried to run this PR with threads test but it failed w/ segv:

``` shell
/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -bind-to core -mca btl_openib_if_include mlx5_0:1  -mca pml ob1 -mca btl openib /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/latency_th 8
```
* did it work for you?

**Comment by hjelmn** [comment]
@miked-mellanox That one was passing for me in multiple different configurations. Did you apply the patches from #827?

**Comment by hjelmn** [comment]
@miked-mellanox Can you enable thread tests with the openib btl with this PR? Master now has the needed code to make this work.

**Comment by miked-mellanox** [comment]
@hjelmn - fixed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
@hjelmn - tests passed, only warn:

``` shell
14:30:47 + timeout -s SIGKILL 10m /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1 -mca pml ob1 -mca btl self,openib /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/message_rate_th 8
14:30:48 [warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
14:30:50 Thread 4, message rate 4248.267450 messages/sec
14:30:50 [warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
14:30:50 [warn] opal_libevent2022_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.

```

**Pull request merged**
