### PR TITLE
Add proc fix/v2.x

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
Need in 9ae3aa0fd956386b55db80a66c0cb64e2776fc04 explained in PR #3011.
On the same system 10a0d0f6ff74568067691e266ec31462f437dc34 helps to reduce barrier time from 170ms to 69 ms with SLURM plugin.

**Comment by artpol84** [comment]
@hjelmn give this a try when you'll be testing at scale. May help 2.x to look better.

**Comment by hjelmn** [comment]
Yeah, was only testing /bin/true. This is a performance bug that has existed since we did the add_procs changes. :+1: Please PR to 2.0.x if possible.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
This is not a blocker for v2.1.0.

**Comment by artpol84** [comment]
It is, for us at least.

**Comment by rhc54** [comment]
Can come across after the master PR has a chance to cycle thru nightly MTT

**Comment by jsquyres** [comment]
It looks like #3011 went through ok last night in MTT.  Merging this to v2.x.

**Pull request merged**
