### PR TITLE
Fix typo in ompi_setup_prrte

### PR DESCRIPTION
**Pull request by opoplawski**

### CODE REVIEW

**Comment by awlauria** [comment]
ok to test

**Review by awlauria — APPROVED** [review]
Thanks!

**Comment by awlauria** [comment]
@opoplawski can you add the --signoff and repush?

```
$. git commit --amend --signoff
$. git push typo -f
```
should do it.

**Comment by bwbarrett** [comment]
Note that this will cause conflicts with https://github.com/open-mpi/ompi/pull/10321 and this code is removed in that PR.

**Comment by opoplawski** [comment]
Ooh, looks like that PR may solve the actual problem I was starting to look into when I found this.  Feel free to close this in favor of that one if appropriate.

**Comment by jsquyres** [comment]
> Ooh, looks like that PR may solve the actual problem I was starting to look into when I found this. Feel free to close this in favor of that one if appropriate.

Thanks!

**Pull request closed without merging**
