### PR TITLE
btl/ugni: swat a compiler warning

### PR DESCRIPTION
**Pull request by hppritcha**
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
@cniethammer hi Christoph I picked you since I think you have access to a cray xc and cray programming environments.

**Comment by cniethammer** [comment]
@hppritcha Hi Howard, since we have a HPE system since last year I have no access to a CLE any more.

However, I wonder what swat reports here and what this PR is intended to fix:
1.) In `hwloc.h`(https://github.com/open-mpi/hwloc/blob/e17cb9634e5c0fa149a512a7176c800867469a5e/include/hwloc.h#L903) there is the declaration `int hwloc_get_nbobjs_by_type(...)` so the PR introduces in the initial assignment a type mismatch
2.) The `mca_btl_ugni_component.virtual_device_count` member is of type `int`, so the assignment to `core_count` some lines below will become unsafe for values larger than `INT_MAX` with the PR

**Comment by hppritcha** [comment]
CC       btl_ugni_init.lo
btl_ugni_init.c: In function 'mca_btl_ugni_init':
btl_ugni_init.c:252:24: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
         if (core_count <= opal_process_info.num_local_peers || !opal_using_threads()) {
                        ^~
  CCLD     mca_btl_ugni.la

**Comment by hppritcha** [comment]
@cniethammer didn't realize you no longer had access to a system with CLE compilers.

**Review by awlauria — APPROVED** [review]

**Pull request merged**
