### PR TITLE
Removing config/opal_check_pmi.m4 

### PR DESCRIPTION
**Pull request by zosman1**
https://github.com/open-mpi/ompi/issues/8326#issuecomment-753382719

Looks like this is a stale file that can be removed, if there's anything I missed let me know! 

Signed-off-by: Zach Osman zosman1

### CODE REVIEW

**Comment by rhc54** [comment]
ok to test

**Comment by rhc54** [comment]
@artemry-mlnx Looks like a bug in the Mellanox CI script?
```text
/__w/1/jenkins_scripts/jenkins/ompi/ompi_test.sh: line 395: HPCX_UCX_DIR: unbound variable
```

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fe26141673380257c40d6fa735142367

**Comment by ggouaillardet** [comment]
@zosman1 thanks for the PR!

you need to sign off your commit so it can be merged upstream

you would typically do that with
```
git commit -s --amend
git push --force ...
```

**Comment by zosman1** [comment]
https://github.com/open-mpi/ompi/pull/8328#issuecomment-753393110

It looks like one of the cases fail but I'm not really sure why, any ideas?

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2edb23c26347aef079047496112182fb

**Comment by rhc54** [comment]
> It looks like one of the cases fail but I'm not really sure why, any ideas?

IBM is having problems with the PGI compiler. I would ignore it for now - it's a known issue.

**Comment by jsquyres** [comment]
@zosman1 Most of us will be returning to work from the winter holidays this upcoming week; there's a few CI problems that crept in while we were on vacation.  Someone will be looking at these this week.

**Comment by zosman1** [comment]
Gotcha, thanks!

**Review by ggouaillardet — APPROVED** [review]

**Pull request merged**
