### PR TITLE
Update PRRTE

### PR DESCRIPTION
**Pull request by rhc54**
- Ensure we accurately handle node name aliases
- Apply the local launch environ to apps prior to spawn
- Add error check if PMIx_Spawn fails
- Fix compiler warning

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a1eef629caeaf647cb9748531aec238b

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/12dfc6aee66cf74e0b11fafffbe7289f

**Comment by rhc54** [comment]
@jjhursey Is this an artifact of your scale testing environment? I'm unable to replicate the problem with my swarm.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/628c2177bb150e4516f920747cc66ed7

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/576844adfcc48d2a02f7e76c156598e6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/47242b842c264b18f1dfeafed2ec5152

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9913d35f701f50e17ae1158a7fbe918b

**Comment by rhc54** [comment]
@jjhursey We appear to only be traversing one node - I'll see if my changes perhaps are causing the problem.

**Comment by jjhursey** [comment]
Maybe it is the hostnames (Are are hashes)? It is curious that this didn't trip on the PRRTE side, but we don't run the all in one wrapper (`mpirun`) over there. So maybe that's a factor. I can try to reproduce locally.

**Comment by jjhursey** [comment]
Yeah this must be something in the difference between `mpirun --hostfile foo.txt --map-by ppr:4:node hostname` and `prte --hosfile foo.txt & prun --map-by ppr:4:node hostname`.

The `mpirun` version will only launch on one node. I also noticed that `--display-allocation` doesn't work with `mpirun` or `prun` at the moment.
```
shell$ mpirun --display-allocation --hostfile /workspace/hostfile.txt hostname
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
ced67f9b646e
shell$ mpirun --map-by ppr:4:node --hostfile /workspace/hostfile.txt hostname
--------------------------------------------------------------------------
Your job has requested more processes than the ppr for
this topology can support:

  App: hostname
  Number of procs:  40
  Procs mapped:  4
  Total number of procs:  40
  PPR: 4:node

Please revise the conflict and try again.
--------------------------------------------------------------------------
[ced67f9b646e:00449] PMIx_Spawn failed (-179): JOB FAILED TO MAP
```

The `prte` version works fine displaying all of the allocated nodes and then launching over all of them.
```
shell$ prte --hostfile /workspace/hostfile.txt &
shell$ prun --map-by ppr:4:node hostname | sort | uniq -c
      4 15d00b8760ae
      4 49a2b46b2dd7
      4 55f7a4869521
      4 830641a19e79
      4 957fa574a566
      4 b7904ff7c40b
      4 c17116a8f8cc
      4 ced67f9b646e
      4 e5b0a1d148a0
      4 f393f9e5f3b5
```

**Comment by rhc54** [comment]
I see the problem - fix coming

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest
bot:ibm:args:"--mca rmaps_base_verbose 100"

**Comment by rhc54** [comment]
Actually, I have to eat my words - I don't see the problem just yet. Pretty sure it is in the name resolution code, though. Can you paste the names of the nodes you are using?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2fcee44b3a646da21476808751e3800f

**Comment by rhc54** [comment]
Looks like that args argument didn't work. I'll try to replicate on my swarm.

**Comment by rhc54** [comment]
I have found the problem, but I'm not sure how to fix it. In @jjhursey's docker setup, we install both PRRTE and OMPI, and the default PATH and LD_LIBRARY_PATH are set to point to the PRRTE installation followed by the OMPI one. When you execute ```mpirun```, we fork/exec ```prte``` to start the DVM - and unfortunately, we are picking up the _external_ version instead of the one generated by the embedded copy of PRRTE. Library confusion ensues.

If I blow away the PRRTE installation, then everything runs just fine. So somehow we need a method of ensuring we are using the embedded PRRTE executables (prte and prted) when someone might have an external version around and ahead of OMPI in the respective paths. I thought of simply renaming the binaries, but that doesn't resolve the LD_LIBRARY_PATH problem.

**Comment by rhc54** [comment]
@jjhursey Can you please confirm this diagnosis? If you do have PRRTE separately installed, can you modify the build formula to not do so? This would at least solve the immediate problem while we work on a long-term solution.

**Comment by jjhursey** [comment]
Actually in the CI running here for OMPI there is no external PMIx or PRRTE in the box, just OMPI using the internal pointers to pmix/prrte/hwloc/libevent. I dropped into the environment this morning to double check.

It's a little different than the swarm setup I gave you. I can work to see if I can create an alternative in the swarm setup that is more 'pure' ompi like what CI is running.

I'll see if I can create reproducer steps outside of the container environment. I'll also try to craft a test for this in the prrte test suite to make it easier to iterate on a solution there.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6d584a7fa6ac1a8e4960f5811ed650ef

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a730facfdd09b268264a5743cb203b8d

**Comment by jjhursey** [comment]
Humm. I've seen that error before with prrte, but I cannot remember how I hit it.
```
bash: data.string/bin:pval-: No such file or directory
bash: data.string/lib:pval-: No such file or directory
bash: data.string/lib:pval-: No such file or directory
bash: data.string/bin/prted: No such file or directory
[fb7722c2bfa0:00015] PRRTE ERROR: Bad parameter in file rml_oob_send.c at line 202
[fb7722c2bfa0:00015] PRRTE ERROR: Bad parameter in file errmgr_dvm.c at line 547
mpirun failed to initialize, likely due to no DVM being available
```

The pmix-test unit test is passing (https://github.com/openpmix/pmix-tests/pull/55) but it does not use an MPI test program. I would be surprised if that was the issue though.

I'll try to get more information and followup in Slack.

**Pull request merged**
