### PR TITLE
Fix language in CUDA error

### PR DESCRIPTION
**Pull request by simonbyrne**
Removes a malapropism (passed should be past), and hopefully makes it a bit clearer.

### CODE REVIEW

**Comment by gpaulsen** [comment]
ok to test.

**Comment by gpaulsen** [comment]
@simonbyrne Hello.  Thanks for submitting the PR.
The signed-off-by checker has failed since you did not use the `-s` flag to `git commit` which signifies that the content that you are submitting is your own work, and that you have permission to give that work to Open-MPI, as stated here:
https://www.open-mpi.org/faq/?category=contributing#contribute-code

**Comment by simonbyrne** [comment]
Fixed

**Comment by awlauria** [comment]
bot:ompi:retest

**Pull request merged**
