### PR TITLE
TCP help message updates

### PR DESCRIPTION
**Pull request by jsquyres**
Take the 2 BTL/OOB TCP commits from #4199:

* OOB TCP: be more explicit about version mismatches
* BTL TCP: be more explicit about connection errors

### CODE REVIEW

**Comment by bosilca** [comment]
What about moving the get_name functions (get_peer_name) down in opal/utils/fd.c ?

**Comment by jsquyres** [comment]
@bosilca Updated

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/14748e1ba18ae5ef0341d75df610cc81

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Pull request merged**
