### PR TITLE
v3.1.x: add gen p5 chip pci id to ini file

### PR DESCRIPTION
**Pull request by dsharma283**
Adding the PF pci id for new gen p5 chip to openmpi code.

Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>

### CODE REVIEW

**Comment by dsharma283** [comment]
Approved

**Comment by jsquyres** [comment]
@dsharma283 Can you please make a master PR for this, and then make v3.0.x, v3.1.x, and v4.0.x PRs cherry-picking the master commit to the release branches?

That's how we get things to release branches.

Thanks!

**Comment by dsharma283** [comment]
On master brnach I could not find the .ini file, could you guide me how to make master PR

**Comment by nmorey** [comment]
@jsquyres The config file was dropped from master when you removed the openib BTL. So the patch doesn't make sense there.

But it should probably be applied to all release branches (including the 2.x if they are still maintained)

**Comment by jsquyres** [comment]
My bad -- I forgot that `openib` was dropped on master.

In these cases, you're right -- just make PRs directly on the release branches (obviously without cherry-picking).  But you should mention in the PR description why it's not a cherry pick so that bozos like me won't ask you to open a PR on master first.  😉 

As for which release branches are active:

* v4.0.x: current.  You've probably missed the v4.0.1 train, but v4.0.2 will happen someday.
* v3.1.x: still maintained.  You may or may not have missed the v3.1.4 train.  Don't know if v3.1.5 will ever happen.  But if you PR and it gets merged, the change will at least be in the nightly snapshot tarballs.
* v3.0.x: same as v3.1.x, but s/v3.1.4/v3.0.4/.
* v2.1.x (i.e., `v2.x` branch): all but dead.  There will never be another release.  Probably not worth it.  Encourage users to upgrade to v3.something or v4.something.

**Comment by jsquyres** [comment]
@dsharma283 Don't forget to get a review on here; PR's aren't merged on release branches unless they are reviewed. I think you need a trivial review for this (perhaps @nmorey?), but a review is needed.

I put the appropriate milestone and tags on here for you; please be sure to put those on future PRs.  Thanks!

**Comment by dsharma283** [comment]
Added some more info to the commit message as Jeffry suggested. @nmorey could you supply the review which Jeffry is asking for.

Thanks

**Comment by jsquyres** [comment]
ok to test

**Comment by dsharma283** [comment]
pull request build checker did not pass, do I need to do anything here or I should ignore that?

**Comment by jsquyres** [comment]
Looks like a false failure on the Cray.

bot:ompi:retest

**Comment by jsquyres** [comment]
Ok, looks good.  Did you guys make an equivalent v3.0.x PR for this?  Or do you really only want v3.1.x?

**Comment by jsquyres** [comment]
@dsharma283 Do you plan to make an equivalent v3.0.x PR for this? Or do you really only want v3.1.x?

**Pull request merged**
