### PR TITLE
Optimizations to PML-CM, MTL-OFI

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- PML-CM Send/Recv optimizations
- Inline MTL OFI, datatype pack/unpack

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 910 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_414/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_414/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_414/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/414/
Test PASSed.

**Comment by rhc54** [comment]
So did we lose some optimization by leaving out the change to opal datatype?

**Comment by jithinjosepkl** [comment]
Yes, the change to the opal data type had helped to reduce instruction count.
I will come up with a patch later considering the BTL path as well.

**Comment by hppritcha** [comment]
Out of curiosity,  by how much does the blocking send/recv optimization improve short message latency on something like ivy bridge processors/psm provider combination?

Looks good to me.

**Comment by rhc54** [comment]
Please continue the conversation - I'm just going to commit this into the master so it can make its way to 1.8.5

**Pull request merged**
