### PR TITLE
OSC portals4 : do not generate an EVENT_SEND to avoid to filter it

### PR DESCRIPTION
**Pull request by francois-wellenreiter**

### CODE REVIEW

**Comment by francois-wellenreiter** [comment]
@regrant could you please review this enhancement

**Comment by jsquyres** [comment]
@regrant Can you have a look?  Thanks.

**Comment by regrant** [comment]
@francois-wellenreiter while there's no explicit use of the PTL_EVENT_SEND event, it's the only way that you can catch initiator side errors since send events are not counted (CT) either. This could lead to infinite polling on your CTWait call if you're waiting for something that will never complete. (See my comment on https://github.com/open-mpi/ompi-release/pull/903) @jsquyres

**Comment by regrant** [comment]
We've finished looking into the potential issues surrounding this pull request and everything checks out. Merging..

**Pull request merged**
