### PR TITLE
fcoll/dynamic_gen2: fix coverty warnings

### PR DESCRIPTION
**Pull request by raafatfeki**
fix warnings for coverty CID 1433655 and CID 1433654
some formatting fixes

Signed-off-by: raafatfeki <fekiraafat@gmail.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
@raafatfeki Is it possible to separate the whitespace changes and the code/logic changes into two separate commits?  That will make it significantly easier to read what the actual code change is vs. the "let's tidy up the code style" changes.

Thanks!

**Comment by bwbarrett** [comment]
bot:ompi:retest

Brian broke the 32bit builds...

**Comment by raafatfeki** [comment]
@jsquyres Definitely, I will make the changes you requested.

**Pull request merged**
