### PR TITLE
oshmem: Fix tarball issue

### PR DESCRIPTION
**Pull request by igor-ivanov**
see: https://github.com/open-mpi/ompi/issues/1036 for details

@hjelmn could you look at. I have checked one and it looks workable for me.

### CODE REVIEW

**Comment by jsquyres** [comment]
@igor-ivanov Pro tip: if you put "Fixes open-mpi/ompi#1036" in the commit message, it'll automatically close #1036 when this PR is merged.  See https://github.com/open-mpi/ompi/wiki/GithubCommitMessages for more details.

**Comment by igor-ivanov** [comment]
It comes from commit message and I missed it during pr creation. Will be more careful in the future.

**Comment by jsquyres** [comment]
@igor-ivanov No problem; it can just save some time and ensure we close issues when PR's are merged.

If you care, you can go back and edit that commit message (via `git rebase -i`) and force-push it to this PR.  Just about the *only* time rebasing / force-pushing is acceptable is on a PR before it is merged.  :smile:

**Comment by hjelmn** [comment]
Will test tomorrow.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
