### PR TITLE
Try a different approach for scalably dealing with hetero clusters

### PR DESCRIPTION
**Pull request by rhc54**
Revert e9bc293 and try a different approach for scalably dealing with hetero clusters. Have each orted send back its topo "signature". If mpirun detects that this signature has not been seen before, then ask for that daemon to send back its full topology description. This allows the system to only get the topology once for each unique topo in the cluster.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@hjelmn This isn't quite right yet - will fix shortly

**Comment by rhc54** [comment]
@hjelmn should be good to go - let me know if it works for you as I'd like verification before committing

**Comment by rhc54** [comment]
@jsquyres you will need to adjust your MTT cmd line if/when this is committed as the hetero-nodes option is being removed

**Comment by hjelmn** [comment]
Will be testing this overnight.

**Pull request merged**
