### PR TITLE
Add a workaroud for issue in libcuda.so library

### PR DESCRIPTION
**Pull request by rolfv**
We intermittently see that the check for GPU memory returns true when the memory is actually host memory.  This workaround gets us past that until we get a fix in the CUDA library.

@bureddy Can you look at this?  I inadvertently closed #728 so this takes its place.  I made change as requested by @bureddy.  It will not affect anything functionally but I can see how it seems to make sense to put the workaround before the CUDA initialization step.

### CODE REVIEW

**Comment by rolfv** [comment]
I made change as requested so I am going to just go ahead and merge now.
Closes #737

**Comment by hppritcha** [comment]
does this need to go in to v2.x?

**Comment by bureddy** [comment]
@rolfv  :+1:

**Comment by rolfv** [comment]
Yes.  Will be submitting for 2.x.  Will soak overnight.

**Pull request merged**
