### PR TITLE
IU jenkins PR check

### PR DESCRIPTION
**Pull request by hppritcha**
this is a check of the PR setup of the IU jenkins
PR build request, not intended to be merged in to master.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/2/

**Build Log**
*last 20 lines*

 ```
[...truncated 27 lines...]
=================================================================
I could not find a recent enough copy of autoconf.
I need at least 2.69, but only found the following versions:

    autoconf: 2.63

I am gonna abort.  :-(

Please make sure you are using at least the following versions of the
tools:

    GNU Autoconf: 2.69
    GNU Automake: 1.12.2
    GNU Libtool: 2.4.2
=================================================================
+ make -j 4 distcheck
make: *** No rule to make target `distcheck'.  Stop.
Build step 'Execute shell' marked build as failure
Setting status of 706705edb9084354823484ef8bff9c3a15eeb92e to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/2/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/91/

**Build Log**
*last 20 lines*

 ```
[...truncated 5444 lines...]
 #ident "$Id: alps_toolAssist.h 7253 2012-03-21 22:12:15Z jhn $"
  ^
In file included from ../../../../orte/mca/odls/alps/odls_alps.h:33:0,
                 from odls_alps_module.c:131:
/opt/cray/alps/5.2.3-2.0502.9295.14.14.ari/include/alps/libalpsutil.h:13:2: warning: #ident is a GCC extension
 #ident "$Id: libalpsutil.h 6022 2009-05-19 15:12:29Z ben $"
  ^
In file included from ../../../../orte/mca/odls/alps/odls_alps.h:34:0,
                 from odls_alps_module.c:131:
/opt/cray/alps/5.2.3-2.0502.9295.14.14.ari/include/alps/libalpslli.h:21:2: warning: #ident is a GCC extension
 #ident "$Id: libalpslli.h 9100 2014-10-13 20:41:14Z jhn $"
  ^
make[2]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte/mca/odls/alps'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/ompi_master_pr_cle5.2up02/orte'
make: *** [all-recursive] Error 1
Build step 'Execute shell' marked build as failure
GCM: Sending notification to: hpp
Setting status of 706705edb9084354823484ef8bff9c3a15eeb92e to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/91/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/3/

**Build Log**
*last 20 lines*

 ```
[...truncated 27 lines...]
=================================================================
I could not find a recent enough copy of autoconf.
I need at least 2.69, but only found the following versions:

    autoconf: 2.63

I am gonna abort.  :-(

Please make sure you are using at least the following versions of the
tools:

    GNU Autoconf: 2.69
    GNU Automake: 1.12.2
    GNU Libtool: 2.4.2
=================================================================
+ make -j 4 distcheck
make: *** No rule to make target `distcheck'.  Stop.
Build step 'Execute shell' marked build as failure
Setting status of 1d8d2f3f5a9f94d249792688015e4a64f719be41 to FAILURE with url http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/3/ and message: Build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
* Coverity found 816 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//588/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/92/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/588/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 816 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//589/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/589/
Test PASSed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/5/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/94/
Test PASSed.

**Comment by hppritcha** [comment]
closing this as its served its purpose validating the distcheck jenkins project

**Pull request closed without merging**
