### PR TITLE
ikrit spml cleanup, mkey cache and assorted bug fixes

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe @igor-ivanov please review

### CODE REVIEW

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by yosefe** [comment]
@alex-mikheev test failure:
```
06:40:33   CC       sshmem_verbs_module.lo
06:40:33 In file included from sshmem_verbs_module.c:36:0:
06:40:33 sshmem_verbs_module.c: In function ‘segment_create’:
06:40:33 sshmem_verbs_module.c:336:34: error: ‘map_segment_t’ has no member named ‘seg_base_addr’
06:40:33             ds_buf->seg_id, ds_buf->seg_base_addr, (unsigned long)ds_buf->seg_size, ds_buf->seg_name)
06:40:33                                   ^
06:40:33 ../../../../opal/util/output.h:523:52: note: in definition of macro ‘OPAL_OUTPUT_VERBOSE’
```

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/c4211918e61f4a25917da0f7ee9f1929

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/c8d430e96d008b0826681913f29b71db

**Comment by jladd-mlnx** [comment]
@jjhursey Are these false alarms? Please advise.

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/2746fecf92fda4d80ff1b80b23edbfc7

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/1c0802e7daeff8b5aa6889d53fdd37d0

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/56872b8a6e4819a04736383bc540bc5a

**Comment by jjhursey** [comment]
Disregard the IBM-CI. The relay machine failed unexpectedly this afternoon. I'll take down the Jenkins until it is back up.

**Comment by hppritcha** [comment]
@jsquyres i think this can be merged

**Comment by hppritcha** [comment]
removing rm approved from this so the ucx/mlnx folks can sort this out.

**Comment by alex-mikheev** [comment]
@shamisp please take a look at my last two commits

**Comment by shamisp** [comment]
@hppritcha  Looks good to me.

**Comment by igor-ivanov** [comment]
:+1:

**Pull request merged**
