### PR TITLE
v2.1.4 updates: VERSION, NEWS, AUTHORS

### PR DESCRIPTION
**Pull request by jsquyres**
@hppritcha please review.  ~~~Haven't given README/etc. a once-over yet.~~~

Refs #4920

### CODE REVIEW

**Comment by jsquyres** [comment]
@hppritcha README and AUTHORS now updated.

**Comment by jsquyres** [comment]
Comments were left in VERSION to explain the `c:r:a` updates -- need to remove those before merging this PR.

**Comment by jsquyres** [comment]
Removed comments from VERSION.  Waiting for CI.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8789a15de474a52272654644d4a02c74

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d2f3f0b502d94508063c3d59abacfbcc

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7d529341fcc834805ccae75b4597a305

**Pull request merged**
