### PR TITLE
osc/pt2pt: invoke ompi_osc_signal_outgoing only once per fragment

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hjelmn could you please review this ?

ompi_osc_signal_outgoing was previously invoked both in ompi_osc_pt2pt_frag_start and frag_send
and that caused a hang reported by @bosilca in http://www.open-mpi.org/community/lists/devel/2015/01/16813.php

```
mpirun -np 2 mpi_test_suite -t 48
```

invoking ompi_osc_signal_outgoing once solves the hang that would occur in MPI_Win_fence otherwise. i simply guessed the extra call was in ompi_osc_pt2pt_frag_start so i just removed it ...

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/183/
Test PASSed.

**Comment by bosilca** [comment]
This fix seems to be the right one as even in the case where the fragment is buffered (because the eager is not available), we will fall back to frag_send which correctly counts the outgoing fragments.

I also confirm that the patch allows the mpi_test_suite to further continue on the execution (now it dies on a grequest/IO related issue).

**Comment by hjelmn** [comment]
This is the correct fix. Looks like a merge issue that cropped up in my btl 3.0 branch (where osc/pt2pt lived until recently).

**Pull request merged**
