### PR TITLE
Correct the datatype args to prevent valgrind memory corruption in MPI_Win_fence.

### PR DESCRIPTION
**Pull request by rhc54**
Per Satish Balay

See http://www.open-mpi.org/community/lists/users/2015/04/26818.php

@bosilca @ggouaillardet Can you please review? This needs to go into 1.8.5 if correct

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 904 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_502/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_502/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_502/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/502/
Test PASSed.

**Comment by bosilca** [comment]
The proposed patch is incorrect. For an INDEXED_BLOCK we need to store the count, the blocklength and then the indexed positions, where all these elements are integers. Thus the correct value should be i[0] + 2. The correct patch is
```
diff --git a/ompi/datatype/ompi_datatype_args.c b/ompi/datatype/ompi_datatype_args.c
index a6dd6a0..81f790e 100644
--- a/ompi/datatype/ompi_datatype_args.c
+++ b/ompi/datatype/ompi_datatype_args.c
@@ -713,7 +713,7 @@ static ompi_datatype_t* __ompi_datatype_create_from_args( int32_t* i, MPI_Aint*
         ompi_datatype_create_indexed_block( i[0], i[1], &(i[2]), d[0], &datatype );
         {
             const int* a_i[3] = {&i[0], &i[1], &i[2]};
-            ompi_datatype_set_args( datatype, 2 * i[0], a_i, 0, NULL, 1, d, MPI_COMBINER_INDEXED_BLOCK );
+            ompi_datatype_set_args( datatype, i[0] + 2, a_i, 0, NULL, 1, d, MPI_COMBINER_INDEXED_BLOCK );
         }
         break;
         /******************************************************************/
```

**Comment by jsquyres** [comment]
Looks like George fixed this in open-mpi/ompi@015d3f56cf749ee5ad9ea4428d2f5da72f9bbe08

**Pull request closed without merging**
