### PR TITLE
configury: disable CMA at configure-time via the --without-cma option

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Sascha Hunold for the report

Fixes open-mpi/ompi#3270

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by hppritcha** [comment]
Not clear we need this if #3272 is merged into master.

**Comment by ggouaillardet** [comment]
per my comment in #3270, only one PR from #3272 and #3275 should be merged

**Comment by jsquyres** [comment]
@ggouaillardet This PR should now be closed without merging, right?

**Comment by ggouaillardet** [comment]
#3272 has been merged, so i will simply close this PS

**Pull request closed without merging**
