### PR TITLE
v5.0.x: Initialize opal/smsc outside of btl/sm, to enable its use without it

### PR DESCRIPTION
**Pull request by gkatev**
#10897 for v5.0.x
Signed-off-by: George Katevenis <gkatev@ics.forth.gr>

@awlauria

### CODE REVIEW

**Comment by awlauria** [comment]
ok to test

**Comment by awlauria** [comment]
bot:as:retest

**Comment by awlauria** [comment]
bot:aws:retest

**Review by devreal — APPROVED** [review]

**Pull request merged**
