### PR TITLE
Cleanup pmix selection and map-by modifiers

### LINKED ISSUE #5482: Older mpirun syntax works but newer one doesn't
Thank you for taking the time to submit an issue!

## Background information

I'm running a python script with TensorFlow and Horovod to train a model across 4 nodes that are on the same network. If I use the newer syntax of `mpirun --map-by ppr:pe` the job fails. If I use the older format of `mpirun --map-by socket -cpus-per-proc` the job succeeds.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

3.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

I download and built 3.0.0 from source.

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: Intel Xeon 6148 CPU
* Network type: LAN TCP/IP

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:

I download and build openMPI 3.0.0 from source and then use it with TensorFlow 1.8 and Horovod to train a model over 4 machines in a local network (all CPUs, no GPU).

If I run the command with the newer syntax `mpirun mpirun --map-by ppr:pe` the job fails with the error:

```--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.
 
  HNP daemon   : [[55014,0],0] on node skl-node1
  Remote daemon: [[55014,0],1] on node skl-node2
 
This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------```

However, if I run the same thing with the older (soon to be deprecated) syntax it works:  

`mpirun --map-by socket -cpus-per-proc`

I've run this on several different local networks with different machines. If I run the newer syntax but stick to running on a single node (i.e. -H localhost), then that works too. 

Is there some additional flag that the older syntax automatically adds that I need for the newer syntax?

Thanks.
-Tony

### PR DESCRIPTION
**Pull request by rhc54**
this  fixes #5482

### CODE REVIEW

**Comment by hppritcha** [comment]
this fixes https://github.com/open-mpi/ompi/issues/5482

**Comment by hppritcha** [comment]
@ggouaillardet please check when you have chance

**Comment by hppritcha** [comment]
@ggouaillardet ping

**Comment by ggouaillardet** [comment]
I will be back on 8/16.

Please reassign this PR if urgent.

**Pull request merged**
