### PR TITLE
Pr/sharedfp append fix v2.0.x

### PR DESCRIPTION
**Pull request by edgargabriel**
Fixes a bug reported on the mailing list. ompio did only reposition the individual
file pointer when the file was opened in append mode. Set the shared file
pointer also to point to the end of the file, similarly to the individual
file pointer.

This is the equivalent to commit d3a8d38
on master, cannot be cherry-picked because of differences in the organization
of the ompio files ( usage of mca/common/ompio on master).

### CODE REVIEW

**Comment by jsquyres** [comment]
@edgargabriel Got a compile fail:

```
io_ompio_file_open.c: In function 'ompio_io_ompio_file_open':
io_ompio_file_open.c:257:17: error: 'shared_fp_base_module' undeclared (first use in this function)
                 shared_fp_base_module = ompio_fh->f_sharedfp;
                 ^
io_ompio_file_open.c:257:17: note: each undeclared identifier is reported only once for each function it appears in
```

Can you have a look?

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/67e65d9823b05c596456c25f9b560ef0

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/e5df2d6317ee8e58798fb2a9ac2a3d9d

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/d1f0dc9ac8383165963718d6a64e667d

**Comment by edgargabriel** [comment]
fixed the patch, compiled and run my testsuite with v2.0.x  to be safe, seems to work.

**Comment by edgargabriel** [comment]
Hm. I'm seeing on master some problems that I did not have yesterday, not sure what changed. I fixed the issues there. It does not happen on v2.0.x, right now, but it actually should. I would prefer to add one more commit to this pr to be on the safe side,.  Will work on this later today.

**Comment by edgargabriel** [comment]
ok, but please hold back with merging. As I mentioned, we might have to bring in another commit.

**Comment by jsquyres** [comment]
@edgargabriel Oh!  I missed your comment above -- got it.  Will wait; thanks.  If you have to choose on where to spend your time, fixing the bug should be considered more important than s/opal_output/opal_show_help/.  Thanks!

**Comment by edgargabriel** [comment]
travis did not finish for the master branch, everything else worked. I tested this patch on 2.0.x fairly thoroughly, so I think we can start to evaluate the overall patch in parallel to master.

**Comment by edgargabriel** [comment]
@jsquyres regarding the conversion to use show_help() instead of opal_output(), I would prefer to do that on master first. I can look into this, but am right now a little tight on time, so I would prefer to postpone  this a bit (february/march roughly), unless you think it is critical.

**Comment by jsquyres** [comment]
@edgargabriel Nah, I think the show_help() thing can wait.  Not critical for v2.0.2, but it should be done at some point.

**Comment by jsquyres** [comment]
@edgargabriel Is this now done?

**Comment by jsquyres** [comment]
@edgargabriel We're going to make an RC tomorrow.  Let us know if you can finish this in time.  Thanks!

**Comment by edgargabriel** [comment]
it is in theory done, I would have prefered to see the results of the MTT overnight before we merge it into v2.0.x, but we can go ahead and look at both MTT results.

**Comment by jsquyres** [comment]
@edgargabriel We're having lots of discussions about time-based releases here.  We're trying this out by saying "2.0.2 RC tomorrow.  Get your fixes in."  I'll bring you up to speed out-of-band... 😄

**Comment by edgargabriel** [comment]
@jsquyres I was actually ready with the fix yesterday around noon, but travis was basically hanging, and I could merge the pr on master only in this morning. Anyway, I will support your decision whether you decide to merge before the rc candidate is created or not.

**Comment by jsquyres** [comment]
Cool.  Travis has been out to lunch recently.  We'll go ahead and merge this for v2.0.2 tomorrow morning, just to check MTT overnight.

**Comment by hppritcha** [comment]
@edgargabriel could you post the url of the email on the mail list where this problem was originally reported?  thanks.

**Comment by edgargabriel** [comment]
Sure, its

https://mail-archive.com/users@lists.open-mpi.org/msg30510.html

**Comment by edgargabriel** [comment]
The new MTT on master looks good, the MPI I/O errors from the night before are gone as far as I can see.

**Pull request merged**
