### PR TITLE
Rel v2.x pr3500 pr3635

### PR DESCRIPTION
**Pull request by gpaulsen**
Cherry-picking to v2.x from PR3500 and PR3635 per Issue 3538

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/89e5087f5927f1032142068b75ac0b38

**Comment by jsquyres** [comment]
@gpaulsen Can you please use a bit more descriptive title in the future?  And assign a milestone?

We only saw this PR by accident (because it didn't have a milestone attached)

**Comment by gpaulsen** [comment]
sure.

**Comment by gpaulsen** [comment]
@jsquyres - please review.

**Comment by gpaulsen** [comment]
@jsquyres, Thanks.  I'm not sure what happened there.  I guess I thought that if there were merge conflicts the authorship would be changed over to the merge conflict resolver (since it's a new hash)?

**Pull request merged**
