### PR TITLE
Adding changes for issue #6303 for branch master.

### PR DESCRIPTION
**Pull request by uberlinuxguy**
Patch to master to address possible race condition mentioned in #6303

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by uberlinuxguy** [comment]
The faillure on the "Pull Request Build Checker" appears to be a failure on the Jenkins server.  The log said something about "Disk Quota Exceeded." for the cray build

**Comment by gpaulsen** [comment]
bot:ibm:retest - Network issue?

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
I pinged @hppritcha again about the Cray CI issue.  He is investigating.  The IBM failures are a different issue; apparently @gpaulsen is investigating.

@uberlinuxguy We do require a signed-off-by line on your commits, though.  Can you please squash and signoff, per @hjelmn's comment?  Thanks!

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hjelmn** [comment]
Will PR this to release branches.

**Comment by hjelmn** [comment]
@rhc54 Relevant to PRRTE.

**Comment by rhc54** [comment]
@hjelmn Thanks for the heads up!

**Pull request merged**
