### PR TITLE
fortran/use-mpi-f08: add MPI C types

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refers open-mpi/ompi#5801

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f17fe24388064c34fcdb730d3d0cd27e

**Comment by jsquyres** [comment]
Got a compile error w.r.t. `OMPI_MPI_C_FLOAT`.

Also, how about also adding these to the `mpi` module and `mpif.h`?

I.e., these constants should be available in all of the Fortran interfaces.

**Comment by ggouaillardet** [comment]
I fixed `use mpi_f08` and will double check `mpif.h` and `use mpi` tomorrow

**Comment by ggouaillardet** [comment]
@jsquyres the `allctypes` tests work for all Fortran bindings, so I think we are good here.

**Comment by gpaulsen** [comment]
Added target v4.0.x as that's also on open-mpi/ompi#5801

**Comment by ggouaillardet** [comment]
@jsquyres there are `allctypes` tests for all Fortran flavors and they all pass, so from my point of view, it means we are good.

**Comment by jsquyres** [comment]
Ok.

**Pull request merged**
