### PR TITLE
 RTD: use ubuntu-22.04 as ReadTheDoc build OS 

### PR DESCRIPTION
**Pull request by lrbison**

### CODE REVIEW

**Review by wzamazon — APPROVED** [review]
The PR

**Comment by lrbison** [comment]
> wzamazon changed the title ...
I was getting to that!

**Review by jsquyres — APPROVED** [review]

**Comment by rhc54** [comment]
Do we need something similar in PMIx and PRRTE to resolve the RTD failures there? I don't see the corresponding `.readthedocs.yaml` file over there - should it be?

**Comment by jsquyres** [comment]
Are your RTD CI jobs failing?  If so, yes.  If not, probably not...?

I *think* that the failure was in the `linkcheck` Sphinx plugin.  If you copied from us (and I think I/you did...?), you probably have `linkcheck` enabled, and you might need the same thing that this PR did.

**Comment by rhc54** [comment]
Yes, the RTD jobs are all failing with the following error:
```text
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is
compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168
```
I didn't set this up - you did. Afraid I have no idea if `linkcheck` is enabled, nor where that is happening, so I'd need guidance on where/how to fix this.

**Comment by lrbison** [comment]
@rhc54 I'm going to try just opening a PR to add the yaml file, and see if the existing RTD CI picks it up

**Comment by jsquyres** [comment]
@rhc54 Yep, you've got the same problem.

@lrbison Many thanks.

**Comment by lrbison** [comment]
@rhc54 

openpmix: https://github.com/openpmix/openpmix/pull/3065
prrte: https://github.com/openpmix/prrte/pull/1740

**Comment by rhc54** [comment]
Many thanks @lrbison !!

**Pull request merged**
