### PR TITLE
Fix some issues with dynamic algorithm selection in coll/tuned

### PR DESCRIPTION
**Pull request by devreal**
This PR addresses a potential performance issue with the algorithm selection in coll/tuned and some minor issues found while digging into it:

1) Performance: some bcast and allreduce algorithms require the number of elements to be larger than the number of ranks and will fall back to a linear implementation if that is not the case. This hit me bitterly with 4B bcast on 128 ranks on a single node where latency increased 10x compared to 127 ranks.
2) The documentation for the coll_tuned_*_algorithm MCA variables should mention that they only take effect if the coll_tuned_use_dynamic_rules variable is set to true.
3) Mark global static array used for the MCA parameters as const.
4) Fix some glitches in comments.

Backport of https://github.com/open-mpi/ompi/pull/8186 to v4.1.x

### CODE REVIEW

**Review by wckzhang — APPROVED** [review]

**Review by bosilca — APPROVED** [review]

**Comment by devreal** [comment]
I added a commit that removes the selection of linear algorithms in allreduce and allgather. In my measurements the latency for these ranges is higher than necessary and I don't see how that is motivated by previous measurements (it seems unlikely to me that linear algorithms perform well at several dozens or hundreds of ranks).

**Comment by rajachan** [comment]
@devreal ICYMI, something was off with allgatherv too (I'd tested with the 4.1.x branch https://github.com/open-mpi/ompi/pull/8186#issuecomment-724835122). Is that something you are seeing?

**Comment by devreal** [comment]
@rajachan I have not yet looked at allgatherv. I can run some tests for that over night and see. Do remember at what scales things were weird?

**Comment by rajachan** [comment]
I was running with ~1K ranks (32 nodes with 36 ranks per node).

**Comment by rajachan** [comment]
Btw, your master PR is missing the allreduce/allgather commit.

**Comment by devreal** [comment]
> Btw, your master PR is missing the allreduce/allgather commit.

Oops, pushed to the wrong branch. Will fix in a minute

**Comment by wckzhang** [comment]
> Btw, your master PR is missing the allreduce/allgather commit.

Nice catch

**Pull request merged**
