### PR TITLE
Fortran fixes

### LINKED ISSUE #7253: OpenMPI may pick up an old version of mpi.mod from an existing installation for building
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
8b424c38634f764de62a0cdb302a519625cc40f0

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* GCC/GFortran: 7.4.0

-----------------------------

## Details of the problem

OpenMPI was configured as follows:
```
./autogen.pl
./configure --enable-hwloc-pci --with-verbs --with-ucx
```
Then the compilation fails with:
```
  PPFC     cancel_f08.lo
  PPFC     cart_coords_f08.lo
  PPFC     cart_create_f08.lo
  PPFC     cartdim_get_f08.lo
cart_create_f08.F90:12:21:

    use :: mpi, only : PMPI_Cart_create
                     1
Error: Symbol ‘pmpi_cart_create’ referenced at (1) not found in module ‘mpi’
Makefile:4362: recipe for target 'cart_create_f08.lo' failed
make[2]: *** [cart_create_f08.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/marcin/build/openmpi/ompi/mpi/fortran/use-mpi-f08'
Makefile:3496: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/marcin/build/openmpi/ompi'
Makefile:1843: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

the configuration details printed by `configure`:

This happened because there was still a leftover from the previous installation, `/usr/local/include/mpi.mod`. It was picked up by `make` and used for the build of the new version. This is probably a bug, after purging this file the compilation succeeded.

### PR DESCRIPTION
**Pull request by jsquyres**
This is an attempt at fixing #7253 with the originally-proposed mechanism (i.e., zeroing out CPPFLAGS / AM_CPPFLAGS when relevant).  I think the original patch I posted was incomplete -- this one is hypothetically complete.

I went this direction because I don't think @jeffhammond's proposed patches on #7253 were correct -- we shouldn't be using CPPFLAGS / AM_CPPFLAGS for Fortran compilation.  Indeed, the Makefiles in question already set AM_FCFLAGS.  So if those are wrong, let's fix those values.  The problem _appears_ to be the incorrect-for-Fortran values in CPPFLAGS / AM_CPPFLAGS, so let's see if zeroing them out in all relevant places (and as a side-effect, moving the one `.c` file compilation in `use-mpi-f08` into its own subdirectory) fixes the issue.

Fixes #7253 

See the individual commit messages for details.

FYI @jeffhammond @marmistrz

### CODE REVIEW

**Comment by jsquyres** [comment]
This is an attempt at fixing #7253 with the originally-proposed mechanism (i.e., zeroing out CPPFLAGS / AM_CPPFLAGS when relevant).  I think the original patch I posted was incomplete -- this one is hypothetically complete.

I went this direction because I don't think @jeffhammond's proposed patches on #7253 were correct -- we shouldn't be using CPPFLAGS / AM_CPPFLAGS for Fortran compilation.  Indeed, the Makefiles in question already set AM_FCFLAGS.  So if those are wrong, let's fix those values.  The problem _appears_ to be the incorrect-for-Fortran values in CPPFLAGS / AM_CPPFLAGS, so let's see if zeroing them out in all relevant places (and as a side-effect, moving the one `.c` file compilation in `use-mpi-f08` into its own subdirectory) fixes the issue.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/be4f601d51a0a5d426598783172d0a01

**Comment by awlauria** [comment]
That looks to be a real issue with the GNU compiler and this pr:

```
FC       mpi_wtime_f90.lo
mpi.F90:23:0: fatal error: ompi/mpi/fortran/configure-fortran-output.h: No such file or directory
 #include "ompi/mpi/fortran/configure-fortran-output.h"
 ```
After fixing the config issue, other PR's are now passing the ibm build.

**Comment by jsquyres** [comment]
bot:lanl:retest

**Comment by jsquyres** [comment]
@jeffhammond @marmistrz Does this PR fix the issue for you?

**Comment by jeffhammond** [comment]
Unfortunately, no.

```
  GENERATE sizeof_f.f90
  FC       sizeof_f.lo
  FCLD     libmpi_mpifh_sizeof.la
  CCLD     libmpi_mpifh.la
Making all in mpi/fortran/use-mpi-ignore-tkr
  GENERATE mpi-ignore-tkr-sizeof.h
  GENERATE mpi-ignore-tkr-sizeof.f90
  PPFC     mpi-ignore-tkr.lo
  FC       mpi-ignore-tkr-sizeof.lo
  FCLD     libmpi_usempi_ignore_tkr.la
Making all in mpi/fortran/mpiext-use-mpi
  PPFC     mpi-ext-module.lo
mpi-ext-module.F90(7): #error: can't find include file: ompi/mpi/fortran/configure-fortran-output.h
mpi-ext-module.F90(32): #error: can't find include file: ../ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h
mpi-ext-module.F90(33): #error: can't find include file: ../ompi/mpiext/pcollreq/use-mpi/mpiext_pcollreq_usempi.h
mpi-ext-module.F90(38): #error: can't find include file: ompi/mpiext/shortfloat/mpif-h/mpiext_shortfloat_mpifh.h
mpi-ext-module.F90(39): #error: can't find include file: ../ompi/mpiext/shortfloat/use-mpi/mpiext_shortfloat_usempi.h
make[2]: *** [mpi-ext-module.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by jsquyres** [comment]
@jeffhammond Well phooey.  Can you send the output of that failure, but run via `make V=1`?

**Comment by jeffhammond** [comment]
```
Making all in mpi/fortran/mpiext-use-mpi
/bin/sh ../../../../libtool  --tag=FC   --mode=compile ifort -DHAVE_CONFIG_H -I. -I../../../../../ompi/mpi/fortran/mpiext-use-mpi -I../../../../opal/include -I../../../../ompi/include -I../../../../oshmem/include -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/private/autogen -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/hwloc/autogen -I../../../../ompi/mpiext/cuda/c    -I../../../../ompi/include -I../../../../../ompi/include -I../../../../ompi/mpi/fortran/base -I../../../../ompi/mpi/fortran/use-mpi-ignore-tkr -I../../../../..   -c -o mpi-ext-module.lo mpi-ext-module.F90
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I../../../../../ompi/mpi/fortran/mpiext-use-mpi -I../../../../opal/include -I../../../../ompi/include -I../../../../oshmem/include -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/private/autogen -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/hwloc/autogen -I../../../../ompi/mpiext/cuda/c -I../../../../ompi/include -I../../../../../ompi/include -I../../../../ompi/mpi/fortran/base -I../../../../ompi/mpi/fortran/use-mpi-ignore-tkr -I../../../../.. -c mpi-ext-module.F90  -fno-common -o .libs/mpi-ext-module.o
mpi-ext-module.F90(7): #error: can't find include file: ompi/mpi/fortran/configure-fortran-output.h
mpi-ext-module.F90(32): #error: can't find include file: ../ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h
mpi-ext-module.F90(33): #error: can't find include file: ../ompi/mpiext/pcollreq/use-mpi/mpiext_pcollreq_usempi.h
mpi-ext-module.F90(38): #error: can't find include file: ompi/mpiext/shortfloat/mpif-h/mpiext_shortfloat_mpifh.h
mpi-ext-module.F90(39): #error: can't find include file: ../ompi/mpiext/shortfloat/use-mpi/mpiext_shortfloat_usempi.h
make[2]: *** [mpi-ext-module.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by jsquyres** [comment]
@jeffhammond @marmistrz Looks like I missed some `$(top_builddir)` instances in my prior commit.  I think that's now fixed.  Can you try again?

**BE AWARE:** I rebased on top of the current Open MPI git master HEAD, which now uses git submodules.  If you clone/pull/whatever this branch, you may need to:

```
$ git submodule update --init --recursive
```

(and fully `autogen.pl` + `./configure` again) before you can build.

**Comment by jeffhammond** [comment]
```
Making all in mpi/fortran/use-mpi-ignore-tkr
make[2]: Nothing to be done for `all'.
Making all in mpi/fortran/mpiext-use-mpi
make[2]: Nothing to be done for `all'.
Making all in mpi/fortran/use-mpi-f08/base
make[2]: Nothing to be done for `all'.
Making all in mpi/fortran/use-mpi-f08/mod
make[2]: Nothing to be done for `all'.
Making all in mpi/fortran/use-mpi-f08/bindings
make[2]: Nothing to be done for `all'.
Making all in mpiext/pcollreq/use-mpi-f08
/bin/sh ../../../../libtool  --tag=FC   --mode=compile ifort -DHAVE_CONFIG_H -I. -I../../../../../ompi/mpiext/pcollreq/use-mpi-f08 -I../../../../opal/include -I../../../../ompi/include -I../../../../oshmem/include -I../../../../opal/mca/hwloc/hwloc2/hwloc/include/private/autogen -I../../../../opal/mca/hwloc/hwloc2/hwloc/include/hwloc/autogen -I../../../../ompi/mpiext/cuda/c   -I../../../../.. -I../../../.. -I../../../../../opal/include -I../../../../../orte/include -I../../../../orte/include -I../../../../../ompi/include -I../../../../../oshmem/include -I/Users/jrhammon/Work/MPI/OMPI/github/build/opal/mca/event/libevent2022/libevent/include -I/Users/jrhammon/Work/MPI/OMPI/github/opal/mca/event/libevent2022/libevent -I/Users/jrhammon/Work/MPI/OMPI/github/opal/mca/event/libevent2022/libevent/include -I/Users/jrhammon/Work/MPI/OMPI/github/build/opal/mca/hwloc/hwloc2/hwloc/include -I/Users/jrhammon/Work/MPI/OMPI/github/opal/mca/hwloc/hwloc2/hwloc/include   -I/usr/local/include -I/usr/local/include -I../../../../ompi/mpi/fortran/use-mpi-f08/mod -I../../../../..   -c -o mpiext_pcollreq_f08.lo ../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I../../../../../ompi/mpiext/pcollreq/use-mpi-f08 -I../../../../opal/include -I../../../../ompi/include -I../../../../oshmem/include -I../../../../opal/mca/hwloc/hwloc2/hwloc/include/private/autogen -I../../../../opal/mca/hwloc/hwloc2/hwloc/include/hwloc/autogen -I../../../../ompi/mpiext/cuda/c -I../../../../.. -I../../../.. -I../../../../../opal/include -I../../../../../orte/include -I../../../../orte/include -I../../../../../ompi/include -I../../../../../oshmem/include -I/Users/jrhammon/Work/MPI/OMPI/github/build/opal/mca/event/libevent2022/libevent/include -I/Users/jrhammon/Work/MPI/OMPI/github/opal/mca/event/libevent2022/libevent -I/Users/jrhammon/Work/MPI/OMPI/github/opal/mca/event/libevent2022/libevent/include -I/Users/jrhammon/Work/MPI/OMPI/github/build/opal/mca/hwloc/hwloc2/hwloc/include -I/Users/jrhammon/Work/MPI/OMPI/github/opal/mca/hwloc/hwloc2/hwloc/include -I/usr/local/include -I/usr/local/include -I../../../../ompi/mpi/fortran/use-mpi-f08/mod -I../../../../.. -c ../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90  -fno-common -o .libs/mpiext_pcollreq_f08.o
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(29): error #7013: This module file was not generated by any release of this compiler.   [MPI_F08_TYPES]
  use mpi_f08_types
------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(285): error #7013: This module file was not generated by any release of this compiler.   [MPI_F08_TYPES]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
----------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(285): error #6580: Name in only-list does not exist or is not accessible.   [MPI_DATATYPE]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
--------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(285): error #6580: Name in only-list does not exist or is not accessible.   [MPI_COMM]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
----------------------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(285): error #6580: Name in only-list does not exist or is not accessible.   [MPI_REQUEST]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
--------------------------------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(316): error #7013: This module file was not generated by any release of this compiler.   [MPI_F08_TYPES]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
----------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(316): error #6580: Name in only-list does not exist or is not accessible.   [MPI_DATATYPE]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
--------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(316): error #6580: Name in only-list does not exist or is not accessible.   [MPI_COMM]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
----------------------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(316): error #6580: Name in only-list does not exist or is not accessible.   [MPI_REQUEST]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request
--------------------------------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(331): error #6580: Name in only-list does not exist or is not accessible.   [MPI_ADDRESS_KIND]
   use :: mpi_f08_types, only : MPI_Datatype, MPI_Comm, MPI_Request, MPI_ADDRESS_KIND
---------------------------------------------------------------------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(336): error #6683: A kind type parameter must be a compile-time constant.   [MPI_ADDRESS_KIND]
   INTEGER(MPI_ADDRESS_KIND), INTENT(IN) :: sdispls(*), rdispls(*)
-----------^
compilation aborted for ../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90 (code 1)
make[2]: *** [mpiext_pcollreq_f08.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

```
jrhammon-mac02:build jrhammon$ git status
On branch fortran-you-win-again
Your branch is up to date with 'jsquyres/pr/fortran-you-win-again'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   ../opal/mca/hwloc/hwloc2/hwloc (untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./

no changes added to commit (use "git add" and/or "git commit -a")
jrhammon-mac02:build jrhammon$ git log -1
commit 259debc5fc28c402824e9204a223663a5d2b7d0e (HEAD -> fortran-you-win-again, jsquyres/pr/fortran-you-win-again)
Author: Jeff Squyres <jsquyres@cisco.com>
Date:   Tue Dec 31 07:06:51 2019 -0800

    fortran: ensure not to use [AM_]CPPFLAGS
    
    Automake's Fortran compilation rules inexplicably use CPPFLAGS and
    AM_CPPFLAGS.  Unfortunately, this can cause problems in some cases
    (e.g., picking up already-installed mpi.mod in a system-default
    include search path).
    
    So in relevant module-using Fortran compilation Makefile.am's, zero
    out CPPFLAGS and AM_CPPFLAGS.
    
    This has a side-effect of requiring that we compile the one .c file in
    the F08 library in a new, separate subdirectory (with its own
    Makefile.am that does _not_ have CPPFLAGS/AM_CPPFLAGS zeroed out).
    
    Signed-off-by: Jeff Squyres <jsquyres@cisco.com>
```

**Comment by jsquyres** [comment]
Do you have stale build artifacts?

```
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(29): error #7013: This module file was not generated by any release of this compiler.   [MPI_F08_TYPES]
  use mpi_f08_types
------^
../../../../../ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_f08.F90(285): error #7013: This module file was not generated by any release of this compiler.   [MPI_F08_TYPES]
```

**Comment by jeffhammond** [comment]
That is unlikely.  I ran `git clean -dfx` and `git reset --hard`, switch to master, did an update, then checkout out your branch from scratch before running `autogen.pl` etc.

**Comment by ggouaillardet** [comment]
@jsquyres did you omit to push (similar) changes to (at least) `ompi/mpiext/pcollreq/use-mpi-f08/Makefie.am`

**Comment by ggouaillardet** [comment]
@jsquyres I made the changes and pushed them into this PR

@jeffhammond could you please give this updated PR an other try?

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
@jeffhammond Ping.

**Comment by jeffhammond** [comment]
It now compiles without error. Hooray!

**Comment by jsquyres** [comment]
Squashed @ggouaillardet's commit into the 1st commit.  When this finishes CI, I'll merge.

**Pull request merged**
