### PR TITLE
v5.0: Update PMIx/PRRTE pointers for release

### PR DESCRIPTION
**Pull request by rhc54**
Bring the PMIx pointer to the lz1 (landing zone 1) of the v4.1.1 branch.
Bring PRRTE pointer to the lz1 (landing zone 1) of v2.0.1 branch.

Fixes https://github.com/open-mpi/ompi/issues/9627
(as well as other things)

Signed-off-by: Ralph Castain <rhc@pmix.org>
bot:notacherrypick

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b79014ee6da951def56c2d1eabdc69e2

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/aa4cb877017776745036d5d6eaef87b2

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ab61a4c3383a7f1d0803631ff5503da6

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
Hold up on this for a bit - I need to update the pmix/prrte pointers (include the NEWS/VERSION changes), and I want to remove the mpirun change so we can take https://github.com/open-mpi/ompi/pull/9645 in its place. Will do the latter as a separate cherry-pick PR.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2057d277400ee91fec1f6526baabb922

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/555b635494bd0b9db32da55ad29cbe3d

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1e30be77f0184c79b7b49bb5263d36fd

**Comment by rhc54** [comment]
@awlauria @gpaulsen I'm going to need some help here, guys. The tests are failing because the dstore shmem plugin is unable to create the backing file. I have no idea why and cannot diagnose from here.

FWIW: we pass all the IBM CI tests for both PMIx and PRRTE on these branches, so it looks like it is something to do with the CI system itself.

**Comment by awlauria** [comment]
I'll try taking a look

**Comment by jjhursey** [comment]
It looks like the Mellanox CI is hitting the same issue that the IBM CI is hitting. So that points to something that is not CI machine specific.
```
+ timeout -s SIGSEGV 17m /__w/1/ompi/ompi_install/bin/mpirun --np 4 --bind-to none --report-state-on-timeout --get-stack-traces --timeout 900 -x UCX_NET_DEVICES=mlx5_1:1 --mca pml ucx /__w/1/ompi/ompi_install/examples/hello_c ''
[swx-jupiter04:27719] PMIX ERROR: ERROR in file dstore_segment.c at line 116
[swx-jupiter04:27719] PMIX ERROR: OUT-OF-RESOURCE in file gds_ds21_lock_pthread.c at line 176
[swx-jupiter04:27719] PMIX ERROR: SUCCESS in file dstore_base.c at line 2497
[swx-jupiter04:27719] PMIX ERROR: ERROR in file dstore_segment.c at line 207
[swx-jupiter04:27719] PMIX ERROR: OUT-OF-RESOURCE in file dstore_base.c at line 664
```

**Comment by rhc54** [comment]
I agree, but I have no way of reproducing it. Everything here works fine, it passes all of your CI tests - no place for me to go.

**Comment by awlauria** [comment]
Doing some local tests, prterun works fine, but mpirun isn't very happy. @rhc54 is that what you are seeing?

**Comment by awlauria** [comment]
It isn't CI specific, I can reproduce on multiple machines.

**Comment by rhc54** [comment]
Will fix in a bit - think I see the problem, but have to run out for awhile.

**Comment by rhc54** [comment]
The change to mpirun depends upon some configure changes, so it needs to be cherry-picked from #9645. It worked locally for me due to some envars I had set, but would fail for anyone not having that environment. I have removed that change from this PR - let's see if this now passes.

**Comment by rhc54** [comment]
@awlauria @gpaulsen @janjust I have marked these PMIx/PRRTE versions as "landing zone 1" in lieu of our usual "release candidate" notation as these branches are not going to be released. Once this PR is clean and committed, I'll tag the two branches accordingly so you always have a reference point. Future updates to those branches will likewise be tagged as "landing zone N". If we ever do decide to formally release, we'll generate a traditional "release candidate" tag at that time.

**Comment by rhc54** [comment]
sigh...java failures

bot:aws:retest

**Comment by gpaulsen** [comment]
@rhc54 Hmm... Are you saying that our sub module pointers will point to a non-release branch version of PMIx / PRRTE?
My understanding is that we're upgrading the Open MPI v5.0.x submodule pointers to point to release branch versions of PMIx / PRRTE for testing purposes, but that before Open MPI v5.0.0 releases, we'd have releases of PMIx and PRRTE that we point to from Open MPI v5.0.x branch?

Has that plan changed or am I incorrect?

**Comment by rhc54** [comment]
Grrrr...more CI failures!
```
--------------------------------------------------------------------------
Unable to locate the variable file:
   /__w/1/ompi/test_amca.conf
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Unable to locate the variable file:
   /__w/1/ompi/test_amca.conf
--------------------------------------------------------------------------
```
/azp run

**Comment by rhc54** [comment]
> @rhc54 Hmm... Are you saying that our sub module pointers will point to a non-release branch version of PMIx / PRRTE? My understanding is that we're upgrading the Open MPI v5.0.x submodule pointers to point to release branch versions of PMIx / PRRTE for testing purposes, but that before Open MPI v5.0.0 releases, we'd have releases of PMIx and PRRTE that we point to from Open MPI v5.0.x branch?
> 
> Has that plan changed or am I incorrect?

You weren't paying attention, mein herr. No, you won't be pointed at an official PMIx/PRRTE release for OMPI v5.0 because your configure logic is no longer compatible. Instead, you will be pointed at a "landing zone" - a tagged point on a branch that contains the old configure logic. We will not be releasing from those branches. Instead, we are releasing from branches that contain the new configure logic.

So you'll have a tag you can refer back to for both PMIx/PRRTE - it just won't be a public release branch, but rather a private branch for OMPI v5. The branches have been brought up-to-date with bug fixes, and you folks can do whatever you like to those branches in terms of the configure logic. I'll continue to try and keep them tracking with any more changes prior to your release, so long as those changes don't impact the configure code.

**Comment by gpaulsen** [comment]
I see.  I thought that was master only of PMIx/PRRTE not on your release branches.  I thought that OMPI v5 was already tracking your release branches.  (one big drawback of submodule pointers, is that it's just a hash and extra work is needed to see the corrisponding branch(es)).

**Comment by awlauria** [comment]
FWIW I don't see these "landing zones" under tags nor branches.

What are these pointers pointing to now?

**Comment by rhc54** [comment]
> FWIW I don't see these "landing zones" under tags nor branches.
> 
> What are these pointers pointing to now?

Right now, you are pointing to the HEAD of the PMIx v4.1 and the PRRTE v2.0 branches. Once we get thru CI, I will "tag" that point on those branches with their respective "LZ1" designation - e.g., "v4.1.1LZ1". This will give you a fixed reference point you can refer back to when needed.

This is really very similar to the way OMPI treats old branches. We push bug fixes into them, but don't release them any more - if someone wants to continue on that branch and needs a fix, they can simply download and use it. In this case, because you are using the branch in a release of your own, and because the incompatibility is something that I induced fairly recently, I'm going to actually tag the branch to mark where your release took its embedded version.

Remember, the only difference between PMIx v4.1.1 and PMIx v4.2.0 is the configure change (ditto for the PRRTE branches). So this allows you to continue your planned release timeline without impact, and we can deal with the configure issue down the road.

**Comment by rhc54** [comment]
@Artemy-Mellanox We keep hitting this error:
```
--------------------------------------------------------------------------
Unable to locate the variable file:
   /__w/1/ompi/test_amca.conf
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Unable to locate the variable file:
   /__w/1/ompi/test_amca.conf
--------------------------------------------------------------------------
```
I'm not seeing where it is supposed to have been created - did something get changed here?

**Comment by rhc54** [comment]
I found where this file is supposed to be created - however, it appears there is something wrong with the `WORKSPACE` the script was provided that prevents the file from being created. Can someone please investigate?

**Comment by awlauria** [comment]
@rhc54 other v5.0.x PR's are passing right now - not sure it is CI environment related.

**Comment by rhc54** [comment]
Hmmm...okay, though I'm hard-pressed to understand how "cannot find the specified file" would be happening. I'll probably have to pass on this problem and let someone (a) from the OMPI side, since this is an OMPI option, and (b) who cares about "tune" files resolve it. I have other things that need doing 😄

**Comment by rhc54** [comment]
You need https://github.com/open-mpi/ompi/pull/9645 to go along with this one to fix the "mpirun" name for help messages. This one contains the PRRTE side of things.

**Comment by artemry-nv** [comment]
> @Artemy-Mellanox We keep hitting this error:
> 
> ```
> --------------------------------------------------------------------------
> Unable to locate the variable file:
>    /__w/1/ompi/test_amca.conf
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> Unable to locate the variable file:
>    /__w/1/ompi/test_amca.conf
> --------------------------------------------------------------------------
> ```
> 
> I'm not seeing where it is supposed to have been created - did something get changed here?

Checking.

**Comment by artemry-nv** [comment]
As far as I see it's passed now. Is the issue still actual?

**Comment by rhc54** [comment]
@artemry-nv No - I found the problem in the code (a misplaced '}'). It is good now.

**Comment by rhc54** [comment]
dropping

**Comment by awlauria** [comment]
Closed in favor of #9825

**Pull request closed without merging**
