### PR TITLE
v3.1.x aarch64 support

### PR DESCRIPTION
**Pull request by hjelmn**
These commits improve the aarch64 support as promised. The three commits:
 1) Fix debug builds (and update the README to reflect this).
 2) Make the patcher code work with aarch64.

### CODE REVIEW

**Comment by hjelmn** [comment]
@bwbarrett I can create a PR for v3.0.x as well. I don't know how far back we want to bring this.

**Comment by hjelmn** [comment]
@gpaulsen FYI. This fixes some power hangs with debug builds + non-builtin atomics as well.

**Comment by gpaulsen** [comment]
@hjelmn Thanks.  I can give it a spin on our power9 nodes also.

**Comment by gpaulsen** [comment]
@hjelmn I'd love a PR for v3.0.x if you have time, otherwise I can give it a stab.

**Comment by hjelmn** [comment]
@gpaulsen The v3.0.x version was merged into the v3.0.x branch this morning.

**Pull request merged**
