### PR TITLE
Update bml.h

### PR DESCRIPTION
**Pull request by jo-pillar**
BML is short for BTL Management Layer instead of BML Management Layer. I have  corrected it. #11243 
Signed-off-by: zhuo dong wu jopillar11@gmail.com

### CODE REVIEW

**Comment by jsquyres** [comment]
Good catch!  Hard to believe we've had that typo for years and years (!!). 😲 

Per the bot notice, can you update your commit to have a signed-off-by line?  Please see https://docs.open-mpi.org/en/main/contributing.html#contributor-s-declaration.

**Comment by jsquyres** [comment]
@jo-pillar You need to update your git commit (e.g., `git commit -s --amend && git push --force`), not the description on the pull request.

**Comment by jo-pillar** [comment]
> @jo-pillar You need to update your git commit (e.g., `git commit -s --amend && git push --force`), not the description on the pull request.

tks, i am new to the open source world,  it will take a while for me.

**Comment by jsquyres** [comment]
> tks, i am new to the open source world, it will take a while for me.

No worries; sorry for the hassle -- the doc link I provide above explains why we need your agreement to the contributor's declaration.

The commands I cited -- `git commit -s --amend` followed by `git push --force` should add the required signed-off-by-line and then push it up to your fork, which will update the PR (you may need to specify the git remote in the 2nd command -- such as `git push --force myfork` -- if you cloned the Open MPI repo, not your github fork).

**Pull request closed without merging**
