### PR TITLE
RFC: Remove embedded libltdl

### PR DESCRIPTION
**Pull request by jsquyres**
Per #311, and per the discussions in the [Dallas OMPI dev meeting](https://github.com/open-mpi/ompi/wiki/Meeting-2015-01), remove the embedded libltdl from Open MPI.

There are two minor commits and then the major commit of removing the libltdl:

1. Remove some extraneous $(LTDLINCL)s
1. Add lt_dladvise support into ompi_info and friends
1. Remove embedded libltdl

There was some discussion in Dallas about what the default should be if libltdl support is not found on a machine when building Open MPI.  Here's the behavior defined in the initial version of this PR, which I think gives a good compromise of what everyone wanted:

* If `--disable-dlopen` is specified, it behaves as it always has: libltdl support is wholly disabled, and all plugins are slurped into their higher-level libraries.
* If `--enable-dlopen` is specified, configure will abort if it cannot find properl libltdl support.
* If neither of these are specified, configure will behave differently between a developer build (i.e., where a .git directory is present in the source tree) and non-developer build:
  * In a developer build, `--enable-dlopen` is assumed (i.e., configure will abort if libltdl support cannot be found).  `--disable-dlopen` must be specified if you do not have libltdl support.
  * In a non-developer build:
    * If configure finds libltdl support, it will build dlopen support and build plugins as DSOs.
    * If configure does not find libltdl support, it will disable dlopen support and slurp plugins into higher level libraries.

The developer build behavior is because dlopen support is usually highly valued (e.g., being able to repeatedly build individual plugins), and libltdl-devel may not be installed by default on Linux distros and OSX.  Hence, developers may inadvertently build without dlopen support without this special developer-build provision.

* Original issue that spawned this PR: open-mpi/ompi#311 (Open MPI can't build with Libtool >= 2.4.3)
* Alternate solution to fix open-mpi/ompi#311: PR open-mpi/ompi#390 (fully embed libltdl in the source tree)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/199/

**Build Log**
*last 50 lines*

 ```
[...truncated 1691 lines...]
checking for struct statvfs.f_basetype... no
checking for struct statvfs.f_fstypename... no
checking for pointer diff type... ptrdiff_t (size: 8)
checking for type of MPI_Aint... ptrdiff_t (size: 8)
checking for type of MPI_Count... long long (size: 8)
checking for type of MPI_Offset... long long (size: 8)
checking for an MPI datatype for MPI_Offset... MPI_LONG_LONG
checking for MPI_INTEGER_KIND... 4
checking for MPI_ADDRESS_KIND... 8
checking for MPI_COUNT_KIND... 8
checking for MPI_OFFSET_KIND... 8

============================================================================
== Library and Function tests
============================================================================
checking for library containing openpty... -lutil
checking for library containing gethostbyname... none required
checking for library containing socket... none required
checking for library containing sched_yield... none required
checking for library containing dirname... none required
checking for library containing ceil... -lm
checking for library containing clock_gettime... -lrt
checking ltdl.h usability... no
checking ltdl.h presence... no
checking for ltdl.h... no
configure: WARNING: Cannot find libltdl support,
configure: WARNING: but --enable-dlopen was specified
configure: WARNING: or this is a developer build.
configure: error: Cannot continue.
+ '[' no = yes ']'
+ '[' no = yes ']'
+ '[' -n 1 ']'
+ '[' no = yes ']'
++ echo /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ '[' yes = yes ']'
+ exe_dir=/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples
+ '[' '!' -d /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples ']'
+ echo 'Running examples for /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1'
Running examples for /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ cp -prf /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/examples /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1
+ PATH=/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib:
+ make -C /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples all
make: *** /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples: No such file or directory.  Stop.
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/200/

**Build Log**
*last 50 lines*

 ```
[...truncated 1691 lines...]
checking for struct statvfs.f_basetype... no
checking for struct statvfs.f_fstypename... no
checking for pointer diff type... ptrdiff_t (size: 8)
checking for type of MPI_Aint... ptrdiff_t (size: 8)
checking for type of MPI_Count... long long (size: 8)
checking for type of MPI_Offset... long long (size: 8)
checking for an MPI datatype for MPI_Offset... MPI_LONG_LONG
checking for MPI_INTEGER_KIND... 4
checking for MPI_ADDRESS_KIND... 8
checking for MPI_COUNT_KIND... 8
checking for MPI_OFFSET_KIND... 8

============================================================================
== Library and Function tests
============================================================================
checking for library containing openpty... -lutil
checking for library containing gethostbyname... none required
checking for library containing socket... none required
checking for library containing sched_yield... none required
checking for library containing dirname... none required
checking for library containing ceil... -lm
checking for library containing clock_gettime... -lrt
checking ltdl.h usability... no
checking ltdl.h presence... no
checking for ltdl.h... no
configure: WARNING: Cannot find libltdl support,
configure: WARNING: but --enable-dlopen was specified
configure: WARNING: or this is a developer build.
configure: error: Cannot continue.
+ '[' no = yes ']'
+ '[' no = yes ']'
+ '[' -n 1 ']'
+ '[' no = yes ']'
++ echo /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ '[' yes = yes ']'
+ exe_dir=/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/examples
+ '[' '!' -d /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/examples ']'
+ echo 'Running examples for /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1'
Running examples for /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1
+ cp -prf /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/examples /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1
+ PATH=/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/lib:
+ make -C /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/examples all
make: *** /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace-2/ompi_install1/examples: No such file or directory.  Stop.
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by jsquyres** [comment]
@miked-mellanox Can you please install libltdl-devel on the build system (or whatever RPM includes ltdl.h)?

**Comment by rhc54** [comment]
Also need to warn all MTT installations!

**Comment by miked-mellanox** [comment]
retest this please

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/201/
Test PASSed.

**Comment by miked-mellanox** [comment]
done, btw on rhel 6.5 it is libtool-ltdl-devel

**Comment by jsquyres** [comment]
Yes, good point -- MTT installations as a good barometer for what will happen in the rest of the world...

I.e., I'll bet that that with this RFC, many (most?) users will effectively be building with --disable-dlopen.  This may not be a tragedy, though.

**Comment by miked-mellanox** [comment]
maybe --disable-dlopen should be the default than?
when --disable-dlopen is used, does it mean that rpath and compile time linker is used instead?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/202/
Test PASSed.

**Comment by jsquyres** [comment]
There is an assumption that developers will highly value dlopen functionality.  See what I just posted here: http://www.open-mpi.org/community/lists/devel/2015/01/16851.php

Actually, I take back what I said above: if MTT installations are only testing tarballs, they won't see this problem (because they'll all build with `--disable-dlopen` by default if there is no ltdl-devel support).  And if MTT installations are only testing with already-installed MTT install sections, then MTT won't be affected by whether ltdl-devel is available or not.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/203/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/204/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/207/
Test PASSed.

**Comment by jsquyres** [comment]
This PR is one option for fixing #311.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/214/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/224/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/226/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/227/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/228/
Test PASSed.

**Comment by jsquyres** [comment]
Per discussion on the 17 Feb 2015 Tuesday webex, we have decided to use the "embed libltdl" approach (i.e., #390) instead of this "remove libltdl" approach.  So I'm closing this PR.

**Pull request closed without merging**
