### PR TITLE
Remove the old patterns, they are not in use.

### PR DESCRIPTION
**Pull request by bosilca**
Bring #12554 to the 5.x

Signed-off-by: George Bosilca <gbosilca@nvidia.com>
(cherry picked from commit e6e5c9455309e19974dc2c15983ddb434b3a786b)

### CODE REVIEW

**Comment by wenduwan** [comment]
@bosilca Question: would this cause any API/ABI compatibility issue?

**Comment by bosilca** [comment]
They were built but not used. I don't foresee any impact.

**Comment by wenduwan** [comment]
@bosilca Could you look at the RTD build issue?

**Comment by jsquyres** [comment]
Looks like there was a transient error at RTD; I kicked off a new build for this PR.

**Comment by wenduwan** [comment]
@bosilca Can you remove the redundant merge commit?

**Comment by wenduwan** [comment]
@janjust Do you have any qualm merging this to v5.0.x?

**Review by wenduwan — APPROVED** [review]

**Pull request merged**
