### PR TITLE
hwloc v2.1.0: use a git submodule

### PR DESCRIPTION
**Pull request by jsquyres**
## Update

This PR changed a little since it was first created.  Short version:

* Rename `hwloc210` component to `hwloc2`
* Make a submodule that now points to the `hwloc-2.1.0` tag in the hwloc repo

-----

## Original

Remove the entire opal/mca/hwloc/hwloc201/hwloc directory, which was
just an expended hwloc v2.0.1 tarball.  Replace it with a git
submodule pointing to https://github.com/open-mpi/hwloc.git at the
hash 4fe5f41804eaf2bcd84e7ac98dc82f6e3df04b86, which is equivalent to
the hwloc-2.0.1 tag.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

This is a first foray into git submodules: just replace `opal/mca/hwloc/hwloc201/hwloc` (which is just an expanded hwloc v2.0.1 tarball) with a git submodule pointing to the hwloc github repo, pointing at the hash that is the `hwloc-2.0.1` tag.  There will be no auto-updating this submodule: it's just a way for a) us to stop physically embedding the hwloc source code in our repository, and b) to learn a bit about git submodules before we start using them more extensively elsewhere in the Open MPI code base.

This PR will almost certainly fail CI until Jenkins learns how to `git clone --recursive ...`.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cca2c89141b7b909763ab9f20326e0ca

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/40a14639e53859eb0eec216dbb7de806

**Comment by bgoglin** [comment]
How do you tell OMPI's make dist to include hwloc's stuff?

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5033953522bcf1fb18d9367bcb2c3f82

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e395844040443dc0ea768d352014408a

**Comment by jsquyres** [comment]
@bgoglin When you `git clone --recursive ...` the OMPI repo, you'll get a full copy of the hwloc repo at 4fe5f41804eaf2bcd84e7ac98dc82f6e3df04b86, too.  That content will just no longer be physically stored in OMPI's git repo.  So things like `./autogen.pl`, `./configure`, `make all`, and `make dist` work fine (although I did just fix up a commit on this PR for `make dist` 😬).

All the CI's are currently failing because they're not doing `git clone --recursive ...`.

**Comment by rhc54** [comment]
@jsquyres No reason to treat libevent any differently as they are also faithfully tagging their releases. I'd suggest just pointing to their latest stable release tag: https://github.com/libevent/libevent/releases/tag/release-2.1.10-stable

**Comment by hjelmn** [comment]
Oh the humanity! Are we sure this is a good idea after all the discussion about the evils of git submodules?

**Comment by jsquyres** [comment]
@hjelmn Yes 😄.  We've been talking about this for a while now; this is the first step towards separating out:

* hwloc
* libevent
* pmix
* OPAL

The latter two will have a bot that updates the git submodule hash in Open MPI whenever commits are made downstream.

**Comment by jsquyres** [comment]
@rhc54 Re libevent: possibly, ya.  Do we have any local changes to our libevent tree?

I wouldn't mind getting used to git submodules with just hwloc first.  There are changes to git commands that our development community will need to get used to, for example.  We might be able to put some detection in `autogen.pl` -- e.g., if you don't `git clone --recursive ...`, your `opal/mca/hwloc/hwloc201/hwloc` tree will be non-existent (or empty? I forget which -- but it'll be something detectable).

**Comment by rhc54** [comment]
>  if you don't git clone --recursive ..., your opal/mca/hwloc/hwloc201/hwloc tree will be non-existent (or empty?

It is empty, so we can detect it easily enough by looking for a signature file in the top level of the hwloc tree.

>  Do we have any local changes to our libevent tree?

Yeah, I believe @abouteiller recently added one to prevent an infinite loop under an unusual race condition. I asked that he push it upstream so it may be something we can pickup from there.

However, this may be indicative of an issue for all the submodules - we may develop updates that take some time to circle back to the submodule. What do we do with those changes in the meantime?

**Comment by jsquyres** [comment]
What we talked about yesterday on the RM call was the possibility of having a github.com:open-mpi/libevent-mirror, where we can have our own copies of libevent.  It would likely be exactly for this case: basically a mirror of the real libevent git repo, but with any local fixes that we want applied to it.

For hwloc, the hope is that we don't need to do this, because we have a good/close relationship with the primary developer (i.e., history has shown that @bgoglin has been very helpful/receptive to taking any fixes that we need into the main hwloc repo/release branches).

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest

**Comment by jjhursey** [comment]
I unexpectedly had a couple of minutes free this morning so tried this with the IBM:GNU CI.

The [Jenkins Git Plugin 2.0](https://wiki.jenkins.io/display/JENKINS/Git+plugin+2.0+beta+testing) has an `Additional Behaviours` option for `Advanced sub-modules behaviours` that lets you add the necessary option.

So in your Jenkins project Config under `Source Code Management` there is `Git` and under that is `Additional Behaviours`. Select the drop down option for `Advanced sub-modules behaviours` then check the box next to `Recursively update submodules`.

That will cause it to search in the subtree for submodules. You should see output like the following:
```
08:44:55  > git checkout -f 75d9bb76fba99dbb6a8a720f4aa31d5056e6864c # timeout=60
08:45:05 Commit message: "Merge b814ff79c9be707ac36848d865c24fcfea985458 into 06c6325bc8ae7cb1cd286768da8c8ebd9b44469f"
08:45:05 First time build. Skipping changelog.
08:45:05  > git remote # timeout=10
08:45:05  > git submodule init # timeout=10
08:45:05  > git submodule sync # timeout=10
08:45:05  > git config --get remote.origin.url # timeout=10
08:45:05  > git submodule init # timeout=10
08:45:05  > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
08:45:05  > git config --get submodule.opal/mca/hwloc/hwloc201/hwloc.url # timeout=10
08:45:05  > git config -f .gitmodules --get submodule.opal/mca/hwloc/hwloc201/hwloc.path # timeout=10
08:45:05  > git submodule update --init --recursive opal/mca/hwloc/hwloc201/hwloc
```

**Comment by jjhursey** [comment]
bot:ibm:xl:retest

**Comment by hjelmn** [comment]
@jsquyres Ok, but we need to carefully document how submodules are used and how they affect OMPI development.

As for OPAL. If we are indeed finally splitting that out I will work on the opal library context stuff. It made no sense while opal was completely internal. Will probably be an interesting topic for a face-to-face meeting as we will likely have to change some MCA semantics and bump the MCA major version.

**Comment by gpaulsen** [comment]
I see that the `url = https://github.com/open-mpi/hwloc.git` in `.gitmodules` uses "https".   This is good.  Github actually recommends using "https" url for read-only access to submodules.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
ompi:bot:retest

to see what's happening here.

**Comment by hppritcha** [comment]
I'll take a shot at seeing what's going on with jenkins and this PR.

**Comment by bwbarrett** [comment]
bot:ompi:retest

**Comment by bwbarrett** [comment]
bot:retest

Ok, it looks like the community and IBM tests pass.  One last time for MLNX, since the results expired out.

**Comment by itemko** [comment]
bot:mellanox:retest

**Comment by itemko** [comment]
Mellanox OpenMPI CI configs have been updated to use git submodules.

**Comment by jsquyres** [comment]
So how do we proceed here -- do we need any other automation in place before merging this PR?

**Comment by bwbarrett** [comment]
@jsquyres nope, I think we’re good.  The only “automation” is that we need to remember to sometimes pull in the changes upstream by moving the submodule pointer, but we didn’t want to do that every day here regardless, since we need hwloc to be at stable releases.

**Comment by jsquyres** [comment]
Ok.  I'm going to write up a few dev instructions on the wiki before I merge this.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
I've updated this PR and some surrounding periphery:

1. Renamed the `hwloc201` component to `hwloc2` (since it can now be used to represent any hwloc v2.x.y, depending on where we point the submodule)
1. Initially replaced the `hwloc` subdir with a submodule pointing to the hwloc repo, at the tag `hwloc-2.0.1`
1. Just to prove that it was possible, added a commit which updated the submodule to point to `hwloc-2.0.4` (i.e., the current release in the hwloc v2.0.x series)
1. Added one more commit to update the submodule to point to `hwloc-2.1.0` (i.e., the most recently release)

Also:

* Added [a wiki page for Open MPI developers about submodules](https://github.com/open-mpi/ompi/wiki/GitSubmodules) (input / edits welcome)
* [Slightly updated the Open MPI web site](https://github.com/open-mpi/ompi-www/pull/290) to give instructions on git clone/pull for submodules

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
Per discussions 6/7 Jan 2020, @bwbarrett will take responsibility for merging this PR, because the introduction of a git submodule will almost certainly break something in the nightly tarball build process.

@bwbarrett will merge this PR when he has a little time to also fix the nightly tarball build process.

**Pull request merged**
