### PR TITLE
v4.0.x: osc/ucx: Detach dynamic window memory when freeing a window

### PR DESCRIPTION
**Pull request by SeyedMir**
Refs: https://github.com/open-mpi/ompi/issues/8774

Memory attached to a dynamic window should be unmapped (deregistered) when a window is freed. Currently, it is done only in win_detach.

### CODE REVIEW

**Comment by SeyedMir** [comment]
I was not sure whether I should make the PR against master first or not because osc ucx has other changes/issues on master.

**Comment by jsquyres** [comment]
We typically like to see fixes merged in on master first, even if they're a little different than the release branches, just to approve the general concept of the fix.

Will this need to be cherry-picked to the v4.1.x branch as well?

**Comment by SeyedMir** [comment]
I made the corresponding PR for master https://github.com/open-mpi/ompi/pull/8937
v4.1.x branch will need it too.

**Comment by gpaulsen** [comment]
@SeyedMir, could you please re-cherry-pick this commit with the `git cherry-pick -x` flag per https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests wiki page?  That will put a reference to the `master` commit and help future git archeology.

**Pull request merged**
