### PR TITLE
v2.0.x: configury: improve NAG compiler support

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
similar to #2092 but for the ```v2.0.x``` branch

**Comment by hppritcha** [comment]
@jsquyres should we close this PR?

**Comment by jsquyres** [comment]
@hppritcha I don't think so.  It's been low on the priority list to review, but it does make the configury better.  It's still in the "someday" category -- perhaps it should be moved to the "Future" milestone?

**Comment by hppritcha** [comment]
@jsquyres time to merge this since we accepted in to v2.x.

**Comment by jsquyres** [comment]
@hppritcha Do we need this in v2.0.x?  With the immanent release of v3.0.0, the life of the v2.0.x series is up on the wall...

Also, we'd probably also want to apply d8c795e312, 0fe7757097, and cf2a80d215 -- but at first (trivial) attempt, they don't cherry pick cleanly.  Meaning: I wonder if porting them is worth the effort.

**Comment by bwbarrett** [comment]
@jsquyres / @ggouaillardet, what's the plan here?  We're almost a year old...

**Comment by jsquyres** [comment]
I think that since these fixes are in v2.1.x, I think it's ok to leave it out of v2.0.x.  At this point, since v3.0.0 is (literally) immanent, we're thinking to only take extremely serious bug fixes into v2.0.x.

@ggouaillardet Ok?

**Comment by jsquyres** [comment]
Gah; I didn't mean to close before @ggouaillardet replied -- sorry!  😦

**Comment by ggouaillardet** [comment]
that's fine for me, so let's keep this PR closed.

**Pull request closed without merging**
