### PR TITLE
v5.0.x: Coverity/v50x/ulfm 

### PR DESCRIPTION
**Pull request by abouteiller**
v5.0.x version of pr #8486

### CODE REVIEW

**Comment by awlauria** [comment]
retest

**Comment by awlauria** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
I'm not sure how to tickle the commit checker. Might need a force-push?

**Comment by jsquyres** [comment]
@awlauria @abouteiller Just edit the description of the PR.  Even adding a space to the end is sufficient to cause the commit checker to run again.

**Comment by jsquyres** [comment]
> @awlauria @abouteiller Just edit the description of the PR. Even adding a space to the end is sufficient to cause the commit checker to run again.

This is preferable to a force push, BTW, because it *only* re-runs the commit checker, not all the rest of CI.

**Comment by gpaulsen** [comment]
I'll take a look.

**Review by awlauria — APPROVED** [review]

**Pull request merged**
