### PR TITLE
ompi/pml/ucx: Fix uninitialized UCX request field.

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
Fixes openucx/ucx#1353

**Comment by artpol84** [comment]
`MCA_PML_BASE_SEND_STANDARD` looks strange for the receive request. Maybe we can change this check as an alternative:
https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx_request.c#L169:L171
so that only for the send requests we will check this field.

**Comment by artpol84** [comment]
@yosefe @alex-mikheev I think that now fix looks more logical.

**Comment by miked-mellanox** [comment]
@artpol84 - please integrate it into 2.x

**Comment by artpol84** [comment]
@miked-mellanox already done #3099

**Pull request merged**
