### PR TITLE
Enable slurm operations on Cray with constraints

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit a29ca2bb0d7e0a1f4749fe88c1aa6bd09837d0a0)

### CODE REVIEW

**Comment by jsquyres** [comment]
Looks like the same false autogen failure we've seen from Mellanox jenkins before.

bot:mellanox:retest

**Comment by hppritcha** [comment]
@hjelmn you need to review this by COB 4/24/17 if you want it in 2.1.1

**Comment by bwbarrett** [comment]
bot:ompi:retest

Looks like the testing aborted due to timeout last night.  Adjusted the timeout configurations to be a bit more flexible.  Let's see how that goes...

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
