### PR TITLE
Fix tree spawn at scale

### LINKED ISSUE #6691: mpirun run hostname cmd unexpected failed
Thank you for taking the time to submit an issue!

## Background information

run openmpi in a kubernetes cluster

```
mpirun -np 256 --bind-to socket -mca pml ob1 -mca btl ^openib --mca oob_base_verbose 100 hostname 2>&1 | tee server_out.txt
```

hostfile

```
jobca1e368c-worker-0-2yi-21-tcmhw slots=8
jobca1e368c-worker-1-kf5-562-7q2l4 slots=8
jobca1e368c-worker-10-ytx-394-tjndh slots=8
jobca1e368c-worker-11-4lo-879-tvd2g slots=8
jobca1e368c-worker-12-am0-360-5bf7n slots=8
jobca1e368c-worker-13-14r-69-djjn6 slots=8
jobca1e368c-worker-14-hij-487-rwll5 slots=8
jobca1e368c-worker-15-bl2-479-ldw6c slots=8
jobca1e368c-worker-16-g5l-33-2qcbg slots=8
jobca1e368c-worker-17-m4z-333-g9l5r slots=8
jobca1e368c-worker-18-q0q-773-n7plw slots=8
jobca1e368c-worker-19-ti7-822-n5zf7 slots=8
jobca1e368c-worker-2-rc1-485-rst7w slots=8
jobca1e368c-worker-20-n9s-551-pn5vt slots=8
jobca1e368c-worker-21-013-239-v57fm slots=8
jobca1e368c-worker-22-prf-680-jbwt9 slots=8
jobca1e368c-worker-23-gv6-714-h8xlp slots=8
jobca1e368c-worker-24-4mb-421-47xbg slots=8
jobca1e368c-worker-25-pre-992-kbnkt slots=8
jobca1e368c-worker-26-fvk-685-2tlht slots=8
jobca1e368c-worker-27-5v7-407-dmt5w slots=8
jobca1e368c-worker-28-dpb-517-tkkkq slots=8
jobca1e368c-worker-29-mvh-486-2r7lz slots=8
jobca1e368c-worker-3-ivv-417-fblnz slots=8
jobca1e368c-worker-30-25h-242-klwh6 slots=8
jobca1e368c-worker-31-17k-516-mbr9b slots=8
jobca1e368c-worker-4-9uv-292-8htt5 slots=8
jobca1e368c-worker-5-lxw-492-w7927 slots=8
jobca1e368c-worker-6-eah-195-jrnwx slots=8
jobca1e368c-worker-7-ss8-753-xv42w slots=8
jobca1e368c-worker-8-7w5-886-fpg4p slots=8
jobca1e368c-worker-9-spz-220-xw66z slots=8
```

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

```
work@jobca1e368c-server-0-juu-120-mn665:~$ mpirun -version
mpirun (Open MPI) 4.0.0

Report bugs to http://www.open-mpi.org/community/help/
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
  tar -zxf openmpi-4.0.0.tar.gz && \
  cd openmpi-4.0.0 && \
  ./configure  --enable-orterun-prefix-by-default --prefix="/usr/local/openmpi" --with-cuda="/usr/local/cuda" && \
  make && \
  make install && \
```

### Please describe the system on which you are running

* Operating system/version: 

```
work@jobca1e368c-server-0-juu-120-mn665:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
work@jobca1e368c-server-0-juu-120-mn665:~$ uname -r
3.10.0-514.44.5.10.h142.x86_64
```

* Computer hardware: 

`72C/512G/8*V100 GPU`

* Network type: 

IP

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

run the shell

```
mpirun -np 256 --bind-to socket -mca pml ob1 -mca btl ^openib --mca oob_base_verbose 100 hostname 2>&1 | tee server_out.txt
```

see the file

[server_log-1.log](https://github.com/open-mpi/ompi/files/3197093/server_log-1.log)
[server_log-2.log](https://github.com/open-mpi/ompi/files/3197094/server_log-2.log)
[server_log-3.log](https://github.com/open-mpi/ompi/files/3197095/server_log-3.log)

it shows that some processes shut down the TCP connection

```
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[64882,0],0] on node jobca1e368c-server-0-juu-120-mn665
  Remote daemon: [[64882,0],18] on node jobca1e368c-worker-24-4mb-421-47xbg

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
[jobca1e368c-worker-24-4mb-421-47xbg:01292] [[64882,0],18] TCP SHUTDOWN
[jobca1e368c-worker-24-4mb-421-47xbg:01292] no hnp or not active
[jobca1e368c-worker-24-4mb-421-47xbg:01292] [[64882,0],18] CLOSING SOCKET 20
[jobca1e368c-worker-24-4mb-421-47xbg:01292] [[64882,0],18] TCP SHUTDOWN done
```

and if i lower down the np number to 192, it works fine ...

### PR DESCRIPTION
**Pull request by rhc54**
The debrujin component is using an algorithm that doesn't respect the
previously assigned parent ID. This causes the other components to have
their routing trees broken whenever debrujin updates routes. This
happens whenever more than 256 nodes are involved, thus breaking tree
spawn for sizes >= 256

Thanks to @zrss for the report and diagnosis!

Closes #6713 
Fixes #6691 

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by zrss** [comment]
thx @rhc54  :+1:

**Comment by hppritcha** [comment]
Hmmm... I thought we did not approve removing components of a framework in a release branch.
At least that's what I was told when I tried to remove the UCT BTL.

**Comment by rhc54** [comment]
I can give you another option - in master, we switched back to a single active component for the routed framework. It would change the routed/base files and so the number of lines changed would be larger. Would you prefer that one?

**Comment by artpol84** [comment]
@karasevb @janjust
Please check if this fixes the issues we observe on some systems.
@jladd-mlnx, FYI.

**Comment by hppritcha** [comment]
@rhc54 yep I'd prefer the second option you mention.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/82ef99604f60d30199a17c0908c27ff1

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/61596b6f7926ac071049654685fc28f5

**Comment by rhc54** [comment]
@hppritcha @gpaulsen I have replaced this with the original change that removes the debruijn component per today's telecon.

**Comment by gpaulsen** [comment]
Thanks.

**Comment by jsquyres** [comment]
Just so that we have this decision rationale recorded...

We concluded on the webed today (2019-06-04) that the debruijn component has never worked in any 3.0.x, 3.1.x, or 4.0.x release (it *did* work in various 2.x releases).  However, since it never worked in any of the 3.x or 4.x releases, we can simply remove that component from those releases without breaking our backwards compatibility guarantees.

This is, thankfully, the easiest path forward -- it's basically `git rm -rf ...` in each of the release branches, and no one has to spend any (further) time debugging or developing.  👍

**Comment by jsquyres** [comment]
Note that this was merged on the v3.0.x and v3.1.x branches already.

CI seems to be borked somehow -- try again.

bot:ompi:retest

**Comment by gpaulsen** [comment]
The UH CI appears to be offline. Let's see if a new round of CI will fix the issue...

bot:retest

**Pull request merged**
