### PR TITLE
Fix remaining typos in source documentation and comments

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./3rd-party,./docs/news -L bloc,chello,childs,connexion,fo,improbe,inout,iput,mmaped,msdos,ro,scoll,sentinal,siz,upto,warmup`

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
bot:aws:retest

**Comment by jsquyres** [comment]
bot:aws:retest

**Comment by jsquyres** [comment]
@awlauria @gpaulsen @janjust FYI: I just tried to cherry-pick these commits to v5.0.x and ran into conflicts.  The conflicts are all easy enough to resolve, but it means that there are commits that are on `main` that have not come over to `v5.0.x`.

Is this already known?  I.e., are there some things on `main` that are intentionally not on `v5.0.x`?  More specifically: is it worth using the attempt to cherry pick the 2 commits on this PR to `v5.0.x` to find other commits that haven't already been cherry picked to `v5.0.x`?

**Comment by awlauria** [comment]
@jsquyres before the next rc I'll do an audit to see what's missing, but you are welcome to check now if you want.

To my knowledge main and v5.0.x should be kept relatively in sync, but of course there's a lag in some cases. There's nothing on main currently that shouldn't be in 5 that I am aware of.

**Comment by jsquyres** [comment]
FWIW, as of v5.0.x e50182c481 (i.e., after your v5.0.x merges from this morning), I still get a bunch of conflicts when I try to cherry pick these commits.

**Pull request merged**
