### PR TITLE
Add missing argument name.

### PR DESCRIPTION
**Pull request by jmbr**

### CODE REVIEW

**Comment by bosilca** [comment]
OK to test.
However, as indicated on our [contributor's portal](https://www.open-mpi.org/community/contribute/) the patch must be signed before being considered for inclusion.

**Comment by jsquyres** [comment]
@jmbr Can you fix your commit to include the signed-off-by line?

In our [contributor's portal](https://www.open-mpi.org/community/contribute/), it's noted that patches must be signed before being considered for inclusion.

Thank you!

**Comment by jmbr** [comment]
> @jmbr Can you fix your commit to include the signed-off-by line?
 
Sure, @jsquyres. I did that on commit 05a3e7a6d9b7327325d489bb0d0e35b7cca1a83c after reading @bosilca's request. I used `git commit --amend` and then `git push` to accomplish that. Did you expect me to do it in a different way? If so, could you please indicate how?

**Comment by jsquyres** [comment]
@jmbr Oh, sorry -- I missed that you had pushed new commits -- I only saw that the CI test was still failing.

You'll need to squash those commits down into a single commit that has the signed-off line, and then force-push that back to your fork branch.  The PR will then auto-update, and the CI will run again (and pass).  Perhaps something like this:

```sh
$ cd /path/to/your/ompi/git/clone

# Fetch everything that has happened upstream
$ git fetch --all

# Make sure you're on the right branch
$ git checkout patch-1

# This should squash it down to a single commit
# (because your 3 commits are effectively equivalent)
$ git rebase origin/master

# Now add a signoff line
$ git commit --amend -s

# Now force push this one commit back up to your github fork
$ git push git@github.com:jmbr/ompi.git --force --dry-run
```

Make sense?

**Comment by jmbr** [comment]
Thank you, @jsquyres. That was crystal-clear.

**Pull request merged**
