### PR TITLE
oshmem/shmem/c: include missing headers

### PR DESCRIPTION
**Pull request by alex--m**
See  #12360

### CODE REVIEW

**Comment by janjust** [comment]
@alex--m forgot the cherry-pick message (-x)

**Comment by alex--m** [comment]
@janjust does this pre-commit error means it depends on the merge to `main` branch? or is there something else I should do?

**Comment by janjust** [comment]
Yes, but I thought I just merged it

**Comment by janjust** [comment]
This is the main commit: d737f003db7057d770b7673a669b51400f038a2a
But the one here says:
cherry picked from commit fda165f5abf2bd01c72576cbaa1b250ea718d256

Did you cherry-pick from your branch? Maybe that's why

**Comment by alex--m** [comment]
You're probably right, fixing...

**Review by janjust — APPROVED** [review]

**Pull request merged**
