### PR TITLE
Make another attempt

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by hjelmn** [comment]
There is one other issue I don't know how to solve. The command line parser stops on an unknown switch. So if the command line has anything that isn't -mca, -am, or -tune its possible not all the options will be parsed. I have a fix but it will potentially parse options to the app. I think that is probably fine. I will put together a patch and we can discuss it.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by rhc54** [comment]
@jjhursey How in the world do I find the error being reported by your tests? All I see is a mass of output, and I can't find the error.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
@hjelmn I took a couple of simple shots at it, but ran into infinite loops. So I'll have to defer until you have your patch available. Can you please set it up as a PR against this PR?

**Comment by hjelmn** [comment]
Sure. I ran into the same issue. I will create a PR later today.

**Comment by jjhursey** [comment]
@rhc54 Looking at the few tests that failed, the bottom of file looks like:
```shell
#################
Run Examples
#################
+ cd /gpfs/gpfs_stage1/jhursey/jenkins/workspace/ompi_public_pr_master/ompi-src/examples
+ timeout --preserve-status -k 22s 20s mpirun -np 2 -mca btl tcp,vader,sm,self hello_c

#################
# Summary
#################
# Tests Passed: 5 of 7
#---------------------
IBM_CI_SUCCESS : Autogen
IBM_CI_SUCCESS : Configure
IBM_CI_SUCCESS : Make
IBM_CI_SUCCESS : Make Install
IBM_CI_SUCCESS : Make examples
#################
```

When a CI test fails I give you all of the output generated from the whole build process, which is a lot. I put a summary at the bottom of what passed to help a bit with that. These seem to have failed in the test run - see the line below (the `+ ` in front of the line is bash showing you the command that it is about to execute next - this way whoever looks at the logs can see all of the commands used by the script in addtion to the output)
```shell
+ timeout --preserve-status -k 22s 20s mpirun -np 2 -mca btl tcp,vader,sm,self hello_c
```
That must have timedout. I'll take a note to see if I can get it to print an error message when that happens before it fails the build.

**Comment by rhc54** [comment]
@hjelmn I think we've made a good-faith attempt, but it's time to surrender pending identification of a maintainer for this code. I've added a check-and-abort so we don't silently ignore the AMCA option. Meantime, I'd suggest we consider this code "non-operational pending identification of a maintainer" ala what we did for checkpoint-restart.

**Comment by rhc54** [comment]
@hjelmn Github problems are preventing the code on the web page from updating - when it does, you'll see that I squashed it down to a single commit and added the check-and-abort logic to mca_base_var.c.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by rhc54** [comment]
See https://github.com/open-mpi/ompi/pull/1692

**Comment by rhc54** [comment]
Closed in favor of other fix

**Pull request closed without merging**
