### PR TITLE
Fix: align OSHMEM API with spec v1.2

### PR DESCRIPTION
**Pull request by igor-ivanov**
This PR adapt OSHMEM API to v1.2 specification. 
It keeps backward compatibility with prevoius spec. hello_oshmem and ring_oshmem are changed according spec v1.2 as more popular while other oshmem examples are kept as is with warning pragma saying about deprecated api.
@miked-mellanox @jladd-mlnx @alex-mikheev could you look at this PR.
@osvegis please check java binding.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by osvegis** [comment]
Now I have no time. I'm sorry. I am not working in java bindings since two years ago.
Maybe @nrgraham23 or @hppritcha could take a look. They are working in Java bindings now.

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
:+1: 

Thanks @igor-ivanov 
Please PR it to v2.x and v1.10.3

**Pull request merged**
