### PR TITLE
accelerator/rocm: some minor fixes

### PR DESCRIPTION
**Pull request by edgargabriel**
- memset the IPC handles to zero before calling hipIpcGetMemHandle (and the event counter part)
- get_buffer_id: fix the buffer_id argument passed to the hip call.

### CODE REVIEW

**Comment by wenduwan** [comment]
I just noticed that we didn't provide constructor/destructor
```
OBJ_CLASS_INSTANCE(
    opal_accelerator_stream_t,
    opal_object_t,
    NULL,
    NULL);

OBJ_CLASS_INSTANCE(
    opal_accelerator_event_t,
    opal_object_t,
    NULL,
    NULL);

OBJ_CLASS_INSTANCE(
    opal_accelerator_ipc_handle_t,
    opal_object_t,
    NULL,
    NULL);

OBJ_CLASS_INSTANCE(
    opal_accelerator_ipc_event_handle_t,
    opal_object_t,
    NULL,
    NULL);
```

Would it be better to reset the object in the constructor instead?

**Comment by edgargabriel** [comment]
@wenduwan I am not sure I follow your comment, can you please explain a bit more?

**Comment by wenduwan** [comment]
Sorry I got confused. I just realized `hipIpcMemHandle_t` is not an OPAL object.

My original comment was about the `opal_accelerator_rocm_ipc_event_handle_t` object and its parent class - I figured that we are not initializing the object to zero values because we did not define the constructor.

**Review by wenduwan — APPROVED** [review]
I cannot test the change but it looks reasonable.

**Pull request merged**
