### PR TITLE
pml/cm: Fix call convertor_prepare_for_send to use the right pointer

### PR DESCRIPTION
**Pull request by wckzhang**
Previously did not use the right offset, same as
36a35fb1fc2de8f675270d252f8ea90abb91a359

Signed-off-by: William Zhang <wilzhang@amazon.com>

### CODE REVIEW

**Comment by wckzhang** [comment]
I was pointed out this code that is the same issue as https://github.com/open-mpi/ompi/pull/10864

@bosilca I'm not too familiar with the opal_convertor_copy_and_prepare_for_send code, does the buffers need to be offset there as well?

@hppritcha this reverts a change you made in - 9e99182b5d9 - where there was a regression. I believe that regression was caused by improper buffer offset and wrapping it in a cuda if check was just hiding the issue.

**Review by bosilca — COMMENTED** [review]
This is an optimization for the contiguous case. A while back, some folks thought that avoiding the convertor call was a way to win few nanoseconds, and this led to these test for contiguous data across the code. Anyway, in this particular case the code is correct as the entire data to be moved is contiguous (in which case the starting point is the base pointer + the true_lb).

**Comment by wckzhang** [comment]
> This is an optimization for the contiguous case. A while back, some folks thought that avoiding the convertor call was a way to win few nanoseconds, and this led to these test for contiguous data across the code. Anyway, in this particular case the code is correct as the entire data to be moved is contiguous (in which case the starting point is the base pointer + the true_lb).

For the non-contiguous case, the buffer isn't offset by true_lb, is that correct?

**Comment by bosilca** [comment]
yes, for the non-contiguous case the offset is computer inside the prepare_for_send.

**Review by hppritcha — APPROVED** [review]

**Pull request merged**
