### PR TITLE
powerpc: Add support for powerpcle in timer/pstat.

### PR DESCRIPTION
**Pull request by AboorvaDevarajan**
Signed-off-by: Aboorva Devarajan <abodevar@in.ibm.com>

### CODE REVIEW

**Comment by nysal** [comment]
Looks good to me. Thanks for the patch.

**Comment by jjhursey** [comment]
@AboorvaDevarajan @nysal Can one of you PR this over to the `v2.0.x` and `v2.x` branches? Do we also want to PR it into `v1.10`?

**Comment by AboorvaDevarajan** [comment]
@jjhursey @nysal I have PRed the same for `v2.0.x` #2386  and `v2.x` #2385 branches.

**Comment by jjhursey** [comment]
@AboorvaDevarajan Thanks!

**Pull request merged**
