### PR TITLE
Integrate PMIx 1.0 into OMPI master

### PR DESCRIPTION
**Pull request by rhc54**
Let's start over as Jenkins is confused

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
@rhc54 once the lanl-distcheck begins passing please remove the .opal_ignore's so we can see what other problems need to be addressed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
@hppritcha We will have to talk on the telecon about those opal_ignore's as I have not done anything to integrate those components to the revised framework, and may well not have time to do so. I think others will have to contribute those pieces.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
@hppritcha Could you help me out with the LANL-distcheck test? It keeps complaining about a missing file, but the file is present, and make tarball works fine for me. Is this a Jenkins problem?

**Comment by hppritcha** [comment]
I checked out your branch and tried to do make distcheck on my mac and got the same sort of error:
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 (cd pmix && /Library/Developer/CommandLineTools/usr/bin/make  top_distdir=../../../../../openmpi-gitclone distdir=../../../../../openmpi-gitclone/opal/mca/pmix/pmix1xx/pmix \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
Makefile:1154: src/buffer_ops/.deps/copy.Plo: No such file or directory
Makefile:1155: src/buffer_ops/.deps/internal_functions.Plo: No such file or directory
Makefile:1156: src/buffer_ops/.deps/open_close.Plo: No such file or directory
Makefile:1157: src/buffer_ops/.deps/pack.Plo: No such file or directory
Makefile:1158: src/buffer_ops/.deps/print.Plo: No such file or directory
Makefile:1159: src/buffer_ops/.deps/unpack.Plo: No such file or directory
Makefile:1160: src/class/.deps/pmix_hash_table.Plo: No such file or directory
Makefile:1161: src/class/.deps/pmix_list.Plo: No such file or directory
Makefile:1162: src/class/.deps/pmix_object.Plo: No such file or directory
Makefile:1163: src/class/.deps/pmix_pointer_array.Plo: No such file or directory
Makefile:1164: src/client/.deps/pmi1.Plo: No such file or directory
Makefile:1165: src/client/.deps/pmi2.Plo: No such file or directory
Makefile:1166: src/client/.deps/pmix_client.Plo: No such file or directory
Makefile:1167: src/client/.deps/pmix_client_connect.Plo: No such file or directory
Makefile:1168: src/client/.deps/pmix_client_fence.Plo: No such file or directory
Makefile:1169: src/client/.deps/pmix_client_get.Plo: No such file or directory
Makefile:1170: src/client/.deps/pmix_client_pub.Plo: No such file or directory
Makefile:1171: src/client/.deps/pmix_client_spawn.Plo: No such file or directory
Makefile:1172: src/sec/.deps/pmix_munge.Plo: No such file or directory
Makefile:1173: src/sec/.deps/pmix_native.Plo: No such file or directory
Makefile:1174: src/sec/.deps/pmix_sasl.Plo: No such file or directory
Makefile:1175: src/sec/.deps/pmix_sec.Plo: No such file or directory
Makefile:1176: src/server/.deps/pmix_server.Plo: No such file or directory
Makefile:1177: src/server/.deps/pmix_server_listener.Plo: No such file or directory
Makefile:1178: src/server/.deps/pmix_server_lite.Plo: No such file or directory
Makefile:1179: src/server/.deps/pmix_server_ops.Plo: No such file or directory
Makefile:1180: src/server/.deps/pmix_server_regex.Plo: No such file or directory
Makefile:1181: src/usock/.deps/usock.Plo: No such file or directory
Makefile:1182: src/usock/.deps/usock_sendrecv.Plo: No such file or directory
Makefile:1183: src/util/.deps/argv.Plo: No such file or directory
Makefile:1184: src/util/.deps/basename.Plo: No such file or directory
Makefile:1185: src/util/.deps/crc.Plo: No such file or directory
Makefile:1186: src/util/.deps/error.Plo: No such file or directory
Makefile:1187: src/util/.deps/fd.Plo: No such file or directory
Makefile:1188: src/util/.deps/hash.Plo: No such file or directory
Makefile:1189: src/util/.deps/os_path.Plo: No such file or directory
Makefile:1190: src/util/.deps/output.Plo: No such file or directory
Makefile:1191: src/util/.deps/pmix_environ.Plo: No such file or directory
Makefile:1192: src/util/.deps/printf.Plo: No such file or directory
Makefile:1193: src/util/.deps/progress_threads.Plo: No such file or directory
Makefile:1194: src/util/.deps/timings.Plo: No such file or directory
make[5]: *** No rule to make target `src/util/.deps/timings.Plo'.  Stop.
make[4]: *** [distdir] Error 1
make[3]: *** [distdir] Error 1
make[2]: *** [distdir] Error 1
make[1]: *** [dist] Error 2
make: *** [distcheck] Error 1

**Comment by jsquyres** [comment]
I'm able to replicate and am troubleshooting.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
Just to close the loop - the issue is/was with VPATH builds. Normal src-tree builds work just fine. Since that is all I do, it works just fine for me :-)

**Comment by rhc54** [comment]
@jsquyres I don't know what is causing the merge conflicts, but something has gotten screwed up in that latest update of PMIx. As you asked me not to merge it myself, I'll stand down until you have time and we can cleanup the merge issue.

**Comment by rhc54** [comment]
@jsquyres Also, FWIW: VPATH build on my Linux box worked fine.

**Comment by jsquyres** [comment]
@rhc54 `make distcheck` is now passing for me.  Want to webex later today to squash this all down to a single commit?

**Comment by rhc54** [comment]
sure - and what the heck are you doing up this early???

**Comment by hppritcha** [comment]
@rhc54 I switched to using OPAL_PMIX_ for the keys and that part now compiles.  I notice all the calls to ```opal_dstore``` are commented out.  Is there a replacement for the ```opal_dstore```  functionality we should be using?

**Comment by hppritcha** [comment]
never mind last question.  I'll just use a opal hash table for now.

**Comment by rhc54** [comment]
Yes, the dstore framework went away as the sm component and hash table both went inside the pmix1xx embedded library. I had figured on simply copying the dstore/hash component into the pmix base as the s1, s2, and cray components will all require it - just haven't had time to do so.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
I should have a PR for the cray pmix component by COB tomorrow.

**Comment by hppritcha** [comment]
opened a PR against this PR to pull in work to get cray pmix component working again.

**Comment by artpol84** [comment]
This doesn't seem right to me:
https://github.com/rhc54/ompi/blob/e356fdf4a47e4a43663ca137dae723603de758a7/opal/mca/pmix/pmix1xx/pmix1xx_client.c#L222

How can you generate arbitrary namespace name that was provided by RM internally with opal_convert_jobid_to_string(proc->jobid)?

**Comment by artpol84** [comment]
This code:
https://github.com/rhc54/ompi/blob/topic/pmix2/orte/orted/pmix/pmix_server_register_fns.c#L334
is supposed to be executed on RM side. Does PMIx exports lists logic to RM then?

**Pull request merged**
