### PR TITLE
Mellanox Open MPI CI: optimized git checkout step to reduce CI duration

### PR DESCRIPTION
**Pull request by artemry-mlnx**
Signed-off-by: Artem Ryabov <artemry@mellanox.com>

### CODE REVIEW

**Comment by rhc54** [comment]
ok to test

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by artemry-mlnx** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
@artemry-mlnx I'm afraid IBM is down, so you won't get anything but false failures from them

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by artemry-mlnx** [comment]
CC @amaslenn

**Comment by jsquyres** [comment]
bot:ibm:retest

**Pull request merged**
