### PR TITLE
opal: run clang-format on all of opal

### PR DESCRIPTION
**Pull request by hjelmn**
Some edits had to be done by hand as opal_datatype_internal.h is incorrectly
detected as objective-c. This happens because the OPAL_DATATYPE_INIT_PTYPES_ARRAY
macro seems to trip up clang-format. I intend to fix this bug upstream but
for now it was fine to delete this definition, format the code, then re-add
it to match the style guidelines.

Signed-off-by: Nathan Hjelm <hjelmn@google.com>

### CODE REVIEW

**Comment by hjelmn** [comment]
If it makes sense this can be broken down into many commits. Not sure what is preferred.

**Comment by hjelmn** [comment]
:bot:retest:aws

**Comment by bosilca** [comment]
Let us suffer only once please.

**Comment by hjelmn** [comment]
Ok. Let me run clang-tidy on opal to add braces to single-line control statements and add it as another commit here so that we get all the opal hurt at once. Will be adding the script to run it to contrib so it can be run whenever someone want to use it.

**Comment by hjelmn** [comment]
Ok, this should be good now. I re-ran clang-format with the setting update then ran clang-tidy to add the missing braces and out that in as a separate commit.

**Review by bwbarrett — APPROVED** [review]

**Comment by gpaulsen** [comment]
@hjelmn Can you please PR this along with other formatting PRs on master to v5.0.x?

Some other PRs that we need now may include:
#8639, (this #8647), #8668, #8674, #8676.

**Comment by gpaulsen** [comment]
@hjelmn I'm getting reports that it's hard to cherry-pick opal changes to v5.0.x, presumably because we're missing the above.
I don't have clang-format v10/11 on our systems yet.  Would you mind cherrypicking (or rerunning) this  (and possibly the others mentioned above) to v5.0.x please?

**Comment by awlauria** [comment]
We should probably merge as many pr's (preferably all of them) from master to v5 first that are coming. That would probably help reduce the pain.

**Pull request merged**
