### PR TITLE
Cleanup compiler warnings

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by jsquyres** [comment]
LOL -- I just committed part of these same fixes on master in 9045d6de0058d4a6af5e3cabd8664b8375326bf3.  I did not fix the opal_proc_t / ompi_proc_t type mismatch -- I mailed @hjelmn about it.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request closed without merging**
