### PR TITLE
io/ompio: fix the request in case of a zero size write/read operation

### PR DESCRIPTION
**Pull request by edgargabriel**
This commit fixes the bug reported by Eric Chamberland on the mailing list.

### CODE REVIEW

**Comment by edgargabriel** [comment]
not sure why the Mellanox build is hanging

**Comment by jsquyres** [comment]
@edgargabriel Sometimes a bot:retest shakes things loose

**Comment by edgargabriel** [comment]
bot:retest

**Comment by edgargabriel** [comment]
bot:retest

**Pull request merged**
