### PR TITLE
Update portable platform file

### PR DESCRIPTION
**Pull request by bwbarrett**
The portable platform file hasn't been updated since Feb 10, 2010 (https://github.com/open-mpi/ompi/commit/3ca8adb540023559788a3fbffb059287ca50b9d9), so it was a bit out of date, including not understanding CLANG and the Nvidia-rebranded PGI compiler, so pull in the latest version from GASNet.  Update some of the infrastructure so that we can pull in the GASNet version unchanged and make future updates easier.

This should allow us to pull in https://github.com/open-mpi/ompi/pull/9398.

### CODE REVIEW

**Comment by jsquyres** [comment]
Got some compile warnings.  In ompi_info (similar ones appear in the op/avx component):

```
In file included from param.c:50:0:
../../../ompi/include/mpi_portable_platform.h:31:5: warning: "_PORTABLE_PLATFORM_H" is not defined [-Wundef]
 #if _PORTABLE_PLATFORM_H != PLATFORM_HEADER_VERSION \
     ^
../../../ompi/include/mpi_portable_platform.h:31:29: warning: "PLATFORM_HEADER_VERSION" is not defined [-Wundef]
 #if _PORTABLE_PLATFORM_H != PLATFORM_HEADER_VERSION \
                             ^
../../../ompi/include/mpi_portable_platform.h:32:9: warning: "PLATFORM_HEADER_VERSION" is not defined [-Wundef]
      || PLATFORM_HEADER_VERSION < 16
         ^
In file included from param.c:50:0:
../../../ompi/include/mpi_portable_platform.h:1056:7: warning: "_PLATFORM_ARCH_BIG_ENDIAN" is not defined [-Wundef]
 #elif _PLATFORM_ARCH_BIG_ENDIAN
       ^
../../../ompi/include/mpi_portable_platform.h:1091:7: warning: "_PLATFORM_ARCH_32" is not defined [-Wundef]
 #elif _PLATFORM_ARCH_32
       ^
```

And in oshmem_info:

```

../../../ompi/include/mpi_portable_platform.h:32:9: warning: "PLATFORM_HEADER_VERSION" is not defined [-Wundef]
      || PLATFORM_HEADER_VERSION < 16
         ^
In file included from param.c:43:0:
../../../ompi/include/mpi_portable_platform.h:1056:7: warning: "_PLATFORM_ARCH_BIG_ENDIAN" is not defined [-Wundef]
 #elif _PLATFORM_ARCH_BIG_ENDIAN
       ^
../../../ompi/include/mpi_portable_platform.h:1091:7: warning: "_PLATFORM_ARCH_32" is not defined [-Wundef]
 #elif _PLATFORM_ARCH_32
       ^
param.c: In function 'oshmem_info_do_config':
param.c:150:19: error: implicit declaration of function '_STRINGIFY' [-Werror=implicit-function-declaration]
                   _STRINGIFY(OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME));
                   ^
In file included from ../../../ompi/include/ompi_config.h:29:0,
                 from ../../../oshmem/include/oshmem_config.h:21,
                 from param.c:18:
../../../opal/include/opal_config.h:1691:49: error: 'GNU' undeclared (first use in this function)
 #define OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME GNU
                                                 ^
param.c:150:30: note: in expansion of macro 'OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME'
                   _STRINGIFY(OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME));
                              ^
../../../opal/include/opal_config.h:1691:49: note: each undeclared identifier is reported only once for each function it appears in
 #define OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME GNU
                                                 ^
param.c:150:30: note: in expansion of macro 'OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME'
                   _STRINGIFY(OPAL_BUILD_PLATFORM_COMPILER_FAMILYNAME));
                              ^
../../../opal/include/opal_config.h:1697:50: error: too many decimal points in number
 #define OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR 4.8.5
                                                  ^
param.c:152:30: note: in expansion of macro 'OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR'
                   _STRINGIFY(OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR));
                              ^
```

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by gpaulsen** [comment]
restarting IBM CI in 2 minutes.

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by bwbarrett** [comment]
bot:aws:retest (Cray timeout)

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
