### PR TITLE
fortran/use-mpi-f08: clean [p]ompi_FOO_f bindings

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres I made two commits in order to ease the review (the heavy lifting is done in the first commit, and the second one is a massive but trivial update)

The second commit should be squashed before merging.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jladd-mlnx** [comment]
bot:mellanox:retest

**Comment by ggouaillardet** [comment]
@jsquyres thanks for the review, I made the requested changes

**Comment by jsquyres** [comment]
This entire PR is worth cherry picking to v4.0.x.

Probably only the dist_graph fixes are worth cherry picking to v3.1.x, v3.0.x, v2.x.

**Pull request merged**
