### PR TITLE
pmix/pmix112: Update to PMIx 1.2.1 release

### LINKED ISSUE #2072: Need PMIX1.2.1 for v2.1 release
This issue tracks getting PMIX2 in the v2.1 release.  The shared memory dstore is an important feature when trying to support 100's of MPI processes on a single node.

### PR DESCRIPTION
**Pull request by jjhursey**
* This PR contains the [PMIx v1.2.1](https://github.com/pmix/master/releases/tag/v1.2.1) release
 * Fixes #2072

### CODE REVIEW

**Comment by hppritcha** [comment]
let's try again with Mellanox bot:

bot:mellanox:retest

**Comment by jjhursey** [comment]
@hjelmn This PR contains the latest PMIx if you want to give it a try at scale again.

**Comment by hppritcha** [comment]
@hjelmn have you had a chance to test this PR?

**Comment by jjhursey** [comment]
@hjelmn Just checking in to see if you had a chance to test. I think your 👍  is the last item before we release PMIx 1.2.1.

**Comment by jjhursey** [comment]
We are waiting on a small configure change, then we are planning to release PMIx `v1.2.1` today.

Once that is officially released, I'll update this PR and we can merge it in. Once merged in then MTT can work on it for a few days before OMPI `v2.1.0` release.

**Comment by jjhursey** [comment]
PMIx v1.2.1 is now officially released. I updated this PR.
I'll let @rhc54 re-review it. @hppritcha @jsquyres This should be ready to go once that is complete.

**Comment by jsquyres** [comment]
@hppritcha Since this is *the* feature for v2.1.0, I'm going to merge this when CI finishes (even though you're unavailable).

**Pull request merged**
