### PR TITLE
Prevent oshmem related files inside install folder in case --disable-oshmem

### PR DESCRIPTION
**Pull request by igor-ivanov**
This PR should resolve issue https://github.com/open-mpi/ompi/issues/850
@jsquyres, @miked-mellanox could you review

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
FWIW, I think the error is this:

```
08:46:49 oshmem/include/Makefile.am:38: error: 'nobase_dist_oshmem_HEADERS' is used but 'oshmemdir' is undefined
08:46:49 oshmem/include/Makefile.am:39: error: 'nobase_nodist_oshmem_HEADERS' is used but 'oshmemdir' is undefined
```

**Comment by igor-ivanov** [comment]
@miked-mellanox include/openshmem folder stores internal header-files. It is done to meet openmpi approach,

**Comment by miked-mellanox** [comment]
thanks
:+1:

**Pull request merged**
