### PR TITLE
Properly report failure to launch when someone mis-types the name of the application

### PR DESCRIPTION
**Pull request by rhc54**
Refs #2233

(cherry picked from commit open-mpi/ompi@16540c7422e6f808b00e1c857a82bc15f734c7ca)

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/2f4bad5c752fe342dad784e5adbd48a4

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/bd2185246e78fdf55afc1b2ce455c767

**Comment by rhc54** [comment]
@jjhursey In both cases, the "details" show that the test passed - any idea why it is marked as failing?

**Comment by jjhursey** [comment]
I'm looking at the internal setup now. It looks like a filesystem problem on one of the test machines. Let me try to work around that node then we can retest.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
