### PR TITLE
mpool/hugepage: set mntent API instead of manually parsing /proc/mounts

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs open-mpi/ompi#1822

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hjelmn is hugetlbfs upported by Open MPI on OS X ?
in other words, is it ok to disqualify this module if mntent is not available ?

**Comment by hppritcha** [comment]
I plan to open a PR for the Cray large page support this week.

The manual parsing doesn't work reliably on CLE 6

Am Montag, 4. Juli 2016 schrieb Gilles Gouaillardet :

**Comment by hjelmn** [comment]
@ggouaillardet OS X has hugepage support using an mmap flag. Problem is that I have not been able to reliably allocate huge pages more than 5 min after a boot. It looks like Apple only allows huge page allocation in a pool that is very quickly exhausted.

**Comment by hppritcha** [comment]
@hjelmn i think this needs to be checked on a Cray  if in fact you'd like the huge page mpool to work on that system.

**Comment by hppritcha** [comment]
This fix is needed for Cray KNL systems (or more precisely CLE 6) otherwise we see fairly frequent aborts in MPI_Init (unless one is using ofi mtl).  So putting this at milestone 2.0.1.

**Comment by hppritcha** [comment]
@ggouaillardet I'm going to merge this and test the cherry pick on 2.x.  Unfortunately native launch is aprun on KNL nodes is all messed up on master.

**Pull request merged**
