### PR TITLE
NEWS: Remove +x rights

### PR DESCRIPTION
**Pull request by nmorey**
Signed-off-by: Nicolas Morey-Chaisemartin <NMoreyChaisemartin@suse.com>

### CODE REVIEW

**Comment by rhc54** [comment]
No CI required on this

**Comment by rhc54** [comment]
Ah, just saw that this is for v1.10 - that series is closed.

**Comment by nmorey** [comment]
Isn't there a 1.x maintenance branch ?
This is not a big issue, but it conflicts with SUSE packaging rules.
I patched in in the RPM but I figured it might be worth upstreaming.

2.x and 3.x do not have this issue

**Comment by rhc54** [comment]
I'm afraid not - the v1.10 is passing out of maintenance as 3.0 is released.

**Pull request closed without merging**
