### PR TITLE
Fix 6238 for v3.1.x

### PR DESCRIPTION
**Pull request by hppritcha**
Correct parsing of ppr directives

Needed to apply commit from PR #5778 to get this commit
from PR #6238 to apply cleanly.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit b19e5edf769858859c96b62d9b2644b44bcc3b03)

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
Mellanox seems to be having a bad day.

**Comment by hppritcha** [comment]
@xinzhao3 could you get someone from Mellanox to investigate the CI failures?  Seems to be impacting multiple PRs.

**Comment by jsquyres** [comment]
@hppritcha See https://github.com/open-mpi/ompi/pull/6414#issuecomment-469753931

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Pull request merged**
