### PR TITLE
Topic/enable atomics

### PR DESCRIPTION
**Pull request by bosilca**
As most compilers gain support for builtin atomics I propose to switch the default Open MPI behavior with regard to atomics. Instead of relying on our own atomics, we should leverage what the compiler, or the OS, is supporting. This patch change the default behavior for builds on OSX or with a compiler supporting gcc-type atomic builtins.

@goodell and @hjelmn please review.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/433/

**Build Log**
*last 50 lines*

 ```
GitHub pull request #288 of commit e9ab8e0d4394676073a9d7a64e49fa5878c0fe72.
Setting status of e9ab8e0d4394676073a9d7a64e49fa5878c0fe72 to PENDING with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/433/ and message: Build started.
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/open-mpi/ompi
 > /usr/bin/git init /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace # timeout=60
Fetching upstream changes from https://github.com/open-mpi/ompi
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git145290382710597451.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
 > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
Pruning obsolete local branches
Fetching upstream changes from https://github.com/open-mpi/ompi
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git2673383877297659309.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi +refs/pull/*:refs/remotes/origin/pr/* --prune # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git rev-parse e9ab8e0d4394676073a9d7a64e49fa5878c0fe72^{commit} # timeout=60
Merging Revision e9ab8e0d4394676073a9d7a64e49fa5878c0fe72 (detached) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='default', fastForwardMode='--ff'}
 > /usr/bin/git rev-parse origin/master^{commit} # timeout=60
 > /usr/bin/git config core.sparsecheckout # timeout=60
 > /usr/bin/git checkout -f origin/master # timeout=20
 > /usr/bin/git merge --ff e9ab8e0d4394676073a9d7a64e49fa5878c0fe72 # timeout=60
 > /usr/bin/git config core.sparsecheckout # timeout=60
 > /usr/bin/git checkout -f e9ab8e0d4394676073a9d7a64e49fa5878c0fe72 # timeout=20
ERROR: Branch not suitable for integration as it does not merge cleanly: Could not merge AnyObjectId[e9ab8e0d4394676073a9d7a64e49fa5878c0fe72]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi/commit/e9ab8e0d4394676073a9d7a64e49fa5878c0fe72
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of e9ab8e0d4394676073a9d7a64e49fa5878c0fe72 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/433/ and message: Build finished.
```

Test FAILed.

**Comment by hjelmn** [comment]
@bosilca Can you rebase this branch instead of merging?

**Comment by hppritcha** [comment]
This is a complete mess.  I want to see this PR either rebased to make for a clean commit or else closed.

**Comment by jsquyres** [comment]
@bosilca Want to catch me on IM to figure out how to rebase it properly?

**Comment by hppritcha** [comment]
Can one of the admins verify this patch?

**Comment by hjelmn** [comment]
I think we still want this but its hard to tell which commits are the PR. I see ffff47f which is simple enough. Are there others?

**Comment by bosilca** [comment]
This has been replaced by #633.

**Pull request closed without merging**
