### PR TITLE
coll/base: reduce memory consumption in Scatter

### PR DESCRIPTION
**Pull request by mkurnosov**
This PR reduces memory consumption in non-root and non-leaf processes of binomial tree algorithm for Scatter operation.

Signed-off-by: Mikhail Kurnosov <mkurnosov@gmail.com>

### CODE REVIEW

**Review by bosilca — APPROVED** [review]

**Comment by jsquyres** [comment]
@mkurnosov Could you cherry-pick this to relevant release branches?

Thanks!

**Comment by mkurnosov** [comment]
@jsquyres I have cherry-picked a commit to v4.0.x and v4.1.x. What is a preferred way to add this changes to v5.0.x?

**Comment by awlauria** [comment]
@mkurnosov please cherry-pick to the v5.0.x branch just like you have for v4.x.x branches.

Thanks!

**Comment by mkurnosov** [comment]
@awlauria This PR adds small changes to not yet merged PR #8619.

**Comment by mkurnosov** [comment]
@jsquyres @awlauria Do I have to wait for merging PR #8619 to v5.0.x before cherry-picking or is it possible to add this commit to PR #8619? Thanks.

**Comment by jsquyres** [comment]
Looks like #8619 is merged, so I guess you get to create a new 5.0 PR.  😄

**Comment by awlauria** [comment]
Ah, I didn't see your response @mkurnosov . Had I seen that I would have been fine with you adding it to #8619 if possible. Sorry about that.

**Comment by mkurnosov** [comment]
@jsquyres @awlauria Thanks!

**Pull request merged**
