### PR TITLE
pml/base: Remove unnecessary lines of code

### PR DESCRIPTION
**Pull request by wckzhang**
Unused int num_pml
Multiple initialization of variables

Signed-off-by: William Zhang <wilzhang@amazon.com>

### CODE REVIEW

**Review by bosilca — APPROVED** [review]

**Review by bwbarrett — APPROVED** [review]
Your commit message could use some work; it took me a bit to figure out what the body of the message was saying (use paragraph form, not half-sentence fragments).

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5b707b42dd2c4376f35e07e32a359fe5

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/208f312b002f191fc104be5ab0060b8b

**Comment by wckzhang** [comment]
Oops...dragged in some changes I didn't mean to, fixing pr now

**Pull request merged**
