### PR TITLE
Deal with special case during cleanup

### PR DESCRIPTION
**Pull request by rhc54**
In some scenarios, we can have a daemon sharing the node with mpirun. In
those cases, we need to avoid race conditions in cleanup

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@hjelmn I _think_ this will fix the problem you've been having on trinitite - can you please confirm?

**Comment by rhc54** [comment]
Woohoo!! Thanks!

**Comment by rhc54** [comment]
Will bring this around to 4.x - do you need it on 3.x as well?

**Comment by hppritcha** [comment]
@gpaulsen we probably want this in v4.0.x as well

**Pull request merged**
