### PR TITLE
README: Note about ld issue for XL and PGI on PPC

### PR DESCRIPTION
**Pull request by jjhursey**
* Related to Issue #2606 and Issue #3075
 * The core problem in those two issues is related to a regression in
   ld upstream. Add a note in the README about this issue.

[skip ci] bot:notest

### CODE REVIEW

**Comment by jsquyres** [comment]
@jjhursey Ping on this one (same as #3886).

**Comment by jsquyres** [comment]
@jjhursey Please update like you did for #3886.

**Comment by jjhursey** [comment]
@jsquyres I picked over that change to this branch. I also filed PR #4048 for `v3.0.x` and PR #4047 for `master`. Then I think all of the branches will have the correct set of commits.

**Comment by hppritcha** [comment]
@jsquyres is this ready to merge?

**Pull request merged**
