### PR TITLE
v2.0.x patching fixes

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
False failure.

:bot:retest:

**Comment by jsquyres** [comment]
@artpol84 @jladd-mlnx Can Mellanox verify that this PR fixes the problem in the v2.0.x series?  (I ask because Mellanox was the one who could easily reproduce the problem)

**Comment by hjelmn** [comment]
I verified it myself but it would be good to get confirmation. I plan to upload a regression test to MTT after this is merged.

**Comment by artpol84** [comment]
@vspetrov can you check this please?

**Comment by jsquyres** [comment]
@artpol84 @vspetrov Could we get word on this before the teleconf tomorrow?  Thanks!

**Comment by artpol84** [comment]
@jsquyres I talked to @vspetrov, he will double-check and report back here.

**Comment by vspetrov** [comment]
@jsquyres @artpol84 Checked this PR with mt_stress: it works. The workaround helps. :+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
