### PR TITLE
Minor edit to general.rst

### PR DESCRIPTION
**Pull request by classicsman**
change:
Open MPI includes support for a wide variety of supplemental hardware and software package. to:
Open MPI includes support for a wide variety of supplemental hardware and software packages. (adding an 's' to the end of the sentence)

### CODE REVIEW

**Comment by awlauria** [comment]
@classicsman thanks for the contribution. Can you open this change up against main first? The process is to open PR's against the main branch first, then once that is merged cherry-pick them back to release (this branch (v5.0.x)/v4.0.x/v4.1.x) as needed.

Also you will need to sign-off your commit using `git commit --signoff`.

**Comment by classicsman** [comment]
I'm afraid I don't know how to do any of that. I'm rather inexperienced
with this. I've never heard anything about cherry-pick.

**Comment by jsquyres** [comment]
@classicsman Our development process requires us to commit to the `main` branch before we can accept a commit to the `v5.0.x` release branch.

For simplicity, can you:

1. Make a new branch from `main`
2. Make the corresponding change/commit there
3. Make a new PR against the `main` branch

We can then merge the `main` PR in, and I can show you how to fix up this PR (i.e., use a cherry pick from `main` to the `v5.0.x` branch) at the KYOSS meeting next Wednesday.

**Review by gpaulsen — APPROVED** [review]

**Comment by classicsman** [comment]
Sorry about that. I thought I found a cool shortcut, but it didn't let me
sign off or say #Hacktoberfest. No commit notes, nuthin.' Thanks again for
your help, I'll eventually get the hang of this.

**Comment by jsquyres** [comment]
@classicsman No problem.  If you can make a new PR against `main` as I described above (especially today, so that it can count against Hacktoberfest!), great.  Regardless, we can talk next Wednesday at the KYOSS meeting and we can fix up one or both of your PRs at that time.

**Comment by awlauria** [comment]
Should this be closed or are we still planning on merging this at some point?

**Comment by classicsman** [comment]
That sounds good to me. I'll plan on being there.

**Comment by jsquyres** [comment]
This PR made moot by #11211

**Pull request closed without merging**
