### PR TITLE
btl/sm: cleanup with clang-format and clang-tidy

### PR DESCRIPTION
**Pull request by hjelmn**
This component had a number of issues with include ordering. Fixed the
dependecies and any other weirdness by moving types into the new
btl_sm_types.h header file. The common functions needed by both the
fifo and fast box code (virtual2relative and relative2virtual) have
been moved into the new btl_sm_virtual.h header file.

Signed-off-by: Nathan Hjelm <hjelmn@google.com>

### CODE REVIEW

**Review by bwbarrett — APPROVED** [review]
I think this all looks right.  Splitting up into a couple of commits would have killed you? :)

**Comment by hjelmn** [comment]
Hah. Yeah. Should probably have done the header detangling in a different commit. Kind of happened organically after clang-format correctly broke the build.

**Review by bosilca — APPROVED** [review]
I really did not expect the formatting changes to be that invasive 🤷

**Comment by hjelmn** [comment]
@bosilca Mostly my fault. I put in some weird header dependencies that I had to fix.

**Comment by awlauria** [comment]
@hjelmn can you cherry-pick this back to v5.0.x when you have a chance.

**Pull request merged**
