### PR TITLE
Configure summary and enable CMA by default

### LINKED ISSUE #1404: cma support - enable by default if detected?
We might want to support CMA by default if auto-detected by configury.  Currently --with-cma needs to be on the configure line to pick up CMA support.

@jsquyres

### PR DESCRIPTION
**Pull request by hjelmn**
This PR contains two changes:
- Add the configure summary.
- Improve CMA detection and turn on CMA support by default.

Both of these things were discussed and agreed upon for 2.1.x but it has been some time since we discussed the summary. If it is still OK for 2.1.x please approve this PR otherwise I can pull the CMA changes off master and back-port them to 2.1.x.

Closes #1404

### CODE REVIEW

**Comment by jsquyres** [comment]
@hjelmn Howard and I discussed: this is definitely an enhancement, and since it missed the Sep 30 deadline, it has unfortunately missed the board for v2.1.0.  That being said, if v2.1.0 ends up getting significantly delayed, we may open the doors again for v2.1.0 enhancements.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
@hppritcha Good to go when CI finishes

**Comment by hppritcha** [comment]
bot:lanl:retest

**Pull request merged**
