### PR TITLE
v3.0.x: disable hwloc CUDA support when relevant

### PR DESCRIPTION
**Pull request by jsquyres**
Refs #4248

### CODE REVIEW

**Comment by jsquyres** [comment]
@ggouaillardet Good catch on the disparity between `--with-cuda` and `--enable-cuda`.  I think this PR's code is probably *correct* as-is (for the `--with-cuda=/path` case), but probably only by accident.  I'll fix on master and bring over to the relevant PRs.

As for NVML: I don't see any relation from NVML to CUDA in the hwloc configury (in hwloc proper, I don't see "disable CUDA? Ok, we'll also disable NVML" like we have in the OMPI master hwloc 2a component `configure.m4`).  So -- another good catch by @ggouaillardet.  😄   Do you know why that stanza is there in master?  I see 8d7541f766dfa00768a8bf797437fd37fdde9262, but the commit message doesn't say *why* we disable NVML if CUDA support is disabled in OMPI.  ☹️   CUDA != NVML -- they don't share support libraries or something, do they?

**Comment by ggouaillardet** [comment]
@bgoglin can you please enlight us on `CUDA` vs `NVML` and how Open MPI might benefit from `hwloc` being built with ```--enable-nvml``` ?
If i understand/remember correctly, `NVML` is a `CUDA` feature, but Open MPI does not use this info from a `hwloc` topology.

**Comment by bgoglin** [comment]
NVML is not a CUDA feature, it's another NVIDIA library that can be used to query GPU information without actually using GPUs. IIRC, that can be used by RMs for allocating GPUs to jobs, and by administrators for configuring/querying stuff such as temperature, UUID, etc.
https://developer.nvidia.com/nvidia-management-library-nvml

I am pretty sure OMPI doesn't care about NVML at all. So you could disable it even when CUDA is enabled.

As long as OMPI doesn't look at hwloc GPU "osdevs", you can disable CUDA, etc.

Grep tells me that the only users of osdevs in OMPI master seem to be usnic and hwloc_base_util.c. The latter looks for KNC MICs and Network/OFED NICs. Nothing for GPUs.

**Comment by sjeaugey** [comment]
We should disable CUDA and NVML in hwloc since we're not using it. If we want to use it in the future, we'll re-enable parts that are of interest only.

**Comment by jsquyres** [comment]
@sjeaugey Am I understanding you correctly: we're not using CUDA functionality in hwloc at all, even when CUDA support is enabled in the Open MPI build?

**Comment by jsquyres** [comment]
See #4257 for a follow-on commit that could be added to all these PRs.

**Comment by jsquyres** [comment]
@ggouaillardet New commit added to this v3.0.x PR.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
@ggouaillardet Thanks!  Can you also review #4249 and #4250?

**Pull request merged**
