### PR TITLE
Check upstream master branches for PMIx/PRRTE

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
@janjust @bwbarrett Could someone help me understand the "continuous-integration/jenkins" failure report? When I click on "Details", it shows a green check by every stage of the procedure - which to me, at least, implies like it "passed". I don't see anything saying it failed.

Is there some subtle thing I'm supposed to notice???

**Comment by rhc54** [comment]
Hit the "console" button and see some weird error output saying that configure cannot find PMIx??? This is very confusing.

**Comment by jsquyres** [comment]
> Could someone help me understand the "continuous-integration/jenkins" failure report?

Yeah, it's a little less than obvious.  We haven't found a way to make it better.  What you have to do is:

1. Click the Details link to go to the Jenkins report.  It shows the "all green" output, which makes you think it passed.  But it didn't.
2. In the top-left of the screen, click on the build number.  In this case, it's "#3" (i.e., the 3rd build of this PR).
3. In the page that comes up, click on "Pipeline steps" in the left-hand navigation.

From here, you'll see steps that have a red X / failed.

In this case, it looks like they had the dumb fail-to-git-clone error that still happens sometimes.  Sigh.  This is just a bot retest type of situation.

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by rhc54** [comment]
I surrender - just cannot get this pulled from upstream

**Pull request closed without merging**
