### PR TITLE
Remove visibility directives from public APIs

### LINKED ISSUE #4069: v2.1.x: PMIx visibility issue
@rhc54 reminded me this morning that there is still a pending symbol visibility issue identified by @siegmargross for the v2.1.x series.

Ralph is working on it and should have a PR within a few days.  We won't hold up the v2.1.2rc for this issue, but wanted to file an issue just to make sure we track it.

### PR DESCRIPTION
**Pull request by rhc54**
Fixes #4069 

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
ah come on, jenkins - stop the infrastructure failures

bot:ompi:retest

**Comment by rhc54** [comment]
i wonder if it is possible for the OMPI jenkins to run all these variations without suffering an infrastructure failure?

bot:ompi:retest

**Comment by rhc54** [comment]
hold on here - we have a revised method that is a better long-term fix

**Comment by jjhursey** [comment]
Refs https://github.com/pmix/pmix/pull/451
Considering https://github.com/pmix/pmix/pull/455 as an alternative approach for PMIx.

**Comment by rhc54** [comment]
@jjhursey should be okay now

**Comment by rhc54** [comment]
It was just timing. However, I'm thinking that PMIx v1.2.3 should be ready to go now, if you have time and are willing to generate the rc. Might be good if we can provide OMPI with an official release.

**Comment by jjhursey** [comment]
@rhc54 Yeah I think we should. With these recent changes we should probably setup an RC. That'll also make it easier for the packaging folks to test out the visibility changes. I'll put it on the list for today.

**Comment by jjhursey** [comment]
Ref [PMIx v1.2.3rc1](https://github.com/pmix/pmix/releases/tag/v1.2.3rc1)

**Comment by jsquyres** [comment]
Per Webex discussion on 15 Aug, we'll take this PR and then be ok to make another RC.  We might take another follow on PR that just updates the VERSION file in PMIx to be 1.2.3, just to be a little  more expressive in the PMIx version file.

**Pull request merged**
