### PR TITLE
MTL portals4 : improve the rendez-vous protocol using PtlTriggeredGet…

### PR DESCRIPTION
**Pull request by francois-wellenreiter**
… operation

### CODE REVIEW

**Comment by francois-wellenreiter** [comment]
As discussed previously with @regrant and @tkordenbrock , you may find hereafter an improvement allowing a complete offloaded execution of a rendez-vous protocol in the MTL portals4.

**Comment by hppritcha** [comment]
@regrant is this targeted for v2.0?

**Comment by regrant** [comment]
:+1:

**Comment by francois-wellenreiter** [comment]
@hppritcha I think that could be interesting to have it in v2.x, would you push the changes or do you prefer that I submit a Pull Request into ompi-release ?

**Comment by jsquyres** [comment]
@francois-wellenreiter Yes, if you want this to go to the v2.x branch, you need to submit a new pull request on the ompi-release repo to the v2.x branch.

**Pull request merged**
