### PR TITLE
configury: clean the flex generated .c files

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres can you please have a look at it ?
i naively thought autotools would take care of that ... but it seems the .c files generated by flex must be manually removed

**Comment by jsquyres** [comment]
No, we don't want the `clean` target to remove lex files -- this will remove the `*lex.c` generated files from tarballs.  I.e., it will mean that users will need to have flex installed.  

If anything, the `maintainer-clean` target could remove these files (i.e., the `maintainer-clean-local` target).

**Comment by jsquyres** [comment]
bot:retest

**Comment by ggouaillardet** [comment]
@jsquyres i updated the PR and now uses the ```maintainer-clean-local``` target

**Comment by jsquyres** [comment]
👍

**Pull request merged**
