### PR TITLE
New add_procs behavior

### PR DESCRIPTION
**Pull request by hjelmn**
This PR updates the behavior of add_procs in master. If the number of processes in the job exceeds mpi_add_procs_cutoff then ompi_proc_t objects will only be made/added for local processes. All other processes will be created dynamically as needed.

See the messages in the various commits for more information.

This PR will be pushed once all BTL authors have indicated that their BTLs are ready for the new behavior. So far the following are supported (or no changes were needed): openib, scif, self, sm, smcuda, tcp, ugni, and vader.

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres When we are ready this PR will bring everything into master.

**Comment by hjelmn** [comment]
Rebased and fixed a typo in coll/fca.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
Hmm, something went wrong in rebase. Fixing.

**Comment by hjelmn** [comment]
Ok, even worse. Ignore this. Will fix from work.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
Looks like add_procs breaks oshmem. Will take a look now.

**Comment by hjelmn** [comment]
@miked-mellanox How was spml/mpi working at all? It uses ompi_group_incl then ompi_comm_create_group AFTER modifying ompi_proc_local_proc. The call to ompi_group_incl sets grp_my_rank based off ompi_proc_local_proc. In this case the proc is not in the group so grp_my_rank gets set to MPI_UNDEFINED. This causes ompi_comm_create_group to blowup.

We either need to modify the _incl code to set the local rank with a different proc pointer (lookup the proc associated with the rank in the old group) or you need to modify the group to set the rank before ompi_comm_create_group.

**Comment by hjelmn** [comment]
@miked-mellanox BTW, you guys should modify your code to take advantage of the new add_procs behavior. Right now if oshmem is in use we will end up allocating procs for all remote ranks.

**Comment by miked-mellanox** [comment]
@igor-ivanov , @alex-mikheev - could you please address these comments? thanks

**Comment by igor-ivanov** [comment]
I hope that issue relates scoll:mpi component only that has the highest priority. Disabling one as -mca scoll ^mpi makes hello_oshmem example workable.

**Comment by hjelmn** [comment]
This problem only seems to affect the mpi component. I will submit a temporary fix as this PR needs to go in now.

**Comment by jladd-mlnx** [comment]
@miked-mellanox,  it is @bureddy 's responsibility to handle Yalla and MTL/MXM layers to take advantage of this capability. Devendar, please provide an updated ETA. We also need to port these changes over to the OSHMEM layer (oshmem add procs.) @igor-ivanov, please begin looking into this.

**Comment by jladd-mlnx** [comment]
@hjelmn, you mentioned some time ago that you collected "hello world!" end-to-end timings for full modex versus direct modex. Could you, please, attach the data to this PR?

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
False failure from LANL-Cray XC.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by igor-ivanov** [comment]
@hjelmn, I believe that basic jenkins test reported issue in scoll:mpi but I guess PR changes could impact oshmem code in other places and we need to look at this carefully.

**Comment by jsquyres** [comment]
@igor-ivanov Ok, thanks.  @hjelmn is two timezones west of me; I don't know offhand what time he typically gets online in the morning.  I know he was still looking into this yesterday afternoon, so any information you have that can help out would be great.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
@jladd-mlnx I don't have the timing numbers but the memory savings on an XE-6 is significant. At 4096 processes I see about 4 MB/process memory savings. This is measured with a code Sam wrote awhile back.

This PR doesn't break oshmem so I will go ahead and merge it so we can start running it through MTT.  I can make myself available to @igor-ivanov if he needs any help/pointers on what should be done to make oshmem take advantage of the new add_procs behavior.

**Comment by hjelmn** [comment]
Pulled out the comm_split_type update. Will PR it separately.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
