### PR TITLE
opal/util: Move cuda copy code to util from common

### PR DESCRIPTION
**Pull request by wckzhang**
As the cuda copy code needs to be included into the
datatype converter, it introduced an open-pal dependency
on the common component. To avoid this, we move the
code into util. This also addresses a bug with
--enable-dynamic-dso and --with-cuda.

Signed-off-by: William Zhang <wilzhang@amazon.com>

### CODE REVIEW

**Comment by wckzhang** [comment]
This will fix #9762

**Comment by bosilca** [comment]
With this approach the CUDA code is spread across the code base. I don't understand why the existence of common/cuda is a problem when we can simply always build it as part of the main libmpi.so.

**Review by gpaulsen — COMMENTED** [review]
I assume it's intentional NOT to move the call to `opal_cuda_add_initialization_function()` from `mca_common_cuda_stage_one_init()`?
Should this PR then also move the implementation of `common_cuda_memory_registrations`? to `opal/util` somewhere?

**Review by bwbarrett — CHANGES_REQUESTED** [review]
@bosilca the problem with common is that it was never designed for the core libraries (libopen-pal.so, libmpi.so) to depend on symbols in a common library.  They were just intended to be used for shared code between components.

I'm 99% sure that the right answer here is not to put this in util/, but to create a new framework for accelerator copies and make CUDA one component (with the expectation that ROCM and Xe's library also get components).  This would also simplify some of the CUDA code (I think) by making it not have to do the dlsym bits.

**Comment by edgargabriel** [comment]
@bwbarrett I like the idea of an accelerator framework. The question in that case would be whether we can get the datatype code accelerator agnostic. Not entirely sure whether we could get rid of the dlsym loading of functions, otherwise wouldn't we have again dependency issues in case of static linking?

**Comment by bwbarrett** [comment]
And you're right about the static linking, but the dlsym trick won't work if we --disable-dlopen, and I think we should just make those components always build dynamic by default.

**Comment by edgargabriel** [comment]
Follow up question: would a framework based approach for accelerators allow us to simplify some of the bootstrapping logic, e.g. getting rid of the 'is compiled and enabled' vs. 'compiled but not enabled', etc?

**Comment by bwbarrett** [comment]
The compile time checks were all about performance, particularly in the datatype engine.  I think those would be hard to overcome.

**Pull request closed without merging**
