### PR TITLE
[v4.1.x] pml/ucx: fix zero sized datatype transfers

### PR DESCRIPTION
**Pull request by AboorvaDevarajan**
Signed-off-by: Aboorva Devarajan <aburvadevarajan@gmail.com>
(cherry picked from commit 202b81d95c7b6eb638f95f17fb82ac050765a3ef)

### CODE REVIEW

**Comment by jjhursey** [comment]
ok to test

**Review by hoopoepg — APPROVED** [review]

**Review by hoopoepg — APPROVED** [review]

**Comment by jsquyres** [comment]
@hoopoepg Did you mean to also approve #8143 (i.e., the v4.0.x version of this PR)?

**Comment by jsquyres** [comment]
bot:ompi:retest

**Review by hoopoepg — APPROVED** [review]

**Comment by jsquyres** [comment]
@hoopoepg You have now approved this PR 3 times, but still not approved the v4.0.x version (#8143).  😆

**Comment by hoopoepg** [comment]
Approved there too :)

**Pull request merged**
