### PR TITLE
OSC/pt2pt: disable pt2pt when UCX PML is selected

### PR DESCRIPTION
**Pull request by hoopoepg**
Signed-off-by: Sergey Oblomov <sergeyo@mellanox.com>

### CODE REVIEW

**Comment by hoopoepg** [comment]
@yosefe will it work?

**Comment by jsquyres** [comment]
We strongly discourage string comparing against specific component names.

Is there a capability that can be checked, instead?

**Comment by hoopoepg** [comment]
@jsquyres technically it is possible, but it will require osc->pml module dependency.
for now this hack allows eliminate crash of 1-sided tests, I'm going to investigate what is wrong with pt2pt over UCX, and try to fix it

**Comment by hoopoepg** [comment]
@jsquyres right, components may be identified by name only

**Comment by jsquyres** [comment]
If it's a bug in the UCX PML, that's likely what should be fixed -- not putting a hackaround over here in this component.  Make sense?

**Comment by hjelmn** [comment]
no. there are times when ucx can not do rdma and osc/rdma can not be used. fix the bug. this pr will not be accepted

**Pull request closed without merging**
