### PR TITLE
PML UCX: handle synchronous send & unite code for all the sending modes

### PR DESCRIPTION
**Pull request by alinask**
Signed-off-by: Alina Sklarevich <alinas@mellanox.com>
(cherry picked from commit 49913c692a67cd5189b59fb1d62c2063a74ba219)

### CODE REVIEW

**Comment by bwbarrett** [comment]
bot:ompi:retest

Looks like UH had some trouble pulling from Github.  We had Jenkins configured to not retry on a failed pull; bumped that up to 5 so hopefully we don't see these false failures in the future.

**Comment by jsquyres** [comment]
Missed the v2.1.1 window, sorry.  Bumped to v2.1.2.

**Comment by alinask** [comment]
@hppritcha Can you please merge?

**Comment by alinask** [comment]
@jsquyres @hppritcha Can this be merged please?

**Comment by jsquyres** [comment]
As I said a few days ago, this missed this v2.1.1 window.  It's been bumped to v2.1.2.

**Comment by jladd-mlnx** [comment]
@jsquyres Understood. But can it be merged so that we can get it covered under our internal MTT, please.

**Comment by jsquyres** [comment]
We have not released v2.1.1 yet -- we can't merge it until the v2.x tree has released the v2.1.1 release, sorry.

**Pull request merged**
