### PR TITLE
opal_check_cma: make consistent with rest of configury

### PR DESCRIPTION
**Pull request by jsquyres**
Split the CMA test into two parts so that the back-end test only has to be run once.  Fail with --with-cma is specified and cannot be provided.  Remove a few useless quotes.  Change $ompi_check_cma_need_defs and $ompi_check_cma_happy to be numeric values.  Finally, remove a bunch of tabs.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

@hjelmn Please review and consider adding to open-mpi/ompi-release#1306.

### CODE REVIEW

**Comment by jsquyres** [comment]
@hjelmn bump

**Comment by hjelmn** [comment]
Looks fine to me. I assume you tried this to make sure it works?

**Comment by hjelmn** [comment]
:bot:retest

Want to see the output of the various tests. The output has fallen off.

**Comment by jsquyres** [comment]
@hjelmn Yes, it worked for me.  I just wanted to make sure it worked for you, since you were the one who reported the issue.

**Comment by jsquyres** [comment]
It looks like all the LANL-Cray resources are currently offline.

**Pull request merged**
