### PR TITLE
v4.0.x: Oshmem multiple contexts

### PR DESCRIPTION
**Pull request by janjust**
Cherry-picked commits from #6492
This PR replaces #6443

### CODE REVIEW

**Comment by janjust** [comment]
@brminich @hoopoepg ; this is the v4.0.x branch, of #6492 , please review

**Comment by gpaulsen** [comment]
This looks like it might be related to https://github.com/open-mpi/ompi/pull/6443.  Any advice regarding both of these?
Is it okay if this waits until v4.0.2?

**Comment by janjust** [comment]
@gpaulsen #6443 is a stale PR, #6509 replaces it, we're hoping to get this PR in 4.0.1 rather than wait for 4.0.2

**Comment by janjust** [comment]
@jsquyres corresponding cherry-picks fixed in this PR also

**Comment by gpaulsen** [comment]
@jsquyres please re-review (or at least dismiss your earlier change request) when you get a moment.  Thanks.

**Comment by jsquyres** [comment]
@gpaulsen I'm not qualified to review this one -- it's all about oshmem and UCX.  I just made the one comment about superfluous commits + cherry pick hashes.  That being said, the corresponding master PR hasn't been merged yet.  So this PR still isn't ready.

**Comment by hppritcha** [comment]
@gpaulsen sorry this PR missed the train.  It can go out in 4.0.2.

**Comment by hppritcha** [comment]
@jsquyres PR for master has been merged in so dismissing your review.

**Pull request merged**
