### PR TITLE
Update PMIx

### PR DESCRIPTION
**Pull request by rhc54**
- Silence a few (valid) warnings

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7ba0de36c37a5b3df60a2feaf9aa0e5b

**Comment by rhc54** [comment]
bot:ibm:xl:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fe75f1d43e08055e673f745315966f2a

**Comment by rhc54** [comment]
bot:ibm:scale:retest

**Pull request merged**
