### PR TITLE
Import the HAN collective into 4.1

### PR DESCRIPTION
**Pull request by bosilca**
Bring https://github.com/open-mpi/ompi/pull/7735 to 4.1

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca Are you going to merge the equivalent PR into master?  We like to have things in master before release branches...

**Comment by bosilca** [comment]
I would love to have a review before merging the PR in master. Any volunteers ?

**Comment by jsquyres** [comment]
> I would love to have a review before merging the PR in master. Any volunteers ?

I was going to review for v4.1, so I'll do master to.  Will take 24 hours or so.

**Comment by jsquyres** [comment]
Converted this back to draft just so that we don't accidentally merge it until the corresponding master PRs are merged and the updates are brought back here to this PR.

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
bot:ompi:retest

**Review by jsquyres — APPROVED** [review]
This tested fine for me on the v4.1.x branch:

* Plain (without HAN or ADAPT)
* HAN
* HAN + ADAPT

All gave the same results.

**Pull request merged**
