### PR TITLE
hwloc: patch to handle hwloc 1.11.x and older

### LINKED ISSUE #7362: Recent hwloc base change breaks external hwloc <= v2.0.x
PR #7201 causes compile errors on master when compiling with older versions of hwloc (older than v2.0.x).

Open MPI master still supports hwloc >= v1.5.x.  Are we changing this to be >= v2.0.x?

Specifically, when I try compiling Open MPI master HEAD with an external installation of 1.5.1, I get the following compile error:

```
make[1]: Entering directory `/home/jsquyres/git/ompi/opal/mca/hwloc'
  CC       base/hwloc_base_util.lo
base/hwloc_base_util.c: In function ‘opal_hwloc_base_find_coprocessors’:
base/hwloc_base_util.c:1393:12: warning: unused variable ‘cps’ [-Wunused-variable]
     char **cps = NULL;
            ^~~
base/hwloc_base_util.c:1392:14: warning: unused variable ‘i’ [-Wunused-variable]
     unsigned i;
              ^
base/hwloc_base_util.c:1391:17: warning: unused variable ‘osdev’ [-Wunused-variable]
     hwloc_obj_t osdev;
                 ^~~~~
base/hwloc_base_util.c: In function ‘opal_hwloc_base_get_locality_string’:
base/hwloc_base_util.c:2207:30: error: ‘obj’ undeclared (first use in this function)
                     if (3 == obj->attr->cache.depth) {
                              ^~~
base/hwloc_base_util.c:2207:30: note: each undeclared identifier is reported only once for each function it appears in
```

It looks like ea80a20e108cb69efc67ad04ad968da7b85772af removed the declaration and initialization of `obj` for `HWLOC_API_VERSION < 0x20000`.

What do we want to do here?

FYI @bgoglin @hppritcha

### PR DESCRIPTION
**Pull request by hppritcha**
PR #7201 broke use of hwloc 1.x series.  this patches gets hwloc 1.x working again with OMPI

fixes #7362

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
@bgoglin please check this and suggest changes if warranted

**Comment by bgoglin** [comment]
I actually just pushed 2 commits and was going to make a PR to get @jsquyres promised beer.
https://github.com/bgoglin/ompi/commit/907ad854b46b42ae7cb1e9c87238691a5cc25e36 is similar to yours, but I didn't have to add a idx parameters like you did, and things worked fine in my testing.
https://github.com/bgoglin/ompi/commit/329d4451a6cdd544e532a29f594f6e5ee63e06da is for @jsquyres warnings but those are totally unrelated and only matter for hwloc 1.7 so we could ignore this part.

**Comment by jsquyres** [comment]
@hppritcha Brice's commits are actually a bit cleaner...

**Comment by hppritcha** [comment]
closing.  shouldn't have wasted my time.

**Pull request closed without merging**
