### PR TITLE
Topic/atomicity

### PR DESCRIPTION
**Pull request by edgargabriel**
add support to atomicity operations in ompio

### CODE REVIEW

**Comment by edgargabriel** [comment]
tested so far with our own testsuite, and the hdf5 testsuite, all tests pass.

**Review by raafatfeki — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ade6f2a8118193ee3224a976ba5af566

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/129ab6c511111ccfe73a63b2cd51b153

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/03900bdd10bf0a47c739425d34f3786e

**Comment by edgargabriel** [comment]
the failures are not related to this pr

**Comment by rhc54** [comment]
Yeah, looks like IBM got cutoff in mid test.

bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b243fb17cb91acd92b7324ef3dad81f5

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6db8cbd62b9e0c6f4ea8a42cda9959c2

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c19aefaf8402c0101f2f8f8e008d18df

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f831511188981c4854ab85442482dcb2

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/73f571d303e87b0a7c376221c5532936

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d0401135b5d53feb37101953cf248675

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by gpaulsen** [comment]
@edgargabriel Is this just for master or intended for release branches as well?

**Comment by edgargabriel** [comment]
@gpaulsen definitely for 5.0, but we can also have a discussion on whether to have that also available for the 4.1 branch. Basically, the question is whether it is a new feature or a bug fix ( I can make the case either way )

**Comment by edgargabriel** [comment]
btw is the signed-off-by checker hanging or why is it not happy?

**Comment by jsquyres** [comment]
> btw is the signed-off-by checker hanging or why is it not happy?

It means that a notice got dropped somewhere in the webhook.  I found the back-end entry and got it re-delivered -- CI is now happy.

**Comment by edgargabriel** [comment]
@jsquyres Thanks!

**Pull request merged**
