### PR TITLE
minor orte compiler warning fixes

### PR DESCRIPTION
**Pull request by jsquyres**
@rhc54 Minor ORTE compiler warning fixes -- can you eyeball these before merging them in?

The only question I had was returning ORTE_ERROR -- I didn't see any other obvious/more descriptive error value to return.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Coverity 767 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_271/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Coverity 20 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_271/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Coverity 2 errors for mxm: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/mxm_271/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/271/
Test PASSed.

**Comment by rhc54** [comment]
We typically use ORTE_ERR_NOT_FOUND, but it doesn't really matter - the generic ERROR is fine. The key thing is that the output tells us _where_ the error is occurring.

**Pull request merged**
