### PR TITLE
Bring the more flexible AVX* support in 4.1

### LINKED ISSUE #8306: open-mpi 4.1.0 build failure (AVX)
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

open-mpi 4.1.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Install process detailed in [this formula](https://github.com/Homebrew/homebrew-core/blob/0b188edf388456e41900f505ffe4e716011ce6d2/Formula/open-mpi.rb)

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A (I am using release tarball)

### Please describe the system on which you are running

* Operating system/version: osx
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

<details>
<summary>build failure</summary>

```
op_avx_functions.c:454:5: error: always_inline function '_mm512_loadu_si512' requires target feature 'avx512f', but would be inlined into function 'ompi_op_avx_2buff_max_int8_t_avx512' that is compiled without support for 'avx512f'
    OP_AVX_FUNC(max, i, 8,    int8_t, max)
    ^
op_avx_functions.c:124:5: note: expanded from macro 'OP_AVX_FUNC'
    OP_AVX_AVX512_FUNC(name, type_sign, type_size, type, op);                  \
    ^
op_avx_functions.c:69:29: note: expanded from macro 'OP_AVX_AVX512_FUNC'
            __m512i vecA =  _mm512_loadu_si512((__m512*)in);                   \
                            ^
op_avx_functions.c:454:5: error: always_inline function '_mm512_loadu_si512' requires target feature 'avx512f', but would be inlined into function 'ompi_op_avx_2buff_max_int8_t_avx512' that is compiled without support for 'avx512f'
op_avx_functions.c:124:5: note: expanded from macro 'OP_AVX_FUNC'
    OP_AVX_AVX512_FUNC(name, type_sign, type_size, type, op);                  \
    ^
op_avx_functions.c:71:29: note: expanded from macro 'OP_AVX_AVX512_FUNC'
            __m512i vecB =  _mm512_loadu_si512((__m512*)out);                  \
                            ^
op_avx_functions.c:454:5: error: always_inline function '_mm512_max_epi8' requires target feature 'avx512bw', but would be inlined into function 'ompi_op_avx_2buff_max_int8_t_avx512' that is compiled without support for 'avx512bw'
op_avx_functions.c:124:5: note: expanded from macro 'OP_AVX_FUNC'
    OP_AVX_AVX512_FUNC(name, type_sign, type_size, type, op);                  \
    ^
op_avx_functions.c:72:27: note: expanded from macro 'OP_AVX_AVX512_FUNC'
            __m512i res = _mm512_##op##_ep##type_sign##type_size(vecA, vecB);  \
                          ^
<scratch space>:194:1: note: expanded from here
_mm512_max_epi8
^
            _mm256_storeu_si256((__m256i*)out, res);                           \
            ^
op_avx_functions.c:456:5: error: always_inline function '_mm512_loadu_si512' requires target feature 'avx512f', but would be inlined into function 'ompi_op_avx_2buff_max_int16_t_avx512' that is compiled without support for 'avx512f'
    OP_AVX_FUNC(max, i, 16,  int16_t, max)
    ^
op_avx_functions.c:124:5: note: expanded from macro 'OP_AVX_FUNC'
    OP_AVX_AVX512_FUNC(name, type_sign, type_size, type, op);                  \
    ^
op_avx_functions.c:69:29: note: expanded from macro 'OP_AVX_AVX512_FUNC'
            __m512i vecA =  _mm512_loadu_si512((__m512*)in);                   \
                            ^
op_avx_functions.c:456:5: error: always_inline function '_mm512_loadu_si512' requires target feature 'avx512f', but would be inlined into function 'ompi_op_avx_2buff_max_int16_t_avx512' that is compiled without support for 'avx512f'
op_avx_functions.c:124:5: note: expanded from macro 'OP_AVX_FUNC'
    OP_AVX_AVX512_FUNC(name, type_sign, type_size, type, op);                  \
    ^
op_avx_functions.c:71:29: note: expanded from macro 'OP_AVX_AVX512_FUNC'
            __m512i vecB =  _mm512_loadu_si512((__m512*)out);                  \
                            ^
op_avx_functions.c:456:5: error: always_inline function '_mm512_max_epi16' requires target feature 'avx512bw', but would be inlined into function 'ompi_op_avx_2buff_max_int16_t_avx512' that is compiled without support for 'avx512bw'
op_avx_functions.c:124:5: note: expanded from macro 'OP_AVX_FUNC'
    OP_AVX_AVX512_FUNC(name, type_sign, type_size, type, op);                  \
    ^
op_avx_functions.c:72:27: note: expanded from macro 'OP_AVX_AVX512_FUNC'
            __m512i res = _mm512_##op##_ep##type_sign##type_size(vecA, vecB);  \
                          ^
<scratch space>:226:1: note: expanded from here
_mm512_max_epi16
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [liblocal_ops_avx512_la-op_avx_functions.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1579487261
relates to https://github.com/Homebrew/homebrew-core/pull/67221

### PR DESCRIPTION
**Pull request by bosilca**
Allow more flexibility on the support of AVX* extensions.

Use cached variables to prevent OMPI from checking specific architecture features. As an example this will allow to disable AVX512 while allowing AVX2.
Protect the code against mismatched flags between configure and make.
Document the list of of vectorial functions we need and the corresponding level of AVX, SSE required.

This is #8322 for 4.1

Fixes #8306

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Comment by leofang** [comment]
Hi @bosilca Any chance this change would break `--allow-run-as-root`? On Conda-Forge we do `mpiexec --allow-run-as-root ...` as the CI runs in a docker, but after applying this patch I'm seeing this error:
```
mpiexec: Error: unknown option "--allow-run-as-root"
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=261970&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=22345
All tests in https://github.com/conda-forge/openmpi-feedstock/pull/71 currently fail due to this.

**Comment by jsquyres** [comment]
No, this should have nothing to do with `--allow-run-as-root`.

I notice in your Azure run output:

```
+ /home/conda/feedstock_root/build_artifacts/openmpi-mpi_1610390538879/test_tmp/mpiexec.sh --help
$PREFIX/bin/mpiexec
mpiexec: Error: unknown option "--allow-run-as-root"
```

What's `mpiexec.sh`?

**Comment by leofang** [comment]
Hi @jsquyres It's just a little script wrapping over `mpiexec`:
https://github.com/conda-forge/openmpi-feedstock/blob/master/recipe/mpiexec.sh
It seems we've been using it fine for quite a long time (before I knew anything about conda or mpi).

**Comment by leofang** [comment]
and this is where it gets called:
https://github.com/conda-forge/openmpi-feedstock/blob/master/recipe/run_test.sh

**Comment by jsquyres** [comment]
It looks like `mpiexec.sh` is just calling `mpiexec` (i.e., via relative path name, not absolute path name).  Can you confirm that you're calling the "right" `mpiexec`?

**Comment by leofang** [comment]
@jsquyres This is a clean/minimal environment so it's very likely impossible. We ensure conda's stuff is first found in $PATH. Tested locally on the same image:
```
$ docker run --rm -it quay.io/condaforge/linux-anvil-cuda:9.2
[conda@6fbb320a1381 ~]$ which mpiexec
/usr/bin/which: no mpiexec in (/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin:/usr/local/cuda/bin)
[conda@6fbb320a1381 ~]$ command -v mpiexec
[conda@6fbb320a1381 ~]$ echo $?
1
```
That said, I'm happy to print the command out 🙂 Let me wait for the current run to finish...(I'm reverting this patch to see if the `--allow-run-as-root` error still happens or not).

**Comment by leofang** [comment]
> Let me wait for the current run to finish...(I'm reverting this patch to see if the `--allow-run-as-root` error still happens or not).

Hi @jsquyres Looks like a simple revert fixes the error: https://github.com/conda-forge/openmpi-feedstock/pull/71/commits/4dac571911bb8b21910e7ef5801ab0a2cf7e7c04

Here's the CI output: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=262072&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642

Any thoughts?

**Comment by jsquyres** [comment]
Wow, that's... weird.  You've got me stumped on that, because this is what I get from a v4.1.x branch HEAD build:

```
$ mpirun --allow-run-as-root uptime
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:00 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
 14:12:01 up 492 days, 10:44, 82 users,  load average: 2.90, 2.91, 1.86
[2:12] savbu-usnic-a:~/g/ompi (v4.1.x)
$ mpirun --version
mpirun (Open MPI) 4.1.1a1

Report bugs to http://www.open-mpi.org/community/help/
```

The patch itself has zero to do with the mpirun command line parsing stuff.  I don't know how applying that patch would disable the `--allow-run-as-root` CLI option. ☹️

**Comment by leofang** [comment]
@jsquyres Question: which file(s) is this option implemented? Is it in one of the 4 files touched here?

**Comment by leofang** [comment]
Apology, @jsquyres. I rerun our CI with the patch applied, and everything is green (so far). Looks like it was a transient error due to [Conda's build infrastructure](https://gitter.im/conda-forge/conda-forge.github.io?at=5ffcac2303529b296be3a044) that messed up with text patches among other things...😞 Thanks a lot (as always) for you help!

**Pull request merged**
