### PR TITLE
Mellanox Open MPI CI: optimized git checkout step to reduce CI duration (v4.0.x)

### PR DESCRIPTION
**Pull request by artemry-mlnx**
Signed-off-by: Artem Ryabov <artemry@mellanox.com>

### CODE REVIEW

**Comment by rhc54** [comment]
ok to test

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by artemry-mlnx** [comment]
CC @amaslenn

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by gpaulsen** [comment]
Yes, thanks.  We'll take this one post v4.0.3

**Comment by gpaulsen** [comment]
Jeff reached out and let us know that we already took this PR into v4.0.x, so we should consider taking this sooner than later.
I want to understand the Mellanox CI failure first however.  I'm reaching out to @jladd-mlnx and @artemry-mlnx via email to ask for help.

**Comment by artemry-mlnx** [comment]
Mellanox Open MPI CI failure is expected ([detailed log file](https://dev.azure.com/mlnx-swx/9a715c71-515f-4a6f-a324-ca65880a05ca/_apis/build/builds/457/logs/8)) - it's because of Open MPI behavioral changes in https://github.com/open-mpi/ompi/pull/7202 which were reflected in the CI scripts https://github.com/mellanox-hpc/jenkins_scripts/pull/92 (see this comment https://github.com/mellanox-hpc/jenkins_scripts/pull/92#issuecomment-583758646).
Need to fork CI tests specifically to Open MPI v4.0.x (there's no plan to port https://github.com/open-mpi/ompi/pull/7202 to v4.0.x - https://github.com/open-mpi/ompi/pull/7202#issuecomment-584151540) and switch CI to them in v4.0.x - I'll deal with this.

**Comment by jsquyres** [comment]
@artemry-mlnx Gotcha.  FWIW, I maintain different config files for Cisco's testing of different Open MPI branches for exactly this reason (the behavior and/or CLI params changes over time).

**Comment by jladd-mlnx** [comment]
bot:mellanox:retest

**Comment by artemry-mlnx** [comment]
@jladd-mlnx 
Mellanox Open MPI v4.0.x CI will pass only after https://github.com/open-mpi/ompi/pull/7468
Pay attention that `bot:mellanox:retest` is not supported by Azure Pipelines so please use `/azp run` to restart Mellanox CI (see [README](https://github.com/open-mpi/ompi/blob/master/.ci/README.md) for details).

**Comment by gpaulsen** [comment]
Hmm.  This is failing on perhaps the only test that passes `--am /__w/2/ompi/test_amca.conf` to mpirun.  there's another test that passes `--tune /__w/2/ompi/test_amca.conf`.  @artemry-mlnx could you please take a look?

**Comment by artemry-mlnx** [comment]
@gpaulsen 
Mellanox Open MPI CI for v4.0.x passes after https://github.com/open-mpi/ompi/pull/7468

**Comment by artemry-mlnx** [comment]
Could anyone please merge this PR?

**Comment by jsquyres** [comment]
Milestone wasn't set -- the v4.0 RMs probably didn't see this PR.

**Pull request merged**
