### PR TITLE
Yoda removal (update docs)

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
@bwbarrett I only could cherry-pick README commit from #3916 as NEWS are outdated.
Please advise how to proceed.

**Comment by bwbarrett** [comment]
Whether it's a cherry-pick or a modified version of the patch, the spirit of my comment was to make sure that your change ended up in both master and v3.0.x.  Yes, others have not done this well, but we're going to try to force people to be better at keeping the files up to date in time...

**Comment by artpol84** [comment]
@bwbarrett I sync'd NEWS with v3.0.x. I don't see other options.

**Comment by bwbarrett** [comment]
sigh; sorry, we've been falling down on the job.

**Pull request merged**
