### PR TITLE
Repair the processing of cmd line options that mapped to MCA params.

### PR DESCRIPTION
**Pull request by rhc54**
This was responsible for breaking things like ```map-by foo```

Fixes https://github.com/open-mpi/ompi/issues/1623

### CODE REVIEW

**Comment by rhc54** [comment]
Spent a bunch of time tracking down this "error" from the Mellanox Jenkins, and I don't think the test is correct. The cmd line shown in fact works correctly:

```shell
$  mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env | grep XXX
OMPI_MCA_mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E
XXX_E=5
XXX_D=4
XXX_C=3
OMPI_MCA_mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E
XXX_E=5
XXX_D=4
XXX_C=3
$
```
So when you run that thru ```wc -l```, you will get an answer of 8, not 6.

**Comment by rhc54** [comment]
Should note: the Jenkins test only exports valus for C, D, and E. Perhaps it was expecting that A and B would be set? If so, then I'm not sure where and how that was supposed to be done, and will have to look further at some point.

**Comment by ggouaillardet** [comment]
@rhc54 I previously noticed Jenkins script explicitly export A and B before invoking mpirun

**Comment by rhc54** [comment]
Sadly, there is no documentation anywhere on these tests, nor are they available to me - nor is the functionality particularly documented in the code. So I'm working my way thru them as best I can.

Progress is being made...

**Comment by ggouaillardet** [comment]
I looks like there is a
set -x
in the Jenkins script, this is how I found it when reading the logs
I previously suggested all Jenkins scripts should be public (read only github repo looks fine) so anyone can understand what is tested and how. shall I add this to the agenda of the next telcon ?

**Comment by rhc54** [comment]
sure - it would definitely help

**Comment by jsquyres** [comment]
@jladd-mlnx @Di0gen can you please comment on this conversation?

**Comment by miked-mellanox** [comment]
@ggouaillardet - the script is public and here (also mindist.c test)

https://github.com/mellanox-hpc/jenkins_scripts

**Comment by ggouaillardet** [comment]
thanks @miked-mellanox 
@rhc54 here is what is broken
```bash
export XXX_A=1
echo XXX_B=2 > xxx.conf
mpirun -np 1 -am xxx.conf env | grep ^XXX
```
```XXX_B``` is not exported

git bisect indicates open-mpi/ompi@58dd41facf4c6f56066158dc739f953f4ad8d639 is the guilty commit
according to the logs open-mpi/ompi@2839484737ed9b5162f13254b91fd52bf268df32 might have been an attempt to fix it, but it did not fix this specific test case.

**Comment by rhc54** [comment]
Yes, I know - I pointed that out in an issue I filed, and requested help to decipher the AMCA stuff as it isn't very well commented 😄

**Pull request merged**
