### PR TITLE
rcache/base: add missing include

### LINKED ISSUE #2141: rcache/gpusm compile error on v2.x
MTT build error on v2.x :
https://mtt.open-mpi.org/index.php?do_redir=2359

It seems includes are missing but the changes are so big it's not clear to me how this should be fixed.

`In file included from rcache_gpusm_module.c:41:0:
../../../../opal/mca/rcache/base/base.h:44:22: error: unknown type name ‘mca_base_framework_t’
 OPAL_DECLSPEC extern mca_base_framework_t opal_rcache_base_framework;`

### PR DESCRIPTION
**Pull request by hjelmn**
Fixes #2141

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
Should fix the compile error on the nVidia MTT.

**Comment by sjeaugey** [comment]
That seems to fix the compilation issue indeed. :+1:

**Comment by jsquyres** [comment]
@hjelmn This is targeting v2.1.0, right?

**Comment by jsquyres** [comment]
bot:lanl:retest

**Pull request merged**
