### PR TITLE
docs: add notes about dependency versions

### PR DESCRIPTION
**Pull request by jsquyres**
In general, recommend using the latest versions of Hwloc, OpenPMIx, and PRRTE.

-----

You can see the rendered version of this PR here: https://ompi--12836.org.readthedocs.build/en/12836/installing-open-mpi/required-support-libraries.html

### CODE REVIEW

**Review by rhc54 — COMMENTED** [review]
Won't let me comment inline, so I'll add a note here. Line 81 references the PMIx standard page, yet the text all talks about the library. Would it make sense to point to the library's page or repo? Or perhaps point to the RTD site for the library?

**Review by rhc54 — APPROVED** [review]
I confess I struggle with this "OpenPMIx" nonsense, but I guess it is where we are for the moment. Note that there is no space in the name (haha).

**Comment by jsquyres** [comment]
> Note that there is no space in the name (haha).

You're killing me, Smalls!  😄  Fixed.

**Comment by rhc54** [comment]
I was actually suggesting using PMIx everywhere in the text and just change the link to point to the openpmix rtd site - but that's just me 😉

**Comment by jsquyres** [comment]
Ok, I think this PR is ready for review / approval.

**Review by abouteiller — APPROVED** [review]

**Pull request merged**
