### PR TITLE
v3.1.x: Update to PMIx v2.1.2

### PR DESCRIPTION
**Pull request by rhc54**
Plus cleanup some errors and warnings

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ee6e20042243a47394d4f59e8bbbc510

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7b7e0063b928827b288768d225098098

**Comment by rhc54** [comment]
MTT before PR:
```
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                          |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| MPI Install | my installation | 3.1.2a1     | 00:00    | 1    |      |          |      | MPI_Install-my_installation-my_installation-3.1.2a1-my_installation.html |
| Test Build  | trivial         | 3.1.2a1     | 00:01    | 1    |      |          |      | Test_Build-trivial-my_installation-3.1.2a1-my_installation.html          |
| Test Build  | ibm             | 3.1.2a1     | 00:41    | 1    |      |          |      | Test_Build-ibm-my_installation-3.1.2a1-my_installation.html              |
| Test Build  | intel           | 3.1.2a1     | 00:31    | 1    |      |          |      | Test_Build-intel-my_installation-3.1.2a1-my_installation.html            |
| Test Build  | orte            | 3.1.2a1     | 00:00    | 1    |      |          |      | Test_Build-orte-my_installation-3.1.2a1-my_installation.html             |
| Test Run    | trivial         | 3.1.2a1     | 00:03    | 2    |      |          |      | Test_Run-trivial-my_installation-3.1.2a1-my_installation.html            |
| Test Run    | ibm             | 3.1.2a1     | 09:33    | 396  |      |          |      | Test_Run-ibm-my_installation-3.1.2a1-my_installation.html                |
| Test Run    | spawn           | 3.1.2a1     | 00:10    | 7    |      |          | 1    | Test_Run-spawn-my_installation-3.1.2a1-my_installation.html              |
| Test Run    | loopspawn       | 3.1.2a1     | 10:01    | 1    |      |          |      | Test_Run-loopspawn-my_installation-3.1.2a1-my_installation.html          |
| Test Run    | intel           | 3.1.2a1     | 12:28    | 242  |      |          | 2    | Test_Run-intel-my_installation-3.1.2a1-my_installation.html              |
| Test Run    | intel_skip      | 3.1.2a1     | 09:18    | 222  |      |          | 22   | Test_Run-intel_skip-my_installation-3.1.2a1-my_installation.html         |
| Test Run    | orte            | 3.1.2a1     | 00:44    | 19   |      |          |      | Test_Run-orte-my_installation-3.1.2a1-my_installation.html               |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+


    Total Tests:    894
    Total Failures: 0
    Total Passed:   894
    Total Duration: 2610 secs. (43:30)
```

**Comment by rhc54** [comment]
MTT with this PR:
```
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                          |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| MPI Install | my installation | 3.1.2a1     | 00:01    | 1    |      |          |      | MPI_Install-my_installation-my_installation-3.1.2a1-my_installation.html |
| Test Build  | trivial         | 3.1.2a1     | 00:01    | 1    |      |          |      | Test_Build-trivial-my_installation-3.1.2a1-my_installation.html          |
| Test Build  | ibm             | 3.1.2a1     | 00:39    | 1    |      |          |      | Test_Build-ibm-my_installation-3.1.2a1-my_installation.html              |
| Test Build  | intel           | 3.1.2a1     | 00:31    | 1    |      |          |      | Test_Build-intel-my_installation-3.1.2a1-my_installation.html            |
| Test Build  | orte            | 3.1.2a1     | 00:01    | 1    |      |          |      | Test_Build-orte-my_installation-3.1.2a1-my_installation.html             |
| Test Run    | trivial         | 3.1.2a1     | 00:02    | 2    |      |          |      | Test_Run-trivial-my_installation-3.1.2a1-my_installation.html            |
| Test Run    | ibm             | 3.1.2a1     | 09:24    | 396  |      |          |      | Test_Run-ibm-my_installation-3.1.2a1-my_installation.html                |
| Test Run    | spawn           | 3.1.2a1     | 00:10    | 7    |      |          | 1    | Test_Run-spawn-my_installation-3.1.2a1-my_installation.html              |
| Test Run    | loopspawn       | 3.1.2a1     | 10:05    | 1    |      |          |      | Test_Run-loopspawn-my_installation-3.1.2a1-my_installation.html          |
| Test Run    | intel           | 3.1.2a1     | 12:33    | 242  |      |          | 2    | Test_Run-intel-my_installation-3.1.2a1-my_installation.html              |
| Test Run    | intel_skip      | 3.1.2a1     | 09:08    | 222  |      |          | 22   | Test_Run-intel_skip-my_installation-3.1.2a1-my_installation.html         |
| Test Run    | orte            | 3.1.2a1     | 00:44    | 19   |      |          |      | Test_Run-orte-my_installation-3.1.2a1-my_installation.html               |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+


    Total Tests:    894
    Total Failures: 0
    Total Passed:   894
    Total Duration: 2599 secs. (43:19)

```

**Comment by jsquyres** [comment]
@bwbarrett FWIW, I'm good with this.  It went in on v3.0.x already.

**Pull request merged**
