### PR TITLE
mpiext/pcollreq: add Fortran bindings

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
Refs open-mpi/ompi#5426

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/87b8958ebfaf5d61aac365a7664bee2c

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cdc82659bd26bd9e4431c270ff3e0a48

**Comment by kawashima-fj** [comment]
@ggouaillardet We (Fujitsu) don't mind. Please go ahead.
(@t-kurita is my colleague in Fujitsu and I asked him to implement it.)

**Comment by kawashima-fj** [comment]
@ggouaillardet I had a review and found no problem. Please merge.

**Pull request merged**
