### PR TITLE
Recursive locks

### PR DESCRIPTION
**Pull request by hjelmn**
Add a class to support recursive mutexes.

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres We should see if this indeed resolves the deadlock. If it does this should be moved to 1.8 as well.

**Comment by mellanox-github** [comment]
* Coverity found 1288 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_322/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_322/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_322/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/322/

**Build Log**
*last 50 lines*

 ```
[...truncated 19882 lines...]
[jenkins01:08877] [ 3] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libopen-pal.so.0(opal_datatype_commit+0x3ef)[0x7ffff77e655f]
[jenkins01:08877] [ 4] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(ompi_datatype_init+0xd2)[0x7ffff7d7fe72]
[jenkins01:08877] [ 5] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(ompi_mpi_init+0x3d0)[0x7ffff7d74cd0]
[jenkins01:08877] [ 6] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(MPI_Init+0x1b0)[0x7ffff7d8c790]
[jenkins01:08877] [ 7] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c[0x400826]
[jenkins01:08877] [ 8] /lib64/libc.so.6(__libc_start_main+0xfd)[0x3d6901ed1d]
[jenkins01:08877] [ 9] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c[0x400739]
[jenkins01:08877] *** End of error message ***
[jenkins01:08875] *** Process received signal ***
[jenkins01:08875] Signal: Segmentation fault (11)
[jenkins01:08875] Signal code:  (128)
[jenkins01:08875] Failing at address: (nil)
[jenkins01:08875] [ 0] /lib64/libpthread.so.0[0x3d6980f710]
[jenkins01:08875] [ 1] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libopen-pal.so.0(opal_memory_ptmalloc2_int_free+0x2a1)[0x7ffff784cdc1]
[jenkins01:08875] [ 2] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libopen-pal.so.0(opal_memory_ptmalloc2_free+0xd3)[0x7ffff784d1e3]
[jenkins01:08875] [ 3] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libopen-pal.so.0(opal_datatype_commit+0x3ef)[0x7ffff77e655f]
[jenkins01:08875] [ 4] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(ompi_datatype_init+0xd2)[0x7ffff7d7fe72]
[jenkins01:08875] [ 5] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(ompi_mpi_init+0x3d0)[0x7ffff7d74cd0]
[jenkins01:08875] [ 6] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/lib/libmpi.so.0(MPI_Init+0x1b0)[0x7ffff7d8c790]
[jenkins01:08875] [ 7] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c[0x400826]
[jenkins01:08875] [ 8] /lib64/libc.so.6(__libc_start_main+0xfd)[0x3d6901ed1d]
[jenkins01:08875] [ 9] /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c[0x400739]
[jenkins01:08875] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node jenkins01 exited on signal 13 (Broken pipe).
--------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/322/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-master-pr/builds/322/tap-master-files/cov_stat.tap].
not ok - coverity detected 1288 failures in all_322 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_322/output/errors/index.html
not ok - coverity detected 11 failures in oshmem_322 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_322/output/errors/index.html
ok - coverity found no issues for yalla_322
ok - coverity found no issues for mxm_322
not ok - coverity detected 2 failures in fca_322 # TODO http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_322/output/errors/index.html
ok - coverity found no issues for hcoll_322

TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_322/output/errors/index.html
coverity_for_oshmem	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_322/output/errors/index.html
coverity_for_fca	http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_322/output/errors/index.html
[copy-to-slave] The build is taking place on the master node, no copy back to the master will take place.
Setting commit status on GitHub for https://github.com/open-mpi/ompi/commit/27289589f7353adb2a8c414c874fa742cf3e30e3
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 31344e7cd02d512b9ca856537313a38683d62e76 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/322/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
This PR is after open-mpi/ompi@3c489ea, which appears to be a bad commit.  When the DDT/malloc/alloca issue is fixed, this PR should be rebased and retested.

**Comment by jsquyres** [comment]
It looks like the issue was just fixed -- @hjelmn can you rebase on top of (at least) open-mpi/ompi@5905bd2ff97542d59e1d27f1c9a1c39e63e3bf7a?  Thanks...

**Comment by bosilca** [comment]
This is of no help in the current code. What is the purpose of this
addition?

**Comment by jsquyres** [comment]
This is the result of @hjelmn and my discussions about the attribute problem with PETSc.

After much off-list discussion between Fab and Jed, the issue boils down to an attribute callback function invoking another attribute function (on a different communicator).  In the current code, the lock is already held, and we deadlock.

Changing to code back to fine-grained locks is *possible* but *unattractive*.  Using a recursive lock seemed like it might well be a simple, good-enough solution.

**Comment by bosilca** [comment]
We had that discussion on our mailing lists before. My recollection of the
status is that:

1. the current code doesn't deadlock, Jed issue had been fixed a while ago.

2. Holding a recursive lock doesn't solve any problems, more than the code
is solving today. You still have the issues with adding/removing attributes
while in a callback, which will still break all the code (because the
recursive mutex will allow to do so).

  George.

PS: For more information read the email thread on the user mailing list
with the subject "Deadlock in OpenMPI 1.8.3 and PETSc 3.4.5"

**Comment by mellanox-github** [comment]
* Coverity found 1288 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_325/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_325/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_325/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/325/
Test PASSed.

**Comment by jsquyres** [comment]
There has been more (off-list) discussion since this discussion.  This solution is based on conversations with Fab and Jed as of this week.

Jeb told Fab that OMPI is still broken because its attribute callbacks hold a global lock, and therefore prevent *any* other attribute actions (even reading attribute values on another communicator, which is "safe" in our implementation).  Jeb is not doing what we consider to be "unsafe" (e.g., reading or deleting attributes on the current communicator while in the delete callback of an attribute on the same communicator).

So it really just boils down to a single, could-be-simple case: make the global attributes lock be re-entrant so that the thread that currently holds it can "re-lock" it and allow "safe (enough)" actions, such as reading attribute values from other communicators.

**Comment by bosilca** [comment]
Having more off-list discussions is no caution for better solutions.
Obviously, based on previous user level email discussions, nobody would
have been interested on this subject on the devel mailing list, so off-list
discussion were clearly the best practice.

In our trunk code today the global mutex is released before calling any
callbacks, be it for delete or the copy operation (attribute.c line 251 and
292). Thus, I see no opportunity for the case you describe in your email to
happen. Do you have a concrete example?

  George.

**Comment by jsquyres** [comment]
These conversations happened organically -- the Petsc guys mailed me+Fab directly because of our prior MPI Forum attribute proposal.  Fab spoke with them a bunch and distilled their requirements down to what was really needed.  Fab spoke to me about this at a dinner this week, and Nathan was there.  He quickly hacked up the addition of recursive locks because it was easy, and threw the PR to me.  I'm on planes-trains-automobiles today and haven't had a chance to look into the code yet.

**Comment by jsquyres** [comment]
I finally got a chance to look at the code this morning.

I confirm what George says -- OMPI should not be deadlocking like this due to the changes that went in a while ago.  Indeed, those changes should have been included in v1.8.4, so there's even a released version which should include the fixes.

As such, either the PETSc guys are wrong, Fab is wrong, or something was lost in translation in the discussions over the past week or so.  I've emailed them back asking for clarification.

I just added ibm/communicator/attr-attr-callbacks to test for deadlocks in this kind of scenario.

@hjelmn: It looks like we don't need the recursive locks in attributes.  Do you still want them for MPI_T scenarios?  You mentioned that it could make some issues easier over there.

**Comment by bosilca** [comment]
@jsquyres thanks for checking this out.

**Comment by hjelmn** [comment]
@jsquyres The discussion started with an apparent problem with the big attribute lock (good to see that is not really an issue-- I will delete that commit). The large discussion was about callbacks from the tools interface. That includes possible support for MPI_T event callbacks and PMPI2 callbacks. Recursive locks may or may not be useful for those cases. In any case having a class available does no harm.

**Comment by jsquyres** [comment]
I'm marking this as "Future" milestone -- it could well be useful for MPI_T, but isn't really useful until then.  I'd prefer not to add the class until we have an actual consumer of it in the tree.

**Comment by jsquyres** [comment]
@hjelmn Just to be sure: you are still confident that recursive locks will be useful for more MPI_T scenarios (that we don't support well/at all), right?

**Comment by hppritcha** [comment]
Can one of the admins verify this patch?

**Comment by hjelmn** [comment]
I do think this will be useful for MPI T events if we get that into the standard. I will be working on that off and on over the next couple of months.

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_cle5.2up02/141/
Test PASSed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/ompi_master_pr_distcheck/47/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 812 errors for all

* Coverity found 5 errors for oshmem

* Coverity found 2 errors for fca
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//627/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/627/

**Comment by jsquyres** [comment]
@hjelmn Advises that we close this since there's no current use case for it.  But it may be useful if MPI_T ever defines callbacks / events.  So we'll close the PR for now and either re-create or re-open this PR if needed.

**Pull request closed without merging**
