### PR TITLE
opal/asm: clean up no longer supported architectures

### PR DESCRIPTION
**Pull request by hjelmn**
We no longer officially support MIPS, IA64, or ARM (prior to v6). This commit
updates the configury to check for sync builtins on these
architectures and removes the MIPS and IA64 assembly from
opal/include/opal/sys.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
I am in the process of modifying the assembly code and I do not want to have to bother with these unsupported architectures.

**Comment by hjelmn** [comment]
@jsquyres, @hppritcha Any objections?

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a8fc318f2280d22be6536459e11c6103

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/02b67039bcdd9f25a7af0f22f55b9aa4

**Comment by hjelmn** [comment]
Opps. Forgot to modify the Makefile.am.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/da33c472f54778239fc243e6549d627b

**Comment by hjelmn** [comment]
@rhc54 Just to make sure. Intel doesn't really care about IA64 anymore, correct? It isn't in the officially supported list so I assume not.

**Comment by rhc54** [comment]
not that I am aware of...

**Pull request merged**
