### PR TITLE
v4.0.x: Backport alltoall in place fixes

### PR DESCRIPTION
**Pull request by awlauria**
This went back to v4.1 a while ago here: https://github.com/open-mpi/ompi/pull/9672

Refs: #9329 and #9501

### CODE REVIEW

**Comment by jsquyres** [comment]
FWIW: do you want these fixes in v4.0.x?  Or is "4.1.x has the fixes for these bugs" a suitable response?

**Comment by awlauria** [comment]
So doing some internal testing - it seems that only bringing over [c7b7619](https://github.com/open-mpi/ompi/pull/10509/commits/c7b76197b8b56939db70a579760902dde93abd45) will fix the segv in the reported issue. The remaining commits are performance improvements, and a new algorithm, and patches to said new algorithm.

So whether the whole series should come over, or just the single patch (c7b7619) - I'll leave the call up to @gpaulsen and @hppritcha.

**Comment by hppritcha** [comment]
Are we wanting this for spectrum MPI?

**Review by gpaulsen — APPROVED** [review]
Looks great!  I'd prefer to take the whole PR.

**Review by hppritcha — APPROVED** [review]

**Pull request merged**
