### PR TITLE
opal/asm: silence xlc warning about typeof usage

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@cs.unm.edu>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3f5da063ed91dc374a76f61c90cea2b6

**Comment by jjhursey** [comment]
IBM Ci had an issue over the weekend. Retrying. bot:ibm:retest

**Comment by hjelmn** [comment]
@jjhursey Thanks. Looks good now.

**Review by jjhursey — COMMENTED** [review]
Looking at the build log the warning is still present, and this section of code wasn't activated for some reason.

The `-qkeyword` is defined for the [AIX version of XL](https://www.ibm.com/support/knowledgecenter/SSGH3R_16.1.0/com.ibm.xlcpp161.aix.doc/compiler_ref/opt_keyword.html), but not the [Power version](https://www.ibm.com/support/knowledgecenter/SSXVZZ_16.1.1/com.ibm.xlcpp1611.lelinux.doc/compiler_ref/rucmpopt.html). We'll have to look at what we need ot do diferently.

```
*** C compiler and preprocessor
checking for gcc... (cached) xlc_r
checking whether we are using the GNU C compiler... (cached) yes
checking whether xlc_r accepts -g... (cached) yes
checking for xlc_r option to accept ISO C89... (cached) none needed
checking whether xlc_r understands -c and -o together... (cached) yes
checking if xlc_r requires a flag for C11... yes
configure: checking if xlc_r supports C11 with a flag
checking if xlc_r -std=gnu11 supports C11 _Thread_local... yes
checking if xlc_r -std=gnu11 supports C11 atomic variables... no
checking if xlc_r -std=gnu11 supports C11 _Atomic keyword... no
checking if xlc_r -std=gnu11 supports C11 _Generic keyword... yes
checking if xlc_r -std=gnu11 supports C11 _Static_assert... yes
checking if xlc_r -std=gnu11 supports C11 atomic_fetch_xor_explicit... no
checking if xlc_r -std=c11 supports C11 _Thread_local... yes
checking if xlc_r -std=c11 supports C11 atomic variables... no
checking if xlc_r -std=c11 supports C11 _Atomic keyword... no
checking if xlc_r -std=c11 supports C11 _Generic keyword... yes
checking if xlc_r -std=c11 supports C11 _Static_assert... yes
checking if xlc_r -std=c11 supports C11 atomic_fetch_xor_explicit... no
checking if xlc_r -c11 supports C11 _Thread_local... no
checking if xlc_r -c11 supports C11 atomic variables... no
checking if xlc_r -c11 supports C11 _Atomic keyword... no
checking if xlc_r -c11 supports C11 _Generic keyword... no
checking if xlc_r -c11 supports C11 _Static_assert... no
checking if xlc_r -c11 supports C11 atomic_fetch_xor_explicit... no
checking for xlc_r option to add a directory only to the search path for the quote form of include... -iquote
checking for xlc_r option to accept ISO C99... none needed
checking if xlc_r  supports C11 _Thread_local... yes
checking if xlc_r  supports C11 atomic variables... no
checking if xlc_r  supports C11 _Atomic keyword... no
checking if xlc_r  supports C11 _Generic keyword... yes
checking if xlc_r  supports C11 _Static_assert... yes
checking if xlc_r  supports C11 atomic_fetch_xor_explicit... no
checking if xlc_r  supports __thread... yes
checking if xlc_r  supports C11 _Thread_local... yes
checking for the C compiler vendor... gnu
checking for ANSI C header files... (cached) yes
checking if xlc_r supports -Wno-long-double... no
configure: WARNING:  -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration  has been added to CFLAGS (--enable-picky)
checking if xlc_r supports -finline-functions... yes
checking if xlc_r supports -fno-strict-aliasing... yes
configure: WARNING:  -fno-strict-aliasing has been added to CFLAGS
checking if xlc_r supports __builtin_expect... yes
checking if xlc_r supports __builtin_prefetch... yes
checking if xlc_r supports __builtin_clz... yes
checking for C optimization flags... -O3 -DNDEBUG -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing
checking for Interix environment... no
```

**Comment by awlauria** [comment]
@jjhursey @hjelmn it looks like it may be because the compiler got labeled as 'gnu', and not 'ibm'. I fixed that in this PR:
https://github.com/open-mpi/ompi/pull/8444/commits/062a72b33912cabb2b6c0e803d82c0844a07258e

**Comment by hjelmn** [comment]
@awlauria Can you confirm the warning goes away with the PR?

**Comment by awlauria** [comment]
I verified that this fix worked for the opal/powerpc atomics:
https://github.com/open-mpi/ompi/pull/8444/commits/09dfb127cf137765940718622af53862382e128f

Since @jjhursey mentioned `-qkeyword` isn't available on Power machines, maybe we should go for that approach if xl is used. I can add that to #8444 or you can here, either works for me.

**Comment by hjelmn** [comment]
@awlauria Unfortunate that they removed that option yet kept the error. Maybe we should updating the ```--std``` flag selection to select c99 (or c11) with extensions? That should also fix it since this is complaining about extensions. I believe for gcc ```--std=gnu11``` is default now so there is a president to use the extensions. I will leave it up to you on how we proceed.

**Comment by awlauria** [comment]
@hjelmn this should do it:

https://github.com/open-mpi/ompi/pull/8444/commits/2487ed91f0d180f2cbcd2e7851508489980ff126

**Comment by awlauria** [comment]
If adding --std=c99 fixes it, I'd be for that as well. I can test it on our power nodes.

**Comment by hjelmn** [comment]
@awlauria Actually this: ```-qlanglvl=extc1x```. And for non-C11 versions: ```-qlanglvl=extc99``` should do it. Can you check if they do?

**Comment by awlauria** [comment]
@hjelmn I can't seem to reproduce this warning on master anymore, so I can't verify either way.

Not sure what commit did it.

**Comment by gpaulsen** [comment]
@hjelmn, once https://github.com/open-mpi/ompi/pull/8528 goes in, can we just close this?

**Comment by hjelmn** [comment]
@gpaulsen Ideally the LL/SC atomics will still be used even when using C11. I think @awlauria has already fixed this issue by using ```__typeof__``` instead of ```typeof``` with xlc so this can be closed.

**Comment by gpaulsen** [comment]
retest

**Comment by awlauria** [comment]
I believe this has long been fixed, but if not this definitely did it:
https://github.com/open-mpi/ompi/commit/7590b31d52c8e1b61c475e19449eaf2190107ec2

**Pull request closed without merging**
