### PR TITLE
Add Chelsio T6 adapter device parameters.

### PR DESCRIPTION
**Pull request by bharatpotnuri**
The following commit adds device parameters of Chelsio T6 adapter.

Signed-off-by: Potnuri Bharat Teja <bharat@chelsio.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
👍

**Comment by bharatpotnuri** [comment]
Hi Jeff,
This commit isn't yet added to the 2.0.x branch and hence isn't available in the recent stable release rpm/tar. Could you please push/queue this for next dot release.
Thanks.

**Comment by jsquyres** [comment]
@bharatpotnuri Did you make PR's for v2.0.x and v2.x?

**Comment by bharatpotnuri** [comment]
@jsquyres there is a PR for 2.x and commit is merged with 2.x repo. Sorry I did not raise it for 2.0.x.
I am raising a new PR for 2.0.x.

**Comment by bharatpotnuri** [comment]
@jsquyres Raised PR #3014. Hoping it can be pulled to v2.0.x.
Thanks.

**Comment by jsquyres** [comment]
Sure, it's no problem.  But note that we don't have a schedule for v2.0.3 -- that will likely be released whenever we accumulate enough bug fixes.  The main focus is on v2.1.0 at the moment.

**Comment by bharatpotnuri** [comment]
ok Fine. I realised this too late :)

**Pull request merged**
