### PR TITLE
ess/singleton: do not pass "--mca state_novm_select 1" to orted

### PR DESCRIPTION
**Pull request by ggouaillardet**
and fix a hang when MPI_Comm_spawn is invoked from a singleton

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 can you please review this ?
currently, the ```dynamic/spawn``` test from the ```ibm``` test suite hangs when invoked as a singleton.
i ran this under the debugger to compare singleton vs mpirun, and i finally found that removing ```--mca state_novm_select 1``` did the trick.

**Comment by rhc54** [comment]
Did you test that with multiple nodes - i.e., where comm_spawn forces the launch of new daemons? I believe that was the use-case which required the novm state machine.

**Comment by ggouaillardet** [comment]
i did not test that case, will do !

**Comment by rhc54** [comment]
Thanks - I think the question here is: is the problem that the novm state machine is hanging? Or that singletons should instead kickoff the full VM?

**Comment by rhc54** [comment]
I've tested singletons now that the --novm option has been fixed and they work just fine, so I'm closing this PR.

**Pull request closed without merging**
