### PR TITLE
Allow to override build user and host

### PR DESCRIPTION
**Pull request by bmwiedemann**
Allow to override build user and host, using the standard $USER and $HOSTNAME environment variables to make reproducible builds possible.
See https://reproducible-builds.org/ for why this is good.

This helps improve issue #3759

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
Thanks for bringing this to our attention again; I admit it kinda fell off our radar.  😦 

Are you looking for both this PR *and* #3779 to be merged?  (it looks like that one kinda fell off the radar, too...)

Also, per the discussion in #3759, are you interested in an output line in `ompi_info`, something like "Reproducible build: yes|no"?  (`ompi_info` is the tool users use to see information about the Open MPI installation)

**Comment by bmwiedemann** [comment]
I'd say, this change perfectly complements #3779

We could use `$SOURCE_DATE_EPOCH` as an indicator for "Reproducible build: yes"
but I'd prefer if we could keep the code simple and use this patch as is
and to compensate, in our .spec file we do something like
```bash
export HOSTNAME=reproducible-SUSE-rpm-build
```
which should show up in ompi_info as well

**Comment by jsquyres** [comment]
I'm good with this PR.  Mind if I add a commit to it with a short README blurb about setting`$USER` and/or `$HOSTNAME` and citing Reproducible Builds?  (what's the best URL to cite for RB's, anyway -- https://reproducible-builds.org/ ?)

**Comment by bmwiedemann** [comment]
oops, missed the other comment. Yes, please add blurb with that URL.

**Comment by jsquyres** [comment]
@bmwiedemann I rebased to the current HEAD (since this commit was super old) and added a 3rd commit with a README blurb.  Look ok?

@ggouaillardet You might want to expand on this README blurb in #3779...?

**Comment by bmwiedemann** [comment]
LGTM

**Comment by bmwiedemann** [comment]
Can you merge this PR, please?

**Comment by jsquyres** [comment]
Thanks for your patience -- merged!

**Pull request merged**
