### PR TITLE
Add some protection against PMIx v4

### LINKED ISSUE #8089: Undefined symbols when building against external PMIX 3.1.5
I am trying to build current `master` (`g0bcef04`) against a site-provided PMIX 3.1.5. `configure` complained about the old version:

```
*** Configuring PRRTE
checking if PMIx version is 4.0.0 or greater... no
configure: WARNING: OMPI's internal runtime environment "PRRTE" does not support
configure: WARNING: PMIx versions less than v4.x as they lack adequate tool
configure: WARNING: support. You can, if desired, build OMPI against an earlier
configure: WARNING: version of PMIx for strictly direct-launch purposes - e.g., using)
configure: WARNING: Slurm's srun to launch the job - by configuring with the
configure: WARNING: --disable-internal-rte option.
configure: error: Cannot continue
```

so I ran configure with `--disable-internal-rte`, which succeeds but then the build fails:

```
  CC       runtime/ompi_rte.lo
In file included from ../../opal/util/proc.h:25:0,
                 from ../../ompi/runtime/ompi_rte.c:46:
../../ompi/runtime/ompi_rte.c: In function 'ompi_rte_init':
../../ompi/runtime/ompi_rte.c:673:40: error: 'PMIX_APP_ARGV' undeclared (first use in this function); did you mean 'PMIX_APP_FREE'?
     OPAL_MODEX_RECV_VALUE_OPTIONAL(rc, PMIX_APP_ARGV,
                                        ^
../../opal/mca/pmix/pmix-internal.h:293:35: note: in definition of macro 'OPAL_MODEX_RECV_VALUE_OPTIONAL'
         (r) = PMIx_Get(&(_proc), (s), &(_info), 1, &(_kv));                             \
                                   ^
../../ompi/runtime/ompi_rte.c:673:40: note: each undeclared identifier is reported only once for each function it appears in
     OPAL_MODEX_RECV_VALUE_OPTIONAL(rc, PMIX_APP_ARGV,
                                        ^
../../opal/mca/pmix/pmix-internal.h:293:35: note: in definition of macro 'OPAL_MODEX_RECV_VALUE_OPTIONAL'
         (r) = PMIx_Get(&(_proc), (s), &(_info), 1, &(_kv));                             \
                                   ^
../../ompi/runtime/ompi_rte.c:686:40: error: 'PMIX_REINCARNATION' undeclared (first use in this function); did you mean 'PMIX_INTERNAL'?
     OPAL_MODEX_RECV_VALUE_OPTIONAL(rc, PMIX_REINCARNATION,
                                        ^
../../opal/mca/pmix/pmix-internal.h:293:35: note: in definition of macro 'OPAL_MODEX_RECV_VALUE_OPTIONAL'
         (r) = PMIx_Get(&(_proc), (s), &(_info), 1, &(_kv));                             \
                                   ^
make[2]: *** [runtime/ompi_rte.lo] Error 1
```

Here is the output of `pmix_info`, in case that matters:

```
$ pmix_info --version
                 Package: PMIx root@tauruslogin6.taurus.hrsk.tu-dresden.de
                          Distribution
                    PMIX: 3.1.5
      PMIX repo revision: gitedebb24
       PMIX release date: Apr 27, 2020
                  Prefix: /usr
 Configured architecture: pmix.arch
          Configure host: tauruslogin6.taurus.hrsk.tu-dresden.de
           Configured by: root
           Configured on: 2020-04-27T11:24:26
          Configure host: tauruslogin6.taurus.hrsk.tu-dresden.de
  Configure command line: '--build=x86_64-redhat-linux-gnu'
                          '--host=x86_64-redhat-linux-gnu'
                          '--program-prefix=' '--disable-dependency-tracking'
                          '--prefix=/usr' '--exec-prefix=/usr'
                          '--bindir=/usr/bin' '--sbindir=/usr/sbin'
                          '--sysconfdir=/etc' '--datadir=/usr/share'
                          '--includedir=/usr/include' '--libdir=/usr/lib64'
                          '--libexecdir=/usr/libexec' '--localstatedir=/var'
                          '--sharedstatedir=/var/lib'
                          '--mandir=/usr/share/man'
                          '--infodir=/usr/share/info'
                Built by: root
                Built on: 2020-04-27T11:25:58
              Built host: tauruslogin6.taurus.hrsk.tu-dresden.de
              C compiler: gcc
     C compiler absolute: /usr/bin/gcc
  C compiler family name: GNU
      C compiler version: 4.8.5
  Internal debug support: no
              dl support: yes
     Symbol vis. support: yes
              MCA bfrops: v3 (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA bfrops: v12 (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA bfrops: v20 (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA bfrops: v21 (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA gds: ds12 (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA gds: hash (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA gds: ds21 (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA pdl: pdlopen (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA pif: linux_ipv6 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
                 MCA pif: posix_ipv4 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
        MCA pinstalldirs: env (MCA v2.1.0, API v1.0.0, Component v3.1.5)
        MCA pinstalldirs: config (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA plog: syslog (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA plog: stdfd (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA plog: default (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA pnet: test (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA pnet: tcp (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA preg: native (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA psec: none (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA psec: native (MCA v2.1.0, API v1.0.0, Component v3.1.5)
             MCA psensor: file (MCA v2.1.0, API v1.0.0, Component v3.1.5)
             MCA psensor: heartbeat (MCA v2.1.0, API v1.0.0, Component
                          v3.1.5)
              MCA pshmem: mmap (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA ptl: tcp (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA ptl: usock (MCA v2.1.0, API v1.0.0, Component v3.1.5)
```

Is this expected and is there another way to build Open MPI on such a system?

### PR DESCRIPTION
**Pull request by rhc54**
Ensure we can build against PMIx v3.1.5

Fixes #8089

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Closes https://github.com/open-mpi/ompi/issues/8074

**Comment by devreal** [comment]
@rhc54 Thanks for working on this! I can configure Open MPI with `--disable-internal-rte` and successfully build and install. However, if I run a simple test application using `srun` I get an error: 

```
$ srun -n 2 -N 1 hello
--------------------------------------------------------------------------
It looks like MPI runtime init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during RTE init; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  node rank
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI runtime init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during RTE init; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  node rank
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and MPI will try to terminate your MPI job as well)
[taurusi4207.taurus.hrsk.tu-dresden.de:30226] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and MPI will try to terminate your MPI job as well)
[taurusi4207.taurus.hrsk.tu-dresden.de:30225] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: taurusi4207: tasks 0-1: Exited with exit code 14
```

Do I need to set any environment variables for OMPI to work in this setting?

**Comment by rhc54** [comment]
You shouldn't need to set anything - I suspect that the Slurm PMIx support isn't quite up to the PMIx Standard and is missing that info. I'll update OMPI to protect it.

**Comment by rhc54** [comment]
@devreal Give it another try when you can.

**Comment by devreal** [comment]
@rhc54 I'm still seeing an error but now it's about the job size:

```
--------------------------------------------------------------------------
It looks like MPI runtime init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during RTE init; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  job size
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
Are you sure Slurm is using PMIx? Job size is pretty fundamental and should be present. Check that you specified PMIx on your srun cmd line or that the system is defaulting to PMIx.

**Comment by devreal** [comment]
I guess I have to provide `--mpi=pmix` to `srun`. That changes the error to `local size`:

```
$ srun --mpi=pmix -n 2 -N 1 hello
--------------------------------------------------------------------------
It looks like MPI runtime init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during RTE init; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  local size
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
Sigh...okay, please try it again.

**Review by devreal — APPROVED** [review]

**Pull request merged**
