### PR TITLE
v5.0.x: Update OpenPMIx and PRRTE submodule pointers.

### PR DESCRIPTION
**Pull request by awlauria**
Updated to point to PRRTE v2.1 branch, and PMIx v4.2 branch.

PRRTE updates:

a9d335b587 - Fix --mca processing.
16d99f20ce - cmd_line.c: Stop parsing at the executable.
17928a4856 - Update TM configure logic to include tm library location
433d6a2bf3 - Ensure tool procs are not counted against resource limits
4a760dce6a - Tag the TM launcher as a "launcher"
111ba00828 - Update VERSION
3e314795fc - Fix typo
f991ce0e0c - Fix the command line parser
d161cb0e57 - Fix the param and show-version options of prte_info
671276729b - Enable per-job specification of the exec agent
5384ce33e8 - Use correct data source when loading info
cef9a8def2 - Address missed comments to correct a couple of options
9824dc4f13 - Address review comments
e929f575ff - Ensure the cmd lien parser exits when it hits the application name
636f2fe78e - Silence warning
2677ec9f31 - Silence multiple output of deprecation warnings
8e9499de6b - Split out setting of default placement policies
ac07637230 - Redesign the command line system to provide isolation
44c016c478 - Update NEWS and VERSION
53a80729e6 - Cleanup a bit in prep for PMIx sync to v5 std
d00d9b3508 - Remove HWLOC version block
0c542cfb2a - Add missing examples to tarball
92cfdad6d0 - Ensure an error gets reported when rankfile fails
2e55c937d3 - Use correct data source when loading info
417d6f71b2 - Update NEWS to track commits
798ac0b85b - Update the hwloc version checking
974828b87a - Protect against HWLOC issues
1cfcc7b8ce - Always build the PBS scheduler support
0a76a82cec - Cleanup handling of allocated node names

PMIx updates:

dc1fa822 - Include typedef for GCC builtin atomics
1e5f9e71 - Remove unnecessary sys/sysctl.h includes
d69db444 - Clean up unused return value warnings
9550258f - pmix_iof.c: malloc buffer before memcpy().
b0ebd954 - Minor port-specific cleanup: convert pmix_value_xfer to PMIx_Value_xfer
11ccb409 - Sync the library to the Standard
a581783b - Initialize the mutex when constructing an object
4b7d62c3 - Begin stripping configure of unnecessary checks
986557eb - Port-specific fixes to cherry-pick of atomics
617b3353 - Remove unneeded atomics code
988ed67f - Minor cleanups to cherry-picks
d9668cf7 - Update NEWS and VERSION
cbb7d313 - test: Fix dereference issue in environ test
cd4fb277 - Try modified Mellanox Dockerfile to get it to build
82c8ee89 - Fix typo - should be not-equal
4042b26a - Remove block of hwloc 2.5 - 2.7
29294282 - Be defensive against string literals in env
ddb8c547 - Update NEWS
8b0f12d9 - Update the hwloc version checking
5c253490 - Protect against HWLOC issues

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by awlauria** [comment]
Fixes issue https://github.com/open-mpi/ompi/issues/10044 in v5.0.x.

**Review by bwbarrett — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/296a2a0dad9d983596d8524c31ee071f

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/91d2059410ce238e4378c5e89c0389b3

**Comment by awlauria** [comment]
I didn't port https://github.com/openpmix/prrte/commit/24eb3bfbe1e8fa300970768f2484bbe6f50783fc to the v2.1 branch. will need to update.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6a8b61abdf75466f50addc08bc511bd9

**Comment by awlauria** [comment]
--mca fix: https://github.com/openpmix/prrte/pull/1230

**Comment by awlauria** [comment]
Picked up the --mca fix.

**Comment by awlauria** [comment]
looks like a real failure on a rhel7 box:

```
--> running examples
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    version
from the file:
    help-schizo-ompi.txt
But I couldn't find that topic in the file.  Sorry!
--------------------------------------------------------------------------
--> mpirun version: 
--> Running example: hello_c
--------------------------------------------------------------------------
An unrecognized option was included on the prterun command line:

  Option: --get-stack-traces

Please use the "prterun --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
Example failed: 213
Command was: timeout -s SIGSEGV 4m mpirun --get-stack-traces --timeout 180 --hostfile /home/ec2-user/workspace/open-mpi.build.platforms/Platform/rhel7/hostfile -np 2  ./examples/hello_c
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Will try and reproduce.

**Comment by jsquyres** [comment]
Looks like a few errors, actually:

* Is `--get-stack-traces` no longer supported (is that a regression)?
* Where's `help-schizo-ompi.txt`?
* It _looks_ like there are actually *two* show_help errors.  There should probably only be one.

**Comment by awlauria** [comment]
It seems to be more command line parsing issues. Not sure if this is a regression, or a new bug exposure.

**Comment by awlauria** [comment]
It was a bug introduced in: https://github.com/openpmix/prrte/pull/1222

Fixed in: https://github.com/openpmix/prrte/pull/1233

**Pull request merged**
