### PR TITLE
PML/UCX/YALLA: Fix the message release call.

### PR DESCRIPTION
**Pull request by alinask**
Set message to MPI_MESSAGE_NULL.

Signed-off-by: Alina Sklarevich <alinas@mellanox.com>
(cherry picked from commit eec310c99c8014a797a04376105792eb6c22a1bb)

### CODE REVIEW

**Comment by alinask** [comment]
@hppritcha Can you please review?

**Comment by alinask** [comment]
@hppritcha Can you please merge this PR?

**Comment by jsquyres** [comment]
@alinask Can you get someone from Mellanox to review this first?  Thanks!

**Comment by alinask** [comment]
@yosefe @jladd-mlnx Can you please review?

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
