### PR TITLE
Create a Github issue template

### PR DESCRIPTION
**Pull request by jsquyres**
It seems like we keep getting bug reports where the first questions we have to ask are always the same (E.g., "what version of Open MPI are you using?").

Per https://help.github.com/articles/creating-an-issue-template-for-your-repository/, perhaps we should have an github issue template for Open MPI.

If you're a community developer and want to make a free-form issue, it's easy enough to select-all/delete and write whatever you want.  But having this template may be helpful for newbies -- it may cause a little introspection during the bug reporting process, which is usually a Good Thing.

I tentatively put together a few questions and format.  I'm not tied to this at all -- I'm very open to suggestions and comments.

[skip ci]
bot:notest

### CODE REVIEW

**Comment by jsquyres** [comment]
@rhc54 Done -- added some version examples.

@hppritcha @jjhursey I just force-pushed a new commit that included `[skip ci]`, but the LANL CIs and at least one IBM CI fired again.

**Comment by jjhursey** [comment]
@jsquyres You need to put that in your PR description, not the commit message or a comment. I think that's the problem.

**Comment by jjhursey** [comment]
👍  This looks good to me. Thanks!

**Comment by jsquyres** [comment]
@jjhursey Huh.  I could have sworn it was the opposite (it had to be in the *commit message*, not the PR description).  Ok.

**Comment by hppritcha** [comment]
Looks good.

**Comment by jjhursey** [comment]
I don't want the template to get too long. But what do you think about adding a note about formatting code blocks in markdown with a link and/or example?

Something like:

**Note**: If you have shell output (or a code block) please use the [Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -np 2 ./hello_world
```

**Comment by bwbarrett** [comment]
@jsquyres , looking at the OMPI Jenkins, it appears to behave as Josh described as well...

**Comment by jsquyres** [comment]
@jjhursey Good point.  Done.

Ah -- I see the issue now.  If you don't include [skip ci] in the commit message, then Travis fires.  Hence, we really need [skip ci] in *both* the commit message (for Travis) *and* the description (for Jenkins).

**Comment by bwbarrett** [comment]
@jsquyres Or I get off my butt and finish replicated the travis tests on Jenkins :)

**Comment by rhc54** [comment]
I was told there is also a ```bot:notest``` that you have to include to avoid the CI tests. Did that change? IIRC, ```skip ci``` handled Travis, and the other handled Jenkins.

**Comment by hppritcha** [comment]
for the AWS jenkins the projects look for either [skip ci] [ci skip] or bot:notest.  The travis only looks at the first two.

**Comment by hppritcha** [comment]
Since I'm shamelessly copying contributing.md from rails I looked at their issue template.  Its short.
I tried ours and now think its too long.  

https://github.com/rails/rails/issues/new

**Comment by rhc54** [comment]
I think we could make it look shorter by condensing some of the requests - e.g., just ask for expected/observed behavior and drop the detailed description of the problem and 1-2 sentence description as those are redundant.

**Comment by jsquyres** [comment]
@rhc54 Done.  Look ok?

**Comment by rhc54** [comment]
Looks good - thx!

**Pull request merged**
