### PR TITLE
If AMODE not set in MPI_File_open, not all of ompio_fh is set, fixes …

### PR DESCRIPTION
**Pull request by hpcraink**
…#9083.

Signed-off-by: Rainer Keller <rainer.keller@hs-esslingen.de>

### CODE REVIEW

**Comment by jsquyres** [comment]
Super pedantic comment: can you put `{}` around the block?  We even want `{}` even around 1-line blocks.

Thanks!

(Hi Rainer!  👋 )

**Review by edgargabriel — APPROVED** [review]

**Comment by edgargabriel** [comment]
@hpcraink thank you for the fix! Short question, do you still have permissions to commit to the repo?

**Comment by jsquyres** [comment]
@hpcraink Sorry -- can you add a signed-off-by line on the message on your second git commit?  We have to have that line on all commits.  Thanks!

**Comment by hpcraink** [comment]
> @hpcraink Sorry -- can you add a signed-off-by line on the message on your second git commit? We have to have that line on all commits. Thanks!
Should I git commit --amend with the signof?

**Comment by hpcraink** [comment]
> > @hpcraink Sorry -- can you add a signed-off-by line on the message on your second git commit? We have to have that line on all commits. Thanks!
> > Should I git commit --amend with the signof?

Well, maybe this helps for future reference: just did a `git commit --amend --signoff --no-edit` and then a `git push --force` (rewriting the tip of my master-branch), github picked it up the previously failing GitHub Action CI now ran successfully.

**Comment by hpcraink** [comment]
> @hpcraink thank you for the fix! Short question, do you still have permissions to commit to the repo?

Hey Edgar, thx for the review. I guess I don't have permission to commit. Would You please on my behalf? Thank You!

**Comment by edgargabriel** [comment]
@jsquyres I think we did not bring this fix over to the various branches (v4.0, v4.1, v5.0), shall I set up the PRs?

**Comment by jsquyres** [comment]
@edgargabriel Yes, please.  Thanks!

**Pull request merged**
