### PR TITLE
Patches for portable open-mpi packages from PathScale

### PR DESCRIPTION
**Pull request by esil**
04e30d4 commit adds support for auto-detecting install dir for open-mpi. If path specified at build time does not exist then openmpi uses path relative to executable.

04e30d4 adds support for ${} variables in paths to compiler in config files. With that patch we can set path to compiler relative to open-mpi install dir.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-master-pr/667/

**Comment by jsquyres** [comment]
@esil It feels like this type of functionality should really be in a component -- not added in the base.  I.e., you added some very specific functionality into the generic base, rather than creating a new plugin for that specific type of functionality.

Can you move this functionality off into a new component?

**Comment by jsquyres** [comment]
@esil Per my above comment, do you think you'll be moving this functionality into its own component?

**Comment by jsquyres** [comment]
@esil I haven't heard back from you.  Closing this PR; feel free to re-open it if you can update the code per prior suggestions.  Thanks.

**Comment by cbergstrom** [comment]
We are not 100% familiar with OpenMPI build infrastructure. Can you reference an example of something doing something similar to what you proposed? Did the patch cause build failures? I feel pretty strongly that this is a core feature which is missing. My vote probably doesn't mean much, if anything though.

**Comment by jsquyres** [comment]
I'm just suggesting to put this in a (probably new) installdirs component (vs. the installdirs base).

**Pull request closed without merging**
