### PR TITLE
v4.1.x: reproducible builds + portability fix

### PR DESCRIPTION
**Pull request by jsquyres**
Cherry pick of #8136 and #8152 from master regarding reproducible builds.  Thanks to @bmwiedemann for bringing this back to our attention.

Also bring in a MacOS/`readlink` portability fix.

### CODE REVIEW

**Review by bmwiedemann — CHANGES_REQUESTED** [review]
needs one more patch:
```diff
orte/tools/orte-info/Makefile.am
-            -DOMPI_BUILD_DATE="\"`date`\"" \
+            -DOMPI_BUILD_DATE="\"`$(top_srcdir)/config/getdate.sh`\"" \
```

**Comment by jsquyres** [comment]
This PR will also need the MacOS portability fixes from #8152.

**Comment by jsquyres** [comment]
bot:ompi:retest

**Review by rhc54 — APPROVED** [review]

**Comment by jsquyres** [comment]
@bmwiedemann If the v4.0.x and v4.1.x PRs now test properly for you, I'll merge them.

**Review by bmwiedemann — APPROVED** [review]

**Comment by bmwiedemann** [comment]
I successfully tested the 4.0.x one, and the code 4.1.x code looks similar enough for me to have a good confidence in it.

**Pull request merged**
