### PR TITLE
coll/base/alltoallv: skip send/recv 0-count messages

### PR DESCRIPTION
**Pull request by wenduwan**
Pairwise alltoallv uses ompi_coll_base_sendrecv which sends and receives 0-count messages. This caused a hang after #12198, which skips sending 0-byte messages:
- Rank 0 skips sending 0-byte message to Rank 1
- Rank 1 still waits to receive 0-count message from Rank 0

This change replaces ompi_coll_base_sendrecv with PML irecv and send, and skips on 0-count messages.

We didn't trigger this path in the previous PR because we tested on a different communicator size that used basic linear algorithm.

### CODE REVIEW

**Comment by bosilca** [comment]
I don't understand the premise of this PR. This algorithm has always used the `ompi_coll_base_sendrecv` and as such it was always sending the 0-bytes messages. How would this suddenly create a hand because of a change in another alltoall algorithm ?

**Comment by wenduwan** [comment]
@bosilca We did change this algorithm in https://github.com/open-mpi/ompi/pull/12198 as well.

We added a short-circuit here https://github.com/open-mpi/ompi/blob/50d56bd011a1c5622894fbcec4a8c0b80da39326/ompi/mca/coll/base/coll_base_alltoallv.c#L221-L224

Today I realize pairwise algorithm is using `ompi_coll_base_sendrecv` and sending 0-count messages.

In the other (i)alltoallv we are skipping 0-count send/recv.

**Comment by bosilca** [comment]
The PR description talks about a hang, I was just trying to understand where the hand is coming from.

**Comment by bosilca** [comment]
Another, potentially simpler solution is to replace `ompi_coll_base_sendrecv` with `ompi_coll_base_sendrecv_actual`, a function that avoids sending 0-byte messages.

**Comment by lrbison** [comment]
I'm with George here, I don't understand how this fixes a hang.  It seems like you are describing a situation in which the sender and the receiver have different logic for posting or not posting the 0-sized/0-count message, but currently the code path goes into sendrecv, which I would assume has similar logic for sender and receiver.

Looking a little closer at both `ompi_coll_base_sendrecv()` and `..._actual()`, the documentation claims they both skip 0-sized messages (sendrecv is a quick wrapper around actual, with just a short-circuit for sending to self).  However looking at the implementation of ompi_coll_base_sendrecv_actual, I see that it does seem to be posting messages no matter the size.

https://github.com/open-mpi/ompi/blob/d231daf236110057d2bd3fa35b27e43b3ecccbc9/ompi/mca/coll/base/coll_base_util.c#L45-L53

Despite what the header documentation claims:
https://github.com/open-mpi/ompi/blob/d231daf236110057d2bd3fa35b27e43b3ecccbc9/ompi/mca/coll/base/coll_base_util.h#L127-L134

However based on the discussion in https://github.com/open-mpi/ompi/pull/12198#issuecomment-1870035887 I think the claim these are "not appropriate" is false.  A rank is allowed to pass through an alltoallv collective (or any *v collective) immediately with no barrier if the rank has no communication to do.

**Comment by wenduwan** [comment]
This hang is tricky. It was revealed in MTT

https://github.com/open-mpi/ompi-tests/blob/6dc370a85328add2a98914866e38714415363d2a/ibm/collective/alltoallv_somezeros.c#L145-L151

The participants are using different data types as well as buffer counts:
- Case 1: some use 0-byte types with non-zero counts
- Case 2: some use non-zero types with zero counts

So what happened in the hang is that, since we previously added 0-byte datatype skips, those in Case 1 do not send anything and return immediately - however the ranks in Case 2 are still trying to receive from them.

Luke is right in that the current `ompi_coll_base_sendrecv_actual` appears to do 0-count send/recv. That's why I replaced it in this PR.

@bosilca So should we fix `ompi_coll_base_sendrecv_actual` instead? I do see it being used in other collectives indirectly.

**Comment by lrbison** [comment]
Here is a reproducer.  I discussed offline with Wenduo, and I would like to propose an alternative to this PR, which is to avoid the "early return" path altogether, and let sendrecv do whatever it wants.  The trickiness as I see it is the combo of 0-size, 0-count, and differing in-place settings.

```
#include <mpi.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char** argv) {
    int rc = 0;

    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    int world_size;
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    if (world_size != 4) {
        if (world_rank == 0) printf("This test requires exactly 4 ranks\n");
        MPI_Barrier(MPI_COMM_WORLD);
        MPI_Finalize();
        rc = 4;
        return rc;
    }

    MPI_Comm_set_errhandler(MPI_COMM_WORLD, MPI_ERRORS_RETURN );

    int sendbuf0[4], recvbuf[4];
    int *sendbuf = sendbuf0;
    int sendcounts[4] = {0,0,0,0};
    int recvcounts[4] = {0,0,0,0};
    int sdispls[4] = {0,1,2,3};
    int rdispls[4] = {0,1,2,3};
    MPI_Datatype sendtype, recvtype;

    sendtype = MPI_CHAR;
    recvtype = MPI_CHAR;

    switch (world_rank)
    {
    case 0:
        /* normal, but in-place */
        sendbuf = MPI_IN_PLACE;
    case 1:
        /* normal */
        sendcounts[0] = 1; sendcounts[1] = 1;
        recvcounts[0] = 1; recvcounts[1] = 1;
        break;
    case 2:
        /* ignored: 0 counts */
        sendtype = MPI_CHAR;
        recvtype = MPI_CHAR;
        break;
    case 3:
        /* ignored: 0 sizes */
        for (int i=0; i<4; i++) {
            sendcounts[i] = 1;
            recvcounts[i] = 1;
        }
        MPI_Type_contiguous(0, MPI_CHAR, &sendtype);
        MPI_Type_contiguous(0, MPI_CHAR, &recvtype);
        MPI_Type_commit(&sendtype);
        MPI_Type_commit(&recvtype);
        break;
    }

    double precision = MPI_Wtick();
    double t0 = MPI_Wtime();
    // printf("Rank %d entering alltoallv\n", world_rank);
    memset(recvbuf, world_rank, world_size);
    memset(sendbuf0, world_rank, world_size);

    rc = MPI_Alltoallv(sendbuf, sendcounts,
                sdispls, sendtype, recvbuf,
                recvcounts, rdispls, recvtype,
                MPI_COMM_WORLD);
    double t1 = MPI_Wtime();

    if (rc != 0) {
        printf("Error: Rank %d completed with status=%d\n",world_rank, rc);
    } else {
        printf("Rank %d completed alltoallv successfully: (%f usec).\n",world_rank,1e6*(t1-t0));
    }
    rc |= MPI_Finalize();
    return rc;
    
}
```

**Comment by lrbison** [comment]
With my test case, I still see hangs in this PR.  I have posted an alternative PR which addresses the issue I mentioned above https://github.com/open-mpi/ompi/pull/12280

**Pull request closed without merging**
