### PR TITLE
rml changes

### PR DESCRIPTION
**Pull request by anandhis**
- added support to rml to allow for loading multiple plugins
- removed qos channel support

### CODE REVIEW

**Comment by rhc54** [comment]
@miked-mellanox The failure on your Jenkins looks totally unrelated to anything here - it is some envar check. There is nothing that tells us what is wrong, and I can't see how this change impacts that test. Could you please clarify?

**Comment by ggouaillardet** [comment]
fwiw

```
08:07:01 + export XXX_C=3 XXX_D=4 XXX_E=5
08:07:01 + XXX_C=3
08:07:01 + XXX_D=4
08:07:01 + XXX_E=5
08:07:01 ++ grep '^XXX_'
08:07:01 ++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
08:07:01 ++ wc -l
08:07:01 + val=10
08:07:01 + '[' 10 -ne 10 ']'
```

so far so good

```
08:07:01 + echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
08:07:01 ++ /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi
08:07:01 ++ grep '^XXX_'
08:07:01 ++ wc -l
08:07:02 + val=0
08:07:02 + '[' 0 -ne 10 ']'
```
test fails

my guess is the commands are
```
echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' > /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf
/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-ompi-master-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi | grep ^XXX_ | wc -l
```
note ```XXX_C``` XXX_D``` and XXX_E``` are still exported from the previous test
one option is the ```env_mpi``` binary is no more there (since i guess the test basically ```mpirun ... | grep ... | wc -l```,  it will simply returns 0
the error message (mpirun was unable to fine the specified executable...) is displayed on stdout, and that could be an other bug by the way
an other option is ```env_mpi``` does not do what it is supposed to do, but i do not have the sources for this test. a quick fix is to use ```env``` instead of ```env_mpi``` since this program does not have to be a MPI app

**Comment by hjelmn** [comment]
bot:retest

**Comment by hjelmn** [comment]
@ggouaillardet That was my bad. A fix in the mpool_rewrite branch got lost which was causing jenkins failures. Fix now.

**Pull request merged**
