### PR TITLE
Add new error code introduced in MPI-3.1.

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
Can't go into 3.1 as it breaks ABI (changes MPI_ERR_LASTCODE). We should probably add a buffer in the future for these sort of minor standard changes.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/317/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/318/
Test PASSed.

**Comment by jsquyres** [comment]
@hjelmn and I chatted tonight -- he had a clever idea of making MPI_T_ERR_INVALID be the same as another error code for v1.8.

We should definitely give ourselves some headroom in below MPI_ERR_LASTCODE for the v1.9 series...

**Comment by mellanox-github** [comment]
* Coverity found 1413 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_320/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_320/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_320/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/320/
Test PASSed.

**Pull request merged**
