### PR TITLE
mtl/ofi: use mca param to set av type

### PR DESCRIPTION
**Pull request by hppritcha**
@yburette 

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by yburette** [comment]
@hppritcha I don't think this is what you want.

`av_type` is the MCA parameter -- e.g. `MTL_OFI_AV_MAP`.
Instead, the `av_attr` that's passed to `fi_av_open()` requires either `FI_AV_MAP` or `FI_AV_TABLE`.
Maybe you can reuse `hints->domain_attr->av_type`...

Or am I missing something?

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
@yburette you're correct. I'll fix.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by lanl-ompi** [comment]
looks like the mlnx bug is due to the dynamic procs problem.

**Pull request merged**
