### PR TITLE
Openib proc accounting fix

### PR DESCRIPTION
**Pull request by artpol84**
@hjelmn 
I'm still working on this, however I'd like to know your position regarding this changes.
Right now it works for OSU tests and I am currently testing it with the full MTT test suite.

### CODE REVIEW

**Comment by artpol84** [comment]
MTT looks fine. No degradation.

**Comment by artpol84** [comment]
Not true - looks like I see some problems with `mpi-test-suite`. Let me check.

**Comment by artpol84** [comment]
@hjelmn I've checked, the problem is out of the scope of this patch.
I'm seeing rear hangs of `mpi_test_suite`, on Gather but this appears with both tcp and openib BTL.

**Comment by artpol84** [comment]
@rhc54 @jsquyres @hppritcha @hjelmn 
Merry Christmas, dear coleagues :).

**Comment by artpol84** [comment]
**Update**: the hang that I was observing with `mpi-test-suite` seems to be related to **vader** BTL. If I use **sm** all runs fine. I recall that @rhc54 has told me that somebody was reporing **vader** hangs. I think that's it.
I'll try to investigate.

**Comment by artpol84** [comment]
`mpi-test-suite` problem addressed in PR https://github.com/open-mpi/ompi/pull/1264.

**Comment by hjelmn** [comment]
PR to v2.x

**Comment by artpol84** [comment]
@hjelmn, to PR this to v2.x we need to merge https://github.com/open-mpi/ompi-release/pull/868 first. This PR depends on it.

**Pull request merged**
