### PR TITLE
rmaps/round_robin: warn if oversubscribing when manually setting the …

### PR DESCRIPTION
**Pull request by ggouaillardet**
…number of hosts

This is a port of the v1.10 serires one-off open-mpi/ompi-release@8c5ce45ab64ab77eddb798ecf0c3a826021eced5

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 can you please review this ?

that fixes the issue described in http://www.open-mpi.org/community/lists/devel/2015/12/18455.php

with the current machinefile
```
localhost slots=2
```

```mpirun --machinefile machinefile -np 3 ...``` works without any warning without this commit.
with this commit, it aborts because of oversubscription (same behaviour as v1.10)

**Comment by rhc54** [comment]
This looks correct, but don't we also need the changes to the other mappers as well?

**Comment by ggouaillardet** [comment]
I guess so, will do from Monday

**Comment by ggouaillardet** [comment]
@rhc54 i back ported the other changes

**Comment by rhc54** [comment]
@ggouaillardet Thanks!

**Pull request merged**
