### PR TITLE
Fix typos in the docs/ sub-directory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./3rd-party,./docs/news -L ans,chello,configury,inout,scoll`

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test

**Comment by jsquyres** [comment]
@luzpaz These are great -- thank you!  Can you make two small updates?

1. We require a "Signed-off-by" line as a means of agreeing to our Contributor's Declaration: https://github.com/open-mpi/ompi/blob/main/.github/CONTRIBUTING.md#contributors-declaration. Can you amend your commit to include that?
2. The ReadTheDocs build CI test failed because some of the spelling fixes made the RST title lines be too short.  Can you amend those as well?  The relevant error message from the RTD CI test is:
```
/home/docs/checkouts/readthedocs.org/user_builds/ompi/checkouts/10485/docs/faq/running-mpi-apps.rst:1316: WARNING: Title underline too short.

Can I force Aggressive or Degraded performance modes?
----------------------------------------------------
/home/docs/checkouts/readthedocs.org/user_builds/ompi/checkouts/10485/docs/faq/running-mpi-apps.rst:1316: WARNING: Title underline too short.

Can I force Aggressive or Degraded performance modes?
----------------------------------------------------
/home/docs/checkouts/readthedocs.org/user_builds/ompi/checkouts/10485/docs/features/extensions.rst:19: WARNING: Title underline too short.

Available extensions
-------------------
```

Thank you!

**Comment by jsquyres** [comment]
> shall i squash and force push ?

Yes please.

**Comment by luzpaz** [comment]
Sorry, I"m trying to `git rebase -i` and vscode if hanging forever. Any tips on how to do it manually? :sweat:

**Review by jsquyres — APPROVED** [review]
Love it -- thank you!

**Pull request merged**
