### PR TITLE
Adding changes for issue #6303 for branch v2.x.

### PR DESCRIPTION
**Pull request by uberlinuxguy**
Signed-off-by: Jason Williams <uberlinuxguy@gmail.com>

### CODE REVIEW

**Comment by uberlinuxguy** [comment]
pushed fix for the alps odls.  accidentally had a double declaration when resolving the conflicts.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
@gpaulsen @jjhursey The IBM CI failed on this PR.  Can you have a look?  Thanks!

**Pull request merged**
