### PR TITLE
Prepare ompio frameworks for bigcount

### PR DESCRIPTION
**Pull request by jtronge**
This updates ompio-related frameworks and components to use size_t instead of int for counts.

I updated the version in the io framework from 2.0.0 to 3.0.0. fcoll and sharedfp both seem to be using different versions for the component and module structs, so I wasn't quite sure what version to use for those.

### CODE REVIEW

**Comment by edgargabriel** [comment]
I can confirm that this PR is correct in terms of high level interface changes. We also still pass our testsuites. However, I am 99% sure that we will need to add more work to actually make bigcount work, including probably adding at least some tests to our testsuite. 

So if the plan is to get the interface changes in and work after that component by component to upgrade them to support bigcount (and I am happy to help with that), I would be ok with this pr.

**Comment by hppritcha** [comment]
@edgargabriel do you approve this PR?

**Comment by hppritcha** [comment]
@edgargabriel could you advise us on the module/component versioning?  we think these should be change in fcoll and sharedfp?

**Review by edgargabriel — APPROVED** [review]

**Comment by edgargabriel** [comment]
@hppritcha I think you are correct in that we should probably increase the module/component versions in the fcoll and sharedfp frameworks. Ping me if you make that change, and I will rerun our tests before merging again

**Comment by hppritcha** [comment]
@edgargabriel could you double check @jtronge 's latest commit ?

**Review by edgargabriel — CHANGES_REQUESTED** [review]
You have removed all type-casts in mallocs, please add them back, e.g. 
```
-  sizes_old_group = (int*)malloc(num_merge_aggrs * sizeof(int));
+ sizes_old_group = malloc(num_merge_aggrs * sizeof(size_t));
```
please leave it as
```
+ sizes_old_group = (size_t *)malloc(num_merge_aggrs * sizeof(size_t)); 
```
throughout the code base. I will re-review once that is fixed everywhere, but I would have to add too many messages/comments right now because of this issue.

**Comment by jtronge** [comment]
@edgargabriel I've added back all the malloc type-casts.

When I was changing the versions in fcoll and sharedfp I noticed that I had missed some of the collective calls in `fcoll/base`, and that's what the majority of these additional changes are.

**Comment by edgargabriel** [comment]
@jtronge thank you, I think it looks good. I will run tomorrow morning our testsuites on this branch, and will let you know after that whether the tests expose something in addition.

**Comment by edgargabriel** [comment]
Tests look good, I think we are good to merge this pr

**Comment by wenduwan** [comment]
After merging the PR we should watch MTT for a while. If often catches corners cases that we don't normally test.

**Comment by wenduwan** [comment]
(Clicked wrong button)

**Comment by hppritcha** [comment]
@edgargabriel could you click the review again?

**Review by edgargabriel — APPROVED** [review]

**Comment by hppritcha** [comment]
canceled NVIDA CI as it seems to be unable to recover from power outage any time soon.

**Pull request merged**
