### PR TITLE
Fix stale definition for OPAL_HAVE_ATOMIC_LLSC_PTR

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@google.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0708e3090370576f01bffa0eba77d73d

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2a4ecce00d3958911152aa46d9836b63

**Comment by jjhursey** [comment]
IBM Ci had an issue over the weekend. Retrying. bot:ibm:retest

**Comment by hjelmn** [comment]
bot:ibm:retest

**Review by awlauria — APPROVED** [review]

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request merged**
