### PR TITLE
openib btl: remove BTL_OPENIB_FAILOVER_ENABLED code

### PR DESCRIPTION
**Pull request by larrystevenwise**
Remove BTL_OPENIB_FAILOVER_ENABLED code in the openib btl source.

Remove the failover-specific files from the openib btl.

Update the openib/Makefile.am accordingly.

Remove the -enable-openib-failover config logic.

Signed-off-by: Steve Wise <swise@opengridcomputing.com>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
@hjelmn Got an opinion?

**Comment by hjelmn** [comment]
:+1:

**Comment by jsquyres** [comment]
@larrystevenwise Can you PR to v2.0.x and v2.x?  Thanks.

**Comment by larrystevenwise** [comment]
@jsquyres  Sure.  This is stale: https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests.  How do I create a PR to pull a commit from master to other branches?

**Comment by jsquyres** [comment]
Yeah, our wiki is a bit out of date since we pulled all the branches from ompi-release and put them back in ompi.  Just make PRs on this repo for the v2.0.x and v2.x branches.

**Comment by larrystevenwise** [comment]
Sorry for being dense...but I tried to create a v2.x PR but it wanted to pull all the commits from master to v2.x!   Should I:

1) cherry pick the commit to a local v2.x branch
2) push that to my clone
3) create a v2.x PR that pulls in the cherry-picked commit

And ditto for v2.0.x

**Comment by jsquyres** [comment]
Yes.  The cherry-pick procedure from the wiki is essentially the same, but now there's only 1 repo (ompi), not two (ompi and ompi-release).

**Comment by larrystevenwise** [comment]
#2350 and #2341 opened for v2.0.x/v2.x.

**Pull request merged**
