### PR TITLE
v4.1.x: Bull 2020 update of coll/han

### PR DESCRIPTION
**Pull request by EmmanuelBRELLE**
This completes and fixes current code for coll/Han:
- a barrier is added
- a "simple" scatter is added
- some Doxygen documentation is added

Fix:
- compilation and cppcheck warnings
- corner case errors when parsing a rule file

Signed-off-by: Emmanuel Brelle <emmanuel.brelle@atos.net>
(cherry picked from commit ca663de22cc96d560716ef35ffd149bc9dbad18f)

This is the re-submission of PR #8437 (on v4.1x), now that PR #8462 is merged on master.

### CODE REVIEW

**Comment by bwbarrett** [comment]
ok to test

**Comment by EmmanuelBRELLE** [comment]
Is there anything I can do to help reviewers to progress on this PR ?

**Comment by bosilca** [comment]
You should request the same reviewers as on the PR in master.

**Review by bosilca — APPROVED** [review]

**Comment by EmmanuelBRELLE** [comment]
> You should request the reviewers that reviewed the PR in master.

Thanks, indeed it would be great to have @jsquyres (who reviewed previous attempt #8437) or @ggouaillardet  (who merged master equivalent #8462) reviewing / merging this PR  ;)

**Comment by jsquyres** [comment]
I just made a few comments about fixing on master first and then cherry-picking to release branches.  😉 

HAN is from @bosilca, so I defer to his review!

**Comment by rajachan** [comment]
I would have preferred this to be separate commits as there are mutually exclusive fixes and updates in the commit, but given this is a cherry-pick from master it is fine to leave it as is. Can you amend your one-line commit summary to be a bit more descriptive of the change? *Bull update of coll/han* doesn't really indicate what the change is :)

**Comment by EmmanuelBRELLE** [comment]
> I would have preferred this to be separate commits as there are mutually exclusive fixes and updates in the commit, but given this is a cherry-pick from master it is fine to leave it as is. Can you amend your one-line commit summary to be a bit more descriptive of the change? _Bull update of coll/han_ doesn't really indicate what the change is :)

You are right, I should have splitted the commit for each feature, I apology. That makes the one-line commit message difficult to write and  complexify any revert. I tried (in feadc68) to improve the one-line message, but someone who wants details will look at the full commit message, at the end.

**Pull request merged**
