### PR TITLE
v4.1.x: Long live MPI_LONG and MPI_UNSIGNED_LONG

### PR DESCRIPTION
**Pull request by markalle**
The only 2 types that have an external32 representation with a different
size than most current architectures, and as a result are more
challenging to handle.

This patch also brings back the support for packing and unpacking to and
from external32 for all datatypes and does a little cleaning in the
datatype API and comments.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>
(cherry picked from commit 4e56e83d524ff7e425afb8b15e9aeb04235c3189)
(cherry picked from commit 49d9a9717810076006ea9e08c06a9d2b8383d4ec)

### CODE REVIEW

**Comment by jsquyres** [comment]
@markalle Your PR is failing the cherry pick CI.  Can you please check / revise?

**Comment by markalle** [comment]
@jsquyres I was wondering about that.  If it started as george's commitA in master, then I cherry picked it into v4.0.x as commitB (but hasn't been accepted there yet), should I just say cherry-picked from commitA here?  There were light modifications to port commitA to commitB.

**Comment by jsquyres** [comment]
If this is a cherry-pick from 4.0, then the CI is returning the correct thing: we just wait for it to be merged in 4.0 and then re-run the CI here.  Then it will pass the cherry pick test.

**Comment by jsquyres** [comment]
@markalle Per https://github.com/open-mpi/ompi/pull/9088#issuecomment-869682776, we also need #8780 here, too, right?

**Comment by markalle** [comment]
Thanks, I added 8780 to both the 4.0.x and 4.1.x PRs.  (this one being a cherry-pick of the 4.0.x version that isn't yet accepted in 4.0.x and therefore will still fail the commit checker part of CI for now)

**Comment by gpaulsen** [comment]
v4.0 RMs merged https://github.com/open-mpi/ompi/pull/9088 to v4.0.x, and advise that v4.1 RMs merge this as well.

**Pull request merged**
