### PR TITLE
Update the PMIx listener to avoid leaking sockets into children, and …

### PR DESCRIPTION
**Pull request by rhc54**
…better handle race condition errors

### CODE REVIEW

**Comment by rhc54** [comment]
Fixes #1842

**Comment by rhc54** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
