### PR TITLE
man: Various manpage corrections

### PR DESCRIPTION
**Pull request by kawashima-fj**
Various manpage corrections.

This PR consists of 16 commits. Please read each commit message for each change.

I forgot to write a description in the commit message of 519ddd9.
I changed five things:
- `ompi/mpi/man/man3/MPI.3in` originally had a big bug. The values of `MPI_ERR_ROOT` and below are not equal to values defined in `mpi.h` and `mpif.h`. In the manpage, both `MPI_ERR_REQUEST` and `MPI_ERR_ROOT`had the value 7 and all error classes below `MPI_ERR_ROOT` had -1 values.
- Remove unused `MPI_ERR_SYSRESOURCE`.
- Add error classes added in MPI-3.0 (MPI_T and RMA).
- Increase `MPI_ERR_LASTCODE` to match `mpi.h`.
- Change indentation of existing error classes to be pretty with added error classes.

I'll create a new PR for v2.x if this PR is accepted.
(with appropriate label and milestone)

During my code editing, I found that most `MPI_File_*` manpages does not have `INCLUDE 'mpif.h` -> `USE MPI` change done by Gilles recently. I'll convert them in another PR if anyone is aware.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by kawashima-fj** [comment]
bot:label:documentation

**Comment by jsquyres** [comment]
@kawashima-fj We only have the OMPI bot watching the ompi-release PRs, not the ompi (master) PRs.

I found 1 super-minor nit (accidental removal of a const), but otherwise this looks great.

**Comment by hppritcha** [comment]
what's going on with jenkins?
bot:retest

**Comment by kawashima-fj** [comment]
@jsquyres I updated my PR branch for removed `const`. Thanks.

**Comment by kawashima-fj** [comment]
My PR branch was updated to resolve the conflict with Gilles' b17c89c1 by reverting my three commits.

**Comment by jsquyres** [comment]
@kawashima-fj Perfect -- thank you!  Can you PR this to v2.x, as well?

**Comment by ggouaillardet** [comment]
@kawashima-fj
FYI
when you are working inside a git branch, and it cannot be merged because some conflicting changes occured in the master, you have the option to rebase&and fix conflicts instead of reverting conflicting changes.
for example, you could have done (from your pr/man-correction branch, and once all changes have been commited)
```
git remote update
# i assume origin points to https://github.com/open-mpi/ompi.git
git rebase -i origin/master
```
if some conflicts are not automatically resolved, you have to fix them manually with your favorite editor, and then
```
git commit -a
# or git add <modified files list> followed by  git commit
git rebase --continue
```
and re-iterate until the rebase operation is fixed.
if the branch was previously pushed into your github account, you need to force the update
```
# i assume kawashima-fj points to https://github.com/kawashima-fj/ompi.git
git push --force -u kawashima-fj pr/man-correction
```

**Comment by kawashima-fj** [comment]
@ggouaillardet Thanks for your information. I'll do it next time.

**Pull request merged**
