### PR TITLE
OMPI timings

### PR DESCRIPTION
**Pull request by karasevb**
Replaces the PR #3299

Note:
For use feature need to configure with `--enable-timings` and set env `OMPI_TIMING_ENABLE = 1` to enable results output.

### CODE REVIEW

**Comment by rhc54** [comment]
it builds now on my Linux machine, but I still get this warning repeatedly:

```shell
runtime/orte_init.c:156:49: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "initializations");
```
l think you have to modify how you are calling this macro so we maintain C99 standards - I saw similar issues in the test subdirectory and had to fix them.

**Comment by rhc54** [comment]
I'm also not able to make it output anything. I tried setting the envar as directed, but that doesn't do anything.  Trying now to see if there is something else that will trigger it

**Comment by rhc54** [comment]
I see what's going on - the configure option you gave is incorrect. It is ```--enable-timing```, not ```--enable-timings```
 Rebuilding now

**Comment by rhc54** [comment]
i can offer you a pull request against your repo, if you like. We still have the following issue:

```
../opal/util/timings.h:82:40: warning: ISO C does not support ‘__FUNCTION__’ predefined identifier [-Wpedantic]
     *name = OPAL_TIMING_ENV_START_TYPE(__FUNCTION__, OPAL_TIMING_AUTOMATIC_TIMER, "");
```

The standard uses ```__func___```, not ```__FUNCTION__``` - the latter is a gcc extension, I believe. It does, however, build on my Linux box - just a flood of warnings

**Comment by rhc54** [comment]
Some additional warnings from Cray:

```
runtime/ompi_mpi_init.c(978): warning #2332: a value of type "const char *" cannot be assigned to an entity of type "char *" (dropping qualifiers)
      OMPI_TIMING_NEXT("barrier-finish");
      ^

runtime/ompi_mpi_init.c(980): warning #556: a value of type "struct ompi_timing_list_t *" cannot be assigned to an entity of type "ompi_timing_list_t *"
      OMPI_TIMING_FINALIZE;
      ^
```
Looks like you forward-declared something, which means you need to cast it later before using it. Likewise to silence the ```const``` complaint.

**Comment by rhc54** [comment]
sigh - still fails to run:

```shell
mpirun: symbol lookup error: /home/common/openmpi/build/boris/lib/libpmix.so.0: undefined symbol: pmix_timing_clocksync_read
```

**Comment by rhc54** [comment]
Given the time difference, I'll try to clean this up a bit today and give you a PR against your repo.

**Comment by karasevb** [comment]
@rhc54 
```
mpirun: symbol lookup error: /home/common/openmpi/build/boris/lib/libpmix.so.0: undefined symbol: pmix_timing_clocksync_read
```
Did I understand correctly (https://github.com/open-mpi/ompi/pull/3299#issuecomment-292400418), do you mean that you will correct it yourself?


```
runtime/orte_init.c:156:49: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
     OPAL_TIMING_ENV_NEXT(tmng, "initializations");
```
What compiler do you use? I can't reproduce on my linux.

**Comment by rhc54** [comment]
My PR against your branch contains all the fixes. gcc (GCC) 6.1.0 on my CentOS7 box

**Comment by rhc54** [comment]
@karasevb You need to add ompi/util/timings.h to the ompi/util/Makefile.am so it gets included in the tarball

**Comment by rhc54** [comment]
Question - I'm trying to understand the following set of numbers:
```shell
[ompi_mpi_init.c:ompi_mpi_init:rte_init]: 5.086538 / 4.958872 / 5.175572
[orte_init.c:orte_init:initializations]: 2.327439 / 1.262884 / 3.245944
[orte_init.c:orte_init:opal_init]: 0.000006 / 0.000003 / 0.000031
[orte_init.c:orte_init:orte_locks_init]: 0.000005 / 0.000003 / 0.000027
[orte_init.c:orte_init:orte_register_params]: 0.000005 / 0.000003 / 0.000023
[orte_init.c:orte_init:orte_show_help_init]: 0.000005 / 0.000003 / 0.000019
[orte_init.c:orte_init:opal_error_register]: 0.000005 / 0.000003 / 0.000018
[orte_init.c:orte_init:orte_proc_info]: 0.000005 / 0.000003 / 0.000017
[orte_init.c:orte_init:framework_open(schizo)]: 0.000005 / 0.000003 / 0.000018
[orte_init.c:orte_init:orte_schizo_base_select]: 0.000005 / 0.000003 / 0.000018
[orte_init.c:orte_init:orte_schizo.check_launch_environment]: 0.000005 / 0.000003 / 0.000018
[orte_init.c:orte_init:framework_open(ess)]: 0.000008 / 0.000006 / 0.000038
[orte_init.c:orte_init:orte_ess_base_select]: 0.000005 / 0.000004 / 0.000017
[orte_init.c:orte_init:orte_ess.init]: 0.000006 / 0.000005 / 0.000016
[orte_init.c:orte_init:finalize]: 0.000005 / 0.000004 / 0.000016
```
The rte_init number from MPI_Init essentially is just the time spent in the call to orte_init. Yet the various pieces of timing from inside orte_init don't come close to adding up to the time reported from MPI_Init.

Any idea as to the reason for the difference?

**Comment by artpol84** [comment]
Detailed measurements are captured at opal level and exported in env.
While mpi_init value comes from ompi level measurements
Maybe smth is wrong with env piece import. I'm not sure if I'll be able to look into this till Monday unfortunately.

Where is this btw? Trinity? Was gettimeofday you mentioned on Thursday resolved? Can it be the cause?

**Comment by artpol84** [comment]
@artpol84 - so I'll get notifications

**Comment by artpol84** [comment]
@jsquyres I went through all commits and it seems that all have signed-off line.

**Comment by rhc54** [comment]
It's the "merge" of my PR that the checker can't figure out - it's a known problem, so don't worry about it.

There was no problem with gettimeofday that we could find. Instead, the issue was with the measurement technique. The detailed measurements show the problem - namely, that the difference in async modex is "masked" by the large linear-scaling time spent in the first stage of MPI_Init.

Let me know what you find out about the time difference issue when you have a chance to look at it.

**Comment by karasevb** [comment]
@rhc54 We found the reason for the time difference, I'm fixing.

**Comment by artpol84** [comment]
@karasevb can you provide an example output from your system with the most recent version of this PR?

**Comment by karasevb** [comment]
```
mpirun -n 4 ./ring_c 
------------------ ompi_mpi_init ------------------
[ompi_mpi_init.c:ompi_mpi_init:initialization]: 0.002895 / 0.002674 / 0.003074
[ompi_mpi_init.c:ompi_mpi_init:rte_init]: 0.018774 / 0.013542 / 0.023012
[orte_init.c:orte_init:initializations]: 0.000000 / 0.000000 / 0.000001
[orte_init.c:orte_init:opal_init]: 0.001336 / 0.001283 / 0.001406
[orte_init.c:orte_init:orte_locks_init]: 0.000003 / 0.000001 / 0.000007
[orte_init.c:orte_init:orte_register_params]: 0.000648 / 0.000600 / 0.000691
[orte_init.c:orte_init:orte_show_help_init]: 0.000011 / 0.000007 / 0.000013
[orte_init.c:orte_init:opal_error_register]: 0.000002 / 0.000001 / 0.000002
[orte_init.c:orte_init:orte_proc_info]: 0.000086 / 0.000079 / 0.000093
[orte_init.c:orte_init:framework_open(schizo)]: 0.000436 / 0.000409 / 0.000469
[orte_init.c:orte_init:orte_schizo_base_select]: 0.000007 / 0.000006 / 0.000008
[orte_init.c:orte_init:orte_schizo.check_launch_environment]: 0.000009 / 0.000008 / 0.000010
[orte_init.c:orte_init:framework_open(ess)]: 0.000247 / 0.000231 / 0.000262
[orte_init.c:orte_init:orte_ess_base_select]: 0.000004 / 0.000003 / 0.000007
[orte_init.c:orte_init:orte_ess.init]: 0.015657 / 0.010474 / 0.019865
[orte_init.c:orte_init:finalize]: 0.000000 / 0.000000 / 0.000000
[ompi_mpi_init.c:ompi_mpi_init:rte_init-modex]: 0.012682 / 0.010331 / 0.017507
[ompi_mpi_init.c:ompi_mpi_init:modex]: 0.009995 / 0.002692 / 0.016509
[ompi_mpi_init.c:ompi_mpi_init:modex-barrier]: 0.055945 / 0.054131 / 0.058499
[ompi_mpi_init.c:ompi_mpi_init:barrier]: 0.003818 / 0.000985 / 0.005643
[ompi_mpi_init.c:ompi_mpi_init:barrier-finish]: 0.000180 / 0.000143 / 0.000253
[ompi_mpi_init:overhead]: 0.003055 
```

**Comment by rhc54** [comment]
Thanks - that makes much more sense as one would expect that the PMIx fetches are where the time would be spent.

**Comment by artpol84** [comment]
@rhc54, we need to check something in addition. PR as it is now is expected to work well, but we want to 2-check and remove pid dependency if we don't need it.

**Comment by artpol84** [comment]
(and I guess we don't)

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2af156ba3bde370c6ce4ece2a61c0641

**Comment by artpol84** [comment]
@rhc54 
```
19:52:21 ../../../orte/.libs/libopen-rte.so: undefined reference to `opal_timing_ts_func'
19:52:21 collect2: error: ld returned 1 exit status
19:52:21 make[2]: *** [orte-clean] Error 1
19:52:21 make[2]: Leaving directory `/scrap/jenkins/jobs/gh-ompi-master-pr/workspace-3/orte/tools/orte-clean'
19:52:21 make[1]: *** [install-recursive] Error 1
19:52:21 make[1]: Leaving directory `/scrap/jenkins/jobs/gh-ompi-master-pr/workspace-3/orte'
19:52:21 make: *** [install-recursive] Error 1
```
I thought you have fixed that - we had almost clean CI previously. Do you have an idea on what has happened?

**Comment by artpol84** [comment]
@rhc54 Ooops - I misread it - this is not a pmix timing error. Sorry

**Comment by rhc54** [comment]
Question for you guys: I want to add timing to opal_init as we are finding there is some time "sink" down there. When I put the macros in, though, I'm not getting anything picked up in the report. What would I need to do to get timing reports out of the opal layer?

**Comment by artpol84** [comment]
You need to import it in OMPI layer. Check how rte_init is imported in ompi_mpi_init

**Pull request merged**
