### PR TITLE
v5.0: Ignore receive buffer at non-root for cuda reduce collective

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
cherry pick of https://github.com/open-mpi/ompi/pull/10329

### CODE REVIEW

**Comment by jsquyres** [comment]
@Akshay-Venkatesh You have the same git commit checker failures here on this PR as you do with #10325.

**Comment by Akshay-Venkatesh** [comment]
@janjust 

Any thoughts on why build checker is failing in configure:
```

3. Running autotools on top-level tree

==> Remove stale files
==> Writing m4 file with autogen.pl results
==> Writing txt file with all the mca component paths
==> Running autoreconf
Running: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force --warnings=all,no-obsolete,no-override -I config
FATAL: command execution failed
```

**Comment by awlauria** [comment]
@Akshay-Venkatesh that seems like an internal ci error. Let's see if it happens again.

**Comment by awlauria** [comment]
@Akshay-Venkatesh can you bring the second commit over as well: https://github.com/open-mpi/ompi/pull/10329/commits/8d9e60fdeeecb1fdf62f61498744dd771cf89e77

**Comment by Akshay-Venkatesh** [comment]
> @Akshay-Venkatesh can you bring the second commit over as well: [8d9e60f](https://github.com/open-mpi/ompi/commit/8d9e60fdeeecb1fdf62f61498744dd771cf89e77)

Not needed as all changes are in the single merge commit I cherry picked.

**Review by awlauria — APPROVED** [review]

**Pull request merged**
