### PR TITLE
oshmem/memheap: correct usage of opal_dss functions

### PR DESCRIPTION
**Pull request by hjelmn**
Any buffer given to opal_dss.load becomes the responsibility of the
opal_buffer_t object. It will be freed automatically if either the
opal_buffer_t is released or opal_dss.load is called again on the
buffer. opal_dss.unload will not prevent this unless no unpacking
takes place between the .load and .unload calls.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@miked-mellanox This fixes the opal_dss usage problem that came up in #893.

**Comment by jsquyres** [comment]
Adding @rolfv, too, since it affects the (probably-false) jenkins failure on #893.

**Comment by miked-mellanox** [comment]
@hjelmn - was there change in behavior for opal_dss.*load() functions?
Why it started from Sept12?

**Comment by hjelmn** [comment]
@miked-mellanox Yes. The behavior changed in open-mpi/ompi@22d7c0081a58c39408adad3c72fa73549c530083. @rhc54 Was this behavior change intended.

**Comment by miked-mellanox** [comment]
thanks.
This PR: #892 which broke master, has failed on exact same failure w/ jenkins (http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr/1070/) , but was merged anyway.

**Comment by hjelmn** [comment]
Ah, so jenkins caught it but the failure was ignored?

**Comment by hjelmn** [comment]
Looks like the new behavior does not match the documentation:

```
/**
 * Unload the data payload from a buffer.
 *
 * The unload function provides the caller with a pointer to the data
 * payload within the buffer and the size of that payload. This allows
 * the user to directly access the payload - typically used in the RML
 * to unload the payload from the buffer for transmission.
 *
 * @note This is a destructive operation. While the payload is
 * undisturbed, the function will clear the buffer's pointers to the
 * payload. Thus, the buffer and the payload are completely separated,
 * leaving the caller free to OBJ_RELEASE the buffer.
 *
 * @param buffer A pointer to the buffer whose payload is to be
 * unloaded.
 *
 * @param payload The address to a void* pointer that is to be loaded
 * with the address of the data payload in the buffer.
 *
 * @param size The size (in bytes) of the data payload in the buffer.
 *
 * @retval OPAL_SUCCESS The request was succesfully completed.
 *
 * @retval OPAL_ERROR(s) An appropriate error code indicating the
 * problem will be returned. This should be handled appropriately by
 * the caller.
 *
 * @code
 * opal_buffer_t *buffer;
 * uint8_t *bytes;
 * int32_t size;
 *
 * status_code = opal_dss.unload(buffer, (void**)(&bytes), &size);
 * OBJ_RELEASE(buffer);
 * @endcode
 */
```

**Comment by hjelmn** [comment]
This PR is obviously not the correct fix unless we want to change the documentation of opal_dss.unload. Lets keep it open for discussion.

**Comment by hjelmn** [comment]
Though, part of this patch is correct. I will keep that part.

**Comment by rhc54** [comment]
I disagree - the patch is correct and necessary. The problem is that people aren't using it correctly and never did. Let's get on the phone and talk this thru before doing something wrong

**Comment by hjelmn** [comment]
After talking with @rhc54 I think the behavior of load/unload is correct. We need to update the documentation at some point so the behavior is clear.

I pushed an updated version of the fix. @miked-mellanox if you have no objections I will merge once the checks have passed.

**Comment by hjelmn** [comment]
Misc failure.

:bot:retest:

**Comment by hjelmn** [comment]
Mellanox jenkins did not rerun. @miked-mellanox can you see what is going on?

**Comment by hjelmn** [comment]
:bot:retest:

**Comment by miked-mellanox** [comment]
failed on slurm "srun" launcher we added yesterday. will disable it for now.
The patch seems to fix the issue.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
shall it be ported to v2.0 as well?

**Comment by hjelmn** [comment]
The patch should probably be moved to 2.x since the patch that changed the behavior of opal_dss will probably be moved to 2.x.

**Comment by rhc54** [comment]
@hjelmn @miked-mellanox Yeah, I'll add it to my PR since it was changed there. Thanks!

**Pull request merged**
