### PR TITLE
Improve the range and accuracy of MPI_Wtime.

### PR DESCRIPTION
**Pull request by bosilca**
As discussed on https://github.com/mpi-forum/mpi-issues/issues/77#issuecomment-369663119
the conversion to double in the MPI_Wtime decrease the range
and accuracy of the resulting timer. By setting the timer to
0 at the first usage we basically maintain the accuracy for
194 days even for gettimeofday.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7c2ade236017945328afb6d446af3d36

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3c1a63356106737ead55087bab035a0b

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4c1c181636566b9960e6c98335a5beb8

**Comment by jsquyres** [comment]
@bosilca Looks like you have some kind of error:

```
pwtime.c:95:15: error: use of undeclared identifier 'tv'
    wtime += (tv.tv_sec - time_origin.tv_sec);
              ^
1 error generated.
Error while processing pwtime.c.
```

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/635054a1e3c30ebd6a85536f41bccab8

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2b30f2f908f408fe9e0db6f642e3b773

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/36e2afa763057f37ed9a5c4099e707b5

**Comment by ggouaillardet** [comment]
@bosilca out of curiosity, why didn't you choose to initialize `time_origin` in `MPI_Init()` and hence get rid of an `if(OPAL_UNLIKELY(...))` ?

**Comment by ggouaillardet** [comment]
@bosilca, got it, thanks !

**Comment by bosilca** [comment]
I fixed some of the suggestions. Regarding the time_origin symbol, it is supposed to be extern so that I can be shared between wtime.o and pwtime.o, but it should not the DECLSPEC as I don't want it to be visible from outside.

**Comment by ggouaillardet** [comment]
:bot:mellanox:retest

**Comment by ggouaillardet** [comment]
@bosilca thanks, that PR looks good to me !

**Comment by hjelmn** [comment]
Looks good to me as well. I still think double is a horrible type for a timer but that is one of the more minor mistakes we have to live with from MPI-1. This PR at least makes it so we don't loose precision.

**Pull request merged**
