### PR TITLE
[v5.0.x] ompi/dpm: make procs consistent before calling PMIx_Connect()

### PR DESCRIPTION
**Pull request by wzamazon**
ompi_dpm_connect_accept() call PMIx_Connect() to establish
connection, with "procs" as an argument.

PMIx requires "procs" to be consistent accross clients.

When it is used to set up inter-communicator communication,
ompi_dpm_connect_accept() does not maintain the order of
proc in "procs". This is because the function is called
by both MPI_Comm_connect() and MPI_Comm_accept(), and
it always put processes in local communicator in "procs"
first, followed by processes in remote communicator.

However, for caller of MPI_Comm_connect() and MPI_Comm_accept(),
local communicator and remote communicator are different.

This patch fixed the issue by sorting "procs" before
it is used to call PMIx_Connect(), this ensures that "procs"
are consistent accross processes.

Signed-off-by: Wei Zhang <wzam@amazon.com>
(cherry picked from commit 029430375a0b46daf1500061b552395bb293754c)

### CODE REVIEW

**Comment by wzamazon** [comment]
back port https://github.com/open-mpi/ompi/pull/10557 to v5.0.x

**Review by hppritcha — APPROVED** [review]

**Comment by hppritcha** [comment]
hmm looks like azure is unhappy
/azp run

**Comment by hppritcha** [comment]
looks like docker issues at mlnx:

Error response from daemon: Get http://rdmz-harbor.rdmz.labs.mlnx/v2/hpcx/ompi_ci/manifests/latest: received unexpected HTTP status: 500 Internal Server Error

**Comment by wzamazon** [comment]
bot:mellanox:retest

**Comment by wzamazon** [comment]
The mellanox CI issue seems to be persistent. I tried a few times, and it always fail.

**Review by jjhursey — APPROVED** [review]

**Comment by wckzhang** [comment]
Mellanox CI was also having trouble last week. @artemry-nv can you take a look?

**Comment by artemry-nv** [comment]
> Mellanox CI was also having trouble last week. @artemry-nv can you take a look?

Some issues with the container registry - working on this.

**Comment by wzamazon** [comment]
Mellanox CI fixed itself and passed. 

@awlauria Can you merge this PR?

**Pull request merged**
