### PR TITLE
platform/mellanox: disable btl-uct by default — v4

### PR DESCRIPTION
**Pull request by amaslenn**
(cherry picked from commit 074e9cc92c79e6b9f8c492b2613eac3f27e1c522)

### CODE REVIEW

**Comment by amaslenn** [comment]
@yosefe

**Comment by yosefe** [comment]
@gpaulsen can we merge this? it's important for us because of btl_uct compilation issues

**Comment by hjelmn** [comment]
@yosefe Again, #5966 is the correct approach. Instead of disabling (and not testing with CI) code it should be fixed.

**Comment by yosefe** [comment]
@hjelmn in general I agree, but currently we need to remove btl/uct from platform/mellanox/optimized, due to issues of supporting it. Since it's Mellanox-only configuration, I hope it wouldn't be a problem.

**Comment by jsquyres** [comment]
Ya, this is an organization-specific platform file.  We generally don't care what individual organizations do in their own platform files.

**Comment by hjelmn** [comment]
As long as it doesn't affect CI I don't really care :). My understanding is this platform file is used by Mellanox CI, is that incorrect?

**Comment by yosefe** [comment]
@hjelmn yes, it's used by Mellanox CI

**Comment by hjelmn** [comment]
Then that I find as a problem. With #5966 the build issue is fixed and for v4.0.x the component is disabled by default so I see no reason to not build it. That way your CI can at least run a build test on btl/uct changes. I don't know of any other CI system which has OpenUCX right now.

**Comment by hjelmn** [comment]
You can also force the component not to load by adding btl = ^uct to your MCA parameters file.

**Comment by yosefe** [comment]
@hjelmn looks like you are not going to merge the fix for a week at least, and in meantime our CI is broken

**Comment by jsquyres** [comment]
Oh, I didn't realize that was the Mellanox CI config file (i.e., the one that is used by open-mpi/ompi github CI, right?).  If so, then I would tend to agree with @hjelmn -- we should just fix the problem.

**Comment by yosefe** [comment]
@jsquyres @hjelmn I didn't mean the CI which tests OMPI PRs, but another one we have internally

**Comment by hjelmn** [comment]
@yosefe Then I withdraw my objection. My primary concern is CI for PRs :).

**Comment by yosefe** [comment]
@hjelmn actually, the PR CI also uses platform/mellanox/optimized, but it is not broken now because it compiles with UCX v1.4 and not UCX master. But i guess we can update the PR CI to run at least build test without a platform config.

**Pull request merged**
