### PR TITLE
Sync updates for PMIx and PRRTE

### PR DESCRIPTION
**Pull request by rhc54**
Fixes typo in setting debug-daemons-flag and adds "iquote" support

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@artemry-mlnx Looks like some UCX device required by one or more of your tests isn't available, and that causes the app to segfault. Not sure why the device is offline. I'm going to retry in case it is just a momentary "burble".

/azp run

**Comment by rhc54** [comment]
@artemry-mlnx Nope, looks like something is busted on the Mellanox CI node:
```text
+ timeout -s SIGSEGV 17m /__w/1/ompi/ompi_install/bin/mpirun --np 4 --bind-to none --report-state-on-timeout --get-stack-traces --timeout 900 -x UCX_NET_DEVICES=mlx5_0:1 --mca pml ucx /__w/1/ompi/ompi_install/examples/hello_c ''
[1586191890.926384] [swx-jupiter04:16914:0]    ucp_context.c:727  UCX  WARN  network device 'mlx5_0:1' is not available, please use one or more of: 'eth0'(tcp)
[1586191890.926384] [swx-jupiter04:16915:0]    ucp_context.c:727  UCX  WARN  network device 'mlx5_0:1' is not available, please use one or more of: 'eth0'(tcp)
[1586191890.926311] [swx-jupiter04:16916:0]    ucp_context.c:727  UCX  WARN  network device 'mlx5_0:1' is not available, please use one or more of: 'eth0'(tcp)
[1586191890.927235] [swx-jupiter04:16913:0]    ucp_context.c:727  UCX  WARN  network device 'mlx5_0:1' is not available, please use one or more of: 'eth0'(tcp)
[swx-jupiter04:16913:0:16913] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8e30)
[swx-jupiter04:16916:0:16916] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8e30)
[swx-jupiter04:16914:0:16914] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8e30)
[swx-jupiter04:16915:0:16915] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8e30)
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node swx-jupiter04 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```
Can you please investigate?

**Comment by artemry-mlnx** [comment]
I'll take a look.
Thanks for reporting.

**Comment by artemry-mlnx** [comment]
Right now there's another CI running - let's check that it isn't specific to this PR.

**Comment by rhc54** [comment]
@artemry-mlnx Looks like they are all crashing on the same error

**Comment by artemry-mlnx** [comment]
Checking.

**Comment by artemry-mlnx** [comment]
OS/MLNX_OFED was updated on the CI host - there're some inconsistencies with docker test environment.
Now it should work fine.
Sorry for the inconvenience.

**Comment by rhc54** [comment]
@artemry-mlnx Thanks!

**Comment by rhc54** [comment]
@bwbarrett This now contains the NUMA_RANK support you requested. Just need someone (you or @jsquyres) to review/approve it

**Pull request merged**
