### PR TITLE
PR/oshmem man pages

### PR DESCRIPTION
**Pull request by igor-ivanov**
This PR adds man pages for OpenSHMEM API (man3). 

Could anyone look at this and provide any comments.
@jsquyres @rhc54 @miked-mellanox 

Do I need to submit related PR to other release branches?

### CODE REVIEW

**Comment by igor-ivanov** [comment]
@jladd-mlnx could you track it too

**Comment by hppritcha** [comment]
this goes in to v2.x as well?

**Comment by hppritcha** [comment]
per discussion with @jladd-mlnx adding to v2.x milestone

**Comment by jsquyres** [comment]
This PR has sat for a while and is now a bit stale.

@igor-ivanov can you please rebase on top of current master?  Also, please update `.gitignore` to ignore your generated man pages and `.dir-stamp`.

Once this is rebased and `.gitignore` is updated, I'd say go ahead and merge it, and file a PR for v2.x.

**Comment by igor-ivanov** [comment]
@jsquyres updated according your notice

**Comment by miked-mellanox** [comment]
:+1:

**Comment by hppritcha** [comment]
please open a pr for v2.x for these changes

----------

sent from my smart phonr so no good type.

Howard

**Pull request merged**
