### PR TITLE
docs: update ompio documentation

### PR DESCRIPTION
**Pull request by edgargabriel**
The ompio documentation has not been updated in quite a while. This pr brings the ompio entry up-to-date with the current state of the software.

Signed-off-by: Edgar Gabriel <Edgar.Gabriel@amd.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@edgargabriel Awesome -- thanks!

Our goal is to completely remove the entire `/faq/` tree, and just fold all that content into the rest of the docs (i.e., not as Q&A content, but as regular "documentation" content, like the rest of the docs).  The `/faq/` dir is there just as a holdover to contain all the as-yet-unconverted content from the old <=v4.x FAQ content.

**SIDENOTE:** I could have sworn that I put disclaimers on all FAQ pages to this effect so that people wouldn't keep editing them, but apparently that never got pushed back up, unfortunately.  ☹️ 

Could you migrate the `/faq/ompio` to a different part of the document -- perhaps under a new subsection in `/features/`, or somewhere else (I'm open to suggestion)?

**Comment by edgargabriel** [comment]
@jsquyres thank you, will do. Niote, the edits that I made are already adjusted to not make it look like an FAQ entry (i.e. its not a question and answer format anymore).

**Comment by edgargabriel** [comment]
The generic description of features makes it sound like it is only meant for extensions to the MPI standard. Do you want to adjust the language to say something like 'this section provides additional information on various features of Open MPI, including some that represent extensions to the MPI specification'. 

Alternative would be to move the ompio section to `tuning` maybe?

**Comment by jsquyres** [comment]
> @jsquyres thank you, will do. Niote, the edits that I made are already adjusted to not make it look like an FAQ entry (i.e. its not a question and answer format anymore).

👍 

> The generic description of `/features/` makes it sound like it is only meant for extensions to the MPI standard. Do you want to adjust the language to say something like 'this section provides additional information on various features of Open MPI, including some that represent extensions to the MPI specification'.

Yeah, you're probably right.
 
> Alternative would be to move the ompio section to a `/tuning/` section maybe?

I've struggled with the organization of the existing content -- the current layout represents my current thinking, but it may still not be quite right yet.  Right now it's generically like this:

* Building MPI applications
  * Talks about the wrapper compilers, the deprecated/removed MPI APIs, and generically how to build MPI applications
* Running MPI applications
  * Talks about the MCA, generically setting MCA params, and then how to launch in a variety of different situations / resource managers
* Debugging Open MPI Parallel Applications
  * Talks about the variety of debugging mechanisms in and around Open MPI
* Networking system support
  * Talks about all the networks that OMPI supports, and their tunable MCA params

I wonder if we should re-jigger this to be:

* Building MPI apps
* Launching MPI apps
* Tuning MPI apps
  * Network type selection and tuning
  * MPI I/O tuning
    * OMPIO
    * ROMIO
  * ...anything else that can be tuned...
* Debugging MPI apps

If that organization looks ok, the question becomes: where to put the MCA description / setting MCA params content?  Should that move to a top-level section on its own?

**Comment by edgargabriel** [comment]
How about if we make the generic MCA description as the first subsection in the 'Tuning MPI apps' section, i.e. something like:

>     * Building MPI apps
>     * Launching MPI apps
>     * Tuning MPI apps
>       * MCA parameters       
>       * Network type selection and tuning
>       * MPI I/O tuning
>         * OMPIO
>         * ROMIO
>       * ...anything else that can be tuned...
>     * Debugging MPI apps

**Comment by jsquyres** [comment]
> How about if we make the generic MCA description as the first subsection in the 'Tuning MPI apps' section,

Technically, setting MCA params also applies to launching MPI apps.

**Comment by edgargabriel** [comment]
yes, you are right, having it as a top level entry makes more sense, I agree

**Comment by jsquyres** [comment]
@edgargabriel I'll make you a deal...

1. I'll take your commit from this PR and fold it into PR #11242 
2. I'll do the re-org we talked about here on this PR on that same PR
3. You review the PR
4. We merge the PR
5. We bask in the glory of well-written docs, and go enjoy the holidays 🎄 🎅

**Comment by jsquyres** [comment]
@edgargabriel I hope you take the deal 😄 because I did the re-shuffle and added the commit from this PR to #11242.

**Comment by edgargabriel** [comment]
> @edgargabriel I hope you take the deal 😄 because I did the re-shuffle and added the commit from this PR to #11242.

sounds good to me :-)

**Pull request closed without merging**
