### PR TITLE
More one sided bindings

### PR DESCRIPTION
**Pull request by nrgraham23**
Bindings for the MPI_WIN_FLUSH_LOCAL, MPI_WIN_FLUSH_LOCAL_ALL, MPI_WIN_ALLOCATE, MPI_WIN_ALLOCATE_SHARED, and MPI_COMM_SPLIT_TYPE.  Also added several necessary constants.

@jsquyres  @hppritcha 

Signed-off-by: Nathaniel Graham ngraham@lanl.gov

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by nrgraham23** [comment]
bot:retest

**Comment by hppritcha** [comment]
:+1:

**Comment by hppritcha** [comment]
I'm going to go ahead a merge, assuming that @jsquyres is probably pretty busy with other stuff at the moment.

**Pull request merged**
