### PR TITLE
Release the allocator list items from the list before destructing

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by jsquyres** [comment]
@rhc54 Does this fix #1065?

**Comment by jsquyres** [comment]
Ah, you said at the bottom of #1065 that this PR is the fix for it.  :-)

Pro tip (if you care): if you put "Fixes open-mpi/ompi#1065" in the commit message, it'll auto-close that issue when this PR is merged.  :smile:

**Comment by bosilca** [comment]
By looking at the proposed patch I have the impression that it does not fix the issue, but instead it hide it. The objects from the seg_list are never released (unlike the subject of this patch suggest), instead they are simply removed from the list (allowing the list destructor to succeed as the list is now empty). Thus, this looks like a potential memory leak to me.

**Comment by rhc54** [comment]
You may well be correct - I wasn't entirely sure why releasing the items was causing a problem, but this seemed to fix it. We hit a similar issue in the oshmem area, but that was clearly a case where the list objects held some memory that was getting double-free'd. Someone should take a look at the underlying objects to understand why releasing them in that location is an issue.

**Pull request merged**
