### PR TITLE
v2.0.x: PML/SPML/UCX: Adapt to the API changes in the UCX lib.

### PR DESCRIPTION
**Pull request by yosefe**
picked from master https://github.com/open-mpi/ompi/pull/2537

### CODE REVIEW

**Comment by yosefe** [comment]
@jladd-mlnx @alinask @miked-mellanox

**Comment by jladd-mlnx** [comment]
:+1:

**Comment by jsquyres** [comment]
Per https://github.com/open-mpi/ompi/pull/2570#issuecomment-267037421, is this correct?

It doesn't even pass Mellanox Jenkins -- I'm not sure whether this should be approved...?

**Comment by hppritcha** [comment]
I think MLNX Jenkins hasn't switched over to the latest UCX.
I think that should be done before we merge this and the corresponding PR for 2.x.

**Comment by jsquyres** [comment]
@hppritcha Agreed.  @jladd-mlnx confirmed as much in https://github.com/open-mpi/ompi/pull/2563.

**Comment by hppritcha** [comment]
bot:mlnx:retest

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jladd-mlnx** [comment]
It's still pulling in bad UCX. Someone in Israel will need to fix it tomorrow.

**Comment by hppritcha** [comment]
@jsquyres I'm going ahead and merging this.

**Pull request merged**
