### PR TITLE
Revert "v5.0.x: hwloc: Update internal hwloc to v2.7.0."

### PR DESCRIPTION
**Pull request by awlauria**
Reverts open-mpi/ompi#9897

bot:notacherrypick

### CODE REVIEW

**Comment by awlauria** [comment]
Reverting until https://github.com/open-mpi/ompi/issues/9907 is resolved.

I'll check hwloc releases to see if we can go to a higher version than 2.4 for a subsequent PR.

**Review by gpaulsen — APPROVED** [review]
Please wait until `master` version is merged before merging this.

**Comment by bwbarrett** [comment]
I'd actually hold off on this, given #9921 should fix the problem (and was way easier than we expected).

**Comment by awlauria** [comment]
Closing in favor of solution in #9921

**Pull request closed without merging**
