### PR TITLE
Cleanup a lagging message that generates an annoying (but seemingly harmless) warning

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by rhc54** [comment]
??? there's no output from the IBM tests except "error" - any idea what is going wrong? I assume it's a problem on the Jenkins end.

**Comment by jjhursey** [comment]
Let me check - it seems that way.

**Comment by jjhursey** [comment]
Should be fixed now. It's hard to get it to report that connectivity issue upstream, but I have a todo item to try to make that error message better. Sorry about that.

bot:retest

**Pull request merged**
