### PR TITLE
Add the ability to pass args to the rsh/ssh command line

### PR DESCRIPTION
**Pull request by rhc54**
Per request from David Bigagli @bigaglidavid

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 912 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_447/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_447/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_447/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/447/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 913 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_448/output/errors/index.html

* Coverity found 5 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_448/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_448/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/448/
Test PASSed.

**Comment by rolfv** [comment]
I think that has broken all my nightly testing on the master.   My errors look like this:
```
[rvandevaart@ivy4 pt2pt]$ mpirun --mca btl_openib_if_include mlx5_0:1 --np 2 -host ivy4,ivy5 ./osu_bw D D
bash: /ivylogin/home/rvandevaart/ompi-repos/ompi-master-uvm/64-dbg//ivylogin/home/rvandevaart/ompi-repos/ompi-master-uvm/64-dbg/bin/orted: No such file or directory
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
[rvandevaart@drossetti-ivy4 pt2pt]$ 
```

**Comment by rhc54** [comment]
Huh - so much for all that vaunted Jenkins crap! Okay, I can revert it for
now and will resolve it later.

**Comment by rolfv** [comment]
I played a little more with this and it seems to only happen when launching on a remote node.  Some how we get a double path in front of orted.   Just tested latest master with revert of this commit and all is good again.

**Comment by miked-mellanox** [comment]
@rhc54 
jenkins is not substitute for mtt, but mostly for compilation issues. 
it is launching all on local machine.
if trigger is use of remote machine - maybe we should add it to jenkins as well.

**Pull request merged**
