### PR TITLE
usnic: remove typo

### PR DESCRIPTION
**Pull request by jsquyres**
Remove an amusing -- but harmless -- typo.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@bwbarrett @wckzhang CI failed on this in the IPv6 build, but this PR has nothing to do with IPv6.

Could one of you look at that build and see what went wrong?

**Comment by wckzhang** [comment]
I don't believe I have edit access or hardware access to the jenkins, but we should fix the -hostfile in the command line.

The relevant error occurred during ring_c:
```
Hello, world, I am 1 of 2, (Open MPI v4.1.0a1, package: Open MPI ubuntu@ip-172-31-10-242 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7599-ga361b80, Unreleased developer copy, 151)
Hello, world, I am 0 of 2, (Open MPI v4.1.0a1, package: Open MPI ubuntu@ip-172-31-10-242 Distribution, ident: 4.1.0a1, repo rev: v2.x-dev-7599-ga361b80, Unreleased developer copy, 151)
[warn] Epoll MOD(1) on fd 20 failed.  Old events were 6; read change was 0 (none); write change was 2 (del): Bad file descriptor
[warn] Epoll MOD(4) on fd 20 failed.  Old events were 6; read change was 2 (del); write change was 0 (none): Bad file descriptor
--> Running example: ring_c
---------------------------
```

Doesn't seem related to your change.

**Comment by jsquyres** [comment]
@wckzhang Ya, I know you don't have usNIC hardware.  😄  I should have been more clear: I was asking because the IPV6 job is running on AWS, and that's where the error occurred.

Hey @rhc54 -- is the error that William is showing a PMIX or PRRTE error, perchance?

**Comment by rhc54** [comment]
Not sure - it's certainly possible that something in the PMIx IPv6 support isn't right as nobody checks it on our side. Is the test for IPv6 something newly added to the CI? If not, I can't think of anything we have done that relates to IPv6, and I would have thought it would have shown up in an update PR for PMIx and/or PRRTE.

**Comment by bwbarrett** [comment]
The IPv6 test has been there for at least a year, so it's definitely not new.

The first crash looks like it was during finalize/cleanup.  These are single core instances; I wonder if it didn't clean up, causing the other test to timeout.  either way, it looks like we might have a problem with IPv6 support.

**Comment by bwbarrett** [comment]
bot:aws:retest

**Pull request merged**
