### PR TITLE
[v4.1.x] fix atomic operations opal_atomic_compare_exchange_strong_ in arm64

### PR DESCRIPTION
**Pull request by yuncliu**
fix opal_atomic_compare_exchange_strong_ bug in arm64

### CODE REVIEW

**Comment by jsquyres** [comment]
Is this a v4.1.x port of #11999?  If so, can you finish the #11999 PR and get that merged first, and then cherry-pick it over here to the v4.1.x branch?

Thanks!

**Comment by yuncliu** [comment]
> Is this a v4.1.x port of #11999? If so, can you finish the #11999 PR and get that merged first, and then cherry-pick it over here to the v4.1.x branch?
> 
> Thanks!

The main branch only need to modify one file, but 4.1.x need to modify two atomic.h with same implementation,  cherry-pick will lost the change in ./opal/include/opal/sys/arm64/atomic.h

**Review by jsquyres — CHANGES_REQUESTED** [review]
It looks like we do have a problem here in v4.1.x somewhere, but this is apparently not the desired solution (per discussion on #11999).  I'm marking this as "request changes" to ensure we don't merge it, but don't want to close it yet.

#12011 is a new issue opened to track the problem (on main, v5.0.x, and v4.1.x).

**Comment by lrbison** [comment]
@yuncliu thank you again for reporting this issue. I think it may be fixed in https://github.com/open-mpi/ompi/pull/12338. Can we have any further discussion in the issue https://github.com/open-mpi/ompi/issues/12011 rather than this PR?

I will close this PR for now, as I don't think it is the correct change. However if you could confirm the additional write memory barrier in smcuda fixed your issue https://github.com/open-mpi/ompi/issues/12011 it would be greatly appreciated!

Thank you

**Pull request closed without merging**
