### PR TITLE
v2.0.x: osc/rdma: fix a segfault in MPI_Win_unlock due to an access to a NULL…

### LINKED ISSUE #5581: v2.0.x: osc/rdma: MPI_Win_unlock segfaults
Thank you for taking the time to submit an issue!

## Background information
using osc/rdma
calling osu_acc_latency -m create -s lock

leads to a segfault in MPi_Win_unlock()

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v2.0.x

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

MPI_Win_unlock() segfaults because of an access to a NULL pointer in ompi_osc_rdma_lock_btl_fop().
This issue is specific to v2.0.x: starting from v2.x, the locking code has been reworked and the issue implicitely fixed.

will submit a fix

### PR DESCRIPTION
**Pull request by derbeyn**
fixes #5581.

Signed-off-by: Nadia Derbey <Nadia.Derbey@atos.net>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6f1d6ddac11cdaa44ebd350168b3e182

**Comment by derbeyn** [comment]
Don't understand how a trivial change as "if (*result)" --> "if (NULL != result)" in osc/rdma can lead to a ld error in pml/ucx?

**Comment by jsquyres** [comment]
@derbeyn See #5584

**Comment by derbeyn** [comment]
ok thx @jsquyres !

Actually, I already faced that same problem on a local cloned tree (because I was using hcoll, and there was a dependency on libucp.so in /opt/mellanox/hcoll/libhcoll.la).
I could fix it by installing ucx-devel in my build environment and by adding:
--with-ucx-libdir=$(pkg-config --variable libdir /usr/lib64/pkgconfig/ucx.pc)'
to my configuration line.

Hope that helps...

**Comment by jsquyres** [comment]
@derbeyn Good to know.  But even if that is necessary, it should fail during `configure` -- not deep down in the build process.  IMNSHO.  😉

**Comment by jsquyres** [comment]
@derbeyn I did not notice that this was on the v2.0.x branch.  Is there a reason you want to commit to this very old branch?

**Comment by derbeyn** [comment]
The openmpi we officially deliver is based on it.

**Comment by jsquyres** [comment]
@derbeyn Ok.  Can you please check if this error exists on v2.x, v3.0.x., v3.1.x, v4.0.x, and master?

@hppritcha I have no objection to merging this on v2.0.x (and #5587, which will allow CI to pass), even though we won't be doing a new community release from this branch.  Thoughts?

**Comment by hppritcha** [comment]
@jsquyres as long as we're not going to release v2.0.5 I'm fine with this just being patched in to the branch.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jsquyres** [comment]
Hmm.  Looks like IBM's CI barfed ("If you see this page then something went wrong with IBM's CI test on your PR. Mention one of the IBM developers on your PR to investigate further on the test system.").  Try again...

bot:ibm:retest

**Comment by jsquyres** [comment]
Now that #5587 is in, this PR passed CI.

@derbeyn Given that v2.0.x is no longer supported by the community, we suggest that you move up to a newer release of Open MPI (e.g., 4.0.0 is coming soon).

**Comment by derbeyn** [comment]
@jsquyres , this is planned, actually. 
But we still have customers that don't want to move to a newer release and that will need support. 
Does this mean that we shouldn't be asking for our commits to be merged in this branch anymore?

**Comment by jsquyres** [comment]
@derbeyn We talked about this on the weekly webex today.  Everyone seemed to be of the opinion that if it isn't too much effort, we'll continue to take your patches up here in the community v2.0.x branch.  It is highly unlikely that we'll do another community release from this branch, but we do recognize:

1. The Open MPI community likes to be as friendly as possible to its members / vendors.
1. There is business value in you contributing your v2.0.x fixes up here to the community repo.
1. It's likely to continue to be a low cost / low effort for the community to accept these patches.

If it becomes difficult / time consuming / resource intensive to accept these patches, we might want to talk it over again (with someone from Bull on the webex).

Cool?

**Comment by derbeyn** [comment]
great. Thx a lot!

**Pull request merged**
