### PR TITLE
Remove C++ Bindings

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
This is waiting on feedback from ECP. The likely result is this will get merged.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by awlauria** [comment]
@hjelmn we want this in for 5.0, did you want me to rebase it?

**Comment by jsquyres** [comment]
This PR has conflicts because a later PR already removed them: #7428 (0b8baa217d584f84d17baa8afa0779c610b6d2cc).

This PR can be closed without merging.

**Comment by awlauria** [comment]
Awesome, thanks. @jsquyres

**Pull request closed without merging**
