### PR TITLE
v2.x: PML/SPML/UCX: Adapt to the API changes in the UCX lib.

### PR DESCRIPTION
**Pull request by yosefe**
picked from master https://github.com/open-mpi/ompi/pull/2537

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox @alinask @jladd-mlnx

**Comment by jladd-mlnx** [comment]
:+1:

**Comment by jsquyres** [comment]
Per https://github.com/open-mpi/ompi/pull/2570#issuecomment-267037421, is this correct?

It doesn't even pass Mellanox Jenkins -- I'm not sure whether this should be approved...?

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by jladd-mlnx** [comment]
I think Mellanox Jenkins was pulling in the older UCX without the API changes.

**Comment by jsquyres** [comment]
@jladd-mlnx Ah, cool.  Can you guys update so that it pulls in the new UCX and therefore we can get a friendly green check from the Mellanox Jenkins?

**Comment by jladd-mlnx** [comment]
@jsquyres Yes, it will be ready in a couple of hours. So, I may have triggered this build a little prematurely. Sorry for the noise.

**Comment by jsquyres** [comment]
@jladd-mlnx No worries.  Do't forget about the Mellanox-specific rebuild option.

**Comment by miked-mellanox** [comment]
bot:mlnx:retest

**Comment by miked-mellanox** [comment]
bot:mellanox:retest

**Comment by miked-mellanox** [comment]
@jsquyres, @hppritcha  - it is ready for merge. now jenkins uses latest ucx instead of latest-stable.

**Pull request merged**
