### PR TITLE
Create an alternative mapping method

### PR DESCRIPTION
**Pull request by rhc54**
Create an alternative mapping method that pushes more responsibility
onto the backend daemons. Let mpirun simply determine how many procs
are on each node and send a regex of that info in the launch msg. Then
have the backend daemons parse that regex to create the proc map, and to
find their own local children.

This significantly reduces the computational time on mpirun as it isn't
running up/down the topology tree computing thousands of binding
locations, and it reduces the launch message to a very small number of
bytes.

This is not quite complete - some of the job-level info isn't being
communicated to the MPI procs. Will finish in the morning.

NOTE: please do not merge this until I return from vacation! This is solely for a few people to test.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@hjelmn @jjhursey @markalle As we discussed - still a bit to do before I depart, but I should get the prototyping done for you. This design preserves the legacy operation for those mappers that don't yet support the regex.

**Comment by rhc54** [comment]
@hjelmn @jjhursey @markalle Okay, I have this working now for the map-by node and slot use-cases. I'm not seeing bindings computed yet, but will work that later today.

**Comment by rhc54** [comment]
should note: using the new code path requires setting ```--mca rmaps rr2```

**Comment by jjhursey** [comment]
@rhc54 Thanks for the work on this. I'm hoping to squirrel away some time in the next week to play with all of this a bit more.

**Comment by rhc54** [comment]
okay, this appears to be fully functional now. Setting ```--mca rmaps rr2``` will get you the regex mapper. It looks like all the binding options are okay right now, though the placement may not be ideal. There are more optimizations (I noted one in the comments), but let's see how much this helps.

**Comment by hjelmn** [comment]
Ok, will test this tonight.

**Comment by rhc54** [comment]
Quick check shows the benefit:

```
$ mpirun -mca ras_simulator_num_nodes 8192 hostname
[rhc001:186467] LAUNCH MSG RAW SIZE: 13861589 COMPRESSED SIZE: 1514624

$ mpirun -mca ras_simulator_num_nodes 8192 -mca rmaps rr2 --map-by slot hostname
[rhc001:186659] LAUNCH MSG RAW SIZE: 837

```
Quite a difference!

**Comment by rhc54** [comment]
That is computed with 24ppn

**Comment by rhc54** [comment]
Final note: you need to also specify ``--map-by node``` or ```--map-by slot``` when you want to use the new mapper

**Comment by hjelmn** [comment]
mpirun is crashing for me with this rmaps component:

```
[tr2-login7:23636] [[49945,0],0] plm:base:receive update proc state command from [[49945,0],35]
[tr2-login7:23636] [[49945,0],0] plm:base:receive got update_proc_state for job [49945,1]
[tr2-login7:23636] [[49945,0],0] plm:base:receive got update_proc_state for vpid 34 state RUNNING exit_code 0
[tr2-login7:23636] [[49945,0],0] ORTE_ERROR_LOG: Not found in file base/plm_base_receive.c at line 342
[tr2-login7:23636] *** Process received signal ***
[tr2-login7:23636] Signal: Segmentation fault (11)
[tr2-login7:23636] Signal code: Address not mapped (1)
[tr2-login7:23636] Failing at address: 0x54
[tr2-login7:23636] [ 0] /lib64/libpthread.so.0(+0xf870)[0x7fe900ebc870]
[tr2-login7:23636] [ 1] /lustre/tr2scratch1/users/hjelmn/build/ompi.master/lib/libopen-rte.so.0(orte_plm_base_recv+0xc82)[0x7fe903d8e935]
[tr2-login7:23636] [ 2] /lustre/tr2scratch1/users/hjelmn/build/ompi.master/lib/libopen-rte.so.0(orte_rml_base_process_msg+0x1f8)[0x7fe903dd9d9d]
[tr2-login7:23636] [ 3] /lustre/tr2scratch1/users/hjelmn/build/ompi.master/lib/libopen-pal.so.0(opal_libevent2022_event_base_loop+0xe51)[0x7fe9038a1cb1]
[tr2-login7:23636] [ 4] mpirun[0x40183c]
[tr2-login7:23636] [ 5] mpirun[0x401226]
[tr2-login7:23636] [ 6] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fe900b26b25]
[tr2-login7:23636] [ 7] mpirun[0x401139]
[tr2-login7:23636] *** End of error message ***
Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x00007fe903d8e935 in orte_plm_base_recv (status=0, sender=0x7fe8f804a310, buffer=0x7fffe210c6c0, tag=5, cbdata=0x0)
    at base/plm_base_receive.c:348
#1  0x00007fe903dd9d9d in orte_rml_base_process_msg (fd=-1, flags=4, cbdata=0x7fe8f804a240) at base/rml_base_msg_handlers.c:185
#2  0x00007fe9038a1cb1 in event_process_active_single_queue (activeq=0x64f940, base=0x64f3d0) at event.c:1370
#3  event_process_active (base=<optimized out>) at event.c:1440
#4  opal_libevent2022_event_base_loop (base=0x64f3d0, flags=1) at event.c:1644
#5  0x000000000040183c in orterun (argc=24, argv=0x7fffe210c998) at orterun.c:197
#6  0x0000000000401226 in main (argc=24, argv=0x7fffe210c998) at main.c:13
(gdb) p peer
No symbol "peer" in current context.
(gdb) p proc
$1 = (orte_proc_t *) 0x0
(gdb) 
```

Looks like it is trying to update the exit code for an app process but it crashes because it doesn't have a proc structure for it.

**Comment by rhc54** [comment]
@hjelmn I think I have this fixed now.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/18537f02509ab6112eeb5f435cac5e53

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/1dbc42fba9827a6dfb256e3ed8649964

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ff471708dc6ea148d5b81d80939401a0

**Comment by rhc54** [comment]
@jjhursey Looks like your server is dead again:

```
Connection to Testing Cluster Failed. Contact @jjhursey
```

**Comment by jjhursey** [comment]
Sure enough. I'll check with the admins, and take down our Jenkins until it's resolved.

**Comment by rhc54** [comment]
@hjelmn I believe this works, and that it also rolls up the messages to mpirun - which in the past has significantly improved launch behavior. However, I'm having trouble testing on gadget as the file system appears to be highly erratic. Any suggestions would be welcome.

If you get a chance to test in the meantime, please let me know how it goes.

**Comment by rhc54** [comment]
I have an update for this that I will push this weekend - it moves _all_ mapping to the backend. The message size results for 8192 nodes at 64ppn are (values in bytes):

```
NEW METHOD:   LAUNCH MSG RAW SIZE: 864
OLD METHOD:   LAUNCH MSG RAW SIZE: 24,642,425 COMPRESSED SIZE: 3,878,081
```

**Comment by rhc54** [comment]
Note that the number of bytes in the message for the new method is independent of the number of procs or nodes. We are simply packing the app_context array and letting the backend daemons do the mapping. So the size depends solely on the number and complexity of the app_contexts, and not on the size of the job.

**Comment by rhc54** [comment]
Here are the new message size numbers:

```
64 nodes, 64ppn   ===> 846 bytes
128 nodes, 64ppn  ===> 850 bytes
256 nodes, 64ppn  ===> 850 bytes
1024 nodes, 64ppn ===> 854 bytes
2048 nodes, 64ppn ===> 854 bytes
4096 nodes, 64ppn ===> 854 bytes
8192 nodes, 64ppn  ===> 854 bytes
8192 nodes, 128ppn  ===> 856 bytes
```
The largest time consumer is now mpirun creating the orte\_node\_pool array as it builds a complete array of orte\_node\_t objects, one per node. For very large allocations, this consumes a lot of time and memory. What we would like to do is somehow go directly from the allocation to the regex of the hostnames.

In addition, we need to cleanup memory footprint on the backend daemons now as they are building a complete picture of the job. At the least, we need to release memory for all nodes and procs other than our own after we get done mapping the job.

These two points will be addressed in upcoming PRs.

**Comment by rhc54** [comment]
This has been tested in default operation, plus using -novm option and with the orte-dvm.

**Comment by rhc54** [comment]
Mellanox error appears due to something else? retry

bot:mellanox:retest

**Comment by rhc54** [comment]
@ggouaillardet Would you mind testing this prior to my committing it? Just want some other environment to have given it a spin first.

**Comment by rhc54** [comment]
```
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                          |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
| MPI Install | my installation | 3.0.0a1     | 00:00    | 1    |      |          |      | MPI_Install-my_installation-my_installation-3.0.0a1-my_installation.html |
| Test Build  | trivial         | 3.0.0a1     | 00:02    | 1    |      |          |      | Test_Build-trivial-my_installation-3.0.0a1-my_installation.html          |
| Test Build  | ibm             | 3.0.0a1     | 00:42    | 1    |      |          |      | Test_Build-ibm-my_installation-3.0.0a1-my_installation.html              |
| Test Build  | intel           | 3.0.0a1     | 01:13    | 1    |      |          |      | Test_Build-intel-my_installation-3.0.0a1-my_installation.html            |
| Test Build  | java            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Build-java-my_installation-3.0.0a1-my_installation.html             |
| Test Build  | orte            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Build-orte-my_installation-3.0.0a1-my_installation.html             |
| Test Run    | trivial         | 3.0.0a1     | 00:08    | 8    |      |          |      | Test_Run-trivial-my_installation-3.0.0a1-my_installation.html            |
| Test Run    | ibm             | 3.0.0a1     | 11:19    | 496  |      | 1        |      | Test_Run-ibm-my_installation-3.0.0a1-my_installation.html                |
| Test Run    | spawn           | 3.0.0a1     | 01:50    | 6    |      | 1        | 1    | Test_Run-spawn-my_installation-3.0.0a1-my_installation.html              |
| Test Run    | loopspawn       | 3.0.0a1     | 05:05    |      | 1    |          |      | Test_Run-loopspawn-my_installation-3.0.0a1-my_installation.html          |
| Test Run    | intel           | 3.0.0a1     | 16:52    | 474  |      |          | 4    | Test_Run-intel-my_installation-3.0.0a1-my_installation.html              |
| Test Run    | intel_skip      | 3.0.0a1     | 12:47    | 431  |      |          | 47   | Test_Run-intel_skip-my_installation-3.0.0a1-my_installation.html         |
| Test Run    | java            | 3.0.0a1     | 00:01    | 1    |      |          |      | Test_Run-java-my_installation-3.0.0a1-my_installation.html               |
| Test Run    | orte            | 3.0.0a1     | 00:42    | 19   |      |          |      | Test_Run-orte-my_installation-3.0.0a1-my_installation.html               |
+-------------+-----------------+-------------+----------+------+------+----------+------+--------------------------------------------------------------------------+
```

**Comment by ggouaillardet** [comment]
@rhc54 

i tested this PR rebased onto the laster ```master```

the first messages in this PR suggest i should
```mpirun --mca rmaps rr2 --map-by {node,slot} ...```
there is now no ```rmaps/rr2``` component. do i need to use ```--map-by {node,slot}``` to properly test this PR ?


i found two issues on a non standard usage
- frontend is single socket with 4 cores
- compute node is KNL

with ```master```
```
$ mpirun --host kusmcnode01 hostname
kusmcnode01
$ mpirun --host kusmcnode01:68 -np 4 true
$ mpirun --host kusmcnode01:68 -np 68 true
```

but with this branch
```
$ mpirun --host kusmcnode01 hostname
[kusmcnode01:25015] [[26793,0],1] ORTE_ERROR_LOG: Bad parameter in file ../../../../../src/ompi-master-knl/orte/mca/odls/base/odls_base_default_fns.c at line 424
--------------------------------------------------------------------------
Either the -host or -hostfile options were given, but the number
of processes to start was omitted. This combination is not supported.

Please specify the number of processes to run and try again.
--------------------------------------------------------------------------
$ mpirun --host kusmcnode01:68 -np 4 true
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4 slots
that were requested by the application:
  true

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
$ mpirun --host kusmcnode01:68 -np 68 true
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 68 slots
that were requested by the application:
  true

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```

and an other issue if i run from a KNL compute node (quite standard)

with ```master```
```
$ mpirun --hostfile machinefile -np 272 true
```
but with this branch
```
$ mpirun --hostfile machinefile -np 272 true
--------------------------------------------------------------------------
Open RTE was unable to open the hostfile:
    machinefile
Check to make sure the path and filename are correct.
--------------------------------------------------------------------------
[kusmcnode01:26710] 2 more processes have sent help message help-hostfile.txt / no-hostfile
[kusmcnode01:26710] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
but everything is fine if i use the full path for the machinefile
```
$ mpirun --hostfile `pwd`/machinefile -np 272 true
```

**Comment by rhc54** [comment]
okay, i'll look at the hostfile situation tomorrow. thx!

**Comment by hjelmn** [comment]
@rhc54 Found a bug. Looks like it just chews up memory until we get OOMed:

```
[NID 13119] 2017-03-05 23:53:47 Apid 2831726: initiated application termination
[NID 13119] 2017-03-05 23:53:47 Apid 2831726: OOM killer terminated this process.
```

I will try and debug it tomorrow.

**Comment by rhc54** [comment]
@ggouaillardet Just to help clarify: were you executing mpirun on node kusmcnode01 for the first set of your tests? Or some other node? I ask because I'm trying to understand which node was complaining about -host not having enough slots.

**Comment by rhc54** [comment]
@ggouaillardet Also, was this in a managed allocation?

**Comment by ggouaillardet** [comment]
@rhc54 no batch manager was used.
the first set was ran from the login node (non knl, 4 cpus only)

**Comment by rhc54** [comment]
@hjelmn @ggouaillardet I found and fixed some errors in the nidmap regex code - I can't swear it fixed everything, but I believe it is worth another try when you have time.

**Comment by rhc54** [comment]
weird - Mellanox failed doing some kind of coverity build??

bot:mellanox:retest

**Pull request merged**
