### PR TITLE
Fix typos in the opal/ subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Comment by luzpaz** [comment]
Converted back to Draft PR because I located more typos. Will add them soon

**Comment by luzpaz** [comment]
Ok, ready for review. This turned in to a big PR, wasn't intending that.

**Comment by awlauria** [comment]
@luzpaz can you squash these and add a signoff? `git commit --amend --signoff` + a force push should do it.

**Comment by luzpaz** [comment]
Signed off + squashed (sorry for the extra noise)

**Comment by awlauria** [comment]
ok to test

**Review by bosilca — APPROVED** [review]

**Review by jsquyres — APPROVED** [review]
On the one hand, it's pretty embarrassing how many typos in comments we have 😢 
On the other hand, hey, we have a lot of comments! 😄 

Before merging this, admittedly at the risk of overthinking it, we should decide whether we want it.

On the one hand, it's a ton of **good, obvious typo corrections** (mostly in comments, but a handful in strings).
On the other hand, **it's a ton** of good, obvious typo corrections (mostly in comments, but a handful in strings).

FWIW, I checked:
* 👍 This commit applies without conflict to the v5.0.x branch
* 👎 This commit has a zillion conflicts with the v4.1.x branch
* 👎 This commit has a zillion conflicts with the v4.0.x branch

Hence, assuming we apply this commit to the v5.0.x branch, I'm not worried about making future cherry picks from main ➡️ v5.0.x.  However, v4.0.x/v4.1.x are a different story.

On the one hand, future cherry picks from main ➡️ v4.x might be a little harder.
On the other hand, cherry picks to v4.x are somewhat slowing down (as they should be).  And the typos don't constitute a *major* source of conflicts; certainly, they may be annoying, but easily resolvable.

This discussion has shades of The Great Style+Whitespace Correction PR from a while ago.  We ultimately decided _not_ to apply that PR, but, IIRC, only because we devolved down into a rathole of trying to decide exactly what style+whitespace rules to apply (and how to apply them, because that was imperfect, too).  Fixing english typos in comments and strings seems a bit different: it's solidly objective (vs. debating style), and easily repeatable.

I think I'm in favor of applying this PR and dealing with the conflicts that come up with v4.x branches.  Other opinions?

**Comment by awlauria** [comment]
I think conflicts should be minimal, and in general will be easily resolvable when they do pop up. I'm in favor of merging and bringing back to v5.

**Comment by luzpaz** [comment]
JFYI, there are a handful of typos in `ompi/`, `oshmem/`, `config/`, and `contrib/`. Please advise

**Comment by jsquyres** [comment]
I think that this has been talked about on the OMPI weekly webex, and no one had any objection.  I'm merging!

@luzpaz Yes, if you have typos fixes for other directories in the overall tree, additional PRs would be welcome!

**Pull request merged**
