### PR TITLE
v2.x: opal: add support for s390 and s390x architectures

### PR DESCRIPTION
**Pull request by nmorey**
Signed-off-by: Nicolas Morey-Chaisemartin <NMoreyChaisemartin@suse.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@nmorey The intent for this PR is to enable Vader's CMA support to compile on S390[X] platforms, is that correct?  Note that we usually commit such fixes to `master` first, and then cherry-pick them to the relevant release branches.  Can you open a corresponding PR against `master`?

@bosilca @hjelmn Can you have a quick look?  Looks fairly straightforward.

**Comment by jsquyres** [comment]
Cross-reference: #3443

**Comment by nmorey** [comment]
@jsquyres Yes. I had to fix 2.1.0 build for SUSE so I sent the patch as is but I can probably port it to master.

**Comment by jsquyres** [comment]
@nmorey Excellent; thanks!

**Comment by bwbarrett** [comment]
@jsquyres, we shouldn't merge this patch to 2.x until it's 1) in master and 2) there's a PR to 3.x as well...

**Comment by nmorey** [comment]
@bwbarrett I'll do one for 3.x once master gets accepted then :)

**Comment by bwbarrett** [comment]
@nmorey: yes, the usual path for PRs in Open MPI is master then to the branches.  @jsquyres, @hppritcha, and I are currently trying to make sure that we don't accidentally ship something in 2.1, but then not in 3.0, so the comment was as much for us as anyone :).

**Comment by jsquyres** [comment]
#3454 was just merged to master; it is a slightly updated version of this PR (i.e., added a comment).

**Comment by jsquyres** [comment]
@hppritcha Do you have an opinion on whether this should go to v2.1.1 or v2.1.2?

**Comment by jsquyres** [comment]
Corresponding master PR: #3454

**Comment by jsquyres** [comment]
Per discussion with @bwbarrett, this will go into v3.x, so let's go ahead and take this in v2.x.

**Pull request merged**
