### PR TITLE
coll/{base,libnbc}: fix datatypes/operator retention

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs. open-mpi/ompi#6870
Refs. open-mpi/ompi#6876

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@AboorvaDevarajan @amaslenn could you please give this PR a try ?

@bosilca can you please review this?
Then I will merge and backport into `v4.0.x`

**Comment by AboorvaDevarajan** [comment]
With the patch `igather_gap` and `iscatter_gap` tests are passing, I ran the tests on 2 nodes (20 procs on each node) for about 10+ iterations, it all passed.

But the below tests still seems to fail for np > 2,

```
ireduce_nocommute_inter 
ireduce_nocommute_stride_inter
ireduce_nocommute_gap_inter
```

**Comment by ggouaillardet** [comment]
@jladd-mlnx Coverity fails on MLNX's Jenkins (licence issue)

```
+ cov-analyze --dir /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build/all
Coverity Static Analysis version 8.5.0 on Linux 3.10.0-327.el7.x86_64 x86_64
Internal version numbers: c8d197a567 p-kent-push-26368.915

[FATAL] No license file (license.dat) or license configuration file (license.config) found in the default location: /hpc/local/commercial/coverity/cov-sa/bin
++ cov-format-errors --dir /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/cov_build/all
++ awk '/Processing [0-9]+ errors?/ { print $2 }'
[FATAL] No license file (license.dat) or license configuration file (license.config) found in the default location: /hpc/local/commercial/coverity/cov-sa/bin
```

Could you please have it fixed ?

I have some PR that would clearly need it before I merge into master.

**Comment by amaslenn** [comment]
Looks like the issue is still here:
```sh
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code:  (128)
Failing at address: (nil)
[ 0] /usr/lib64/libpthread.so.0(+0xf5e0)[0x7fb7ed51e5e0]
[ 1] /ompi/__install/lib/libmpi.so.0(ompi_coll_base_retain_datatypes_w+0x7c)[0x7fb7ed7cb0cc]
[ 2] /ompi/__install/lib/libmpi.so.0(PMPI_Ialltoallw+0x2c1)[0x7fb7ed78fa21]
[ 3] /mpich-3.3.1/test/mpi/coll/nbicalltoallw[0x401c28]
[ 4] /mpich-3.3.1/test/mpi/coll/nbicalltoallw[0x401f81]
[ 5] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fb7ed16dc05]
[ 6] /mpich-3.3.1/test/mpi/coll/nbicalltoallw[0x401af9]
*** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
```

**Comment by ggouaillardet** [comment]
@amaslenn I pushed a new commit that should fix this issue

@AboorvaDevarajan I cannot reproduce any crash, could you please upload a stack trace ?

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by gpaulsen** [comment]
@AboorvaDevarajan , @amaslenn, How does this PR look now that it's been updated?

**Comment by gpaulsen** [comment]
Will want this on v4.0.x after https://github.com/open-mpi/ompi/pull/6863 goes in.

**Comment by amaslenn** [comment]
> @AboorvaDevarajan , @amaslenn, How does this PR look now that it's been updated?

My tests have passed 👍

**Comment by AboorvaDevarajan** [comment]
It's all passing now with the updated fixes, Thanks :+1:

**Comment by ggouaillardet** [comment]
Thanks ! I issued #6889 to backported the fix to the `v4.0.x` branch

**Pull request merged**
