### PR TITLE
Update v2.0.2 release files (including VERSION/shared library versions)

### LINKED ISSUE #2573: Update shared library versions for v2.0.2
Title says it all.

### PR DESCRIPTION
**Pull request by jsquyres**
Fixes #2573

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Please review.  I've temporarily left the "JMS" comments in so that you can see the rationale for each version number change.  I'll remove those comments before the final merge.

### CODE REVIEW

**Comment by hppritcha** [comment]
:+1:

**Comment by jsquyres** [comment]
These are all doc updates.  No need to wait for CI.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/c09986dfcf22b5b5df46e8077b88a565

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/c09986dfcf22b5b5df46e8077b88a565

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/c09986dfcf22b5b5df46e8077b88a565

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/c09986dfcf22b5b5df46e8077b88a565

**Pull request merged**
