### PR TITLE
CI/add ze compile sanity check github action

### PR DESCRIPTION
**Pull request by hppritcha**
may merge with ROCM sanity check at some point

### CODE REVIEW

**Comment by edgargabriel** [comment]
@hppritcha I looked over the compilation, something is not yet right. It seems to me that ze is discovered by configure, but the component is after that not actually compiled.
image

**Comment by hppritcha** [comment]
odd but the ze component is built lower down something like 8300 or something.

**Comment by hppritcha** [comment]
oh this may be because i was doing make -j

**Comment by edgargabriel** [comment]
oh, ok, makes sense, sorry for the noise :-)

**Review by edgargabriel — APPROVED** [review]

**Comment by hppritcha** [comment]
thanks for being thorough!

**Pull request merged**
