### PR TITLE
asm/arm64: ensure instruction ordering on timer

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@shamisp Please review.

**Comment by shamisp** [comment]
@hjelmn thanks for the patch. I would suggest to go ```asm volatile("isb" : : : "memory")```. This is what is used in linux kernel. I also use it in ucx.

**Comment by shamisp** [comment]
@hjelmn looks good to me 👍

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/6a1f97e7ba0be7a6846ecfaa4c39911d

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/2746fecf92fda4d80ff1b80b23edbfc7

**Comment by ibm-ompi** [comment]
Build Failed with PGI compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/1c0802e7daeff8b5aa6889d53fdd37d0

**Pull request merged**
