### PR TITLE
Allow all tuned MCA parameters to be modified programatically. (#2829)

### PR DESCRIPTION
**Pull request by bosilca**
Fix a comment in the MCA header.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by jsquyres** [comment]
RM's discussed on 19 June: looks like some of this is a set of new features, but it looks like there are some bug fixes, too (i.e., don't pass the address of a stack variable into registration).  @hppritcha will make a new PR with just the bug fixes from this PR.

**Comment by jsquyres** [comment]
@hppritcha will also need to check the v3.x branch.

**Comment by bosilca** [comment]
These are not new features, but they have been lost with the transition to the new MCA system. I merely brought them back.

**Comment by jsquyres** [comment]
Fair enough -- but they're "new" to the 2.x branch, right?  If so, we probably have to forego them here (since they're a "new" feature to v2.1.x.).

**Comment by bosilca** [comment]
There was a user complain on the mailing list that made me look into this. I have no idea when we lost the capability to dynamically change the collective, but you might be right, it might be a "new" feature in the 2.x.

I have no strong feeling for the v2.x, but I would rather have this capability in the 3 series.

**Comment by bwbarrett** [comment]
I'm ok with the patch in 3.x when there's a CR for that.

**Comment by hppritcha** [comment]
A subset of this PR will be pulled in to 2.x

**Pull request closed without merging**
