### PR TITLE
Attempt to reduce the RARP traffic during definition of allocations

### PR DESCRIPTION
**Pull request by rhc54**
@jsquyres @miked-mellanox would you please review and see if this helps reduce the lookup traffic?

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 923 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_355/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_355/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_355/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/355/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 923 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_357/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_357/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_357/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/357/
Test PASSed.

**Comment by miked-mellanox** [comment]
@elenash, @nkogteva - while testing this patch with hello_c app on 64k ranks - got following errors:
``` shell
OPAL ERROR: Data unpack would read past end of buffer in file pmix_native.c at line 574
ORTE_ERROR_LOG: Out of resource in file grpcomm_brks.c at line 122
```

and the stacktrace was:

``` shell
Thread 4 (Thread 0x7f8363be1700 (LWP 33763)):
#0  0x00007f8365ae8513 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f836550513c in epoll_dispatch (base=0x658d00, tv=<optimized out>) at epoll.c:407
#2  0x00007f836550a326 in opal_libevent2022_event_base_loop (base=0x658d00, flags=<optimized out>) at event.c:1627
#3  0x00007f83654d232e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:89
#4  0x00007f8365d8c806 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f8365ae7e8d in clone () from /lib64/libc.so.6
#6  0x0000000000000000 in ?? ()
Thread 3 (Thread 0x7f83633e0700 (LWP 33801)):
#0  0x00007f8365ae8513 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f836550513c in epoll_dispatch (base=0x6b0a0e0, tv=<optimized out>) at epoll.c:407
#2  0x00007f836550a326 in opal_libevent2022_event_base_loop (base=0x6b0a0e0, flags=<optimized out>) at event.c:1627
#3  0x00007f83654d232e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:89
#4  0x00007f8365d8c806 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f8365ae7e8d in clone () from /lib64/libc.so.6
#6  0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7f835e0e1700 (LWP 33820)):
#0  0x00007f8365ae8513 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f835e3cefbc in mxm_async_thread_func (arg=<optimized out>) at mxm/core/async.c:316
#2  0x00007f8365d8c806 in start_thread () from /lib64/libpthread.so.0
#3  0x00007f8365ae7e8d in clone () from /lib64/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 1 (Thread 0x7f8366472700 (LWP 33736)):
#0  0x00007f8365ab4b1d in nanosleep () from /lib64/libc.so.6
#1  0x00007f8365ae1a54 in usleep () from /lib64/libc.so.6
#2  0x00007f8363be70fa in native_fence (procs=0x7fff1c72648e, nprocs=0) at pmix_native.c:569
#3  0x00007f8365fe762d in ompi_mpi_init (argc=1, argv=0x7fff1c726788, requested=<optimized out>, provided=0x7fff1c726574) at runtime/ompi_mpi_init.c:632
#4  0x00007f8365ffb9c9 in PMPI_Init (argc=0x7fff1c72659c, argv=0x7fff1c726590) at pinit.c:84
#5  0x00000000004008c7 in main (argc=1, argv=0x7fff1c726788) at hello_c.c:18
```

**Comment by rhc54** [comment]
I see the issue here - I'll fix it. Sorry about that - it didn't show in my tests

**Comment by rhc54** [comment]
This seems to be working okay for me, but I'm only testing the recursive doubling grpcomm component and I note that you saw the error in the brucks component. I'll have to let you test that one.

**Comment by nkogteva** [comment]
@rhc54 let me fix it. I already have prepared fix for grpcomm components. I need to test it in the large scale.

**Comment by rhc54** [comment]
Thanks!

**Comment by mellanox-github** [comment]
* Coverity found 923 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_359/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_359/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_359/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/359/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 923 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/all_360/output/errors/index.html

* Coverity found 11 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/oshmem_360/output/errors/index.html

* Coverity found 2 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-master-pr//ws/cov_build/fca_360/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/360/
Test PASSed.

**Comment by miked-mellanox** [comment]
with latest patch from @rhc54 and grpcomm_v2.patch from @nkogteva - it works fine and took 1m30s to launch on 64k processes. very nice! thanks guys!

**Comment by rhc54** [comment]
I'll go ahead and merge this change, then, as the grpcomm patch is a separate issue

**Comment by goodell** [comment]
minor Q on the commit message here:
> Attempt to reduce the RARP traffic during definition of allocations

Are you actually trying to reduce *RARP* traffic?  Is someone still using [RARP](http://en.wikipedia.org/wiki/Reverse_Address_Resolution_Protocol) these days?  I thought that was totally obsoleted by DHCP and other protocols.

**Pull request merged**
