### PR TITLE
small typo corrections

### PR DESCRIPTION
**Pull request by WiltonLoch**
Just some small typo corrections in the coll component files

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@WiltonLoch thank you very much for this PR (and being gracious enough to qualify some of these typos as "small").

All commits have to be signed-off in order to be accepted.
Once you understand the implications (I am not a lawyer and hence cannot advise on that topic), you can
`git commit --amend -s`
and then
`git push --force ...`
in order to update this PR

**Comment by WiltonLoch** [comment]
Thank you for the information, update done!

**Comment by ggouaillardet** [comment]
Thanks!

ok to test

@jsquyres the signed off line contains the login name instead of the full name (it is trivial to retrieve the full name from the login name and/or the email address though). Does this meet our requirements?

**Comment by jsquyres** [comment]
> @jsquyres the signed off line contains the login name instead of the full name (it is trivial to retrieve the full name from the login name and/or the email address though). Does this meet our requirements?

IANAL, but I think it's fine.

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
