### PR TITLE
timer/aix: remove stale code

### PR DESCRIPTION
**Pull request by jsquyres**
Per discussion on the mailing list and with IBM, remove the AIX timer code (since AIX is no longer supported). 

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

@gpaulsen @jjhursey I created this PR solely to make sure we talk about it (per @PHHargrove's mail http://www.open-mpi.org/community/lists/devel/2016/05/18934.php).  If you guys still want this AIX component, I'll close this PR without merging.

### CODE REVIEW

**Comment by jsquyres** [comment]
Per 2016-05-10 call, IBM is still in process of checking.  If IBM cares, we may have to disable this for v2.0.0 release anyway (becaseu it doesn't compile).

**Comment by PHHargrove** [comment]
@jsquyres 
The 2.0.0rc2 tarball did not build for me on AIX.
However, this timer code was not the cause of the problem(s) - just the motivation for even trying.
I am sorry if my list posting was not clear on what was broken.

**Comment by jsquyres** [comment]
@PHHargrove Thanks; good to know.

So: @gpaulsen @jjhursey it may be a bit more work to get things going on AIX than just fixing the timer code.

**Comment by gpaulsen** [comment]
Thanks, we're having internal discussions, and I will update after talking to all of the interested parties.

**Comment by PHHargrove** [comment]
@gpaulsen 
Do you think it is worth me starting the process of determining how badly things are broken on AIX?
My first round of tests had stopped short of getting a complete build.

**Comment by gpaulsen** [comment]
Well, I got back the word that IBM is not interested in investing resources into Open MPI on P7 under AIX at this time.  Sorry.

**Comment by jsquyres** [comment]
Roger.  I'll merge this PR, which removes `timer/aix`.

**Comment by PHHargrove** [comment]
gpaulsen wrote:
> [...] IBM is not interested in investing resources into Open MPI on P7 under AIX at this time [...]

That's good because my attempts at building there show things are pretty badly broken.

**Pull request merged**
