### PR TITLE
ROMIO 3.4.1 refresh

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by gpaulsen** [comment]
@markalle Are your patches in this refresh?

**Comment by markalle** [comment]
I'd still like for some of the commits here to become part of the mpich codebase.  Eg I'm sure that modernization commit would go in pretty easy.  And I bet some of the OMPI patch commit could be #ifdef in a way that would work for both projects, like where it sets/clears errhandlers differently I guess based on OMPI having a different load/unload location for using romio.

But I think the main thing everybody's wanting from me is that list of MPICH commits and whether they're represented here.  So the good news is they're all at least completely checked in to MPICH's "main" branch now, so we're at least not stuck waiting for anything more at that level.  I don't think any of them are in romio 3.4 unfortunately and thus aren't represented here, they're just in mpich "main".

And here's the list (of PRs, some of which contain multiple commits):
*** https://github.com/pmodels/mpich/pull/4943  --  darray fix which contains a flatten fix, this is all the main functional changes that apps like HDF5 were hitting
*** https://github.com/pmodels/mpich/pull/4995  --  write strided fix, I can't remember which app hit this, but it was found "in the wild" by a real app somewhere too
*** https://github.com/pmodels/mpich/pull/5100  --  build fix for -Wpedantic
*** https://github.com/pmodels/mpich/pull/5099  --  build fix, they had let --with-file-system=...gpfs bit rot
*** https://github.com/pmodels/mpich/pull/5150  --  build fix, configure-related _GNU_SOURCE
*** https://github.com/pmodels/mpich/pull/5184  --  build fix, continuation of _GNU_SOURCE fix

So I'm thinking I should just make another PR added on top of this one to reflect all the above additions.  It actually shouldn't take real long now that I've gone back and looked up all the PRs.  Getting stuff like that organized is most of the battle.

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2cac31ac8c48da2554c089095605aec3

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/06c2a0ba433ca56f7f25034d06f8a2c6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a1bd47d6d8d8f2631996b916838d921c

**Comment by markalle** [comment]
@ggouaillardet
Looks like one of the new mpich PRs needs the same modernization change you made for the rest of romio:
https://github.com/ggouaillardet/ompi/pull/6

**Comment by gpaulsen** [comment]
@ggouaillardet Any time to look at @markalle's comment?  Love to get this into master soon.

Thanks,
 Geoff

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8989f9e5bf0d0dfd2c5ce5289a26ed2a

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/07985725cda3be985b9e71ab4c5072d0

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6e9e1c3a7819e2bbec48ebb09bc439a0

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9e9a320b174431fe1c4a6d3fdd820842

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5a33ba5b3bb640688f9631cf229ce37e

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2e8751b5ce3e8e8da22f66b88671d111

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5eb4f03c5dcdf5b6b9c789db7a6b4b3a

**Comment by ggouaillardet** [comment]
:bot:as:retest

**Comment by ggouaillardet** [comment]
:bot:aws:retest

**Comment by ggouaillardet** [comment]
@gpaulsen I think this PR is now ready for prime time!

My apologies for the delay, I have been unfortunately unable to spare more time than I hoped for Open MPI...

@markalle I could not figure out some paperwork, so I am afraid my contributions to MPICH won't be accepted.

That being said, I prepared a commit for MPICH at https://github.com/ggouaillardet/mpich/commit/055562718e685fcbe2e3b08fff9c3a48bc76d9e1.patch
Feel free to make yourself the author and submit it upstream.

**Review by markalle — APPROVED** [review]

**Pull request merged**
