### PR TITLE
Update PRRTE and PMIx

### PR DESCRIPTION
**Pull request by rhc54**
- ensure we return timeout error status
- lots of various bug fixes

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@artemry-mlnx We seem to be getting stuck in PRRTE's autogen.pl, but I cannot replicate on any machine of mine. I seem to recall we have seen this before and it was due to some filesystem problem over there? Could you please take a look?

**Comment by artemry-mlnx** [comment]
@rhc54 
Enabled backup agents and re-started CI.
Looks like it's similar issue (with particular CI agent) we observed some time ago - I'll check this.

**Comment by rhc54** [comment]
@artemry-mlnx Thanks!!

**Pull request merged**
