### PR TITLE
update openpmix/prrte pointer

### PR DESCRIPTION
**Pull request by wzamazon**
Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
Looks like internal Mellanox CI errors.  I've pinged @janjust.

**Comment by janjust** [comment]
@jsquyres  docker registry is under maintenance, CI is affected

**Comment by wzamazon** [comment]
Looks like all tests have passed. Can I get a review?

**Review by janjust — APPROVED** [review]

**Pull request merged**
