### PR TITLE
Fixed completion for unused request

### PR DESCRIPTION
**Pull request by EmmanuelBRELLE**
This patch may be open for discussion : I am quite new to the topic of Generalized requests.
It seems allowed to start a generalized request and completing it without using it. This is what one of our test do to check basic functionality.
In this case, the started request is created with 'REQUEST_COMPLETED' as req_complete member. However ompi_request_complete do not handle such a tag in the input request.

### CODE REVIEW

**Comment by bosilca** [comment]
I am not sure what you means by start and complete without using for generalized requests. You need to use it in order to have it queried (and thus completed). What is the sequence of MPI calls your test is doing?

**Comment by awlauria** [comment]
ok to test

**Comment by EmmanuelBRELLE** [comment]
> I am not sure what you means by start and complete without using for generalized requests. You need to use it in order to have it queried (and thus completed). What is the sequence of MPI calls your test is doing?

```
int query_called = 0;
int query_fn(  void * extra_state, MPI_Status * status )
{
    query_called = 1;
    return MPI_SUCCESS;
}

int free_called = 0;
int free_fn( void * extra_state )
{
    free_called = 1;
    return MPI_SUCCESS;
}

int main( int argc, char **argv ){
    MPI_Init( &argc, &argv );
    MPI_Request my_req;
	
    int param = 0;
    MPI_Grequest_start( query_fn, free_fn, NULL, (void*)&param, &my_req );
    MPI_Grequest_complete( my_req );

    MPI_Status status;
    MPI_Wait( &my_req, &status );

    if(!query_called||!free_called )
    {
        printf("Error free or querry were not called\n");
        abort();
    }
    MPI_Finalize();
}
```
Do you mean this code is incorrect in terms of MPI specifications ?

**Comment by bosilca** [comment]
This code looks good to me, the grequest is started and waited upon, so both the query (which gets the status) and the free (which release the request) are called. Your example works with 115b594a0e.

**Comment by EmmanuelBRELLE** [comment]
Indeed you submitted a patched earlier this year that fix my issue : 434a2515f
Sorry for the  waste of time.

**Pull request closed without merging**
