### PR TITLE
V4.0.x: oshmem/ucx: improves spml ucx performance for multi-threaded applications.

### PR DESCRIPTION
**Pull request by janjust**
Improves multi-threaded performance by adding the option to create
multiple ucx workers in threaded applications.

Co-authored with:
Artem Y. Polyakov <artemp@mellanox.com>,
Manjunath Gorentla Venkata <manjunath@mellanox.com>

Signed-off-by: Tomislav Janjusic <tomislavj@mellanox.com>
(cherry picked from commit 3d6bf9f)

### CODE REVIEW

**Comment by janjust** [comment]
FYI @artpol84 @jladd-mlnx @yosefe 

The v4.0.x multi-worker PR (need to wait for #7327 to go in before merging this PR)

**Comment by gpaulsen** [comment]
@janjust Once we merge in #7327 will we need to rebase this PR, or just re-test?
And is that the only reason the LABEL:WIP_DNM! is on this PR or is there another reason?

**Comment by janjust** [comment]
@gpaulsen We’ll need to rebase, and yes that’s the only reason LABEL:WIP_DNM! is on this PR.

**Comment by janjust** [comment]
@artpol84 please note, this PR has an additional commit from #7333 that fixes the coverity issues.

**Comment by janjust** [comment]
@artpol84, @jladd-mlnx  Just fyi, this PR needs the commit from #7332

**Comment by artpol84** [comment]
@hoopoepg we should have someone from UCX originally on #7274, 
please have a look at this one.

**Comment by janjust** [comment]
@jladd-mlnx @gpaulsen @hppritcha 
PR Rebased, ready to go

**Pull request merged**
