### PR TITLE
Cleanup handling of OPAL_PREFIX vs PMIX_INSTALL_PREFIX

### LINKED ISSUE #3980: OMPI v3.0: pmix install dirs info is not propagated to orteds
### Open MPI version

gitclone ompi v3.0.x (2f13cce)

## Details of the problem

If OMPI installation is moved to a different location `OPAL_PREFIX` env var is used to identify that and `installdirs/env`  is handling this correctly.
PMIx also has MCA infrastructure and similar installdirs component. in PMIx `PMIX_INSTALL_PREFIX` playing the role of `OPAL_PREFIX`. The important difference is that `OPAL_PREFIX` is an OMPI variable and it gets propagated to orte daemons, i.e.:
```
[cn01:17570] [[10714,0],0] plm:rsh: final template argv:
/usr/bin/ssh <template> \
	OPAL_PREFIX=<ompi-path>/ompi-v3.0.x ; export OPAL_PREFIX; \
	PATH=<ompi-path>/ompi-v3.0.x/bin:$PATH ; export PATH ; \
	LD_LIBRARY_PATH=<ompi-path>/ompi-v3.0.x/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; \
	DYLD_LIBRARY_PATH=<ompi-path>/ompi-v3.0.x/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   \
	<ompi-path>/ompi-v3.0.x/bin/orted -mca orte_debug_daemons "1" -mca ess "env" -mca ess_base_jobid "702152704" \
	-mca ess_base_vpid "<template>" -mca ess_base_num_procs "2" -mca orte_node_regex "cn01,cn02@0(2)" \
	-mca orte_hnp_uri "702152704.0;tcp://<IP1>,<IP2>;ud://<UD>" -mca coll_hcoll_enable "1" -mca pml "yalla" \
	--mca plm_base_verbose "100" -mca plm "rsh" -mca rmaps_base_mapping_policy "node" \
	-mca hwloc_base_binding_policy "core" -mca rmaps_base_display_map "1"
```
As it can be seen there `PMIX_INSTALL_PREFIX` is not propagated so orteds are failing with:
```
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    listener-thread-start
But I couldn't open the help file:
    <OLD-INSTALLATION_PATH>/ompi-v3.0.x/share/pmix/help-pmix-server.txt: No such file or directory.  Sorry!
```
Because they can't find PMIx mca ptl components.

### PR DESCRIPTION
**Pull request by rhc54**
Do a better job of detecting mismatches between location directives for OPAL and PMIx. Provide a more helpful error message and error out if we find a mismatch. If any OPAL values are set and the PMIx equivalent is not, then transfer it.

Update to track PMIx v2.0.1rc

Fixes #3980
Closes #4007
Closes #3985

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@bwbarrett This replaces the prior PR on the matter, and represents a rollup of all the discussion and proposed changes. Sorry for the confusion.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/40e76ee2ddf9bc2b93c53c656874df75

**Comment by jjhursey** [comment]
I think the pgi failure might have been a file system issue. Let's retry.
bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/548f9d030235992401b4dbc9551a3cc3

**Comment by jjhursey** [comment]
Humm the PGI compiler thing might be real. It looks like the `pmix2x` component's configure is failing in it's asm test. I'm wondering if we missed something from upstream when we ported it back to PMIx. I'll get some more information after the call.

**Comment by rhc54** [comment]
Hmmm...let me check. I updated asm in PMIx master, but I bet the changes weren't ported to the branch prior to making this update.

**Comment by jjhursey** [comment]
Here is a capture of the configure output from `opal/mca/pmix/pmix2x/pmix`:
```shell
*** Assembler
checking dependency style of pgcc... pgcc
checking for perl... /usr/bin/perl
checking for __atomic builtin atomics... no
checking for processor support of __atomic builtin atomic compare-and-swap on 128-bit values... no
checking for __atomic builtin atomic compare-and-swap on 128-bit values with -mcx16 flag... no
checking for __sync builtin atomics... no
checking for 64-bit __sync builtin atomics... no
checking for processor support of __sync builtin atomic compare-and-swap on 128-bit values... no
checking for __sync builtin atomic compare-and-swap on 128-bit values with -mcx16 flag... no
configure: error: __sync builtin atomics requested but not found.
```

**Comment by rhc54** [comment]
I just checked and the atomics on the PMIx v2.0 branch matches the PMIx master, so it looks like something from OPAL didn't come over?

**Comment by rhc54** [comment]
I didn't find any substantive change in OPAL atomics that was missing from PMIx master. However, the opal_config_asm.m4 did change - notably, it removed that error line! So I'm guessing that is the "issue" here. I'm updating PMIx master and will bring it across to the PMIx 2.0 branch so it can land here.

**Comment by rhc54** [comment]
Wait a minute - we have PR #3757 waiting which adds that error so we abort, and folks indicate they want that behavior. So I'm guessing that PMIx is actually up-to-date minus the recent renaming of the opal_atomic_init stuff (which we'll pickup in the next round when something substantive changes in the atomics). So whatever it is, it looks like there actually is something broken in the PGI-based atomics

**Comment by artpol84** [comment]
@rhc54 should https://github.com/open-mpi/ompi/commit/71da0fcbef3e19e2c2f10fcc15da83229112a0e0 go here then?

**Comment by artpol84** [comment]
Or it is not needed anymore?

**Comment by rhc54** [comment]
We should probably revert 71da0fc from master to be consistent - we want to handle the OPAL_PREFIX case for the internal PMIx code, but leave anything else alone.

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/567f7456831e9709c3b42ddac4bbc679

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f4741098cb0accf6e4aab81d27dd1357

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b9a584373d3412b3992d81fc76fbd061

**Comment by rhc54** [comment]
MTT results:
```
+-------------+-----------------+-------------+----------+------+------+----------+------+---------------------------------------------------------------------------+
| Phase       | Section         | MPI Version | Duration | Pass | Fail | Time out | Skip | Detailed report                                                           |
+-------------+-----------------+-------------+----------+------+------+----------+------+---------------------------------------------------------------------------+
| MPI Install | my installation | 3.0.0rc3    | 00:00    | 1    |      |          |      | MPI_Install-my_installation-my_installation-3.0.0rc3-my_installation.html |
| Test Build  | trivial         | 3.0.0rc3    | 00:02    | 1    |      |          |      | Test_Build-trivial-my_installation-3.0.0rc3-my_installation.html          |
| Test Build  | ibm             | 3.0.0rc3    | 00:48    | 1    |      |          |      | Test_Build-ibm-my_installation-3.0.0rc3-my_installation.html              |
| Test Build  | intel           | 3.0.0rc3    | 01:19    | 1    |      |          |      | Test_Build-intel-my_installation-3.0.0rc3-my_installation.html            |
| Test Build  | java            | 3.0.0rc3    | 00:02    | 1    |      |          |      | Test_Build-java-my_installation-3.0.0rc3-my_installation.html             |
| Test Build  | orte            | 3.0.0rc3    | 00:01    | 1    |      |          |      | Test_Build-orte-my_installation-3.0.0rc3-my_installation.html             |
| Test Run    | trivial         | 3.0.0rc3    | 00:06    | 8    |      |          |      | Test_Run-trivial-my_installation-3.0.0rc3-my_installation.html            |
| Test Run    | ibm             | 3.0.0rc3    | 10:05    | 508  |      |          |      | Test_Run-ibm-my_installation-3.0.0rc3-my_installation.html                |
| Test Run    | spawn           | 3.0.0rc3    | 00:09    | 7    |      |          | 1    | Test_Run-spawn-my_installation-3.0.0rc3-my_installation.html              |
| Test Run    | loopspawn       | 3.0.0rc3    | 10:06    | 1    |      |          |      | Test_Run-loopspawn-my_installation-3.0.0rc3-my_installation.html          |
| Test Run    | intel           | 3.0.0rc3    | 16:42    | 474  |      |          | 4    | Test_Run-intel-my_installation-3.0.0rc3-my_installation.html              |
| Test Run    | intel_skip      | 3.0.0rc3    | 12:59    | 431  |      |          | 47   | Test_Run-intel_skip-my_installation-3.0.0rc3-my_installation.html         |
| Test Run    | java            | 3.0.0rc3    | 00:01    | 1    |      |          |      | Test_Run-java-my_installation-3.0.0rc3-my_installation.html               |
| Test Run    | orte            | 3.0.0rc3    | 00:43    | 19   |      |          |      | Test_Run-orte-my_installation-3.0.0rc3-my_installation.html               |
+-------------+-----------------+-------------+----------+------+------+----------+------+---------------------------------------------------------------------------+


    Total Tests:    1455
    Total Failures: 0
    Total Passed:   1455
    Total Duration: 3183 secs. (53:03)
```

**Pull request merged**
