### PR TITLE
arm64: add timer support

### PR DESCRIPTION
**Pull request by abjoshi-brcm**

### CODE REVIEW

**Comment by jsquyres** [comment]
@bosilca @hjelmn Can you have a look?

**Comment by hjelmn** [comment]
Looks great to me. @abjoshi-brcm Please update the AUTHORS file with your info.

**Comment by hjelmn** [comment]
I should also add that you probably want to add your copyright at the top of the changed files.

**Comment by hjelmn** [comment]
Will merge once the author updates the AUTHORS file and copyrights.

**Comment by bosilca** [comment]
Looks good.  :+1:

**Comment by abjoshi-brcm** [comment]
Hi,
Updated the Copyrights and Authors file

**Comment by hjelmn** [comment]
Great. Thanks!

**Comment by shamisp** [comment]
Since I have been working on a similar issue in the context of openucx/ucx I will add my $0.02.
I used ISB instruction to ensure the order https://github.com/openucx/ucx/blob/master/src/ucs/arch/aarch64/cpu.h#L34

**Pull request merged**
