### PR TITLE
contrib/lanl: update platform files for TOSS2

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@hppritcha This is what I recommend for updating the platform files. For one we no longer have panasas so renamed to use lustre... Not that any of our users use MPI/IO.

**Comment by hjelmn** [comment]
Oh, I also removed the nopanasas files. There is no reason to keep an extra set around that only disable the PFS.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
hah, have to update the Makefile.am's.

**Comment by hppritcha** [comment]
:+1:

**Comment by hjelmn** [comment]
Ok, will PR to v1.10 and v2.x.

**Pull request merged**
