### PR TITLE
cray ftn: modify fortran module loc checker

### PR DESCRIPTION
**Pull request by hppritcha**
to support the Cray Fortran compiler.  Cray Fortran compiler does not
contain all symbol info in the module file, have to link with the *.o
created as part of module file compilation.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
Could a compiler choose **not** to emit a `.o` file if there is no code in it?

**Comment by jsquyres** [comment]
> Could a compiler choose **not** to emit a `.o` file if there is no code in it?

The module in question has a variable instance in it -- so I think something must be emitted, right?

**Comment by hppritcha** [comment]
@ggouaillardet has a point.  I'll rework to check for case of a .o or not.

**Comment by jsquyres** [comment]
A few lines above your code, there's this:

```
OPAL_LOG_COMMAND([$FC $FCFLAGS $FCFLAGS_f90 -c conftest-module.f90 $LDFLAGS $LIBS] ...
```

The `-c` means that a `.o` _must_ be emitted, right?

**Comment by hppritcha** [comment]
@jsquyres and @ggouaillardet I could see that there might be some weird compiler that only emits a *.mod for this simple example.  I tweaked the code some to try both with and without a *.o.

**Comment by hppritcha** [comment]
cori is again discomfited
bot:ompi:retest

**Comment by jsquyres** [comment]
@hppritcha I made a minor code suggestion in a new commit on this PR.  Feel free to squash or discard.

**Comment by hppritcha** [comment]
bot:ompi:retest

**Pull request merged**
