### PR TITLE
Formatting fixes for Java files.

### PR DESCRIPTION
**Pull request by nrgraham23**
White space changes only (except few comments)

Fixed tab indenting as well as some of the block comments
at the top of a few of the files.

Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>

@hppritcha  @jsquyres

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
the lanl -cray xc didn't like the java.  

JAVAC    MPI.class
../../../../ompi/mpi/java/java/MPI.java:1001: error: illegal start of type
	=======
	^
../../../../ompi/mpi/java/java/MPI.java:1001: error: ';' expected
	=======
	  ^
../../../../ompi/mpi/java/java/MPI.java:1001: error: illegal start of type
	=======
	    ^
../../../../ompi/mpi/java/java/MPI.java:1001: error: <identifier> expected
	=======
	      ^
../../../../ompi/mpi/java/java/MPI.java:1001: error: ';' expected
	=======
	       ^

**Comment by nrgraham23** [comment]
Yeah.  It seems there was a larger issue with a conflict than I at first realized.  Working on fixing the issue now.

**Comment by hppritcha** [comment]
looks good, official eclipse way.

**Pull request merged**
