### PR TITLE
Fix PMI and PMI2 builds

### PR DESCRIPTION
**Pull request by nysal**
@rhc54 please review

### CODE REVIEW

**Comment by rhc54** [comment]
wow - how did that slide thru? thx!

**Comment by rhc54** [comment]
:+1:

**Comment by nysal** [comment]
Same issue exists in v2.x. I'll open a PR.

**Comment by rhc54** [comment]
Thanks! Does it also exist in the 1.10 series?

**Comment by nysal** [comment]
1.10 seems to be alright. I did not build and verify though, just took a quick look at the code.

**Pull request merged**
