### PR TITLE
v3.1.x: Fix incorrect behavior with length == 0

### LINKED ISSUE #6575: Possibly, incorrect MPI_Type_indexed behavior with zero blockLenght
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
compiled from source, git clone open-mpi/ompi/master

### Please describe the system on which you are running

* Operating system/version: RHEL 7.4 
* Computer hardware: x86
* Network type: n/a

-----------------------------

## Details of the problem
Consider the test case:
```
#include <mpi.h>
#include <stdio.h>

int main (int argc, char **argv) {
    int rank, size;
    MPI_Datatype dtype;
    int dt_count = 1;
    int pBlockLength[1] = {0};
    int pDisps[1] = {0};
    MPI_Aint lb, extent;

    MPI_Init(&argc, &argv);

    MPI_Type_indexed(dt_count, pBlockLength, pDisps, MPI_DOUBLE_COMPLEX, &dtype);
    MPI_Type_commit(&dtype);
    MPI_Type_get_extent(dtype, &lb, &extent);

    printf("lb: %llu, extent %llu\n",
           (long long unsigned)lb, (long long unsigned)extent);
    MPI_Finalize();
}
```
Compile and run on a single node:
```
mpicc mpi_create_indexed.c -g -o mci
mpirun -np 1 ./mci
lb: 9223372036854775807, extent 1
```

In this test user creates an Indexed dtype with count = 1 and pBlockLength[0] = 0;
The resulting dtype has huge LB  and extent = 1. I would expect this dtype to have LB=UB=TRUE_UB=TRUE_LB=EXTENT=0. 

1. Do i understand correctly that the test is MPI spec compliant ? From the spec i read that the entries of pBlockLength have to be non-negative. So all looks legit. 
2. Do you agree that the resulting dtype must have zero extent and lb,ub?
3. MPICH handles this case this way: [mpich_type_indexed](https://github.com/pmodels/mpich/blob/66218a1a6ab2f58e6fd1c5eef3968aa6ac32d76d/src/mpi/datatype/type_indexed.c#L158) So, the check if at least one entry of pBlockLength is non-zero and only then create the dtype otherwise mpich would return an empty type.

One more notice: i think that similar fallback logic in OMPI (for example, [here](https://github.com/open-mpi/ompi/blob/163bbd4f047df738bc96870cc8458e3c674febea/ompi/datatype/ompi_datatype_create_indexed.c#L81)) is incorrect. We create an empty dtype with:
```
ompi_datatype_add( *newType, &ompi_mpi_datatype_null.dt, 0, 0, 0);
```
which calls
```
opal_datatype_add( &pdtBase->super, &pdtAdd->super, count, disp, extent );
```
but if the count is set to 0 (like in this case) opal_datatype_add would just leave the newType uninitialized https://github.com/open-mpi/ompi/blob/98afc838aa53da88cba339f6dcbab256806a5745/opal/datatype/opal_datatype_add.c#L119.

### PR DESCRIPTION
**Pull request by bosilca**
Cherry-pick f68b06e9 on the 3.1.
Fixes #6575.

Signed-off-by: George Bosilca <bosilca@icl.utk.edu>

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:ompi:retest

**Comment by hppritcha** [comment]
bot:ompi:retest

USRC is having a network outage.

**Comment by jsquyres** [comment]
@ggouaillardet Can you please review?  This PR was just brought to my attention (it wasn't labeled / milestoned before moments ago)

**Comment by bwbarrett** [comment]
@ggouaillardet can you take a look?  we'd like to get going with a 3.1 update.

**Comment by jsquyres** [comment]
We need a review for this.  We're looking to make a 3.1RC1 in the immediate future.  Can someone review?

**Comment by jsquyres** [comment]
Unless we get an immanent review for this, it won't be included in v3.1.6.

**Pull request merged**
