### PR TITLE
opal static mutex initializers

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca, @jsquyres please take a look.

Some time ago I asked for this support for MPI_T but we chose not to add it because we supported non-posix mutexes. That is no longer the case so we might as well add them.

It might also be worth considering adding an equivalent to pthread_once.

**Comment by hjelmn** [comment]
I may remove the debug initializers since they only set some members to 0. This is already guaranteed by the C standard if the variable being initialized has global or file scope.

**Comment by jsquyres** [comment]
:+1:

**Comment by hjelmn** [comment]
One change. Some platforms define PTHREAD_RECURSIVE_MUTEX_INITIALIZER and others use PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP. Added support for the later.

**Pull request merged**
