### PR TITLE
v5.0.x: Update PMIx v4.2 submodule and update PRRTe to use v3.0 branch

### PR DESCRIPTION
**Pull request by awlauria**
I separated out the pmix/prte updates into seperate commits.

No changelog for prrte since it branched off of master, and comparing v2.1 to v3.0/master isn't worth untangling.

bot:notacherrypick

### CODE REVIEW

**Review by jsquyres — APPROVED** [review]

**Comment by awlauria** [comment]
Forced pushed to fix a bad PR reference (point it to openpmix, not ompi).

**Comment by awlauria** [comment]
Will merge tomorrow assuming this passes CI.

That will give: https://github.com/open-mpi/ompi/pull/10611 a chance to run MTT overnight, since the v3.0 prrte branch is basically master right now.

**Comment by awlauria** [comment]
This should be good to go, but might be good to check the nightly mtt for main to make sure.

**Comment by rhc54** [comment]
@awlauria I have updated PRRTE v3.0 branch with yesterday's fixes fixes from the master branch, if you want to update this before merging.

**Comment by awlauria** [comment]
Adding the WIP label is these pointers need to be updated, and I believe we still need an update to main to fix a slurm issue.

**Comment by gpaulsen** [comment]
Holding off until we can get a fix for https://github.com/open-mpi/ompi/issues/10641

**Comment by gpaulsen** [comment]
closes #10664

**Comment by awlauria** [comment]
bot:ibm:retest

**Pull request merged**
