### PR TITLE
opal/pmix: Bring dstore fixes for rc3 testing

### PR DESCRIPTION
**Pull request by artpol84**
* https://github.com/pmix/pmix/pull/329/commits/14f865c4b631827fb99779d42eaf0567f117a76f
* https://github.com/pmix/pmix/pull/329/commits/1b86a6e7ee99fc5969a0789a9905a4a2159a6dc0

Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54

**Comment by jjhursey** [comment]
@artpol84 Please update this `README` file with a link to the cherry-picked commits:
  * https://github.com/open-mpi/ompi/blob/v2.x/opal/mca/pmix/pmix112/README

If they ship OMPI before we ship PMIx this will be our record of what the difference might be.

**Comment by artpol84** [comment]
@jsquyres @jjhursey addressed.

**Comment by jsquyres** [comment]
CI took forever; this didn't make the nightly snapshot tonight.  I might go kick the snapshots after merging this to make another snapshot tonight...

**Comment by artpol84** [comment]
`CI took forever` - @jsquyres what do you mean? It seems to me that it finished in reasonable time.

**Comment by jsquyres** [comment]
I approved the PR around 3pm US Eastern time.  Travis wasn't finished by about 6:30-7pm US Eastern when I  had to go offline.  I checked again right around 9:30pm US Eastern, and it was done, but that was too late to merge it to get it into the nightly snapshots.  I kicked the nightly snapshots again after the first round finished (somewhere around 10:30-11pm US Eastern?), and I see that it finished making another 2.x nightly snapshot at 11:30pm US Eastern.

Regardless, Travis's really long CI times (~4+ hours, in this case) are somewhat annoying.

**Pull request merged**
