### PR TITLE
v4.1.x: iof/base: (try to) set the winsize to the pty of the spawned tasks

### PR DESCRIPTION
**Pull request by ggouaillardet**
This is a backport from the prrte project.
bot:notacherrypick

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

(back-ported from openpmix/prrte@795de884b71afe0cf6a8499bca02fb9e5f8320dd)

### CODE REVIEW

**Comment by jsquyres** [comment]
@ggouaillardet Could you put the reference to the stackoverflow question where this update came from?  That provides some useful context for why we would want this change.  Thanks!

https://stackoverflow.com/questions/68224156/get-terminal-window-size-in-an-c-c-mpi-application

**Comment by jsquyres** [comment]
@ggouaillardet Can you update the commit message on this one?  Thanks!

**Comment by ggouaillardet** [comment]
@jsquyres  done!

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
@ggouaillardet Can you apply the same to #9119?

**Pull request merged**
