### PR TITLE
Remove VampirTrace

### PR DESCRIPTION
**Pull request by bertwesarg**
@jsquyres @hppritcha This is it!

### CODE REVIEW

**Comment by jsquyres** [comment]
I'd say that once the merge build completes, this looks fine to me.  Thank you for splitting it into multiple commits; that definitely makes it easier to review.

**Comment by jsquyres** [comment]
@miked-mellanox Mike, do you know why this merge Jenkins build hasn't completed yet?  The PR was opened 8 hours ago.  When I click on the "details" link, it takes me to the jenkins page, but I'm not sure if it's telling me that it failed or is somehow still processing...?

**Comment by miked-mellanox** [comment]
yep, we upgraded ofed on the jenkins machine and it appeared in the middle of the job. 
sorry about that, will ask jenkins to retest

**Comment by miked-mellanox** [comment]
retest this please

**Comment by jsquyres** [comment]
@miked-mellanox Cool, thanks.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/186/
Test PASSed.

**Pull request merged**
