### PR TITLE
Removed text block from line 883 of README.

### PR DESCRIPTION
**Pull request by msbrowning**
Removed text block starting at line 883 from README.
Removed extension directory ompi/mpiext/cr.

#hacktoberfest

Signed-off-by: Mark Browning <marksbrowning3@gmail.com>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
thanks for the PR!

could you please reword the commit message (it is really about removing the `cr` extension and not so much about updating the `README`).

**Comment by jsquyres** [comment]
ok to test

**Comment by msbrowning** [comment]
@ggouaillardet Done. Thanks for the feedback.

**Comment by jsquyres** [comment]
bot:ompi:retest

**Pull request merged**
