### PR TITLE
configure: detect UCX support by default

### PR DESCRIPTION
**Pull request by karasevb**
Adds detecting UCX from following paths: "/usr /usr/local /opt/ucx"

Signed-off-by: Boris Karasev <karasev.b@gmail.com>

### CODE REVIEW

**Comment by rhc54** [comment]
I can't really help you here as I don't have UCX on my systems

**Comment by jladd-mlnx** [comment]
@hppritcha can you have your student give this a spin, please?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f0f114ad6092fea29ce473c02aa8619a

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/eff8f5836006d86c583b8b8f82dac95c

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/2e251aec57361b78d479c7b5e0ff243f

**Comment by artpol84** [comment]
@hppritcha do you know if you'll be able to verify?

**Comment by hppritcha** [comment]
works for me (using pkg-config)

**Comment by artpol84** [comment]
@karasevb, please cherry-pick to v3.0.x

**Pull request merged**
