### PR TITLE
pr-checks: use reusable actions for commit checker and labeler

### PR DESCRIPTION
**Pull request by Joe-Downs**
An OMPI maintainer wanted the commit checker and labeler in two of their other repos. Instead of copying code, it's far easier to move the actions to separate repos and use them as reusable actions. They now live at:

https://github.com/open-mpi/pr-git-commit-checker
https://github.com/open-mpi/pr-labeler

This means any development on these (and new, future) actions can happen in their dedicated repos. Additionally, the actions can easily be used by anyone else on GitHub. For convenience's sake, the action calls here could also be setup to track a branch (such as v1) instead of the release (v1.0.0, as it is now). Therefore, if changes are made to the action upstream, it need not be updated here. However, right now, if OMPI wants to make use of upstream changes, the YAML needs to be changed here as well.

The functionality of the actions remains the same, but they are now called slightly differently, using inputs to pass config and the GITHUB_TOKEN secret into the actions. Instead of using JSON to make cherry picks required on other branches, you pass it in as an input.

Signed-off-by: Joe Downs <joe@dwns.dev>

### CODE REVIEW

**Comment by jsquyres** [comment]
@Joe-Downs Just to make sure: here on `main`, the git commit checker will not require cherry picks, but on the release branches (`v4.0.x`, `v4.1.x`, and `v5.1.x`), we'll pass an additional parameter in the YAML `with` section to have the git commit checker require cherry picks.  Is that correct?

**Comment by Joe-Downs** [comment]
Yes, that is correct. We'll add the line `cherry-pick-required: true` to the `with:` section. In fact, I was debating if we should also explicitly state `  cherry-pick-required: false` for `main`. The default value is false, but perhaps it would be better clarity-wise.

**Comment by bwbarrett** [comment]
This is awesome; did not know you could do that with GitHub actions.

**Comment by rhc54** [comment]
Agreed - awesome indeed! I'd love to see that in the PMIx and PRRTE repos as well.

**Review by jsquyres — APPROVED** [review]

**Comment by jsquyres** [comment]
> Yes, that is correct. We'll add the line `cherry-pick-required: true` to the `with:` section. In fact, I was debating if we should also explicitly state ` cherry-pick-required: false` for `main`. The default value is false, but perhaps it would be better clarity-wise.

As long as we document this parameter properly in a README.md in the source repo, I don't think we need to put an explicit `cherry-pick-required: false` here in the Open MPI `main` usage of it.

**Comment by jsquyres** [comment]
> Agreed - awesome indeed! I'd love to see that in the PMIx and PRRTE repos as well.

You already have this GitHub Marketplace Action on PMIx and PRTE `main` branches (via https://github.com/openpmix/openpmix/pull/2763 and https://github.com/openpmix/prrte/pull/1513).  Do you want @Joe-Downs to cherry pick them to various release branches (and therefore set `cherry-pick-required: true` on those release branches?

**Comment by rhc54** [comment]
Not necessary - I can easily do that myself. In fact, I already did it for PMIx. Easy enough to add the necessary line. Thx!

**Comment by jsquyres** [comment]
@Joe-Downs Can you please cherry-pick this PR to the Open MPI `v4.0.x`, `v4.1.x`, and `v5.0.x` branches?  Thank you!

**Comment by Joe-Downs** [comment]
Will do!

**Pull request merged**
