### PR TITLE
fix typo (distplacement -> displacement)

### PR DESCRIPTION
**Pull request by kokke**
Fixing typo (replacing distplacement with displacement)

EDIT:
The 'Signed-off-by checker' implies that this is needed:

Signed-off by kokke@github

### CODE REVIEW

**Comment by awlauria** [comment]
ok to test

**Comment by jsquyres** [comment]
Greetings @kokke -- thanks for the PR!

Yes, we require that all commits on Open MPI PR's contain the signed-off-by line, indicating your acceptance of the Open MPI contributors declaration: https://github.com/open-mpi/ompi/wiki/Administrative-rules#contributors-declaration.

Can you `git commit --amend -s` your commit to add the signed-off-by line to your commit message (not just the PR description), and then `git push --force ...` to push the amended commit up to your fork?  This will re-trigger the git commit checkers / etc.

Thank you!

**Comment by awlauria** [comment]
@kokke thanks for the change.

I assume this was a compile time failure. Not sure how this was getting past nightly checks...

**Comment by kokke** [comment]
Hi @jsquyres and thanks for the help - I tried committing an amended message and doing a forced push. I can't tell if I did it correctly (since the tests seemingly haven't re-run?) 🤔

@awlauria yes and no - I am testing a static analysis tool I wrote, which flagged this typo as a compile error. So it was found at compile-time, but not by a compiler.

I would guess you aren't compiling all variations of the code (compile-time conditionals/pre-processor directives/#ifdef's etc), if this error is not found in nightly checks 🤷‍♂️

**Comment by rhc54** [comment]
FYI: this is a ROMIO change - should go upstream

**Comment by jsquyres** [comment]
@kokke It doesn't look like your force push worked -- the new commit didn't end up at github (and therefore the CI tests didn't re-run, etc).

As @rhc54 pointed out ROMIO is effectively a 3rd party package to us.  We import it into Open MPI "by value", so to speak, for a variety of reasons.  You might also want to file a corresponding PR at the actual MPICH upstream: https://github.com/pmodels/mpich.

As for why we didn't run into this error, it looks like that part of ROMIO is only for the ancient-and-now-dead SGI MPI.  Hence, this is effectively dead code for Open MPI (i.e., we'll never compile that block).  Since SGI MPI is also dead, MPICH proper probably also doesn't compile this code.

**Comment by gpaulsen** [comment]
@kokke can we close this?

**Comment by awlauria** [comment]
Closed since this now has conflicts, and will need to be fixed in upstream romio. Thanks @kokke - can you port this over the mpich if you have not done so already?  https://github.com/pmodels/mpich

**Pull request closed without merging**
