### PR TITLE
Revert the MPI_Init fence operations to use volatile bool instead of thread macros

### PR DESCRIPTION
**Pull request by rhc54**
Refs https://github.com/pmix/pmix/issues/580

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by artpol84** [comment]
:+1: Fixes pmix/pmix#580

**Comment by artpol84** [comment]
Need this starting from 3.0.x

**Comment by rhc54** [comment]
Not really - it is only in master today

**Comment by artpol84** [comment]
I was using 3.0.x when I caught it.
And to test I cherry picked

**Comment by rhc54** [comment]
Don't know what to say - look at the v3.0.x branch code and you can clearly see that none of those thread lock code lines are present

**Comment by artpol84** [comment]
@rhc54 you are right, looks like I was working with the master instead of v3.0.x as I though. Sorry for the confusion.

**Pull request merged**
