### PR TITLE
osc/rdma: two bug fixes 

### PR DESCRIPTION
**Pull request by wzamazon**
fix two bugs in `allocate_state_shared` in osc/rdma/osc_rdma_component.c

### CODE REVIEW

**Review by bwbarrett — APPROVED** [review]

**Comment by wzamazon** [comment]
The GitHub Action CI failure is because I did not add a description in the PR. After I did that, the GitHub Action CI passed.

**Comment by wzamazon** [comment]
Is there anything else needed for this PR to get merged?

**Comment by bwbarrett** [comment]
I'd like @hjelmn to comment in case I was totally off in my review, even if he doesn't do a full review.

**Comment by wzamazon** [comment]
@hjelmn Do you have time to take a look?

**Comment by wzamazon** [comment]
@hjelmn Can you please take a look at this PR?

**Review by hjelmn — APPROVED** [review]

**Review by awlauria — APPROVED** [review]

**Comment by wzamazon** [comment]
Thanks! I will open a PR to back port to v5.0.x.

**Pull request merged**
