### PR TITLE
Revert "Fix a race condition between registering a callback and completing a request"

### PR DESCRIPTION
**Pull request by devreal**
This reverts commit b6467d0358ce758e80d67c793a6f1b3b7b1690b9 from https://github.com/open-mpi/ompi/pull/11460. The change breaks some persistent op implementations, which do not reinitialize the request object. @bosilca and I will bring this back with a consistent fix.

Fixes https://github.com/open-mpi/ompi/issues/11493

### CODE REVIEW

**Review by bosilca — APPROVED** [review]

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by dalcinl** [comment]
@jsquyres Can you please retest to move this one forward?

**Comment by bosilca** [comment]
bot:ibm:builds:retest

**Comment by jsquyres** [comment]
IBM's CI has been broken since this weekend.  I know they're still investigating.  

Let's talk about this PR on the webex today -- I think it might be worthwhile to merge it anyway, even before IBM's CI comes back, because we know that that PR's reverting of a prior commit (that, ironically, was merged even though there were CI failures) will enable Mellanox CI to pass.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
> Let's talk about this PR on the webex today -- I think it might be worthwhile to merge it anyway, even before IBM's CI comes back, because we know that that PR's reverting of a prior commit (that, ironically, was merged even though there were CI failures) will enable Mellanox CI to pass.

Scratch that.  IBM CI is back up and running 🎉 -- CI for this PR is queued up and will run shortly.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jsquyres** [comment]
> bot:ibm:retest

Thanks @jjhursey

**Pull request merged**
